### ISSUE TITLE
Dated folder?

### ISSUE THREAD

**Issue by DGMayor** [evilhero/mylar#1000]
So as of a version or two ago (development), I've had comics showing up in a dated folder in the root of my comics folder (so for example M:\Comics\2015-04-29)   These are duplicated from the normal series folders.

I can't figure out why this has started, and I see no option anywhere to create such a folder.

**Comment by evilhero** [comment]
There's an option on the weekly pullist page that asks to copy to dated folder - you need to uncheck it. It only copies issues from the Pull-list that have been post-processed successfully  and during a post-processing run (unless you click on the Download now button on the page)

**Comment by DGMayor** [comment]
Odd.  Don't recall ever checking that.  thanks
