### ISSUE TITLE
Pull List Broken 5/4/2015

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#1002]
I think something broke the pull list for this week.

http://pastebin.com/wrJj53ZT

**Comment by evilhero** [comment]
It looks like it's getting caught up on the Surface GN entry. Are you using the alt_pull method for the weekly pull list? 

You might have to pause / delete / set status to ended for that series until I can get a fix up.

**Comment by kev0153** [comment]
Yes I'm using the alt pull method

**Comment by evilhero** [comment]
I've tried to duplicate this several times but can't seem to replicate it at all - there shouldn't be a case where the 'GN' gets passed into the db as the Issue Number. I can fix the traceback error (it should be a break statement not a pass at the end of it, which causes the error), but if it's throwing in GN's instead of ignoring them, then that's going to cause future problems.

Are you on the latest development build ?

**Comment by kev0153** [comment]
I believe so yes

Version: b6b8c6293af8587ce03e9aeb7b74c96f95f9e111

**Comment by evilhero** [comment]
I'm just going to assume you also did the Recreate Pullist option recently?

**Comment by kev0153** [comment]
That's what caused it to throw the error.  I deleted the offending book
altogether and that solved it.

**Comment by evilhero** [comment]
Do you happen to have the ComicID of the series itself? I'm trying to figure out how that got in there, but haven't even been able to duplicate the error.

**Comment by kev0153** [comment]
Pretty sure this is it

http://www.comicvine.com/the-surface-1-gn/4000-435855/

4000-435855

**Comment by evilhero** [comment]
So, it's a Graphic Novel? That might explain things abit then, mylar doesn't full support Graphic Novels, although this one has an issue #, which would explain why it got added and matched on that issue then.

**Comment by kev0153** [comment]
Right there is an ongoing Image Series called The Surface, that is probably
why it tripped up.

**Comment by kev0153** [comment]
This is the image series

http://www.comicvine.com/the-surface/4050-80610/

This is in my list of comics to watch.  When I removed it all was good with
the world.  It might be that you can't reproduce it because you don't have
the above series in your list.
