### ISSUE TITLE
Manual PP deleting issues

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#1004]
Strange thing. On the latest Manual PP run, lots of files have just disappeared. No record of processing in logs and other files were processed fine.
The files were v3 and v4 of Alpha Flight and v1 Omega Flight. V1 and v2 were existing series.
So I figured I've accidentally deleted them and I re-download and place in PP folder. And again they just disappear, one by one as if they are being post processed.
Very strange and no log entries (that I can see)..

**Comment by ElementSixtySix** [comment]
All series are correctly labeled as v1, v2, v3, v4. Files are named (Alpha Flight v3 01.cbr)

**Comment by evilhero** [comment]
Try doing a manual post-processing run on just one issue (move it into another directory and point the manual post-processing at that specific folder). Once it's done, shutdown mylar and check the mylar.log file. Near or at the end of it you should see the post-processing logging.

**Comment by ElementSixtySix** [comment]
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] There are 2 files found that match on your watchlist, 2196 do not match anything and will be ignored.
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK] Duplicate check for D:\Mylar\v3\Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK] Existing Status already set to Downloaded
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK] Existing file :Alpha Flight 007 (1984).cbz has a filesize of : 30229266 bytes.
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [DUPECHECK] Based on duplication preferences I will retain based on : filesize
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK-FILESIZE PRIORITY] [#7] Retaining currently scanned in filename : Alpha Flight 007 (1984).cbz
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK] Duplicate check for D:\Mylar\v3\Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [POST-PROCESSING] [2/2] Starting Post-Processing for Alpha Flight issue: 7
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] issueid: 113391
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] issuenumOG: 7
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Zero Suppression set to : 00x
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Pretty Comic Issue is : 007
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Issue Year : 2004
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Publisher: Marvel
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Series: Alpha Flight
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Year: 2004
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Comic Location: K:\Comics\Marvel\Alpha Flight (2004)
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Comic Version: v3
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Not an annual - removing from filename parameters
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] New format: $Series $Issue ($Year)
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Metatagging enabled - proceeding...
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName:D:\Mylar
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] chkpath: D:\Mylar\v3
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] chkfile: Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Changing D:\Mylar location to D:\Mylar\v3 as it is a directory.
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Paths / Locations:
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] scriptname : Mylar.py
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] downloadpath : D:\Mylar\v3
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] sabnzbdscriptpath : K:\Mylar New
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] comicpath : D:\Mylar\v3\113391
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] unrar_folder : D:\Mylar\v3\113391\unrard
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Running the ComicTagger Add-on for Mylar
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Attempting to create directory @: D:\Mylar\v3\113391
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Created directory @ : D:\Mylar\v3\113391
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Filename is : D:\Mylar\v3\Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : D:\Mylar\v3\Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] moving : D:\Mylar\v3\Alpha Flight v3 07.cbr to D:\Mylar\v3\113391\Alpha Flight v3 07.cbr
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] zipfile detected
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Mylar.py: renaming Alpha Flight v3 07.cbr to be a cbz
06-May-2015 19:21:32 - INFO    :: FOLDERMONITOR : [META-TAGGER] Filename detected as a .cbz file.
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] filename : D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] This is a zipfile. Unable to test rar.
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Base set to : D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Moving : D:\Mylar\v3\113391\Alpha Flight v3 07.cbz - to - D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Verified file exists in location: D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Successfully removed temporary directory: D:\Mylar\v3\113391
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] new filename : D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Converted directory: D:\Mylar\v3\
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Converted filename: Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Destination path: D:\Mylar\v3\Alpha Flight v3 07.cbz
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName: D:\Mylar
06-May-2015 19:21:32 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] absDirName: D:\Mylar
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] ComicTagger 1.1.15-beta being used - using personal ComicVine API key supplied via mylar.
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] CR Tagging enabled.
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Will modify existing tag blocks even if it exists.
06-May-2015 19:21:33 - INFO    :: FOLDERMONITOR : [META-TAGGER] ComicRack tagging meta-tagging processing started.
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Enabling ComicTagger script: C:\Program Files (x86)\ComicTagger\comictagger.exe with options: ['-s', '--verbose', '-m', 'volume=3', '--cv-api-key', u'72f595aab1483d8ca63b8aaaf2f43c29cd9409e8', '-o', '--id', u'113391', '--type', 'cr', u'D:\\Mylar\\v3\\113391\\Alpha Flight v3 07.cbz']
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Executing command: ['C:\\Program', 'Files', '(x86)\\ComicTagger\\comictagger.exe', '-s', '--verbose', '-m', 'volume=3', '--cv-api-key', u'72f595aab1483d8ca63b8aaaf2f43c29cd9409e8', '-o', '--id', u'113391', '--type', 'cr', u'D:\\Mylar\\v3\\113391\\Alpha Flight v3 07.cbz']
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Absolute path to script: C:\Program
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [META-TAGGER][COMIC-TAGGER] : None
06-May-2015 19:21:33 - INFO    :: FOLDERMONITOR : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging
06-May-2015 19:21:33 - ERROR   :: FOLDERMONITOR : [META-TAGGER] Unable to move file from temporary path. Deletion of temporary path halted.
06-May-2015 19:21:33 - ERROR   :: FOLDERMONITOR : [META-TAGGER] attempt to move: D:\Mylar\v3\113391\Alpha Flight v3 07.cbz to D:\Mylar\v3\Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - INFO    :: FOLDERMONITOR : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Alpha Flight v3 07.cbz) - Continuing..
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] otofilename:D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] odir: D:\Mylar\v3\113391
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] ofilename: Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] path: Alpha Flight v3 07
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] ext:.cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Original Filename: Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Original Extension: .cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] New Filename: Alpha Flight 007 (2004)
06-May-2015 19:21:33 - INFO    :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: K:\Comics\Marvel\Alpha Flight (2004)
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Source: D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Destination: K:\Comics\Marvel\Alpha Flight (2004)\Alpha Flight 007 (2004).cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Renaming D:\Mylar\v3\113391\Alpha Flight v3 07.cbz ..to.. D:\Mylar\Alpha Flight 007 (2004).cbz
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: [Error 3] The system cannot find the path specified
06-May-2015 19:21:33 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "K:\\Mylar New\\mylar\\scheduler.py", line 78, in runAction\n    self.action.run()\n  File "K:\\Mylar New\\mylar\\PostProcessor.py", line 1131, in run\n    result = PostProcess.Process()\n  File "K:\\Mylar New\\mylar\\PostProcessor.py", line 563, in Process\n    self.Process_next(comicid,issueid,issuenumOG,ml,stat)\n  File "K:\\Mylar New\\mylar\\PostProcessor.py", line 983, in Process_next\n    os.rename(os.path.join(odir, str(ofilename)), os.path.join(odir ,str(nfilename + ext)))\nWindowsError: [Error 3] The system cannot find the path specified\n'

**Comment by evilhero** [comment]
Are you on the master branch or development of Mylar (sorry, should have been first thing asked)

**Comment by ElementSixtySix** [comment]
Latest dev

**Comment by evilhero** [comment]
Ok, I think I see the problem:
```
06-May-2015 19:21:33 - ERROR :: FOLDERMONITOR : [META-TAGGER] Unable to move file from temporary path. Deletion of temporary path halted.
06-May-2015 19:21:33 - ERROR :: FOLDERMONITOR : [META-TAGGER] attempt to move: D:\Mylar\v3\113391\Alpha Flight v3 07.cbz to D:\Mylar\v3\Alpha Flight v3 07.cbz
```
and then:
```
06-May-2015 19:21:33 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] otofilename:D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
06-May-2015 19:21:33 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] odir: D:\Mylar\v3\113391
...
06-May-2015 19:21:33 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Source: D:\Mylar\v3\113391\Alpha Flight v3 07.cbz
```
I found the bad reference in the tagger portion and fixed it so that it returns the correct location of the metatagged filename if it can't delete the temporary directory. Not sure exactly if that will fix the problem, but looking at it it would then attempt to move it to D:\Mylar\v3\Alpha Flight v3 07.cbz, which would then have that used later in post-processing as the otofilename/odir/source. I'll try and push it out today and you can test and let me know ;)

**Comment by ElementSixtySix** [comment]
Yep that's done the trick. Tnx...
