### ISSUE TITLE
Add one off error

### ISSUE THREAD

**Issue by spydermixx** [evilhero/mylar#1007]
Hi,

Having a few issues adding one off's from the weekly pull list. 

Regardless of the file, results every time in a [500 Internal server error](http://pastebin.com/dfF7ztjc)

Relevant log file [here](http://pastebin.com/rYYraBe8).

Any ideas?

**Comment by evilhero** [comment]
Are you on the master / development branch of mylar?

**Comment by spydermixx** [comment]
Dev

**Comment by evilhero** [comment]
Yeah, just as I initially thought. It was passing back an invalid value - will be fixed in the upcoming development commit.
