### ISSUE TITLE
ASN1_verify:unknown message digest algorithm

### ISSUE THREAD

**Issue by stustaff** [evilhero/mylar#1009]
Error fetching data from geek2(newznab) [RSS]: [Errno 1] _ssl.c:499: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm

anyone seen that before? lots of possible mentions on line but nthing clear cut?

I get it a few times and it seems to only be for certain searches eg latest Hulk.

**Comment by evilhero** [comment]
It's having a problem with SSLv2 incompatibility.

You need to either:
 a) update python to 2.7.9
and/or
b) update your openssl library (pyopenssl I believe)

You can test what versions you're running by going to an ssh shell and typing:
python -c "import ssl; print ssl.OPENSSL_VERSION"

**Comment by stustaff** [comment]
thanks
