### ISSUE TITLE
API key error

### ISSUE THREAD

**Issue by spydermixx** [evilhero/mylar#1010]
Hi,

Run into a new problem with the latest commit, looks like an API error maybe?

> Uncaught exception: Traceback (most recent call last):
> File "C:\Mylar\mylar\logger.py", line 159, in new_run
> old_run(_args, *_kwargs)
> File "C:\Python27\lib\threading.py", line 763, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "C:\Mylar\mylar\webserve.py", line 1284, in queueissue
> foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
> File "C:\Mylar\mylar\search.py", line 211, in search_init
> findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
> File "C:\Mylar\mylar\search.py", line 1295, in NZB_SEARCH
> searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
> File "C:\Mylar\mylar\search.py", line 1779, in searcher
> fileURL = urllib.quote_plus(linkapi + '&r=' + apikey) # + '&i=' + uid + '&r=' + apikey)
> UnboundLocalError: local variable 'apikey' referenced before assignment

Also seems to result in an `unable to download nzb from link` error message in the log where it looks like there is no API key passed through.

**Comment by evilhero** [comment]
What provider are you pulling it from, and can you post the send-to-sab link from the mylar.log file so I can see what it's trying to poll against?

**Comment by spydermixx** [comment]
Using nzb.su and the latest commit - there doesn't seem to be a send-to-sab link in the log, will this do?

>12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [SEARCHER] entry[title]: Inhuman Annual 001 (2015) (Digital) (Zone-Empire)
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (remove chars): Inhuman Annual 001  2015   Digital   Zone-Empire 
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (\s): Inhuman Annual 001 2015 Digital Zone-Empire
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [SEARCHER] end nzbname: Inhuman.Annual.001.2015.Digital.Zone-Empire
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : nzbname used for post-processing:Inhuman.Annual.001.2015.Digital.Zone-Empire
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [nzb.su] link: http://api.nzb.su/getnzb/7dd1b38712c45a07a74c22d0372125d3.nzb
12-May-2015 07:19:01 - INFO    :: Thread-12 : download url:http://api.nzb.su/getnzb/7dd1b38712c45a07a74c22d0372125d3.nzb
12-May-2015 07:19:01 - ERROR   :: Thread-12 : Unable to download nzb from link: http://api.nzb.su/getnzb/7dd1b38712c45a07a74c22d0372125d3.nzb
12-May-2015 07:19:01 - INFO    :: Thread-12 : [FAILED-DOWNLOAD] Marking as a Failed Download.
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [FAILED-DOWNLOAD]nzb_name: Inhuman.Annual.001.2015.Digital.Zone-Empire
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [FAILED-DOWNLOAD]issueid: 487837
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [FAILED-DOWNLOAD]nzb_id: 7dd1b38712c45a07a74c22d0372125d3.nzb
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [FAILED-DOWNLOAD]prov: nzb.su
12-May-2015 07:19:01 - INFO    :: Thread-12 : [FAILED-DOWNLOAD] Annual detected.
12-May-2015 07:19:01 - INFO    :: Thread-12 : prov  : nzb.su [RSS][7dd1b38712c45a07a74c22d0372125d3.nzb]
12-May-2015 07:19:01 - INFO    :: Thread-12 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
12-May-2015 07:19:01 - DEBUG   :: Thread-12 : issues match!
12-May-2015 07:19:01 - INFO    :: Thread-12 : Found Inhuman Annual (2015) issue: 1 using nzb.su [RSS]
12-May-2015 07:19:01 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\webserve.py", line 1284, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "C:\Mylar\mylar\search.py", line 211, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Mylar\mylar\search.py", line 1295, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "C:\Mylar\mylar\search.py", line 1780, in searcher
    fileURL = urllib.quote_plus(linkapi + '&r=' + apikey) # + '&i=' + uid + '&r=' + apikey)
UnboundLocalError: local variable 'apikey' referenced before assignment

**Comment by spydermixx** [comment]
The gui error is:
 `ERROR	Unable to download nzb from link: http://api.nzb.su/getnzb/7dd1b38712c45a07a74c22d0372125d3.nzb`

**Comment by evilhero** [comment]
Isn't nzb.su https instead of http?

The url generation for nzb.su needs to be redone as I didn't know what it was asking for exactly. I'll see if I can push something out in the next little while for you to try.
