### ISSUE TITLE
https://api.nzbgeek.info/api?t=get&id Blah blah downloads SOME stuck in Sab

### ISSUE THREAD

**Issue by stustaff** [evilhero/mylar#1011]
So ant  man 1 came through ok and ant man 5 not so much just sat in sab saying https://api.nzbgeek.info/api?t=get&id= Removed &apikey= removed &i=&r=

i have maybe 20 just sat and 5 that downloaded as normal..?

i updated to python 2.7.9 as per earlier ssl issue seems like SAB dosnt play nicely with that so am I stuck?  2.7.8 mylar doesnt work, 2.7.9 SAb doesnt work.

ALthough all fine with sickbeard?!

changing all to http now works add https and breaks down again.
It says all worked in mylar but in SAB its creating an error starting with "Empty NZB file api?" then same info as above.

**Comment by stustaff** [comment]
Just looked in log and noticed this when i hit retry... coincidence?

Uncaught exception: Traceback (most recent call last):
File "/Applications/mylar-master/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/Applications/mylar-master/mylar/webserve.py", line 1165, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True)
File "/Applications/mylar-master/mylar/search.py", line 1652, in searcher
name_newznab = newznab[0].rstrip()
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by evilhero** [comment]
Can you post the complete link that the send-to-sab is generating (just xxxx out your api keys) for one of the download that isn't working? The link it's generating probably isn't correct (or keys are duplicated which wouldn't work either). 

Don't use retry either.. It tries to resend the last successful send which is messed up at this point. Something I'll be fixing, but in the short term just avoid using it.

**Comment by stustaff** [comment]
is this what you mean? seemd to have API in loads?
Empty NZB file api?t=get&id=xxxxxxNotAPIxxxxxapikey=xxthiswasapixxx&i=&r=xxthiswaspixx.nzb [https://api.nzbgeek.info/api?t=get&id=xxxnotapixxxapikey=xxxthiswasapixxx&i=&r=xxxthiswasapixxx]

**Comment by evilhero** [comment]
Close, in the mylar.log file it will actually be called send-to-sab... I need to see that complete url.

**Comment by stustaff** [comment]
mylar.log finds nothing if i search even for just sab? no entry with send-to-sab but im assuming log is short as I closed and reopened Mylar

**Comment by stustaff** [comment]
I was able to create this full from mylar.log

10-May-2015 23:13:56 - DEBUG   :: Thread-12 : Completed send-to-SAB link: https://localhost:8083/api?apikey=xxxxxx&mode=addurl&name=https%3A%2F%2Fapi.nzbgeek.info%2Fapi%3Ft%3Dget%26id%3Df4xxxxxxx08dce1d29dab%26apikey%3Dxxxxxx686b%26i%3D%26r%3D30eexxxxx740e2f9dc686b6&priority=-100&cat=comics&script=ComicRN.py
10-May-2015 23:13:56 - INFO    :: Thread-12 : sab-to-send:https://localhost:8083/api?apikey=xxxxx19d90a9&mode=addurl&name=https%3A%2F%2Fapi.nzbgeek.info%2Fapi%3Ft%3Dget%26id%3Df4xxxxxxxx1c208dce1d29dab%26apikey%3Dxxxxxxx9dc686b%26i%3D%26r%3D30eexxxxx2f9dc686b6&priority=-100&cat=comics&script=ComicRN.py
10-May-2015 23:13:56 - ERROR   :: Thread-12 : Unable to send nzb file to SABnzbd

**Comment by stustaff** [comment]
if i paste that into browser i get ok in window and SAB tells me its added to queue, but then gives a warning of empty NZB file.

**Comment by evilhero** [comment]
It's putting the apikey in twice.. So it's an invalid link. I'll try and get a fix up abit later as I can't get to a machine until then. 

Can you confirm what versions of python and sabnzbd you're running?

**Comment by stustaff** [comment]
yeh python 2.7.9 osx
Sab 0.7.20

thanks

**Comment by evilhero** [comment]
Ok that's good.. I can't verify the fix works 100% as I don't use nzbgeek, but I'm pretty sure it'll not reduplicate

**Comment by stustaff** [comment]
Thanks for taking time to review. Appreciated and donation sent towards a couple of drinks to help deal with fools like me. :)

Oh and so how do I actually update or add that? Will it just be in next update?

**Comment by stustaff** [comment]
Thanks for taking time to review. Appreciated and donation sent towards a couple of drinks to help deal with fools like me. :)

**Comment by evilhero** [comment]
That's great - thanks for the support and contributing to my addiction to Java ;) 

If the fix works for you (or not) , please let me know either way so if something needs to be addressed it can be looked at, or otherwise we can close the issue of it's all worky-worky.

**Comment by stustaff** [comment]
No problem I'm away for a few days but will let you know and close this off if it resolves.

**Comment by stustaff** [comment]
I updated Mylar and am seeing same issue.

13-May-2015 09:35:12 - DEBUG   :: Thread-13 : sab-to-send:http://localhost:8083/api?apikey=cbbdeleted&mode=addurl&name=https%3A%2F%2Fapi.nzbgeek.info%2Fapi%3Ft%3Dget%26id%3D2deleted28ee279e9c2ee502c6c0%26apikey%3D30ee748ddeletede2f9dc686b&priority=-100&cat=comics&script=ComicRN.py
13-May-2015 09:35:13 - INFO    :: Thread-13 : Successfully sent nzb file to SABnzbd

**Comment by evilhero** [comment]
And sabnzbd isn't receiving any nzbsu or they're empty?

**Comment by stustaff** [comment]
They are empty

Stuart Hill

**Comment by evilhero** [comment]
If you copy/paste the addurl&name link in a very, does it add it ok to your sabnzbd? 

Also is it an rss hit that's it's grabbing or via the api of nzbgeek?

**Comment by stustaff** [comment]
I will test, how do I check the second thing?

Stuart Hill

**Comment by evilhero** [comment]
In the log just prior to that link that you pasted it would say somewhere that's it's from RSS or nothing if it's am api hit (the shhh line also indicates which)

**Comment by stustaff** [comment]
Ok no reference to RSS just API, I have seen RSS before but not in the log for this one.

not sure if im selecting right bit to paste?

if i use the following I get a message saying -<error code="100" description="Invalid API Key"/> in the browser but nothing added - https://api.nzbgeek.info/api?t=get&id=2b5230delete9e9c2ee502c6c0&apikey=30ee7delete740e2f9dc686b

if i use http://localhost:8083/api?apikey=cbb2f7deleteb19d90a9&mode=addurl&name=https%3A%2F%2Fapi.nzbgeek.info%2Fapi%3Ft%3Dget%26id%3D2b52deleteee279e9c2ee502c6c0%26apikey%3D30ee748delete40e2f9dc686b I get a single word "ok: in browser and nothing added.

oh and if it matters the correct API is the ones starting "30ee"

if I use the next one i get

**Comment by stustaff** [comment]
now im confused.

pasting - https://api.nzbgeek.info/api?t=get&id=6dcb1b3190f02a883e8a3df8dad3b24c&apikey=30ee7delete0e2f9dc686b6
into browseradds to Sab fine

**Comment by evilhero** [comment]
What about the full send to sab link from your browser? 

It's working on my end, or was yesterday, so I'm really abit confused as to why it's not working atm.

**Comment by stustaff** [comment]
me too.
I just retried the one from yesterday and it went through and was added instantly!

I havent reset anything or changed anything at all?
ill let it run for a couple of days and then report back.

**Comment by stustaff** [comment]
Oh dear...
then tried another and it didnt!
this was from log
http://localhost:8083/api?apikey=cbb2f7deleteb91252421919d90a9&mode=addurl&name=https%3A%2F%2Fapi.nzbgeek.info%2Fapi%3Ft%3Dget%26id%3D8b43db8929a013b4703077b500ecba20%26apikey%3D30ee7deleteddc686b&priority=-100&cat=comics&script=ComicRN.py

i pasted into browse and it trys to send to Sab but sab reports same think if generated by mylar or link into browser

2015-05-14 13:51:40,252	WARNING:	Empty NZB file api?t=get&id=8b43db8929a013b4703077b500ecba20&apikey=30eedelete740e2f9dc686b.nzb [https://api.nzbgeek.info/api?t=get&id=8b43dbdelete077b500ecba20&apikey=30ee74delete40e2f9dc686b]
2015-05-14 13:45:34,701	WARNING:	Empty NZB file api?t=get&id=8b43db8929a013b4703077b500ecba20&apikey=30ee7deletede740e2f9dc686b.nzb [https://api.nzbgeek.info/api?t=get&id=8b43dbdeleteb4703077b500ecba20&apikey=30ee7delete40e2f9dc686b]

**Comment by evilhero** [comment]
Is it pulling both of those from the rss or from the api? If ones working vs not, then I would suspect one is rss and the other is api, and one of them is causing the problem. 

If they're both from rss, then it's possible that the one (issue 16) has an invalid link - I remember something about nzbgeek leaving the nzbs intact but it's marked as spam. 

Can you verify via their site if it's a valid nzb still?

**Comment by stustaff** [comment]
still valid on site.
I have done a sample and a few worked fine rest not. all worked fine according to Mylar.
in SAB three worked and have been added to queue and 20 have appeared a sa warning saying empty.

I cant se any common reaon why.?

remember i hadnt had any issues until i upgraded python.

is it worth a total reinstall? anyway to keep a record of my wanted list and stuff?

**Comment by evilhero** [comment]
Well python 2.7.9 is required for sites that use https and have SNI (Shared Name Identification) enabled  and are on a shared host as it needs to verify the certificate against the right site. Downgrading to a different versions of python would just cause different problems (aside from OS ones since python is linked directly into the OS for nix based systems). 

It might be due to rss vs api results being downloaded, it's just trying to figure out which. I'm on 2.7.9 ubuntu 12.04 and it's just required almost if you hit https sites due to the SNI and every site using cloudflare type services (they all use SNI). 

You can try doing this. Within mylar, turn off rss feeds in the configuration/search providers tab. Save it and restart Mylar. Then try doing a manual search (or two) for something and see if it passes it (turning off rss will force it to use only api results).

**Comment by stustaff** [comment]
ok so first 7 i have tried with RSS off all added to sab fine??

**Comment by evilhero** [comment]
Ok so then it's a problem with the rss caching most likely. Is it occurring across all your providers? I only recall you mentioning nzbgeek, have you tried any others (experimental)?

**Comment by DGMayor** [comment]
I just noticed I'm having issues with NZBGeek as well.  When I copy the URL in the error message from SABnzbd, it's apparently truncating the last character of my API key.  I verified that it was entered properly in the settings (hasn't changed).

**Comment by evilhero** [comment]
Which one is getting cut off - the apikey for sab or the apikey for nzbget?

**Comment by DGMayor** [comment]
The Error message in Sab of empty nzb file shows the link with the last character of my nzbgeek api cut off.

**Comment by evilhero** [comment]
What about the log within thr mylar.z

**Comment by DGMayor** [comment]
Scrolled away already via web interface (not at my computer), but subsequent attempts show the complete key there.  (I've got another issue with NZB.SU I'm about to post).  FYI all these issues started up this week.  Things were fine a week or so ago if that means anything to you.

**Comment by evilhero** [comment]
Yeah I had to switch mylar to the requests library due to problems with SNI support.. So some of these problems are expected if you're trying to access an https site and you're on python 2.7.6 (since SNI support is only available in >2.7.7).

Newest development commit though has the updated requests library which might help things.

**Comment by DGMayor** [comment]
I'm on 2.7.9 and have been for a while and I'm on the latest dev commit.

**Comment by evilhero** [comment]
So you shouldn't be having any connection issues since 2.7.9 is able to use requests. 

Your issue is probably the link itself, or are you using https with sabnzbd?

**Comment by DGMayor** [comment]
No I am not.

**Comment by evilhero** [comment]
Can you paste in the fill url that it's sending to your sab? The complete line with your sabnzbd host in it is the one I need to see (just xxxx out your keys)

**Comment by DGMayor** [comment]
Is there another log location other than the logs folder within the mylar folder?  There are two logs in there both dated last friday...

**Comment by evilhero** [comment]
Nope that'd be the only place unless you changed the log location, or it errored out and hasn't been logging due to the error.

**Comment by DGMayor** [comment]
Mylar.log contains entries from  4:53AM to 7:17AM on May 15th
Mylog.log.5 contains entries from 2:12AM to 4:53am on May 15th

That's my current log folder.

**Comment by evilhero** [comment]
I'd restart mylar and /or shut it down and then start it up and see if it starts logging without errors. Something errored out and caused it to stop logging.

**Comment by DGMayor** [comment]
Is there a way to unmark it as failed?  It won't try the nzbgeek file anymore because I had marked it as failed before I realized there might be a bigger issue.

**Comment by evilhero** [comment]
Unfortunately not without editing the sql manually. It was in the pipe, but then the requests became more prevalent so it took precedence in the hierarchy. 

Will have something for this in the next day or so as I find myself having this problem as well occasionally.

**Comment by DGMayor** [comment]
So I restarted and now it won't load anymore.  https://github.com/evilhero/mylar/issues/1020

**Comment by evilhero** [comment]
This bug should be squashed in the next development commit - hopefully early tomorrow.

**Comment by DGMayor** [comment]
Still having issues with nzbgeek.

	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 1165, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True)
File "C:\Mylar\mylar\search.py", line 1684, in searcher
name_newznab = newznab[0].rstrip()
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-21 12:59:02	INFO	link : https://01100111011001010110010101101011.info/getnzb/64408d0b883a7b21cc1951be62675161.nzb&i=7030&r=myapikey
2015-05-21 12:59:02	INFO	newznab detected as : NZBGeeks @ https://01100111011001010110010101101011.info/
2015-05-21 12:59:02	INFO	fetched via newnzab. Retrying the send.
2015-05-21 12:59:02	INFO	--Referencing : newznab @ 2015-05-20 21:46:42
2015-05-21 12:59:02	INFO	Located snatched download:
2015-05-21 12:59:02	INFO	Retrying : 489315
2015-05-21 12:59:02	INFO	ComicID:72417

**Comment by evilhero** [comment]
Not nzbgeek, it's the Retry option - it's currently broken and will throw them error. It's next on the fix list. 

Try downloading normally (don't use the retry option) and see if that works.

**Comment by DGMayor** [comment]
That was it!
