### ISSUE TITLE
Story Arc Management

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1013]
How can I update a already selected story arc? For instance, last week I added Secret Wars to my story arc list and it included 25 issues. This week that story arc was updated on Comicvine to 26 issues, to include this weeks issue. However, the story arc for Secret Wars in mylar still only shows 25 issues. Is there a way to update this? Or will I have to remove the story arc, and re-add it each week?

**Comment by evilhero** [comment]
Currently you'll have to remove / readd as it wasn't coded for ongoing story arcs. I need to do that portion, but it'll be in the development branch before next week's pull so you don't have to delete/readd again.

**Comment by evilhero** [comment]
Just to confirm, will be in the next development commit as I have it working on my local repo currently. The only caveat is that you can only refresh arcs that are added via the search option from within the Story Arc Management screen (meaning it's not available for arcs that were created by importing a .cbl file). So in there cases you would have to delete the arc and readd it to get things to work properly.

**Comment by bguidotti** [comment]
This is awesome, and I started using StoryArcs with the refresh button.
Question re: The Append Reading# to Filename:

I had a bunch of Convergence books already.
I created the Convergence storyarc and threw them in that folder.
It snatched some issues I did not have and put the reading number at the front of the filename.
I don't appear to be able to get Mylar to rename the files I already had with the reading number, even though it does see that they are downloaded.

Am I doing something wrong, or is this not possible?

Thanks.

**Comment by evilhero** [comment]
Renaming issues that don't exist in your watchlist already isn't available atm (meaning they only appear in your story arc, you aren't watching the series). 

There's a bunch of things that I'm planning on pushing into the story arc section over the next little while, so I'll add this one in there as well. It might not make it in there for a few commits at the very least since there are a bunch of other fixes that need to get done first.
