### ISSUE TITLE
NZBget Unable to parse NZB

### ISSUE THREAD

**Issue by hermy65** [evilhero/mylar#1014]
I updated mylar this morning and now every nzb it sends to nzbget shows this error

ERROR   Thu May 14 2015 09:19:35    Could not add collection Chrononauts.003.2015.digital.Son.of.Ultron-Empire.nzb to queue
ERROR   Thu May 14 2015 09:19:35    Failed to parse nzb-file
ERROR   Thu May 14 2015 09:19:35    Error parsing nzb-file: Start tag expected, '<' not found
INFO    Thu May 14 2015 09:19:35    Adding collection Chrononauts.003.2015.digital.Son.of.Ultron-Empire.nzb to queue

If i manually download and import the same nzb it works fine

**Comment by evilhero** [comment]
What version of nzbget and OS are you running?

**Comment by baz1860** [comment]
I'm having the same issue using nzbget 15.0-testing on synology DSM 5.2

**Comment by hermy65** [comment]
Currently running 14.2 stable and its running on unraid - no issues up until today

**Comment by evilhero** [comment]
I just pushed up a fix to development a few hrs ago. Tested on 13 (as that's what I had installed), and was able to pass nzbs to client with no issues. 

Please post back if it's working or not so I know if it's a version problem or something else.

**Comment by hermy65** [comment]
That update looks like it fixed my issue. Its pushing them to nzbget correctly now
