### ISSUE TITLE
Tool bar doesn't show up on firefox mobile

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1015]
I use firefox 38.0 on my android phone, and for some reason the toolbar at top does not show up.  I zoom all the way out, and it is not there, so I can get to any page except the main page.  This is on the development branch.

**Comment by evilhero** [comment]
I honestly haven't used either Firefox or ie in a while (for ie, it's been like a decade) - in chrome though it displays just fine. At one point though it didn't, and I believe that was when I tried with Firefox if I recall. 

I'm not sure exactly of the differences between and obviously mylar isn't specifically built for a mobile/tablet environment yet (yes, yet) - so I kind of expect it to a degree. 

I'll look into it, but there are some other items that are taking up alot of my time atm (namely things not being downloaded, and invalid torrent files) - but I'll see what I can figure out.
