### ISSUE TITLE
Folder Format loses slashes

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1016]
I dump all my comics into a single directory, without using publisher or series folders; Up until recently, this has been successfully accomplished by setting the Folder Format to 

/Users/<username>/Documents/Comics

However, for the last few versions of code, once I've set that path and restarted mylar, I get the following in the field (both in the Settings window, and when adding a new title)

/Users/<username>/Documents/ComicsUsers<username>DocumentsComics

Any idea why it might be doing that?  I can manually set the path in the Title Details to remove the erroneous appended string, so it's not a huge issue. Just odd behavior.

**Comment by evilhero** [comment]
The folder format just parses out the variables though and replaces them with values. It then appends the comic location value to the folder format and if there are any sub-folders, drop them down. 

If it was working before, honestly I had no idea ;)  

What is your Comic Location set to? And do you have anything in the file format field? 

I'm guessing there's nothing in the logs, but can you see the point where it doubles up the value? Is it when you refresh a series, post-process, add, something?

**Comment by ForumFerret** [comment]
ahh, maybe that's it - because Comic Location is indeed also set to /Users/<username>/Documents/Comics. 

Here's what I have in the logs: 

15-May-2015 10:52:13 - INFO    :: Thread-12 : Directory (/Users/<username>/Documents/Comics/Users<username>DocumentsComics) already exists! Continuing...
15-May-2015 10:52:15 - INFO    :: Thread-12 : [FILE-RESCAN] Now checking files for Mythic (2015) in /Users/patrickburke/Documents/Comics/UserspatrickburkeDocumentsComics
15-May-2015 10:52:15 - DEBUG   :: Thread-12 : [FILECHECKER] Looking in: /Users/<username>/Documents/Comics/Users<username>DocumentsComics
15-May-2015 10:52:15 - DEBUG   :: Thread-12 : [FILE-RESCAN]dir: /Users/<username>/Documents/Comics/Users<username>DocumentsComics
15-May-2015 10:52:15 - DEBUG   :: Thread-12 : [FILE-RESCAN]os.path.basename: UserspatrickburkeDocumentsComics
15-May-2015 10:52:15 - INFO    :: Thread-12 : [FILE-RESCAN] Now checking files for Mythic (2015) in :Users<username>DocumentsComics
15-May-2015 10:52:15 - DEBUG   :: Thread-12 : [FILECHECKER] Looking in: Users<username>DocumentsComics
15-May-2015 10:52:45 - INFO    :: CP Server Thread-3 : Validating Directory (/Users/<username>/Documents/Comics/). Already exists! Continuing...
15-May-2015 10:52:56 - DEBUG   :: Thread-13 : cache directory successfully found at : /Users/<username>/Applications/Mylar/mylar/cache
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for /Users/patrickburke/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] Comic Location: /Users/<username>/Documents/Comics/
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] odir (root): /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] odir: /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - INFO    :: Post-Processing : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Users/<username>/Documents/Comics/
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] Source: /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] Destination: /Users/<username>/Documents/Comics/Mythic 1.cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] self.nzb_folder: /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] odir: /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] Renaming /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr ..to.. /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr/Mythic 1.cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING] Removed temporary directory : /Users/<username>/Documents/Comics/Mythic 001 (2015) (3 covers) (digital) (Son of Ultron-Empire).cbr
15-May-2015 10:53:25 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Now checking files for Mythic (2015) in /Users/<username>/Documents/Comics/
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [FILECHECKER] Looking in: /Users/<username>/Documents/Comics/
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [FILECHECKER] Mythic - watchlist match on : /Users/<username>/Documents/Comics/Mythic 1.cbr
15-May-2015 10:53:25 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN]dir: /Users/<username>/Documents/Comics/
15-May-2015 10:54:23 - DEBUG   :: CP Server Thread-4 : Trying to execute: "git rev-parse HEAD" with shell in /Users/<username>/Applications/Mylar/mylar
15-May-2015 11:02:38 - DEBUG   :: CP Server Thread-5 : Trying to execute: "git rev-parse HEAD" with shell in /Users/<username>/Applications/Mylar/mylar
15-May-2015 11:02:41 - DEBUG   :: CP Server Thread-5 : Trying to execute: "git rev-parse HEAD" with shell in /Users/<username>/Applications/Mylar/mylar

**Comment by evilhero** [comment]
Try just using the comic location value and see if that works. Leaving it in the Folder Format portion is probably going to cause some problems I would imagine.

**Comment by ForumFerret** [comment]
With Folder Format blank, when adding a new title it sets the Directory to  

/Users/<username>/Documents/Comics/The Dark Tower The Drawing of the Three - House of Cards/ (2015)

So it looks like a blank Folder Format is treated as if the value was $Series $Year

**Comment by evilhero** [comment]
Ahh ok, so set your Comic Location to /Users/username/Documents/ 
and your Folder format to Comics/

Keep in mind that this isn't really supported, so I have no idea if it will actually work or if it would hit a check and it would default to some other value.

**Comment by ForumFerret** [comment]
Hey, that works a treat. Thanks man!
