### ISSUE TITLE
Unable to download nzb from link:

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1018]
I started getting these errors this week.
If I paste the link into my browser, I'm able to download the NZB so I'm not sure what the problem is.
Log excerpt below
Thanks!

> 16-May-2015 15:45:31 - INFO :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
> 16-May-2015 15:46:32 - INFO :: SEARCH : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b9', 't': 'get', 'id': '77c7633f924b01cd4efb14fb82270536.nzb&i=123486&r=a18ababfdab1bc33fc1f106f4b959'}
> 16-May-2015 15:46:32 - INFO :: SEARCH : download url:https://api.nzb.su/api
> 16-May-2015 15:46:32 - ERROR :: SEARCH : Unable to download nzb from link: https://api.nzb.su/getnzb/77c7633f924b01cd4efb14fb82270536.nzb&i=123486&r=a18ababfdab1bc33fc1f106f449

**Comment by evilhero** [comment]
Sign out of nzb.su first, close the browser. And then paste  the download link into a new browser and see if it works. 

I'm not sure what the api for 'get' is for nzb.su or if they changed it from the default newznab. I can try to adjust it to what I think might work, but without knowing for sure it'd be a best guesd/trial & error kinda thing.

**Comment by thewindupboy** [comment]
It still worked when I tried that.
Regarding the API, is this something I can ask them?

**Comment by evilhero** [comment]
They probably have the info on their api page. I just need to know the url reference for the get command - usually it's getnzb/id&apikey=apikey or t=get&id=nzb&apikey=apikey

**Comment by thewindupboy** [comment]
Available Functions

Use the parameter ?t= to specify the function being called.
Server Functions

    Capabilities ?t=caps
    Reports the capabilities if the server. Includes information about the server name, available search categories and version number of the newznab protocol being used.
    Capabilities does not require any credentials in order to be ran.

User Functions

    Register ?t=register&email=user@newznab.com
    Registers a new user account. Does not require any credentials in order to be ran.
    Returns either the registered username and password if successful or an error code.
    User ?t=user&username=user123
    Returns public information about a user.
    Returns either the user information or an error code.
    Cart rss?t=-2&del=1
    Returns the items in a users cart in the form of an rss feed. The optional parameter &del=1 will remove the items from the cart after the feed is requested.
    CartAdd ?t=cartadd&id=9ca52909ba9b9e5e6758d815fef4ecda
    Adds an nzb to a users cart.
    CartDelete ?t=cartdel&id=9ca52909ba9b9e5e6758d815fef4ecda
    Remove an nzb from a users cart.

Search Functions

    Search ?t=search&q=linux
    Returns a list of nzbs matching a query. You can also filter by site category or group name by including a comma separated list as follows ?t=search&cat=1000,2000&group=a.b.multimedia. Include &extended=1 to return extended information in the search results.
    TV ?t=tvsearch&q=beverly%20hillbillies&season=1&ep=1
    Returns a list of nzbs matching a query, category, tvrageid, season or episode. You can also filter by site category by including a comma separated list of categories as follows ?t=tvsearch&rid=2204&cat=1000,2000. Include &extended=1 to return extended information in the search results.
    Movies ?t=movie&imdbid=0023010
    Returns a list of nzbs matching a query, an imdbid and optionally a category or genre. Filter by site category by including a comma separated list of categories as follows ?t=movie&imdbid=0023010&cat=2030,2040&genre=Romance. Include &extended=1 to return extended information in the search results.
    Music ?t=music&artist=Jack
    Returns a list of nzbs matching an audio based query and optionally a category. Filter by site category by including a comma separated list of categories as follows ?t=music&artist=Jack&cat=2030,2040. Include &extended=1 to return extended information in the search results. Other search parameters include artist, album, label, year, genre (supports comma separated list).
    Book ?t=book&author=Daniel
    Returns a list of nzbs matching a book based query. Include &extended=1 to return extended information in the search results. Other search parameters include title.
    Details ?t=details&id=9ca52909ba9b9e5e6758d815fef4ecda
    Returns detailed information about an nzb.
    GetNfo ?t=getnfo&id=9ca52909ba9b9e5e6758d815fef4ecda
    Returns an nfo file for an nzb. Optional parameter &raw=1 returns just the nfo file without the rss container.
    Comments ?t=comments&id=9ca52909ba9b9e5e6758d815fef4ecda
    Returns comments for an nzb.

NZB Functions

    Get ?t=get&id=9ca52909ba9b9e5e6758d815fef4ecda
    Downloads the nzb file associated with an Id.
    CommentAdd ?t=comments&id=9ca52909ba9b9e5e6758d815fef4ecda&text=comment
    Adds a comment to an nzb.

Output Format

Obviously not appropriate to functions which return an nzb file.

    Xml (default) ?t=search&q=linux&o=xml
    Returns the data in an xml document.
    Json ?t=search&q=linux&o=json
    Returns the data in a json object.

Extended Attributes

Using the attrs tag and a comma separated list of supported values, extended information can be returned in the search results.
For example ?attrs=files,poster,group. Note that not every attribute is available for every release type. Below is a list of some of the supported attributes. To return all known attributes per release use the parameter ?extended=1. See the API specification for a full list.

    files
    poster
    group
    team
    grabs
    password
    comments
    usenetdate
    info
    year
    season
    episode
    rageid
    tvtitle
    tvairdate
    video
    audio
    resolution
    framerate
    language
    subs
    imdb
    imdbscore
    imdbtitle
    imdbtagline
    imdbplot
    imdbyear
    imdbdirector
    imdbactors
    genre
    artist
    album
    publisher
    tracks
    coverurl
    backdropcoverurl
    review

**Comment by evilhero** [comment]
Lol ok more info than I needed, but thanks for the detail ;) 

It's just a Newznab standard, so if I flip it to use the Newznab defaults it should work again. 

I'll try and commit something up at some point today to try and fix this (long weekend here ya know)

**Comment by thewindupboy** [comment]
I like to cover my bases ;)
Thank you kindly, no hurry on my account :)

**Comment by evilhero** [comment]
Ok, I had some time to look into this, the nzbid that was being parse out was the complete url, which resulted in mylar sending two apikeys in the url to retrieve the nzb from nzb.su (which wouldn't work). The other problem is the link that's displayed in the error isn't the actual link that mylar used to request (it regenerates everything from scratch so that apikey changes can be accounted for properly).

I believe I have it working, so I'll commit this up shortly and you can test/try it and if you could let me know if it works or not, that'd be great!

**Comment by thewindupboy** [comment]
Will give it a shot as soon as the commit is up!

**Comment by thewindupboy** [comment]
(I assume I'll get alerted in Mylar?)

**Comment by evilhero** [comment]
If you restart mylar you will, or if you go to the Manage tab/Advanced Options and select check for updates, you'll get the popup box telling you to upgrade. 

Mylar only checks for new commits every 6 hrs if I recall.

**Comment by thewindupboy** [comment]
18-May-2015 16:38:23 - INFO :: Thread-12 : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b949', 't': 'get', 'id': 'e9b67ce943ec83892eed10ee8a9b540e'}
18-May-2015 16:38:23 - INFO :: Thread-12 : Download URL: https://api.nzb.su/apiapikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [VerifySSL:False]
/Applications/Mylar/lib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
18-May-2015 16:38:24 - ERROR :: Thread-12 : Unable to download nzb from link: https://api.nzb.su/apiapikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [https://api.nzb.su/getnzb/e9b67ce943ec83892eed10ee8a9b540e.nzb&i=123486&r=a18ababfdab1bc33fc1f106f4b95b949]

**Comment by evilhero** [comment]
Ok, it looks like it was chunking it all in one line, just pushed out a fix for that - still not sure if the verify_ssl has to be on / off for the site still. 

I'm just assuming it needs to be off just because it's probably on an SNI-type hosting.

**Comment by thewindupboy** [comment]
18-May-2015 16:52:26 - INFO :: Thread-12 : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b949', 't': 'get', 'id': 'e9b67ce943ec83892eed10ee8a9b540e'}
18-May-2015 16:52:26 - INFO :: Thread-12 : Download URL: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [VerifySSL:False]
18-May-2015 16:52:26 - ERROR :: Thread-12 : Unable to download nzb from link: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [https://api.nzb.su/getnzb/e9b67ce943ec83892eed10ee8a9b540e.nzb&i=123486&r=a18ababfdab1bc33fc1f106f4b95b949]
18-May-2015 16:52:26 - INFO :: Thread-12 : Could not find Issue 1 of Hellboy and the B.P.R.D.(2014) using nzb.su
18-May-2015 16:52:26 - INFO :: Thread-12 : Could not find issue doing a manual search via : api

**Comment by evilhero** [comment]
are you running python 2.7.9 by chance ?

**Comment by thewindupboy** [comment]
How can I tell?

**Comment by thewindupboy** [comment]
Mylar says:
Python Version : 2.7.6

**Comment by evilhero** [comment]
If you sign off of nzb.su in your web-browser, and then try to get the downloadlink via the browser, does it still work ?

**Comment by thewindupboy** [comment]
I logged off of NZB.su, clicked on the link, and yes, I downloaded an NZB

**Comment by evilhero** [comment]
Ok, I forced the ssl check so you can try the latest commit and see if that works.

**Comment by thewindupboy** [comment]
18-May-2015 17:13:29 - INFO :: Thread-12 : Issue Title given as : 1952
18-May-2015 17:13:29 - INFO :: Thread-12 : search provider order is ['nzb.su']
18-May-2015 17:13:29 - INFO :: Thread-12 : Shhh be very quiet...I'm looking for Hellboy and the B.P.R.D. issue: 1 (2014) using nzb.su
18-May-2015 17:13:29 - INFO :: Thread-12 : pausing for 60 seconds before continuing to avoid hammering
18-May-2015 17:13:58 - INFO :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
18-May-2015 17:14:30 - INFO :: Thread-12 : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b949', 't': 'get', 'id': 'e9b67ce943ec83892eed10ee8a9b540e'}
18-May-2015 17:14:30 - INFO :: Thread-12 : Download URL: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [VerifySSL:True]
18-May-2015 17:14:30 - ERROR :: Thread-12 : Unable to download nzb from link: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [https://api.nzb.su/getnzb/e9b67ce943ec83892eed10ee8a9b540e.nzb&i=123486&r=a18ababfdab1bc33fc1f106f4b95b949]
18-May-2015 17:14:30 - INFO :: Thread-12 : Could not find Issue 1 of Hellboy and the B.P.R.D.(2014) using nzb.su

**Comment by evilhero** [comment]
Ok, it's still the stupid requests problem again, thanks for bearing with all of this.

 I don't have time atm, but going to try and update the requests library later tonight.

**Comment by thewindupboy** [comment]
Oh, no worries, I appreciate the help and whenever you can get to it, great

Thanks!

**Comment by thewindupboy** [comment]
Any chance of a commit today?

**Comment by evilhero** [comment]
Sorry, yeah I updated the requests to 2.7.0, which has an updated urllib3 and some better SNI handling.This may/may not solve the problem, as I haven't run it through any tests (aside from with python 2.7.9, which was working previously).

Just so you're aware, SNI support is only in python > 2.7.7, so you're 2.7.6 (and openssl) might be the end-culprit in all of this unfortunately. You can get SNI support to work on lower versions of python by installing some other packages (according to the requests package maintainer), but I didn't really want to just throw you a bunch of links and say 'install these'...

If it doesn't work, you can try to either:
- install the packages it requires:
```
In order to support `SNI`_ in python 2.6/2.7 you need to install additional packages:
 * `pyOpenSSL`, a Python wrapper module around the OpenSSL library.
 * `pyasn1`, ASN.1 types and codecs.
 * `ndg-httpsclient`, enhanced HTTPS support for httplib and urllib2.

If you can use 'pip install' to install all 3. Requests is then able to make SSL requests to servers with SNI.
```
- update to a python greater than 2.7.6. (hint, if you don't want to break other things, use the great 'pyenv' package which lets you side-load python and you can use it to directly run programs against it - you just need to install any dependencies seperately)

**Comment by thewindupboy** [comment]
OK, I'll give it a shot and let you know.
Can I install  python 3.whatever?

**Comment by thewindupboy** [comment]
Or should I just go with 2.7.9?

**Comment by evilhero** [comment]
Don't go python 3 - not supported, and alot of other apps don't use it as well.

Python 2.7.9 would be what I would suggest, python 2.7.10 is abit too new, but it might work - I have 2.7.9 and it's working on mine.

**Comment by thewindupboy** [comment]
Great, thanks!

**Comment by thewindupboy** [comment]
19-May-2015 12:54:55 - INFO :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
19-May-2015 12:55:19 - INFO :: Thread-12 : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b949', 't': 'get', 'id': 'e9b67ce943ec83892eed10ee8a9b540e'}
19-May-2015 12:55:19 - INFO :: Thread-12 : Download URL: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [VerifySSL:True]
19-May-2015 12:55:19 - INFO :: Thread-12 : filen: Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire -- nzbname: Hellboy.and.the.B.P.R.D.001.2014.digital.Son.of.Ultron-Empire are not identical. Storing extra value as : Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire
19-May-2015 12:55:19 - INFO :: Thread-12 : Found Hellboy and the B.P.R.D. (2014) issue: 1 using nzb.su
19-May-2015 12:55:19 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 1284, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Applications/Mylar/mylar/search.py", line 230, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/Applications/Mylar/mylar/search.py", line 1295, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/Applications/Mylar/mylar/search.py", line 1808, in searcher
    fileURL = urllib.quote_plus(downurl + '&i=' + mylar.NZBSU_UID + '&r=' + mylar.NZBSU_APIKEY)
NameError: global name 'downurl' is not defined

Traceback (most recent call last):
  File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 1284, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Applications/Mylar/mylar/search.py", line 230, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/Applications/Mylar/mylar/search.py", line 1295, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/Applications/Mylar/mylar/search.py", line 1808, in searcher
    fileURL = urllib.quote_plus(downurl + '&i=' + mylar.NZBSU_UID + '&r=' + mylar.NZBSU_APIKEY)
NameError: global name 'downurl' is not defined

**Comment by evilhero** [comment]
Ok, that's good - you're past the initial download part and it pulled it down fine. Give me a minute and I'll patch that stupid error for you (it should be 'down_url', not 'downurl')

**Comment by DGMayor** [comment]
Seem to be having the same/similar issue?  Link within Mylar logs now looks good - I can copy it out of the log and paste it in the browser and the download window pops up, but when I look in SABnzbd it states that there is no ID and the link looks different?
From Mylar Log:  https://api.nzb.su/api?apikey=myapikey&t=get&id=4138a6ec445417869979ffd1f843f672
From SabNZBd: https://api.nzb.su/api?&i=7030&r=myapikey

**Comment by thewindupboy** [comment]
OK, so, getting closer?
From Mylar:
19-May-2015 15:28:20 - INFO :: Thread-12 : payload:{'apikey': 'a18ababfdab1bc33fc1f106f4b95b949', 't': 'get', 'id': 'e9b67ce943ec83892eed10ee8a9b540e'}
19-May-2015 15:28:20 - INFO :: Thread-12 : Download URL: https://api.nzb.su/api?apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=e9b67ce943ec83892eed10ee8a9b540e [VerifySSL:True]
19-May-2015 15:28:21 - INFO :: Thread-12 : filen: Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire -- nzbname: Hellboy.and.the.B.P.R.D.001.2014.digital.Son.of.Ultron-Empire are not identical. Storing extra value as : Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire
19-May-2015 15:28:21 - INFO :: Thread-12 : Found Hellboy and the B.P.R.D. (2014) issue: 1 using nzb.su
19-May-2015 15:28:21 - INFO :: Thread-12 : Successfully sent nzb file to SABnzbd
19-May-2015 15:28:21 - INFO :: Thread-12 : setting the nzbid for this download grabbed by nzb.su in the nzblog to : e9b67ce943ec83892eed10ee8a9b540e
19-May-2015 15:28:21 - INFO :: Thread-12 : setting the alternate nzbname for this download grabbed by nzb.su in the nzblog to : Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire



But I get a warning in SabNZB:
Empty NZB file api?&i=&r=a18ababfdab1bc33fc1f106f4b95b949.nzb [https://api.nzb.su/api?&i=&r=a18ababfdab1bc33fc1f106f4b95b949]

**Comment by thewindupboy** [comment]
OK, Idon't think it is actually grabbing the NZB.  I'm not seeing the NZB file anywhere.

**Comment by evilhero** [comment]
The first download is grabbing the actual nzb into a temp name. The second one is actually sending the request to your sabnzbd client. 

Is that the actual error or did you edit the keys, because there is no ID or userid (i=)  for the last log line.

**Comment by thewindupboy** [comment]
I did nothing.  Thats the error.

**Comment by thewindupboy** [comment]
(thats just copied from SabNZB's warning screen)

**Comment by evilhero** [comment]
Ok so the key is being messed up - can you check the mylar.log file and post that portion so I can see what's being passed?

**Comment by thewindupboy** [comment]
19-May-2015 15:28:21 - INFO    :: Thread-12 : filen: Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire -- nzbname: Hellboy.and.the.B.P.R.D.001.2014.digital.Son.of.Ultron-Empire are not identical. Storing extra value as : Hellboy.and.the.B.P.R.D..001.2014.digital.Son.of.Ultron-Empire
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : issues match!
19-May-2015 15:28:21 - INFO    :: Thread-12 : Found Hellboy and the B.P.R.D. (2014) issue: 1 using nzb.su
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : link given by: nzb.su
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : cache directory successfully found at : /Applications/Mylar/cache
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : link to retrieve via api:https://api.nzb.su/getnzb/e9b67ce943ec83892eed10ee8a9b540e.nzb&i=123486&r=a18ababfdab1bc33fc1f106f4b95b949
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : send-to-SAB host &api initiation string : http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : ...selecting API type: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : ...attaching nzb provider link: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : ...setting priority: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949&priority=-100
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : ...attaching category: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949&priority=-100&cat=comics
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : ...attaching rename script: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949&priority=-100&cat=comics&script=ComicRN.py
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : Completed send-to-SAB link: http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949&priority=-100&cat=comics&script=ComicRN.py
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : sab-to-send:http://localhost:8085/api?apikey=af0478bef962a1dc3af4b300fc998c0e&mode=addurl&name=https%3A%2F%2Fapi.nzb.su%2Fapi%3F%26i%3D%26r%3Da18ababfdab1bc33fc1f106f4b95b949&priority=-100&cat=comics&script=ComicRN.py
19-May-2015 15:28:21 - INFO    :: Thread-12 : Successfully sent nzb file to SABnzbd
19-May-2015 15:28:21 - DEBUG   :: Thread-12 : we should break out now - sucessful

**Comment by evilhero** [comment]
This bug should be squashed in the next development build - hopefully going up early tomorrow.

**Comment by evilhero** [comment]
Apologies for the delay in this, personal life and all. Will get this fix up later tonight hopefully.

**Comment by thewindupboy** [comment]
I'm deeply troubled that you have a life outside of developing and supporting an application for free.

;)

**Comment by DGMayor** [comment]
Excuses Excuses :)

**Comment by evilhero** [comment]
Lol, yeah life sucks ;) 

Latest development commit has the fix for all of this which should (hopefully) solve all of these types of Issues.

**Comment by thewindupboy** [comment]
Looks good to me!

thanks so much for your help!

Quick question, why does adding a series take so long?  If I want to add a new series, it seems to take a very long time getting the information and such.  I would think this would be a fast and simple thing.

**Comment by DGMayor** [comment]
nzb.su issues seem to be resolved, thanks!

**Comment by thewindupboy** [comment]
Or I get stuff like this after a long time:
Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 192, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=issue)
  File "/Applications/Mylar/mylar/mb.py", line 145, in findComic
    comicResults = searched.getElementsByTagName(type) #('volume')
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'

**Comment by evilhero** [comment]
@thewindupboy: it depends on what else is going on, but normally it's under 20s from start to finish. 

If it's longer than its probably due to you hitting the api limit for comicvine and it has to wait - or it encountered an error and hangs (only fix for any type of error is to always restart mylar)

**Comment by thewindupboy** [comment]
Cool, tbanks!

**Comment by tcn33** [comment]
I am also seeing this error.

```
2015-06-08 09:50:09	ERROR	Unable to download nzb from link: https://api.nzb.su/api?apikey=foo&t=get&id=bar [https://api.nzb.su/getnzb/bar.nzb&i=uid&r=foo]
```

I have tried installing pyOpenSSL, pyasn1 and nag-httpsclient as suggested earlier in the thread, and also [backports.ssl] (https://github.com/alekstorm/backports.ssl) as suggested somewhere else - no go. Not real sure how to use pyenv and a bit reluctant if it may not even fix the issue - is this definitely an SNI issue or still potentially something within Mylar?

**Comment by evilhero** [comment]
@tcn33 : what version of python are you running ? 

SNI support is only in python > 2.7.7, and preferably 2.7.9 (or 2.7.10 as that has some bugfixes) should be the choice if you're having to use pyenv to setup a virtual python environment. I'm pretty sure nzb.su falls under the SNI umbrella, but I don't use them so I really wouldn't know off hand.

**Comment by tcn33** [comment]
@evilhero I'm on 2.7.6, though I understood from your [comment] (https://github.com/evilhero/mylar/issues/1018#issuecomment-103576326) above that adding these packages was a workaround.

**Comment by evilhero** [comment]
It was an unconfirmed workaround from the maintainer of the requests package. The whole SNI thing pretty much broke everything related to python that's an older version, installing the packages was something that could be tried in an attempt to solve things, before having to consider upgrading python. And because python is so interwoven on linux-based machines, it's not just as simple usually as installing - that's why pyenv works so well for those that don't want to upgrade their base OS for fear of breaking things. 

As an example, I'm running Ubuntu 12.04, which has python 2.7.3 - because of the SNI problems, I would have had to install 2.7.9, which would have really broken my system. With pyenv, I have Mylar running 2.7.9, my base python is 2.7.3, and I even have various other apps using different versions of python (I have 5 different flavours installed including python 3 and python 2.6 all for testing purposes)

**Comment by tcn33** [comment]
Okay, thanks. Can I ask what the most practical method is for using pyenv in this case - would I just add something like ``` pyenv local 2.7.9 ```to /etc/init/mylar.conf?

**Comment by evilhero** [comment]
If you want to change just mylar to run that flavour of python, then you need to replace python in the exec line to point to the pyenv shim path.

**Comment by tcn33** [comment]
That did the trick. Thanks so much for your help :+1:

**Comment by thewindupboy** [comment]
Hey, I'm getting this again:

Empty NZB file api?apikey=3a249970291f12a7c6b89fd0e2d90fb8&cmd=downloadNZB&nzbname=Ghost.Racers.001.2015.Digital.BlackManta-Empire.nzb.nzb [http://0.0.0.0:8090/api?apikey=3a249970291f12a7c6b89fd0e2d90fb8&cmd=downloadNZB&nzbname=Ghost.Racers.001.2015.Digital.BlackManta-Empire.nzb]

Did the last update undo some changes you made?

**Comment by thewindupboy** [comment]
The output from Mylar

10-Jun-2015 20:27:17 - INFO :: SEARCH : Download URL: https://api.nzb.su/api??apikey=a18ababfdab1bc33fc1f106f4b95b949&t=get&id=4e23545db89c4304e23d12e9e4287fc9 [VerifySSL:True]
10-Jun-2015 20:27:18 - INFO :: SEARCH : Found Ghost Racers (2015) issue: 1 using nzb.su
10-Jun-2015 20:27:18 - INFO :: SEARCH : Successfully sent nzb file to SABnzbd
10-Jun-2015 20:27:18 - INFO :: SEARCH : setting the nzbid for this download grabbed by nzb.su in the nzblog to : 4e23545db89c4304e23d12e9e4287fc9
10-Jun-2015 20:27:18 - INFO :: SEARCH : [UPDATER] Updating status to snatched
10-Jun-2015 20:27:18 - INFO :: SEARCH : [UPDATER] Updated the status (Snatched) complete for Ghost Racers Issue: 1

**Comment by evilhero** [comment]
It's a new bug from the last development commit due to some other issues. 

There are a few things you can try until I can get a fix out :
- enable the mylar API in the configuration, generate a key, and save/restart mylar. 
- make sure your HOST in the mylar configuration is using the actual ip of the machine and not localhost/0.0.0.0 (note that if the ip change works, you'll have to change your AutoProcesscomics.cfg to have the exact same ip as in mylar)

**Comment by thewindupboy** [comment]
I'll just wait until the fix :)

**Comment by thewindupboy** [comment]
This is working fine for me now, thanks!

**Comment by wschlotter** [comment]
I'm getting a similar error. I have updated to python 2.7.9 not sure what else to do, any help is appreciated.

![mylar_nzbsu_issue](https://cloud.githubusercontent.com/assets/10885290/9890983/c3df3d82-5bc8-11e5-8eca-f5710c18c4ba.png)

**Comment by wschlotter** [comment]
Having similar issues. Updated to python 2.7.9. Any help is appreciated.

![mylar_nzbsu_issue](https://cloud.githubusercontent.com/assets/10885290/9891020/f7243436-5bc8-11e5-9597-7b40bce3bd96.png)

**Comment by wschlotter** [comment]
After looking at the settings again. I realized that i was using the wrong API key.
