### ISSUE TITLE
Error fetching Dognzb 

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1019]
I get this in the log. My Api key is correct. Not sure what's happening. 

Any ideas?

WARNING Error fetching data from dognzb:

**Comment by psychoflame** [comment]
Dog Api has been having problems. It's been returning requests with empty fields. Been a problem for awhile now. They've been trying to fix it. Using experimental plus usernet crawer has worked for me as a backup if you need one

**Comment by lostkt87** [comment]
Ok, I've noticed it for awhile, just never said anything. Till now. Thanks! I'll add them
