### ISSUE TITLE
Won't load after restart - Illegal cookie name

### ISSUE THREAD

**Issue by DGMayor** [evilhero/mylar#1020]
After we talked about restarting to fix the log, I"m now getting this (restarted at least twice).

400 Bad Request

Illegal cookie name __utma

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 610, in respond
    self.process_headers()
  File "C:\Mylar\cherrypy\_cprequest.py", line 710, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name __utma')

**Comment by evilhero** [comment]
Never saw that before, but could try one/both of two things :
- clear your cookies from your browser 
- use firefox/chrome

**Comment by DGMayor** [comment]
Strange.  I replied to this and closed it minutes after you replied, but here it is..


I am using chrome, and clearing the cookies worked.  Not sure why I didn't do that to begin with.
