### ISSUE TITLE
Can we have search results sorted with exact match first?

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1022]
When I search for something like "Fables", I get 76 results, and the actual comic named "Fables" is on the 3rd page.  Is there a way to have the exact match show up first?

**Comment by evilhero** [comment]
Unfortunately with single word series there isn't an exact match search available via comicvine. If it was more than one word you could use the Explicit Search button in the search results page, but it's dependent on comicvine and their search returns leave a lot to be desired sometimes (try searching for Batman and see what I mean)
