### ISSUE TITLE
Not Finding Issues

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#1023]
I think my file naming system broke something again. 

I name files  "series Vol.2015 #01 (January, 2015)

I think that Vol.2015 is causing the problem.....sorry

Here is the log entry

http://pastebin.com/yxkESWCz

**Comment by evilhero** [comment]
Looks like it doesn't like the Vol. portion for some reason, I'll look into it and see what I can figure out.

**Comment by kev0153** [comment]
I took that Vol. out of my naming scheme, seemed to cause too many problems.

**Comment by kev0153** [comment]
looks like it is fixed thanks
