### ISSUE TITLE
Torrent Problems

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1025]
Hi, 

Each torrent that mylar grabs from KAT won't load in the watch directory for transmission. This is probably because the contents of the torrent file on the disk are this:

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.7.10</center>
</body>
</html>

Any idea what's going on here? Is there a provider URL somewhere that needs to be changed?

**Comment by glberen** [comment]
Oh, it looks like GIT renders the HTML above. Sorry. It's just a simple HTML document from nginx with the 404 error. 


</html>

**Comment by evilhero** [comment]
You're using a python version less than 2.7.9 I'm guessing right? (probably 2.7.6)

I wonder if it's because I forced the https in the default... 

Are you using a kat proxy within mylar (in the config.ini, the kat_proxy field)? 

If you're not can you put in the following for the kat_proxy field (make sure mylar isn't running) :

kat_proxy = http://kat_proxy.me/

And save the config.ini and start up mylar and see if that works.

**Comment by glberen** [comment]
Yes, I'm on 2.7.6. I was not using a proxy. I added the proxy into the config file, but it didn't change the behavior at all. Do I need to move to 2.7.9?

**Comment by evilhero** [comment]
Honestly, I hate saying that people should update to 2.7.9, but that does seem to solve a lot of issues in relation to this type of problem. 

I think I might know what's the problem, but I need confirmation and if I'm right it's going to take a few days for me to get a fix out. 

 You can try this, and in doing so will help me out too :
- leave the kat_proxy entry as I mentioned above. 
- disable the RSS option in mylar and disable all your other providers except for KAT. 
- save the configuration and restart Mylar. 
- Directly search for a given issue by clicking on the magnifying glass in the options column in the comic details page . 

If I'm right, it should pull it down and send it to your watch directory in the correct format.

**Comment by glberen** [comment]
Nope, still the same problem. I turned off experimental search as well since I had that on, but it didn't make any difference.

**Comment by evilhero** [comment]
Is it a simple thing for you to update to 2.7.9 then?  I know you can use the awesome package 'pyenv'  which let's you sideload various flavours of python, so it doesn't mess up your main version of python (important if you run some *nix systems since python is integral to the OS and updating can mess things up)

**Comment by glberen** [comment]
I'll try the pyenv and see how that works. It's an ubuntu 14.04 vm, so I think 2.7.6 is baked into a lot of stuff.

**Comment by evilhero** [comment]
Yep, I run ubuntu 12.04, so my default is 2.7.3. The pyenv works great for python specific application loading - if you need a hand with it, I could probably help out too (the information is pretty good out there for it as well)

**Comment by glberen** [comment]
Ok, so I got it setup and I installed 2.7.9. I created a .python-version file containing 2.7.9 in the mylar app directory and restarted mylar. Tried the manual download the resulting torrent file is still the 404 error. How can I verify that mylar is using 2.79? pyenv local run from within the mylar directory returns 2.7.9

What else can I try? This is a fairly recent problem as Mylar had been working. I guess it started a couple of weeks ago, but I can't pinpoint a date.

**Comment by evilhero** [comment]
If you go to the configuration tab and in the first tab within it will indicate the python version it's being run against.

**Comment by glberen** [comment]
Ok, I figured it out. I changed the path of the python binary in /etc/defaults/mylar to include the pyenv shim. That allowed the correct version of mylar to load. And the torrents it dumps into the watch directory have data now. Thanks for your help! Also thanks for pointing me to pyenv. That's going to a real help for many things.

**Comment by glberen** [comment]
Should I leave the RSS feed search turned off?

**Comment by evilhero** [comment]
No, you should turn it back on.. A lot of power that mylar has when it comes to searching is monitoring /caching the feeds for quicker search results.
