### ISSUE TITLE
[Request] Add reading list support to API

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#1029]
I was looking through the Mylar API and from what I can tell it doesn't have reading list support.  It would be great if the reading list could be accessed via the API.  That would allow a comic reader app that decided to integrate your API to display the list so the user could easily keep track of it and even download comics directly from it using the API.

**Comment by evilhero** [comment]
Yep it's definitely doable, but the api in its current state is a complete train wreck. There's been a gent who has been trying to get the api usable for his app to use it and bad submitted a few PR's in that regards, so it's shaping up - but it needs a pretty good overhaul (I'm pretty sure I just copied the headphones api at the time and changed a few things to see if it would work).
