### ISSUE TITLE
Enhancement Request: Comicvine ID search

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1031]
Hi!
I was wondering, the search tool has some problems (like searching for things with a hyphen such as A-Force), and can take a while.  Both of these (I suspect) may be issues at the comicvine end, which wouldn't be surprising.  But the first could be solved by adding a 'search by comicvine id' option.
That way, I could add The Authority, for example, by putting in 4060-40399

Just a thought.

**Comment by evilhero** [comment]
Is already present ;) 

Just plunk in the 4050-40399 (it will only accept 4050's, anything else is not a volume) into the search box at the top of every page. Mylar will assume you know what you're doing an auto-add the series into your watchlist.

**Comment by thewindupboy** [comment]
YAY!!!
