### ISSUE TITLE
Just a doublecheck: mylar on Windows?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1032]
I'm kind of fed up with the video/display issues that Ubuntu is going through. I am considering starting over with Windows Media Center. Just checking on my favorite programs: Does Mylar install and run on Windows without any issues?

**Comment by evilhero** [comment]
Just make sure you're running python 2.7.9 as earlier versions are causing some problems with https related provider sites. Aside from that, everything else should work just fine on Windows.

**Comment by AtariBaby** [comment]
I am moving my config file over, but I guess I better not do this with database file, because the file directories are all changed...

**Comment by evilhero** [comment]
You can move the db file over (as well as all the .jpgs in the cache directory), you just have to change 2 settings in the config.ini and mylar will change all the comic location paths for all your watchlist series to a new path and it will even enforce your Folder Format on all the new locations (within the mylar.db, it doesn't touch your file system at all)

**Comment by AtariBaby** [comment]
wow you really are an evil hero! I’ll try it.

**Comment by evilhero** [comment]
I'm trying to find the link on the forum with the instructions lol

**Comment by AtariBaby** [comment]
I'll try it, though I had already moved things and updated directories in config.ini

What's the command to start it up without a running command prompt? I Have the vbs file for startup working, but don't know how to manually kick it on

**Comment by evilhero** [comment]
Should be able to just execute 'python Mylar.py' in the root directory of mylar.

**Comment by AtariBaby** [comment]
how do you do that in windows lol

**Comment by evilhero** [comment]
Command prompt, cd into mylar directory and execute the cmd (don't close the command window as that will close mylar as well)

**Comment by AtariBaby** [comment]
yeah but that sets the command prompt window to flying with lots of text right?

hey sorry for being lazy. in autoprocesscomics cfg i use my mylar username and password and what do I put in "web root"?

**Comment by evilhero** [comment]
Yeah you'll get console spam but only cause it's logging directly to the console window. 

Leave Web root blank if you don't have a reverse proxy or the like (meaning you don't access it like: http:/localhost/mylar/index.html)

**Comment by Hellowlol** [comment]
If you want to open mylar without console window right click choose open with, find pythonw.exe

**Comment by AtariBaby** [comment]
oh thanks. I'll try it.

Guys I'm stuck. If I force a search of a comic, Sab says "Trying to fetch NZB from http://0.0.0.0:8090/api?apikey=(deleted)&cmd=downloadNZB&nzbname=Injection.001.2015.digital.Son.of.Ultron-Empire.nzb

with a 60 second countdown that just keeps repeating. What do you think?

**Comment by evilhero** [comment]
Sab and mylar are on same machine? 

Make sure you're running latest development branch as well.

**Comment by AtariBaby** [comment]
They are.

**Comment by AtariBaby** [comment]
ed754796fc5c97605e2e276e65a603123e4e41a0

**Comment by evilhero** [comment]
What version of python are you running now?

**Comment by AtariBaby** [comment]
2.7?

**Comment by evilhero** [comment]
Ok, this should have been resolved in the latest dev commit - but you can try one/both of these to see if it works:
- set the IP for mylar to be the actual IP of the machine (not 0.0.0.0)

If that doesn't work, then try enabling the api within the mylar configuration, generating a key, and then saving the configuration and restarting mylar.

Just let me know if ether/both of those work so I can look into this more, as there were reports back today that everything was working again...

**Comment by AtariBaby** [comment]
ah. i think i had to do this before.

I am also seeing a lot of things in the command prompt scroll about do rollover being unavailable, not sure if that's important

**Comment by evilhero** [comment]
the rollover for logging ?

**Comment by AtariBaby** [comment]
yeah something like doRollover in handler.py or something. going very fast so hard to see what it says

**Comment by AtariBaby** [comment]
Okay, that worked. Now I'm getting
```
Top of Form 1
Bottom of Form 1
           Loading config from C:\Scripts\autoProcessComics.cfg
Opening URL: http://localhost:8090/post_process?nzb_name=Nameless.003.2015.Digital.Mephisto-Empire&failed=0&apc_version=1.0&comicrn_version=1.01&nzb_folder=C%3A%5CUsers%5Cxboxl_000%5CDocuments%5CDownloads%5Ccomplete%5CNameless.003.2015.Digital.Mephisto-Empire
Unable to open URL:  [Errno socket error] [Errno 10061] No connection could be made because the target machine actively refused it
```

**Comment by AtariBaby** [comment]
maybe i need to edit the cfg file with local ip address too?

**Comment by evilhero** [comment]
yep you need to make sure whatever IP you put in for the configuration for mylar, you need to duplicate it in the autoProcessComics.cfg file.

So you just changed the host ip of mylar to the ip of the machine ?

**Comment by AtariBaby** [comment]
yes that's right. from "localhost"

**Comment by evilhero** [comment]
You 'might' want to try and use '0.0.0.0' instead - that way you can access it via the machine's actual IP  on any machine in your network (as well as using localhost). That is, unless you tried that one already ;)

**Comment by AtariBaby** [comment]
i didn't, although is it that way by default in mylar's configuration webpages? I might have been mistaken. but i'll try. it seems to work now! I can use the ip address of that computer and see mylar now, so not sure I need that 0.0.0.0

**Comment by evilhero** [comment]
Yep, no it's fine either way  - there are some users that don't like to manually enter in the IP of the machine (I'm guessing because it's dynamic and not a static IP probably). But if you gots it working, that's the good news!

**Comment by AtariBaby** [comment]
oh i see. yeah i'm all about the static ip's lol thanks as usual

**Comment by AtariBaby** [comment]
sorry, I'm sure you get asked this all the time: I'm seeing a lot of "500: request limited reached". Does this indicate something is wrong with my comic vine api or something?

**Comment by evilhero** [comment]
Depends on what you're doing when you get the 500 error. Your api usage is indicated at the bottom of every page in mylar (the hits/15mins),so as long as you're not over 400/15mins you should be fine... unless you're using the same api in different applications which mylar can't account for (it only tracks mylar usage since comicvine doesn't let you track global api hits).

**Comment by AtariBaby** [comment]
does “enable API” need to be checked, or is that for the mylar api?

**Comment by AtariBaby** [comment]
Here's another problem I just got.

2015-06-13 10:06:37	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.

But I have two or three things in there!

**Comment by AtariBaby** [comment]
And do these config ini lines look right to you?

provider_order = dognzb, Experimental, 1, dognzb, 2, nzbplanet

[DOGnzb]
dognzb = 1
dognzb_apikey = (api key deleted))
[Experimental]
experimental = 1
altexperimental = 1
[Newznab]
newznab = 1
extra_newznabs = nzbplanet, http://nzbplanet.net, (api key deeted), (username deleted), 1

**Comment by evilhero** [comment]
You enabled/disabled/added to the configuration and didn't restart mylar after a save. Shutdown mylar, edit the config.ini and delete the provider_order line from the .ini. Then save and start up mylar and that provider error will be gone.

**Comment by evilhero** [comment]
The enable api in the configuration is for mylar, there's a spot just above that in the configuration for thr comicvine api Key.

**Comment by AtariBaby** [comment]
yeah, getting the "500 error limit reached". I got about 4 comics downloaded after your help last night, and it looks like that's been going on since.

**Comment by AtariBaby** [comment]
FYI I've been down for 2 or 3 weeks due to rebuilding server as windows instead of ubuntu. Hence my million questions since last night.

**Comment by AtariBaby** [comment]
but well, it's downloading new titles i'm adding!

**Comment by evilhero** [comment]
Downloading doesn't use the CV api though, whereas searching, adding, updating the pullist, story arcs all utilize the api key.

**Comment by AtariBaby** [comment]
Ah. Any cause for concern?

**Comment by evilhero** [comment]
Well if you're getting 500 errors, it would mean that you're either hitting your API limit on Comicvine, or you're possibly hammering it (although I've never seen that occur before, but hey - there's a first for everything)..

Can you post the exact error you're getting ?

**Comment by AtariBaby** [comment]
'''
2015-06-13 11:37:29	INFO	pausing for 60 seconds before continuing to avoid hammering
2015-06-13 11:37:29	INFO	Shhh be very quiet...I'm looking for FBP Federal Bureau of Physics issue: 15 (2015) using nzbplanet (newznab)
2015-06-13 11:37:29	INFO	Alternate Search pattern detected...re-adjusting to : FBP Federal Bureau of Physics 2015
2015-06-13 11:37:29	ERROR	[ERROR CODE: 500] Request limit reached
2015-06-13 11:36:28	INFO	pausing for 60 seconds before continuing to avoid hammering
2015-06-13 11:36:28	ERROR	[ERROR CODE: 500] Request limit reached
2015-06-13 11:35:27	INFO	pausing for 60 seconds before continuing to avoid hammering
2015-06-13 11:35:27	INFO	Shhh be very quiet...I'm looking for FBP: Federal Bureau of Physics issue: 15 (2015) using nzbplanet (newznab)
'''
Do you require stuff from the actual log files, Captain?

**Comment by evilhero** [comment]
ooh that's an nzbplanet error - you've maxed out your api there it looks like. (or you're requesting too fast - but I doubt that's it since a minute between searches is alot more than many other automated type programs).

**Comment by AtariBaby** [comment]
ahh, okay. that makes sense. i should probably find a more generous free supplement to my vip dognzb

**Comment by AtariBaby** [comment]
So I think I have one more question then I’m done harrassing you. What is the best command to tell Mylar to go back and catch me up on the new issues of already added titles that I missed in recent weeks?

**Comment by evilhero** [comment]
If your machine was offline for awhile, probably you would need to do the Force Search option. Once it's done that once though, you'd be 'up-to-date' on any backlog searches and just letting mylar poll the rss feeds every 20 minutes would be enough to keep you up-to-date of any new changes (kinda like sonarr does now, and mylar will be moving more towards this type of searching in the weeks/months to come)...

I would do a 'Force Update Active Comics' from the Manage tab/Advanced options first though to make sure all of your series are up-to-date and current with all the issues listed. Once that's done, then do the Force Search ;)
