### ISSUE TITLE
Story Arc issues that aren't in watch list

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1033]
I am a big event reader so will often add just an event into the story arc management area.

When I have Mylar search for missing issues, it will find the missing issues across different series and download them. At that point, since they aren't in my wathclist, they never get post processed and moved to the story arc folder, they just sit in my downloads folder. If I add the series to the watchlist it will then post process them and move them to that series' folder, but still won't go into the story arc folder unless I then manually tell it to check against the watch list.

Would it be possible to have comics moved into their correct story arc folder, if they were downloaded from the story arc checking for new issues, even if the series is not in the watch list?

Thanks a million!

**Comment by evilhero** [comment]
The should be occurring now as it is - as long as the download was initiated from the story arc page (meaning clicking on 'grab it', or doing the Search for Missing option). I've used this myself recently and didn't encounter any errors and the issue got moved into the story arc folder since it didn't exist on the watchlist. 

Do you have the option to store issues in the story arc directory enabled? Does the directory exist with the correct permissions (meaning the user who runs mylar has to have fill access to the story arc folder)?

**Comment by kurnalbert** [comment]
I do have the option to store issues in the story arc directory. If the issues are in the watch list, then they get moved without issue.

The directory already exists with a large number of issues already in it, moved there by Mylar and the logged in user has all of the correct permissions on the folder.

When Mylar runs the folder monitor it only shows this:

28-May-2015 08:35:56 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder /Users/tv/Downloads for newly snatched downloads
28-May-2015 08:35:58 - INFO :: FOLDERMONITOR : [POST-PROCESSING] No matches for Manual Run ... exiting.
28-May-2015 08:35:58 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Finished checking for newly snatched downloads
28-May-2015 08:35:59 - INFO :: FOLDERMONITOR : delaying startup thread for 60 seconds to avoid locks.

This is after having just downloaded two new issues from the Story Arc page by clicking search for missing. Mylar does not seem to recognise them until the series they belong to is added to the watch list.

Thanks for your reply!

**Comment by evilhero** [comment]
How are you downloading the issues - via nzbs or torrents? 

I can see now that if it's via torrents then it might not match up to the arcs properly, but using nzbs it should be working (at least for me). Manual post-processing is a completely different beast, so if it's via torrents / manual post-processing  (which from what you're describing would seem to fit), I'll have to fix some things up for it pick up the arc properly.

**Comment by kurnalbert** [comment]
It is through torrents that I'm downloading them.

Good to hear at least it's nothing something I've done wrong. I am using the development branch so I shall make sure to look out for the fix when it's added.

Thank you again for looking at this for me!

**Comment by blindguy** [comment]
I am having this same problem and I use nzb's and I have the same problem.  I also have problems where it won't create the proper folder due to strange characters in the name such as 'Earth 2: World's End' it does not like the :  .

I have the 'Should I create a Story-Arc Directory?' checked off.

**Comment by evilhero** [comment]
Manual post-processing issues that exist within a story arc isn't working currently, regardless of how it was initially downloaded (it's requiring alot more backend changes than originally expected due to how everything is integrated amongst issues).

The folder creation I'll check into - it should be following the same restrictions/replacing non-allowable characters as in normal directory creation, so that's a new one.

**Comment by kurnalbert** [comment]
Just wanted to update this. It now seems that if a file is in the watch list, it will automatically get moved to the correct directory and to the correct story arc directory.

However, if the issues is just in the story arc and not in the watch list, it will attempt to name the file with the entire location to the path instead of just the file itself as seen here:

This is for the comic Armor Wars 001 when it is just in the story arc and not in the watch list:

25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder /Users/tv/Downloads for newly snatched downloads
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : Issue Number :001
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : ReleaseDate: 2015-06-03
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : IssueDate: 2015-08-31
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [Armor Wars #1] MATCH: /Users/tv/Downloads/Armor Wars #001 (2015).cbr / 490877 / 490877
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : Issue Number :001
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : ReleaseDate: 2015-06-03
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : IssueDate: 2015-08-31
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Enabled for Secret Wars
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars
25-Jun-2015 10:30:49 - INFO :: FOLDERMONITOR : [POST-PROCESSING] Moving /Users/tv/Downloads/Armor Wars #001 (2015).cbr into directory : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars/046-/Users/tv/Downloads/Armor Wars #001 (2015).cbr
25-Jun-2015 10:30:49 - WARNING :: FOLDERMONITOR : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.

This is for the comic Armor Wars 001 when it is in the story arc and also in the watch list:

25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder /Users/tv/Downloads for newly snatched downloads
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : Issue Number :001
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : ReleaseDate: 2015-06-03
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : IssueDate: 2015-08-31
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] IssueID 490877 exists in your watchlist. Bypassing Story-Arc post-processing performed later.
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : Issue Number :001
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : ReleaseDate: 2015-06-03
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : IssueDate: 2015-08-31
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [DUPECHECK] Duplicate check for /Users/tv/Downloads/Armor Wars #001 (2015).cbr
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [POST-PROCESSING] [1/1] Starting Post-Processing for Armor Wars issue: 1
25-Jun-2015 10:31:50 - INFO :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media /eBooks/Comics/Armor Wars (2015)
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Armor Wars issue: 1
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][FILE-RESCAN] Now checking files for Armor Wars (2015) in /Volumes/Media /eBooks/Comics/Armor Wars (2015)
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][FILE-RESCAN] Now checking files for Armor Wars (2015) in :Armor Wars (2015)
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][FILE-RESCAN] Updated the status of 1 issues for Armor Wars (2015) that were not found.
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][FILE-RESCAN] Total files located: 1
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][FILE-RESCAN] I have physically found 1 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 1 / 2 ]
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : Watchlist Story Arc match detected.
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars
25-Jun-2015 10:31:52 - INFO :: FOLDERMONITOR : [POST-PROCESSING] Copying /Volumes/Media /eBooks/Comics/Armor Wars (2015)/Armor Wars 001 (2015).cbr into directory : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars/046-Armor Wars 001 (2015).cbr
25-Jun-2015 10:31:53 - INFO :: FOLDERMONITOR : [POST-PROCESSING] Post-Processing completed for: Armor Wars issue: 1
25-Jun-2015 10:31:53 - INFO :: FOLDERMONITOR : [POST-PROCESSING] Manual post-processing completed for 1 issues.

When it is not in the watch list and it fails to move, it also does not tag any metadata to the file either.

**Comment by evilhero** [comment]
Not what you want to hear - but I can't duplicate this :(  I've tried it with manual post-processing, and doing the folder-check method, both of which were done with story arc issues that did not exist on the watchlist, and it named it properly and moved it.

So what it tells me, is that it's probably some configuration option that you have enabled, that's causing the duplicate paths to happen - the only one being if you have the 'Arcs in Grab-bag directory' option enabled.

What would really help in this case is if you could post the mylar.log showing the post-processing run - I need to see the debugging levels so I can try and figure out where the paths are getting altered incorrectly, as the information levels don't provide that kind of information.

**Comment by kurnalbert** [comment]
Thank you for looking into this for me.

From the mylar.log it was returning the following:

25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.
25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Enabled for Secret Wars
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Story Arc Directory set to : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars
25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName:/Users/tv/Downloads
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] WARNING:  cannot find the unrar command.
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] File conversion and extension fixing not available
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] You probably need to edit this script, or install the missing tool, or both!
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file.
25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] readingorder#: 78
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Destination Path : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars/078-/Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:20:55 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Source Path : /Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [POST-PROCESSING] Moving /Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr into directory : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars/078-/Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:20:55 - WARNING :: FOLDERMONITOR : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
25-Jun-2015 14:20:55 - INFO    :: FOLDERMONITOR : [FOLDER-CHECK] Finished checking for newly snatched downloads

Having seen that I added shortcuts to the far and unrar commands in /usr/local/bin. After that it now converts the file into a rar but doesn't go any further. It now produces these entries in the log:

25-Jun-2015 14:25:00 - INFO    :: FOLDERMONITOR : [STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.
25-Jun-2015 14:25:00 - INFO    :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Enabled for Secret Wars
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Story Arc Directory set to : /Volumes/Media /eBooks/Comics/StoryArcs/Secret Wars
25-Jun-2015 14:25:00 - INFO    :: FOLDERMONITOR : [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName:/Users/tv/Downloads
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Paths / Locations:
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] scriptname : Mylar.py
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] downloadpath : /Users/tv/Downloads
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] sabnzbdscriptpath : /Applications/mylar
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] comicpath : /Users/tv/Downloads/temp
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] unrar_folder : /Users/tv/Downloads/temp/unrard
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Running the ComicTagger Add-on for Mylar
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Attempting to create directory @: /Users/tv/Downloads/temp
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Created directory @ : /Users/tv/Downloads/temp
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Filename is : /Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : /Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] moving : /Users/tv/Downloads/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr to /Users/tv/Downloads/temp/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Mylar.py: converting Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbr to be zip format
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] {0}: Comicpath is /Users/tv/Downloads/temp/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).rar
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] {0}: Unrar is /Users/tv/Downloads/temp/unrard
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: [Errno 8] Exec format error
25-Jun-2015 14:25:00 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "/Applications/mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/Applications/mylar/mylar/PostProcessor.py", line 1521, in run\n    result = PostProcess.Process()\n  File "/Applications/mylar/mylar/PostProcessor.py", line 550, in Process\n    metaresponse = cmtagmylar.run(self.nzb_folder, issueid=issueid, filename=ofilename)\n  File "/Applications/mylar/mylar/cmtagmylar.py", line 262, in run\n    output = subprocess.check_output([unrar_cmd, \'x\', baserar])\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output\n    process = Popen(stdout=PIPE, *popenargs, **kwargs)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__\n    errread, errwrite)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child\n    raise child_exception\nOSError: [Errno 8] Exec format error\n'
25-Jun-2015 14:25:01 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
25-Jun-2015 14:25:01 - INFO    :: FOLDERMONITOR : delaying startup thread for 60 seconds to avoid locks.

**Comment by kurnalbert** [comment]
An update to this. After moving the actually rar and unrar commands to the /usr/local/bin folder and not shortcuts, it is now correctly moving the files to the correct story arc folder.

The last thing although it is minor, it prepends the reading order number to the beginning of the file as I have enabled in settings, however it doesn't tidy up the rest of the name as it normally does when moving to the watch list comic folder. This is a minor thing so if it doesn't affect anyone else or it is a lot of work, then no need to worry about it!

**Comment by evilhero** [comment]
I was going to say you probably needed to move those files directly,  or make use of the unrar_cmd option in the config.ini which lets you provide the path to your unrar binary. But regardless, glad you were able to get it to work!

By tidying up, do you mean that it's not renaming the file as per the file format you have configured?

**Comment by kurnalbert** [comment]
That's correct. If the comic is also in the watch list, it goes through the watchlist processing first, gets renamed as per the file format and then that correctly named file is copied into both the watchlist comic folder and the story arc folder.

When it is not in the watch list, it will add the meta tags, prepend the reading order number and then copies that file without renaming the rest of the file following the file format.

**Comment by evilhero** [comment]
Gotcha, that should be an easy fix so expect it in the next development commit which should go up either today or tomorrow.

**Comment by kurnalbert** [comment]
You're a hero, thank you so much!
