### ISSUE TITLE
NZBMegaSearch Search URL Broken?

### ISSUE THREAD

**Issue by TBhimdi** [evilhero/mylar#1037]
As of a week or two ago, Mylar stopped getting issues for me. I only have NZBMegaSearch added as my search provider.

At first I thought it was an NZBMegaSearch issue since it hasn't been updated in 2 years:
https://github.com/pillone/usntssearch

So I updated to the new fork:
https://github.com/thezoggy/usntssearch

Didn't fix the issue.

Here's the relevant log details from Mylar:

```
31-May-2015 12:51:25 - DEBUG   :: Thread-12 : nzbname used for post-processing:Saga.028.2015.Digital.Zone-Empire
31-May-2015 12:51:25 - DEBUG   :: Thread-12 : [newznab] link: https://example.com:5000/warp?x=k35aJ3eYRIZ9S35Ohd68Avg8lKmy4voaSjrfRTeIAd6v4C9fed594VMtGK6vGCQ04cbxGcMTGKo9GKsaRKpYAf4rEcmtN24IEd6vAKuCeKu0ACQB4cuCec9BATmqGTh0NdepAdWT4Ceq
31-May-2015 12:51:25 - DEBUG   :: Thread-12 : payload:{'apikey': 'XXX', 't': 'get', 'id': ''}
31-May-2015 12:51:25 - INFO    :: Thread-12 : Download URL: https://example.com:5000/api?apikey=XXX&t=get&id= [VerifySSL:False]
31-May-2015 12:51:25 - ERROR   :: Thread-12 : Unable to download nzb from link: https://example:5000/apiapikey=XXX&t=get&id= [https://example.com:5000/warp?x=k35aJ3eYRIZ9S35Ohd68Avg8lKmy4voaSjrfRTeIAd6v4C9fed594VMtGK6vGCQ04cbxGcMTGKo9GKsaRKpYAf4rEcmtN24IEd6vAKuCeKu0ACQB4cuCec9BATmqGTh0NdepAdWT4Ceq]
31-May-2015 12:51:25 - INFO    :: Thread-12 : Could not find Issue 28 of Saga(2012) using NZBMegasearcH
31-May-2015 12:51:25 - INFO    :: Thread-12 : Finished searching via :api. Issue not found - status kept as Wanted.
```

**Comment by evilhero** [comment]
Mylar regenerates the complete download url from scratch in order to accommodate https entries, retries and api changes.  Based on that entry, it looks like there is no ID being passed back to mylar in a format mylar understands.

**Comment by evilhero** [comment]
^^Update: Ok, I grabbed the newest version of nzbmega, tested it out (failed in the identical spot as originally posted). So I made some changes within Mylar and tested it out again, grabbed from nzbmega fine, and got it to tag it with the unique id as well so that Failed marking / direct retries are now possible.

Expect in next development commit...

**Comment by TBhimdi** [comment]
Thank for the amazingly quick response and fix.

**Comment by razambon** [comment]
Hrm.....this was working for me and I just updated today and now Mylar is sending oddball NZB URLs to Sab.  (Trying to fetch NZB from http://0.0.0.0:8090/api?apikey=[KEY IS HERE]&cmd=downloadNZB&nzbname=Conan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb)

**Comment by evilhero** [comment]
Mylar downloads the nzb first and makes sure it's valid - so in this case it downloaded the nzb using nzbmegasearch. It then opens up a random api for itself, and sends a internal api link (it's a random apikey that has nothing to do with the mylar api within the configuration) to the downloaded nzb. 

The only problem that would occur is if your mylar instance is listening on localhost or 0.0.0.0.0 and your sabnzbd is on another machine (then you have to specify the actual ip of mylar within the configuration)

**Comment by razambon** [comment]
They are both on the same machine and this just started a few minutes ago
after updating Mylar.   Never seen this happen before...let me try just
configuring the IP anyway.

**Comment by razambon** [comment]
Just updated to an actual IP from 0.0.0.0, and still not working.  When retrying to add from the history section, it's doing the same thing and I'm seeing this error in the log:

2015-06-08 23:18:50 	ERROR 	Uncaught exception: Traceback (most recent call last):
File "C:\Program Files\mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 761, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Program Files\mylar\mylar\webserve.py", line 1221, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
File "C:\Program Files\mylar\mylar\search.py", line 2033, in searcher
notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
File "C:\Program Files\mylar\mylar\search.py", line 2038, in notify_snatch
snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

Completely killed and restarted (vs just restart via the button) and now I'm getting blank NZBs in Sab, with the following error (actual API keys where I put [APIKEYHERE]:
Empty NZB file api!apikey=[APIKEYHERE]&cmd=downloadNZB&nzbname=Amazing.Spider-Man.018.1.2015.Digital.Zone-Empire.nzb.nzb [http://whs:8090/api?apikey=[APIKEYHERE]&cmd=downloadNZB&nzbname=Amazing.Spider-Man.018.1.2015.Digital.Zone-Empire.nzb]

Restarting has everything reprocessing, so I'll have to try again after it gets through checks as it seems to have slowed to a crawl and isn't being responsive...which is odd.  

Here's the detailed log of the process from click on the 'retry' link to error:
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : ComicID:73235
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : Retrying : 489874
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : Located snatched download:
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : --Referencing : experimental @ 2015-06-08 22:50:03
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : fetched via experimental. Retrying the send : http://nzbindex.nl/download/download
08-Jun-2015 23:34:20 - DEBUG   :: Thread-12 : [experimental] link: http://nzbindex.nl/download/download
08-Jun-2015 23:34:20 - INFO    :: Thread-12 : Download URL: http://nzbindex.nl/download/download [VerifySSL:False]
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : [FILENAME] filename (remove chars): NZBIndex-download.nzb
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : [FILENAME] nzbname (\s): NZBIndex-download.nzb
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : [FILENAME] end nzbname: NZBIndex-download.nzb
08-Jun-2015 23:34:21 - INFO    :: Thread-12 : filen: NZBIndex-download -- nzbname: Conan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire are not identical. Storing extra value as : NZBIndex-download
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : Cache Directory successfully found at : C:\Program Files\mylar\cache/
08-Jun-2015 23:34:21 - INFO    :: Thread-12 : prov  : experimental[download]
08-Jun-2015 23:34:21 - INFO    :: Thread-12 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : issues match!
08-Jun-2015 23:34:21 - INFO    :: Thread-12 : Found Conan the Avenger (None) issue: 14 using experimental
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : link given by: experimental
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : send-to-SAB host &api initiation string : http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : ...selecting API type: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : ...attaching nzb via internal Mylar API: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : ...setting priority: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb&priority=-100
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : ...attaching category: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb&priority=-100&cat=comics
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : ...attaching rename script: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : Completed send-to-SAB link: http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
08-Jun-2015 23:34:21 - DEBUG   :: Thread-12 : sab-to-send:http://whs:8080/api?apikey=f3d7e4c6ecde3b91e6106f4c38bae294&mode=addurl&name=http%3A%2F%2Fwhs%3A8090%2Fapi%3Fapikey%3D674fe84bbb37cea52442500c0b79a52b%26cmd%3DdownloadNZB%26nzbname%3DConan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
08-Jun-2015 23:34:22 - INFO    :: Thread-12 : Successfully sent nzb file to SABnzbd
08-Jun-2015 23:34:22 - DEBUG   :: Thread-12 : Found matching comic...preparing to send to Updater with IssueID: 489874 and nzbname: Conan.the.Avenger.014.2015.digital.Son.of.Ultron-Empire [NZBIndex-download]
08-Jun-2015 23:34:22 - INFO    :: Thread-12 : setting the nzbid for this download grabbed by experimental in the nzblog to : download
08-Jun-2015 23:34:22 - INFO    :: Thread-12 : setting the alternate nzbname for this download grabbed by experimental in the nzblog to : NZBIndex-download
08-Jun-2015 23:34:22 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files\mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files\mylar\mylar\webserve.py", line 1221, in retryissue
    sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
  File "C:\Program Files\mylar\mylar\search.py", line 2033, in searcher
    notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
  File "C:\Program Files\mylar\mylar\search.py", line 2038, in notify_snatch
    snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
The retry and error you're getting are related.. The history tab doesn't track the series year for a given series, so when it tries to send the notification that it was snatched it errors out. I'm working on this, but that's a bug. Retrying from the actual series page should work however. 

It looks like retrying and experimental results are messing up.. Can you try retrying from a different provider if you have access, or just try doing a manual search for said issue instead of using the retry option (I'm pretty sure it's the experimental option is buggered up as it's not even storing thr proper ID for the nzb as it should be a numeric not the word 'download')

**Comment by razambon** [comment]
Tried with the NZBMegaSearch provider and same blank nzb issue and the following error:
09-Jun-2015 08:33:36 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files\mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files\mylar\mylar\webserve.py", line 1221, in retryissue
    sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
  File "C:\Program Files\mylar\mylar\search.py", line 2033, in searcher
    notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
  File "C:\Program Files\mylar\mylar\search.py", line 2038, in notify_snatch
    snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

How do I do a manual search for an issue?

**Comment by razambon** [comment]
...found manual searching...now it's giving me an error saying no search providers enabled....odd.

**Comment by evilhero** [comment]
It might not be the same as mylar caches results, so it might be picking an item from the cache. 

Can you try enabling the mylar api within thr configuration, saving and restarting and then trying again? 

For whatever reason, I can't seem to duplicate this at all, even with nzbmegasearch being used.

**Comment by razambon** [comment]
Ok.  That fixed it - everything.  What did that do?  Now I'm getting an
error with post-processing though.

Opening URL: http://localhost:8090/post_process?nzb_name=Amazing.Spider-Man.018.1.2015.Digital.Zone-Empire&failed=0&apc_version=1.0&comicrn_version=1.01&nzb_folder=Z%3A%5CServerFolders%5CDownloads%5C-+Comics%5CAmazing.Spider-Man.018.1.2015.Digital.Zone-Empire
Unable to open URL:  [Errno socket error] [Errno 10061] No connection
could be made because the target machine actively refused it


On Tue, Jun 9, 2015 at 10:52 AM, evilhero <notifications@github.com> wrote:

> It might not be the same as mylar caches results, so it might be picking
> an item from the cache.
>
> Can you try enabling the mylar api within thr configuration, saving and
> restarting and then trying again?
>
> For whatever reason, I can't seem to duplicate this at all, even with
> nzbmegasearch being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/1037#issuecomment-110391359>.
>



-- 
Robert A. Zambon, Ph.D.

**Comment by evilhero** [comment]
Yep, you need to update your AutoProcesscomics.cfg  to have the exact ip as you put in for mylar in the configuration (you mentioned earlier you changed to the actual ip). Since you tagged it now as an actual ip, thr post-processing script had to match.

**Comment by wyldphyre** [comment]
If I read the previous conversation correctly something has gone wrong and the url passed to Sabnzb has '0.0.0.0:8090' in it instead of 'localhost'. If that is the problem then I seem to have it as well.

What are the exact steps to rectify? I don't quite follow what "enabling the mylar api within the configuration" entails. 

Thanks

**Comment by evilhero** [comment]
In configuration / settings / Web interface /basic / host make sure it has the ip of the machine that mylar is running on. 

As far as the api, mylar now uses its own api to send files from mylar to sabnzbd. What's supposed to happen is that mylar generates a unique apikey for each send without requiring that the mylar api is enabled. What seems to be happening is that mylar doesn't generate the key properly unless the api is enabled.

**Comment by wyldphyre** [comment]
Bugger. I set the IP address, but I still have the "empty nzb file" error in Sabnzbd, though at least now the IP looks right.

Any other ideas?

p.s. On a side note I discovered something a little bit horrible. If you set the IP as 'localhost' in the config, you can only get to Mylar by using 'localhost' in the URL. That obviously doesn't work on machines outside the one it's running on.

**Comment by wyldphyre** [comment]
Possibly of help, if I take the URL provided to Sabnzbd (below), I get a page that say "API key not generated".

http://192.168.1.3:8090/api?apikey=9d55d4d1294c2fa6ea38f8621109d1a7&cmd=downloadNZB&nzbname=Injection.002.2015.digital.Son.of.Ultron-Empire.nzb

**Comment by evilhero** [comment]
Have you enabled the api within mylar?  It's a checkbox on the Web Settings tab within the configuration.  Try enabling it, generating an api and then save and restart Mylar for the changes to take effect.

**Comment by wyldphyre** [comment]
Doh. I have now, and verily it is working again. Thanks muchly for the help.

Oh and thanks also for creating and maintaining such a nifty bit of software.

**Comment by evilhero** [comment]
Thanks for the kudos and helping me to confirm that it's the dammed enable api thing that's stopping things from rolling on. I'll be fixing this shortly hopefully, but at least you and others having similar problems have a quick fix around this :)

**Comment by wyldphyre** [comment]
Cool. I'm going to log that 'localhost' problem I ran into as a new issue.
