### ISSUE TITLE
Mixed content over HTTPS

### ISSUE THREAD

**Issue by dotsam** [evilhero/mylar#1042]
Due to the inclusion of http://code.jquery.com/jquery-1.9.1.js in base.html, all pages are served mixed content and not pure HTTPS. In addition, I'm confused as to why query 1.9.1 is included from this external URL, while query 1.7.2 is also included from the local copy in /js/libs/. Can this be cleaned up, and either the external reference removed, or the script source changed to a relative URL: `<script src="//code.jquery.com/jquery-1.9.1.js"></script>`

**Comment by evilhero** [comment]
1.9.1 was being referenced for use in additional fixes / improvements. 1.7.2 is what is currently being utilized and is why it's included in the repo. 

I'm not going to remove either until I can determine if the 1.9.1 is still needed on certain pages or not. But I can change the url to accommodate your request.
