### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1043]
I'm getting this error each time Mylar searches for a comic. Using torrents.
Ideas?

Uncaught exception: Traceback (most recent call last):
File "XXXXXX/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "XXXXXXX/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "XXXXXXX/mylar/mylar/webserve.py", line 1320, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "XXXXXXXXX/mylar/mylar/search.py", line 212, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "XXXXXXXXX/mylar/mylar/search.py", line 1321, in NZB_SEARCH
nzbname = nzbname_create(nzbprov, info=comicinfo, title=entry['title'])
File "XXXXXXXXXXX/mylar/mylar/search.py", line 1634, in nzbname_create
logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment

**Comment by evilhero** [comment]
Post the mylar.log give showing what's occurring prior to the error.

**Comment by glberen** [comment]
2015-06-05 07:50:46	INFO	Shhh be very quiet...I'm looking for The Woods issue: 13 (2015) using experimental [RSS]
2015-06-05 07:50:46	INFO	Could not find Issue 13 of The Woods(2014) using KAT
2015-06-05 07:50:46	INFO	Shhh be very quiet...I'm looking for The Woods issue: 13 (2015) using KAT [RSS]
2015-06-05 07:50:46	INFO	search provider order is ['kat', 'Experimental']
2015-06-05 07:50:46	INFO	Issue Title given as : None
2015-06-05 07:50:46	INFO	Initiating manual search for The Woods issue: 13
2015-06-05 07:50:38	INFO	No series have been marked as being on auto-watch.
2015-06-05 07:50:38	INFO	Finished checking for comics on my watchlist.
2015-06-05 07:50:37	INFO	Checking the Weekly Releases list for comics I'm watching...
2015-06-05 07:50:37	INFO	No new pull-list available - will re-check again in 24 hours.
2015-06-05 07:50:35	INFO	[PULL-LIST] Populating & Loading pull-list data from file
2015-06-05 07:50:35	INFO	Weekly pull list present - checking if it's up-to-date..
2015-06-05 07:50:35	INFO	[WEEKLY] Checking Weekly Pull-list for new releases/updates
2015-06-05 07:50:25	INFO	delaying startup thread for 60 seconds to avoid locks.
2015-06-05 07:50:25	INFO	Enabling folder monitor for : /xxxxxx/comics every 30 minutes.
2015-06-05 07:50:25	INFO	delaying startup thread for 10 seconds to avoid locks.
2015-06-05 07:50:25	INFO	delaying startup thread for 30 seconds to avoid locks.
2015-06-05 07:50:25	INFO	Checking for existance of Weekly Comic listing...
2015-06-05 07:50:25	INFO	Initiating startup-RSS feed checks.
2015-06-05 07:50:25	INFO	Initiating the ComicVine API Checker to report API hits every 5 minutes.
2015-06-05 07:50:25	INFO	Initializing the DB Updater.
2015-06-05 07:50:25	INFO	Starting Mylar on http://0.0.0.0:8090/
2015-06-05 07:50:25	INFO	Writing PID 22982 to /var/run/mylar/mylar.pid
2015-06-05 07:50:25	INFO	Daemonized to PID: 22982
2015-06-05 07:50:25	INFO	Sucessfully ordered 349 series in your watchlist.
2015-06-05 07:50:25	INFO	Remapping the sorting to allow for new additions.
2015-06-05 07:50:25	INFO	Mylar is up to date
2015-06-05 07:50:23	INFO	Comparing currently installed version with latest github version
2015-06-05 07:50:20	INFO	Retrieving latest version information from github
2015-06-05 07:50:20	INFO	Correcting Null entries that make the main page break on startup.
2015-06-05 07:50:20	INFO	Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2015-06-05 07:50:20	INFO	Populating Custom Exception listings into Mylar....
2015-06-05 07:50:20	INFO	Populating Base Exception listings into Mylar....
2015-06-05 07:50:20	INFO	Checking to see if the database has all tables....
2015-06-05 07:50:20	INFO	[DB Module] Loading : as the database module to use.

**Comment by evilhero** [comment]
That's the gui log, I need to see the actual mylar.log file as it holds all the debugging information - the gui only shows informational level of logging.

**Comment by glberen** [comment]
Apologies. Here you go:

05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 007 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 007 (2014) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 007 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 007 (2014) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 001 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 001 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 001 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 001 (2014) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 001 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 001 (2014) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: Sweet Tooth Vol. 01 - Out of the Deep Woods (2010) (TPB) (Digital-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): Sweet Tooth Vol. 01 - Out of the Deep Woods (2010) (TPB) (Digital-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :Sweet Tooth Vol. 01 - Out of the Deep Woods (2010) (TPB) (Digital-Empire). (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 77 - formatrem_torsplit : sweet tooth vol 01 out of deep woods (2010) (tpb) (digital empire)cbr ( nem )
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : Sweet Tooth Vol. 01 - Out of the Deep Woods (2010) (TPB) (Digital-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend:  tooth vol 01 out of deep woods (2010) (tpb) (digital empire) ( nem )
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 008 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 008 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 008 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 008 (2014) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 008 (2014) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 008 (2014) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: Through the Woods (2014) (Digital) (BlurPixel-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): Through the Woods (2014) (Digital) (BlurPixel-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :Through the Woods (2014) (Digital) (BlurPixel-Empire). (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 60 - formatrem_torsplit : through woods (2014) (digital) (blurpixel empire)cbr ( nem )
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : Through the Woods (2014) (Digital) (BlurPixel-Empire).cbr (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: gh woods (2014) (digital) (blurpixel empire) ( nem )
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 009 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 009 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 009 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 009 (2015) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 009 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 009 (2015) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 010 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 010 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 010 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 010 (2015) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 010 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 010 (2015) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 011 (2015) (SD-Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 011 (2015) (SD-Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 011 (2015) (SD-Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 40 - formatrem_torsplit :  woods 011 (2015) (sd digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 011 (2015) (SD-Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 011 (2015) (sd digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: The Woods 012 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): The Woods 012 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :The Woods 012 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 37 - formatrem_torsplit :  woods 012 (2015) (digital empire)cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : The Woods 012 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: s 012 (2015) (digital empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : tor-Title: Jacqueline Woodson - [Lonnie 01] - Locomotion (retail) (epub) - Rocky_45 [CPUL]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : there are 1 sections in this title
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : section(0): Jacqueline Woodson - [Lonnie 01] - Locomotion (retail) (epub) - Rocky_45 [CPUL]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : rebuiltline is :Jacqueline Woodson - [Lonnie 01] - Locomotion (retail) (epub) - Rocky_45 [CPUL]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 73 - formatrem_torsplit : jacqueline woodson [lonnie 01] locomotion (retail) (epub) rocky_45 [cpul]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 5 - formatrem_seriesname :woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched to : Jacqueline Woodson - [Lonnie 01] - Locomotion (retail) (epub) - Rocky_45 [CPUL]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : matched on series title: The Woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : titleend: eline woodson [lonnie 01] locomotion (retail) (epub) rocky_45 [cpul]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 003 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 39.9 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 02 Jul 2014 18:36:03 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 004 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 37.9 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 06 Aug 2014 18:27:03 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 005 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 48.5 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 03 Sep 2014 16:18:02 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 006 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 44.6 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 01 Oct 2014 15:57:03 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods v01 - The Arrow (2014) (Digital) (DR & Quinch-Empire). (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 181.3 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Sun, 02 Nov 2014 16:31:53 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 007 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 47.4 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 05 Nov 2014 19:51:03 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 001 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 41.5 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Thu, 20 Nov 2014 23:12:34 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: Sweet Tooth Vol. 01 - Out of the Deep Woods (2010) (TPB) (Digital-Empire). (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 133.0 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Tue, 02 Dec 2014 14:55:27 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 008 (2014) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 38.3 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 03 Dec 2014 15:21:03 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: Through the Woods (2014) (Digital) (BlurPixel-Empire). (- Nem -)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 83.3 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Sat, 27 Dec 2014 01:06:18 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 009 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 44.9 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 07 Jan 2015 16:18:51 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 010 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 36.7 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 04 Feb 2015 22:34:20 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 011 (2015) (SD-Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 17.5 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 04 Mar 2015 16:51:09 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 012 (2015) (Digital-Empire).
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 42.5 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Wed, 01 Apr 2015 14:40:05 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: Jacqueline Woodson - [Lonnie 01] - Locomotion (retail) (epub) - Rocky_45 [CPUL]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 100 KB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Tue, 28 Apr 2015 05:50:09 +0000 is before store date of 2015-06-03. Ignoring search result as this is not the right issue.
05-Jun-2015 09:47:18 - INFO    :: Thread-13 : Could not find Issue 13 of The Woods(2014) using KAT
05-Jun-2015 09:47:18 - INFO    :: Thread-13 : Shhh be very quiet...I'm looking for The Woods issue: 13 (2015) using experimental [RSS]
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : calpha/cnumber: None / None
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : RSS Check: yes
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : nzbprov: experimental
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : comicid: 73689
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Sending request to RSS for The Woods : 013 (2015)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : checking search result: The Woods 013 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : size given as: 47.5 MB
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Thu, 04 Jun 2015 08:39:04 +0200 is after store date of 2015-06-03
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Entry: The Woods 013 (2015) (Digital-Empire).cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Removed extension from filename: .cbr
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Cleantitle: the woods 013 (2015) (digital-empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Cleantitle: the woods 013 (2015) (digital-empire)
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 0. Bracket Word: the woods 013 
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Comic: the woods 013 
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : UseFuzzy is  : None
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : ComVersChk : 0
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 1. Bracket Word: 2015
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : year detected: 2015
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : year looking for: 2015
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 2015 - right years match baby!
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 3. Bracket Word: digital-empire
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Scanner detected: digital-empire
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Scanner detected: digital-empire
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : original nzb comic and issue: the woods 013 
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : adjusted nzb comic and issue: the woods 013 
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : adjusting from: the woods 013  to: 013
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : ['the', 'woods', '013'] nzb series word count: 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : ['the', 'woods'] watchlist word count: 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : splitst : 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : len-watchcomic : 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : length match..proceeding
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : search-length: 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Watchlist-length: 2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : splitit: the
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : scount : 0
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 0 Comparing: the .to. the
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : word matched on : the
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : splitit: woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : scount : 1
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : 1 Comparing: woods .to. woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : word matched on : woods
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : scount:2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : splitit-len:2
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : Match to series : 100.0 %.
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : it's a go captain... - we matched 100.0%!
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : this should be a match!
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : issue we are looking for is : 13
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : integer value of issue we are looking for : 13000
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : issue we found for is : 013
05-Jun-2015 09:47:18 - DEBUG   :: Thread-13 : integer value of issue we have found : 13000
05-Jun-2015 09:47:18 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/xxxxxxxxxx/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/xxxxxxx/.pyenv/versions/2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/xxxxxxxxxxx/mylar/mylar/webserve.py", line 1320, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/xxxxxxxxxx/mylar/mylar/search.py", line 212, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/xxxxxxxxxxx/mylar/mylar/search.py", line 1321, in NZB_SEARCH
    nzbname = nzbname_create(nzbprov, info=comicinfo, title=entry['title'])
  File "/xxxxxxxxxxxxxx/mylar/mylar/search.py", line 1634, in nzbname_create
    logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment

**Comment by evilhero** [comment]
That's using experimental search which is nzb (not torrents),  and it looks like you're using the blackhole method for nzbs. Basically it can't find the directory you have provided for your blackhole directory. 

If you're just using torrents, turn off experimental search (as it's trying to dump the nzb into your blackhole which I'm guessing you don't have one specified the more I think of it). 
Remedy to restart mylar after the change and save.

**Comment by glberen** [comment]
Yup, fixed it. Thanks!
