### ISSUE TITLE
How to turn off the weekly comics directory creation?

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1045]
I apologize if this is a simple setting that I've just overlooked, but is there a way to turn off that weekly directory creation? I know I can uncheck it, but I often go back to find it checked again or next week it will be automatically checked again.

**Comment by evilhero** [comment]
It should remain unchecked/checked through restarts - I'll try and move off the config option into a location that's more accessible. 

You can shutdown mylar and edit the config.ini, change :

**Comment by glberen** [comment]
Ok, thanks. I see it now. Can't believe I missed it earlier.
