### ISSUE TITLE
Error when using "retry" in the history list

### ISSUE THREAD

**Issue by ljw1** [evilhero/mylar#1046]
I updated my mylar today (git build d6009fa0a39355b30f7a5954326a4eafe9069579) and when submitting nzb links to sabnzbd on a different server it failed, by sending nzb links with the ip address 0.0.0.0. After changing the host ip in the settings and restarting mylar I attempted to retry the download from the history and the following error occurred. 

Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1219, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
UnboundLocalError: local variable 'newznabinfo' referenced before assignment

**Comment by evilhero** [comment]
crap - yeah that would happen if it wasn't from a newzab provider originally. Can you confirm if the attempted retry was it from dognzb, nzb.su, or Experimental ?

**Comment by ljw1** [comment]
I just checked and it came from experimental.

**Comment by evilhero** [comment]
Ok, give that a try - should be working fine now.

**Comment by ljw1** [comment]
Tried the new version (THANKS for the speedy update). Firstly I didn't have the API mode turned on for mylar and sabnzbd threw an empty nzb file message which checking the url gave this "API key not generated".  So I generated an API key and enabled it. The next error is empty nzb file again from sabnzbd with the file downloaded containing "<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.nzbindex.com/nzb-1.0.dtd">

<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
</nzb>

I tried with another comic and it worked so there must have been something else wrong that I cannot immediately see. 

Additionally there is an error in the mylar logs for any file that is retried.

Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1221, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
File "/opt/mylar/mylar/search.py", line 2033, in searcher
notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
File "/opt/mylar/mylar/search.py", line 2038, in notify_snatch
snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
The error is for notification, which I thought I fixed but maybe didn't (it was 4am).

As far as the api, mylar generates one on the fly for the download regardless of if you have it enabled or not (it should be at least). I'll have to check again, but it was working ok prior to me pushing it out (whole week of testing)

**Comment by ljw1** [comment]
Last night I had about 15 empty nzb passed to sabnzbd so I tried the retry again this morning and got a different error message:

NZBname does not exist within the cache directory. Unable to retrieve.

It looks as if when nzbindex returns an invalid file it is being passed to sabnzbd which is returning the error.

**Comment by evilhero** [comment]
Can I ask what some of the files (searches) were that you were re-trying ? 

What's supposed to happen is if Mylar can't download the file to it's cache, it's not supposed to make it to the point where it actually sends it to SAB (it downloads it first, verifies it and the filename, and then if it's ok sends it to get processed by SAB).

**Comment by ljw1** [comment]
Here is the log of one that will not re-try.

2015-06-08 18:59:24	INFO	setting the alternate nzbname for this download grabbed by experimental in the nzblog to : NZBIndex-download
2015-06-08 18:59:24	INFO	setting the nzbid for this download grabbed by experimental in the nzblog to : download
2015-06-08 18:59:24	INFO	Successfully sent nzb file to SABnzbd
2015-06-08 18:59:24	INFO	Found Uncanny Avengers (2013) issue: 2 using experimental
2015-06-08 18:59:24	INFO	[FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2015-06-08 18:59:24	INFO	prov : experimental[download]
2015-06-08 18:59:24	INFO	filen: NZBIndex-download -- nzbname: Uncanny.Avengers.002.2013.Digital.Archangel+Zone-Empire are not identical. Storing extra value as : NZBIndex-download
2015-06-08 18:59:24	INFO	Download URL: http://nzbindex.nl/download/download [VerifySSL:False]
2015-06-08 18:59:24	INFO	fetched via experimental. Retrying the send : http://nzbindex.nl/download/download
2015-06-08 18:59:24	INFO	--Referencing : experimental @ 2015-06-07 22:46:02
2015-06-08 18:59:24	INFO	Located snatched download:
2015-06-08 18:59:24	INFO	Retrying : 370249
2015-06-08 18:59:24	INFO	ComicID:52880

**Comment by evilhero** [comment]
Did it actually say the id of the download is 'download', or did you remove the id# when you pasted it in here?

Can you check the mylar.log file for  any additional information? 

Mylar regenerates everything dynamically now - it only stores the id of the download and the provider instead of the link. This was done so that if mylar had downloaded something that required an apikey, and apikey has been changed since the download it wouldn't error out - granted this is for api-related sites, but the experimental search had to follow the same workflow for storing information thus the change.  You should see the full link appear within thr mylar.log file as it would get logged on a debugging level.

**Comment by ljw1** [comment]
The previous log is just taken from the web interface and nothing has been removed.

This is a copy of the mylar.log section taken directly after clicking retry. I have removed the some api keys and my internal ip addresses.

09-Jun-2015 16:30:14 - INFO    :: Thread-15 : ComicID:52880
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : Retrying : 457652
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : Located snatched download:
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : --Referencing : experimental @ 2015-06-07 23:13:46
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : fetched via experimental. Retrying the send : http://nzbindex.nl/download/download
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : [experimental] link: http://nzbindex.nl/download/download
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : Download URL: http://nzbindex.nl/download/download [VerifySSL:False]
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : [FILENAME] filename (remove chars): NZBIndex-download.nzb
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : [FILENAME] nzbname (\s): NZBIndex-download.nzb
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : [FILENAME] end nzbname: NZBIndex-download.nzb
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : filen: NZBIndex-download -- nzbname: Uncanny.Avengers.021.2014.Digital.Archangel+Zone-Empire are not identical. Storing extra value as : NZBIndex-download
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : Cache Directory successfully found at : /opt/mylar/cache/
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : prov  : experimental[download]
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : issues match!
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : Found Uncanny Avengers (None) issue: 21 using experimental
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : link given by: experimental
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : send-to-SAB host &api initiation string : http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : ...selecting API type: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : ...attaching nzb via internal Mylar API: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : ...setting priority: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb&priority=-100
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : ...attaching category: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : ...attaching rename script: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : Completed send-to-SAB link: http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : sab-to-send:http://xx.xx.xx.xx:8080/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&mode=addurl&name=http%3A%2F%2Fxx.xx.xx.xx%3A8090%2Fapi%3Fapikey%3Dbf265a29ef5dd45c82198baf85fa3675%26cmd%3DdownloadNZB%26nzbname%3DUncanny.Avengers.021.2014.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
09-Jun-2015 16:30:14 - DEBUG   :: CP Server Thread-7 : Recieved API command: downloadNZB
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : Successfully sent nzb file to SABnzbd
09-Jun-2015 16:30:14 - DEBUG   :: Thread-15 : Found matching comic...preparing to send to Updater with IssueID: 457652 and nzbname: Uncanny.Avengers.021.2014.Digital.Archangel+Zone-Empire [NZBIndex-download]
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : setting the nzbid for this download grabbed by experimental in the nzblog to : download
09-Jun-2015 16:30:14 - INFO    :: Thread-15 : setting the alternate nzbname for this download grabbed by experimental in the nzblog to : NZBIndex-download
09-Jun-2015 16:30:14 - ERROR   :: Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1221, in retryissue
    sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
  File "/opt/mylar/mylar/search.py", line 2033, in searcher
    notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
  File "/opt/mylar/mylar/search.py", line 2038, in notify_snatch
    snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by wyldphyre** [comment]
I think I'm seeing this error as well.

What I'm seeing is Sabnzbd saying that the file it gets from Mylar is empty, such as the following...

Empty NZB file api?apikey=e6baeecb735911d63f0457aba0169802&cmd=downloadNZB&nzbname=Injection.002.2015.digital.Son.of.Ultron-Empire.nzb.nzb [http://0.0.0.0:8090/api?apikey=e6baeecb735911d63f0457aba0169802&cmd=downloadNZB&nzbname=Injection.002.2015.digital.Son.of.Ultron-Empire.nzb]

The log in Mylar looks ok. If found the file in the experimental search and handed it off to Sabnzbd. I can even see the .znb file in the /cache folder, and it is about 7KB, definitely not empty.

It's rather annoying as until just recently Mylar has been working like a champ.

**Comment by evilhero** [comment]
It looks like it's a problem with the way the experimental search is handled after the download, or the fact that 0.0.0.0 is being used instead of the actual ip of the machine that mylar is running on.

**Comment by ljw1** [comment]
Originally I had the same ip address error but that can be fixed by setting it in mylar.

**Comment by weidercs** [comment]
I'm having this issue too, it seems to be for all nzb that have a '+' in the file name.  Maybe that helps narrow down the problem?

**Comment by weidercs** [comment]
Here are the ones that are giving me problems:
```
Media-Library-2:cache xxx$ ls *+*
Hawkeye.001.2012.Digital.Archangel+Zone-Empire.nzb	Hawkeye.003.2012.Digital.Archangel+Zone-Empire.nzb	Hawkeye.005.2013.Digital.Archangel+Zone-Empire.nzb
Hawkeye.002.2012.Digital.Archangel+Zone-Empire.nzb	Hawkeye.004.2013.Digital.Archangel+Zone-Empire.nzb
```

**Comment by evilhero** [comment]
@weidercs: the error with the retry (at least the initial one posted and I've been able to reproduce) is due to the comic year not being stored on the history page, so retry in will fail at the notification section if you have it enabled.
Retrying off the series detail page should work fine however. The '+' should be getting encoded to allow for url translation, so I'm thinking it shouldn't be that, but the year thing again.  Can you confirm any error messages after retry in?

**Comment by weidercs** [comment]
```
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : ComicID:50941
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : Retrying : 348048
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : Located snatched download:
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : --Referencing : newznab @ 2015-07-14 14:13:30
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : fetched via newnzab. Retrying the send.
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : newznab detected as : usenet @ https://usenet-crawler.com/
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : link : https://usenet-crawler.com/getnzb/80f3b9c64926b34f88e3492b8c2eb8c4.nzb&i=&r=xxx
14-Jul-2015 14:47:04 - DEBUG   :: Thread-17 : [newznab] link: https://usenet-crawler.com/getnzb/80f3b9c64926b34f88e3492b8c2eb8c4.nzb&i=&r=xxx
14-Jul-2015 14:47:04 - DEBUG   :: Thread-17 : payload:{'apikey': 'xxx', 't': 'get', 'id': '80f3b9c64926b34f88e3492b8c2eb8c4'}
14-Jul-2015 14:47:04 - INFO    :: Thread-17 : Download URL: https://usenet-crawler.com/api?apikey=xxx&t=get&id=80f3b9c64926b34f88e3492b8c2eb8c4 [VerifySSL:False]
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : [FILENAME] filename (remove chars): Hawkeye 001  2012   Digital   Archangel+Zone-Empire 
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : [FILENAME] nzbname (\s): Hawkeye 001 2012 Digital Archangel+Zone-Empire
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : [FILENAME] end nzbname: Hawkeye.001.2012.Digital.Archangel+Zone-Empire
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : Cache Directory successfully found at : /Users/weiderha/Mylar/mylar/cache/
14-Jul-2015 14:47:06 - INFO    :: Thread-17 : prov  : usenet (newznab)[80f3b9c64926b34f88e3492b8c2eb8c4]
14-Jul-2015 14:47:06 - INFO    :: Thread-17 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : issues match!
14-Jul-2015 14:47:06 - INFO    :: Thread-17 : Found Hawkeye (2012) issue: 1 using usenet (newznab)
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : link given by: newznab
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : send-to-SAB host &api initiation string : https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : ...selecting API type: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : ...attaching nzb via internal Mylar API: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : ...setting priority: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb&priority=-100
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : ...attaching category: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : ...attaching rename script: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : Completed send-to-SAB link: https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : sab-to-send:https://localhost:9090/api?apikey=143e9d40401af1e9a1f0ab81262b200e&mode=addurl&name=https%3A%2F%2F0.0.0.0%3A8090%2Fapi%3Fapikey%3Df94a670fc327ce9764c6691fcf2da9f8%26cmd%3DdownloadNZB%26nzbname%3DHawkeye.001.2012.Digital.Archangel%2BZone-Empire.nzb&priority=-100&cat=comics&script=ComicRN.py
14-Jul-2015 14:47:06 - INFO    :: Thread-17 : Successfully sent nzb file to SABnzbd
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : Found matching comic...preparing to send to Updater with IssueID: 348048 and nzbname: Hawkeye.001.2012.Digital.Archangel+Zone-Empire
14-Jul-2015 14:47:06 - INFO    :: Thread-17 : setting the nzbid for this download grabbed by usenet (newznab) in the nzblog to : 80f3b9c64926b34f88e3492b8c2eb8c4
14-Jul-2015 14:47:06 - DEBUG   :: Thread-17 : Deleted stale entry from nzblog for IssueID: 348048 [usenet (newznab)]
14-Jul-2015 14:47:06 - DEBUG   :: CP Server Thread-3 : Matched to key. Api set to : download mode.
14-Jul-2015 14:47:06 - DEBUG   :: CP Server Thread-3 : Recieved API command: downloadNZB
```

Then SAB has this:

```
Empty NZB file api?apikey=f94a670fc327ce9764c6691fcf2da9f8&cmd=downloadNZB&nzbname=Hawkeye.001.2012.Digital.Archangel+Zone-Empire.nzb.nzb [https://0.0.0.0:8090/api?apikey=f94a670fc327ce9764c6691fcf2da9f8&cmd=downloadNZB&nzbname=Hawkeye.001.2012.Digital.Archangel+Zone-Empire.nzb]
```

And when I manually go to "https://0.0.0.0:8090/api?apikey=f94a670fc327ce9764c6691fcf2da9f8&cmd=downloadNZB&nzbname=Hawkeye.001.2012.Digital.Archangel+Zone-Empire.nzb"

I get:

```
NZBname does not exist within the cache directory. Unable to retrieve.
```

**Comment by evilhero** [comment]
Are mylar and sabnzbd on the same machine?

If you go to your cache directory, does the nzb file exist and is it greater than 1kb in size? 

There were https addurl problems within sabnzbd itself at one point ( you couldn't use https sites for addurl links ), but mylar should circumvent that as well as the latest sabnzbd addressed the issue.

**Comment by weidercs** [comment]
Same machine
nzb files exists and is a valid nzb file full of article information

Turned off SSL and I'm still having the issue (I'm also running the new sabnzdb .8 alpha so there may be oddities there too)

Not a big deal at this point, I'll keep trouble shooting and let you know what I find.

**Comment by evilhero** [comment]
Is it happening to all of your retry attempts even with different issues or is it just occuring with filenames that have the + within the name?

I'm assuming that normal downloads from mylar to sabnzbd work fine still?

**Comment by weidercs** [comment]
Normal downloads are happening just fine.  I manually imported the ones
that were having problems so I can't easily reproduce now (sorry)...

Trying to find another release with a '+' in the name to see if it's an
initial import problem or just a retry thing, I'm guessing since I had to
retry, it failed on the initial load attempt as well.

**Comment by evilhero** [comment]
It's possible - I'll try and do some testing later today to see if I can narrow it down abit more and then we can put this thing down for good ;)

**Comment by evilhero** [comment]
Looks like it's having problems creating the nzb name due to the '+' in the filename. I stripped out the '+' from a release prior to downloading it, and Mylar was able to find it and download fine (not stripping it out resulted in the same error as above)
