### ISSUE TITLE
Multiple Download Folders

### ISSUE THREAD

**Issue by GeneLocklin** [evilhero/mylar#1049]
I have my folder format set to ```$Publisher/$Series $Year```.

The ```$Publisher/$Series $Year``` folder is created as soon as I begin watching a comic BUT the comic is actually downloaded to the main _comics folder. 

Here's what happens:

This folder is created automatically, when I subscribe to a series:  

```.txt
../sabnzbd/complete/_comics/Marvel/All-New.X-Men.2013/NOTHING.DOWNLOADS.HERE
```

This is what actually happens:

```.txt
../sabnzbd/complete/_comics/FILE.ACTUALLY.DOWNLOADS.HERE
```

I'm running:

```.txt
Mylar Version: master
-- git build 83dc652b96feb14356f7a2f48be93dc0de7db0c9.
Python Version : 2.7.6
```

Any ideas what's going on here?

**Comment by evilhero** [comment]
Do you have post-processing enabled within mylar and have the comicRN.py script setup? 

If you don't use the comicRN.py script for post-processing then sabnzbd would just dump the comics to the folder you specified for your comics category within sabnzbd.

**Comment by GeneLocklin** [comment]
That totally worked. I don't know why I thought reading the instructions would have helped. Thanks!
