### ISSUE TITLE
No post-processing notification

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#1050]
I noticed after a recent update that I'm no longer receiving Boxcar.io notifications. I checked in the log and found the following.  I'm running a custom script from my torrent client that does some conversion on the comic after download and before dumping it in the Mylar watch folder.  Could that have anything to do with it?  It used to work ok until a couple days ago.

`
09-Jun-2015 08:48:27 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Was not downloaded with Mylar and the usage of torrents. Disabling torrent manual post-processing completion notification.
`

**Comment by evilhero** [comment]
Nothing has changed in that area over the last few commits. 

Argh, I just realized that the call to check the db for torrents downloaded checks against cbt, not 32p. 

I'll get a fix out later today for it, that's my bad on missing that one.

**Comment by bonebox** [comment]
Ah yeah, guess I should have mentioned I'm using 32p, but didn't realize that mattered.  Thanks!

**Comment by bonebox** [comment]
A couple of the comics I added manually to the torrent client, so I understand why those didn't alert, but at least a handful were definitely snatched by Mylar.  Anyway, I just got a notification today for a new comic, so this seems to be intermittent. I'll just assume that it's working now.
