### ISSUE TITLE
Individual comic images incorrect

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#1051]
I've noticed for a while now that when I click the Info button (blue icon with an "i") that appears next to an individual comic under "Options" when it's been tagged, that the exact same comic image appears, no matter which comic it is.

**Comment by evilhero** [comment]
If the cbz has a nested folder structure (although I think this might  be working, I just can't recall atm) or the naming of the jpgs inside the zip follow some weird naming convention (it doesn't have 01,or 00 in the jpgs cover title for example) then mylar wouldn't be able to pull the data properly to display the image.

**Comment by bonebox** [comment]
Would it matter that they're webp images?  They aren't in nested folders and the naming convention is pretty standard, I think (issue #-page #, i.e.  `001-000.webp`, `001-001.webp`, `001-002.webp`).

**Comment by evilhero** [comment]
Yep, mylar isn't setup for .webp, it's just a matter of adding in the extension but atm it wouldn't pick up anything in that extension. I'll add this in for the next development build.
