### ISSUE TITLE
Story Arc file rename bug - 10 instead of 010 - low priority

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1052]
I noticed that when the story-arc rename function does work and you have 'Append Reading # to filename' checked off for issues number ten it creates a 10 and not a 010.

For instance for Secret Wars, it creates '10-New Avengers 028 (2015)' not a '010-New Avengers 028 (2015)'

**Comment by evilhero** [comment]
I'll have a look at this, but do you have issue padding enabled or not within thr configuration?

**Comment by blindguy** [comment]
Yes, 'Issue Number Padding' is checked and I have selected 00x for the format.  All the other numbers seem to be fine.  030 and 040 are set properly, just having this problem with 010 - it makes a 10

**Comment by evilhero** [comment]
Yep verified as a stupid mistake.. I did 'greater than 10' not 'greater then or equal to 10'. 

Will be fixed in the next development commit that gets pushed.

**Comment by blindguy** [comment]
Thanks for the qucik fix, it wasn't a major issue but glad it fixed.
