### ISSUE TITLE
Can't access Mylar from other machines when specifying 'localhost' as the IP address in the Web Interface config

### ISSUE THREAD

**Issue by wyldphyre** [evilhero/mylar#1054]
# Situation
I tried specifying 'localhost' as the Mylar IP address in the web configured in order to solve the problem mentioned [here](https://github.com/evilhero/mylar/issues/1037#issuecomment-111090257). The help text on the page suggests that this is a valid configuration.

# Problem
After setting 'localhost' as the IP address and restarting Mylar you can only access it using a url that contains 'localhost' i.e. "http://localhost:8090/home". Obviously this means that you can only access Mylar from the machine you are running it on. If I tried using the IP Address the actual IP address of the machine, "http://192.168.1.3:8090/home", I couldn't access Mylar, even from the machine it was running on.

# Expected Behaviour
When 'localhost' is used as the IP address in the web interface configuration it should be possible to:
- Access Mylar using either "http:/localhost:8090/home" or "http://192.168.1.3:8090/home" on the local machine that Mylar is running on.
- Should be able to access Mylar using "http://192.168.1.3:8090/home" from other machines on the local network.

**Comment by evilhero** [comment]
According to the cherrypy docs:
- having a host of '0.0.0.0' will listen on multiple interfaces. Allowing you access via both localhost/ip address on different interfaces.
- having a host of 'localhost' will listen only to the local loopback IP. If this is disabled within your OS (either on purpose or not), then localhost will fail to resolve and no page(s) will be served.

**Comment by wyldphyre** [comment]
Changed the IP back to 0.0.0.0 and all is well. I guess I just needed to turn on the API to fix my previous issue, not updated the IP address as well.

I'm fine to call this closed at this point.

**Comment by evilhero** [comment]
Keeping it at 0.0.0.0 might still cause problems with the API (I haven't tested it atm, so I'm unclear right now exactly what would happen). 

If you're still experiencing problems after the 0.0.0.0 change and you can't send nzbs (again), just throw a message back in here...

At this point I might have to rewrite the whole thing with the api...

**Comment by wyldphyre** [comment]
So far it works with 0.0.0.0. Hopefully that will continue.
