### ISSUE TITLE
sabnzbd error (?) on a few Justice League titles

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1059]
Exit (1) nzbname

```
Loading config from C:\Scripts\autoProcessComics.cfg
Opening URL: http://10.0.1.4:8090/post_process?nzb_name=Justice.League.023.4.2013.digital&failed=0&apc_version=1.0&comicrn_version=1.01&nzb_folder=C%3A%5CUsers%5Cxboxl_000%5CDocuments%5CDownloads%5Ccomplete%5CJustice.League.023.4.2013.digital
nzb name: Justice.League.023.4.2013.digital

nzb folder: C:\Users\xboxl_000\Documents\Downloads\complete\Justice.League.023.4.2013.digital

nzbname: Justice.League.023.4.2013.digital
```

**Comment by AtariBaby** [comment]
Also getting this on Avengers World.


  	
Exit(1) nzbname: Avengers.World.021.2015.Digital.Zone-Empire

**Comment by evilhero** [comment]
What does the mylar.log say? 

Oh wait, you are using the db from your other install aren't you?

**Comment by AtariBaby** [comment]
I did yes.

--
Gregory Fleming
415-218-4101
Misspelled from my iPhone

**Comment by evilhero** [comment]
Ok, then it's a dead reference - I'm fact probably your entire history has to get wiped so it can match stuff up properly again. 

Go into the history tab, and at the top select the wipe nzblog option. Then try and redownload those issues again (don't use retry), and it should start post-processing normally again.
