### ISSUE TITLE
Story Arc - folder and files name problem with special characters

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1061]
I thought I had created a issues for this but I can't find it so I'm creating it now, sorry if it is a dupe I can't find. 

Having problems with Story arcs that contain invalid characters like : or & and %.

01-Mar-2015 13:11:07 - WARNING :: CP Server Thread-4 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:11:07 - INFO :: CP Server Thread-4 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld

It says it is creating it and there is no error but it does not actually create anything.

Then when I try again I get more errors:
Please ignore the dates, my time is off on the server.

01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-7 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-7 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-2 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-2 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-6 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-6 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-5 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-5 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-9 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-9 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - WARNING :: CP Server Thread-8 : [DIRECTORY-CHECK] Could not find comic directory: /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld
01-Mar-2015 13:15:52 - INFO :: CP Server Thread-8 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/archive01/comics/mylar/StoryArcs/Secret Wars: Battleworld

**Comment by evilhero** [comment]
Weird, I thought I had this done in a previous commit - had to fix up some things to get this to fly, but have it working on my local repo now. Will commit up shortly for ya.

**Comment by blindguy** [comment]
Got the update and that fixed it right up.  Thanks for the awesome work!
