### ISSUE TITLE
Mylar will not search newznab provider.

### ISSUE THREAD

**Issue by kevindebie** [evilhero/mylar#1063]
I have installed Mylar on a computer and have it working. However I can't get it to search for any actual content.
I've indended to use a single newznab provider, and it doesn't seem to want to search it no matter how convincing I sound. 
I have deleted and re-added it several times, triple checked all the value's and it just seems to ignore them.

Looking in the config file i see the exact same input I gave in the web-interface, also correct, showing a 1 for beeing enabled and all that. Also tried deleting the provider_order bit. No cigar. (and I am aware any and all changes need restarts)

Funny thing when I search for a random comic I see no mention of my configured newznab provider anywhere in the log files and Mylar just gives me "no results" without any sort of an error.
I feel like I can go at this for ages without some help so what am I missing, or is something in fact broken?

**Comment by evilhero** [comment]
Nothings broken about the Newznabs, I use them quite abit for testing and haven't had any issues (as well as others obviously), so it probably is either a configuration problem of some sort, or your Newznab provider isn't returning results in a format mylar can understand. 

So let's start at the beginning - can you paste in your config.ini but I only need to see the Newznab section showing the information (just xxxx out the apikey). 

Also, you might want to paste in the contents of the mylar.log file showing a search and what's happening (from the 'Shhh'  part to the point where it says it cannot find anything).

**Comment by kevindebie** [comment]
I feel like an apocalyptic tit, but I completely missed the part where comicvine is not optional... sorry for that.

**Comment by evilhero** [comment]
Haha no worries, getting it setup initially is the hardest part for a lot of people. Once you do it once, you can pretty much do the 'set it and forget it', but if you have any more problems setting it up/configuring - just throw a message or start another issue and I can help you get it working.

**Comment by kevindebie** [comment]
Its working now, consider this message not sent at all. I'm usually very capable with things like this (IT professional) but mis- or rather not reading details such as this is something I seem to be good at at times... :)
