### ISSUE TITLE
Automatically send new pulls to readlist

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#1064]
I have this option enabled, but no new pulls are being added to the read list.

**Comment by evilhero** [comment]
It only will add issues that are in the current weekly pull-list and have a status of Downloaded, as it needs to be able to reference the physical file for other actions. 

Are the issues in a Downloaded status on the weekly pull-list?

**Comment by bonebox** [comment]
Yes, they are.

**Comment by evilhero** [comment]
Mine got added just fine yesterday but they were all via manual post-processing. 

Are yours from nzb or torrents?

**Comment by bonebox** [comment]
Torrent (32p)

**Comment by evilhero** [comment]
Same as mine, so shouldn't be a problem adding. 

Do you still have a post-processing run from one of the issues that was on the pullist (the mylar.log file).

**Comment by bonebox** [comment]
Nope, already rotated off.  The log does have the below--probably irrelevant, but including it just in case. I'll try and catch it on the next download.

```
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : looking for : LAZARUS
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : comparingLAZARUS..to..LAZARUS
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : watchcomic : Lazarus / mod :Lazarus
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : comicnm : LAZARUS / mod :LAZARUS
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : matched on:LAZARUS...LAZARUS
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : [Lazarus] trying to locate issue 17 to do comparitive issue analysis for pull-list
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Returning Release Date for issue # 17 of 2015-06-17
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Now checking date comparison using an issue store date of 20150617
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Using a compare date (usedate) of 20150617
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Status of Downloaded
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Store Date falls within acceptable range - series MATCH
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Issue #17 already downloaded.
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Watchlist hit for : Lazarus ISSUE: 17
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Refreshing :64204
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : CV_OneTimer option enabled...
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Gathering the status of all issues for the series.
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Checking how out of whack the series is.
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Comic series already up-to-date ... no need to refresh at this time.
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : Available to be marked for download - checking...Lazarus Issue: 17
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : ...Existing status: Downloaded
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : ...Already have issue - keeping existing status of : Downloaded
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : --attempt to find errant adds to Wanted list
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : UpcomingNewValue: {'Status': 'Downloaded', 'ComicName': 'Lazarus', 'IssueID': u'492256', 'DisplayComicName': 'Lazarus', 'IssueNumb
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : UpcomingcontrolValue: {'ComicID': u'64204'}
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : updating Pull-list to reflect status change: Downloaded[Downloaded]
18-Jun-2015 08:31:41 - DEBUG   :: WEEKLYCHECK : weekly_update of table : LAZARUS #:17 to a status of Downloaded
```

**Comment by bonebox** [comment]
So Mylar just processed a new pull and still no add to reading list.  Is there anything specific you're looking for from the log?  Do you just want the lines marked as `[POST-PROCESSING]`?  I ask because there's over 1000 lines related to this one download...

**Comment by evilhero** [comment]
It should indicate if it's checking the weekly pull list for additions to the reading list near the end of the post-processing run. As long as your weekly pull-list hasn't rotated into a different week (it would have rotated to this week's pull-list either late yesterday or today), it should push it into your reading list. 

I'm going to modify it (at some point soon), so that it will put any item that was pulled from a previous pull-list into the reading list (since alot of times, if you're like me you end up manually post-processing stuff a week or so after it's been downloaded, and it then won't match up to the current week's pull-list since it rotated to the new week).

**Comment by bonebox** [comment]
I didn't see anything re: reading list in the log.  Is there specific text I should search for?  I tried "read list", "readlist", and "reading" and got no hits.  I'm not manually post-processing, so it's occurring as soon as the issue is found and downloaded.  They appear on the weekly pull-list as downloaded, so seems like something isn't right.

**Comment by evilhero** [comment]
```
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] I have physically found 1 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 1 / 2 ]
25-Jun-2015 09:28:05 - DEBUG   :: Post-Processing : [POST-PROCESSING][WEEKLY-PULL] Weekly pull list detected as : 2015-06-24
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [POST-PROCESSING][WEEKLY-PULL] Issue found on weekly pull-list.
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [POST-PROCESSING][WEEKLY-PULL][DIRECTORY-CHECK] Found comic directory: /Comics/2015-06-24
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [POST-PROCESSING][WEEKLY-PULL] Sucessfully copied to /Comics/2015-06-24/Infinity Gauntlet 002 (2015)/Infinity Gauntlet 002 (2015) (2 covers) (digital) (Minutemen-Midas).cbz
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [READLIST] Send to Reading List enabled for new pulls. Adding to your readlist in the status of 'Added'
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [READLIST] Attempting to add issueid 493043
25-Jun-2015 09:28:05 - DEBUG   :: Post-Processing : [READLIST] Multiple_dest_dirs:/mnt/Comics-1
25-Jun-2015 09:28:05 - DEBUG   :: Post-Processing : [READLIST] Dir: /Comics/The Infinity Gauntlet-(2015)
25-Jun-2015 09:28:05 - DEBUG   :: Post-Processing : [READLIST] Os.path.basename: The Infinity Gauntlet-(2015)
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [READLIST] Added The Infinity Gauntlet #2 to the Reading list.
25-Jun-2015 09:28:05 - INFO    :: Post-Processing : [POST-PROCESSING][NOTIFIER] Sending notification request to NotifyMyAndroid
25-Jun-2015 09:28:06 - INFO    :: Post-Processing : [POST-PROCESSING] Post-Processing completed for: The Infinity Gauntlet issue: 2
``
Working fine for me, off a download directly from SABnzbd (also did a manual post-processing/folder-check and it worked as well for both). So it might appear to be some kind of configuration option or possible some error that's not getting logged. What does the post-processing run look like in the mylar.log file ?

**Comment by bonebox** [comment]
As mentioned in my original post, I have `Automatically send new pulls to Readlist (Added)` enabled in Reading List Management.  Is there some other config option that factors into this?  

I'll have to wait until a new pull in order to get a fresh log since it has rolled off again, but I didn't notice any errors the last time.   I know for certain there were no `[READLIST]` entries, though.

**Comment by bonebox** [comment]
From your log, it looks like you have `Store in Weekly Directory` enabled.  I do not have that enabled. Does that make a difference?

**Comment by evilhero** [comment]
Man I really need to start sleeping, you're absolutely correct. You need to have the weekly directory creation enabled for the read list to work. I had it setup the correct way at some point but guess the changes got dropped somewhere along the lines.

I'll get a fix up for it, but at this rate it probably won't be until tomorrow when I plan on pushing out a new development commit.

**Comment by bonebox** [comment]
No rush.  Get some 💤.  BTW, I hope I'm not annoying you with all the issues I've opened, I'm honestly just trying to help 😊

Question about the weekly directory--does Mylar automatically move those into their series folder at some point, or does that have to be done manually?

**Comment by evilhero** [comment]
Heh, my sleep pattern is going to get massively screwed up after tomorrow anyways (school is out for kidlets). And of course I'm not annoyed at all, fixing the issues is what will bring more stability and reliability hopefully to mylar so I'm all for that ;)

With the week directory option enabled, mylar moves the meta-tagged/renamed issue into the series directory first. Once that's successful, it then polls it against the weekly pull to confirm a match and if it matches up, it then just copies that file into the weekly directory. So no manual intervention required (at least I haven't had to do anything this far, unless the post-processing script errors out and then it wouldn't get moved anyways)

**Comment by bonebox** [comment]
Cool, so is it an actual copy (i.e. two physical copies of the file) or a symbolic link?  The latter would be really nice.  Also, I'm assuming the weekly directories still need to be manually deleted  (Mylar doesn't do any sort of automated cleanup after a certain time frame)?  That would be nice to have too, especially if they are actual copies.  Of course I can always set up a cronjob to do it...

**Comment by evilhero** [comment]
It's actually 2 physical copies of the same file (it copies from the series directory and into the week folder as required). The ability to specify copy/move/symlink for a post-processing run is coming too - I've been abit busy trying to get the send to sab, and https stuff all sorted out, so hopefully that's on a downward swing now and I can spend more time on other mylar-related things that need some attention.

The weekly directories need to be manually deleted yes, as Mylar has no way of knowing exactly when they were read/sent (thus far of course). Since Mylar does track all the sends it does to your tablet (if using the reading list send to tablet option), in theory it's possible to delete the directory once it's been sent successful and all issues are considered 100% on the device - but I haven't looked into this anymore than just these few lines I'm writing now :)
