### ISSUE TITLE
Newznab Configuration

### ISSUE THREAD

**Issue by jwillmer** [evilhero/mylar#1067]
Can't figure out how to configurate a new search provider. Is my settings correct? That is the Uid, in programs like sonarr and did not need it..

Name: oznzb
Host: https://api.oznzb.com
Api: myapikey
Uid: rss

**Comment by evilhero** [comment]
The UID is the user token and is required by most rss things that use rss feeds - sonarr might not need it for whatever reason (or maybe they use the api to figure out the uid possibly), but mylar does.

https://oznzb.com/rss and take the value of i as your UID.

**Comment by jwillmer** [comment]
@evilhero I closed it because I could find the missing infos but if i only activate usenet as indexer i get the following warning in the log:
`[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.`

Is this related to incorrect usenet data or should I open a new issue?

**Comment by evilhero** [comment]
If you make any kind of configuration change (especially regarding provider as in enabling /disabling even), you need to save the changes and restart Mylar. 

This is because the provider order gets generated on startup only, so when it doesn't get restarted after a change there are incorrect values present.

**Comment by jwillmer** [comment]
o.k., thx. Someone should fix that info: `Web Interface changes require a restart to take effect` into `Changing settings require a restart to take effect`

**Comment by evilhero** [comment]
I'll get my wife to write up the paperwork for the change ;)
