### ISSUE TITLE
global name 'GIT_BRANCH' is not defined

### ISSUE THREAD

**Issue by wyldphyre** [evilhero/mylar#1068]
Getting this after using the auto update to update to the latest version which allows configuring the git branch. I'm assuming that there is a bug resulting in no proper default?

How do I fix this?

**Comment by evilhero** [comment]
It should default when starting up based on the commit you're currently running.

What commit are you on and which OS? (I tested on Ubuntu and Win 8)

**Comment by wyldphyre** [comment]
OS X  that was just upgraded to Yosemite shortly before the Mylar upgrade attempt (though I doubt that matters).

I'm not sure how to tell what branch I'm on. The config.ini has a git_path variable that is an empty string, and says the config_version is 5

**Comment by evilhero** [comment]
If you can't get to the gui of mylar after starting it up, you could just try and run 'git status' from a command window/she'll from within the mylar directory - the branch will be right at the beginning of the resulting text.

**Comment by wyldphyre** [comment]
hmm. Don't have git on that box at the moment, but working on it. Slow connection so will take a little bit.

I've tried manually adding the git_branch to the end of the config.ini and also under [General], but the same error for both. Does it have to go in a particular place?

**Comment by evilhero** [comment]
Oh so you're updating from source?

**Comment by wyldphyre** [comment]
I think I originally downloaded a zip file (of the source?) and have been running from that? It was a while back so I can't recall I'm afraid. I do appear to have all the source, but that would be the same if I'd pulled from a git branch, right?

**Comment by evilhero** [comment]
Yeah it's the same file, but the update method is different .Using git it falls on git to do the update so it's pretty hands off for mylar. Updating from source though require mylar to download the new source file from git, extract it and then update your local copy so it's identical to the source.

I believe I need to set a default for branch for source updates.

**Comment by wyldphyre** [comment]
Right. Of course. The lack of Git on that machine is probably part of the issue, which I'm currently trying to rectify. Going to take an annoyingly long time though.

Should it start up if I get Git installed, or an I borked?

**Comment by evilhero** [comment]
I'm looking at it now,  just kids are all up in my face atm lol.

Since I don't run from source, can you verify the contents of your version.txt file located in the mylar directory? I need to know it's contents as I have to be able to parse it cleanly and just want to verify it's as I have it.

**Comment by wyldphyre** [comment]
Damn kids :). Not super urgent, as I'm off to bed in about an hour (in Western Australia).

Contents of the version.txt file is: 0c6bd57606a718f0c022f2ab426568b551d1eacb

**Comment by evilhero** [comment]
K, kids are eating and watching tv haha ;)

That should fix your problems (I hope), keep in mind that at least on initial startup it will set the branch to master - so if you want to flip to development, you'll have to edit the config.ini with mylar shutdown and change the git_branch variable as I had described above.

**Comment by wyldphyre** [comment]
I replaced versioncheck.py and I'm back up and running, though I noticed one oddity.

In the the first settings page it says "Mylar Version: Development", even thought the git_branch setting is  currently master. I'm guessing this is something to do with my having downloaded the development source originally?

I guess at some point I should just bite the bullet and pull the dev branch via git. If I do so, can I just back up the config.ini file and keep all my existing configurations?

**Comment by evilhero** [comment]
ahh crap - that's pointing to the versions.py file. I'll need to fix that so that it points to GIT_BRANCH instead of pulling the branch from the versions.py file - even though it's just for display purposes. Whatever branch you have set in your config.ini (GIT_BRANCH) is the branch you're currently running.- the branch name on the configuration page, as well as at the bottom of every page will say the wrong branch.

You can verify it by just looking at what commit you're running and then seeing which branch it falls under just by browsing the github page.

**Comment by evilhero** [comment]
Last fix hopefully - that last one should fix the webpages so they're in line with what you're actually on now ;) Thanks for bearing with me on all of this - hopefully with your help, we were able to get it fixed before alot more people grabbed the updates that were running from source.

**Comment by wyldphyre** [comment]
I guess we can call this one closed at this point.

**Comment by wyldphyre** [comment]
Now I'm confused.

Pulled a new clone from https://github.com/evilhero/mylar.git, and that says I'm on master. There is no git_branch in the config.ini, and adding git_branch to point to development doesn't still says master in the settings.

doing `git checkout development` does put me on the development branch though. Does that sound right?

**Comment by evilhero** [comment]
Yes that's right. The git_branch option is only available in the development branch. When you git clone a repo it defaults to the master branch unless you specify the -b development option in the git clone command. 

Once you're on the development branch,  the git_branch option will be in the config.ini file. 

When development merges with master there won't be any discrepancies with the config.ini in regards to the branch switching option.

**Comment by wyldphyre** [comment]
ah, right. I'd missed the bit about the option only working in Development. All good for now I guess.
