### ISSUE TITLE
Switched back to Master Branch from Development after newest update

### ISSUE THREAD

**Issue by psychoflame** [evilhero/mylar#1069]
As the title says, it appears the newest Update on the development branch switches me back to the master branch instead of keeping me on the development branch. Do we just reedit the versioncheck.py file to put us back onto the development branch

**Comment by evilhero** [comment]
It actually flipped into the config.ini section now - it's just the initial switch that has to be done to get things back on track again unfortunately. If you edit the config.ini (with mylar shutdown), and set the following line:
```
git_branch = development
```
Save the config.ini, start up mylar and you'll be back on the development branch ;)

I'll look into seeing about reading the variable line from the version.py file

**Comment by psychoflame** [comment]
It's Run from a Freenas jail, using joshua's complied pbi for freenas. I'm gonna assume he complied it from source. Also, thanks for the advice. i didn't know you had switched the branch switch to the config file

**Comment by psychoflame** [comment]
Okay so a little bug in this. I'm going into the config.ini and editing that line with mylar off. however when i restart mylar it seems to be reverting back to having it on the master branch instead of development branch. Not sure why this is happening

**Comment by evilhero** [comment]
It sounds like you're stuck between commits.. which commit are you currently running? .

**Comment by psychoflame** [comment]
Commit im currently on is

1b4db818782d12ba0efab9daab5297e110f7df83

Branch is still master

**Comment by evilhero** [comment]
Yep, you need to pull from the source again ..the fix went into the last development build which you're not on (you're on the 2nd last one). So either do a git pull from the command line (within the mylar directory), or do a fresh git clone (just backup your config.ini, mylar.db and cache prior to doing the git clone then move them back afterwards)
