### ISSUE TITLE
Feature request, all config of default display

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1070]
I would like to have default display all results instead of 25 per page, especially on main page. And the sort I would rather just have it by alphabetical instead of alphabetical continuing then ended comics. Also on search results I tend to resort based on number of issues. Can we have this configurable? Or at least remember last option?
Thanks

**Comment by evilhero** [comment]
Mylar will remember your choices in regards to display, and filtering (possible sorting although I can't recall atm, but I believe it encompasses it) but relies on session cookies. These cookies will exist for up to 2 hours, or until the session browser window is closed. Being able to have these as configurable options isn't something that's possible given the current datatables being used (unless someone can point me in the right direction). 

Having it last for a longer period of time or to have the settings saved to the local storage and called back on loadup, are only available in the newer datatables version. I haven't checked out all of the changes, or even attempted to see what might be broken in upgrading - and tbh, it's not high on the to-do atm, unless something big comes along that breaks things and requires the upgrade. I'll be looking into it, but atm other things are abit more pressing and taking alot of my free time up with regards to Mylar.

**Comment by CptanPanic** [comment]
Maybe just make session cookies last a longer time like forever or a month?
