### ISSUE TITLE
Not Finding Anything, In PDF Format

### ISSUE THREAD

**Issue by mathandsciencechannel** [evilhero/mylar#1072]
I like to transfer my comics to PDF so i can easily read them on my ipad. However, i noticed that mylar didnt index any of these comics. It did, however, index some CBR's i had before i converted them. Is there a simple fix that would allow me to index my PDF's as well as the CBR/Z's?

thx

**Comment by evilhero** [comment]
Unfortunately no, not at this time anyways. Mylar has always focused on cbr/cbz, and that's where it's focus will ultimately lie, unless there is a surge in some newer format.

Just curious, why would you want to convert them into pdf (or even use) when cbr/cbz readers exist in droves for reading devices?

**Comment by mathandsciencechannel** [comment]
I store my comics on a nas, and for me its easier to use PDF on my ipad. The CBR/z readers on ipad all cost money, or else they dont allow easy acsess to a network location.

About the PDF thing, it doesn't have to download them, i just would like it to recognize they are there, so it doesnt try to download them again. Otherwise, beautiful software, thank you for putting your time into this project!

**Comment by evilhero** [comment]
Adding the .pdf option to allow for scanning in would be an easier task, since there are only 4 lines of code to modify to allow that to occur. I'll look into this and see how adding it in goes - the only problem I forsee happening is the duplication checker might have some problems with the extension, since it only tests for cbr / cbz - but I'll still look into it and see what I can do to get the scanning at least working.

**Comment by n3IVI0** [comment]
I used to do the exact same thing, but then I discovered a comic reader app called Chunky Comic Reader. It will (for a $3.99 upgrade) let you access network shares to read comics, including .cbr and .cbz files, and also pdfs. Only reader I have found that lets you access comics on a NAS.

**Comment by JasonMSims** [comment]
Hey @evilhero, were you able to look into adding the option to scan .pdfs in?  I've got hundreds of pdf's that I would like to import.  I'm unfamiliar with python but catch on pretty quick, if you'd like to simply point me in the direction I'll be more than happy to attempt on my own.

**Comment by evilhero** [comment]
Well its actually probably as simple as just adding the extension into the file checker module... If I can get to a machine tonight, I'll roll out the patch for you to try. Post-processing probably won't work, although if I do the same to that module in would theory allow you to name it as per the renamed settings within mylar.

**Comment by evilhero** [comment]
The .pdf extension has been added to the filechecker module and is now in the latest development commit - not sure exactly how much it will work for your given case, but at the very least you should be able to file-check against the issues now and have them be recognized.

**Comment by JasonMSims** [comment]
Great!  Thanks for the effort.  I'll give it a go shortly.

**Comment by JasonMSims** [comment]
It works great!  It recognizes them as well as renames when running manual post-processing.  It doesn't appear to be recognizing them when scanning the library though.  I'm working around that by adding each series to the pull list first and then manually post-processing them out of a temp import folder.
