### ISSUE TITLE
Importing collected volumes - Unable to locate downloaded file to rename. PostProcessing aborted.

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1073]
How should i name a "collected volume" e.g. https://www.comixology.com/The-Flash-2011-Vol-6-Out-of-Time/digital-comic/211240 which contains a range of issues? Mylar simply reports "Unable to locate downloaded file to rename. PostProcessing aborted."

**Comment by evilhero** [comment]
Typically mylar doesn't support graphic novels, trade paperbacks, or comps.  That being said, there are cases where some will work but it really depends on how comicvine has it listed. In any case, mylar will always need at a minimum 2 items within a filename - the series title, and an issue number.  The comp you're asking about actually has an issue number so in theory you could have a filename as : 'The Flash v6 001 - Out of Time.cbr' or 'The Flash v6 1 (2011).cbr'.

Keep in mind it's not supported, so I honestly don't expect it would work, but you could try those formats. Also keep in mind that if The Flash series ever hits a v6 in series, mylar wouldn't be able to distinguish multiple watchlist matches to the same series properly.

**Comment by mnbf9rca** [comment]
It would be super to be able to map issues in a trade paperback to a series



On 26 Jun 2015, at 16:58, evilhero <notifications@github.com> wrote:

Typically mylar doesn't support graphic novels, trade paperbacks, or comps.
That being said, there are cases where some will work but it really depends
on how comicvine has it listed. In any case, mylar will always need at a
minimum 2 items within a filename - the series title, and an issue number.
The comp you're asking about actually has an issue number so in theory you
could have a filename as : 'The Flash v6 001 - Out of Time.cbr' or 'The
Flash v6 1 (2011).cbr'.

Keep in mind it's not supported, so I honestly don't expect it would work,
but you could try those formats. Also keep in mind that if The Flash series
ever hits a v6 in series, mylar wouldn't be able to distinguish multiple
watchlist matches to the same series properly.

—
Reply to this email directly or view it on GitHub
<https://github.com/evilhero/mylar/issues/1073#issuecomment-115739987>.
