### ISSUE TITLE
message: "no upcoming data to display"

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1075]
when looking at the /upcoming page, i just see "no upcoming data to display". in the logs i see "No series have been marked as being on auto-watch." Any ideas?

**Comment by evilhero** [comment]
Upcoming data only occurs when a new pullist has been grabbed. It will then populate the Upcoming portion with the series that are on the watchlist. Depending on your settings,  the pull list is 'new' and available on Saturday/Sunday or on Mondays. This is outside of my control as its entirely dependent on the site mylar pulls the data from (previewsworld)

**Comment by mnbf9rca** [comment]
i understand, thanks. will keep an eye on it. I hadn't ever come across previewsworld before.

**Comment by mnbf9rca** [comment]
thanks
