### ISSUE TITLE
Error: "Could not get the latest commit from github"

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1077]
When clicking "Check for mylar updates" it tells me "Checking for update successful" in the bottom right corner, however when i look in the logs, it says "Could not get the latest commit from github". so, 2 issues i guess:
1. the update check message is misleading - perhaps it shoudl say "update check requested" or something, and
2. why can't it check for updates?

**Comment by evilhero** [comment]
1. Possibly, although it's more of a display issue than anything else that had zero correlation to the problem at hand.
2. It can check for updates just fine. If it can't hit github, then it's either github is offline or you have a problem on your side with something.  The mylar.log is there for a reason and logs the git request under normal circumstances, so you should probably check that and see what it says.

**Comment by mnbf9rca** [comment]
thanks for the quick turnaround.
1. yes, i understand. i'm just suggesting a minor enhancement. i've noticed this sort of thing in a couple  of places - where it's acknowledging the request vs. actually completing it. It would reduce user confusion if the message was more accurate.
2. i'm sure it can :) and i think this page is the first place many people will come to try and fix the issue for themselves but when i searched i couldnt find anything. the logs just contain this:

```
29-Jun-2015 14:21:46 - DEBUG   :: MAIN : Trying to execute: "git rev-parse HEAD" with shell in /opt/mylar
29-Jun-2015 14:21:46 - DEBUG   :: MAIN : Git output: 46fe69a4394f843a4f1e0f959dda686dee2e7d00

29-Jun-2015 14:21:46 - DEBUG   :: MAIN : Trying to execute: "git branch --contains 46fe69a4394f843a4f1e0f959dda686dee2e7d00" with shell in /opt/mylar
29-Jun-2015 14:21:46 - DEBUG   :: MAIN : Git output: * development

29-Jun-2015 14:21:46 - INFO    :: MAIN : Branch detected & set to : development
29-Jun-2015 14:21:46 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
29-Jun-2015 14:21:46 - INFO    :: MAIN : Checking to see if the database has all tables....
29-Jun-2015 14:21:46 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
29-Jun-2015 14:21:46 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
29-Jun-2015 14:21:47 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
29-Jun-2015 14:21:47 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
29-Jun-2015 14:21:47 - INFO    :: MAIN : Retrieving latest version information from github
29-Jun-2015 14:21:47 - WARNING :: MAIN : Could not get the latest commit from github
```

**Comment by evilhero** [comment]
Try running mylar from the cli instead of as a daemon. Then try updating and seeing if the error message appears. 

Odds are the git response is being displayed to screen, and because it's in daemon mode those messages get suppressed.

**Comment by mnbf9rca** [comment]
i'll try it at teh weekend

r.

**Comment by kev0153** [comment]
are you by any chance running mylar on an older version of ubunty?  If so I had this problem and fixed it.

https://github.com/evilhero/mylar/issues/1083

**Comment by evilhero** [comment]
Sorry, I've been afak for awhile - went on a vacation with the family and left the phone at home (since I was travelling outside of the country). 

Is this still an issue ? Or has there been any additional information ?

**Comment by kev0153** [comment]
Upgrading or otherwise running mylar with the latest version of python seems to fix it

**Comment by mnbf9rca** [comment]
i havent upgraded my machine (ubuntu 14.04 LTS). i was thinking of getting a newer version of python just for mylar, but then i figured its no real hassle to load terminal and call git pull every now and then. Might even schedule it.

**Comment by evilhero** [comment]
Could always try pyenv which lets you use virtual python environments on a per application level if required.

At the rate of people having problems I might try to work something so that those on less than 2.7.9 can still update (using the old methods), while those 2.7.9+ can use the current methods.

**Comment by mnbf9rca** [comment]
i wouldnt say it's worth it - i'd rather you focus your time on things like
improved management of large collections (e.g. grouping sets of comics
etc.). Just make a note in teh readme that people need to install using git
clone, and then to upgrade use git pull.

r.

**Comment by conbud** [comment]
Have there been any application updates to fix this? I read the other issue submitted by kev. I'm having the same issue where mylar won't update. I'm using the DEV version of mylar on ubuntu server 14.04 LTS with Python 2.7.6.

I can't upgrade to ubuntu 15.04 quiet yet which seems to be the fix.

WARNING :: MAIN : Could not get the latest commit from github

**Comment by evilhero** [comment]
Upgrading python is a solution only because in doing so you update your version of python to one that can properly handle https requests (and it's kinda a really important fix).

There's not really a fix for mylar at this time, and until i can do some testing its still going to be a bit. So your other options are:
- upgrade python to at least 2.7.7 but 2.7.9+ would be better (ugh I hate that myself)
- use something like pyenv which lets you run virtual python environments. 

I run Ubuntu 12.04 LTS  which comes with python 2.7.3. With pyenv I run mylar with 2.7.9 along with some other apps, and I don't have to upgrade python itself as that tends to break things since python is so integral to the OS. Plus I can easily switch between various python versions with no impact on the OS itself ;)
