### ISSUE TITLE
Feature Request: A button to test notification configuration

### ISSUE THREAD

**Issue by wyldphyre** [evilhero/mylar#1079]
It just occurred to me that it would be nice to have a "test" button to send a test notification in order to confirm that everything is ok. The lack of such a feature at the moment means that you have to wait until something happens that would trigger a notification before you know if there is a problem.

**Comment by evilhero** [comment]
Yep this is on the todo (has been for a while actually), but something always happens that pushes it back as far as me being able to work on it. I believe the notifiers all have the tests built in, it's just making the buttons link back and the, well testing the test buttons

**Comment by wyldphyre** [comment]
Cool. No rush, I just thought it would be a good idea to get logged.

**Comment by evilhero** [comment]
Finished this on my local repo...not sure when I will push it up, but it will be in the next development commit.

**Comment by wyldphyre** [comment]
Cool
