### ISSUE TITLE
Empty NZB errors

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1082]
Hey, suddenly I've gotten this error 4 times this morning.  THis is the message from SABNZB.  I'm not saying that it is impossible that the error is correct, just that this has happened 4 times on 4 different titles.
THanks!

Empty NZB file api?apikey=40e57e8d0a0039648a684c5fee44ffae&cmd=downloadNZB&nzbname=A-Force.002.2015.Digital.Zone-Empire.nzb.nzb [http://0.0.0.0:8090/api?apikey=40e57e8d0a0039648a684c5fee44ffae&cmd=downloadNZB&nzbname=A-Force.002.2015.Digital.Zone-Empire.nzb]

**Comment by evilhero** [comment]
Well it depends on your setup. You can use the host_return field within the config.ini and set it to the full url to your mylar install (ie. http://192.168.1.7:8080) - doing it this way allows you to keep 0.0.0.0 as your mylar host so it can listen on all interfaces.  You can also just change the mylar host from localhost/0.0.0.0 to the internal ip of the machine running mylar. If you do this though,  you need to change the host address in youryour autoProcessComics.cfg if you're doing post-processing using the comicRN script.

**Comment by thewindupboy** [comment]
Changing the host_return seemed to work, thanks!

**Comment by timm088** [comment]
hrmm - i seem to be getting the same issue here now ie., Empty NZB
Setting the return host does not seem to have any effect

If you are using a different http_root , what should the return host be (in this scenario?)

**Comment by evilhero** [comment]
The host return address uses whatever you have stipulated as the http root value within the mylar configuration.  

So you shouldn't have to add anything extra to the return host other than ip:port line preceded by the protocol.

If they're on the same machine,  there really shouldn't be a need to use the host_return  

Can you paste in some of the mylar.log file showing what is happening during a download with sab?

**Comment by timm088** [comment]
Actually, I think the empty NZB (for me) was because I hit my API download limit on a newznab provider. 

This provider was '0' in the provider order.
But, I still had api 'searches' available. 

Mylar was marking the download as 'snatched', when it hadnt actually got the file though (might be a very edge case?)

**Comment by evilhero** [comment]
It might be edge case,  but it's probably something that can be programmed in to handle better.  Unfortunately a lot of the provider's don't let you query the api to find out how many hits you have done/have left.  And I'm guessing even though you hit your limit,  it still returned some sort of file - probably an empty one (or had a message inside in xml). There must be a return code that comes back indicating ok/bad results.

I'm also not sure if you had enabled Failed Download Handling within mylar if it would have caught the empty nzb, marked it as Failed and then retried in a different source (what it's supposed to do when it's enabled ).

I'll definitely look into this abit more as better error handling / messages is just as important as anything else.
