### ISSUE TITLE
Can't get latest info github

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#1083]
Not sure when this started but checking github fails.  I made a backup of the database, redownloaded the zip reinstalled and restored the database.   I run mylar as a dameon and it fails, tried running from the command line and it fails.  It seems to be contacting github becuase I see the log entrty like this

DEBUG   :: MAIN : Trying to execute: "git rev-parse HEAD" with shell in /home/kev/.mylar
02-Jul-2015 21:40:51 - DEBUG   :: MAIN : Git output: 83dc652b96feb14356f7a2f48be93dc0de7db0c9

02-Jul-2015 21:40:51 - DEBUG   :: MAIN : Trying to execute: "git branch --contains 83dc652b96feb14356f7a2f48be93dc0de7db0c9" with shell in /home/kev/.mylar
02-Jul-2015 21:40:51 - DEBUG   :: MAIN : Git output: * master

02-Jul-2015 21:40:51 - INFO    :: MAIN : Branch detected & set to : master

Even though I'm using the development branch. Seems like I got out of synch some where

when I start mylar but when I check for update I get this

VERSIONCHECK : Starting new thread: VERSIONCHECK
01-Jul-2015 12:01:25 - INFO    :: VERSIONCHECK : [VersionCheck] Checking for new release on Github.
01-Jul-2015 12:01:25 - INFO    :: VERSIONCHECK : Retrieving latest version information from github
01-Jul-2015 12:01:26 - WARNING :: VERSIONCHECK : Could not get the latest commit from github

.  I know I'm at least one commit behind.  I'm thinking about nuking the whole thing and starting over.

**Comment by evilhero** [comment]
Yeah either that or edit your config.ini. and change the github_branch line so it reads : 
github_branch = development 

The last few development commits put in place the ability to specify the git user / branch so that you no longer need to edit .py files etc.

It still might be abit buggy, but editing the .ini and starting it up should put you on the correct branch again where you can update. 

If it doesn't work,  then you'll have to do a git pull from within the mylar directory to get yourself back on track ( or fresh git clone,  either one ).

**Comment by kev0153** [comment]
tried chaning .ini an no love, just going to do a git clone and go from there.

**Comment by kev0153** [comment]
ok I might be doing something wrong.  I deleted the entire mylar folder and did this

 git clone https://github.com/evilhero/mylar.git --branch development --single-branch .mylar

it downloads and everything is good.  I do a git branch -a and I get this
* development
  remotes/origin/development
 That is good.  checking config.ini shows branch set to development but when I run python from command line and as a daemon I get this
03-Jul-2015 10:40:16 - INFO :: MAIN : Retrieving latest version information from github

/home/kev/.mylar/lib/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

03-Jul-2015 10:40:16 - WARNING :: MAIN : Could not get the latest commit from github

when I clone the master git clone https://github.com/evilhero/mylar.git

git branch -a gives

* master
  remotes/origin/HEAD -> origin/master

when i start mylar from the command line

03-Jul-2015 10:43:29 - INFO :: MAIN : Retrieving latest version information from github
03-Jul-2015 10:43:30 - INFO :: MAIN : Comparing currently installed version with latest github version
03-Jul-2015 10:43:30 - INFO :: MAIN : Mylar is up to date

does it have something to do with the ssl thing?  I don't remember seeing that before and it doesn't give the warning on startup of the master.  I'll look into that link it spits out.

**Comment by evilhero** [comment]
Ahh yeah the SSL verify. If it's an ssl request url (like github is), it will attempt to verify the https certificate to ensure that it's the correct site. The verify option only works in > 2.7.7 (or I guess if it's an SNI-based host, although I didn't think github was).

You can try this to see if it works, and if it does I can patch up the fix for it.  On line 165 in versioncheck.py, change the line:
```
        response = requests.get(url, verify=True)
```
to 
```
        response = requests.get(url, verify=False)
```

Save it, start Mylar up and see if that works at all.

**Comment by kev0153** [comment]
let me try that, I'm running ubuntu server 14.04, I might upgrade to 14.10 or 15.04 to get the newer version of python (I have 2.7.6 right now)  but let me try your suggestion first.

**Comment by evilhero** [comment]
If you have to upgrade, you can also try to use pyenv, it's a virtual python environment - lets you specify and install varying versions of python without messing up your original python that's required by the OS.

**Comment by kev0153** [comment]
changing that line didn't fix it, let me upgrade my version of ubuntu

**Comment by kev0153** [comment]
upgrading is fairly easy so I'm going to try that first, looks like 14.10 gets me that right version of python

**Comment by kev0153** [comment]
ok I had to go all the way to ubuntu 15.05 but I have python 2.7.9.  Error is gone, I did not modify any files.  Hopefully anybody else having this problem will see this thread.   thanks

**Comment by evilhero** [comment]
Just to confirm, 2.7.8 on 14.10 didn't work?

**Comment by kev0153** [comment]
no 2.7.8 still gave the error, 15.04 has 2.7.9 according to this you have to go 2.7.9 or greater.

https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

"Certain Python platforms (specifically, versions of Python earlier than 2.7.9) have restrictions in their ssl module that limit the configuration that urllib3 can apply"

**Comment by mnbf9rca** [comment]
thanks - although i have 14.04 LTS so i'll just have to wait.
