### ISSUE TITLE
Trying to post process X-Tinction Agenda 002 throws an exception

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1085]
I tried to trace down why it was throwing the exception but found that if I changed the name to X-tinction (lower case t) and did manual post processing it worked ok...

    04-Jul-2015 21:40:19 - INFO    :: CP Server Thread-5 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
    04-Jul-2015 21:40:19 - INFO    :: CP Server Thread-5 : Starting postprocessing for : X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /Users/xxx/Downloads/complete/X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [NZBNAME]: X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): X-Tinction Agenda 002 2015 Digital Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : X-Tinction.Agenda.002.2015.Digital.Zone-Empire
    04-Jul-2015 21:40:19 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: 1
    04-Jul-2015 21:40:19 - INFO    :: Post-Processing : [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
    04-Jul-2015 21:40:19 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb not found.
    04-Jul-2015 21:40:19 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
      File "/Users/xxx/Mylar/mylar/mylar/logger.py", line 159, in new_run
        old_run(*args, **kwargs)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/Users/xxx/Mylar/mylar/mylar/PostProcessor.py", line 715, in Process
        if helpers.is_number(sandwich):
    UnboundLocalError: local variable 'sandwich' referenced before assignment

**Comment by evilhero** [comment]
Weird second issue posted with this exact error and same lead up. The issue was fixed for the other person by not using daemontools to start up mylar - how exactly are you starting mylar?

**Comment by weidercs** [comment]
Command prompt (OSX), not even demonized:
python ./Mylar.py

**Comment by evilhero** [comment]
Was this on a normal download or manual post-processing run (meaning you didn't manually download the nzb and then tried to run the comicRN script on it)?

**Comment by weidercs** [comment]
Normal post processing for a story arc pull, then tried adding the series with same result.  Was finally able to manually download and manually post process after I changed the uppercase T to lower case to match issue 1 which imported automatically fine.

**Comment by evilhero** [comment]
Was on vacation with the family for the last few days, so just got back now. I'll look into the post-processing aspect for story-arcs...it should be able to match regardless of capitalization, so if that's all that it is that's causing the problem, it will be an easy fix :)

**Comment by weidercs** [comment]
Fixed
