### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED error from autoProcessComics.py when SSL is on

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1087]
I was getting an error in SABnzbd when I turned on SSL for Mylar.  I tracked it down to autoProcessComics.py and it's throwing a CERTIFICATE_VERIFY_FAILED when trying to run.

Changed the following at line 75:

From:

    if ssl:
        protocol = "https://"
    else:
        protocol = "http://"

To: 

    if ssl:
        protocol = "https://"
        opt_out_of_certificate_verification = True
        if opt_out_of_certificate_verification:
            try:
                import ssl
                ssl._create_default_https_context = ssl._create_unverified_context
            except:
                pass
    else:
        protocol = "http://"

Not super clean, but t cleared up the error and I could test it by swapping the variable from True to False.

Not sure if it's something messed up with my setup but this fixed it for me.  Take it of leave it...

**Comment by evilhero** [comment]
That will definitely work if your opens sl isn't at the correct level, but then your disabling https verification, which for some would be an issue.

I can change the open so that it uses the requests module, which has all of the ssl within - but then if you're not running python 2.7.9+ it probably becomes an issue when post-processing.

**Comment by weidercs** [comment]
I'm running 2.7.10 but there have been some oddities, I'll try to clean up my python versioning and see if that helps

**Comment by evilhero** [comment]
It might not be your actual version of python if that's the case. .it's probably more in line with your openssl version that you're running. I believe you need at least 1.01 (maybe 1.0+) to allow for self signing certificate verification from within python.

**Comment by weidercs** [comment]
Media-Library-2:Resources xxx$ python -c "import ssl; print ssl.OPENSSL_VERSION"
OpenSSL 1.0.2c 12 Jun 2015

**Comment by weidercs** [comment]
ahh, but SAB might be running it's own version of python! let me chase that down...

**Comment by weidercs** [comment]
Python versioning issue, not a bug

**Comment by ChrisWeiss** [comment]
I'm running into a similar issue with my RSS Search Provider that's using a self-signed cert. I'm no Python expert, I was unable to track down where the RSS call is so I could add a similar wrapper. Is there a different solution?

**Comment by evilhero** [comment]
argh - it looks like I forgot to change out the rss parser for the nzb providers. As long as you're running python 2.7.9+, the fix will allow you to specify ssl certificate verification on a per provider basis (it does in the latest development commit), and that will include rss feeds in the fix.

I'll try and get this out in the next little bit.

**Comment by ChrisWeiss** [comment]
Thanks. FWIW - This is on the QNAP. I assume that the qpkg will update from Github rather than having to wait for a new package spin?

**Comment by evilhero** [comment]
From what I know of the QNAP (which is pretty much negligible), it should update via the git as it does a git pull on startup to ensure it's up-to-date (if I'm remembering right)...
