### ISSUE TITLE
Mylar grabs the wrong IP address

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1090]
With the new update, mylar is grabbing the local address of my OpenVPN (tun0) tunnel instead of the local network address (en0).  You'll probably want to make this configurable if you include it, there are some pretty messy network configurations out there... Here is my ifconfig:

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether c8:2a:14:1e:59:af 
	inet 10.0.1.2 netmask 0xffffff00 broadcast 10.0.1.255
	nd6 options=1<PERFORMNUD>
	media: 1000baseT <full-duplex,flow-control>
	status: active
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
	lladdr c8:2a:14:ff:fe:85:b7:80 
	nd6 options=1<PERFORMNUD>
	media: autoselect <full-duplex>
	status: inactive
en1: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	ether 10:9a:dd:9e:61:21 
	nd6 options=1<PERFORMNUD>
	media: autoselect (<unknown type>)
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:18:5b:78:00 
	media: autoselect <full-duplex>
	status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether d2:00:18:5b:78:01 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 2304
	ether 02:9a:dd:9e:61:21 
	media: autoselect
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether ca:2a:14:e1:3a:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 8 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::f87d:c78d:acf0:ecce%utun0 prefixlen 64 scopeid 0xb 
	inet6 fd8b:8be3:4c9b:1aaf:f87d:c78d:acf0:ecce prefixlen 64 
	nd6 options=1<PERFORMNUD>
tun0: flags=8851<UP,POINTOPOINT,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	inet 10.161.1.6 --> 10.161.1.5 netmask 0xffffffff 
	open (pid 11607)
```

**Comment by evilhero** [comment]
Is it assigning it to the send-to-sab line though? 

I mean, it only attempts to discover the IP (if you only grab torrents, it never comes into play), so that if it's not a local IP (you assign a mylar host of something other than localhost or 0.0.0.0), it will attempt to use that. If you have your mylar host set to localhost/0.0.0.0, it shouldn't use the discovered IP at all when sending nzbs to SAB.

**Comment by weidercs** [comment]
SAB tried to retrieve the nzb from 10.161.1.6:8090 so I figured that's where it pulled it from.  Nothing is listening on 10.161.1.6 because that can change every time the interface goes up and down.

My mylar host is set to 0.0.0.0.

**Comment by evilhero** [comment]
Yeah actually I can see that happening now -  you should be able to set the host_return to your local IP (I don't think 0.0.0.0 would work for the host_return, you'd probably have to use the IP for the machine itself since you're on the VPN), and it should start linking again properly. 

I'll have to

**Comment by weidercs** [comment]
setting the host_return worked, do you want me to close this or are you going to still tweak it a little?

**Comment by evilhero** [comment]
Yeah I'm going to try and figure out some default settings. .hopefully I can get this all working automatically without telling those having problems to just use the host_return option ;)

**Comment by weidercs** [comment]
Work around in place, special case for VPN
