### ISSUE TITLE
Torrent files not valid

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1091]
When downloading torrent files through Mylar (using KAT as the source) all torrent files are downloading as invalid torrent files.

I'm running python 2.7.10

When copying the torcache address from the logs (where it says KAT Referer set to) into a browser, the torrent will download correctly making me think that Mylar is somehow corrupting the torrent on download.

The logs for a torrent file that will not open from Mylar but will in the browser is below:

21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ComicID:None
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : mode:readlist
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : Story Arc : Secret Wars queueing selected issue...
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : IssueArcID : 58266_9817
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : Marking Secret Wars: Battleworld 3 as wanted...
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Unable to locate given IssueID within the db. Assuming Issue Title is None.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Issue Title not found. Setting to None.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : One-Off Search parameters:
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ComicName: Secret Wars: Battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Issue: 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Year: 2015
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : IssueDate:2015-09-30
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Story-ARC Search parameters:
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Story-ARC: Secret Wars
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : IssueArcID: 58266_9817
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Checking for torrent enabled.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : nzbprovider(s): []
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : there are : 1 torrent providers you have selected.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : there are : 0 nzb providers you have selected.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Usenet Retention : 1500 days
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : found provider in existing enabled providers.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : checking against torrent provider: kat
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : torrent provider found: kat
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : provider order sequence is now to start with kat at spot #0
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : search provider order is ['kat']
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Initiating Search via : rss
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : Shhh be very quiet...I'm looking for Secret Wars: Battleworld issue: 3 (2015) using KAT [RSS]
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : calpha/cnumber: None / None
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : RSS Check: yes
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : nzbprov: KAT
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : comicid: None
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Sending request to [KAT] RSS for Secret Wars: Battleworld : 003
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : tsearch : secret%wars%%battleworld%
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : seriesname_alt:None
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : tor-Title: Secret Wars - Battleworld 003 (2015) (digital-Oroboros).cbr
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : there are 1 sections in this title
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : section(0): Secret Wars - Battleworld 003 (2015) (digital-Oroboros).cbr
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : rebuiltline is :Secret Wars - Battleworld 003 (2015) (digital-Oroboros).
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 56 - formatrem_torsplit : secret wars battleworld 003 (2015) (digital oroboros)cbr
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 23 - formatrem_seriesname :secret wars battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : matched to : Secret Wars - Battleworld 003 (2015) (digital-Oroboros).cbr
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : matched on series title: Secret Wars: Battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : titleend:  003 (2015) (digital oroboros)
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : tor-Title: Secret Wars - Battleworld 03 (of 04) (2015) (digital) (Minutemen-Faessla).cbz
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : there are 1 sections in this title
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : section(0): Secret Wars - Battleworld 03 (of 04) (2015) (digital) (Minutemen-Faessla).cbz
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : rebuiltline is :Secret Wars - Battleworld 03 (of 04) (2015) (digital) (Minutemen-Faessla).
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 74 - formatrem_torsplit : secret wars battleworld 03 (of 04) (2015) (digital) (minutemen faessla)cbz
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 23 - formatrem_seriesname :secret wars battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : matched to : Secret Wars - Battleworld 03 (of 04) (2015) (digital) (Minutemen-Faessla).cbz
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : matched on series title: Secret Wars: Battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : titleend:  03 (of 04) (2015) (digital) (minutemen faessla)
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : checking search result: Secret Wars - Battleworld 003 (2015) (digital-Oroboros).
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : size given as: 48.8 MB
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Wed, 15 Jul 2015 15:37:55 +0000 is after store date of 2015-07-15
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Entry: Secret Wars - Battleworld 003 (2015) (digital-Oroboros).
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Cleantitle: secret wars - battleworld 003 (2015) (digital-oroboros) 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Cleantitle: secret wars - battleworld 003 (2015) (digital-oroboros) 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 0. Bracket Word: secret wars - battleworld 003 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Comic: secret wars - battleworld 003 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : UseFuzzy is  : None
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ComVersChk : 0
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 1. Bracket Word: 2015
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : year detected: 2015
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : year looking for: 2015
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 2015 - right years match baby!
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 3. Bracket Word: digital-oroboros
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Scanner detected: digital-oroboros
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : original nzb comic and issue: secret wars - battleworld 003 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : [Secret Wars: Battleworld] I have found a -  within the nzbname @ position: 12
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : There is no hyphen present in the series title.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Assuming position start is : 12
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : First word of issue stored as : battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : adjusted nzb comic and issue: secret wars   battleworld 003 
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : adjusting from: secret wars   battleworld 003  to: 003
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ['secret', 'wars', 'battleworld', '003'] nzb series word count: 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ['secret', 'wars', 'battleworld'] watchlist word count: 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : splitst : 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : len-watchcomic : 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : length match..proceeding
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : search-length: 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Watchlist-length: 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : splitit: secret
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : scount : 0
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 0 Comparing: secret .to. secret
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : word matched on : secret
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : splitit: wars
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : scount : 1
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 1 Comparing: wars .to. wars
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : word matched on : wars
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : splitit: battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : scount : 2
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : 2 Comparing: battleworld .to. battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : word matched on : battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : scount:3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : splitit-len:3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Match to series : 100.0 %.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : it's a go captain... - we matched 100.0%!
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : this should be a match!
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : issue we are looking for is : 3
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : integer value of issue we are looking for : 3000
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : issue we found for is : 003
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : integer value of issue we have found : 3000
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : nzbname used for post-processing:Secret.Wars.-.Battleworld.003.(2015).(digital-Oroboros).
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : [KAT] link: 0841CC2A98532ED15C1F0E361D7FE27DF2966D9F
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : prov  : KAT [RSS][0841CC2A98532ED15C1F0E361D7FE27DF2966D9F]
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : issues match!
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : Found Secret Wars: Battleworld (2015) issue: 3 using KAT [RSS]
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : link given by: KAT
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : sending .torrent to watchdir.
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : ComicName:Secret Wars: Battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : link:0841CC2A98532ED15C1F0E361D7FE27DF2966D9F
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : Torrent Provider:KAT
21-Jul-2015 21:51:20 - INFO    :: CP Server Thread-7 : matched on Secret Wars: Battleworld
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : filename for torrent set to : /Users/tv/Downloads/Secret_Wars_Battleworld_3_2015.torrent
21-Jul-2015 21:51:20 - DEBUG   :: CP Server Thread-7 : KAT Referer set to :http://torcache.net/torrent/0841CC2A98532ED15C1F0E361D7FE27DF2966D9F.torrent
21-Jul-2015 21:51:21 - DEBUG   :: CP Server Thread-7 : [KAT] Saved torrent file to : /Users/tv/Downloads/Secret_Wars_Battleworld_3_2015.torrent
21-Jul-2015 21:51:21 - DEBUG   :: CP Server Thread-7 : we should break out now - sucessful search previous
21-Jul-2015 21:51:21 - DEBUG   :: CP Server Thread-7 : Found matching comic...preparing to send to Updater with IssueID: None and nzbname: Secret.Wars.-.Battleworld.003.(2015).(digital-Oroboros).
21-Jul-2015 21:51:21 - INFO    :: CP Server Thread-7 : setting the nzbid for this download grabbed by KAT in the nzblog to : 0841CC2A98532ED15C1F0E361D7FE27DF2966D9F
21-Jul-2015 21:51:21 - DEBUG   :: CP Server Thread-7 : Deleted stale entry from nzblog for IssueID: S58266_9817 [KAT]
21-Jul-2015 21:51:21 - DEBUG   :: CP Server Thread-7 : findit = found!
21-Jul-2015 21:51:21 - INFO    :: CP Server Thread-7 : Downloaded Secret Wars: Battleworld #3 (2015)

**Comment by evilhero** [comment]
Are the files themselves valid torrent files? (Meaning they're not 0 byte files). Mylar downloads the torrent to the cache directory and then moves it to your designated watch folder.

I'm going to guess that the user running your torrent client doesn't have the permissions to read torrent file in the location (as mylar wrote it). Or even mylar doesn't have permissions to write to your watch folder.

I don't seem to have any problems snatching/sending torrents via KAT (using development build of mylar,  python 2.7.9 on Ubuntu 12.04)

**Comment by kurnalbert** [comment]
The files it creates are all 168bytes in size. When trying to open them manually, Transmission errors saying they are not valid. Opening the file in a text editor, it just shows 403 forbidden errors.

I had this issue once before but updating the version of Python did resolve it.

Torrent files being written to this folder have always worked from Mylar before. Saving torrent files there from a browser will have them automatically picked up by the torrent client still.

This is all on the development build, which was updated earlier today. It is possible that it was after the update that the issues started to occur.

**Comment by evilhero** [comment]
Permissions have changed in the last Dev commit..you'll have to check the perms on the torrent files themselves,  both in the cache directory of mylar and your watchlist directory. Nothing has changed in relation to how mylar downloads from kat, and like I said I have no issues sending and picking up from the watch directory.  Downloading from a browser vs. how mylar downloads the torrent files will have different permissions as it's app/user dependent.

If you have installed mylar not from source or via git (ie. 3rd party,  docker,  etc ), they tend to move directories and permissions around quite liberally in some cases which causes problems.

**Comment by gamergeekv2** [comment]
I am having this same issue.

**Comment by thorinmesser** [comment]
Same here. It is not a permissions issue on the computer, KAT is sending a 403 forbidden error as the response to the request for the torrent. A very similar problem did indeed happen before, issue 1025. That time is was something in python and https vs https resulting in 404 errors.

**Comment by kurnalbert** [comment]
To be sure, I double checked all of the permissions on the computer and everything seems to be as it should, nothing has changed.

Mylar is installed from Git directly, not through a third party. As I said, the torrent files are being created fine, it's just they are not valid files, they only contain the following:

"403 Forbidden

nginx/1.9.2"

It does seem exactly the same as issue 1025 but I have confirmed that I am definitely running python 2.7.10

**Comment by evilhero** [comment]
Yep I'm getting it now too...it's definitely something up with the https and or the referrer it's using (or a combo). I'll look into it more in abit once I can get to a machine (I checked at 5am when one of the kids woke up, whose still asleep on me lol).

**Comment by evilhero** [comment]
Ok, here's an update. It looks like torcache implemented some kind of timer restriction to limit the use of automated downloads (some JS script). The workaround is to just use a different cache provider than torcache (if you look at some of the other automated downloaders - headphones, sickrage, etc) they're all having the same kind of issues posted.

I'll see if I can commit up something quick to jump from torcache

**Comment by kurnalbert** [comment]
That seems to have fixed it all again.

Thank you so much!

**Comment by gamergeekv2** [comment]
Did this get fixed? I'm still having the issue?

**Comment by glberen** [comment]
I'm still having this issue as well.

**Comment by evilhero** [comment]
It should be fixed on the development branch as long as your python version is 2.7.7+.

If it's not workimg, then you might be having a different problem and need to confirm that the file is incorrectly written to your cache directory as a file that when opened up has a 403 error within.

**Comment by glberen** [comment]
Yep, that was it. Somehow, I'd lost the .git folder and couldn't update then, so I pulled down a new copy and moved my DB and config over, neglecting to copy my .python-version file as well. It's dumping a good file now that's getting picked up by transmission. Thanks for your help!

**Comment by JediKnut** [comment]
Hey, I had the same problem with the last Mylar update, except I don't get a 403 forbidden error. I was getting an error that said: Unable to load "torrent_name":torrent is not valid bencoding! (obviously with the actual torrent name inside.

I updated Python from 2.7.6 to 2.7.9, but had to re-populate the full DB and after that it started working.
After I updated Mylar yesterday, I'm having the same issue, and was wondering what to do. Hope i don't have to re-install Python again.

Any help at all would be greatly appreciated!

**Comment by evilhero** [comment]
You probably have to make sure that mylar is running against the right version of python - checking in the configuration / General tab will tell you which version of python is running it.

Are the torrents from KAT or 32p? 

Shouldn't have to reinstall mylar and kind of surprised you had to repopulate the db since upgrading python wouldn't affect the db itself (unless mylar was running when you upgraded perhaps).

Is there anything in the mylar.log file after you grab a torrent that sheds any more information ?

**Comment by JediKnut** [comment]
This is what it says in the Settings tab:

Mylar Version: master
-- source build e44d5817a329aa9e1bab1344476d03ffd11b314e.
Python Version : 2.7.9

I'm using KAT.

This is the message in the command prompt window:

23-Jul-2015 11:04:22 - INFO :: Thread-14 : setting the nzbid for this download grabbed by KAT in the nzblog to : 15B0F10EBFA89BC6619ED4F6B33D7AA15D3AF1D8
23-Jul-2015 11:04:22 - INFO :: Thread-14 : Sending NMA notification

Just noticed it's saying nzblog. I don't use newsgroups and am not subscribed to any. Does this have anything to do with it?

The logs tab has a similar message:
2015-07-23 11:04:22 	INFO 	setting the nzbid for this download grabbed by KAT in the nzblog to : 15B0F10EBFA89BC6619ED4F6B33D7AA15D3AF1D8

I didn't re-install Mylar (either this time or last). I got the notification message that there was an update available, so I updated it. Python was re-installed. Last time around I was using 2.7.6 so I just upgraded to the latest vers (2.7.9). This time so far, all I've done is update Mylar to the latest version.

I probably didn't copy the db folders correctly, and so had to re-add everything, but really, I don't know much about using Python.

It's the same problem as last time. I can see the .torrent file in my watch folder, but it's being saved as a 168b file, so it's definitely got corrupt on the way down. 

Obviously, if I do a manual search using KAT the magnet link works fine. In fact, I also have an RSS feed, and if I click on the post in my reader, it starts the transfer automatically.

Is there any other specific information you'd need? Hope this issue can be sorted!

**Comment by evilhero** [comment]
The fix for KAT is currently in the development branch only.  You're in the master so you'd have to switch branches in order to get things back on track. It should be fairly easy - with mylar not running edit your config.ini file and change the line git_branch = master 
to 
git_branch = development

Save the config.ini,  start up mylar and it should prompt to update and then you're good to go

**Comment by JediKnut** [comment]
I wouldn't mind using the development branch if it means not having to do this each update! No clue why I even chose the master branch. Probably followed the instructions wrong while installing Python!

As is obvious, I'm not really familiar with Python or linux!

Changing the .ini file is simple enough. Will try it & get back!

**Comment by JediKnut** [comment]
Went into my Program Files folder where Python is installed. I have kept the Mylar-master folder in that, where I have installed everything.
Going into that folder, I edited the config.ini & changed git_brand = development.
Didn't seem to make a difference though. Still the same issue of 168b files.

It didn't prompt for an update after I re-started Mylar though.

**Comment by evilhero** [comment]
which commit are you currently running? And which branch?  (Both of the info can be found in the configuration / General tab ).

Note: git_branch not git_brand ;)

**Comment by JediKnut** [comment]
Which commit? You mean which version of Mylar?
This is what it says in the Settings - Information tab:

Configuration Options
Mylar Version: master
-- source build e44d5817a329aa9e1bab1344476d03ffd11b314e.
Python Version : 2.7.9

Reading that, I saw that it still says 'master' instead of 'development'. I changed the ini file again but it doesn't seem to save it like that!

So after seeing that I checked the file and yep, it says master. Saved it, shut Mylar & re-started it, and I saw in the command promt, the following line appears:

23-Jul-2015 21:03:12 - INFO :: MAIN : Branch detected & set to : master

So that's probably changing the config.ini file.

Completely lost & stumped as to why this is happening!

**Comment by evilhero** [comment]
You can't edit the config.ini when mylar is running. Shut it down first, then edit the file, save the file and start up mylar.

**Comment by JediKnut** [comment]
Sorry, I didn't mention, but I did that...
Shut it down, made changes, made sure it's corrected.
Re-started & noticed it's changing in the dos prompt when I run Mylar.

**Comment by JediKnut** [comment]
Maybe I should also mention that I'm unable to edit the config.ini file on it's own.

It's saved in my c:\Program Files (x86) folder and it doesn't let me edit it.
What I do is move it to another folder (have to do it as admin), edit it & save it and then move it back (as admin).
Then when I open the file (in the prog files\python folder it still says git_branch = development

But when I start Mylar from cmd prompt I see it saying that "Branch detected & set to : master" line.

**Comment by evilhero** [comment]
Well it tries to auto detect on startup, and then (if its not already present) writes the branch information into the config.ini file as it's needed throughout the program.

Are you editing the correct config.ini file ? (It should be located in the same directory as the Mylar.py file).

One last question - how did you install mylar ..from source or using git to clone the repo?

**Comment by gamergeekv2** [comment]
I'm having the same issue. I change to development, Save, close, and reopen. It's there. Launch Mylar and it says it can't find branch. Resets it to Master. Open Config.ini and it's set to master again.

**Comment by evilhero** [comment]
Did you install from source or via git clone? You might be stuck on that one commit that messed up the branches abit on startup. In either case, the best bet would be go either download the newest source again or do a fresh git clone.

In both cases, make sure you backup your config.ini,  mylar.db, and the cache directory  (holds the images for the covers). Once you've upgraded you can move these items  back and start things up so things truck along again.

**Comment by gamergeekv2** [comment]
This fixed it.

**Comment by JediKnut** [comment]
I'm not entirely sure since I don't use Python for almost anything else, but I think I installed it from source.

I do have two Python folders. I can delete the old one (2.7.6), but yes, I am editing the correct config.ini file. The file location is: c:\Program Files (x86)\Python 2.7.9\mylar-master\config.ini & the Mylar.py file is in the same folder.

I'm ok re-installing it all (guessing I don't need to re-install Python as well this time), but would probably need help un-installing & re-installing Mylar so I don't mess it up again!

Apologies, and thanks again!

**Comment by JediKnut** [comment]
Any suggestions on how / what to do?

**Comment by evilhero** [comment]
If you don't have git installed, you would have to install mylar from source (meaning downloading the .zip file and extracting it yourself basically). The preferred method is via git as then mylar can use git to update things via the gui. From source is fine, the gui updater will work fine - but the git aspect has a bit more functionality. 

So download the source for mylar, and extract it into a new mylar directory. If you have a preexisting config.ini and mylar.db then copy those over as well.  Start up mylar (double-clicking on Mylar.py) and it will put itself on the master branch by default.  Shutdown Mylar,  edit the config.ini and change:
git_branch = master
to
git_branch = development 

Save the config.ini and then startup mylar and should denote you're in the development branch.

**Comment by JediKnut** [comment]
Ok, a few questions, which may be quite daft:

1) Download the file: This link right?
https://github.com/evilhero/mylar/archive/master.zip

2) Should I delete the existing Mylar folder first (after copying the cache, config.ini & mylar.db files?

3) Start Mylar: Double clicking Mylar.py never worked for me... I always went to my dos prompt, to the folder where Python / Mylar were installed & had to type python Mylar.py. Do I continue in the way I'm used to?

**Comment by JediKnut** [comment]
Help me evilhero, you're my only hope!

Thanks!

**Comment by evilhero** [comment]
Wow, sorry I didn't see this - I don't check the Closed issues very often, but here's the answers to the Q's :)

1) You should probably use this link so you're on the development branch immediately: https://github.com/evilhero/mylar/archive/development.zip 

2) Probably wouldn't be a bad idea - having more than one copy of Mylar isn't really necessary.

3) Yeah you're right sorry, wasn't thinking when I typed that out. You could also issue a python command from anywhere in your dos shell depending on where your python is (ie. c:\python2.7\python.exe c:\mylar\Mylar.py or if you have your python in your PATH, it would be as simple as doing 'python.exe c:\mylar\Mylar.py from anywhere)

**Comment by JediKnut** [comment]
Thanks a ton & no problem. Will try this & get back to you!

**Comment by JediKnut** [comment]
Works like a charm! Thanks a ton!
I've actually created an autorun.bat file with the following: 

cd\
cd C:\Program Files (x86)\Python 2.7.9\mylar-development\
python Mylar.py

And instead of having to run the DOS prompt & type it all out, I just run the file as Admin, and it works like a charm.

Thanks again for all the help!
