### ISSUE TITLE
Searching results in 500 Internal Server error

### ISSUE THREAD

**Issue by blkphnx** [evilhero/mylar#1096]
Whenever I try to search for a new comic to add I get the following error. I tried switching to the master branch from development but still see the same error. I didnt see this error a week back so might have been introduced by latest commits.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 200, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=None, explicit=explicit)
TypeError: 'bool' object is not iterable

**Comment by evilhero** [comment]
Everything is working fine with searching, it would appear to be a local issue of some nature.

Have you restarted/shutdown mylar since getting the error message?

What were you searching for when it errored out?

**Comment by blkphnx** [comment]
Yes. I tried doing that and also restarted my PC. Getting the same error.

From the logs, I am seeing the following.

31-Jul-2015 09:31:57 - DEBUG   :: CP Server Thread-5 : Default search mode - this will match on ALL search words
31-Jul-2015 09:31:58 - ERROR   :: CP Server Thread-5 : err : HTTP Error 403: Forbidden
31-Jul-2015 09:31:58 - ERROR   :: CP Server Thread-5 : There was a major problem retrieving data from ComicVine - on their end. You'll have to try again later most likely.

I changed my API key to a different account's key but still getting the same error. My API key works fine with ComicRack so I am sure thats not the problem.

**Comment by evilhero** [comment]
If it's saying forbidden - that's probably exactly what it is. The forbidden message is indicating that you don't have the proper permissions (apikey) to retrieve the resource. 

Either you got blacklisted for having multiple apikeys or you hit the maximum of api hits / 15 minutes (they currently have it set to 400 hits / 15 minutes - keep in mind it's 400 universal hits, meaning it's a shared 400 hits from all your applications that uses that same api key). CV has started enforcing some stiffer penalities for multiple keys and hammering, so it could be either of those issues.

**Comment by blkphnx** [comment]
You are right. I set up Mylar to run on a VPS. I am unable to access comicvine.com from my VPS browser. Looks like they have banned that IP range. 

Its not an issue with too many request from my side. My guess is the shared servers share a common IP.
