### ISSUE TITLE
some comic counts incorrect

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1098]
For a few comics, i have every issue, including annuals, but the count shows that i'm missing some (e.g. 47/50), even though mylar has clearly identified a file for each entry in the detail page. Rescanning the files does not change it. What logs would you need to support this issue?

**Comment by evilhero** [comment]
Would need to see the mylar.log file showing the complete file check scan.  It also might be screwing up the count because of the status that's being changed to/from - if the 3 missing are annuals (or you have 3 annuals in the given series), that might be the cause of the discrepancy as well - but without seeing the .log file it's hard to even guess.

**Comment by mnbf9rca** [comment]
log file here: http://pastebin.com/g0SNEYDx. I shut down mylar, removed mylar.log, restarted and then scanned one of the comics with the issue (Action Comics). Below is a listing of the comic folder, which shows there are 57 comic files (for some reason it's downloaded 7 duplicates - didnt notice that before. Any idea why?) but there are clearly all 50 issues here, and when i browse the comic page in Mylar no issues show as missing:
ro@s:~/Dropbox/Comics/Action Comics (2011)$ ls -alh
total 2.0G
drwxrwxr-x  2 ro ro 4.0K Jul 25 01:05 .
drwxrwxr-x 53 ro ro 4.0K Jul 24 20:43 ..
-rw-rw----  1 ro ro  20M Jun 28 23:43 Action Comics 000 (2012).cbr
-rw-rw----  1 ro ro  20M Jun 28 23:36 Action Comics 000 (2012).cbz
-rw-rw----  1 ro ro  35M Jun 28 22:20 Action Comics 001 (2011).cbz
-rw-rw----  1 ro ro  16M Jun 28 23:43 Action Comics 002 (2011).cbr
-rw-rw----  1 ro ro  16M Jun 28 23:35 Action Comics 002 (2011).cbz
-rw-rw----  1 ro ro  17M Jun 28 23:43 Action Comics 003 (2012).cbr
-rw-rw----  1 ro ro  17M Jun 28 23:35 Action Comics 003 (2012).cbz
-rw-rw----  1 ro ro  20M Jun 28 23:43 Action Comics 004 (2012).cbr
-rw-rw----  1 ro ro  20M Jun 28 23:36 Action Comics 004 (2012).cbz
-rw-rw----  1 ro ro  20M Jun 28 23:43 Action Comics 005 (2012).cbr
-rw-rw----  1 ro ro  20M Jun 28 23:35 Action Comics 005 (2012).cbz
-rw-rw----  1 ro ro  20M Jun 28 22:13 Action Comics 006 (2012).cbz
-rw-rw----  1 ro ro  19M Jun 28 23:43 Action Comics 007 (2012).cbr
-rw-rw----  1 ro ro  19M Jun 28 23:35 Action Comics 007 (2012).cbz
-rw-rw----  1 ro ro  21M Jun 28 22:19 Action Comics 008 (2012).cbz
-rw-rw----  1 ro ro  29M Jun 28 22:17 Action Comics 009 (2012).cbz
-rw-rw----  1 ro ro  20M Jun 28 23:43 Action Comics 010 (2012).cbr
-rw-rw----  1 ro ro  19M Jun 28 23:36 Action Comics 010 (2012).cbz
-rw-rw----  1 ro ro  23M Jun 28 22:13 Action Comics 011 (2012).cbz
-rw-rw----  1 ro ro  24M Jun 28 22:19 Action Comics 012 (2012).cbz
-rw-rw----  1 ro ro  21M Jun 28 22:17 Action Comics 013 (2012).cbz
-rw-rw----  1 ro ro  26M Jun 28 22:13 Action Comics 014 (2013).cbz
-rw-rw----  1 ro ro  25M Jun 28 22:15 Action Comics 015 (2013).cbz
-rw-rw----  1 ro ro  29M Jun 28 22:19 Action Comics 016 (2013).cbz
-rw-rw----  1 ro ro  20M Jun 28 22:12 Action Comics 017 (2013).cbz
-rw-rw----  1 ro ro  27M Jun 28 22:14 Action Comics 018 (2013).cbz
-rw-rw----  1 ro ro  44M Jun 28 22:19 Action Comics 019 (2013).cbz
-rw-rw----  1 ro ro  53M Jun 28 22:17 Action Comics 020 (2013).cbz
-rw-rw----  1 ro ro  53M Jun 28 22:13 Action Comics 021 (2013).cbz
-rw-rw----  1 ro ro  54M Jun 28 22:16 Action Comics 022 (2013).cbz
-rw-rw----  1 ro ro  37M Jun 28 22:18 Action Comics 023.1 (2013).cbz
-rw-rw----  1 ro ro  54M Jun 28 22:16 Action Comics 023 (2013).cbz
-rw-rw----  1 ro ro  39M Jun 28 22:19 Action Comics 023.2 (2013).cbz
-rw-rw----  1 ro ro  31M Jun 28 22:17 Action Comics 023.3 (2013).cbz
-rw-rw----  1 ro ro  35M Jun 28 22:15 Action Comics 023.4 (2013).cbz
-rw-rw----  1 ro ro  43M Jun 28 22:20 Action Comics 024 (2013).cbz
-rw-rw----  1 ro ro  50M Jun 28 22:14 Action Comics 025 (2014).cbz
-rw-rw----  1 ro ro  43M Jun 28 22:18 Action Comics 026 (2014).cbz
-rw-rw----  1 ro ro  44M Jun 28 22:16 Action Comics 027 (2014).cbz
-rw-rw----  1 ro ro  50M Jun 28 22:18 Action Comics 028 (2014).cbz
-rw-rw----  1 ro ro  50M Jun 28 22:18 Action Comics 029 (2014).cbz
-rw-rw----  1 ro ro  43M Jun 28 22:17 Action Comics 030 (2014).cbz
-rw-rw----  1 ro ro  50M Jun 28 22:15 Action Comics 031 (2014).cbz
-rw-rw----  1 ro ro  49M Jun 28 22:14 Action Comics 032 (2014).cbz
-rw-rw----  1 ro ro  52M Jun 28 22:13 Action Comics 033 (2014).cbz
-rw-rw----  1 ro ro  50M Jun 28 22:14 Action Comics 034 (2014).cbz
-rw-rw----  1 ro ro  48M Jun 28 22:16 Action Comics 035 (2014).cbz
-rw-rw----  1 ro ro  44M Jun 28 22:15 Action Comics 036 (2015).cbz
-rw-rw----  1 ro ro  42M Jun 28 23:16 Action Comics 037 (2015).cbz
-rw-rw----  1 ro ro  35M Jun 28 23:16 Action Comics 038 (2015).cbz
-rw-rw----  1 ro ro  48M Jul  4 05:44 Action Comics 039 (2015).cbz
-rw-rw----  1 ro ro  49M Jun 28 23:16 Action Comics 040 (2015).cbz
-rw-rw----  1 ro ro  36M Jun 28 23:16 Action Comics 041 (2015).cbz
-rw-rw----  1 ro ro  38M Jul  3 23:39 Action Comics 042 (2015).cbz
-rw-rw----  1 ro ro  27M Jun 28 22:06 Action Comics Annual 001 (2012).cbr
-rw-rw----  1 ro ro  64M Jun 28 22:07 Action Comics Annual 002 (2013).cbr
-rw-rw----  1 ro ro  84M Jun 28 22:07 Action Comics Annual 003 (2014).cbr
-rw-rw----  1 ro ro 160K Jul  1 21:18 cover.jpg
-rw-rw----  1 ro ro   50 Jul  1 21:18 cvinfo

**Comment by evilhero** [comment]
I can't seem to duplicate this for the life of me - same exact series, same issue counts and it's all matching up fine and indicating 50/50. 

Do you have annuals enabled in the configuration? (from the looks of it you do - but just need to clarify).

If it's saying 47/50 - there should be 3/50 issues that are in a status other than Downloaded?

When was the last time you restarted mylar (if you were toggling annuals on/off and didn't save it - it would mess things up)? Restarting after any kind of error is recommended as well, so that things can start from a clean slate, instead of possibly carrying invalid values throughout the program.

**Comment by mnbf9rca** [comment]
it says this:
![image](https://cloud.githubusercontent.com/assets/1039058/9069870/dceb3868-3ae3-11e5-855f-d12f8d771bef.png)

and the whole comic page looks like this:
![image](https://cloud.githubusercontent.com/assets/1039058/9070176/e2fec0f6-3ae5-11e5-831a-745a7ab03957.png)

**Comment by evilhero** [comment]
Ok so it's not tallying the annuals with the issue total. I thought I had this fixed a few months ago, but if it's still occuring then it's something I need to look into more.

I'll mark this as a bug until I can look into it later on today and see why it's ignoring the annual counts.
