### ISSUE TITLE
Feature Request (Comicvine API)

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#1100]
Comicvine now limit API hits to 400 per day. Aside from the morally ambiguous practice of having multiple Comicvine accounts and API keys, is or would it be considered to allow Mylar accept multiple Comicvine API keys and cycle through them?

**Comment by evilhero** [comment]
You'll get banned for having shadow accounts as the api key is tied to your IP. Both your apikey and your IP would be banned .

It's actually 500/24 hrs but that's limited to just searching. I'll have to see exactly what kind of requests mylar is doing. I have a feeling some of the open ended searches would definitely hit that (ie. A-Force was one series that brought back an enormous amount of hits for no real reason).

The best practice in this type of stuff is to not try and circumvent, but to try and find a way to make things work - in this case it wouldn't be a bad thing to tighten how mylar does searches against CV regardless
