### ISSUE TITLE
Manual post-processing / folder scan issue

### ISSUE THREAD

**Issue by animedork** [evilhero/mylar#1103]
I've been experiencing an issue with post-processing since the last update (possibly before?). Here is the error I'm currently seeing on my log:

06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] There are 810 files found that match on your watchlist, 1907 do not match anything and will be ignored.
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] comic: Thanos Rising
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] Looking in: /local/downloads/@COMPLETE/MYLAR
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : there are 965 files.
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] numberinseries: False
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] decimalinseries: False
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] bracketinseries: False
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] subnm len : 9
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: 'NoneType' object has no attribute 'lower'
06-Aug-2015 17:38:39 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "/usr/local/lib/mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/usr/local/lib/mylar/mylar/PostProcessor.py", line 1535, in run\n    result = PostProcess.Process()\n  File "/usr/local/lib/mylar/mylar/PostProcessor.py", line 427, in Process\n    arcmatch = filechecker.listFiles(self.nzb_folder, k, v[i][\'ArcValues\'][\'ComicPublisher\'], manual=v[i][\'WatchValues\'])\n  File "/usr/local/lib/mylar/mylar/filechecker.py", line 349, in listFiles\n    if Publisher.lower() in re.sub(\'_\', \' \', subname.lower()):\nAttributeError: \'NoneType\' object has no attribute \'lower\'\n'

This appears to happen either when the folder monitor does a periodic scan (it finds a number of issues but hangs there at the end of the scan from what I can tell) and I get the same result when I initiate a manual scan via Manage > Manual Post-Processing. Hoping to find it's just something I've done wrong to cause the issue but could use some assistance at this point.

**Comment by animedork** [comment]
As an aside, post-processing through SAB is working properly. It's just the folder monitor/scan that is not currently for me.

**Comment by evilhero** [comment]
If that's the exact same error that occurs on every run,  then it's that series (Thanos Rising) that is causing the problem. It looks like it doesn't have a publisher - can you verify on the series detail page for that particular series if it has a publisher present?

**Comment by animedork** [comment]
It does appear to be the exact same error on each run (the periodic scan ran again and it's repeated there) but the odd thing is that I don't have any from that series (Thanos Rising) in that folder. I've run a find command on a few different keywords and wildcards related to that series title and it doesn't show anything filename-wise. Additionally, from what I'm seeing Thanos Rising is listed with Marvel as the publisher on CV.

**Comment by evilhero** [comment]
Well with manual post-processing,  mylar has to scan through each series in your watchlist since it's doing text based comparisons (normal post-processing ties things to the proper comicid/issueid so it's not a problem). Once the scan hits that particular series, it's dying for some reason. Sometimes CV doesn't have the correct information or is lacking information about series and even stranger sometimes it is different results when using the apikey vs the website. However if that series has incomplete issue data, it's quite possible the publisher is blank on your installation (a simple Refresh Series would be enough to line things back up usually)

**Comment by animedork** [comment]
I'll give that a try and report back! Thanks a bunch!

**Comment by animedork** [comment]
No good unfortunately, still getting the same exact error after not only refreshing Thanos Rising but all of the series in my database. Any other ideas?

**Comment by evilhero** [comment]
Which Thanos Rising series are you watching (there's the mini-series, and then a tpb)?

**Comment by animedork** [comment]
It appears to be the five-issue series (http://www.comicvine.com/thanos-rising/4050-59511/). I have all of the issues/0 wanted in the series so if there's some way I can exclude that I'd go that route.

**Comment by evilhero** [comment]
Abit weird, I have that same series in my watchlist and can't reproduce any sort of problems with it - so it's not the series per-se. Can you check what your mylar has listed for that series publisher  - it's definitely getting hung up on that value for some reason with that particular series.

You 'could' also try to delete the series from your watchlist, and then try manual post-processing to see if the error just moves to another series or if it lets things continue normally.

**Comment by animedork** [comment]
If I'm going to the right place, it does show "Marvel." I'll try deleting it and rechecking again.

![thanos](https://cloud.githubusercontent.com/assets/4765513/9146454/e16bf87a-3d2a-11e5-914d-67378d1b1ac8.jpg)
![thanos2](https://cloud.githubusercontent.com/assets/4765513/9146455/e170ca12-3d2a-11e5-8d8c-73ead4d22e37.jpg)

**Comment by animedork** [comment]
Now I'm extremely confused.. I deleted the series from Mylar, restarted it, and it's STILL giving the same exact error. If it's helpful at all, here's what the web interface log always hangs at:

![thanos3](https://cloud.githubusercontent.com/assets/4765513/9146883/a25d2b3c-3d2e-11e5-906b-8ecab59f4468.jpg)

**Comment by evilhero** [comment]
Does it actually still say the Thanos Rising portion a few lines prior to the error? (in the mylar.log file)

Can I ask what branch/commit you're currently running of mylar? (Check the configuration, 1st tab for the info)

**Comment by animedork** [comment]
Yes, it's the exact same error with the comic: 

07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] watchcomic:Civil War ..comparing to found file: Uncanny X Men 19
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] you have a total of 0 Civil War comics
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] There are 810 files found that match on your watchlist, 1906 do not match anything and will be ignored.
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] comic: Thanos Rising
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] Looking in: /local/downloads/@COMPLETE/MYLAR
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : there are 965 files.
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] numberinseries: False
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] decimalinseries: False
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] bracketinseries: False
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] subnm len : 9
07-Aug-2015 17:56:21 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: 'NoneType' object has no attribute 'lower'

(I deleted the last line of the log when cutting in terminal by accident heh.. it was the same though).

Version information:

Mylar Version: development
-- git build ec31c9ec9d75b5562efafc5843c7dd9b2818505f.
Python Version : 2.7.9

**Comment by evilhero** [comment]
How often do you have the folder monitor running ? I'm wondering if it's somehow sending multiple requests and locking itself out after the initial attempt is still trying to run.

**Comment by animedork** [comment]
Hmm... every 60 minutes but there are a *lot* of things in there that it hasn't been able to churn through. I'll disable the folder check, restart, then do a manual run.

**Comment by animedork** [comment]
I'll also increase that going forward regardless, I forgot that I set it to 60 awhile back for some reason. That's way too often..

**Comment by evilhero** [comment]
Well having to scan through 2500+ comics is going to take a while and it would probably try to run it multiple times.  For a consistently smaller set it works fine (I have mine set to scan every 5 minutes,  but there's usually not more than 30 comics at a time in there).

I'm not saying that's the cause, but there's something amiss happening with your runs and it's really hard to troubleshoot (obviously lol).

I can work on locking the manual run & folder monitor so that only one instance can be running at a time -but it'd be good to figure out if that would actually fix your issues atm.

**Comment by animedork** [comment]
Still no joy. Disabled the scheduled folder check in addition torrent/nzb searches (so nothing else scheduled would pop and I could run just a manual run without interruption immediately upon restart). I believe it's the same exact error, including Thanos Rising, though it appears a little differently, and it also appears in the web log and not just in the mylar.log file..

07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [POST-PROCESSING] There are 810 files found that match on your watchlist, 1906 do not match anything and will be ignored.
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] comic: Thanos Rising
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] Looking in: /local/downloads/@COMPLETE/MYLAR
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : there are 965 files.
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] numberinseries: False
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] decimalinseries: False
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] bracketinseries: False
07-Aug-2015 22:35:15 - DEBUG   :: Thread-12 : [FILECHECKER] subnm len : 9
07-Aug-2015 22:35:15 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/opt/python-2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/mylar/mylar/PostProcessor.py", line 427, in Process
    arcmatch = filechecker.listFiles(self.nzb_folder, k, v[i]['ArcValues']['ComicPublisher'], manual=v[i]['WatchValues'])
  File "/usr/local/lib/mylar/mylar/filechecker.py", line 349, in listFiles
    if Publisher.lower() in re.sub('_', ' ', subname.lower()):
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by evilhero** [comment]
Did you delete Thanos Rising from your watchlist,  but it's still coming up during the error?

**Comment by evilhero** [comment]
Ooh wait - that's a story arc error...it's trying to load up arcs to see if any that your post-processing will match and it's messing up on Thanos Rising (Secret Wars arc maybe?)

**Comment by animedork** [comment]
The only story arc I had loaded (was testing it out) was Infinity. I've removed that now, restarting, and trying again!

By watchlist, I want to make sure I'm not missing anything.. I've deleted Thanos Rising completely from the database and I don't see it listed in the "Wanted" tab. Would it be anywhere else I'm missing?

**Comment by evilhero** [comment]
There were lot of changes to the arcs over the last month or two, which might be the cause of the error. Deleting and readding the arc might have been enough to fix things up (assuming removing it worked and that was the cause).

**Comment by animedork** [comment]
That was it, removing the story arc fixed that publisher error. Unfortunately, now I have a new one once it actually started post-processing/tagging/dupe checking but I'm gonna play with things more before bothering you since it seems completely unrelated. Thank you so much for the assistance with troubleshooting this one! You rock!
