### ISSUE TITLE
Moving DB from Windows to Linux

### ISSUE THREAD

**Issue by conbud** [evilhero/mylar#1104]
Hi ... I moved my installation from windows to an ubuntu server ... I was trying to find a way to move my DB (all my collections) so I didn't have to research for everything again. I moved the mylar.db over and that moved my collection but it obviously has windows pathing for each series.

Is there an easy way to update the pathing? Or, is there another way I could have went about moving my collections to a new installation on a new OS?

**Comment by evilhero** [comment]
There's instructions on the forums on how to migrate the db structure to a new location. The only caveat being that it has to be done in a certain sequence (mylar never touches the physical files during this process, it only updates the comic locations within the db itself).  I'm on my phone atm, so can't link to the forum thread, but I'll try and link it here abit later if necessary.
