### ISSUE TITLE
Manual scan doesn't find comics in folder

### ISSUE THREAD

**Issue by redfro** [evilhero/mylar#1106]
I think the might be an issue with the dates on a few of my comics on my watch list. I've downloaded tons of Preacher and Transmetropolitan, but the scan does this:

/mnt/user/apps/Sabnzbd/config/Downloads/complete/Preacher.041.1998.digital.HD.Minutemen-Midas/Preacher 041 (1998) (digital) (HD) (Minutemen-Midas).cbr
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] cchk is : Preacher
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] we should remove 0 characters
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] nonocount [0] cchk [Preacher] length [8]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] final jtd_len to prune [8]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] before title removed from FILENAME [Preacher 041 (1998) (digital) (HD) (Minutemen-Midas).cbr]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] after title removed from FILENAME [ 041 (1998) (digital) (HD) (Minutemen-Midas).cbr]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] creating just the digits using SUBNAME, pruning first [8] chars from [Preacher 041]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] after title removed from SUBNAME [041]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] JUSTTHEDIGITS [041]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] final justthedigits [041]
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] cchk = preacher
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] modwatchcomic = preacher
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] subname = preacher 041
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] SeriesYear: 1995
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] IssueTotal: 66
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] Comic Volume: None
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] volume detected: None
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] 0 Bracket Word: Preacher 041/12
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] 1 Bracket Word: 1998/4
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] year detected: 1998
13-Aug-2015 17:55:45 - DEBUG   :: Thread-12 : [FILECHECKER] 1998 - not right - year not within series range of 1995-1995

Obviously the date range Mylar is looking for is wrong, but how do I change that? It shows a publication date of 1997 to 2002, but that's not what it's searching for.

**Comment by evilhero** [comment]
I thought I had fixed this a while ago, both in the development and the master branches.

What branch / commit are you currently running? 

And is the last issue in that series have the proper issue data within mylar? (The publication date listed on the series detail page itself)

**Comment by redfro** [comment]
Development branch that ends in 9747. And all the series info looks right.

Wes Pitzer
Highway Marketing
Sent from My iPad

_____________________________

**Comment by redfro** [comment]
And it's only on Transmet and Preacher.

Wes Pitzer
Highway Marketing
Sent from My iPad




On Thu, Aug 13, 2015 at 4:42 PM -0700, "evilhero" <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought I had fixed this a while ago, both in the development and the master branches.

What branch / commit are you currently running?

And is the last issue in that series have the proper issue data within mylar? (The publication date listed on the series detail page itself)

**Comment by evilhero** [comment]
2 series I haven't tested lately - can you do a Refresh Series on each (on the series detail page)? Then try again after and see if that helped or not.

If there's anything out of whack (that probably occuring in the backend somewhere), the refresh might be able to line things up properly on its own.

**Comment by redfro** [comment]
I've already refreshed the both a couple of times, but I'll try again.

Wes Pitzer
Highway Marketing
Sent from My iPad




On Thu, Aug 13, 2015 at 5:04 PM -0700, "evilhero" <notifications@github.com<mailto:notifications@github.com>> wrote:


2 series I haven't tested lately - can you do a Refresh Series on each (on the series detail page)? Then try again after and see if that helped or not.

If there's anything out of whack (that probably occuring in the backend somewhere), the refresh might be able to line things up properly on its own.

**Comment by redfro** [comment]
Nope, no love.

Wes Pitzer
Highway Marketing
Sent from My iPad




On Thu, Aug 13, 2015 at 5:04 PM -0700, "evilhero" <notifications@github.com<mailto:notifications@github.com>> wrote:


2 series I haven't tested lately - can you do a Refresh Series on each (on the series detail page)? Then try again after and see if that helped or not.

If there's anything out of whack (that probably occuring in the backend somewhere), the refresh might be able to line things up properly on its own.

**Comment by evilhero** [comment]
Ok I'll try adding one of those series to my repo and see if I can replicate the issue, or at least figure out what's happening...

**Comment by evilhero** [comment]
Ahh ok, I can see now. All of the Store Dates for the series are actually '0000-00-00' which is what Mylar uses to try and get the last issue that was published from a series (since the publication dates are sometimes realy out there sometimes). 

Since they're all '0000-00-00', it just takes the start of the series as the end point (1995-04-01) which is obviously wrong. I've fixed it so that it will now take the Latest Date value (from the main home page) and the actual last issue published (Store Date), and if they're not the same then do some quick math to figure out which one is 'higher' and use that value. 

```
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] JUSTTHEDIGITS [041]
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] final justthedigits [041]
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] cchk = preacher
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] modwatchcomic = preacher
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] subname = preacher 041
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] SeriesYear: 1995
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] IssueTotal: 66
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] Comic Volume: None
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] volume detected: None
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] 0 Bracket Word: Preacher 041/12
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] 1 Bracket Word: 1998/4
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] year detected: 1998
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] 1998 is within the series range of 1995-2000
13-Aug-2015 21:06:15 - DEBUG   :: Thread-12 : [FILECHECKER] Matched on year, not on version - continuing.
```

Got it working for Preacher, so it should be working for the rest (hoping it won't stop working for others, but it's kind of hard to tell on a limited test basis). I'll push this out in the next little bit since it could impact alot of people trying to do manual post-processing on older series.

Thanks for the bug report (I wouldn't have found it on my own most likely),

**Comment by redfro** [comment]
[POST-PROCESSING] Manual post-processing completed for 121 issues.

Outstanding!!!

Thanks for everything you do, Mylar is such a great program!

**Comment by evilhero** [comment]
Thanks for the report back and the kudos ! 

Will close this now, since it's resolved :)
