### ISSUE TITLE
BUG - Series not reporting as wanted or watched in Weekly Pull list

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1111]
There are many comics that are listed in my weekly pull list with a status of skipped and I have the option to +Add Series but then I click the +add Series, at the next screen it will tell me Already in library.

![image](https://cloud.githubusercontent.com/assets/11575103/9364733/ac5a65d6-4662-11e5-9e85-b9068902064e.png)

![image](https://cloud.githubusercontent.com/assets/11575103/9364741/b83e6938-4662-11e5-955e-f767b16c9a8d.png)

**Comment by evilhero** [comment]
I can see what's happening, it's because CV lists it as having 0 issues instead of the actual 1 so Mylar is getting confused in the logic. I'll look into this and see exactly what's going on.

**Comment by blindguy** [comment]
As always, appreciate all your hard work on Mylar.

Having the same problems with 1872 and that is listed as having 2 in some places and 1 in others. 

![image](https://cloud.githubusercontent.com/assets/11575103/9365001/f56c0404-4663-11e5-9f32-3f4923f6c087.png)

![image](https://cloud.githubusercontent.com/assets/11575103/9365013/077bb7ac-4664-11e5-8b56-a5c4b4a9bc3a.png)
