### ISSUE TITLE
Enhancement request - Please proper case items on the Weekly Pull list

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1113]
All the comic titles in the weekly pull list are caps.  Can they be proper case? 

![image](https://cloud.githubusercontent.com/assets/11575103/9364892/7128e4b4-4663-11e5-8637-a4417e071b68.png)

**Comment by evilhero** [comment]
It's like that from the website that mylar pulls down from unfortunately - there's no way to proper case it as Mylar would only be able to capitalize the first letter of each word. It has no bearing on the actual searches or anything, but yeah it's not exactly pleasing to the eye with the capital letters I'll agree.

**Comment by blindguy** [comment]
Thanks for the info.
