### ISSUE TITLE
Cannot send files to NZBGet

### ISSUE THREAD

**Issue by Spence1115** [evilhero/mylar#1115]
When Mylar finds a comic and tries to send it to NZBGet, I get the following uncaught exception, and nothing appears in NZBGet

---
Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1303, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 242, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1365, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1956, in searcher
send_to_nzbget = server.append(nzbpath, str(mylar.NZBGET_CATEGORY), int(nzbgetpriority), True, nzbcontent64)
File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1240, in __call__
return self.__send(self.__name, args)
File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1599, in __request
verbose=self.__verbose
File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1280, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1308, in single_request
self.send_content(h, request_body)
File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1456, in send_content
connection.endheaders(request_body)
File "/usr/local/python/lib/python2.7/httplib.py", line 1049, in endheaders
self._send_output(message_body)
File "/usr/local/python/lib/python2.7/httplib.py", line 893, in _send_output
self.send(msg)
File "/usr/local/python/lib/python2.7/httplib.py", line 855, in send
self.connect()
File "/usr/local/python/lib/python2.7/httplib.py", line 832, in connect
self.timeout, self.source_address)
File "/usr/local/python/lib/python2.7/socket.py", line 557, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
error: [Errno 0] Error

---
Machine: Synology DS412+
NZBGet version: 15.0
Mylar version: Latest development build

**Comment by evilhero** [comment]
Problem is I don't use nzbget or really had much to do with that portion of code.

What values do you have for the nzbget host / port etc within mylar? 

The error itself has something to do with not being able to write the nzb file to the temp directory or something along those lines (just a guess).

Does your cache directory have proper permissions for the user running mylar?

**Comment by Spence1115** [comment]
Host: http://localhost
Port: 6789 (default and correct)
Username and password are correct, but not the default ones everyone seems
to use.

As far as I'm aware, yeah should be fine. The 'mylar' user has the same
permissions as all the rest and they (headphones etc) have no issue. Where
in the code is the bit that talks to NZBget so I can have a look?

On 23 August 2015 at 23:32, evilhero <notifications@github.com> wrote:

> Problem is I don't use nzbget or really had much to do with that portion
> of code.
>
> What values do you have for the nzbget host / port etc within mylar?
>
> The error itself has something to do with not being able to write the nzb
> file to the temp directory or something along those lines (just a guess).
>
> Does your cache directory have proper permissions for the user running
> mylar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/1115#issuecomment-133948714>.
>



-- 
*Richard Spenceley*
<https://twitter.com/spence1115> [image:
http://uk.linkedin.com/in/richardspenceley/]
<http://uk.linkedin.com/in/richardspenceley/>

**Comment by evilhero** [comment]
Try changing the localhost entry to 0.0.0.0

Remember to restart mylar after the change so the settings take effect and see if that helps at all.

**Comment by Spence1115** [comment]
Setting it to http://0.0.0.0 worked, strangely enough. Weird, as your
default value is http://localhost, and that works fine on headphones.

On 24 August 2015 at 00:03, evilhero <notifications@github.com> wrote:

> Try changing the localhost entry to 0.0.0.0
>
> Remember to restart mylar after the change so the settings take effect and
> see if that helps at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/1115#issuecomment-133954434>.
>



-- 
*Richard Spenceley*
<https://twitter.com/spence1115> [image:
http://uk.linkedin.com/in/richardspenceley/]
<http://uk.linkedin.com/in/richardspenceley/>

**Comment by evilhero** [comment]
Some systems don't have the localhost value setup properly for whatever reason, although by default it should be anyways. 

Localhost allows access to mylar only on the local interface.

0.0.0.0 allows access to mylar on any interface on the local machine.

**Comment by Spence1115** [comment]
Just seems odd since they're all on the same system. Oh well, this works,
so thanks!

On 24 August 2015 at 01:25, evilhero <notifications@github.com> wrote:

> Some systems don't have the localhost value setup properly for whatever
> reason, although by default it should be anyways.
>
> Localhost allows access to mylar only on the local interface.
>
> 0.0.0.0 allows access to mylar on any interface on the local machine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/1115#issuecomment-133972103>.
>



-- 
*Richard Spenceley*
<https://twitter.com/spence1115> [image:
http://uk.linkedin.com/in/richardspenceley/]
<http://uk.linkedin.com/in/richardspenceley/>
