### ISSUE TITLE
Found a comic that doesn't appear to be downloading

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1119]
"Where Monsters Dwell"

**Comment by evilhero** [comment]
Grabbed fine for me off of 32p the other day. 

Make sure you have a volume label set within the series detail page since it's being posted as 'vol2' (I have mine set to v2), and there's no volume information available for mylar to pull from - so it has to be manually entered.

**Comment by AtariBaby** [comment]
do I put that in "version number?"

**Comment by AtariBaby** [comment]
That was the trick. Thanks. Will try to remember.
