### ISSUE TITLE
OMGWTFNZBs API call format

### ISSUE THREAD

**Issue by DaveBrackets** [evilhero/mylar#1122]
As I mentioned in another issue, I'm getting 404 errors on the search urls for my newznab provider OMGWTFNZBs. Looking at the log, the search url that's being generated doesn't seem to me to match the format they specify in their documentation:

https://api.omgwtfnzbs.org/xml/?search={some search term}&user={username}&api={apikey}

You asked also for a download url format - here's the sample output from the API doc, which I think contains it (note I've added a space after every "<" because I couldn't figure out how else to make sure it all showed up!):

< xml version="1.0" encoding="ISO-8859-1">

< info>
< results>100< /results>
< pages>2< /pages>
< current_page>1< /current_page>
< published>server time request was published</published
< /info>

< search_req>

< post>
< release>Some.FLAC.Release.Name-INFO< /release>
< group>alt.binaries.sounds.flac< /group>
< sizebytes>286396335< /sizebytes>
< usenetage>1338679302< /usenetage>
< categoryid>22< /categoryid>
< cattext>music.flac< /cattext>
< language>0< /language>
< imglink>https://if-added.jpg< /imglink>
< weblink>http://weblink.net< /weblink>
< details>https://omgwtfnzbs.org/details.php?id={nzbid}< /details>
< getnfo>https://api.omgwtfnzbs.org/nfo/?id={nzbid}&user={username}&api={apikey}< /getnfo>
< getnzb>https://api.omgwtfnzbs.org/sn.php?id={nzbid}&user={username}&api={apikey}< /getnzb>
< /post>

< /search_req>
< /xml>

That's all for the XML API, which I think is what you want, but let me know if you want JSON, NFO or Direct Download.

**Comment by evilhero** [comment]
Haven't forgotten about this - will be in the next development commit which will hopefully work (have no way to test the xml returned aside from what you provided, so going off of that).

**Comment by rupaschomaker** [comment]
If there are issues I can issue a pull request to fix any low hanging
problems.

**Comment by DaveBrackets** [comment]
Got this update tonight and just tried a search - threw an error. From the log:

Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\search.py", line 1501, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "C:\Mylar\mylar\search.py", line 246, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Mylar\mylar\search.py", line 525, in NZB_SEARCH
findurl = findurl + "&apikey=" + str(apikey)
UnboundLocalError: local variable 'findurl' referenced before assignment

**Comment by evilhero** [comment]
Looks like you have an empty newznab provider within your configuration. 

 If it was a problem with omgwtfnzbs url (at least at that stage in the logs) the line would be indicating 'api', and not 'apikey'.

**Comment by DaveBrackets** [comment]
Yep, I deleted OMG from the "Use Newznab" section but didn't untick "use Newznab". Duh.

...still getting the same error though. Checked my config.ini and there's no Newznab provider in there. The line before in the logs is that it's looking "using omg".

**Comment by evilhero** [comment]
Lol its all good - I know there's gonna be problems with this as I have no way to test against the xml (cause I didn't have any xml responses).

The error is probably happening because the provider_order line needs to be reset. With mylar not running,  edit the config.ini and delete the entire provider_order line. Save it and then start up mylar and it should be gone (mylar only generates the order on startup so if you make provider changes and don't restart mylar they won't take effect properly in most cases).

What would help is of you could load up the rss feed for comics in your browser and save the resulting response (it will be in xml). Then copy me that file (with your api keys edited out) and then I could test against valid xml to make sure the structure is being polled against properly. You don't have to copy the entire file actually, just 1/2 complete entries would be good enough ;)

**Comment by DaveBrackets** [comment]
The provider_order thing worked. Baffling (and thanks!).

This is the xml of the first two entries from a search using the search url format I set out above on the term "guardians":

< xml version="1.0" encoding="ISO-8859-1">
< info>
< results>176</results>
< pages>1</pages>
< current_page>1</current_page>
< published>Wed, 16 Sep 2015 22:30:07 +0100</published>
< /info>
< search_req>
< post>
< nzbid>kayFb</nzbid>
< release>
Guardians.of.the.Galaxy.S01E01.Road.to.Knowhere.1080p.WEB-DL.DD5.1.AAC2.0.H.264-YFN
< /release>
< group>alt.binaries.hdtv.x264</group>
< sizebytes>1093813689</sizebytes>
< usenetage>1441605776</usenetage>
< categoryid>20</categoryid>
< cattext>tv.hd</cattext>
< language>0</language>
< details>https://omgwtfnzbs.org/details?id=kayFb</details>
< getnzb>
https://api.omgwtfnzbs.org/nzb/?id=kayFb&user=XXXX&api=XXXX
< /getnzb>
< /post>
< post>
< nzbid>8HFRY</nzbid>
< release>
Guardians.of.the.Galaxy.S01E01.Road.to.Knowhere.720p.WEB-DL.DD5.1.AAC2.0.H.264-YFN
< /release>
< group>alt.binaries.hdtv.x264</group>
< sizebytes>951334066</sizebytes>
< usenetage>1441604660</usenetage>
< categoryid>20</categoryid>
< cattext>tv.hd</cattext>
< language>0</language>
< details>https://omgwtfnzbs.org/details?id=8HFRY</details>
< getnzb>
https://api.omgwtfnzbs.org/nzb/?id=8HFRY&user=XXXX&api=XXXX
< /getnzb>
< /post>

(I manually entered a space after each <, and censored my username and API key...)

**Comment by evilhero** [comment]
That's awesome - that will help immensely when I run it through what mylar is trying to do.

One thing, do you know what category comics is on the site ( categoryid I'm guessing ). The results you posted were for 2 tv shows so it wasn't comics, although the schematic should be the same, just missing the category for comics ;)

Thanks!

**Comment by DaveBrackets** [comment]
Comics appear to go in the ebooks category, which is 9.

The addition to the URL seems to be &catid=9, would that make sense? Here's the results from the same search as before, with that added in (I tried adding it in a couple of different places in the URL, doesn't make a difference):

< xml version="1.0" encoding="ISO-8859-1">
< info>
< results>1</results>
< pages>1</pages>
< current_page>1</current_page>
< published>Wed, 16 Sep 2015 23:10:51 +0100</published>
< /info>
< search_req>
< post>
< nzbid>1etAj</nzbid>
< release>
100th.Anniversary.Special.Guardians.of.the.Galaxy.No.1.Sep.2014.SCAN.Comic.eBook-iNTENSiTY
< /release>
< group>alt.binaries.inner-sanctum</group>
< sizebytes>39335715</sizebytes>
< usenetage>1409051295</usenetage>
< categoryid>9</categoryid>
< cattext>other.ebook</cattext>
< language>0</language>
< details>https://omgwtfnzbs.org/details?id=1etAj</details>
< getnfo>
https://api.omgwtfnzbs.org/nfo/?id=1etAj&user=XXXX&api=XXXX
< /getnfo>
< getnzb>
https://api.omgwtfnzbs.org/nzb/?id=1etAj&user=XXXX&api=XXXX
< /getnzb>
< /post>
< /search_req>
< /xml>

**Comment by evilhero** [comment]
Ugh - I just noticed this, omgwtfnzbs doesn't index any of the comics group. They index just books, and files that are in pdf format which Mylar doesn't recognize even when searching / file-checking.

Might have to try and garner some support in order to get them to index the a.b.dcp groups so that Mylar will work properly (right now, it's not going to even if the back-end code of mylar was working properly with omg)

**Comment by DaveBrackets** [comment]
I'll try to find whether that site has a process to go through to ask for groups to be added.

I have definitely found cbrs on there by manual search previously, but I guess what you're saying is that they're randoms in groups that Mylar can't pull from?

P.S. Sorry, I'm an idiot - meant to close the other issue.

**Comment by evilhero** [comment]
There are a few cbrs on there, but only due to someone uploading the nzbs to the indexer itself. 

They don't index a.b.comics.dcp and ab.comics.dcp.repost which are thr two main ones. I popped on their irc yesterday to ask about if they would consider indexing said groups, but I had to leave after about 30 mins without a response.

I think if you want them to index those groups then you might have to get a bunch of people to +1 the idea so there's support in numbers (just guessing,  I have never spoken to the admins there).

**Comment by DaveBrackets** [comment]
Had a look at the group index today - at the top it says:

"This page lists all binary groups currently in our database.
Please note we are a user indexed site, meaning for a group to be added to this page all you need do is submit a .nzb file #here".

The way I read that is that if I uploaded something hosted in one of those groups it would just add the group to the list for that one file, rather than adding the entire group to the index. Agree?

**Comment by evilhero** [comment]
Yep that's pretty much my understanding - it's just a one-off basically that says that it has indexed x items from a given group. You can see under the a.b.comics.dcp group that there are only like 45 indexed and the last one was indexed 146 days ago.

I'm pretty sure we'd have to request the group to be added somehow...
