### ISSUE TITLE
Not finding Torrents

### ISSUE THREAD

**Issue by gamergeekv2** [evilhero/mylar#1123]
I'm having an issue where Mylar is not finding anything on Kickass.to even though I am a able to find them is I search the site manually.

**Comment by evilhero** [comment]
I noticed this myself the other day,  but haven't had a chance to look into it further - other than the fact if you do a non-rss search (force search, or manually marking an issue as Wanted) it will find results. 

So it's something to do with the rss not working properly again, as I thought I had fixed this problem in the last commit.

**Comment by gamergeekv2** [comment]
It's not even working when I do a force or manual search. It's searching in the logs but just not finding anything.

**Comment by evilhero** [comment]
Are you using a proxy for kat within mylar? 

Accidentally close the issue?

**Comment by gamergeekv2** [comment]
No proxy. And yeah, I have no idea why it closed.

**Comment by evilhero** [comment]
Hmm, it looks like the # of seeders is being messed up on there end (it's not updating when the rss snatches) - so it always remains at 0. If you're like me (and probably alot of others), my value for minimum number of seeders in Mylar is set to 1. Looking at the xml there's a new field now labelled as 'Verified' which I'm assuming is the initial uploader - I'll see if I can whip something up. 

In the meantime, can you try setting your minimum number of seeders to 0, save and restart Mylar and then try a Force RSS again to see if anything helps ?
