### ISSUE TITLE
Error when looking for wanted issues

### ISSUE THREAD

**Issue by Herjar** [evilhero/mylar#1125]
On some issues I get an error when it looks for wanted issues. It then stops looking it seems, so all issues after the one that fails never get searched for. Here is an example log for log for Spawn 251:

04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : checking search result: Spawn vol0 #251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Size of file cannot be retrieved. Ignoring size-comparison and continuing.
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Year has been fuzzied for this series, ignoring store date comparison entirely.
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Entry: Spawn vol0 #251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Cleantitle: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : volume detected - stripping and re-analzying for volume label.
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Cleantitle: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : 0. Bracket Word: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Comic: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : UseFuzzy is  : 1
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : ComVersChk : 0
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : Year not given properly formatted but Version detected.Bypassing Year Match.
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : original nzb comic and issue: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : adjusted nzb comic and issue: spawn vol0 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : adjusting from: spawn vol0 251 to: 251
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : ['spawn', 'vol0', '251'] nzb series word count: 2
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : ['spawn'] watchlist word count: 1
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : volume detection commencing - adjusting length.
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : watch comicversion is None
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : version found: 0
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : vers4year: no
04-Sep-2015 19:13:40 - DEBUG   :: Thread-13 : vers4vol: 0
04-Sep-2015 19:13:40 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/media/a6a3/home/herjar/.mylar/mylar/logger.py", line 159, in new_run
    old_run(_args, *_kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 1488, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 220, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 1177, in NZB_SEARCH
    if postdate_int >= issuedate_int and nzbprov == '32P':
UnboundLocalError: local variable 'postdate_int' referenced before assignment

04-Sep-2015 19:13:57 - DEBUG   :: RSSCHECK : Starting new thread: RSSCHECK
04-Sep-2015 19:13:57 - INFO    :: RSSCHECK : delaying startup thread for 30 seconds to avoid locks.

**Comment by evilhero** [comment]
It looks like it's due to the year being fuzzied for a particular series (I'm assuming it's Spawn). 

It's a bug as it's trying to compare the dates posted and published to see if it's the correct issue, but the calculations for posting date occur when the year isn't being fuzzied. 

I'll have to look into this as it's more than one line of code change most likely,  but in the meantime you could try to remove the fuzzy year for the series and try again - it should work (I'm pretty sure)?

**Comment by Herjar** [comment]
I just changed the wanted Spawn and Judge Dredd issues to ignored and the rest of my downloads went fine.
