### ISSUE TITLE
An idea to assist with KAT's torrent issues as of late

### ISSUE THREAD

**Issue by scooterpsu** [evilhero/mylar#1126]
Does the rss caching save magnet links? If so, could something like this be integrated as an alternative download method?

https://gist.github.com/sbisbee/8215353

Since magnet links in the rss wouldn't need to go through torcache, they shouldn't 404.

I'm going to have a look at attempting to integrate it myself, but obviously you would probably have better luck.

**Comment by evilhero** [comment]
In theory, yes it would get around it but I think it would need direct access to the torrent client itself in order to load the magnet link - I've looked at ways to convert magnet links to torrent files, but either they don't work or it just downloads the torrent from torcache.

Obviously this is a pretty big game changer for users of KAT, and it's affecting every other piece of automation software that hits torcache (it's not just mylar), which is probably the intent of the torcache admins to a certain extent. Looking at KAT forums it's pretty obvious that everyone is having problems accessing torcache so they're working on something to fix it, but no one has any idea.

I should have answered to, the rss doesn't save magnet links but it could very easily. It's just what to do with magnet link to get the torrent file, since mylar doesn't have direct access to the torrent clients.

**Comment by scooterpsu** [comment]
That bash method was super hacky, but tranmission has actual remote access capabilities via transmission-remote.

http://linux.die.net/man/1/transmission-remote

I switched over to the non-dev build so I could get broken torrent files, and use a bash script to look for that filename in the KAT rss, grab the matching magnet link, and send that to transmission-remote.

**Comment by evilhero** [comment]
Forgot to document this in the most recent commits - the fix is in both the development and master branches now. Was as simple as changing the referrer that it was pointing to ;)

At some point, will definitely have to figure out the magnet links - I'd be interested in seeing that transmission mock-up you did to get the magnet links. Obviously not fond of having a bash script instead of a python script/module, but I'm also aware of all the problems associated with the magnet conversions and if it's direct sending to the client - that's a bigger plus ;)

**Comment by scooterpsu** [comment]
I guess it's just that I'm on a docker image that's using an older build then... whatever it is, I'm taking advantage for now. :)

Here's my latest version of the script. It's actually passing the command to a Transmission docker image.

https://gist.github.com/scooterpsu/74cba89746e96335c12e#file-comicmonitor

**Comment by scooterpsu** [comment]
I just noticed what you said about the most recent commits (totally missed that you just pushed one). That just leaves me with the same issue I /was/ having with the dev branch, 404'ing in the logs, vs the torrent files with 404's in them (improvement?). I forked before this commit, so I'll probably roll back to that and use my script.

**Comment by evilhero** [comment]
It's 404'ing on the most recent development commit? Oh wait, you're using a proxy aren't you?

**Comment by scooterpsu** [comment]
Nope, no proxy here.

This is what the logs show when it tries to download a torrent. 

2015-09-11 13:55:08	ERROR	Unable to send torrent - check logs and settings.
2015-09-11 13:55:08	WARNING	Unable to download torrent from KAT [Status Code returned: 404]

I only use the katproxy page for the rss download in the script because it seems to work better with curl than kat direct.

**Comment by evilhero** [comment]
Ok, so 404 means it can't find the url on torcache. Can you verify that the torrent exists,  or try to grab another issue? It's not unheard of for some torrents to not get on the cache due to problems, but maybe try a different issue and see if that works.

**Comment by scooterpsu** [comment]
This happens with every issue (Injustice: Gods Among Us - Year Four), which I only added to Mylar because I saw the most recent issue towards the top of the kat comic page. 

With the older build, it had enough data to try and grab every issue, but gave me the invalid torrents with 404's in them.

**Comment by evilhero** [comment]
I can't duplicate this - even using the same series:
```
11-Sep-2015 14:40:54 - INFO    :: Thread-12 : Found Injustice: Gods Among Us Year Four (2015) issue: 3 using KAT [RSS]
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : link given by: KAT
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : sending .torrent to watchdir.
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : ComicName:Injustice: Gods Among Us Year Four
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : link:13B6BBDA2526F390DE8959BF3861AE8AC09197BE
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : Torrent Provider:KAT
11-Sep-2015 14:40:54 - INFO    :: Thread-12 : matched on Injustice: Gods Among Us Year Four
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : filename for torrent set to : /home/hero/mylar/cache/Injustice_Gods_Among_Us_Year_Four_3_2015.torrent
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : Grabbing torrent from url:http://torcache.net/torrent/13B6BBDA2526F390DE8959BF3861AE8AC09197BE.torrent
11-Sep-2015 14:40:54 - DEBUG   :: Thread-12 : [KAT] Saved torrent file to : /home/mylar/cache/Injustice_Gods_Among_Us_Year_Four_3_2015.torrent
11-Sep-2015 14:40:56 - DEBUG   :: Thread-12 : Sending file: Injustice_Gods_Among_Us_Year_Four_3_2015.torrent
11-Sep-2015 14:40:58 - DEBUG   :: Thread-12 : Upload complete to seedbox.
```

If you check your mylar.log file, it will indicate that it's 'Grabbing torrent from url:' with the url to torcache.

**Comment by scooterpsu** [comment]
Ok, so it turns out I have a completely different problem. My apologies, I've been looking at the /logs page and missing the details in the log file.

Running the newest commit, my log finds the file but can't download it.

```
11-Sep-2015 15:30:16 - DEBUG   :: Thread-13 : Torrent Provider:KAT
11-Sep-2015 15:30:16 - INFO    :: Thread-13 : matched on Injustice: Gods Among Us Year Four
11-Sep-2015 15:30:16 - DEBUG   :: Thread-13 : filename for torrent set to : /torrents/Injustice_Gods_Among_Us_Year_Four_19_2015.torrent
11-Sep-2015 15:30:16 - DEBUG   :: Thread-13 : Grabbing torrent from url:http://torcache.net/torrent/F3DEFFA326D4A9055D372CF8898267B5A30E0213.torrent?title=[kat.cr]injustice.gods.among.us.year.four.019.2015.digital.son.of.ultron.empire.cbr.nem
11-Sep-2015 15:30:16 - WARNING :: Thread-13 : Unable to download torrent from KAT [Status Code returned: 404]
11-Sep-2015 15:30:16 - ERROR   :: Thread-13 : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
```

The link works fine if I click it manually. So now I'm stumped. Does it need a longer timeout set somewhere?

**Comment by evilhero** [comment]
Can you confirm the branch and commit you're running? There's 2 places to confirm the commit - the bottom of every page, and on the 1st tab of the configuration page, the branch can be checked on the configuration tab as well.

**Comment by evilhero** [comment]
Does the user running mylar (or the docker even I suppose) have complete access to the cache directory of mylar? Mylar writes the torrent file to the cache directory first, and then moves it accordingly.

**Comment by scooterpsu** [comment]
Version: dfd1ac1b92469268dd2059ef7966b4ac74409890 shows at the bottom, so that's the latest commit right?

And I just specifically checked the cache folder's permissions (freshly set to 777), and when I added Injustice and a couple others to test, it successfully saved the cover images and the newreleases text files in there.

**Comment by evilhero** [comment]
Can I ask what version of python you're currently running mylar against? 

I'm guessing that it's not even writing any torrent files to your cache directory?

**Comment by scooterpsu** [comment]
Python ver: 2.7.6... is that the issue? 

And it doesn't seem to be getting that far, no.

**Comment by evilhero** [comment]
Well normally it would be the python version as 2.7.6 doesn't support SNI certificates so when it goes to verify the ssl connection it fails. 

But the torcache site is non-ssl (unless the referrer it set to https which would show up in the log).

At this point given how much troubleshooting you've gone through I would suspect that the version of python might be a factor.  Is it easy for you to upgrade or use a 3rd party app like pyenv (don't go less than 2.7.9 if you can).

**Comment by scooterpsu** [comment]
So wouldn't ya know it, updated to 2.7.9 and everything went smooth. The biggest issue I had was figuring out how to permanently update my docker image to 2.7.9... 

Sorry, it was totally a pebkac issue. :)
