### ISSUE TITLE
Iron Man 20.INH (2013)

### ISSUE THREAD

**Issue by solidus0079** [evilhero/mylar#1128]
For whatever reason, they decided to number an issue of Iron Man (2013) as 20.INH.  I have that issue as a .CBZ, and Mylar is struggling to recognize it.  It's always coming up as Archived and I can't get that to go away.

The file name is "Iron Man #20.INH (March, 2014).cbz"

I have tried renaming it as other variations of this, but it's a no-go.  I think Mylar can't understand the 20.INH part, since it's not a decimal number?

Here's a link to the Comicvine entry for it, if you need more information.  :)

http://www.comicvine.com/iron-man-20-inh/4000-442923/

Edit:  I should also add there's a normal #20 which is a separate book altogether.

**Comment by evilhero** [comment]
Weird,  this was working fine previously - the INH titles did cause problems initially but that was all resolved a while ago. Which means it's cause of a recent push and I think I know the one - I'll check into this today probably and see what's happening.

Just to confirm - are you on the most recent development or master branch?

**Comment by weidercs** [comment]
Duplicate of 1092 I logged back in July, I'm on the Dev branch and can confirm it hasn't worked for quite a while. (it's my only incomplete series and bugs me every time I look at the list :), OCD problems)

**Comment by evilhero** [comment]
Was thus occuring for searching still, or was it just for file checking? 

I just looked and some of the code changed over iterations (obviously lol), which caused some irregular parsing.  I have it fixed in my local repo now so it will be in the next development commit (checked and working specifically against said issue in this thread)

**Comment by weidercs** [comment]
searching and file check

**Comment by evilhero** [comment]
Just an update: 
Both searching and filechecking fixed and working (at least from tests with filenames in the '020.INH', '020 INH', '020INH' formatting) - will be in the next development commit.
