### ISSUE TITLE
Pushover notifications not working, likely due to SSL changes

### ISSUE THREAD

**Issue by wyldphyre** [evilhero/mylar#1130]
Pushover has just made changes to start using SHA256 for their SSL. See http://updates.pushover.net/post/126918128857/api-upcoming-upgrade-to-sha256-ssl-certificate.

Because of this I went and tested the notifications via the test button in the settings, and the notifications don't seem to work anymore. I'm guessing that however Mylar is doing it's integration, it may need updating to work now.

**Comment by evilhero** [comment]
Yeah, I kinda figured this one was coming soon. I had converted a few of the nofications to use the requests library (NMA and pushbullet), so I'll have to look at doing the same for Pushover. 

I'll try and get this in for the next development commit.

**Comment by baz1860** [comment]
This is weird; I've been receiving notifications via Pushover today,
presumably using the newly minted and operational SHA-256.

**Comment by evilhero** [comment]
I can't test it as I don't have Pushover access - but I'm wondering if it's a python version issue (meaning that maybe the OP was at a level < 2.7.9)

**Comment by wyldphyre** [comment]
Ok. Clarification. I got some notifications this morning, so it seems like it's actually the Test button that isn't working :).

Tried to send test messages again and the tests still aren't working.

**Comment by evilhero** [comment]
Yep, test button was muffled all up. Rejigged things, threw PushOver to use the requests module so it's all up-to-date and test button working too. 

Will be in next development commit ;)

**Comment by wyldphyre** [comment]
Cool. I'll give it a whirl when it's released.

**Comment by wyldphyre** [comment]
Confirmed fixed in the recent development release
