### ISSUE TITLE
Manual Post-Processing Failure

### ISSUE THREAD

**Issue by misleadingrhino** [evilhero/mylar#1132]
Thanks so much for this amazing software. 

I get the below error when I try to do Manual Post-Processing

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/PostProcessor.py", line 305, in Process
watchmatch = filechecker.listFiles(self.nzb_folder, cs['ComicName'], cs['ComicPublisher'], cs['AlternateSearch'], manual=cs['WatchValues'])
File "/opt/Mylar/mylar/filechecker.py", line 1083, in listFiles
newc += split_sub[i] + ' '
IndexError: list index out of range

It happens as soon as I click the button. 

Mylar Version: development
-- git build caa8654b4a5256d8e1fc8de5f9695d5d148575e5.
Python Version : 2.7.10

MYLAR PROGRAM OPTIONS
Mylar Data Directory : /opt/Mylar
Mylar Program Directory : /opt/Mylar
Mylar Cache Directory : /opt/Mylar/cache
Mylar Config File :/opt/Mylar/config.ini

Thanks in advance!

**Comment by evilhero** [comment]
I'd need to see the mylar.log file itself (not the GUI log as that's only informational) leading up to the error. It's having a problem parsing one of the filenames - the log file will indicate which file and exactly where it's coughing up.

**Comment by misleadingrhino** [comment]
Well, apparently I'm impatient and accidentally renamed it myself without knowing which one it was so now it's working. Sorry for bothering you!
