### ISSUE TITLE
Mylar has stopped finding NZBs

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1136]
Last week, mylar seemed to have simply stopped finding the NZBs (I'm using NZB.SU) for new issues.  If I put in an older comic, like Catwoman, it seems to work fine and downloads everything.  But the comics I have been reading seem to never get found (except for Batgirl and Nameless, for some reason).

Anyhow, I manually prompted it to search for a comic that I know is out there:
The Manhattan Projects: The Sun Beyond the Stars 003
Below are the results

30-Sep-2015 17:06:20 - INFO :: Thread-13 : Initiating manual search for The Manhattan Projects: The Sun Beyond the Stars issue: 3
30-Sep-2015 17:06:20 - INFO :: Thread-13 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : The Manhattan Projects The Sun Beyond the Stars
30-Sep-2015 17:06:20 - INFO :: Thread-13 : Issue Title given as : None
30-Sep-2015 17:06:20 - INFO :: Thread-13 : search provider order is ['nzb.su']
30-Sep-2015 17:06:20 - INFO :: Thread-13 : Shhh be very quiet...I'm looking for The Manhattan Projects: The Sun Beyond the Stars issue: 3 (2015) using nzb.su
30-Sep-2015 17:06:20 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:07:21 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:08:21 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:09:21 - INFO :: Thread-13 : Alternate Search pattern detected...re-adjusting to : The Manhattan Projects The Sun Beyond the Stars 2015
30-Sep-2015 17:09:21 - INFO :: Thread-13 : Shhh be very quiet...I'm looking for The Manhattan Projects The Sun Beyond the Stars issue: 3 (2015) using nzb.su
30-Sep-2015 17:09:21 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:10:22 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:11:22 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
30-Sep-2015 17:12:23 - INFO :: Thread-13 : Could not find Issue 3 of The Manhattan Projects: The Sun Beyond the Stars(2015) using nzb.su [api]

**Comment by evilhero** [comment]
I think it's the ':' that's causing the problem - mylar attempts to safe search it by removing the character but then it's placed in a search result with a - that usually denotes an issue title or the like. 

Have you tried to set the Alternate Search Name to 'The Manhattan Projects -The Sun Beyond the Stars'?

**Comment by thewindupboy** [comment]
Should I include the year?  Using Captain Marvel & The Carol Corps (2015), should use:
Captain Marvel and The Carol Corps (2015)

**Comment by thewindupboy** [comment]
Attached is a screenshot from NZB.SU showing the Captain Marvel And The Carol Corps files
![carol](https://cloud.githubusercontent.com/assets/12476776/10207894/57e14e14-679d-11e5-9645-e98c1e1e3759.png)

**Comment by thewindupboy** [comment]
And this is what I have in Alternate Search Names:
Captain Marvel and The Carol Corps

**Comment by evilhero** [comment]
That one's abit different. .the & and 'and are interchangeable within mylar so there's no need to create an alternate search name with the alternate &/and replaced.

The problem with that is that the category isn't in the Comics category. Mylar only searches the comics category for nzbsu in order to cut down on spam and unnecessary result sets. So the first two entries in that screens hot are in the wrong category so they would never get picked up by mylar currently.  If you have experimental search enabled you would possibly get the corect results from there ( just a guess)

**Comment by thewindupboy** [comment]
Thanks much!  Trying things now

**Comment by thewindupboy** [comment]
Seems to be working now, thanks!
