### ISSUE TITLE
BOY-1 not being recognized

### ISSUE THREAD

**Issue by goncalovalverde** [evilhero/mylar#1143]
The cbr files of series BOY-1 are not being recognized. Mylar snatches the torrent file ok, it's donwload but it doesnt move to the right directory.
Even when i move the file directly to the BOY-1 comic series directory and do a "recheck files" it doesn't recognize the files. I've also tried to rename the file to BOY-1_001_(2015).cbr and still nothing. Problaly there is a conflict with the name "BOY-1" and the issue numbering logic implemented in mylar

**Comment by evilhero** [comment]
For some reason mylar isn't properly detecting the series as having a numeric, so it assumes the '-1' portion is the actual issue number which also happens to be negative.

Will look into this more today (on phone atm), but definitely a verified bug.

**Comment by evilhero** [comment]
```
15-Oct-2015 13:53:24 - INFO :: Thread-12 : [FILE-RESCAN] Now checking files for BOY-1 (2015) in /mnt/mediavg/Comics/Comics-2/BOY-1-(2015)
15-Oct-2015 13:53:24 - INFO :: Thread-12 : [FILE-RESCAN] Now checking files for BOY-1 (2015) in : /Comics/Comics-1/BOY-1-(2015)
15-Oct-2015 13:53:24 - INFO :: Thread-12 : [FILE-RESCAN] Updated the status of 2 issues for BOY-1 (2015) that were not found.
15-Oct-2015 13:53:24 - INFO :: Thread-12 : [FILE-RESCAN] Total files located: 1
15-Oct-2015 13:53:24 - INFO :: Thread-12 : [FILE-RESCAN] I have physically found 1 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 1 / 3 ]
```
issue was named : BOY-1_001_(2015).cbz as shown below:
![boy-1](https://cloud.githubusercontent.com/assets/909424/10522704/8f56e2fc-7344-11e5-90a8-77642b9f83a6.png)

Will be in next development commit.
