### ISSUE TITLE
selecting all - error

### ISSUE THREAD

**Issue by sstretchh** [evilhero/mylar#1145]
When I add new comics and i click the box at the top to select all comics. The bottom right comes up and says error. some times its selects them all, some times its random on the wants that get marked wanted and the rest have to be manually selected wanted.

**Comment by evilhero** [comment]
What branch / commit are you running of mylar? 

What screen are you on when you try the select all? Are you meaning issues or series?

**Comment by sstretchh** [comment]
Not sure on the branch, what is ever on the main page.

any time I search to add a new comic, doesn't matter the comic. Once the ComicDetails load, I click the box that selects all comics, then select the action that makes them wanted. When i hit Wanted, there is a red error in the bottom right that pops up only a random amount of comics are marked random. 

I have to go and select all the comics manually then hit wanted

**Comment by evilhero** [comment]
I was going to say that I think it might be taking the 'select all' checkbox as a valid response and mistakingly trying to change its status.

This might be a problem with the data tables themselves, but I'll look into it and see if I can figure out what's happening. 

What browser are you using out of curiosity?

**Comment by sstretchh** [comment]
nothing happens when i selected all, once I hit the drop down  to change marked item's to wanted is when it randomly only marks a few wanted and the rest are left to skipped

I did discover after posting this the change all skipped to wanted works like a champ !

**Comment by evilhero** [comment]
Yeah I figured this out. It was also including the annuals table when doing a select all, which throws errors. I've put in a check to ignore the annuals table when selecting from the issues and it's working on my local repo. Will be in the next development commit.
