### ISSUE TITLE
Searching/Adding series returns "Errno 11001" "getAddrInfo failed"?

### ISSUE THREAD

**Issue by chazmodan** [evilhero/mylar#1147]
Hi folks,

As the title suggests, I'm running into an internal server error and the error message is the following in the browser:

![screen shot 2015-10-27 at 9 00 21 pm](https://cloud.githubusercontent.com/assets/15355025/10779429/db3e5e4a-7ced-11e5-9d85-672a2a64e87e.png)

Everything has been working fine for days on the same version and there's been no changes that I've noticed to the system. This error pops up basically anytime a search is performed. I've reinstalled Python 2.7.10 and the latest version (as of 10/27) of Mylar and it hasn't had any effect. Not sure what's up.

Running on git build 60140e8c900ae6c2acc3c9bf319506b6514fbed4

**Comment by ryanrbrinkman** [comment]
Also getting this error all of sudden (posted on web)

**Comment by evilhero** [comment]
They removed the url for comicvine that mylar was using to access. Fix up momentarily for both branches.

**Comment by chazmodan** [comment]
That does it, all working again. Thanks for fixing this so quick :+1:
