### ISSUE TITLE
Not importing comics from monitored folder or from a manual request

### ISSUE THREAD

**Issue by blackforestham** [evilhero/mylar#1149]
This is the error in the log.

ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/PostProcessor.py", line 305, in Process
watchmatch = filechecker.listFiles(self.nzb_folder, cs['ComicName'], cs['ComicPublisher'], cs['AlternateSearch'], manual=cs['WatchValues'])
File "/opt/mylar/mylar/filechecker.py", line 76, in listFiles
dirlist = traverse_directories(basedir)
File "/opt/mylar/mylar/filechecker.py", line 1214, in traverse_directories
for (dirname, subs, files) in os.walk(dir):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 286, in walk
if isdir(join(top, name)):
File "/usr/lib/python2.7/posixpath.py", line 73, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 31: ordinal not in range(128)

This only started happening since the last update.

**Comment by evilhero** [comment]
Probably doesn't have much to do with the last update (dev had nothing to do with that module,master yes, but still probably not likely).
The ascii error is indicating you have a filename with an invalid character in it witihn that directory - and Mylar can't interpret it properly.I'm currently trying to rework some of these errors, as they only tend to pop-up when people have the characters, but it's not 100% obviously.

Can you let me know what the filename is that causing the problem? The special character in question is : á

**Comment by blackforestham** [comment]
Ok.  So I made a directory labeled "to be imported", threw all the files in it and did a manual post-process request.  That worked.  I still cannot get it to import from my download directory (this was working fine up until a few days ago).  One of the files is "Avengers & X-Men - Axis 005 (2015) (Digital) (Zone-Empire).cbr".  When in the download folder (which is the monitored folder) nothing happens.  If I move it to another folder (in this case a "to be imported" folder) and do a manual post-process request it goes through.  

I don't see any special characters in any files or folders.

**Comment by evilhero** [comment]
Check the perms on your download directory to make sure that the user running mylar has full permissions. 

If switching directories makes it run properly then it's not the process itself but something in the given directory stopping the process, since both methods use the same underlying function.
