### ISSUE TITLE
SABnzbd warnings of key authentication

### ISSUE THREAD

**Issue by solidus0079** [evilhero/mylar#1151]
Whenever Mylar downloads something (and it appears to be downloading issues OK), it generates a Warning in SABnzbd of "u'400', u'There was an error parsing the key for validity'".  I have verified the SABnzbd API key is enabled and correct.  Any idea what's causing this?  This started recently, possibly after a Mylar update.  It's possible I am overlooking something obvious.  Any suggestions would be helpful. :)

**Comment by evilhero** [comment]
It looks like that's some sort of growl related error - do you have growl notifications enabled within sabnzbd?

**Comment by solidus0079** [comment]
That's exactly what it was!  Thank you!  Just for my future reference to prevent dumb questions, how did you know?

**Comment by evilhero** [comment]
Just some good ol' google - fu.   Almost every google result mentioned growl, which mylar doesn't use - but sabnzbd does ;)

**Comment by solidus0079** [comment]
Ah.  Sorry for the bother!
