### ISSUE TITLE
Unable to find anything through newznab search

### ISSUE THREAD

**Issue by potablepoison** [evilhero/mylar#1157]
I'm currently using nzbgeek while I wait for an invite to one of the other providers, but mylar almost never finds anything from it.  I can manually search on their site and find what I'm looking for, but mylar doesn't find it.  It does seem like the things mylar can find are the newer issues (with a few exceptions), is this a caching issue or something?

**Comment by evilhero** [comment]
Alot depends on the actual issues being searched for and how it is that your'e searching. 

If the filename isn't properly labelled (ie. it doesn't have a volume label or an issue year), then odds are Mylar won't grab it as it can't determine if it's the proper title it's looking for. There are some exceptions - if it's the only series by that name, it would forgo the volume/issue year check albeit there's always a chance that it's been mislabelled. Or if you fuzzy the year it would ignore the year check and just grab it regardless - which could also cause some mis-grabs as it's doing away with one of it's sanity checks. It could also be that the headers that are being posted to nzbgeek aren't being stripped properly and there's something in the header (which mylar parses from in some cases) of the nzb that's causing it to get confused. I'd have to see a search result from your mylar.log file to see exactly what's going on.

Are you letting mylar initiate the search every 6hrs (which does rss + api-backlog search), or are you just checking the rss check which only checks the last 50 or so items (dependent on the nzb provider) that have been updated on your provider? If you don't run mylar 24/7 - the 20 minute interval checks aren't going to poll anything relevant if you left it off for 6-8 hours (as then it will miss anything posted during that time frame), but the api-backlog search would be able to find it (which runs every 6hrs by default, or by doing a Force Search on the Wanted tab, or by initiating a manual search by clicking on the magnifying glass on the series detail page).
