### ISSUE TITLE
Cannot refresh series, instead deletes all issues

### ISSUE THREAD

**Issue by Herjar** [evilhero/mylar#1158]
When i try to manually refresh a series Mylar just deletes all issues and does not refresh anything. Here is the log:
14-Nov-2015 17:51:42 - DEBUG   :: CP Server Thread-9 : Refreshing comic: [u'78067']
14-Nov-2015 17:51:42 - INFO    :: Thread-12 : Starting update for 1 active comics
14-Nov-2015 17:51:42 - DEBUG   :: Thread-12 : Refreshing :78067
14-Nov-2015 17:51:42 - DEBUG   :: Thread-12 : CV_OneTimer option enabled...
14-Nov-2015 17:51:42 - DEBUG   :: Thread-12 : Gathering the status of all issues for the series.
14-Nov-2015 17:51:42 - DEBUG   :: Thread-12 : Checking how out of whack the series is.
14-Nov-2015 17:51:42 - DEBUG   :: Thread-12 : Deleting all issue data.
14-Nov-2015 17:51:43 - DEBUG   :: Thread-12 : Refreshing the series and pulling in new data using only CV.

This also happens automatically to some series with wrong "Have" from some other bug. So all my data is steadily disappearing.
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : [The Walking Dead] trying to locate issue 148 to do comparitive issue analysis for pull-list
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Returning Release Date for issue # 148 of 2015-11-11
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Now checking date comparison using an issue store date of 20151111
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Using a compare date (usedate) of 20151111
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Status of Snatched
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Store Date falls within acceptable range - series MATCH
14-Nov-2015 17:48:51 - DEBUG   :: WEEKLYCHECK : Watchlist hit for : The Walking Dead ISSUE: 148
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Refreshing :18166
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : CV_OneTimer option enabled...
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Gathering the status of all issues for the series.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Checking how out of whack the series is.
14-Nov-2015 17:48:52 - INFO    :: WEEKLYCHECK : Series is out of whack. Forcibly refreshing series to ensure everything is in order.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Forcibly maintaining status of : Snatched for #148 to ensure integrity.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Comic series has an incorrect total count. Forcily refreshing series to ensure data is current.
14-Nov-2015 17:48:52 - INFO    :: WEEKLYCHECK : Starting update for 1 active comics
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Refreshing :18166
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : CV_OneTimer option enabled...
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Gathering the status of all issues for the series.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Checking how out of whack the series is.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Deleting all issue data.
14-Nov-2015 17:48:52 - DEBUG   :: WEEKLYCHECK : Refreshing the series and pulling in new data using only CV.

**Comment by Herjar** [comment]
Forgot to mention that if I delete the series and add it again the issues show up fine.

**Comment by evilhero** [comment]
The log would indicate it might be having problems hitting comicvine to retrieve the issue data. If it can't hit it, the issues would appear to have no data available as it was trying to either refresh or wipe/refresh due to some previous retrieval problems.

If you share your cv api key in other apps at all (taggers, etc), you might have gone over the api limit enforced by cv. Trying again after a short delay might be enough to overcome the time restriction (normally it's 400/15 minutes unless that's changed recently - and it's quite possible as they have been trying to reel in their api alot lately it seem).

You can try running mylar in non-daemon mode from a command prompt and then try refreshing a series (or whatever you did to get the errors previously). It might be that the error is suppressed in the logging, but the console would trap the error.

**Comment by Herjar** [comment]
I only share the API key with the tagger in comicrack, but I have not used that lately so I should not hit the API limit. I tried the tagger right after mylar failed and I could retrieve issues fine in comicrack, so I don't think that is the issue.

I ran mylar in non-daemon mode, but that gives even less info:
17-Nov-2015 16:12:33 - INFO :: Thread-17 : Starting update for 1 active comics
17-Nov-2015 16:12:33 - WARNING :: Thread-17 : [DIRECTORY-CHECK] Could not find comic directory: /media/sdq1/home/herjar/comics/Tooth & Claw/ (2014)
17-Nov-2015 16:12:33 - INFO :: Thread-17 : [DIRECTORY-CHECK] Creating comic directory (0777) : /media/sdq1/home/herjar/comics/Tooth & Claw/ (2014)

Maybe something happened to my installation/.ini file? Maybe I'll try a reinstall when I have time.

**Comment by Herjar** [comment]
Ok some progress. If I try to update an existing comic it seems like it will always fail. However, if I delete the comic from Mylar and re-add it all the issues are retrieved fine, and if I do a refresh of the new series the update goes fine too without the issues disappearing. So newly added series work fine. 

Re-adding ~400 series is a chore though. Any idea what could cause this? Something happen to my database?

**Comment by Herjar** [comment]
I found the problem. I use Mylar on a seedbox and I changed to a new slot a few weeks back.
I moved everything over to the new slot and it seemed to be working fine, but I just realised the full path ComicLocation in the database is wrong because it is on a new harddrive.
So it used to be:
/media/sdq1/home/herjar/comics/
But now it is:
/media/a6a3/home/herjar/comics/

Did not notice that in the log before. I ran a query and changed all the locations and I can finally update my comics again :)

Maybe you should add some error to the log/cmd when it does not have permission/not possible to create a directory?

BTW is it possible to stop creating the folders? I found create_folder in config.ini and set that to 0, but the folders are still created. I never leave the comics on the seedbox long, so it just creates empty folders I need to delete every time the comic is refreshed. I just need to dump all comics in the comics folder.
