### ISSUE TITLE
Cannot refresh or add series, maybe CV api issue

### ISSUE THREAD

**Issue by ministoat** [evilhero/mylar#1159]
This has been an issue for a few days now, log shows this error: 
"2015-11-15 09:25:53	WARNING	Unable to retrieve URL for volume. This is usually due to a timeout to CV, or going over the API. Retrying again in 10s"

No series can be added or refreshed. Comicvine is up

**Comment by ministoat** [comment]
...and api key is correct!

**Comment by evilhero** [comment]
Can you reach cv from the machine running mylar via a webbrowser?  Can you reach the www.comicvine.com/api resource?

Do you share the api key used in mylar with other applications?just prior to that error it should have some indication of the number of api hits that mylar has tracked thus far - it can only track what mylar uses though, not any other app using the same api key.

**Comment by ministoat** [comment]
Problem fixed be signing up for a new api key - I guess the old one was blocked!

Mylar was the only app using it.

There's a lot of stuff about blocked api keys and CV changes and new api limits on the Comicrack and CV forums, so I'll see if this happens again.

**Comment by evilhero** [comment]
I have a CV api rate limit in place for mylar coming shortly - it's on my local repo and wanted to do some testing. It looks like while mylar might conform the new api rate limiting imposed by CV, comictagger doesn't and will hammer it.

I've modified my local comictagger and was able to apply the rate limit to it,  but it means I'll have to include the comictagger lib as part of mylar going forward.
