### ISSUE TITLE
Two errors, detecting branch, Uncaught exception error when post processing initializes

### ISSUE THREAD

**Issue by regulus0** [evilhero/mylar#1168]
First Error:

2015-11-25 10:44:10 INFO    Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2015-11-25 10:44:10 INFO    Populating Custom Exception listings into Mylar....
2015-11-25 10:44:10 INFO    Populating Base Exception listings into Mylar....
2015-11-25 10:44:10 INFO    Checking to see if the database has all tables....
2015-11-25 10:44:10 INFO    [DB Module] Loading : sqlite3 as the database module to use.
2015-11-25 10:44:10 INFO    Branch detected & set to : development
2015-11-25 10:44:10 WARNING No branch specified within config - will attempt to poll version from mylar
2015-11-25 10:44:10 INFO    Successfully discovered local IP and locking it in as : 192.168.1.5

Second error:

Uncaught exception: Traceback (most recent call last):
File "D:\ServerApps\Mylar\mylar-development\mylar\logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.**target(_self.__args, *_self.__kwargs)
File "D:\ServerApps\Mylar\mylar-development\mylar\PostProcessor.py", line 928, in Process
return self.Process_next(comicid, issueid, issuenumOG)
File "D:\ServerApps\Mylar\mylar-development\mylar\PostProcessor.py", line 1164, in Process_next
pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion)
File "D:\ServerApps\Mylar\mylar-development\mylar\cmtagmylar.py", line 330, in run
ctversion = subprocess.check_output([comictagger_cmd, "--version"])
File "C:\Python27\lib\subprocess.py", line 566, in check_output
process = Popen(stdout=PIPE, _popenargs, *_kwargs)
File "C:\Python27\lib\subprocess.py", line 710, in __init**
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
2015-11-25 10:51:31 INFO    [POST-PROCESSING] [1/1] Starting Post-Processing for Daredevil issue: 4
2015-11-25 10:51:31 INFO    [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2015-11-25 10:51:31 INFO    [DUPECHECK] Duplicate check for D:\Comics\Incomplete\Daredevil.Vol.2014.04.August.2014
2015-11-25 10:51:31 INFO    [POST-PROCESSING] issuenzb found.
2015-11-25 10:51:31 INFO    Starting postprocessing for : Daredevil.Vol.2014.04.August.2014
2015-11-25 10:51:31 INFO    ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
2015-11-25 10:51:17 INFO    pausing for 60 seconds before continuing to avoid hammering
2015-11-25 10:50:16 INFO    pausing for 60 seconds before continuing to avoid hammering
2015-11-25 10:50:16 INFO    Shhh be very quiet...I'm looking for Detective Comics issue: 23.1 (2013) using dognzb
2015-11-25 10:50:16 INFO    Could not find Issue 23.1 of Detective Comics(2011) using nzb.su [api]
2015-11-25 10:49:16 INFO    pausing for 60 seconds before continuing to avoid hammering
2015-11-25 10:48:16 INFO    pausing for 60 seconds before continuing to avoid hammering
2015-11-25 10:48:16 INFO    Shhh be very quiet...I'm looking for Detective Comics issue: 23.1 (2013) using nzb.su

Showing: Version: efe447f5170dfcea873b5da735c2fd66d2fe9936 (development) at the bottom of the UI.

I just downloaded a fresh ZIP from the development branch and extracted to my directory to refresh files.

**Comment by regulus0** [comment]
Resolved issue #2 by fixing my comictagger path. I had just moved my server to a new location and hadn't changed anything. Don't know why it pointed path back to my mylar-development folder?

**Comment by evilhero** [comment]
The detecting branch error is more of a warning than an actual error. It will always occur on the first startup as there is no value given in the config.ini as of yet for which branch it should ensure you're up-to-date on. If there isn't one set, Mylar does it's best guess to figure out the branch based on what your source files/git commit are. As you can see in the next line, it detects that you're on the development branch, so it checks against that tree to make sure you're up to date. Next startup, you won't see that message (you shouldn't).

The second error looks like it's due to the latest commit that went up a few days ago and is related to the comictagging. I'll look into this now (I tested as much as I could before, but obviously didn't test enough) - but in the meantime, you could disable the metatagging option to ensure it doesn't error out during post-processing.

**Comment by evilhero** [comment]
oh - it's diverting back due to the comictagger program and the new CV API rate limiting they are enforcing now. Basically it's 1 api request/s, but from my testing ComicTagger doesn't adhere to that, so while Mylar might follow the rate limiting rule, enabling metatagging within Mylar would mean it wouldn't. So I had to include the comictagger library within mylar now as I had to modify a few lines to ensure that it doesn't get people banned ;)

What did it flip the comictagger path back to exactly ?

**Comment by regulus0** [comment]
D:\ServerApps\Mylar\mylar-development  -- Which is root of my mylar path.

**Comment by regulus0** [comment]
The config actually changed my path back after restarting once more. I am looking at the correct line in my config right?

"cmtagger_path = D:\ServerApps\Mylar\mylar-development"

After it reverted I still get the same issues with Post Processing (error in original post) just a different comic.

**Comment by evilhero** [comment]
Weird,can you verify that there's a comictagger.py file in the root of mylar and that there are files within the mylar_root\lib\comictaggerlib\ directory?

I'm not in front of a machine atm, but will have to run through some of this when I get a chance later on.

**Comment by regulus0** [comment]
There is a comictagger.py file in the root of mylar. There are 46 items (3 are folders) in the comictaggerlib directory.

**Comment by evilhero** [comment]
Yep that's right - one last thing. Can you check the mylar.log file and find the last post-processing run and see if it provides any additional information - it should have the exact command being sent to comictagger within.

**Comment by regulus0** [comment]
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : Checking how out of whack the series is.
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : Comic series already up-to-date ... no need to refresh at this time.
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : Available to be marked for download - checking...Aquaman Issue: 46
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : ...Existing status: Wanted
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : ...Status already Wanted .. not changing.
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : --attempt to find errant adds to Wanted list
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : UpcomingNewValue: {'Status': 'Wanted', 'ComicName': 'Aquaman', 'IssueID': u'506617', 'DisplayComicName': 'Aquaman', 'IssueNumber': '46', 'IssueDate': '2015-11-25'}
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : UpcomingcontrolValue: {'ComicID': u'43022'}
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : updating Pull-list to reflect status change: Wanted[Wanted]
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : weekly_update of table : AQUAMAN #:46 to a status of Wanted
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : looking for : THE WALKING DEAD
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : There are 10 comics this week to get!
25-Nov-2015 16:06:11 - INFO    :: WEEKLYCHECK : Finished checking for comics on my watchlist.
25-Nov-2015 16:06:11 - DEBUG   :: WEEKLYCHECK : cflist: []
25-Nov-2015 16:06:11 - INFO    :: WEEKLYCHECK : No series have been marked as being on auto-watch.
25-Nov-2015 16:06:42 - INFO    :: CP Server Thread-8 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
25-Nov-2015 16:06:42 - INFO    :: CP Server Thread-8 : Starting postprocessing for : Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] SABnzbd Download folder option enabled. Directory set to : D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [NZBNAME]: Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Wonder Woman 035 2014 Digital phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: 468868
25-Nov-2015 16:06:42 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb found.
25-Nov-2015 16:06:42 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - INFO    :: Post-Processing : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
25-Nov-2015 16:06:42 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for Wonder Woman issue: 35
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] issueid: 468868
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] issuenumOG: 35
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Zero Suppression set to : 0x
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Pretty Comic Issue is : 035
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issue Year : 2014
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Publisher: DC Comics
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Series: Wonder Woman
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Year: 2011
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Comic Location: D:\Comics\DC Comics\Wonder Woman (2011)
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Comic Version: None
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] No version # found for series, removing from filename
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] New format is now: $Series $Issue ($Year)
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Not an annual - removing from filename parameters
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] New format: $Series $Issue ($Year)
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [POST-PROCESSING] Metatagging enabled - proceeding...
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] dirName:D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Paths / Locations:
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] scriptname : Mylar.py
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] downloadpath : D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] sabnzbdscriptpath : D:\ServerApps\Mylar\mylar-development
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] comicpath : D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] unrar_folder : D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp\unrard
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Running the ComicTagger Add-on for Mylar
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Attempting to create directory @: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Created directory @ : D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Filename is : None
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] Mylar.py: converting Wonder Woman 035 (2014) (Digital) (phillywilly-Empire).cbr to be zip format
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] {0}: Comicpath is D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp\Wonder Woman 035 (2014) (Digital) (phillywilly-Empire).rar
25-Nov-2015 16:06:42 - DEBUG   :: Post-Processing : [META-TAGGER] {0}: Unrar is D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\temp\unrard
25-Nov-2015 16:06:44 - DEBUG   :: Post-Processing : [META-TAGGER] Converted directory: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:44 - DEBUG   :: Post-Processing : [META-TAGGER] Converted filename: Wonder Woman 035 (2014) (Digital) (phillywilly-Empire).cbz
25-Nov-2015 16:06:44 - DEBUG   :: Post-Processing : [META-TAGGER] Destination path: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire\Wonder Woman 035 (2014) (Digital) (phillywilly-Empire).cbz
25-Nov-2015 16:06:44 - DEBUG   :: Post-Processing : [META-TAGGER] dirName: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:44 - DEBUG   :: Post-Processing : [META-TAGGER] absDirName: D:\Comics\Incomplete\Wonder.Woman.035.2014.Digital.phillywilly-Empire
25-Nov-2015 16:06:44 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "D:\ServerApps\Mylar\mylar-development\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\ServerApps\Mylar\mylar-development\mylar\PostProcessor.py", line 928, in Process
    return self.Process_next(comicid, issueid, issuenumOG)
  File "D:\ServerApps\Mylar\mylar-development\mylar\PostProcessor.py", line 1164, in Process_next
    pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion)
  File "D:\ServerApps\Mylar\mylar-development\mylar\cmtagmylar.py", line 330, in run
    ctversion = subprocess.check_output([comictagger_cmd, "--version"])
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

25-Nov-2015 16:06:56 - DEBUG   :: SEARCH : checking search result: 004+5 Green Lantern 028 - Red Lanterns 028 (2014) (4 covers) (Digital) (Nahga-Empire)
25-Nov-2015 16:06:56 - DEBUG   :: SEARCH : sub:004+5 Green Lantern 028 - Red Lanterns 028 (2014) (4 covers) (Digital) (Nahga-Empire)

**Comment by regulus0** [comment]
SABnzbd gets stuck with ComicRN.py running when this happens. Never clears until I kill Mylar.
