### ISSUE TITLE
Log Spam - ignoring os metadata for ._.DS_Store

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1169]
Not a huge or urgent issue, but my log fills up with really quickly with this message: "ignoring os metadata for ._.DS_Store"   

I think it is writing it once for every series that I have in Mylar, which is currently 248, and it does all these writings when Mylar does a either a [FOLDER-CHECK] or a [POST-PROCESSING].  

This is what the end of my log looks like:
![image](https://cloud.githubusercontent.com/assets/5505883/11446176/6ed9c9fc-9501-11e5-8e8f-a07435524a0b.png)

There is usually a couple pages of just this message.

**Comment by evilhero** [comment]
Ugh, yeah that's not good - Will be fixed in the next development commit. 

Thanks for the heads-up (since I don't have a mac, I never come across this

**Comment by BenBeyond** [comment]
Actually running on Ubuntu 15.04 if that help with the fix...

**Comment by millhench** [comment]
Those files are written by Macs on non-Mac filesystems. They're called AppleDouble Format files and store Finder info and extended attributes for macs. They can definitely be ignored and are only being written by OS X.
