### ISSUE TITLE
Can't access StoryArc feature.

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1171]
@evilhero , I am trying to access StoryArcs feature on newest DEV build.
I receive:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\webserve.py", line 2073, in storyarc_main
    if int(la['IssueDate'][:4]) > maxyear:
TypeError: 'NoneType' object has no attribute '__getitem__'
Powered by CherryPy 3.2.0

Any idea why?

**Comment by evilhero** [comment]
Do you have any story arcs present already within Mylar ? If you do, were they previous adds that were done with a .cbl import (comicrack story arc)

One/Several of a story arc already present has an invalid publication date for a particular issue - usually this is due to either CV problems failing to grab proper issue data, or it was a cbl import and it's causing some problems.

**Comment by bguidotti** [comment]
Do you have any story arcs present already within Mylar ? If you do, were they previous adds that were done with a .cbl import (comicrack story arc)

One/Several of a story arc already present has an invalid publication date for a particular issue - usually this is due to either CV problems failing to grab proper issue data, or it was a cbl import and it's causing some problems.

---
Reply to this email directly or view it on GitHub:
https://github.com/evilhero/mylar/issues/1171#issuecomment-160860054
HCSC Company Disclaimer

The information contained in this communication is confidential, private,
proprietary, or otherwise privileged and is intended only for the use of
the addressee.  Unauthorized use, disclosure, distribution or copying is
strictly prohibited and may be unlawful.  If you have received this
communication in error, please notify the sender immediately at
(312)653-6000 in Illinois; (800) 447-7828 in Montana;
(800)835-8699 in New Mexico; (918)560-3500 in Oklahoma; 
or (972)766-6900 in Texas.

**Comment by bguidotti** [comment]
I did have some; I think they were with .cbl.
How do I delete them since I can't access the feature through the GUI?

**Comment by evilhero** [comment]
You probably have to wipe the story arc table from the mylar.db (without mylar running) in order to clear it up as there's no real quick fix.

If you can get into the sqlite3 command prompt, with the mylar.db, typing in:
DROP TABLE readinglist;

**Comment by bguidotti** [comment]
OK - done. That did it; Thanks!
I will try to avoid any goofiness by being careful on the arcs I add.
