### ISSUE TITLE
FOLDERMONITOR stuck in an infinite 60 second delay/loop due to META-TAGGER

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1180]
Version: efe447f5170dfcea873b5da735c2fd66d2fe9936 (development)

This started acting up recently. 
FOLDERMONITOR performs the following steps:
1. [FOLDER-CHECK] checks against my download folder.
2. [DUPECHECK] detects a file.
3. [DUPECHECK] detection returns no hits. Not a duplicated file.
4. [POST-PROCESSING] Starts at step [1/x] for the issue.
5. Delaying startup thread for 60 seconds.
6. Go to step 1 60 seconds later.

As a result, no files are post-processed automatically anymore.

09-Dec-2015 19:41:12 - INFO    :: FOLDERMONITOR : [POST-PROCESSING] [1/5] Starting Post-Processing for The Amazing Spider-Man issue: 4
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] issueid: 507766
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] issuenumOG: 4
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Zero Suppression set to : 00x
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Pretty Comic Issue is : 004
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Issue Year : 2016
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Publisher: Marvel
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Series: The Amazing Spider-Man
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Year: 2015
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Comic Location: F:\Comics\Marvel\The Amazing Spider-Man (2015)
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Comic Version: v4
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Not an annual - removing from filename parameters
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] New format: $Series $Issue ($Year-$month)
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING] Metatagging enabled - proceeding...
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName:C:\Users\ldsilverman\Documents\Downloads\complete
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] chkpath: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] chkfile: Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Changing C:\Users\ldsilverman\Documents\Downloads\complete location to C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire as it is a directory.
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Paths / Locations:
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] scriptname : mylar.py
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] downloadpath : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] sabnzbdscriptpath : C:\PythonPrograms\mylar-development
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] comicpath : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] unrar_folder : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766\unrard
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Running the ComicTagger Add-on for Mylar
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Attempting to create directory @: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Created directory @ : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Filename is : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] moving : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz to C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - INFO    :: FOLDERMONITOR : [META-TAGGER] Filename detected as a .cbz file.
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] filename : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] This is a zipfile. Unable to test rar.
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Base set to : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Moving : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz - to - C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Verified file exists in location: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Successfully removed temporary directory: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\507766
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] new filename : C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Converted directory: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Converted filename: Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Destination path: C:\Users\ldsilverman\Documents\Downloads\complete\comics\Amazing.Spider-Man.004.2016.Digital.Zone-Empire\Amazing Spider-Man 004 (2016) (Digital) (Zone-Empire).cbz
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] dirName: C:\Users\ldsilverman\Documents\Downloads\complete
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] absDirName: C:\Users\ldsilverman\Documents\Downloads\complete
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: [Error 2] The system cannot find the file specified
09-Dec-2015 19:41:12 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "C:\PythonPrograms\mylar-development\mylar\scheduler.py", line 78, in runAction\n    self.action.run()\n  File "C:\PythonPrograms\mylar-development\mylar\PostProcessor.py", line 1580, in run\n    result = PostProcess.Process()\n  File "C:\PythonPrograms\mylar-development\mylar\PostProcessor.py", line 912, in Process\n    self.Process_next(comicid, issueid, issuenumOG, ml, stat)\n  File "C:\PythonPrograms\mylar-development\mylar\PostProcessor.py", line 1166, in Process_next\n    pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml[\'ComicLocation\'])\n  File "C:\PythonPrograms\mylar-development\mylar\cmtagmylar.py", line 330, in run\n    ctversion = subprocess.check_output([comictagger_cmd, "--version"])\n  File "C:\Python27\lib\subprocess.py", line 566, in check_output\n    process = Popen(stdout=PIPE, _popenargs, *_kwargs)\n  File "C:\Python27\lib\subprocess.py", line 710, in **init**\n    errread, errwrite)\n  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child\n    startupinfo)\nWindowsError: [Error 2] The system cannot find the file specified\n'
09-Dec-2015 19:41:13 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
09-Dec-2015 19:41:13 - INFO    :: FOLDERMONITOR : delaying startup thread for 60 seconds to avoid locks.

**Comment by lodasi** [comment]
Disabling meta-tagger does lead to files being processed.

**Comment by evilhero** [comment]
It looks like it can't find comictagger - the problem is that due to the new CV api rate limit,  using the original comictagger will get you banned eventually as it doesn't follow the new rate limits. I had modified some of the code within comictagger that allows it to conform to the rate limit, but I had to then include comictagger within mylar now (to ensure the rate limits apply).

I'll have to look into this more as I was trying to get it to work without having to open up a separate dos window when tagging, and streamlining it all in one would be better.

Unfortunately the only thing to do atm, is to disable metatagging within mylar temporarily. I'll see if I can get this all working as soon as in can again.

**Comment by DGMayor** [comment]
Tried to figure out why I Haven't downloaded anything since November 27th. Just went to ComicVine to see I was ipbanned ><  Must be why..

**Comment by DGMayor** [comment]
So Mylar pretty much requires Comicvine access right?  If so, I guess it's useless to me now, as they basically told me to F off when I emailed about the ban.

**Comment by DGMayor** [comment]
Well they released the ban, but said this:

Oh sorry. I read the wrong record.  Your IP is banned because you were running a scraper bot that we don't allow. I removed the ban.  We do not allow anything other that a web browser to use our service. Any third party app will get you banned again.

**Comment by evilhero** [comment]
Yeah they implemented a new api rate limit now that if you go over 1 api hit / s, it will get you a temporary ban, and subsequent attempts would possibly be worse.

Mylar doesn't scrape ComicVine though (it only uses the api), and as far as I can remember ComicTagger doesn't either (although it doesn't adhere to the rate limit). The only app that I know of that was scraping CV, was comicvine scraper. Were you using that recently (or around the time that you stopped being able to access CV)?

**Comment by DGMayor** [comment]
Not to my knowledge.  I haven't touched my config in forever.

**Comment by DGMayor** [comment]
@evilhero Possible to take this convo offline/out of comments?  Email or private message somewhere or something.  I just want to make sure I've got everything set up correctly here..

**Comment by evilhero** [comment]
@DGMayor sure, email evilhero@mylarcomics.com and we can talk
