### ISSUE TITLE
Rename - Failed to move files - check directories and manually re-run.

### ISSUE THREAD

**Issue by timm088** [evilhero/mylar#1181]
When i try to run a rename on the files being managed by mylar, I get the following error:
2015-12-11 09:45:03 ERROR   Failed to move files - check directories and manually re-run.

From what I can see, everything below the root directory mylar looks for files has the right permissions, there should be nothing stopping it for renaming. 

I have tried changing logverbose = 2 (I think thats debug?), with mylar stopped, in order to get more information, but every time I start the service again, It reverts back to logverbose = 1 ? 

Everything else is working fine for me at the moment, just renaming wont seem to work.

**Comment by timm088** [comment]
I should add that I only see this problem on existing files, new files, do not seem to have the same issue

**Comment by timm088** [comment]
Ok, some further testing. 
I did have enabled 'lowercase the entire filename', which seemed to be causing the issue. 

After disabling that option (in Advanced Settings) the rename works. 

Not sure if bug?

**Comment by evilhero** [comment]
The manual rename and the renaming during post-processing each use different code, so having problems in one vs the other can occur for sure.

Mylar logs everything in debug mode to the mylar.log files - you can only see information level of logging within the gui. So you probably need to check the actual mylar.log file I order to get a better understanding. 

It's definitely possible the lowercase is behaving wrong during a manual rename. I'll have to do some tests on my side to make sue I can replicate the problem and then see what's going on.

**Comment by sterlinganderson** [comment]
Just wanted to comment, this was happening to me as well. Unchecking the "Lowercase the entire filename" option solved the problem.
This happened on a cbr file I placed in to the comic folder manually.

**Comment by evilhero** [comment]
Thanks for the update - since I don't use that option I wouldn't have noticed it happening. I'll consider this then an outstanding bug and will look into it more - I'm planning on pushing a big commit out in a bit, so I'll see if I can add this in as it should be a fairly simple fix.
