### ISSUE TITLE
Notifications not respecting http base

### ISSUE THREAD

**Issue by timm088** [evilhero/mylar#1182]
Using pushover (or I assume) any notification service, I cant get the notification to work when the http base is changed. 

If you use the "test pushover" button, nothing will happen (nothing in the log) - only an empty green box within the UI

If however, you change the 'test pushover' url manually to myip:8090/mybase/testpushover you get a successful test sent through. 

Sorry I am not too good on python / finding where this is used in the modules or I'd created a PR myself.

**Comment by evilhero** [comment]
Sorry it took so long for this one, fix will be in the next development commit (was a silly slash at the beginning of the url call in the html page that was stopping the correct joining of the parameters together)
