### ISSUE TITLE
Not post-processing

### ISSUE THREAD

**Issue by basvroegop** [evilhero/mylar#1190]
Hello!

First off: thanks a ton for making Mylar. Really appreciating the idea behind this bit of software.

I set Mylar up with a torrent client tonight, and most of it seemed to go well. Midway through though, it stopped postprocessing each time it checked my completed download folder. When I try to manually post-process, I get this error:

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/PostProcessor.py", line 305, in Process
watchmatch = filechecker.listFiles(self.nzb_folder, cs['ComicName'], cs['ComicPublisher'], cs['AlternateSearch'], manual=cs['WatchValues'])
File "/opt/Mylar/mylar/filechecker.py", line 76, in listFiles
dirlist = traverse_directories(basedir)
File "/opt/Mylar/mylar/filechecker.py", line 1230, in traverse_directories
for (dirname, subs, files) in os.walk(dir):
File "/usr/lib/python2.7/os.py", line 284, in walk
if isdir(join(top, name)):
File "/usr/lib/python2.7/posixpath.py", line 80, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 69: ordinal not in range(128)

Any idea what I'm doing wrong? Tried looking around in issues, but couldn't find a solution.

Thanks.

**Comment by evilhero** [comment]
It looks like either there's a special character in one of the filenames that's causing the problem - or it might be related to mylar and the torrent client being on a different OS (just a wild guess).

Can you check the directory mylar's trying to post process and see if there's any such files? 

Also if you check the mylar.log file and search for that particular error, just prior to the error it will indicate what file it was trying to post-process.

**Comment by claym** [comment]
Are you running ok FreeNAS? There's no locale set in its VMs and I've seen
it throw very similar errors.

**Comment by basvroegop** [comment]
@claym I'm running an small computer with Ubuntu installed on it, so I don't think that's it.

@evilhero Checked out the log! It seemed to be freaking out once it needs to check the download folder for Saga. Tried removing some files that might be causing issues at random, but no lock. I deleted all non-comic files that were in the folder though, and that did the trick. Need to figure out a setup that doesn't crash whenever I download something else, now. 

Any chance a movie or two might have caused the issue? Thanks for responding so quickly, anyway!

**Comment by evilhero** [comment]
Mylar only looks at files that have a cbr/cbz extension, so unless one of the movies ended with that extension it shouldn't have played a factor (mine monitors a folder that has everything under the sun in it, and mylar has only ever grabbed comic files).

Is it possible that the user running mylar didn't have proper permissions to the download folder it's scanning in? It 'should' log it as a permission denied type of error, but it's quite possible it's crashing at that part.

**Comment by basvroegop** [comment]
Ah, guessing there was a file with a weird name, if that's the case. No clue what sort of character caused the issue, sorry. I didn't change rights before or after it started working again, so don't think that's it.

I am up to date! Did end up splitting my folders by downloader, even though it probably wasn't different filetypes causing the issues. At least this way, it'll be easier to narrow down any future problems I might run into. :)

Thanks for helping me out, and goodluck keeping up this awesome project!
