### ISSUE TITLE
Mass download of comics caused URL Grabber issues in SABnzbd

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1191]
I am experiencing an issue where, seemingly upon a large stack of comics downloads getting queued in SAB, I have multiple URL Grabber errors.  I don't know if this is more your issue or theirs.

I am running DEV branch of Mylar and 0.80beta4 on Windows of SAB.

The errors look similar to the below:

ERROR 01/10/2016 23:52 URLGRABBER CRASHED
Traceback (most recent call last):
  File "sabnzbd\urlgrabber.pyo", line 204, in run
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\Users\Bruce\AppData\Local\sabnzbd\admin\future\api?apikey=REDACTED&cmd=downloadNZB&nzbname=Invincible.126.2015.Digital.Zone-Empire.nzb'

Any idea what is causing this?

Thanks in advance for your insight.

**Comment by bguidotti** [comment]
Could it be because of the path formatting?

**Comment by evilhero** [comment]
That looks like sab is trying to save the filename as that entire path for some reason - not entirely sure why as all mylar does is send an addurl command to sabnzbd which then has the addurl reference pointing back to the downloaded nzb (that resides in mylar's cache) to download. 

I'm wondering if there's something different in that beta version of sabnzbd that's causing the problem - url grabber is sabnzbd, not mylar.

**Comment by bguidotti** [comment]
Yeah, I found some instances related to Sickbeard and Sonarr in the past - I will take it up with them.

Thanks!

**Comment by evilhero** [comment]
Here's a similar post on the mylar forums that was posted earlier with the same version of sabnzbd and a similar type of problem:

http://mylar.forumatic.com/viewtopic.php?f=8&t=1203

(Sorry for weird link url - on my phone atm)

**Comment by bguidotti** [comment]
I see that...hmm. I opened an issue with them; do you want to leave this open so I can crosslink resolution? If not I will close this one.

**Comment by evilhero** [comment]
Sure you can leave it open - if mylar needs to be patched somehow I can do it, but I'd need to know why it's throwing that error. 

Otherwise I'd like to know the resolution so others might see it or we can temporarily advise against that particular version.

**Comment by bguidotti** [comment]
Here is the link to the SAB issue: https://github.com/sabnzbd/sabnzbd/issues/422
They stated: "It seems to be that Mylar sends odd headers and the new CherryPy web framework doesn't handle this well. I guess SABnzbd must clean up the alleged file name coming from CherryPy."

The final closure note says: "Sometimes an uploaded filename contains the full URL, strip it down."

**Comment by bguidotti** [comment]
This is not happening anymore.  Closing.
