### ISSUE TITLE
32p/torrents not finding anyting

### ISSUE THREAD

**Issue by dvdgorila** [evilhero/mylar#1200]
I've recently set up mylar, and i am not having any luck with torrents.

`Configuration Options
Mylar Version: master
-- git build f0f9cda21ec15451b05c4e930595159540b19e8e.
Python Version : 2.7.11
`

I've configured 32p and Tornab as you can see below this it the output i get for every search. 

`
28-Jan-2016 16:15:52 - INFO :: Thread-15 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Marvels Captain America Civil War Prelude
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Issue Title given as : part two
28-Jan-2016 16:15:52 - INFO :: Thread-15 : search provider order is ['32p', 'torznab']
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Shhh be very quiet...I'm looking for Marvel's Captain America: Civil War Prelude issue: 2 (2016) using 32P [RSS]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Alternate Search pattern detected...re-adjusting to : Marvels Captain America Civil War Prelude 2016
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Shhh be very quiet...I'm looking for Marvels Captain America Civil War Prelude issue: 2 (2016) using 32P [RSS]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Could not find Issue 2 of Marvel's Captain America: Civil War Prelude(2015) using 32P [rss]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Shhh be very quiet...I'm looking for Marvel's Captain America: Civil War Prelude issue: 2 (2016) using Torznab [RSS]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Alternate Search pattern detected...re-adjusting to : Marvels Captain America Civil War Prelude 2016
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Shhh be very quiet...I'm looking for Marvels Captain America Civil War Prelude issue: 2 (2016) using Torznab [RSS]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Could not find Issue 2 of Marvel's Captain America: Civil War Prelude(2015) using Torznab [rss]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Finished searching via :rss. Issue not found - status kept as Wanted.
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Could not find Issue 2 of Marvel's Captain America: Civil War Prelude(2015) using 32P [api]
28-Jan-2016 16:15:52 - INFO :: Thread-15 : Shhh be very quiet...I'm looking for Marvel's Captain America: Civil War Prelude issue: 2 (2016) using Torznab
28-Jan-2016 16:15:52 - INFO :: Thread-15 : pausing for 60 seconds before continuing to avoid hammering

**Comment by evilhero** [comment]
Try enabling the verbose logging in the Log tab in the gui. Then do a Force RSS check from the Search Providers tab in the configuration. 

You should get some logging then that shows more or what's occuring.

There is no backlog support for 32p as of yet - so it relies purely on rss feeds and caching. The longer you have mylar running and grabbing the feeds off of 32p the more of a cache you can draw from when searching. 

If you use the authentication method for 32p within mylar then it will monitor the new releases rss feed as well as any personal feeds you might have. If you use the other method, it just monitors the new releases feed. 

Backlog support is coming, but we're trying to work out a suitable approach to the backlog that 32p admins will approve of, as well as one that's beneficial to the users of mylar that will support some kind of backlog search functionality.

**Comment by dvdgorila** [comment]
That makes a lot of sense now. I wasn't aware it didnt backlog search. I'll play around with the RSS feeds from 32p.

Thanks for the reply.
