### ISSUE TITLE
post processing script now hangs in sabnzb

### ISSUE THREAD

**Issue by partymike** [evilhero/mylar#1204]
Hi, after the recent couple of updates mylar now effectivly crashes sabnzb as it "sticks" on running the comicRN.py script...which freezes everything else in the sabnzb queue - I have to manually clear it down for things to work again.

I can see this error in the log:

ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 947, in Process
return self.Process_next(comicid, issueid, issuenumOG)
File "C:\Mylar\mylar\PostProcessor.py", line 1213, in Process_next
pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, filename=os.path.join(odir, ofilename))
File "C:\Mylar\mylar\cmtagmylar.py", line 143, in run
ctversion = subprocess.check_output([sys.executable, comictagger_cmd, "--version"])
File "C:\Python27\lib\subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Mylar\\comictagger.py', '--version']' returned non-zero exit status 

I've checked that the comicRN.py is newest version.....help!

**Comment by skywayskase** [comment]
Looks like what's happening to me as well. Do you get the same error when you try to manually post-process?

**Comment by partymike** [comment]
I've currently disabled the comicRN.py script as was causing me too many issues in sabnzb, so not sure....manually moving the downloads for now :-(

**Comment by evilhero** [comment]
What happens when you run the following from the command lne?
```
C:\Python27\python.exe C:\Mylar\\comictagger.py --version
```
or from within the mylar directory itself:
```
python comictagger.py --version
```

**Comment by partymike** [comment]
C:\Mylar>python comictagger.py --version
Traceback (most recent call last):
  File "comictagger.py", line 2, in <module>
    from lib.comictaggerlib.main import ctmain
  File "C:\Mylar\lib\comictaggerlib\main.py", line 27, in <module>
    import utils
  File "C:\Mylar\lib\comictaggerlib\utils.py", line 28, in <module>
    from settings import ComicTaggerSettings
  File "C:\Mylar\lib\comictaggerlib\settings.py", line 23, in <module>
    import configparser
ImportError: No module named configparser

**Comment by evilhero** [comment]
you need to have the configparser module installed for comictagger to work ;)

**Comment by partymike** [comment]
any idea how this stopped/uninstalled as worked ok till about a week ago....

how's best to install the module on a windows box?? :-)

**Comment by evilhero** [comment]
it should be as easy as making sure you're in your python directory in a command prompt and doing a
```
pip install configparser
```
or 
```
easy_install configparser
```
(I've only done the easy_install one, but pip should work as well)

In the last week dev got merged into master and something changed in regards to how ComicTagger interacts with Mylar due to new ComicVine limitations. Aside from yourself and @skywayskase, there hasn't been anyone mentioning problems with the way things are currently with Mylar and ComicTagger.

I would assume that both of you probably had ComicTagger installed as a separate program and when Mylar flipped to it's own version (which is a python module, not the .exe) it caused the error during the import message (Which I can now trap - thanks for that).

**Comment by partymike** [comment]
used pip and installed fine, yes I used a comictagger as its own .exe - thanks for the help, love the program :-D

**Comment by partymike** [comment]
all working,
