### ISSUE TITLE
Issue deletion

### ISSUE THREAD

**Issue by kiloboy** [evilhero/mylar#1205]
I've noticed that when I find comics that Mylar can not find and I put them into their directories, Mylar will delete those issues.

**Comment by evilhero** [comment]
Can you provide a log snapshot (in debug mode)  showing what's occurring?  This hasn't been brought up before and mylar generally doesn't delete stuff haphazardly -  although it may overwrite files based on your settings, or if you're using metatagging and it fails to tag properly for some reason. 

Are you just dumping files into the series directory and doing a Recheck Files on the series?

**Comment by kiloboy** [comment]
Ok. Re-downloaded the files and I will wait and see if Mylar does it again. I have no meta-tagging in place. The files weren't even over written, just gone. For giggles I put a mispaced comic in there and it hasn't been deleted yet.

**Comment by kiloboy** [comment]
Go ahead and close out this issue. I can't seem to get it to repeat the
issue. Thanks, donation incoming.

**Comment by evilhero** [comment]
Closing as per your request.  If it happens again feel free to reopen (hopefully with a log that I can follow what's happening)
