### ISSUE TITLE
Can't move cache directory

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1208]
I have Mylar on my system SSD drive. Because of all the cache writes, I want to move the cache directory for Mylar to the drive all my other comics are located on, but when I change the config file to specify a different location, it only works the next time I start Mylar, but any time I restart Mylar after that, it defaults back to the main Mylar directory.

**Comment by skywayskase** [comment]
It also forces an incorrect bracket at the end:
```
C:\Program Files (x86)\Mylar\cache/
```
You had me erase that entire line in the config file and have Mylar recreate it earlier this week, but after starting Mylar the second time after the change, it automatically added that bracket back to the path.

**Comment by evilhero** [comment]
You can't have mylar running when you edit the config.ini file as it writes to it on exit of the program and will hammer any changes made. 

So shutdown mylar, edit the config.ini, change the setting and save the config.ini, start up mylar and the settings will be persistent through reboots. 

Keep in mind that if your startup script specifies a cache directory that will override any config values.

**Comment by skywayskase** [comment]
That's what I did. I always shut down mylar before editing the config.ini. And my startup script does not appear to manually specify a cache directory.

**Comment by evilhero** [comment]
OK that was my 'it will fix the problem 90% of the time' answer - usually when I'm on my phone for a quick response to try ;) 

I'll check into it when I can get in front of a machine later tonight and see what's going on. If it's not allowing for the specification of a cache directory then that's a definite problem

**Comment by skywayskase** [comment]
So just a quick update here. I saw that the latest update included a possible fix for cache-dir not being respected. I updated, shutdown mylar, specified a customer cache-dir, and started mylar back up. I then shut it down and started it back up again. Settings held, I experienced joyful delusion, and I thought everything was good. I then told mylar to do a manual search on a comic from last week, and when it found the comic and sent it to Sabnzbd, it reset the cache-dir back to "C:\Program Files (x86)\Mylar\cache/" in the config file, all on its own.

**Comment by evilhero** [comment]
Thanks for the update @skywayskase  - I'll have to check and see what's happening, based on what you're saying there's another check somewhere during the search/post-process workflow that forces the cache directory. I just need to find out where....
