### ISSUE TITLE
Duplicate issue? - won't copy from cache

### ISSUE THREAD

**Issue by Rumtum** [evilhero/mylar#1209]
Two things here. The ConfigParser warning has come back and new imports are remaining in the cache directory - see the error at the end of the log.

"07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
"

Version: bbcd4ea82a629493f6b63528ea5b3ed68eb87283 (development)

07-Feb-2016 13:25:43 - INFO    :: CP Server Thread-4 : Verbose toggled, set to True
07-Feb-2016 13:25:44 - DEBUG   :: CP Server Thread-4 : If you read this message, debug logging is available
07-Feb-2016 13:25:53 - INFO    :: CP Server Thread-4 : Starting postprocessing for : Manual Run
07-Feb-2016 13:25:53 - DEBUG   :: Thread-12 : [POST-PROCESSING] nzb name: Manual Run
07-Feb-2016 13:25:53 - DEBUG   :: Thread-12 : [POST-PROCESSING] nzb folder: L:\sabnzbd\complete\comics
07-Feb-2016 13:25:53 - DEBUG   :: Thread-12 : [POST-PROCESSING] Not using SABnzbd : Manual Run
07-Feb-2016 13:25:53 - DEBUG   :: Thread-12 : [POST-PROCESSING] Manual Run initiated
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [FILECHECKER] I have found a total of 1 Promethee comics
07-Feb-2016 13:25:54 - INFO    :: Thread-12 : [POST-PROCESSING] Found matching issue # 7000 for ComicID: 83109 / IssueID: 513815
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] There are 1 files found that match on your watchlist, 50 do not match anything and will be ignored.
07-Feb-2016 13:25:54 - INFO    :: Thread-12 : [DUPECHECK] Duplicate check for L:\sabnzbd\complete\comics\Promethee 07.cbr
07-Feb-2016 13:25:54 - INFO    :: Thread-12 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
07-Feb-2016 13:25:54 - INFO    :: Thread-12 : [POST-PROCESSING] [1/1] Starting Post-Processing for Promethee issue: 7
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] issueid: 513815
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] issuenumOG: 7
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] Zero Suppression set to : none
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] Pretty Comic Issue is : 7
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] Issue Year : 2016
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] Publisher: Soleil
07-Feb-2016 13:25:54 - DEBUG   :: Thread-12 : [POST-PROCESSING] Series: Promethee
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] Year: 2015
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] Comic Location: r:\eComics\Promethee
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] Comic Version: None
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] No version # found for series, removing from filename
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] New format is now: $Series $Issue ($Year)
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] Not an annual - removing from filename parameters
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] New format: $Series $Issue ($Year)
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [POST-PROCESSING] Metatagging enabled - proceeding...
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [META-TAGGER] dirName:L:\sabnzbd\complete\comics
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : ComicTagger Path location for internal comictagger.py set to : C:\Program Files (x86)\Mylar\comictagger.py
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
07-Feb-2016 13:25:55 - DEBUG   :: Thread-12 : [META-TAGGER] Filename is : L:\sabnzbd\complete\comics\Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] Paths / Locations:
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] scriptname : mylar.py
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] downloadpath : L:\sabnzbd\complete\comics
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] sabnzbdscriptpath : C:\Program Files (x86)\Mylar
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] comicpath : C:\Program Files (x86)\Mylar\cache\mylar_nmbfwk
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] unrar_folder : C:\Program Files (x86)\Mylar\cache\mylar_nmbfwk\unrard
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
07-Feb-2016 13:25:59 - WARNING :: Thread-12 : [META-TAGGER][WARNING] Make sure that you have configparser installed.
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without tagging...
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] ofilename:Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] odir: L:\sabnzbd\complete\comics
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] ofilename: Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] ext:.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Original Filename: Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Original Extension: .cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] New Filename: Promethee 7 (2016)
07-Feb-2016 13:25:59 - INFO    :: Thread-12 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: r:\eComics\Promethee
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Source: L:\sabnzbd\complete\comics\Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Destination: r:\eComics\Promethee\Promethee 7 (2016).cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Renaming L:\sabnzbd\complete\comics\Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] odir src : L:\sabnzbd\complete\comics\Promethee 07.cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] moveing L:\sabnzbd\complete\comics\Promethee 07.cbr ... to ... r:\eComics\Promethee\Promethee 7 (2016).cbr
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
07-Feb-2016 13:25:59 - DEBUG   :: Thread-12 : [POST-PROCESSING] Post-Processing ABORTED.
07-Feb-2016 13:25:59 - INFO    :: Thread-12 : [POST-PROCESSING] Manual post-processing completed for 1 issues

**Comment by evilhero** [comment]
The configparser error is due to comictagger now being included with mylar as opposed to using user installed versions due to new CV rate limiting restrictions. Windows users are mainly affected by this as running the .exe you didn't need to have configparser installed.  Now that Mylar uses it as a python module you need to install configparser manually ('pip install configparser' or 'easy_install configparser' from a command prompt should install it without any issues). 

The second problem is due to not having configparser installed, it doesn't metatag the issue but fails to update the directory path to the new cache directory (where the file would now reside).  I'll do the fix for this for the next development commit -  once you have configparser installed though you won't see the error message again about failing  to move.
