### ISSUE TITLE
 'issuenotes_id' referenced before assignment

### ISSUE THREAD

**Issue by hakarune** [evilhero/mylar#1210]
I'm getting this error on scanning any of my comics. Comic library migrating from ComicRack to Mylar. Just installed Mylar today and getting this issue when I try to scan any comic into the library.

`ERROR  Unable to complete the scan: local variable 'issuenotes_id' referenced before assignment`

Sample Test Comic
Filename: `Invincible (2003) V2003 #091 -.cbz`
XML: attached - [ComicInfo.xml](https://github.com/evilhero/mylar/files/122706/ComicInfo.txt)

**Comment by evilhero** [comment]
Yep, that's an omission on my part. When I was doing the meta-tagging check, I was only using ComicTagger which puts the IssueID in the notes field as '[Issue ID <issueid>]'. 

Comicvine Scraper (I'm guessing that's what you used to tag), puts the IssueID in the notes field as well, but as '[CVDB<issueid>]'

I've fixed my local repo - so will be in the next development commit which hopefully should be coming shortly pending some personal things going on atm.

**Comment by hakarune** [comment]
Yeah, I have comicvine setup. Oh nice, can't wait for the update. I look forward to pushing it onto my system. Thanks for the quick response ^_^.
