### ISSUE TITLE
Stopped post processing

### ISSUE THREAD

**Issue by stumueller** [evilhero/mylar#1213]
Hi

I've been experiencing this for a while now. When a comic is downloaded it goes into my download folder, but Mylar has recently not been able to correctly rename and tag the comic, its been sitting in an unrared state. I checked my log file and got these entries

11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] downloadpath : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] sabnzbdscriptpath : C:\Mylar
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] comicpath : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] unrar_folder : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530\unrard
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : [META-TAGGER] Running the ComicTagger Add-on for Mylar
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Torrents\\Comics\\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\\514530'
11-Feb-2016 22:39:34 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "C:\\Mylar\\mylar\\scheduler.py", line 78, in runAction\n    self.action.run()\n  File "C:\\Mylar\\mylar\\PostProcessor.py", line 1580, in run\n    result = PostProcess.Process()\n  File "C:\\Mylar\\mylar\\PostProcessor.py", line 912, in Process\n    self.Process_next(comicid, issueid, issuenumOG, ml, stat)\n  File "C:\\Mylar\\mylar\\PostProcessor.py", line 1166, in Process_next\n    pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml[\'ComicLocation\'])\n  File "C:\\Mylar\\mylar\\cmtagmylar.py", line 139, in run\n    shutil.rmtree(comicpath)\n  File "C:\\Python27\\lib\\shutil.py", line 256, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File "C:\\Python27\\lib\\shutil.py", line 254, in rmtree\n    os.rmdir(path)\nWindowsError: [Error 32] The process cannot access the file because it is being used by another process: u\'C:\\\\Torrents\\\\Comics\\\\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\\\\514530\'\n'
11-Feb-2016 22:48:52 - DEBUG   :: CP Server Thread-8 : Weekly pull list present - retrieving pull-list date.
11-Feb-2016 22:58:30 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
11-Feb-2016 22:58:30 - INFO    :: FOLDERMONITOR : delaying startup thread for 60 seconds to avoid locks.

a search on google just find issues related to the log file not rolling over, however this appears to be  an issue with the comic file being locked by a process, not the log file.

Any ideas?

Stuart

**Comment by stumueller** [comment]
Just an addition, after restarting mylar, and cleaning up my download directory, I've now got this error.
It all seemed to start after I updated my version of comictagger that I have installed, but I thought mylar came with its own version of comictagger.

11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Changing C:\Torrents\Comics location to C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD as it is a directory.
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Paths / Locations:
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] scriptname : Mylar.py
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] downloadpath : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] sabnzbdscriptpath : C:\Mylar
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] comicpath : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] unrar_folder : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530\unrard
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Attempting to create directory @: C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Created directory @ : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Filename is : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] moving : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz to C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - INFO    :: Thread-17 : [META-TAGGER] Filename detected as a .cbz file.
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] filename : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] This is a zipfile. Unable to test rar.
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Base set to : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Moving : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz - to - C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Verified file exists in location: C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Successfully removed temporary directory: C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\514530
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] new filename : C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Converted directory: C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Converted filename: Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] Destination path: C:\Torrents\Comics\Grimm.Fairy.Tales.119.2016.3.covers.Digital.TLK-EMPIRE-HD\Grimm Fairy Tales 119 (2016)(3 covers)(Digital)(TLK-EMPIRE-HD).cbz
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] dirName: C:\Torrents\Comics
11-Feb-2016 23:15:56 - DEBUG   :: Thread-17 : [META-TAGGER] absDirName: C:\Torrents\Comics
11-Feb-2016 23:15:56 - ERROR   :: Thread-17 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\PostProcessor.py", line 912, in Process
    self.Process_next(comicid, issueid, issuenumOG, ml, stat)
  File "C:\Mylar\mylar\PostProcessor.py", line 1166, in Process_next
    pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml['ComicLocation'])
  File "C:\Mylar\mylar\cmtagmylar.py", line 330, in run
    ctversion = subprocess.check_output([comictagger_cmd, "--version"])
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by evilhero** [comment]
You probably need to use the development branch of mylar.  All issues related to the comictagger included with mylar and how it interacts both with comicvine and mylar itself have pretty much resolved themselves on that branch. 

Keep in mind the that you need to install configparser as the version that is included with mylar isn't the . exe and as such the dependency needs to be fulfilled on a system by system basis.

**Comment by stumueller** [comment]
How do I switch to th dev branch now Im running Live without reinstalling?

and is configparser a module in python?

Stu

**Comment by evilhero** [comment]
If you used git to install the version you're running is as simple as doing 2 commands from the gitshell:
git pull
git checkout development

Otherwise you can go to the github page, change the branch to development and grab the source zip file and then do the normal extract process to get it into the correct directory.

**Comment by stumueller** [comment]
Thats worked a treat thanks!

So should I stay on the dev branch from now on?

**Comment by evilhero** [comment]
Yep stay on the development branch as it's the most up to date  and if something goes wrong for whatever reason the development branch gets things fairly quickly.

**Comment by stumueller** [comment]
Thank you
