### ISSUE TITLE
Cannot import or search

### ISSUE THREAD

**Issue by szimmerman29** [evilhero/mylar#1214]
Tried both the -master and the -dev, see below for log file:

2016-02-12 16:16:32 ERROR Uncaught exception: Traceback (most recent call last):
 File "C:\Users\Scott\Desktop\mylar-development\mylar\logger.py", line 158, in new_run
 old_run(_args, *_kwargs)
 File "C:\Python27\lib\threading.py", line 763, in run
 self.__target(_self.__args, *_self.__kwargs)
 File "C:\Users\Scott\Desktop\mylar-development\mylar\search.py", line 1544, in searchforissue
 foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
 File "C:\Users\Scott\Desktop\mylar-development\mylar\search.py", line 283, in search_init
 if searchprov == '32P':
UnboundLocalError: local variable 'searchprov' referenced before assignment

**Comment by evilhero** [comment]
Sounds like it didn't save the configuration properly.  Shutdown mylar and then start it up again. If you need to make changes in the config, do the changes and then make sure to save and restart mylar.  The restart is an unfortunate need as then it ensures that Mylar loads up all the config values from the config.ini and doesnt use some cached version. 

If not that, then it's either a config problem of some kind (you have torrents enabled but didn't specify an method to download to),  or you're using an outdated version of mylar.
