### ISSUE TITLE
Search failures

### ISSUE THREAD

**Issue by sterlinganderson** [evilhero/mylar#1216]
Searches are failing for me recently. I can pull the search URL from the logs and they work fine, so i am not sure what is going on. Log info is below:

25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : ComicID:18166
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : mode:want
25-Feb-2016 13:42:08 - INFO    :: Thread-13 : Initiating manual search for The Walking Dead issue: 148
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : Publisher is : Skybound
25-Feb-2016 13:42:08 - INFO    :: Thread-13 : Issue Title given as : no turning back
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : Checking for torrent enabled.
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : newznab name:nzbfinder @ https://nzbfinder.ws
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : nzbprovider(s): ['newznab:nzbfinder']
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : there are : 0 torrent providers you have selected.
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : there are : 1 nzb providers you have selected.
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : Usenet Retention : 1500 days
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : found provider in existing enabled providers.
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : checking against nzb provider: newznab:nzbfinder
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : newznab match against: newznab:nzbfinder
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : sucessfully matched - appending to provider.order sequence
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : provider order sequence is now to start with nzbfinder at spot #1
25-Feb-2016 13:42:08 - INFO    :: Thread-13 : search provider order is ['newznab:nzbfinder']
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : Initiating Search via : api
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : using Newznab host of : nzbfinder
25-Feb-2016 13:42:08 - INFO    :: Thread-13 : Shhh be very quiet...I'm looking for The Walking Dead issue: 148 (2015) using nzbfinder (newznab)
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : calpha/cnumber: None / None
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : RSS Check: None
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : nzbprov: newznab
25-Feb-2016 13:42:08 - DEBUG   :: Thread-13 : comicid: 18166
25-Feb-2016 13:42:08 - INFO    :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
25-Feb-2016 13:43:08 - DEBUG   :: Thread-13 : [SSL: True] Search URL: https://nzbfinder.ws/api?t=search&q=%20walking%20dead%20148&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
25-Feb-2016 13:43:08 - INFO    :: Thread-13 : 404 page not found
25-Feb-2016 13:43:08 - WARNING :: Thread-13 : Unable to download torrent from newznab [Status Code returned: 404]
25-Feb-2016 13:43:08 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1313, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/opt/mylar/mylar/search.py", line 249, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/opt/mylar/mylar/search.py", line 601, in NZB_SEARCH
    if data:
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by evilhero** [comment]
The 404 is probably due to leaving out something simple from the request (like a user agent). 
I'll look into this momentarily and see if I can see what's happening.

**Comment by sterlinganderson** [comment]
I'm also getting a 400 bad request error from nzb.su. This just recently started happening. I wonder if a software update messed something up? I'm on Ubuntu 14.04.

**Comment by evilhero** [comment]
That might have to do with your python version (although there is a bug in the search atm) - what version of python are you currently running? 

Do you have the 'verify ssl' option enabled for either of the providers you're currently having problems with ?

**Comment by sterlinganderson** [comment]
Python 2.7.6. I have the SSL box checked.

**Comment by evilhero** [comment]
Yeah that's the problem then.  Since python 2.7.7 SNI certificate support was used, which allows for certificates of different subdomains to be authenticated properly. Almost every nzb provider (and most torrents) utilize the SNI certificates. 

You need to update your version of python to 2.7.9 (at the very least). Once you do that then you'll be able to use the ssl verification properly and securely.  It's been widely acknowledged that using a lesser version of python is a security risk as it doesn't support proper certificate authentication against SNI certificates.

**Comment by sterlinganderson** [comment]
Hmm. Okay. I need to figure out how to get Python up to that version on Ubuntu 14.04. The Ubuntu packages are pretty behind I guess.

**Comment by evilhero** [comment]
Gent in #1217 as well as a user on the forums both did the following to update theirs to 2.7.11:
sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get upgrade

**Comment by sterlinganderson** [comment]
Fabulous, that did it. Post processing failed on the first comic to download, but that's likely something else entirely.
