### ISSUE TITLE
Mylar log telling me I have no search providers configured

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#1217]
My log shows the following line:

	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.

I have 4 newsnab providers configured with API keys.

**Comment by apastuszak** [comment]
Ok, I had 2 blank search providers.  I manually edited the search providers and got mylar to do a search.  Now it throws this error:

2016-02-25 16:23:02	ERROR	Uncaught exception: Traceback (most recent call last):
File "/home/xxxx/.mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/xxxx/.mylar/mylar/webserve.py", line 1313, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/home/xxxx/.mylar/mylar/search.py", line 249, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/home/xxxx/.mylar/mylar/search.py", line 601, in NZB_SEARCH
if data:
UnboundLocalError: local variable 'data' referenced before assignment
2016-02-25 16:23:02	WARNING	Unable to download torrent from nzb.su [Status Code returned: 400]

**Comment by claym** [comment]
I've noticed when you change the providers, you have to restart before it
picks them up

**Comment by apastuszak** [comment]
I did that.  When I restart Mylar, it looks like it adds back the 2 blank providers.

**Comment by evilhero** [comment]
It looks like it's not retrieving the requested page from the provider properly. Just a few lines prior to that, there should be a search url line followed by what the contents of the page is.. Can you paste in what they are?  Someone else posted a similar issue, and it was returning a 404 status code (page not found)

**Comment by apastuszak** [comment]
Getting an error 400

`016-02-25 16:30:49	WARNING	Unable to download torrent from nzb.su [Status Code returned: 400]
2016-02-25 16:30:49	INFO	



Bad Request`

Your browser sent a request that this server could not understand.

Now, if I turn off nzb.su, it tells me I have no search providers configured.

I'm tempted to blow away the ini and start from scratch.

**Comment by apastuszak** [comment]
Concerned that is says it is unable to download a torrent from an nzb provider.

**Comment by evilhero** [comment]
Whenever you enable/disable providers within mylar, you need to restart Mylar after you save the configuration. This is because the provider_order gets generated on startup only, so enabling/disabling a provider and not having the provider_order regenerated with said provider on/off will cause problems when it goes to search (which is what the 0 providers line is saying basically).

The 'download torrent from an nzb provider' is just a logging message - I copied the log line from the  torrent section (lazy i know), and forgot to change out 'torrent' for 'nzb'. It's not trying to download from a torrent site if that's the message you're getting ;)

The '400' though is a malformed request - I have a slight fix coming that might address this, although I'm not 100% sure atm as I don't have every nzb provider to test against obviously.

Do you have the verify ssl option enabled/disabled for nzb.su ? And what version of python are you currently running Mylar against?

**Comment by apastuszak** [comment]
Python 2.7.6

Verify SSL is enabled.

I disabled nzb.su and dognzb (the next provider on the list) is 
throwing the same 400 error.

**Comment by apastuszak** [comment]
Disabled Verify SSL and it did not make a difference.

**Comment by evilhero** [comment]
Python 2.7.6 can't validate certificates properly that use SNI. And almost every nzb/torrent provider use it based on how they're being hosted. 

Your only option is to upgrade your python to 2 7.9 (at a minimum), as that's when SNI certificate validation was properly introduced (it was introduced in 2.7.7, but had issues as well). 

Once you update python, you'll be able to properly validate the certificates that are SNI and you shouldn't have any other problems like this. 

Note that upgrading to 2.7.9 is considered an important security upgrade and is almost a requirement for users that use applications in Python.

**Comment by apastuszak** [comment]
I'm on Ubuntu 14.04 LTS.  That's probably why my Python is so old.  Let me see what I can do.

**Comment by apastuszak** [comment]
For anyone else experiencing this issue on Ubuntu 14.04, this will get you on Ubuntu 2.7.11:

sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get upgrade

Rebooting now to test mylar

**Comment by apastuszak** [comment]
New issue now.

Teh cbr to cbz conversion is causing the file to just disappear.  And I am getting this warning on my log file:

	WARNING	[META-TAGGER][WARNING] Make sure that you have configparser installed.

I know I have configparser installed.

**Comment by apastuszak** [comment]
just did a `sudo cp /usr/bin/python2.7 $(which python2.7)`  That fixed issues I was having with some other apps.  Testing Myalr now.

**Comment by apastuszak** [comment]
Ok, the download issue is definitely fixed now.  The only issue now is post processing seems to delete the file.  Definitely have configparser installed.

When I do a sudo pip install configparser, it comes back with:

Requirement already satisfied (use --upgrade to upgrade): configparser in /usr/lib/python2.7/dist-packages

**Comment by apastuszak** [comment]
Ran  the following two command inside of /usr/lib/python2.7:

sudo ln -s ./dist-packages/configparser.pyc configparser.pyc
sudo ln -s ./dist-packages/configparser.py configparser.py

Configparser issue resolved and comics are processing properly now.  Thanks for your help!  Closing the issue.
