### ISSUE TITLE
Journey Into Mystery 2011 throws traceback exception

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1218]
When I try to add the title: Journey Into Mystery (2011), I get uncaught exception errors from CherryPy.

Here is the log:

25-Feb-2016 23:43:51 - INFO    :: Thread-12 : Now adding/updating: Journey into Mystery
25-Feb-2016 23:43:51 - INFO    :: Thread-12 : Sucessfully retrieved details for Journey into Mystery
25-Feb-2016 23:44:01 - INFO    :: RSSCHECK : RSS Feed Check was last run at : 2016-02-25 23:42:20
25-Feb-2016 23:44:01 - WARNING :: Thread-12 : [DIRECTORY-CHECK] Could not find comic directory: y:\comics\Journey into Mystery (2011)
25-Feb-2016 23:44:01 - INFO    :: Thread-12 : [DIRECTORY-CHECK] Creating comic directory (0777) : y:\comics\Journey into Mystery (2011)
25-Feb-2016 23:44:04 - INFO    :: Thread-12 : Image header check: jpeg
25-Feb-2016 23:44:04 - INFO    :: Thread-12 : Successfully retrieved cover for Journey into Mystery
25-Feb-2016 23:44:04 - INFO    :: Thread-12 : previous version detected as None - seeing if update required
25-Feb-2016 23:44:04 - INFO    :: Thread-12 : updated version to :v1
25-Feb-2016 23:44:36 - INFO    :: Thread-12 : Sucessfully retrieved issue details for Journey into Mystery
25-Feb-2016 23:44:37 - INFO    :: SEARCH : <?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/"><channel><newznab:response offset="0" total="0"/></channel></rss>
25-Feb-2016 23:44:37 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
25-Feb-2016 23:45:39 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\importer.py", line 531, in addComictoDB
    issuedata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\importer.py", line 1177, in updateissuedata
    weeklyissue_check = annual_check(comicname, SeriesYear, comicid, issuetype, issuechk, weeklyissue_check)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\importer.py", line 1486, in annual_check
    sresults, explicit = mb.findComic(annComicName, mode, issue=None, explicit='all')#,explicit=True)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 144, in findComic
    searched = pullsearch(comicapi, comicquery, 0, explicit, type)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 92, in pullsearch
    dom = parseString(r.content) #(data)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0

25-Feb-2016 23:45:40 - INFO    :: SEARCH : <?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/"><channel><newznab:response offset="0" total="0"/></channel></rss>
25-Feb-2016 23:45:40 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
25-Feb-2016 23:46:05 - WARNING :: CP Server Thread-4 : Journey into Mystery has not finished loading. Nulling some values so things display properly until they can populate.
25-Feb-2016 23:46:22 - INFO    :: Thread-13 : Starting update for 1 active comics
25-Feb-2016 23:46:22 - INFO    :: Thread-13 : [DIRECTORY-CHECK] Found comic directory: y:\comics\Journey into Mystery (2011)
25-Feb-2016 23:46:42 - INFO    :: SEARCH : <?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/"><channel><newznab:response offset="0" total="0"/></channel></rss>
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Could not find Issue 5 of Web of Spider-Man annual(1985) using NewsDemon [api]
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Finished searching via :api. Issue not found - status kept as Wanted.
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Issue Title given as : give me a hand, future max!
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Annual issue search detected. Appending to issue #
25-Feb-2016 23:46:42 - INFO    :: SEARCH : search provider order is ['Experimental', 'newznab:NewsDemon']
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Web of Spider-Man annual issue: 1 (1985) using experimental [RSS]
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Could not find Issue 1 of Web of Spider-Man annual(1985) using experimental [rss]
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Web of Spider-Man annual issue: 1 (1985) using NewsDemon(newznab) [RSS]
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Could not find Issue 1 of Web of Spider-Man annual(1985) using NewsDemon [rss]
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Finished searching via :rss. Issue not found - status kept as Wanted.
25-Feb-2016 23:46:42 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Web of Spider-Man annual issue: 1 (1985) using experimental
25-Feb-2016 23:46:45 - INFO    :: SEARCH : Could not find Issue 1 of Web of Spider-Man annual(1985) using experimental [api]
25-Feb-2016 23:46:45 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Web of Spider-Man annual issue: 1 (1985) using NewsDemon (newznab)
25-Feb-2016 23:46:45 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
25-Feb-2016 23:46:55 - INFO    :: Thread-13 : Now adding/updating: Journey into Mystery
25-Feb-2016 23:46:55 - INFO    :: Thread-13 : Sucessfully retrieved details for Journey into Mystery
25-Feb-2016 23:47:15 - INFO    :: Thread-14 : [FILE-RESCAN] Now checking files for Journey into Mystery (2011) in y:\comics\Journey into Mystery (2011)
25-Feb-2016 23:47:16 - INFO    :: Thread-14 : [FILE-RESCAN] Now checking files for Journey into Mystery (2011) in :Journey into Mystery (2011)
25-Feb-2016 23:47:16 - WARNING :: Thread-14 : [FILE-RESCAN] An error occured trying to get the relevant issue data. This is probably due to the series not having proper issue data.
25-Feb-2016 23:47:16 - WARNING :: Thread-14 : [FILE-RESCAN] you should either Refresh the series, and/or submit an issue on github in regards to the series and the error.
25-Feb-2016 23:47:42 - WARNING :: CP Server Thread-2 : Journey into Mystery has not finished loading. Nulling some values so things display properly until they can populate.
25-Feb-2016 23:47:48 - INFO    :: SEARCH : <?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/"><channel><newznab:response offset="0" total="0"/></channel></rss>
25-Feb-2016 23:47:48 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
25-Feb-2016 23:47:50 - INFO    :: MAIN : Received signal: restart
25-Feb-2016 23:47:50 - INFO    :: MAIN : Aborting all threads
25-Feb-2016 23:47:50 - INFO    :: MAIN : Waiting for the DB UPDATE thread to exit
25-Feb-2016 23:47:51 - INFO    :: MAIN : Waiting for the SEARCH thread to exit
25-Feb-2016 23:47:57 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\updater.py", line 270, in dbUpdate
    cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\importer.py", line 222, in addComictoDB
    sresults, explicit = mb.findComic(annComicName, mode, issue=None, explicit='all')#,explicit=True)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 144, in findComic
    searched = pullsearch(comicapi, comicquery, 0, explicit, type)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 92, in pullsearch
    dom = parseString(r.content) #(data)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0

**Comment by bguidotti** [comment]
Then, after a while, Mylar stops responding and throws this error no matter what I do until I restart the process:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\webserve.py", line 217, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=issue)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 144, in findComic
    searched = pullsearch(comicapi, comicquery, 0, explicit, type)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\mb.py", line 92, in pullsearch
    dom = parseString(r.content) #(data)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0
Powered by CherryPy 3.2.0

**Comment by evilhero** [comment]
Pretty sure this is comicvine taking a dump.  The min site is throwing a 500 in a normal web browser and I  can't even hit the api. 

I'd give it a few hrs and try again and see if they were able to fix the problem.

**Comment by evilhero** [comment]
This should be working now as CV is back up... Can you confirm?

**Comment by bguidotti** [comment]
Yes, this was resolved.  Completely a ComicVine problem.  Thanks.
