### ISSUE TITLE
Can't get series

### ISSUE THREAD

**Issue by andrewcfitz** [evilhero/mylar#1221]
I've tried this for a few different series', but I am getting this error.

02-Mar-2016 19:15:59 - INFO    :: Thread-15 : Starting update for 1 active comics
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : Refreshing :85421
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : CV_OneTimer option enabled...
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : Gathering the status of all issues for the series.
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : No issue data available. This is Whack.
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : Deleting all issue data.
02-Mar-2016 19:15:59 - DEBUG   :: Thread-15 : Refreshing the series and pulling in new data using only CV.
02-Mar-2016 19:15:59 - ERROR   :: Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "/opt/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Mylar/mylar/updater.py", line 270, in dbUpdate
    cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload)
  File "/opt/Mylar/mylar/importer.py", line 86, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "/opt/Mylar/mylar/filechecker.py", line 1353, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by evilhero** [comment]
Did you happen to set a comic location within the mylar configuration (2nd tab)? 

Mylar needs to know where to create/store the series it will be watching, so you need to specify it. Then save and restart mylar for the settings to take effect.
