### ISSUE TITLE
can I add new provider ? t411 !

### ISSUE THREAD

**Issue by solspire** [evilhero/mylar#1224]
Hello,
I would like add 1 provider to mylar.
KAT isn't french and i can't find lot of things..
Is it possible add http://www.t411.ch/ ? How ?
Thinks

**Comment by evilhero** [comment]
Try using jackett with mylar. I believe it might have support for t411 - otherwise if it doesn't, then no it can't be added to mylar unless someone can create the code for it as I don't have the time to decipher the website.

**Comment by solspire** [comment]
Thinks for the clue. Unfortunately t411 does not seem to be support at this moment.
I had post issues for that in jackett page.

Other thing, In "This Week" in mylar, I have lot of things (not interest me) but I would like only the same comics of my database (like Schedule in sickrage). Is it a normaly work to have comics in this week whereas aren't in my comics database ?

**Comment by evilhero** [comment]
Yes it's showing the comics that are coming out for the current week.  It shows them all in case people aren't aware of certain issues coming out or they just want to grab one issue instead of watching an entire series. 

If you want to see issue for the week just for your own watch list, go to the Wanted tab and at the bottom of the page you'll see an Upcoming tab.

**Comment by solspire** [comment]
The synology package of jackett doesn't have T411, only private tracker ...shit !
Any suggestion for use Torznab option with thing work with t411 ?

**Comment by solspire** [comment]
hello, any news for add t411.si to mylar ?
I see option 32p and torznab bur I don't understand exaxtly what is it.
I have mylar on Nas synology
I would like work mylar with t411.si provider
Thinks for help

**Comment by evilhero** [comment]
Your best bet is to use jackett as that  has some support for t411 now from the looks of it. 

You use jackett with mylar as a torznab provider. Paste in the url link it gives in jackett when you add t411 and other info and that's it. Although of stuff isn't posted with proper naming it's not going to get downloaded as it has to be name parsed for matches (as opposed to movies / tv shows that lookup by an exact ID #)

**Comment by solspire** [comment]
Unfortunately T411.si does not work on Jacckett ...yet
