### ISSUE TITLE
/logs times out

### ISSUE THREAD

**Issue by chromerobv** [evilhero/mylar#1227]
when i look at the logs in the webui it will time out after a while. it seems like the log is huge and it is trying to load the whole thing. i see no way of clering the log. in settings i have the log size set to default. i have even tried to lower that number but it seems to make no difference to what shows in /logs. i even went to far as to delete the logs in /var/db/mylar/logs and it still makes no difference.

**Comment by evilhero** [comment]
This should be resolved in the development build. The log pages will now load only what it needs to display for the current log page you're viewing. 

A verbose mode (-v on startup), as well as an instant verbose toggle in the logs tab within mylar are also available in the development build to help with some logging problems.

**Comment by chromerobv** [comment]
nice! ty
