### ISSUE TITLE
Traceback error after mass import - move files. 

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#1238]
I just updated to the new development update and tried importing some books when I saw this traceback error. 

08-Apr-2016 17:51:31 - ERROR :: Thread-19 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\Development\mylar\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Mylar\Development\mylar\mylar\importer.py", line 589, in addComictoDB
    moveit.movefiles(comicid, comlocation, ogcname)
  File "C:\Mylar\Development\mylar\mylar\moveit.py", line 18, in movefiles
    logger.fdebug("Issue :" + impr['IssueNumber'])
TypeError: cannot concatenate 'str' and 'NoneType' objects

Traceback (most recent call last):
  File "C:\Mylar\Development\mylar\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Mylar\Development\mylar\mylar\importer.py", line 589, in addComictoDB
    moveit.movefiles(comicid, comlocation, ogcname)
  File "C:\Mylar\Development\mylar\mylar\moveit.py", line 18, in movefiles
    logger.fdebug("Issue :" + impr['IssueNumber'])
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
It shouldn't have gotten that far in the process with no issue number being present (that's what that error is saying). 

Are you using an existing import scan that was done previous to the upgrade? A ton of stuff changed in the background, so you would need to flush the existing imports (button at top of import results screen), and then reimport again. 

If you did all that already, can you look a few lines up from that error in your log (verbose logging required) to see what the filename is, and or series/issue number?

**Comment by Nobrumski** [comment]
It looks like that log is already wiped out. I may not have flushed the imports. I will keep an eye out for the error again. All my books have issue numbers though.

**Comment by evilhero** [comment]
I have a feeling it may have been from a previous import and it messed up some values because of it. There's going to be a constant wave of fixes/improvements to the import process over the next month (at least), so if it is an issue with the new process hopefully someone will be able to provide a log showing what's happening.
