### ISSUE TITLE
comictagger gives: Sorry is not a comic archive

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#1240]
Since I last updated Mylar none of the comics are being post-processed by comictagger. Mylar log shows:

09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] dirName:/share/media/comics.temp
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : ComicTagger Path location for internal comictagger.py set to : /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/comictagger.py
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] UNRAR path set to : /usr/bin/unrar
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] Filename is : /share/media/comics.temp/Black Panther 001 (2016).cbr
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] Paths / Locations:
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] scriptname : Mylar.py
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] downloadpath : /share/media/comics.temp
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] sabnzbdscriptpath :
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] comicpath : /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] unrar_folder : /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa/unrard
09-Apr-2016 20:17:15 - DEBUG   :: Thread-12 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] ComicTagger 1.20.0 [ninjas.walk.alone / SHURIKEN]
Modified version of ComicTagger (Copyright (c) 2012-2014 Anthony Beville)
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) being used - using personal ComicVine API key supplied via mylar.
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] CR Tagging enabled.
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] CBL Tagging enabled.
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] Enabling ComicTagger script: ['/opt/bin/python2.7', '/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa/Black Panther 001 (2016).cbr']
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] Executing command: ['/opt/bin/python2.7', '/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/comictagger.py', '-e', '--delete-rar', u'/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa/Black Panther 001 (2016).cbr']
09-Apr-2016 20:17:18 - DEBUG   :: Thread-12 : [META-TAGGER] Absolute path to script: /opt/bin/python2.7
09-Apr-2016 20:17:22 - INFO    :: Thread-12 : Sorry, but /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa/Black Panther 001 (2016).cbr  is not a comic archive!

09-Apr-2016 20:17:22 - INFO    :: Thread-12 : None
09-Apr-2016 20:17:22 - WARNING :: Thread-12 : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/ and/or the location where Mylar is trying to tag the files from.
09-Apr-2016 20:17:22 - DEBUG   :: Thread-12 : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without tagging...

Obviously the permissions are ok and it's been working with the previous version. If I run the comictagger from command line it gives the same error:

/opt/bin/python2.7 /share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/comictagger.py -v -e --delete-rar Black\ Panther\ 001\ \(2016\).cbr
Sorry, but Black Panther 001 (2016).cbr  is not a comic archive!

I can open the file using comicrack and also in the server using unrar:

[/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cache/mylar_T5X7fa] # unrar l Black.Panther.001.2016.cbr

UNRAR 3.60 freeware      Copyright (c) 1993-2006 Alexander Roshal

Archive Black.Panther.001.2016.cbr

 Name             Size   Packed Ratio  Date   Time     Attr      CRC   Meth Ver
-------------------------------------------------------------------------------
 Black Panther (2016-) 001-000.jpg  1376969  1366451  99% 06-04-16 07:13  .....A.   F035ED23 m3f 2.9
 Black Panther (2016-) 001-001.jpg   606464   562695  92% 06-04-16 07:13  .....A.   A79A11DF m3f 2.9
 Black Panther (2016-) 001-002.jpg  1313750  1286237  97% 06-04-16 07:13  .....A.   551A617F m3f 2.9
 Black Panther (2016-) 001-003.jpg  1707557  1694118  99% 06-04-16 07:13  .....A.   ACDBE8E2 m3f 2.9
 Black Panther (2016-) 001-004.jpg  1508018  1468975  97% 06-04-16 07:13  .....A.   1DF17182 m3f 2.9
 Black Panther (2016-) 001-005.jpg  1745414  1711555  98% 06-04-16 07:13  .....A.   5AC0E042 m3f 2.9
 Black Panther (2016-) 001-006.jpg  1657048  1625279  98% 06-04-16 07:13  .....A.   EFB8BD5A m3f 2.9
 Black Panther (2016-) 001-007.jpg  1291813  1266855  98% 06-04-16 07:13  .....A.   35AB486E m3f 2.9
 Black Panther (2016-) 001-008.jpg   999898   903739  90% 06-04-16 07:13  .....A.   7EE6535D m3f 2.9
 Black Panther (2016-) 001-009.jpg  1682377  1648791  98% 06-04-16 07:13  .....A.   423B25A1 m3f 2.9
 Black Panther (2016-) 001-010.jpg  1736929  1692613  97% 06-04-16 07:13  .....A.   01320180 m3f 2.9
 Black Panther (2016-) 001-011.jpg  1606808  1572645  97% 06-04-16 07:13  .....A.   15024374 m3f 2.9
 Black Panther (2016-) 001-012.jpg  1695740  1669190  98% 06-04-16 07:13  .....A.   0DD28131 m3f 2.9
 Black Panther (2016-) 001-013.jpg  1493591  1453341  97% 06-04-16 07:13  .....A.   68F35633 m3f 2.9
 Black Panther (2016-) 001-014.jpg  1348125  1311470  97% 06-04-16 07:13  .....A.   6BF48276 m3f 2.9
 Black Panther (2016-) 001-015.jpg  1496536  1459837  97% 06-04-16 07:13  .....A.   0E321DE0 m3f 2.9
 Black Panther (2016-) 001-016.jpg  1669632  1632822  97% 06-04-16 07:13  .....A.   1E28C5F5 m3f 2.9
 Black Panther (2016-) 001-017.jpg  1740644  1713796  98% 06-04-16 07:13  .....A.   FB4E0B5F m3f 2.9
 Black Panther (2016-) 001-018.jpg  1308753  1274818  97% 06-04-16 07:13  .....A.   6F1A370F m3f 2.9
 Black Panther (2016-) 001-019.jpg  1616629  1584422  98% 06-04-16 07:13  .....A.   D915ED27 m3f 2.9
 Black Panther (2016-) 001-020.jpg  1739195  1703071  97% 06-04-16 07:13  .....A.   74A59B12 m3f 2.9
 Black Panther (2016-) 001-021.jpg  1263173  1226716  97% 06-04-16 07:13  .....A.   6775A89B m3f 2.9
 Black Panther (2016-) 001-022.jpg  1340440  1304188  97% 06-04-16 07:13  .....A.   ACB80B5D m3f 2.9
 Black Panther (2016-) 001-023.jpg  1666558  1627471  97% 06-04-16 07:13  .....A.   A49682D0 m3f 2.9
 Black Panther (2016-) 001-024.jpg  1451393  1424660  98% 06-04-16 07:13  .....A.   5A2595AB m3f 2.9
 Black Panther (2016-) 001-025.jpg  1224073  1153175  94% 06-04-16 07:13  .....A.   EB35453E m3f 2.9
 Black Panther (2016-) 001-026.jpg  1182201  1100651  93% 06-04-16 07:13  .....A.   D3E7D50D m3f 2.9
 Black Panther (2016-) 001-027.jpg  1507908  1479366  98% 06-04-16 07:13  .....A.   A16078A2 m3f 2.9
 Black Panther (2016-) 001-028.jpg  1390104  1312264  94% 06-04-16 07:13  .....A.   7EC2E6E9 m3f 2.9
 Black Panther (2016-) 001-029.jpg  1794340  1724339  96% 06-04-16 07:13  .....A.   A208A8DD m3f 2.9
 Black Panther (2016-) 001-030.jpg   982038   901340  91% 06-04-16 07:13  .....A.   7C9FA523 m3f 2.9
 z.jpg         1687379  1684482  99% 06-04-16 07:13  .....A.   9E8177C5 m3f 2.9
 Black Panther 001 (2016) (Digital) (BlackManta-Empire)        0        0   0% 06-04-16 07:13  .D.....   00000000 m0  2.0
-------------------------------------------------------------------------------
   33         46831497 45541372  97%

python is: 2.7.11
comictagger is: 1.20.0
Mylar: Version: 8082a61f17100f022a3daa754c9f7a764ecf7a38

Any assistance will be appreciated.

Thanks.

**Comment by cesalo** [comment]
It seems it just affects CBR. Just tried with a CBZ and it worked. No idea why is failing for CBRs.

**Comment by evilhero** [comment]
This probably has something to do with your version of UnRAR on your system. CT uses pyunrar to link to your unrar executable, and from what I remember if it was 5.30 there were issues uncompressing due to invalidly formatted datestamps - they were in fact OK, but there was a change that occurred in 5.30 that reversed the dates causing some problems. 

I was under the impression this was fixed in development (and master recently too).

**Comment by cesalo** [comment]
Thanks a lot for the tip. I upgraded UNRAR to 5.31 (QNAP entware) and now we are back to business.
This is the full version just in case somebody else encounters the same issue:

UNRAR 5.31 freeware      Copyright (c) 1993-2016 Alexander Roshal

Thanks again. Now I can disable the workaround I put in place to convert everything to CBZ.
