### ISSUE TITLE
Processing issue

### ISSUE THREAD

**Issue by stoofz** [evilhero/mylar#1241]
Having a error when processing files

ERROR   Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 993, in Process
dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
File "C:\Mylar\mylar\helpers.py", line 1711, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "C:\Python27\lib\genericpath.py", line 57, in getsize
return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'M:\Downloads\complete\comics\comicbooknamehere.cbr'

**Comment by evilhero** [comment]
There was a bug just found that if you don't have the checkbox enabled for sabnzbd and mylar being on seperate machines, but you have a value set for the sabnzbd download location (it appears when you enable the option), it incorrectly takes the sabnzbd download location. 

Can you confirm that you don't have a value for that option for sabnzbd within the mylar configuration? 

Otherwise I would need to see the debug logs for a post-processing run to help me figure out what's happening.

**Comment by stoofz** [comment]
The Sab settings are empty as I have just switched over to NZBGet, the value and option for the download location is unchecked and location blank.

**Comment by evilhero** [comment]
Can you enable verbose logging and do a manual post-processing run again and paste in the log showing up until the error occurs?

Im assuming this is a manual post-processing run here of course.

**Comment by stoofz** [comment]
10-Apr-2016 21:05:10 - INFO    :: CP Server Thread-3 : Starting postprocessing for : Manual Run
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] nzb name: Manual Run
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] nzb folder: M:\Downloads\complete\comics
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] Not using SABnzbd : Manual Run
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] Manual Run initiated
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : there are 2 files.
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : [FILENAME]: comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Scanner group tag discovered: Minutemen-InnerPhDemons
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : checking date : 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : date: 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : datecheck: [{'date': '2009', 'position': 3, 'mod_position': 16}]
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : sctd: 2016
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : year verified as : 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : year verified as: 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : highest_series_position: 3
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '001', 'mod_position': 12}]
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : issue verified as : 001
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : series title possibly: comic book
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : [FILENAME]: comic book 002 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Scanner group tag discovered: Minutemen-InnerPhDemons
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : checking date : 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : date: 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : datecheck: [{'date': '2009', 'position': 3, 'mod_position': 16}]
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : sctd: 2016
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : year verified as : 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : year verified as: 2009
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : highest_series_position: 3
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '002', 'mod_position': 12}]
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : issue verified as : 002
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : series title possibly: comic book
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : {'comiclist': [{'issue_number': '001', 'sub': None, 'issue_year': '2009', 'comiclocation': u'M:\\Downloads\\complete\\comics', 'scangroup': 'Minutemen-InnerPhDemons', 'series_name': 'comic book', 'comicfilename': 'comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr', 'series_volume': None}, {'issue_number': '002', 'sub': None, 'issue_year': '2009', 'comiclocation': u'M:\\Downloads\\complete\\comics', 'scangroup': 'Minutemen-InnerPhDemons', 'series_name': 'comic book', 'comicfilename': 'comic book 002 (2009) (digital) (Minutemen-InnerPhDemons).cbr', 'series_volume': None}], 'comiccount': 2}
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : I have located 2 files that I should be able to post-process. Continuing...
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Dynamic-ComicName: comicbook
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : Series_Name: comic book --- WatchComic: comic book
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [MATCH: comic book] comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING][SUCCESSFUL MATCH: comic book-27671] Match verified for comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Dynamic-ComicName: comicbook
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : Series_Name: comic book --- WatchComic: comic book
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [MATCH: comic book] comic book 002 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING][SUCCESSFUL MATCH: comic book-27671] Match verified for comic book 002 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] There are 2 files found that match on your watchlist, 0 do not match anything and will be ignored.
10-Apr-2016 21:05:10 - DEBUG   :: Thread-16 : [POST-PROCESSING] Now Checking if the issue also resides in one of the storyarc's that I am watching.
10-Apr-2016 21:05:10 - INFO    :: Thread-16 : [DUPECHECK] Duplicate check for M:\Downloads\complete\comics\comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr
10-Apr-2016 21:05:10 - ERROR   :: Thread-16 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\PostProcessor.py", line 993, in Process
    dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
  File "C:\Mylar\mylar\helpers.py", line 1711, in duplicate_filecheck
    filesz = os.path.getsize(filename)
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'M:\\Downloads\\complete\\comics\\comic book 001 (2009) (digital) (Minutemen-InnerPhDemons).cbr'

**Comment by stoofz** [comment]
It occurs both manual and auto

**Comment by evilhero** [comment]
Does the file exist within that actual directory - M:\Downloads\complete\comics, or is the comic located within a subdirectory within that directory?

**Comment by stoofz** [comment]
Each issues is automatically extracted in to its own folder inside  M:\Downloads\complete\comics

 i.e.
 M:\Downloads\complete\comics\comicbook.001.2010.digital\comicbook.001.2010.digital.cbr

I just moved a comicbook.cbr outside its own dir into M:\Downloads\complete\comics and it was processed correctly

**Comment by evilhero** [comment]
Yep, that's the bug I found the other day and started working through the process - but because of the way everything integrates into the filechecker module now, it's taking me abit of time to go through every module to make sure things are working as they should.

I'm working on it atm (still lol) - expect a commit to fix this probably in an hour or two.

**Comment by stoofz** [comment]
Awesome! Thanks for all the work on Mylar too!

**Comment by lodasi** [comment]
This is still an issue.

**Comment by evilhero** [comment]
@lodasi : Can I ask what the filename was that you were having problems with ?
