### ISSUE TITLE
ComicRN.py hanging in SABNZB

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1245]
Hey, starting today or yesterday, the ComicRN.py script has failed to complete when being run by SABNZB.  It just runs forever.  I'm assuming something has changed in the most recent update.  I'm not sure what I should provide you with here to help, so just let me know and I'll post it!
THanks as always!

**Comment by sbcrumb** [comment]
Not sure if it is the same but this is happening to me in Nzbget as well. Just hangs and never moves on to the next one.

**Comment by thewindupboy** [comment]
That is exactly what's happening to me.

**Comment by tjiddy** [comment]
I am also getting the hanging during post processing after being downloaded from nzbget.  The mylar logs show this:
'''
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/PostProcessor.py", line 1045, in Process
return self.Process_next(comicid, issueid, issuenumOG)
File "/opt/mylar/mylar/PostProcessor.py", line 1681, in Process_next
updater.forceRescan(comicid, module=module)
File "/opt/mylar/mylar/updater.py", line 1237, in forceRescan
sys.exit()
NameError: global name 'sys' is not defined
'''
I noticed that updater.py was missing an 
'''import sys'''

After adding that, the nzbget queue clears, but all in pp-failure.  Looking in the mylar logs this time revealed: 
'''
INFO    :: CP Server Thread-3 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
13-Apr-2016 11:34:18 - INFO    :: CP Server Thread-3 : Starting postprocessing for : Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /mnt/jabba/downloads/complete/comics/Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] Not using SABnzbd
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] Using NZBGET
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] NZB name as passed from NZBGet: Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] NZBGET Download folder option enabled. Directory set to : /mnt/jabba/downloads/complete/comics/Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [NZBNAME]: Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Spider-Gwen v2 006 2016 Digital BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] Failure - could not locate nzbfile initially
13-Apr-2016 11:34:18 - DEBUG   :: Post-Processing : [POST-PROCESSING] Trying to locate nzbfile again with nzbname of : Spider-Gwen.v2.006.2016.Digital.BlackManta-Empire
13-Apr-2016 11:34:18 - ERROR   :: Post-Processing : [POST-PROCESSING] Unable to locate downloaded file to rename. PostProcessing aborted.
'''

**Comment by mightyflub** [comment]
Does anyone know how to clear my sab queue of this? I've turned off the script for that category until it gets fixed but I've got a number of download stuck in the queue

**Comment by mightyflub** [comment]
Sorted it. Shut down Mylar and killed the current issue of the script. Now the rest are happily failing. I'll tidy up manually today :)

**Comment by evilhero** [comment]
Yep this is my fault - late last night I pushed a few quick fixes and forgot to remove the sys.exit line (it was just for testing purposes). I'll push out a fix for it momentarily. This would effectively kill the post-processing run of anything, as well as not update the file count checks when doing a recheck files (which occurs at the end of post-processing).

@tjiddy: What probably is happening is you're trying to post-process the issues again that were already removed from the nzb log. The best bet is to clear your nzblog (history tab, upper right button), which will cleaer out all the logs pertaining to your unfinished downloads. Then try and download again and you should be all in the clear.

**Comment by mightyflub** [comment]
Thanks evil hero. Much appreciated.

**Comment by mightyflub** [comment]
I think I've gotten my linux install of mylar confused with this. It thinks I'm 40 commits ahead of the development branch. Is there any easy way to reset it back to what it should be without losing my settings?

**Comment by mightyflub** [comment]
Never mind lol. 
git fetch --all
git reset --hard origin/development seems to have done the trick. At least it appears to have :)

**Comment by thewindupboy** [comment]
Downloaded the newest release, working fine for me now.  Thanks!  
(I won't close this ticket, obvs, since others are involved)

**Comment by mightyflub** [comment]
I'm not quite there yet. I think I've gotten my install in a screwy state. It now says it's up to date but hasn't pulled down the change to updater.py

**Comment by mightyflub** [comment]
Ok. I can't read. Sorted now :)

**Comment by tjiddy** [comment]
working for me now!  thank you for the quick fix evilhero!

**Comment by cclick815** [comment]
I'm running the current commit and still getting the following error when the ComicRN.py runs.

2016-04-13 23:02:26	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/PostProcessor.py", line 1045, in Process
return self.Process_next(comicid, issueid, issuenumOG)
File "/opt/Mylar/mylar/PostProcessor.py", line 1681, in Process_next
updater.forceRescan(comicid, module=module)
File "/opt/Mylar/mylar/updater.py", line 784, in forceRescan
tmpval = tval.listFiles()
File "/opt/Mylar/mylar/filechecker.py", line 171, in listFiles
'sub': runresults['sub'],
KeyError: 'sub'
2016-04-13 23:02:26	INFO	[NO MATCH] New Mutants v2 003 2003.cbz [WATCHLIST:New Mutants]
2016-04-13 23:02:26	INFO	Series_Name: new mutants 003 --- WatchComic: new mutants
2016-04-13 23:02:26	INFO	[FILENAME]: New Mutants v2 003 2003.cbz
2016-04-13 23:02:26	INFO	there are 4 files.

**Comment by evilhero** [comment]
@cclick815 : different issue entirely than OP, but fix for that error is coming shortly..
