### ISSUE TITLE
Manual Post-Processing Deletes Temporary Folder

### ISSUE THREAD

**Issue by cscattaglia917** [evilhero/mylar#1251]
Hello,

I have just begun using Mylar - thank you for the excellent software.  It really helps keep track of my collection. 
I'm on the dev build, figured I'd throw that out there as I frequently see you recommending it to people since there is frequent work being done on it.

I setup Mylar to post-process a monitored directory that stores "incomplete comics" at a directory called Comics-incomplete.

This works well, however, Mylar removes the Comics-incomplete directory after it post-processes, if there are no more files left in the directory.  I don't think this is intentional, correct? This forces me to recreate that Comics-incomplete folder so that my cronjob has a place to move completed torrents/manual downloads etc. 

Log snippet from the "Tidying up" process after a successful post-process:
2016-04-14 11:28:36 DEBUG   [POST-PROCESSING] Tidying up. Deleting folder : /mnt/Pool/Content/Comics-incomplete

Log snippet now that I have touched a test file in my Comics-incomplete folder so that Mylar can not remove the folder:
2016-04-14 11:36:46 DEBUG   [POST-PROCESSING] Failed to remove temporary directory (/mnt/Pool/Content/Comics-incomplete) - Processing will continue, but manual removal is necessary

For now, I will just keep my little touch test file in Comics-incomplete as I can deal with that little warning in the logs - monitored directory post processing is still working as intended, but I wanted to let you know about this as I don't think this is intentional.

Thanks,

**Comment by evilhero** [comment]
Well it depends on what path you're designating to monitor in the Folder Monitor seciton. 

If it's a sub-directory located within the monitored folder, then it will remove it when post-processing is completed. This is normal behaviour for many automated apps, as a lot of users don't want empty directories (usually when downloading via sab/nzbget the downloaded files get placed within their own subdirectories).

If the folder that's being monitored (/mnt/Pool/Content/Comics-incomplete) is the one that's being deleted, then that is not supposed to happen.

**Comment by cscattaglia917** [comment]
Hey evilhero,

The folder I have designated to monitor is:/mnt/Pool/Content/Comics-incomplete/ and that is the one that gets deleted.  If there are sub-directories inside that folder, they do get removed during post-processing, which is completely understandable.

But if the post-processing files are just inside Comics-incomplete, the entire Comics-incomplete folder will be removed when there are no more files inside it.

I am sure I can reproduce/provide more detailed logs if you would like.

**Comment by evilhero** [comment]
Yep, then that's definitely not supposed to happen.

Do the series that are in the comics-incomplete folder exist in your watchlist, or are they one-off downloads or from a story-arc ? (it matters, cause there are a few different types and they get tidied up different ways)

**Comment by cscattaglia917** [comment]
They are standard series(not story arcs) that exist in my watchlist, snatched using Mylar, downloaded with Deluge and then moved to Comics-incomplete.

**Comment by cscattaglia917** [comment]
Hey Evilhero,

Updated to the latest commit, deleted my placeholder "touch" file, and had Mylar snatch a comic on my watchlist.  Post-processing without removing the Comics-incomplete folder was successful.

Thanks!
