### ISSUE TITLE
Error when trying to download new issues

### ISSUE THREAD

**Issue by infected36** [evilhero/mylar#1254]
Hey, for some reason, something weird happens every time I try to download new issues. It started a few days ago I think, but I'm pretty sure a some issues still download. Anyway, I've attached a crop of what happens on the Mylar window when I either press Force Check or it does so alone.
![capture](https://cloud.githubusercontent.com/assets/13667208/14592297/69fecdc6-04f3-11e6-970e-d1ef060fca41.PNG)

And here's the log:

> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Initiating Search scan at requested interval of 360 minutes.
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Amazing Spider-Man & Silk Spider(Fly) Effect Infinite Comic
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Issue Title given as : chapter one
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : search provider order is ['kat']
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Amazing Spider-Man & Silk: Spider(Fly) Effect Infinite Comic issue: 1 (2016) using KAT [RSS]
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Alternate Search pattern detected...re-adjusting to : Amazing Spider-Man & Silk Spider(Fly) Effect Infinite Comic 2016
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Amazing Spider-Man & Silk Spider(Fly) Effect Infinite Comic issue: 1 (2016) using KAT [RSS]
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Could not find Issue 1 of Amazing Spider-Man & Silk: Spider(Fly) Effect Infinite Comic(2016) using KAT [rss]
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Finished searching via :rss. Issue not found - status kept as Wanted.
> 17-abr-2016 23:18:44 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Amazing Spider-Man & Silk: Spider(Fly) Effect Infinite Comic issue: 1 (2016) using KAT
> 17-abr-2016 23:18:45 - WARNING :: Thread-14 : Error fetching RSS Feed Data from KAT: [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> 17-abr-2016 23:18:45 - ERROR   :: Thread-14 : Uncaught exception: Traceback (most recent call last):
>   File "C:\mylar-master\mylar\logger.py", line 158, in new_run
>     old_run(_args, *_kwargs)
>   File "C:\Python27\lib\threading.py", line 483, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "C:\mylar-master\mylar\search.py", line 1580, in searchforissue
>     foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
>   File "C:\mylar-master\mylar\search.py", line 254, in search_init
>     findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
>   File "C:\mylar-master\mylar\search.py", line 642, in NZB_SEARCH
>     for entry in bb['entries']:
> TypeError: 'NoneType' object is not subscriptable
> 
> 17-abr-2016 23:20:17 - INFO    :: FOLDERMONITOR : delaying thread for 60 seconds to avoid locks.
> 17-abr-2016 23:21:17 - INFO    :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder C:\Users\Medeiros C\Downloads\Complete for newly snatched downloads
> 17-abr-2016 23:21:18 - INFO    :: FOLDERMONITOR : [POST-PROCESSING] No matches for Manual Run ... exiting.
> 17-abr-2016 23:21:18 - INFO    :: FOLDERMONITOR : [FOLDER-CHECK] Finished checking for newly snatched downloads

**Comment by evilhero** [comment]
It could be a few different things, all of which relate to your particular system. 

If you're using a proxy (kat_proxy in config.ini), you need to set the kat_verify to True if it's https, or False if it's not https.

If you're not using a proxy, then you need to set the kat_verify to True. 

You also have to ensure that you're using python 2.7.9+.

(don't edit the config.ini when mylar is running)

**Comment by infected36** [comment]
Sorry for forgetting to reply, I think it may have been the version of python. I updated to 2.7.9 and haven't had the problem since
