### ISSUE TITLE
Searching for StoryArc

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1258]
I have just noticed a slight issue when searching for new story arcs to add to Story Arc management. When searching for _Spider-Women_ it provides no search results even though it shows up on ComicVine (http://comicvine.gamespot.com/spider-women/4045-58802/).

Additionally when searching for a term that provides a lot of search results (in this instance searching for just _spider_) the Mylar webpage produces the following 500 error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/mylar/mylar/webserve.py", line 245, in searchit
    searchresults, explicit = mb.findComic(name, mode=None, issue=None, explicit='explicit', type='story_arc')
  File "/Applications/mylar/mylar/mb.py", line 210, in findComic
    arcinfolist = storyarcinfo(xmlid)
  File "/Applications/mylar/mylar/mb.py", line 437, in storyarcinfo
    if (arcdom.getElementsByTagName('image')[0].childNodes[0].nodeValue) is None:
IndexError: list index out of range

**Comment by evilhero** [comment]
Yeah, that's definitely not working the way it should. I fixed this in my local repo so expect it in the next dev commit coming up shortly.

I might try and add in a feature to add by comicid (but for storyarcs), like what already exists in the main search dialog box. You'd just have to know what the story arc comicid is and then it would auto-add it on it's own...
