### ISSUE TITLE
FEATURE REQUEST: Retry mechanism before marking torrents as failed

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1259]
torcache has been so flakey later, I find myself every wednesday having to clear the failed attempts because torcache is slow at picking up the new torrents.  Would it be possible to try a configurable number of times with a configurable amount of time between retries before marking the torrent as failed?

**Comment by evilhero** [comment]
Can you paste the debug log showing the seach and then the subsequent fail?

I can add in something in regards to retry and timing, but it's going to require a fair chunk of code as I'll have to start storing the retry attempts along with the time differentials and having it run in separate instance (unless I just flip it back into the normal Wanted queue, but it would actually retry the download until X amount of minutes has already transpired)

**Comment by weidercs** [comment]
Log:
```
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : Shhh be very quiet...I'm looking for Spider-Man/Deadpool issue: 4 (2016) using KAT [RSS]
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : prov  : KAT [RSS][3918E7C8BC2AD7D72050C68AB132969FCE75C057]
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : [FAILED_DOWNLOAD_CHECKER] result has a status of FAIL which indicates it is not a good choice to download.
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : [FAILED_DOWNLOAD_CHECKER] continuing search for another download.
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : prov  : KAT [RSS][1452A52779BFD91B0C0F3A9FF681E5DE3750BEDC]
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : Found Spider-Man/Deadpool (2016) issue: 4 using KAT [RSS]
20-Apr-2016 08:56:26 - INFO    :: RSSCHECK : matched on Spider-Man/Deadpool
20-Apr-2016 08:56:27 - WARNING :: RSSCHECK : Unable to download torrent from KAT [Status Code returned: 404]
20-Apr-2016 08:56:27 - ERROR   :: RSSCHECK : Unable to send torrent to client. Assuming incomplete link - sending to Failed Handler and continuing search.
20-Apr-2016 08:56:27 - INFO    :: RSSCHECK : [FAILED-DOWNLOAD] Marking as a Failed Download.
20-Apr-2016 08:56:27 - INFO    :: RSSCHECK : [FAILED-DOWNLOAD] Successfully marked as Failed.
```

I went out to KAT after I saw them and verified that torcache still hadn't updated with them, then about an hour later they were all ok.  Next time I see one, I'll grab the log.

I could see the structure for the failed attempts being more of a 'suggestion' until x number of attempts have been made, then you could add a column to the failed table with "Attempts" that incremented by 1 until whatever the threshold is.  Then just use the existing retry logic as the duration (maybe having them both be configurable would be a bit much), as long as attempts < threshold, try it again.

Thanks, as always, for the great product!
