### ISSUE TITLE
I was 22 versions behind, now I am.... not.....working at all...using experimental

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#1261]
Hi Evilhero,
I am back with an issue after upgrading to the latest version. Before that all was working perfectly for me.
Still using experimental until someone can invite me into 32P.

Here below is the log for a manual search of Superman
24-Apr-2016 15:58:34 - INFO :: Thread-21 : search provider order is ['Experimental']
24-Apr-2016 15:58:34 - DEBUG :: Thread-21 : Initiating Search via : api
24-Apr-2016 15:58:34 - INFO :: Thread-21 : Shhh be very quiet...I'm looking for Superman issue: 49 (2016) using experimental
24-Apr-2016 15:58:34 - DEBUG :: Thread-21 : calpha/cnumber: None / None
24-Apr-2016 15:58:34 - DEBUG :: Thread-21 : RSS Check: None
24-Apr-2016 15:58:34 - DEBUG :: Thread-21 : nzbprov: experimental
24-Apr-2016 15:58:34 - DEBUG :: Thread-21 : comicid: 42986
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : checking search result: Superman Vol 03 049 (2016) (Digital) (HD) (Thornn-Empire).cbr
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : sub:Superman Vol 03 049 (2016) (Digital) (HD) (Thornn-Empire).cbr
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : size given as: 44.2 MB
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Thu, 25 Feb 2016 03:20:06 +0100 is after store date of 2016-02-24
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Entry: Superman Vol 03 049 (2016) (Digital) (HD) (Thornn-Empire).cbr
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Removed extension from filename: .cbr
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Cleantitle: superman vol 03 049 (2016) (digital) (hd) (thornn-empire)
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : volume detected - stripping and re-analzying for volume label.
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Split Volume label detected [03] - ie. Vol 4. Attempting to adust.
24-Apr-2016 15:58:36 - INFO :: Thread-21 : [0, 1, 2, 3, 4, 5, 6, 7]
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Newly finished reformed cleantitle (with NO volume label): superman 049 (2016) (digital) (hd) (thornn-empire)
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : [Vxxx] Version detected as v03
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Newly finished reformed cleantitle (with NO volume label): superman 049 (2016) (digital) (hd) (thornn-empire)
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Cleantitle: superman 049 (2016) (digital) (hd) (thornn-empire)
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 0. Bracket Word: superman 049 
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Comic: superman 049 
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : UseFuzzy is  : None
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : ComVersChk : 3
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Year not given properly formatted but Version detected.Bypassing Year Match.
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 1. Bracket Word: 2016
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : year detected: 2016
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : year looking for: 2016
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 2016 - right years match baby!
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 3. Bracket Word: digital
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : digital edition detected
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 5. Bracket Word: hd
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : 7. Bracket Word: thornn-empire
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : Scanner detected: thornn-empire
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : original nzb comic and issue: superman 049 
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : adjusted nzb comic and issue: superman 049 
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : adjusting from: superman 049  to: 049
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : ['superman', '049'] nzb series word count: 1
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : ['superman'] watchlist word count: 1
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : volume detection commencing - adjusting length.
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : watch comicversion is v3
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : version found: vol
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : vers4year: no
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : vers4vol: v03
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : FCVersion: 
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : DCVersion: 3
24-Apr-2016 15:58:36 - DEBUG :: Thread-21 : SCVersion: 2011
24-Apr-2016 15:58:36 - ERROR :: Thread-21 : Uncaught exception: Traceback (most recent call last):
  File "/Users/me/Myapps/Mylar/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/me/Myapps/Mylar/mylar/mylar/webserve.py", line 1341, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Users/me/Myapps/Mylar/mylar/mylar/search.py", line 254, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/Users/me/Myapps/Mylar/mylar/mylar/search.py", line 1290, in NZB_SEARCH
    elif int(F_ComicVersion) == int(D_ComicVersion) or int(F_ComicVersion) == int(S_ComicVersion):
ValueError: invalid literal for int() with base 10: ''

Traceback (most recent call last):
  File "/Users/me/Myapps/Mylar/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/me/Myapps/Mylar/mylar/mylar/webserve.py", line 1341, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Users/me/Myapps/Mylar/mylar/mylar/search.py", line 254, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/Users/me/Myapps/Mylar/mylar/mylar/search.py", line 1290, in NZB_SEARCH
    elif int(F_ComicVersion) == int(D_ComicVersion) or int(F_ComicVersion) == int(S_ComicVersion):
ValueError: invalid literal for int() with base 10: ''

Hope its something simple.
Thanks again
Pipi

**Comment by evilhero** [comment]
Should be fixed in the latest development commit - was a small problem with the parser not removing the proper wording.

**Comment by pipieye** [comment]
Confirmed working ;)
Thanks for the quick response.
