### ISSUE TITLE
Adding series

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1265]
When adding a new comic, it automatically changes directory folder format. For example

Suicide Squad (2013)     This is how I have it setup to make a directory.

To

Suicide Squad(2013).

I have saved it as $Publisher/$Series ($Year)

But when I add a new comic, changes to $Publisher/$Series($Year). I have saved and restarted to correct it, shows the space, then when I add a new comic. It goes back to no space.

**Comment by evilhero** [comment]
Should be fixed in the dev that just went up a short while ago.
