### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by scc90** [evilhero/mylar#1267]
I am getting the following error.  I tried to change the provider order in the config.ini file but that did not help.  Was working fine before upgrade.  thanks for the help.

ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1313, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/opt/Mylar/mylar/search.py", line 254, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/opt/Mylar/mylar/search.py", line 603, in NZB_SEARCH
logger.info('status code: ' + str(r.status_code))
UnboundLocalError: local variable 'r' referenced before assignment
2016-05-01 13:44:44	WARNING	Error fetching data from newznab: ('Connection aborted.', error(111, 'Connection refused'))

**Comment by evilhero** [comment]
Connection refused would mean that  it can't connect to the nzb provider.  Just prior to that error in the logs it should indicate what the provider was. Either disable it, or delete it and try again. 

If you check the provider_order line, make sure there are no empty entries in there, as it's possible you also have an empty newznab entry.

**Comment by scc90** [comment]
I removed that provider and it working.  Will have to see why the provider is causing an issue.  Thanks.
