### ISSUE TITLE
Issue with Self signed cert.

### ISSUE THREAD

**Issue by richierichman** [evilhero/mylar#1269]
Hi I have a personal indexer running with a self signed cert and I have noticed that Mylar is unable to trust the site or do a RSS lookup I keep getting errors like 
WARNING Error fetching RSS Feed Data from websitename: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
I am unable to do any searches either is there anyway to add the site as a trust to Mylar. It is a trusted site in windows. 
This is my mylar config at the moment running on Windows 10
Configuration Options
Mylar Version: development
-- git build 09f6e32d603a818f3cba9d4f6161049457602eb0.
Python Version : 2.7.11

Any help would be greatly appreciated.
Regards
Richard

**Comment by evilhero** [comment]
For your newznab entry within Mylar that relates to your personal indexer - do you have the Verify SSL option enabled or disabled ?

**Comment by richierichman** [comment]
I have tried to use both options and get the same result. At the moment it is un-ticked to verify ssl.

**Comment by evilhero** [comment]
It might be related to your openssl version that you have attached to python. From a command prompt if you type in : python -c "import ssl; print ssl.OPENSSL_VERSION",  what is the version  response?

**Comment by richierichman** [comment]
Here is my output:
OpenSSL 1.0.2d 9 Jul 2015

**Comment by richierichman** [comment]
Ok now I seem to be getting a different error. I did a re-install of Python and after a reboot I now get  WARNING Error fetching data from newznab: __str__ returned non-string (type Error). Not sure what this means. Thanks again for your help.

**Comment by richierichman** [comment]
WARNING	Error fetching data from newznab: ```__str__``` returned non-string (type Error) 
Looks like github was removing the ```_```.

**Comment by evilhero** [comment]
That seems like it's a problem with the way the requests module is handling the response, although according to some forum posts - it's still throwing back an invalid certificate error. Under normal circumstances, it's a problem with your OpenSSL version and your pyOpenSSL version, as well as what type of encryption support the certificate/site has enabled when dealing out the response (tls1,tls2, sslv2,sslv3,etc)
