### ISSUE TITLE
post-processing failure... no reason provided.

### ISSUE THREAD

**Issue by pironic** [evilhero/mylar#1275]
https://gist.github.com/pironic/cf3e12fa526727472af0d1af4b90ff5a 

Attached is my log file for the manual attempt to run the post-processing of a folder for several comics it can't match. Is this a format issue? Some permission issue? something else?

mylar is running as the user 'sabnzbd' as is sabnzb... and i've even tried `chmod 777 * -r` in the directory before manual post and no luck.

take a look at 

>  09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Saga (2012) - 3.cbr

for example. i have `$Series ($Year) - $Issue` currently set as my format in config, but i only changed it to that after experiencing issues.

is it something i'm doing?

EDIT: I'm running ubuntu 14.10

**Comment by evilhero** [comment]
```
09-May-2016 00:38:34 - INFO    :: Thread-40 : Series_Name: morningglories --- WatchComic: morning glories
09-May-2016 00:38:34 - INFO    :: Thread-40 : Series_Name: invincible --- WatchComic: invincible
09-May-2016 00:38:34 - INFO    :: Thread-40 : Series_Name: lazarus --- WatchComic: lazarus
09-May-2016 00:38:34 - INFO    :: Thread-40 : Series_Name: fatale --- WatchComic: fatale
09-May-2016 00:38:34 - INFO    :: Thread-40 : Series_Name: chew --- WatchComic: chew
```
relates to :
```
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: MorningGlories_vol1_1398374447.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Invincible_vol1_1398382571.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: TheManhattanProjects_vol1_1398374447.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Lazarus_vol1_1398374447.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Revival_vol1_update.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Fatale_vol1_1398374447.cbr
09-May-2016 00:38:34 - INFO    :: Thread-40 : [FILENAME]: Chew_vol1_1398371801.cbr
```
Basically your filenaming structure isn't in a parsable format for Mylar to use. For Mylar to be successful in post-processing (or importing or filechecking, etc) the filename has to contain a valid series title and an issue number (at the very least). It's also helpful for Mylar to include a volume label and or an issue year that will help Mylar best determine if a series belongs to a particular volume/set when there are multiple volumes per series. So having '1398371801' has absolutely no merit in being in a filename as it's not indicative of an issue number, or year. It does however parse the series title and volume correctly, which is what the whole 'Series_Name' -- 'Watchcomic' information line is regarding, it's matching it up to existing series in your watchlist, but not having a valid issue number means it won't get post-processed.

The Saga issue is a parsing issue that I can look at it - typically if a series has the year before the issue number it causes problems (think of series like Spider-Man 2099, or similar types of series where there is a number in the series - it gets confusing to say the least). I think I can get that formatting to work though. I would put your format back to whatever it was before ( '$Series $Issue ($Year)' ?)  - it doesn't have any impact on the actual scanning in of the files for post-processing, but only when it goes to rename the files after a successful scan/post-process.

The remainder of your series either don't exist in your watchlist, or don't have a valid issue number for it to parse (the failed_files segment shows the TPB issues failing for exactly this reason). Mylar doesn't support TPB's / GN's officially, some might work - but there's no guarantee as alot of it depends on how ComicVine has their data structured.
