### ISSUE TITLE
Detecting CB7

### ISSUE THREAD

**Issue by solidus0079** [evilhero/mylar#1279]
I thought CB7 was implemented for file scanning, but mylar doesn't appear to be detecting these files.  Files I previously had as CBZ but converted to CB7 are now showing as "archived", and files that I downloaded without Mylar and converted them to CB7 are showing as skipped or wanted.

Is there something I need to do?  I just did an update and am on Mylar Version: development - source build 872edd43293aaf65ec98f50071cbbb6835956612.

**Comment by evilhero** [comment]
Ahhh I don't think I added that back in when I was redoing the file checker,  but that was weeks ago. 

I'll check it out and patch out a fix for cb7, probably in the next little while.

**Comment by solidus0079** [comment]
Ah, no worries.  Thanks, just whenever you got time.  Cheers!
