### ISSUE TITLE
Odd Error - Non-Posic-compliant windows feature?

### ISSUE THREAD

**Issue by necromancyr** [evilhero/mylar#128]
Getting PAGES of the following on continuous scroll in my shell window (in Windows) every once and awhile.  Seems to happen when I do a refresh...or anything else.  Seems tied to some odd inability to open the log file...don't know why it is occuring.

ValueError: I/O operation on closed file
Logged from file logger.py, line 79
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    if self.shouldRollover(record):
  File "C:\Python27\lib\logging\handlers.py", line 151, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Logged from file logger.py, line 81
04-Jan-2013 22:54:39 - INFO :: CP Server Thread-7 : I've found 64 / 208 issues.
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    if self.shouldRollover(record):
  File "C:\Python27\lib\logging\handlers.py", line 151, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Logged from file logger.py, line 81

**Comment by evilhero** [comment]
Concurrent Rotational Log Handler has been added to Mylar - development build. If you are running on Windows it will automatically try to enable it. The only requirement is that it needs Python Extensions for Windows installed ( http://sourceforge.net/projects/pywin32/ ). Once installed, Mylar will automatically switch to the Concurrent one, which should (it's supposed to) stop the deadlocks on the logging file.
