### ISSUE TITLE
substitutes.csv added now I need to re-add all series

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1280]
I tried editing my substitutes.csv and now when I hit the button to recreate Pull-list now all of my series I have to hit add series but when I do that they say already in library.
![image](https://cloud.githubusercontent.com/assets/11575103/15260244/84e35b86-190a-11e6-9994-b3bd52d5215d.png)

![image](https://cloud.githubusercontent.com/assets/11575103/15260262/a382fe3e-190a-11e6-8e5c-7a4095b333db.png)

Any thoughts?

**Comment by evilhero** [comment]
You probably have something in your csv file that's causing it to error out. 

Are you running the master /development branch? 

If you run mylar with the -v option (or enable verbose logging in the log tab),, do you receive an error at startup about failure to connect to database? When you recreate the purist, and you have debug logging on, does it have anything in the logs?

**Comment by blindguy** [comment]
Configuration Options
Mylar Version: development
-- git build 872edd43293aaf65ec98f50071cbbb6835956612.
Python Version : 2.7.3


contents of substitutes.csv:
GWENPOOL|The Unbelievable Gwenpool


/etc/init.d mylar start -v shows error but not error your looking for:
Starting mylar:/opt/Mylar/lib/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/opt/Mylar/lib/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning



Debug log turned on:
13-May-2016 13:52:19 - INFO    :: CP Server Thread-5 : Deleted existed pull-list data. Recreating Pull-list...
13-May-2016 13:52:19 - INFO    :: CP Server Thread-5 : Weekly pull list present - checking if it's up-to-date..
13-May-2016 13:52:19 - INFO    :: CP Server Thread-5 : [PULL-LIST] Populating & Loading pull-list data from file
13-May-2016 13:52:19 - DEBUG   :: CP Server Thread-5 : Substitutes file read : ['GWENPOOL', 'The Unbelievable Gwenpool']
13-May-2016 13:52:19 - DEBUG   :: CP Server Thread-5 : shipdate: 20160511
13-May-2016 13:52:19 - DEBUG   :: CP Server Thread-5 : today: 00000000
13-May-2016 13:52:19 - INFO    :: CP Server Thread-5 : Preparing to update to the new listing.
13-May-2016 13:52:19 - DEBUG   :: CP Server Thread-5 : Switch worked on GWENPOOL replacing GWENPOOL with The Unbelievable Gwenpool
13-May-2016 13:52:19 - INFO    :: CP Server Thread-5 : Populating the NEW Weekly Pull list into Mylar.

then it does some other stuff and then pull list entry is next at this and it goes for a few hundread lines with different series and alot of 'no Alternate name given. Aborting search'.

13-May-2016 13:52:51 - INFO    :: CP Server Thread-5 : Weekly Pull List successfully loaded.
13-May-2016 13:52:51 - INFO    :: CP Server Thread-5 : Checking the Weekly Releases list for comics I'm watching...
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : ComicName: Extraordinary X-Men
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : latestdate:  2016-06-30
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : c_date : 2016-06-30 ... n_date : 2016-05-13
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : recentchk: -48 days
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Biggie publisher detected - Marvel
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Check date limit set to : 55
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 :  ----- 
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : no Alternate name given. Aborting search.
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : ComicName: Squadron Supreme
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : latestdate:  2016-06-30
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : c_date : 2016-06-30 ... n_date : 2016-05-13
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : recentchk: -48 days
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Biggie publisher detected - Marvel
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Check date limit set to : 55
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 :  ----- 
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : no Alternate name given. Aborting search.
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : ComicName: Power Man and Iron Fist
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : latestdate:  2016-06-30
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : c_date : 2016-06-30 ... n_date : 2016-05-13
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : recentchk: -48 days
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Biggie publisher detected - Marvel
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 : Check date limit set to : 55
13-May-2016 13:52:51 - DEBUG   :: CP Server Thread-5 :  -----

**Comment by evilhero** [comment]
If I were to guess, it's the python 2.7.3 that's causing the problems, and would cause some additional ones as well. 

Mylar can be used with other versions of python, but it's highly recommended that python 2.7.9+ is used (it's actually stated on the github that Mylar only supports 2.7.9+). This is in some ways due to the changed usage of https certificates, SNI related problems, and just an improved method of accessing external resources using the requests module.

**Comment by blindguy** [comment]
Thanks for the quick info.

Dam.  I'm running Debian-Wheezy and I tried updating python before and bad tings happen.  I'll need to read up on that.

I also tried deleting the substitutes.csv in the hopes that things would go back to the way they were but that did not work either.

**Comment by evilhero** [comment]
It's weird - nothing changed in the dev build (or even master) in regards to requests, maybe it was a while since you updated? 

If you need to update python I'd suggest looking into the excellent pyenv program. It allows you to run different versions of python in a virtual type of environment - I use it for several programs on my box ranging from 2.7.3, 2.7.6, 2.7.9,  2.7.10 and even some 3.x and they're running with no problems.

**Comment by kurnalbert** [comment]
Just wanted to add that I am now having the exam same issue after having made an edit to my substitutes.csv file. I have tried as you suggested by shutting down Mylar, deleting the substitutes file and then restarting and the issue continues for me.

**Comment by evilhero** [comment]
What's the error that you're getting? On startup is it giving a failure to connect to the dB?

**Comment by kurnalbert** [comment]
There are no errors on startup (or at all that I can see). The logs of startup are below:

17-May-2016 22:25:54 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.10.20
17-May-2016 22:25:54 - DEBUG   :: MAIN : Logger set to use : Rotational Log Handler (default)
17-May-2016 22:25:54 - INFO    :: MAIN : Branch detected & set to : development
17-May-2016 22:25:54 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
17-May-2016 22:25:54 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : /Applications/mylar/cache/
17-May-2016 22:25:54 - INFO    :: MAIN : Checking to see if the database has all tables....
17-May-2016 22:25:54 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
17-May-2016 22:25:54 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
17-May-2016 22:25:54 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
17-May-2016 22:25:54 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
17-May-2016 22:25:54 - INFO    :: MAIN : Retrieving latest version information from github
17-May-2016 22:25:55 - DEBUG   :: MAIN : Comparing currently installed version [8ac1918b34998caa8813d0eb71e20d77198a4641] with latest github version [8ac1918b34998caa8813d0eb71e20d77198a4641]
17-May-2016 22:25:55 - INFO    :: MAIN : Mylar is up to date
17-May-2016 22:25:55 - INFO    :: MAIN : Setting ComicTagger settings default path to : /Applications/mylar/lib/comictaggerlib/ct_settings
17-May-2016 22:25:55 - INFO    :: MAIN : ComicTagger settings location exists.
17-May-2016 22:25:55 - INFO    :: MAIN : Remapping the sorting to allow for new additions.
17-May-2016 22:25:55 - INFO    :: MAIN : Sucessfully ordered 62 series in your watchlist.
17-May-2016 22:25:55 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/
17-May-2016 22:25:55 - INFO    :: MAIN : Initializing the DB Updater.
17-May-2016 22:25:55 - INFO    :: MAIN : Initiating startup-RSS feed checks.
17-May-2016 22:25:55 - INFO    :: MAIN : Checking for existance of Weekly Comic listing...
17-May-2016 22:25:55 - DEBUG   :: RSSCHECK : Starting new thread: RSSCHECK
17-May-2016 22:25:55 - INFO    :: RSSCHECK : delaying thread for 30 seconds to avoid locks.
17-May-2016 22:25:55 - DEBUG   :: WEEKLYCHECK : Starting new thread: WEEKLYCHECK
17-May-2016 22:25:55 - INFO    :: WEEKLYCHECK : delaying thread for 10 seconds to avoid locks.
17-May-2016 22:25:55 - INFO    :: MAIN : Enabling folder monitor for : /Users/tv/Downloads every 1 minutes.
17-May-2016 22:25:55 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
17-May-2016 22:25:55 - INFO    :: FOLDERMONITOR : delaying thread for 60 seconds to avoid locks.
17-May-2016 22:25:59 - INFO    :: CP Server Thread-4 : Branch detected & set to : development
17-May-2016 22:26:05 - INFO    :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
17-May-2016 22:26:05 - INFO    :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..
17-May-2016 22:26:05 - INFO    :: WEEKLYCHECK : [PULL-LIST] Populating & Loading pull-list data from file
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : no substitues.csv file located - not performing substitutions on weekly pull list
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : shipdate: 20160518
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : today: 20160518
17-May-2016 22:26:06 - INFO    :: WEEKLYCHECK : No new pull-list available - will re-check again in 24 hours.
17-May-2016 22:26:06 - INFO    :: WEEKLYCHECK : Checking the Weekly Releases list for comics I'm watching...
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : ComicName: The Amazing Spider-Man
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : latestdate:  2016-07-31
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : c_date : 2016-07-31 ... n_date : 2016-05-17
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : recentchk: -75 days
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : Biggie publisher detected - Marvel
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : Check date limit set to : 55
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK :  ----- 
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : no Alternate name given. Aborting search.
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : ComicName: Rick and Morty
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : latestdate:  2016-04-30
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : c_date : 2016-04-30 ... n_date : 2016-05-17
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : recentchk: 17 days
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : Indie publisher detected - Oni Press
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : Check date limit set to : 75
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK :  ----- 
17-May-2016 22:26:06 - DEBUG   :: WEEKLYCHECK : no Alternate name given. Aborting search.

The pull list shows none of my series and, like blindguy, if I click add it says they are already added. This is on OSX.

**Comment by evilhero** [comment]
Can you shutdown mylar and edit your config.ini and change the value of alt_pull to alt_pull = 1

Then save it and start up mylar and see if that helps?

**Comment by kurnalbert** [comment]
Just tried that and unfortunately it's still the same. Here are the logs from startup again:

17-May-2016 23:30:47 - DEBUG   :: MAIN : Logger set to use : Rotational Log Handler (default)
17-May-2016 23:30:47 - INFO    :: MAIN : Branch detected & set to : development
17-May-2016 23:30:47 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
17-May-2016 23:30:47 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : /Applications/mylar/cache/
17-May-2016 23:30:47 - INFO    :: MAIN : Checking to see if the database has all tables....
17-May-2016 23:30:47 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
17-May-2016 23:30:47 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
17-May-2016 23:30:47 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
17-May-2016 23:30:47 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
17-May-2016 23:30:47 - INFO    :: MAIN : Retrieving latest version information from github
17-May-2016 23:30:48 - DEBUG   :: MAIN : Comparing currently installed version [8ac1918b34998caa8813d0eb71e20d77198a4641] with latest github version [8ac1918b34998caa8813d0eb71e20d77198a4641]
17-May-2016 23:30:49 - INFO    :: MAIN : Mylar is up to date
17-May-2016 23:30:49 - INFO    :: MAIN : Setting ComicTagger settings default path to : /Applications/mylar/lib/comictaggerlib/ct_settings
17-May-2016 23:30:49 - INFO    :: MAIN : ComicTagger settings location exists.
17-May-2016 23:30:49 - INFO    :: MAIN : Remapping the sorting to allow for new additions.
17-May-2016 23:30:49 - INFO    :: MAIN : Sucessfully ordered 62 series in your watchlist.
17-May-2016 23:30:49 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/
17-May-2016 23:30:49 - INFO    :: MAIN : Initializing the DB Updater.
17-May-2016 23:30:49 - INFO    :: MAIN : Initiating startup-RSS feed checks.
17-May-2016 23:30:49 - DEBUG   :: RSSCHECK : Starting new thread: RSSCHECK
17-May-2016 23:30:49 - INFO    :: MAIN : Checking for existance of Weekly Comic listing...
17-May-2016 23:30:49 - INFO    :: RSSCHECK : delaying thread for 30 seconds to avoid locks.
17-May-2016 23:30:49 - DEBUG   :: WEEKLYCHECK : Starting new thread: WEEKLYCHECK
17-May-2016 23:30:49 - INFO    :: MAIN : Enabling folder monitor for : /Users/tv/Downloads every 1 minutes.
17-May-2016 23:30:49 - INFO    :: WEEKLYCHECK : delaying thread for 10 seconds to avoid locks.
17-May-2016 23:30:49 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
17-May-2016 23:30:49 - INFO    :: FOLDERMONITOR : delaying thread for 60 seconds to avoid locks.
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Populating Base Exception listings into Mylar....
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Populating Custom Exception listings into Mylar....
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Correcting Null entries that make the main page break on startup.
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Deleted existed pull-list data. Recreating Pull-list...
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : Weekly pull list present - checking if it's up-to-date..
17-May-2016 23:30:55 - INFO    :: CP Server Thread-4 : [PULL-LIST] Populating & Loading pull-list data directly from webpage
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : New Releases date detected as : 5/18/2016
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : Saving new pull-list information into local file for subsequent merge
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : file does not exist - continuing.
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : no substitues.csv file located - not performing substitutions on weekly pull list
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : shipdate: 20160518
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : today: 00000000
17-May-2016 23:30:56 - INFO    :: CP Server Thread-4 : Preparing to update to the new listing.
17-May-2016 23:30:56 - INFO    :: CP Server Thread-4 : Populating the NEW Weekly Pull list into Mylar.
17-May-2016 23:30:56 - INFO    :: CP Server Thread-4 : Weekly Pull List successfully loaded.
17-May-2016 23:30:56 - INFO    :: CP Server Thread-4 : Checking the Weekly Releases list for comics I'm watching...
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : ComicName: The Amazing Spider-Man
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : latestdate:  2016-07-31
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : c_date : 2016-07-31 ... n_date : 2016-05-17
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : recentchk: -75 days
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : Biggie publisher detected - Marvel
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : Check date limit set to : 55
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 :  ----- 
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : no Alternate name given. Aborting search.
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : ComicName: Rick and Morty
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : latestdate:  2016-04-30
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : c_date : 2016-04-30 ... n_date : 2016-05-17
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : recentchk: 17 days
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : Indie publisher detected - Oni Press
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : Check date limit set to : 75
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 :  ----- 
17-May-2016 23:30:56 - DEBUG   :: CP Server Thread-4 : no Alternate name given. Aborting search.

**Comment by evilhero** [comment]
I'll have to look into this later when I can get to a machine.  There's something amiss with the matching - it looks like it's generating the information correctly, but just not matching.

**Comment by evilhero** [comment]
Try refreshing one of the series that's on the pull list, and then recreate the pullist with the option on the weekly tab and see if that matches..

**Comment by kurnalbert** [comment]
It looks like the latest update has fixed the issue completely for me, thank you!

**Comment by blindguy** [comment]
Same here.  After refreshing the series and readding them the pull list works properly.
