### ISSUE TITLE
Mass Import - Creating Folder but not moving files

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1281]
During mass import - folders are being created but files are not being moved to new folder. Can you guide me on what the correct settings should be?

**Comment by evilhero** [comment]
It only creates the directories as it gets to the series that's being imported. If its not moving files, but creating the directory then it's a problem with the path that's being passed to the moving module - I believe it's passing the whole path + filename, and it should be seperate entries. I think I had this fixed on my local a few days ago but had some personal things to attend to so wasn't able to commit.  I'll check it out in a little bit and see what's the status of this.

**Comment by F688** [comment]
Getting a lot of ERROR	[IMPORT] Unable to complete the scan: list index out of range which is stopping import scan
[mylar.log.txt](https://github.com/evilhero/mylar/files/268620/mylar.log.txt)

**Comment by evilhero** [comment]
Are you running the most recent development commit? The list index error that someone mentioned in a previous issue was fixed for that.. Not sure if it applies to yours or not however.

**Comment by F688** [comment]
Sorry but I'm running the latest dev commit.

**Comment by evilhero** [comment]
Are these from previous import scan runs that your trying to import in (basically did you run a fresh import scan after updating)

**Comment by F688** [comment]
fresh import scan. I place new comic series in a folder (d:\new). Collect in a different folder D:\Comics. Run scan. I some cases it finishes. I hit the import button, then the mass import. Folder is created byfiles dont move. Other times it will stop working wth the error.

**Comment by evilhero** [comment]
This was working kinda better up until recently right? I've been occupied working on some times to offload api hits from mylar amongst other things, but I'll try and look more into this today so you can get some resolution to this hopefully

**Comment by F688** [comment]
I can confirm that it was working prior as I only tried scanning files that were in their final location previously. Listed below is the error that occurs

ERROR	Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\importer.py", line 590, in addComictoDB
moveit.movefiles(comicid, comlocation, imported)
File "c:\Mylar\mylar\moveit.py", line 15, in movefiles
logger.fdebug('original comicname is : ' + str(imported['ComicName']))
TypeError: string indices must be integers, not str
2016-05-21 11:27:36	DEBUG	comlocation is : D:/Comics/Archie Comics/Sonic Universe (2009)
2016-05-21 11:27:36	INFO	Mass import - Move files

**Comment by F688** [comment]
My config file (Removed api info)
[config.ini.txt](https://github.com/evilhero/mylar/files/275923/config.ini.txt)
