### ISSUE TITLE
mylar wont open after update

### ISSUE THREAD

**Issue by HoLLyWo0d96** [evilhero/mylar#1285]
i updated mylar last night and when it was done the page said local host could not be connect. also now when i try to run mylar the window pops open shows some text then closes its self. i think this is the text it is showing before it closes

c:\user...\mylar.py", line268,  in <module> main<>
File "C:\users...\mylar.py", line 90, in main logger.intlogger<console=not mylar.QUIET, log_dir=False,
AttributeError: 'module' object had no attribute 'QUIET"

any help would be appreciated.

**Comment by evilhero** [comment]
Are you running the master or development branch? 

How are you starting mylar?

**Comment by HoLLyWo0d96** [comment]
i believe master. i am starting mylar by opening the mylar folder on desktop and double clicking mylar.py.

i have had no problems with this way or software for a few months but last night i just updated it and now it wont open.

**Comment by evilhero** [comment]
Probably cause the mylar.py file changed in the last update. You can't normally double-click on the .py file, but you can rename the .py file to a .pyw file and double click on that. 

Just make sure the Mylar.py file your running is from the correct build (the latest).

**Comment by HoLLyWo0d96** [comment]
i tried to change the file from .py to .pyw and still have the same results. can i just dl the newest version if so can i get a link? is that the easier way to fix this?

**Comment by evilhero** [comment]
Well probably best way is to just git clone the repo again, or download the source (not sure how you installed it).  Just backup your config.ini, mylar.db, substitutes.csv (if you have one), and the cache directory (store all the .jpgs for each series). Then just put them all back once you reinstall.

**Comment by evilhero** [comment]
Actually, don't start mylar with the -q option. 

I think it's buggering up the startup sequence.

**Comment by HoLLyWo0d96** [comment]
how do i re-download mylar again?

**Comment by evilhero** [comment]
Have you tried starting mylar without the -q option enabled? 
The link is on the main page of the github repo - either grab the source zip or issue a 'git clone https://github.com/evilhero/mylar -b development' if you have git installed and it will download as well.

**Comment by HoLLyWo0d96** [comment]
how do i start is with out the -q option?

**Comment by evilhero** [comment]
Open up a command prompt and type in the 'python Mylar.py -v'  option from within the mylar directory. It will keep the console window open but you could then tell if it's working or not.
