### ISSUE TITLE
[Request] allow users to have Mylar send notifications for every new comic

### ISSUE THREAD

**Issue by Bart274** [evilhero/mylar#1290]
Allow users to change a setting that would allow them to have Mylar also send them notifications for every new comic that has been found, good for manually downloaded comics instead of just for the snatched ones.

**Comment by evilhero** [comment]
I'm not quite sure I follow - mylar can only track what it downloaded or post-processes and I mylar will notify of torrents that were post-processed successfully (if they were snatched by Mylar). 

Unless youre wanting a notification for every successful post-process of issues?

**Comment by Bart274** [comment]
If you take a look at how sickrage, sickbeard, headphones, couchpotato,... work, then you'll see that they all send their notifications when they successfully post process  an item, but that doesn't depend on whether or not they have snatched that item themselves or not. Sometimes these applications don't find a certain item and I download the torrent manually, but still as soon as the download is completed, these applications post process that downloaded file and I get a notification for that item so I know the download and post processing is done.

**Comment by evilhero** [comment]
I'll look into adding the option into the notification settings.  I'm pretty site the do not spam notification on every post-processing of an issue was intentional, but setting up a toggle option to turn it on or off would be easy enough. 

I'll see if I can get this into development in the next little while...

**Comment by Bart274** [comment]
Thanks, that would be great! :)
