### ISSUE TITLE
ComicRN.py post processing hangs indefiently

### ISSUE THREAD

**Issue by GTSlayer** [evilhero/mylar#1291]
Running into some issues with Post Processing. File downloads fine (as far as I can tell), jumps into ComicRN post processing script and just hangs endlessly.  

Tried reinstalling mylar as well. Running latest Development build. Using Nzbget as my downloader.

> 2016-05-25 11:23:35   ERROR   Uncaught exception: Traceback (most recent call last):
> File "/opt/Mylar/mylar/logger.py", line 158, in new_run
> old_run(_args, *_kwargs)
> File "/usr/lib/python2.7/threading.py", line 754, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/opt/Mylar/mylar/Failed.py", line 151, in Process
> logger.info(module + ' ID: ' + self.id)
> TypeError: cannot concatenate 'str' and 'NoneType' objects
> 2016-05-25 11:23:35 INFO    [FAILED-DOWNLOAD] Provider: NZB Hydra (newznab)
> 2016-05-25 11:23:35 DEBUG   [FAILED-DOWNLOAD] Issueid: 349623
> 2016-05-25 11:23:35 DEBUG   [FAILED-DOWNLOAD] After conversions, nzbname is : Batgirl.012.2012.Digital.Nahga-Empire <

In my original install, I had setup Nzb Hydra as my indexer, but I removed it after it kept sending empty nzbs. I don't see nzbhydra in config.ini so not sure where its pulling that provider.

**Comment by GTSlayer** [comment]
Second note, I did transfer my DB file from my first install to the new one. Would that cause any issue with that? I didn't transfer the config file, I set it up fresh.

**Comment by evilhero** [comment]
Try clearing the nzb log (history tab, wipe nzb log).. It looks like it's trying to locate an errored out nzb. 

Also if you go I to Manage tab / Failed Management, you should be able to see which issues are in failed status and remove it. 

How are you attempting to download it - manual wanted, or retry within mylar?
