### ISSUE TITLE
Error when searching nzbhydra

### ISSUE THREAD

**Issue by tjiddy** [evilhero/mylar#1296]
I see this error in the logs when searching nzbhydra as an indexer. 

```
06-Jun-2016 00:45:32 - INFO    :: Thread-16 : Download URL: http://localhost:8085/api?apikey=xxxxx&t=get&id= [VerifySSL:True]
06-Jun-2016 00:45:32 - ERROR   :: Thread-16 : Unable to download nzb from link: http://localhost:8085/api?apikey=xxxxx&t=get&id= [http://localhost:8085/getnzb?apikey=xxxxx&searchresultid=150624]
06-Jun-2016 00:45:32 - INFO    :: Thread-16 : prov  : Hydra (newznab)[]
06-Jun-2016 00:45:32 - INFO    :: Thread-16 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
06-Jun-2016 00:45:32 - INFO    :: Thread-16 : Found Guardians of the Galaxy (2016) issue: 2 using Hydra (newznab)
06-Jun-2016 00:45:32 - ERROR   :: Thread-16 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1341, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/opt/mylar/mylar/search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/opt/mylar/mylar/search.py", line 1506, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/opt/mylar/mylar/search.py", line 2128, in searcher
    in_file = open(nzbpath, "r")
UnboundLocalError: local variable 'nzbpath' referenced before assignment
```

If I manually put http://localhost:8085/getnzb?apikey=xxxxx&searchresultid=150624 into my browser, I'm able to download the nzb file from nzbhydra just fine.

**Comment by evilhero** [comment]
You have VerifySSL:True which wouldn't be able to validate against a non-https site.  Have you tried turning off Verify SSL for that site, save /restart mylar and try again?

**Comment by tjiddy** [comment]
I don't believe I have it enabled.  This is a screenshot from my providers tab:
<img width="457" alt="mylar" src="https://cloud.githubusercontent.com/assets/4010316/15825785/54ff687c-2bc2-11e6-9d91-d0bed9c28ad3.png">

And this is the corresponding entry in the config.ini file:
<img width="768" alt="config ini" src="https://cloud.githubusercontent.com/assets/4010316/15825799/63ceae44-2bc2-11e6-9e0d-359b172a45e1.png">

**Comment by tjiddy** [comment]
(sorry accidently hit the wrong button and closed the issue)

**Comment by evilhero** [comment]
Ahh ok, I see that something's changed in the response - it's now checking against searchresultid instead of what it was originally - so it's sending the incorrect link to retrieve back to nzbhydra and the verify option is all messed up. Hang on, I'll try and push out a quick fix so you can test.

**Comment by Undeadhunter** [comment]
Doesn't seem to work, since the check is 
`                if 'warp?x=' in link or 'searchresultid' in link:
`
However nzbhydra doesn't use warp like nzbmegasearch used to do. 

In general I think hydra is kind of non functional at this time, with #1244 RSS not returning any results (wrong string). I would assume a complete analysis would be needed to be able to support Hydra, which I don't think is something you'd like to take the time for when other more important issues are out there already.

Personally I gave up on Hydra for Mylar for foreseeing future, since it's such a small audience who uses it I don't think this will be a priority anytime soon, which I completely understand!

**Comment by evilhero** [comment]
It doesn't use warp, but it does use searchresultid (which is why the 'or' is there).  It was just a quick attempt at a fix that was broken, I wasn't able to verify beforehand. 

I'm not sure when the response changed to that tho, so if you're using an old version of hydra that might be part of the problem. 

I'll have to fire mine up at some point today and see if I can get the links working again if they're not working.

**Comment by Undeadhunter** [comment]
Ah yes, sorry I'm blind it seems like it! 

You're absolutely correct, it uses searchresultid=

Pasting link into browser downloads the file, but through Mylar error is still 
`UnboundLocalError: local variable 'nzbpath' referenced before assignment`

**Comment by tjiddy** [comment]
Thanks Evilhero, I just updated to 	5431908 and mylar is able to snatch files again.  All seems to be working properly.  Feel free to close the defect.

**Comment by evilhero** [comment]
@tjiddy: thanks for coming back and saying it's working for you :) 

@Undeadhunter : are you using the latest development commit? If you are I'm wondering if it's a setting within hydra that's changing the response that mylar's expecting (I know you could run hydra in some different modes for how it responds to queries)

**Comment by Undeadhunter** [comment]
@evilhero seems like the issue was with the Docker instance I was running not updating to the latest version. Edited the dockerfile and all is good now. Thanks!
