### ISSUE TITLE
Post-Processing Hangs/ComicRN hangs indefinitely

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1299]
Got another ComicRN/Post Processing bug, different from the one on April 13th I think. 

Around 60% of the issues I download exhibit this behavior: they're found and snatched and downloaded properly, but during sab post-processing something goes awry.  The issue is unpacked and renamed, and moved to the appropriate folder, but ComicRN never exits, so my sab queue sits until I manually go in and kill the process.  

I'm running mylar and sab on a Diskstation NAS.  Mylar Version: fba18e28656339dc2c195a2a91df782ec366e964

LOGS:

> 2016-06-08 16:00:39   ERROR   Uncaught exception: Traceback (most recent call last):
> File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
> old_run(_args, *_kwargs)
> File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1090, in Process
> return self.Process_next(comicid, issueid, issuenumOG)
> File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1732, in Process_next
> updater.forceRescan(comicid, module=module)
> File "/volume1/@appstore/mylar/share/mylar/mylar/updater.py", line 795, in forceRescan
> tmpv = mvals.listFiles()
> File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 123, in listFiles
> filelist = self.traverse_directories(self.dir)
> File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 921, in traverse_directories
> dir = dir.encode(mylar.SYS_ENCODING)
> AttributeError: 'NoneType' object has no attribute 'encode'
> 2016-06-08 16:00:39 ERROR   Uncaught exception: Traceback (most recent call last):
> File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
> old_run(_args, *_kwargs)
> File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1090, in Process
> return self.Process_next(comicid, issueid, issuenumOG)
> File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1732, in Process_next
> updater.forceRescan(comicid, module=module)
> File "/volume1/@appstore/mylar/share/mylar/mylar/updater.py", line 795, in forceRescan
> tmpv = mvals.listFiles()
> File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 123, in listFiles
> filelist = self.traverse_directories(self.dir)
> File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 921, in traverse_directories
> dir = dir.encode(mylar.SYS_ENCODING)
> AttributeError: 'NoneType' object has no attribute 'encode'
> 2016-06-08 16:00:39 INFO    [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in :
> 2016-06-08 16:00:39 INFO    [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in :
> 2016-06-08 16:00:39 INFO    FAILED FILES: [{'issue_number': '01', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 01.cbr', 'series_volume': None}, {'issue_number': '02', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 02.cbr', 'series_volume': None}, {'issue_number': '03', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 03.cbr', 'series_volume': None}, {'issue_number': '04', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 04.cbr', 'series_volume': None}, {'issue_number': '05', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 05.cbr', 'series_volume': None}, {'issue_number': '06', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 06.cbr', 'series_volume': None}, {'issue_number': '07', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 07.cbr', 'series_volume': None}, {'issue_number': '08', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 08.cbr', 'series_volume': None}, {'issue_number': '09', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mr Majestic', 'comicfilename': 'Mr Majestic 09.cbr', 'series_volume': None}, {'issue_number': '01', 'sub': 'Archive/Mr Majestic', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Wildstorm Spotlight', 'comicfilename': 'Wildstorm Spotlight 01 - Majestic.cbr', 'series_volume': None}, {'issue_number': '01', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2003', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 01 (of 12) (2003) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '02', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2003', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 02 (of 12) (2003) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '03', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2003', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 03 (of 12) (2003) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '04', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2003', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 04 (of 12) (2003) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '05', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 05 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '06', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 06 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '07', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 07 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '08', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 08 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '09', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 09 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '10', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 10 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '11', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 11 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': '12', 'sub': 'Archive/Superman - Birthright', 'issue_year': '2004', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': 'Zone-Empire', 'parse_status': 'failure', 'series_name': 'Superman Birthright', 'comicfilename': 'Superman Birthright 12 (of 12) (2004) (Digital) (Zone-Empire).cbr', 'series_volume': None}, {'issue_number': None, 'sub': 'Archive/Superman - Earth One', 'issue_year': '2010', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Superman - Earth', 'comicfilename': 'Superman - Earth One Volume One (2010).cbr', 'series_volume': 'v'}, {'issue_number': None, 'sub': 'Archive/Superman - Earth One', 'issue_year': '2012', 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Superman - Earth', 'comicfilename': 'Superman - Earth One Volume Two (2012).cbr', 'series_volume': 'v'}, {'issue_number': None, 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Union - Final Vengeance', 'comicfilename': 'Union - Final Vengeance.cbz', 'series_volume': None}, {'issue_number': '00', 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Union', 'comicfilename': 'Union v1 - 00.cbz', 'series_volume': 'v1'}, {'issue_number': '01', 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Union', 'comicfilename': 'Union v1 - 01.cbz', 'series_volume': 'v1'}, {'issue_number': '02', 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Union', 'comicfilename': 'Union v1 - 02.cbz', 'series_volume': 'v1'}, {'issue_number': '03', 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Union', 'comicfilename': 'Union v1 - 03.cbr', 'series_volume': 'v1'}, {'issue_number': '04', 'sub': 'Archive/Union', 'issue_year': None, 'comiclocation': u'/volume1/Diskstation/Media/Comics/', 'scangroup': None, 'parse_status': 'failure', 'series_name': <

**Comment by evilhero** [comment]
It looks like you're not passing a directory:
```
dir = dir.encode(mylar.SYS_ENCODING)
AttributeError: 'NoneType' object has no attribute 'encode'
2016-06-08 16:00:39 INFO [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in :
2016-06-08 16:00:39 INFO [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in :
```
The NoneType error is indicating that the dir variable is empty,and the Now Checking portion for Daredevil also has no values in it for the directory to check, so it's literally checking the entire root of your comic location (I think).

If you go to the series detail page for the given series, does it have the proper directory location displayed?

**Comment by ForumFerret** [comment]
It does - but i've got a nonstandard folder setup. 

My root comics path is /diskstation/media/

Renaming is enabled, and the Folder Format variable is set to "comics/"
This dumps ALL my comics into a single directory, which I sync to my tablet. Once issues are synced to my tablet, I archive or delete them manually. 

Looking at the series in question, I do see the path set to /diskstation/media/comics as appropriate

**Comment by evilhero** [comment]
Right now there's pretty much no way to change it unfortunately. With the recent changes to the filechecker/post-processor/importer and soon to be search modules, it's a requirement that the series directories are present so that it knows what files belong where.

It's probably possible to change it to allow single folders instead of separate folders, but I'll need to look into it more as even allowing for the one directory for all, would mean that it has to ignore all the failures (which are just tagged as failures because they don't match to the series title that it's looking for - in this case Daredevil).

In looking at the log, is there any information on the issues that were scanned in as Daredevil (probably would have occured just prior to the failure list that printed in that log)? I'm curious - if they scanned in and weren't tagged as being failures, that would make things much easier from a coding standpoint (I think)

**Comment by ForumFerret** [comment]
Just that giant list of Failed files - I can hop on the Synology and pull the whole log file if you'd like.

**Comment by evilhero** [comment]
Well I don't think I'd need the whole log - just the part prior to the that failure list. You should evem be able to find the daredevil issues by searching for the names in the log and it would show if the checker parsed them OK or not.

**Comment by ForumFerret** [comment]
I think this is what you're looking for: 

> 08-Jun-2016 16:00:29 - INFO    :: RSSCHECK : Download URL: http://nzbindex.nl/download/136701722/0-Day-2016.6.8-Daredevil-008-2016-Digital-Zone-Empire.cbr.nzb [VerifySSL:False]
08-Jun-2016 16:00:29 - INFO    :: RSSCHECK : filen: Daredevil.008.2016.Digital.Zone-Empire. -- nzbname: Daredevil.008.2016.Digital.Zone-Empire are not identical. Storing extra value as : Daredevil.008.2016.Digital.Zone-Empire.
08-Jun-2016 16:00:29 - INFO    :: RSSCHECK : Found Daredevil (2016) issue: 8 using experimental [RSS]
08-Jun-2016 16:00:29 - INFO    :: RSSCHECK : setting the alternate nzbname for this download grabbed by experimental in the nzblog to : Daredevil.008.2016.Digital.Zone-Empire.
08-Jun-2016 16:00:30 - INFO    :: RSSCHECK : [UPDATER] Updated the status (Snatched) complete for Daredevil Issue: 8
08-Jun-2016 16:00:38 - INFO    :: CP Server Thread-3 : Starting postprocessing for : Daredevil.008.2016.Digital.Zone-Empire
08-Jun-2016 16:00:38 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for /volume1/Diskstation/Media/Comics/Daredevil.008.2016.Digital.Zone-Empire
08-Jun-2016 16:00:38 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for Daredevil issue: 8
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [POST-PROCESSING][UPDATER] Updating Status (Downloaded) now complete for Daredevil issue: 8
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in /volume1/Diskstation/Media/Comics/
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [FILENAME]: Daredevil 8 (2016).cbr
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: daredevil --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 01.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 02.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 03.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 04.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 05.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 06.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 07.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 08.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: mr majestic --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Mr Majestic 09.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: wildstorm spotlight --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Wildstorm Spotlight 01 - Majestic.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 01 (of 12) (2003) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 02 (of 12) (2003) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 03 (of 12) (2003) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 04 (of 12) (2003) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 05 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 06 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 07 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 08 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 09 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 10 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 11 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: superman birthright --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Superman Birthright 12 (of 12) (2004) (Digital) (Zone-Empire).cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v1 - 00.cbz [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v1 - 01.cbz [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v1 - 02.cbz [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v1 - 03.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v1 - 04.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 01.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 02.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 03.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 04.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 05.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 06.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 07.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 08.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : Series_Name: union --- WatchComic: daredevil
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [NO MATCH] Union v2 - 09.cbr [WATCHLIST:Daredevil]
08-Jun-2016 16:00:39 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Now checking files for Daredevil (2015) in :
08-Jun-2016 22:51:08 - INFO    :: Thread-26 : [FILENAME]: Daredevil 8 (2016).cbr
<
