### ISSUE TITLE
Cannot post-process with NZBGet

### ISSUE THREAD

**Issue by haygoodhtpc** [evilhero/mylar#1303]
Here's my log:

`INFO   Sat Jun 11 2016 03:57:20    Collection The.Wicked.The.Divine.020.2016.Digital.Zone-Empire added to history
ERROR   Sat Jun 11 2016 03:57:20    Post-process-script ComicRN.py for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire failed
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Unable to locate a valid cbr/cbz file. Aborting post-processing for this filename.
INFO    Sat Jun 11 2016 03:57:20    ComicRN: No version # found for series - tag will not be available for renaming.
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Comic Version: None
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Comic Location: /media/78bc2183-39f9-4870-bf80-eb5108785400/Comics/The Wicked + The Divine (2014)
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Year: 2014
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Series: The Wicked + The Divine
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Publisher: Image
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Issue Year: 2016
INFO    Sat Jun 11 2016 03:57:20    ComicRN: nzbname: The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    ComicRN: nzb folder: /media/78bc2183-39f9-4870-bf80-eb5108785400/Comics/The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    ComicRN: nzb name: The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Opening URL: http://192.168.1.151:8090/post_process?nzb_name=The.Wicked.The.Divine.020.2016.Digital.Zone-Empire&failed=0&apc_version=1.0&comicrn_version=1.01&nzb_folder=%2Fmedia%2F78bc2183-39f9-4870-bf80-eb5108785400%2FComics%2FThe.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    ComicRN: Loading config from /usr/share/nzbget/scripts/autoProcessComics.cfg
INFO    Sat Jun 11 2016 03:57:20    Executing post-process-script ComicRN.py for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    Move for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire successful
INFO    Sat Jun 11 2016 03:57:20    Moving file The Wicked + The Divine 020 (2016) (Digital) (Zone-Empire).cbr to /media/78bc2183-39f9-4870-bf80-eb5108785400/Comics/The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:20    Moving completed files for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:19    Nothing to cleanup for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:19    Cleaning up The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:19    Nothing to unpack for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:19    No renamed files found for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:19    Checking renamed files for The.Wicked.The.Divine.020.2016.Digital.Zone-Empire
INFO    Sat Jun 11 2016 03:57:18    Queueing The.Wicked.The.Divine.020.2016.Digital.Zone-Empire for post-processing
INFO    Sat Jun 11 2016 03:57:18    Collection The.Wicked.The.Divine.020.2016.Digital.Zone-Empire completely downloaded
INFO    Sat Jun 11 2016 03:57:18    Successfully downloaded The.Wicked.The.Divine.020.2016.Digital.Zone-Empire/The Wicked + The Divine 020 (2016) (Digital) (Zone-Empire).cbr`

When it downloads, it downloads to my ../Comics folder, but instead of putting it in the same file with the rest of the comics in the series, it puts it into its own file with oddly-set permissions. I don't know if it's Mylar or NZBGet which is setting the permissions.

**Comment by evilhero** [comment]
It puts it in the root of your comic location folder because you have your downloads going there. Generally speaking, don't put your nzb download directory within your comic location folder (keep it seperate). I mean it will work, but from a troubleshooting perspective, it's not helping isolate the problem. 

Set mylar to run in verbose mode, either by starting it with the -v option or going into the logs tab within mylar and clicking on the toggle verbose option. Then try downloading an issue again and post back the mylar.log file so I can see the debugging info.

**Comment by haygoodhtpc** [comment]
Turns out I was able to fix it because nzbget was downloading it to the Comics folder. Once I changed that setting, NZBGet began downloading it to the typical NZB download folder and copying it into the Comics folder. NZBGet's cleanup isn't working perfectly, but I can manually empty the NZB download folder once a week as a cron job, no biggie.
