### ISSUE TITLE
New folders missing space character between title and year

### ISSUE THREAD

**Issue by max6166** [evilhero/mylar#1305]
New comic folders are now being created in the following format: "title(year)". 

Until recently, the naming convention for new comic folders was "title (year)", i.e. with a space between the title and year.

**Comment by evilhero** [comment]
The format for folder creation is user controlled via the Folder Format string located on the last tab within the configuration.  I'd check your folder format to see how you have it currently, by default it's set to $Series-($Year)

**Comment by max6166** [comment]
Thanks evilhero.
