### ISSUE TITLE
Manual Intervention Uncaught Exception

### ISSUE THREAD

**Issue by JasonMSims** [evilhero/mylar#1306]
When selecting an option from the importresults_popup, the following uncaught exception is thrown:

``` python
Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 590, in addComictoDB
moveit.movefiles(comicid, comlocation, imported)
File "/opt/Mylar/mylar/moveit.py", line 16, in movefiles
logger.fdebug('original comicname is : ' + str(imported['ComicName']))
TypeError: string indices must be integers
```

Looking at the importresults_popup.html, it's passing in a string as imported (imported='yes') to webserve.py, which passes it on to importer.py, which finally passes it on to moveit.py - where moveit.py is expecting a dict that includes the index 'ComicName' (among others) that do not exist because there is only a string ('yes').

**Comment by evilhero** [comment]
Yep, I missed that one - Thanks for posting the error along with an explanation.

I was just in the process of fixing the 'imported' dict within the actual import process. Good thing you posted this when you did - I can now fix this at the same time. Expect it in the next development commit hopefully coming very shortly.
