### ISSUE TITLE
Mylar/NZBHydra not working.

### ISSUE THREAD

**Issue by stayupthetree** [evilhero/mylar#1307]
Similar to issue #1206 
Was your fix master or dev?
 Here is log:

21-Jun-2016 02:19:57 - INFO    :: Thread-13 : Download URL: http://docker.local:5075/api?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&t=get&id= [VerifySSL:True]
21-Jun-2016 02:20:04 - ERROR   :: Thread-13 : Unable to download nzb from link: http://docker.local:5075/api?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&t=get&id= [http://docker.local:5075/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=1]
21-Jun-2016 02:20:04 - INFO    :: Thread-13 : prov  : nzbhydra (newznab)[]
21-Jun-2016 02:20:04 - INFO    :: Thread-13 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
21-Jun-2016 02:20:04 - INFO    :: Thread-13 : Found The Legend of Wonder Woman (2015) issue: 1 using nzbhydra (newznab)
21-Jun-2016 02:20:04 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Mylar\mylar\webserve.py", line 1341, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "C:\Mylar\mylar\search.py", line 254, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Mylar\mylar\search.py", line 1467, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "C:\Mylar\mylar\search.py", line 2073, in searcher
    in_file = open(nzbpath, "r")
UnboundLocalError: local variable 'nzbpath' referenced before assignment

Looks like it is cutting off information after =get&id=

**Comment by evilhero** [comment]
Fixes always go into development for testing and confirmation before merging into master. 

This has already been confirmed as working, but hasn't made it into the master branch yet.

**Comment by stayupthetree** [comment]
I switched to dev, same issue. Should I try a reinstall?

**Comment by evilhero** [comment]
Shouldn't have to - what commit are you running of mylar?

**Comment by stayupthetree** [comment]
156119ffa4ebe06a994c2d8d8ccdffcdc99331cb

**Comment by evilhero** [comment]
Is your version of  nzbhydra up to date as well?  Really weird how it's working for others, but not yourself.

**Comment by stayupthetree** [comment]
http://prntscr.com/bjbqi6

**Comment by stayupthetree** [comment]
http://prntscr.com/bjbthu

**Comment by evilhero** [comment]
That's master -  the fix is in development (see issue #1296). 

I have zero knowledge of dockers, but the in last comment updating the docker fixed the issue.

**Comment by stayupthetree** [comment]
I looked into updating the docker, I wish he was more specific about what he did. I checked the dockerfile he said he tinkered with and nothing indicated anything related to updating or changing branch

**Comment by evilhero** [comment]
I think he was getting at that the docker wasn't allowing mylar to update to the latest version properly so he had to do something. 

You might(?) have to force mylar to the dev branch by using the git_branch option in the mylar config.ini and set it to git_branch = development 

You might have to ask the docker folks about this, as I have no way to test against a docker.

**Comment by stayupthetree** [comment]
Oh, Mylar isn't in a Docker, just NZBHydra

**Comment by evilhero** [comment]
OK, we'll that helps a bit.  Try running mylar in verbose mode and then try to download something. Make sure you're on the development branch as well just to make sure you're up to date. 

How is nzbhydra set to send the links?

**Comment by stayupthetree** [comment]
Sorry for the late response, work gets in the way sometime. I just wiped and did a fresh install and all is working fine, I think something got crossed up on my end. So this can be closed sorry for wasting your time.

I do have a random question, don't know where to ask however, so I will ask here. If ComicRack and Mylar both scrape from ComicVine, why does ComicRack get more info? Can 'Story Arc' tags be added to the tags? Or does each bit of info on a comic cause an API hit? A hit I am incurring anyways by scraping again with ComicRack.
