### ISSUE TITLE
Add support for intermediate certificates

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#1309]
I have a domain validation cert I want to use with mylar.  But to use it and not have it throw errors, it requires an intermediate cert.

**Comment by evilhero** [comment]
I honestly haven't a clue as to how to go about doing this. I haven't any idea about the intermediate certificate and to be honest, I don't really have the time to do a ton of reading on the subject. 

If it's something as simple as adding a variable to control the location of certificate chain to be loaded within cherrypy, that might be doable. But again, no real idea and no way to test out anything related to this.

**Comment by apastuszak** [comment]
I think it might be.  I'll do some homework and get back to you.

**Comment by apastuszak** [comment]
Look at line 165 of ssl_pyopenssl.py.  Does that help any?

**Comment by evilhero** [comment]
Yeah I already knew of that option, but it's not enabled by default.  Was more of how to implement it within Mylar without breaking the web UI. 

I think I found something that might work. I'll see how quick I can mock it up for you to test

**Comment by apastuszak** [comment]
Thank you!
