### ISSUE TITLE
getting odd Ssl issues recently

### ISSUE THREAD

**Issue by dilbaggins** [evilhero/mylar#1311]
i have updated to the latest python and openssl ( 	openssl-1.0.2h)  yet am seeing the below when searching my nzedb indexer.  

Evil - if you fix it,  many cups of coffee will come your way :)

2016-07-01 14:46:44	ERROR	Uncaught exception: Traceback (most recent call last):
File "/home/.mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/.mylar/mylar/search.py", line 1642, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/home/.mylar/mylar/search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/home/.mylar/mylar/search.py", line 621, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-07-01 14:46:44	WARNING	Error fetching data from newznab: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-07-01 14:46:05	WARNING	Error fetching data from newznab: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by evilhero** [comment]
If you're using  python 2.7.12rc1, there's some sort of change that's causing some ssl problems. I can't verify what it is, but there have been a few users who upgraded to it and then had to downgrade to 2.7.11 in order for things to work again. 

It might be too 'bleeding edge' atm, or it might have compatibility issues with some versions of openssl.. I'm not sure, but if you are running the rc1 - try and downgrade it and see if that helps at all. 

Other than that, can you confirm your version of python?

**Comment by dilbaggins** [comment]
thanks @evilhero 
Configuration Options
Mylar Version: master
-- git build 562a8a851204051c1a60a63d80f6b1beb1b499fa.
Python Version : 2.7.10

**Comment by evilhero** [comment]
OK so shoot the 2.7.12 out the door (unless you upgraded to 2 7.12 and mylar is showing the wrong python version). 

In your nzedb indexer info within mylar, do you gave verify ssl enabled or disabled? And are you running the nzedb as an https or non-https site?

**Comment by dilbaggins** [comment]
i have 2.7.10 installed of Python.

nzedb is https

**Comment by evilhero** [comment]
Do you have the Verify SSL option enabled for your nzedb indexer within mylar?

**Comment by dilbaggins** [comment]
this is unchecked.

**Comment by evilhero** [comment]
Probably the problem. You have an https site that you're trying to access, but it can't verify the certificate. Try checking on the verify ssl option, save the config, and  restart mylar. 

If everything goes as I'm thinking, it should start working again.

**Comment by dilbaggins** [comment]
@evilhero did the above and still seeing this:  Error fetching data from newznab: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

even after rebooting the server and deleting and readding the newznab listing as well.

**Comment by evilhero** [comment]
Check your version of pyOpenssl - maybe?
>>> import OpenSSL
>>> OpenSSL.__file__
>>> OpenSSL.__version__

I don't think you'd need to install the Cryptography module, but it's a possibility (and not without it's inherit problems due to additional required modules for it to be installed properly).

If you upgraded your python and your openssl, you would need to relink the pyopenssl to use the correct openssl/python binaries again (from what I can remember)

**Comment by dilbaggins** [comment]
the linking is correct from what ive seen. still very odd.

**Comment by evilhero** [comment]
What did the python commands above return?

**Comment by dilbaggins** [comment]
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named OpenSSL


strange as i have the OpenSSL running and the PIP installed.

**Comment by dilbaggins** [comment]
here is the pip list:

 pip list
ansible (2.1.0.0)
apt-xapian-index (0.45)
argparse (1.2.1)
cffi (1.7.0)
chardet (2.0.1)
Cheetah (2.4.4)
colorama (0.2.5)
configobj (4.7.2)
cryptography (1.4)
enum34 (1.1.6)
feedparser (5.1.3)
html5lib (0.999)
httplib2 (0.8)
idna (2.1)
iotop (0.6)
ipaddress (1.0.16)
Jinja2 (2.7.2)
Landscape-Client (14.12)
lxml (3.3.3)
MarkupSafe (0.18)
PAM (0.4.2)
paramiko (1.10.1)
pip (1.5.4)
pssh (2.3.1)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pygobject (3.12.0)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
uTidylib (0.2)
wheel (0.24.0)
wsgiref (0.1.2)
yenc (0.4.0)
zope.interface (4.0.5)

**Comment by evilhero** [comment]
I think you might need to update your pyopenssl to work correctly with the version of openssl you're now running. The pyopenssl just links python to your openssl install from what I remember, so if you're running a newer version of openssl and you updated python, it makes sense why it wouldn't link properly anymore.

**Comment by dilbaggins** [comment]
thanks @evilhero  is there a command i need to run (looked around and found nothing)

**Comment by evilhero** [comment]
I think it's just a simple: 
pip install --upgrade pyopenssl  (maybe sudo?)

although you might have to upgrade your pip since it's at a low level:
sudo -H pip2 install --upgrade pip

**Comment by dilbaggins** [comment]
pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

pyOpenSSL (0.13)

strange... 

Found existing installation: pyOpenSSL 0.13

**Comment by evilhero** [comment]
yeah that's not normal - sudo doesn't update the pyOpenSSL?

Mine is:
pip 8.1.2 (python 2.7)
pyOpenSSL (16.0.0)

I didn't think you'd have to uninstall pyOpenSSL, but if the upgrade option doesn't work I don't think there's another option ?

**Comment by dilbaggins** [comment]
ok fixed it by following the curl script here:  http://www.liquidweb.com/kb/how-to-install-pip-on-ubuntu-14-04-lts/


here is my output now:  

python
Python 2.7.10 (default, Jun 27 2016, 21:41:59)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
>>> OpenSSL.__file__
'/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.pyc'
>>> OpenSSL.__version__
'16.0.0'

**Comment by evilhero** [comment]
OK looks good... And still errors with mylar or is that fixed now as well?

**Comment by dilbaggins** [comment]
2016-07-05 16:20:54	WARNING	Error fetching data from newznab: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

i have tried toggling "Verify SSL" on and off.

**Comment by dilbaggins** [comment]
with a stop adn start of mylar services to refresh UI.

**Comment by evilhero** [comment]
Still weird. At this point the only thing I can think of is the version of python.  A lot of the problems that I've read about with the sni stuff is either due to being on python < 2.7.9, or being on 2.7.10. 

A bit drastic and not sure if it's possible, but upgrade python to 2.7.11 might fix things (not 2.7.12 as that's an rc, and don't think you want to downgrade to 2.7.9 at this point)

**Comment by dilbaggins** [comment]
thanks going to close as i've done enough surgery for now.  going to build a new VM just for Mylar and test. thanks @evilhero

**Comment by evilhero** [comment]
Sorry wish I could have helped more. I was going to suggest (prior to the python upgrade comment), that you might want to try and upgrade your requests via pip. I'm at a higher level than what you're at , and I know that requests plays a big role in how mylar accesses sites (even though it comes with it, there might be something that needs to be have it installed for some reason). 

Let me know if you do get it working, as I'd like to know myself what works vs what doesn't.
