### ISSUE TITLE
Failed downloads not processing correctly

### ISSUE THREAD

**Issue by stayupthetree** [evilhero/mylar#1313]
Whenever a download fails the post processing script gets stuck on that step, instead of continuing on. This is what shows in the log files at the moment of processing a failed download. This screenshot is the NZBGet side of life. I have to manually delete the download or no more post processing will continue in NZBGet as it is waiting for a response from the post processing script. http://prntscr.com/bowiwl
Running latest dev
04-Jul-2016 22:22:36 - INFO    :: CP Server Thread-7 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
04-Jul-2016 22:22:36 - INFO    :: CP Server Thread-7 : Starting postprocessing for : Superman.Annual.01.2012.Megan-Empire.REPOST
04-Jul-2016 22:22:36 - INFO    :: CP Server Thread-7 : Initiating Failed Download handling for this download.
04-Jul-2016 22:22:36 - INFO    :: FAILED Post-Processing : [FAILED-DOWNLOAD] Provider: nzbhydra (newznab)
04-Jul-2016 22:22:36 - ERROR   :: FAILED Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "c:\Mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\Mylar\mylar\Failed.py", line 151, in Process
    logger.info(module + ' ID: ' + self.id)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
Probably related to nzbhydra being used as a provider and going through the Failed handler. I'll have to try and look more into it and see if I can figure it out.

**Comment by stayupthetree** [comment]
This was happening before I used nzbhydra. You'd know better than I, but isn't NZBHydra's involvement done at this point? Usenet provider no longer had the proper articles for download, download fails, as soon as NZBGet/ComicsRN.py communicates this to Mylar....error.

**Comment by evilhero** [comment]
Well the involvement of nzbhydra is done at that point yes, but in order for it to reference the failed download properly it needs to tag it to a specific id. For some reason, it's failing to poll that id from your db for that specific download (meaning that either it wasn't properly determined, or it was never written to the db).

What would help immensely in this case, is if you could turn on verbose logging and then try to download the failed download again. The INFO level of logs isn't very helpful in debugging, and in order to see what ID it's trying to search for to reference, I'd need to see the debugging logs.

**Comment by stayupthetree** [comment]
http://pastebin.com/U84Ca0FB

**Comment by evilhero** [comment]
Sorry about the delay in response.

The line where it's not generating the ID is actually here, the blank []:
```
06-Jul-2016 13:12:27 - INFO    :: Thread-13 : prov  : nzbhydra (newznab)[]
```

Think I have this fixed now, so it will be in the next development commit for you to try out. Please don't forget to let me know if it works and/or close off the ticket depending on the result :)

**Comment by stayupthetree** [comment]
Seems to be working and not holding up postprocessing in nzbget. Thanks! "15-Jul-2016 16:51:42 - INFO    :: FAILED Post-Processing : Failed download handling for story-arcs and one-off's are not supported yet. Be patient!"
