### ISSUE TITLE
"Wanted" button causing 500 Internal Server Error

### ISSUE THREAD

**Issue by Spartan304** [evilhero/mylar#1319]
Updated to latest commit and now when I click on "Wanted" I get:  

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/spartan304/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/spartan304/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/spartan304/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/spartan304/mylar/mylar/webserve.py", line 1821, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

Powered by CherryPy 3.2.0
```

Also when I click on "This Week" none of the comics that are in my pull list are highlighted as Wanted however if I go into the specific comic the newest issue is actually marked as Wanted.  I've ran updates, rebooted Mylar, and rebooted the server multiple times, issue still persists.

**Comment by evilhero** [comment]
See #1316 -  should be fixed in latest dev commit.  You probably need to do a recreate pullist in order to get things all lined up again however.

**Comment by Spartan304** [comment]
My apologies, my idiot brain didn't see the "closed" section.  Thanks for the speedy response and awesome work on Mylar!
