### ISSUE TITLE
Pull list download button creates 500 Internal Server Error

### ISSUE THREAD

**Issue by digitaldiatribe** [evilhero/mylar#1321]
Latest development release: 836fea2cfe3b48897c718df7249e6b353576c1c0

Some of my releases didn't make it to the weekly folder despite them being downloaded in the respective folders. I pressed the download button to get the missing books copied into the weekly folder and it produced and 500 Internal Server Error message and the following error message:

Traceback (most recent call last):
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 3072, in MassWeeklyDownload
    desdir = os.path.join(dstdir, str( str(pulldate['year']) + '-' + str(pulldate['weeknumber']) ))
TypeError: string indices must be integers

**Comment by evilhero** [comment]
I'll have to check into this - think it's due to the new way the pullist is working atm.  Should be easily fixable so will give an update hopefully in bit.

**Comment by the-Dakta** [comment]
I just updated from the master to the development branch, and got this error immediately upon trying to access my wanted list. I've already restarted mylar and the PC with no change. Latest version of the development build and Python 2.7.10 on Windows 10.

**Comment by evilhero** [comment]
Try the Recreate Pullist button on the weekly tab. It's due to a new method that Mylar uses to gather new pullist information (it's optional), but it's still causing this issue on new startups.

**Comment by the-Dakta** [comment]
Well would you look at that. Back at it again with the quick and efficient response. Thanks for the support and hard work!
