### ISSUE TITLE
Add One-Off generates 500 Internal Server Error

### ISSUE THREAD

**Issue by Spartan304** [evilhero/mylar#1323]
Anytime I try to add a One-Off I get: 

`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/spartan304/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/spartan304/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/spartan304/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/spartan304/mylar/mylar/webserve.py", line 1288, in queueissue
    foundcom, prov = search.search_init(ComicName=ComicName, IssueNumber=ComicIssue, ComicYear=ComicYear, SeriesYear=None, Publisher=Publisher, IssueDate=cyear['SHIPDATE'], StoreDate=cyear['SHIPDATE'], IssueID=None, AlternateSearch=None, UseFuzzy=None, ComicVersion=None,allowpacks=False)
TypeError: search_init() got an unexpected keyword argument 'allowpacks'
Powered by CherryPy 3.2.0`

When I check the GUI log it says it's marking the issue as Wanted however no search gets performed.  I'm on the latest development build and I recently recreated the pull list to fix the Wanted button issue.  Have also rebooted Mylar and the server, no change.

**Comment by evilhero** [comment]
Can confirm, it's a bug. And will be fixed in the next development commit.

**Comment by Spartan304** [comment]
Awesome! Confirmed working after latest update. As always, keep up the awesome work!
