### ISSUE TITLE
[IMPORT] Unable to complete the scan: string index out of range

### ISSUE THREAD

**Issue by samkatakouzinos** [evilhero/mylar#1327]
# Issue

Manage - Scan Comic Library - Save Changes and Scan
Performing above doesn't complete with following settings and logs
## Settings

```
Path to directory; D:\fs\prg\pd\NZBGet\complete\Comics 
Auto-add new series; ticked.
Use existing Metadata; ticked. Use existing Metadata to better locate series for import
Move files into corresponding Series directory; ticked. Leaving this unchecked will not move anything, but will mark the issues as Archived
Rename Files; ticked. Rename files to configuration settings
```
## Logs

```
19-Jul-2016 01:05:15 - INFO    :: CP Server Thread-5 : Verbose toggled, set to True
19-Jul-2016 01:05:15 - DEBUG   :: CP Server Thread-5 : If you read this message, debug logging is available
19-Jul-2016 01:05:16 - INFO    :: CP Server Thread-5 : Web logs cleared
19-Jul-2016 01:05:23 - INFO    :: CP Server Thread-11 : Verbose toggled, set to False
19-Jul-2016 01:05:24 - INFO    :: CP Server Thread-11 : Verbose toggled, set to True
19-Jul-2016 01:05:24 - DEBUG   :: CP Server Thread-11 : If you read this message, debug logging is available
19-Jul-2016 01:05:45 - INFO    :: CP Server Thread-10 : forcescan is: 0
19-Jul-2016 01:05:45 - INFO    :: LibraryScan : Scanning comic directory: D:\fs\prg\pd\NZBGet\complete\Comics
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Scanner group tag discovered: RedBeard-Empire-Novus
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : checking date : 2012
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : date: 2012
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : datecheck: [{'date': '2012', 'position': 7, 'mod_position': -1}]
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : sctd: 2016
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : year verified as : 2012
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : year verified as: 2012
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : highest_series_position: 7
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : series title possibly: Assassin's Creed - The Fall Deluxe Edition
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Comic: Assassin's Creed - The Fall Deluxe Edition (2012) (Epilogue Only) (RedBeard-Empire-Novus).cbr [D:\fs\prg\pd\NZBGet\complete\Comics\0486  Assassin's Creed - The Fall Deluxe Edition (2012) (Epilogue Only) (RedBeard-Empire-Novus)\Assassin's Creed - The Fall Deluxe Edition (2012) (Epilogue Only) (RedBeard-Empire-Novus).cbr] - 13807448 bytes
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : [PARSE-FAILURE][SERIES: Assassin's Creed - The Fall Deluxe Edition][ISSUE YEAR: 2012]
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Exception match: A
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Possible alpha numeric issue (or non-numeric only). Testing my theory.
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : [A] Removing possible alpha issue leaves: 03 (Should be a numeric)
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : Exception match: A
19-Jul-2016 01:05:45 - DEBUG   :: LibraryScan : alphanumeric issue number detected as : 2 A
19-Jul-2016 01:05:45 - ERROR   :: LibraryScan : [IMPORT] Unable to complete the scan: string index out of range
```

**Comment by evilhero** [comment]
Well aside from the failure during file scanning which was due to no valid issue number being within the title (GN's, TPB's and comps aren't supported),  the error looks like it's having a problem with detecting the issue # in the given file (the one with a '2 A'  or '03A' (maybe?) 

Do you have any filenames with such a numbering as without seeing the filename itself I really can't debug the problem properly, let alone try to resolve it.

**Comment by samkatakouzinos** [comment]
This is the list of what I'm attempting to manually scan.
[comics.txt](https://github.com/evilhero/mylar/files/370643/comics.txt)

**Comment by evilhero** [comment]
The A03 Chain Dell 2A types of filenames aren't in a format that Mylar can parse properly. Drop the A03 (whatever the heck that is?) and mylar might have a better shot at parsing the filename. 

Keep in mind that if a series doesn't exist on CV, it's not going to matter if it can parse it or not as it will never find a valid match against CV. 

Also, as an aside - graphic novels, trade paperbacks and compendiums aren't supported in mylar (they might work, they might not - it depends on how CV has named the issues normally)

**Comment by samkatakouzinos** [comment]
May you consider reworking the scan so that it may continue after a failed file attempt?

**Comment by evilhero** [comment]
Ideally that's what it's supposed to be doing - normally if a file fails a file parsing it just continues trucking along, but with those specific filenames it's causing it to error out (which is trapped anyways), and the trap is returning the warning that it can't continue due to the error.

I'll have to check into it some more and see which module is actually causing the error, and maybe I can trap things abit better to accommodate these types of scenarios.

**Comment by ptempier** [comment]
Affected too, could you print out the problematic screen at least ?

**Comment by evilhero** [comment]
There's nothing to print out, if you have mylar in verbose mode, it will say the name of the files that are being scanned in and parsed as it's doing it. 

Without knowing the exact Unicode character that's causing the problem, it's almost impossible to isolate based on just it being Unicode properly.

Indicate the filename(s) that have special characters in them, and I can add specific exceptions into mylar. 

Not sure what else you're asking me to print out...

**Comment by ptempier** [comment]
Humm the filename isn't clean, but apart from that..

10-sept.-2016 01:10:46 - DEBUG   :: LibraryScan : Comic: Valerian_20HS_20-_20Par_20Les_20Chemins_20De_20L_27Espace.cbr [/mnt/video2/ebooks/valerian/Valerian_20HS_20-_20Par_20Les_20Chemins_20De_20L_27Espace.cbr] - 32637694 bytes
10-sept.-2016 01:10:46 - ERROR   :: LibraryScan : [IMPORT] Unable to complete the scan: string index out of range

**Comment by ptempier** [comment]
i replaced the _20 by spaces and now import works.
It couldn't parse the other files, but there were no string index error

Example of another file with the similar name and no such error
Valerian_2011_20-_20Les_20Spectres_20D_27Inverloch.cbr

**Comment by evilhero** [comment]
These are invalid filenames tho - having _20 be representing a space is not typical of a filename that can be parsed properly. Mylar has no way of knowing which is a space or the actual number 20, or if it stands for something else.  You need to format the files so they conform to some standardized naming convention that denotes series, issue # and year.  There's honestly no way that Mylar can parse that information from a file named as such (string error is because of the _20, no error means it couldn't be parsed)
