### ISSUE TITLE
No 'add series' link

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1328]
Hey, so this week, I noticed that some titles in the pull list don't have an 'add series' link.  An example would be 'Hellblazer Rebirth'.  I have "Skip" "Watch" and "One-Off".  Not sure why this is happening.  Also, if I click Watch, nothing happens (I'm actually not sure what should happen here) and if I click "One-Off", I get:

```

Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 1288, in queueissue
    foundcom, prov = search.search_init(ComicName=ComicName, IssueNumber=ComicIssue, ComicYear=ComicYear, SeriesYear=None, Publisher=Publisher, IssueDate=cyear['SHIPDATE'], StoreDate=cyear['SHIPDATE'], IssueID=None, AlternateSearch=None, UseFuzzy=None, ComicVersion=None,allowpacks=False)
TypeError: search_init() got an unexpected keyword argument 'allowpacks'
```

**Comment by skywayskase** [comment]
I just noticed the same thing

**Comment by evilhero** [comment]
The allowpacks error should be fixed as per #1323 in the current development branch. 

The add series link failure will be fixed in the next dev commit

**Comment by thewindupboy** [comment]
THis problem is still happening for series starting this week (i.e. I can't add anything with issue #1)

**Comment by evilhero** [comment]
Are you using the alt_pull =2 method, or just the normal method? 

The problem with #1 issues is that CV doesn't populate the issue data until either today at some point, or even tomorrow (Wed).  So you can't Add a series without there being data for it - you would just have a watch option in this case. If you're using the alt_pull = 2 method, then once the comicid is on CV, it becomes available on the pullist after it does its 4hr cycle check. Then once the issueid is available will it appear as Wanted on the series / upcoming tab. 

You should still have an option to watch though regardless.
