### ISSUE TITLE
500 Internal Server Error on Wanted button

### ISSUE THREAD

**Issue by starkilla2003** [evilhero/mylar#1333]
I am on the latest development commit and everytime when i click on the Wanted button i get the following error:

`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/app/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 1821, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'`

**Comment by evilhero** [comment]
Do a recreate pullist to fix things - due to the changes in the pullist over the last few commits, if you already had the pull populated you need to do the Recreate pullist to line things up again.

**Comment by starkilla2003** [comment]
Thank you for the fast response! I didnt see the option to recreate a pull list, but now i found it and everything works again.
