### ISSUE TITLE
Create a Wiki page for updating, switching/running mylar branches

### ISSUE THREAD

**Issue by samkatakouzinos** [evilhero/mylar#1334]
I would like to be confident in switching branches in mylar. 
Please create a declarative wiki page that spells out how to do this.

I do see often requests to change to development branch to resolve a problem. 
I'm no expert with git and config files yet I'd like to be there one day soon. 

I would very much appreciate the confidence it will provide.

**Comment by evilhero** [comment]
I'll see about it - it needs to get done, but atm I don't have much time to devote to this.

**Comment by Undeadhunter** [comment]
Quick guide to change to the main Development branch 
https://github.com/evilhero/mylar/wiki/Changing-Branch-to-Development
