### ISSUE TITLE
Manage Issue Wanted View Shows Annuals As WantedBut They Have Been Downloaded

### ISSUE THREAD

**Issue by cwsleeper** [evilhero/mylar#1335]
Not even sure how to explain this.

When I go in to Manage/Manage Issues/Wanted, all the annuals show up with a Wanted status. When I click the link to open the Series Annual page in that view, the Series page for the Annual opens, not the Series Annual page.

Now, if I am in Manage/Manage Issues/Downloaded and filter for Annuals, the same Annuals show up there as Downloaded and when I click the link, the Series Annual page displays with a status of Downloaded.

Also, from the main view, if I click the link for an Annual, it opens the Series Annual page and shows all the Annual issues with a Downloaded status.

I have never changed the settings to include the Annual with the Series. I check the  config.ini file and 'annual_on' is set to 0.

I am not sure if this would be captured by any log file. Let me know if you need them and which one. I can also attach screenshots as needed. Thanks.

**Comment by evilhero** [comment]
I'll have to look into this more - alot of the changes that have occurred over the last few months might have altered some of the ways the annuals are handled and need to be converted to the new methods. 

Since I run mine with annual integration enabled, I generally don't see these types of errors unless they're brought up, so I'll do some testing on my end to try and replicate the problem(s) and report back once I figure things out better :)

**Comment by cwsleeper** [comment]
Awesome. Thanks.

**Comment by cwsleeper** [comment]
Update - OK. The issue has now gone away.

The Wanted view occasionally throws a cherry pi error. When that happens I have found a reboot makes it go away. Normally, I just ignore it until I find a time to reboot as I can generally check wanted issues through Manage/Manage Issues.

Anyway, I rebooted today and checked Wanted and it was still giving an error so I decided to check the issues log. There was a recommendation somewhere to recreate  the pull list so I did that. 

Afterwards, I noticed the Annuals were no longer being shown as wanted in either the Manage/Manage Issues/Wanted view or the Wanted page. 

There have been 6 updates since I first logged this as an issue so I am not sure if you fixed it or if simply rebuilding the pull list did it.

**Comment by evilhero** [comment]
The pullist error/recreate is a problem with the upcoming tab atm - the easiest fix for users is to do the recreate pullist option like you did to line things up properly again (I hope to fix this in the next day or two). 

As far as the updates, yes one of the updates had the fix to address the problem you had posted initially about (the reference commit above says the exact commit that had the fix). 

So, am I right in assuming  now that the issue has been resolved for yourself?

**Comment by cwsleeper** [comment]
Yes. It is working. The already downloaded annuals are no longer appearing in the Manage/Manage Issues view as Wanted. 

Thanks!
