### ISSUE TITLE
mktime argument out of range

### ISSUE THREAD

**Issue by AustinYQM** [evilhero/mylar#1338]
Some comic are failing to find and Mylar seems to crash out and thus not keep looking for other comics. 

Here is an example of mktime failing.

```
File "C:\Mylar-Master\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar-Master\mylar\search.py", line 1642, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "C:\Mylar-Master\mylar\search.py", line 232, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Mylar-Master\mylar\search.py", line 800, in NZB_SEARCH
    postdate_int = time.mktime(dateconv[:len(dateconv) -1]) - dateconv[-1]
OverflowError: mktime argument out of range
```

Here is another example with a different comic, this time "Year" is out of range.

```
27-Jul-2016 20:43:36 - ERROR   :: Thread-21 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar-Master\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar-Master\mylar\webserve.py", line 1341, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "C:\Mylar-Master\mylar\search.py", line 232, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Mylar-Master\mylar\search.py", line 800, in NZB_SEARCH
    postdate_int = time.mktime(dateconv[:len(dateconv) -1]) - dateconv[-1]
ValueError: year out of range
```

**Comment by evilhero** [comment]
The posting date is the date that's being returned from the indexer - it's quite possible the indexer isn't returning the posting date in a proper timestamp format for some reason. It's also possible that the date format you have set for the os is causing the problems too (windows has enforced date formats before, albeit not for posting dates - as far as I can remember it was based on the default language of the OS). 

Can you put mylar into verbose mode (-v on startup), and then try the search again.  This issue hasn't come up in close to 2 yrs, which was when the code changed into its' current format, so there might be something more going on here. But without seeing the debugging logs leading up to the error, it's kind of difficult to say atm.

**Comment by AustinYQM** [comment]
Here is the log file with the two errors recreated. I am on Windows 10. I am using Mylar's must recent master branch. I am on Python version 2.7.12.
[mylar.log.txt](https://github.com/evilhero/mylar/files/387569/mylar.log.txt)

I had to reset the file to "wanted" has I had manually downloaded / archived the file from 32p already.

**Comment by evilhero** [comment]
From the log you sent, it looks like the RSS has an invalid date in the db for a particular issue and is causing the problems.  Without seeing what the date format is that it's trying to convert, I can't fix that particular part of it.

However, I'll have to add in an exception / trap where if it fails to do the date conversion, it will just ignore the result since not being able to do the date comparison will make the search results less accurate and possibly result in some issues being downloaded that were snatched when they shouldn't have been. The trap/exception should stop it from erroring out and the searching would continue.
