### ISSUE TITLE
Selection in Import Results not recognised

### ISSUE THREAD

**Issue by bebetech** [evilhero/mylar#1344]
When selecting comics to remove from the import results screen, Mylar does not seem to recognise that comics have been checked.

**Comment by evilhero** [comment]
This should be fixed in the most recent development commit - are you running master / dev ?

**Comment by bebetech** [comment]
Running dev. Will update and try again.

**Comment by bebetech** [comment]
I'm running: Version: 95b9b10786cf912a8af3611c0fd66d6218a5b90a (development)

**Comment by evilhero** [comment]
Is this still an issue? This should be working now based on what I can reproduce on my end
