### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1347]
Been seeing this in the logs. Any idea what it means? Running the latest on the master branch, but it was happening in development as well. 

"Fatal error executing query: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings."

**Comment by evilhero** [comment]
Would have to see the context in the logs leading up to that error (debug logs).  It's trying to write an entry into the dB that's not being converted properly - are you trying to import when you see the error in the logs?

**Comment by glberen** [comment]
I wasn't doing anything in Mylar. It was just running the periodic folder scan, I think. I toggled debug logging on and will watch for it to appear again.

**Comment by evilhero** [comment]
If it's during a folder scan, them it's possibly a filename in that folder that's being monitored that has a special character in it (ie.  not alpha-nuneric)

**Comment by glberen** [comment]
Yeah, that's it, I think. Don't know which file, but I cleared stuff out and the next run completed without issue. Thanks!
