### ISSUE TITLE
Question: Moving comics directory from one drive to another

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1348]
I transplanted the entire folder structure where all my comics files were from one drive to another.
I followed your instructions from the other forum, but I am getting a traceback.
My newcom_dir=d:\comics

Thanks in advance.
-Bruce

**Comment by bguidotti** [comment]
OK - to update on this issue, I found the fields in the config.ini based on a post you made on this forum: http://mylar.forumatic.com/viewtopic.php?f=8&t=235

When I check the log, though, Mylar seems to have thrown an exception when trying to do a mass update.  Any thoughts?

13-Aug-2016 23:22:34 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.2
13-Aug-2016 23:22:34 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
13-Aug-2016 23:22:34 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : C:\Users\Bruce\Documents\GitHub\mylar\cache/
13-Aug-2016 23:22:34 - INFO    :: MAIN : Checking to see if the database has all tables....
13-Aug-2016 23:22:34 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
13-Aug-2016 23:22:34 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
13-Aug-2016 23:22:34 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
13-Aug-2016 23:22:34 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
13-Aug-2016 23:22:34 - INFO    :: MAIN : Retrieving latest version information from github
13-Aug-2016 23:22:35 - INFO    :: MAIN : Mylar is up to date
13-Aug-2016 23:22:35 - INFO    :: MAIN : Performing a one-time mass update to Comic Location
13-Aug-2016 23:22:35 - INFO    :: MAIN : [DIRECTORY-CHECK] Found comic directory: d:\comics
13-Aug-2016 23:22:35 - ERROR   :: MAIN : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\Mylar.pyw", line 275, in <module>
    main()
  File "C:\Users\Bruce\Documents\GitHub\mylar\Mylar.pyw", line 207, in main
    mylar.initialize()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\__init__.py", line 1163, in initialize
    helpers.updateComicLocation()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\helpers.py", line 820, in updateComicLocation
    com_done = re.sub('%&', os.sep, comlocation).strip()
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Python27\lib\re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Python27\lib\re.py", line 273, in _compile_repl
    raise error, v # invalid expression
error: bogus escape (end of line)

**Comment by evilhero** [comment]
What's the path your using for the new location and what's the old location path (what your Comic Location should be set to prior to running the mass update). 

Do you have the folder formatting enabled for the mass import as well (the ff_to_new_comdir option)?

**Comment by bguidotti** [comment]
d:\comics is the new location
the old location path is y:\comics (which was a network share mapped to a local drive letter)
the fftonewcom_dir option was set to 0 because I wanted the paths to stay exactly the same other than the drive letter change.

**Comment by evilhero** [comment]
can you paste in your config.ini options for your destination_dir and newcom_dir values within the config.ini?

**Comment by bguidotti** [comment]
[General]
git_user = evilhero
git_branch = development
**destination_dir = y:\comics**
multiple_dest_dirs = ""
create_folders = 1
delete_remove_dir = 0
chmod_dir = 0777
chmod_file = 0660
chowner = JAGA\Bruce
chgroup = Administrators
usenet_retention = 15000
alt_pull = 0
search_interval = 360
nzb_startup_search = 1
add_comics = 1
**comic_dir = y:\comics**
blacklisted_publishers = None
imp_move = 0
imp_rename = 0
imp_metadata = 1
enable_check_folder = 0
download_scan_interval = 5
folder_scan_log_verbose = 0
check_folder = ""
interface = default
dupeconstraint = filesize
ddump = 0
duplicate_dump = ""
autowant_all = 1
autowant_upcoming = 1
preferred_quality = 0
comic_cover_local = 1
correct_metadata = 0
move_files = 0
rename_files = 1
folder_format = $Series ($Year)
file_format = $Series $Issue ($Year)
blackhole_dir = ""
replace_spaces = 0
replace_char = .
zero_level = 1
zero_level_n = 00x
lowercase_filenames = 0
ignore_havetotal = 0
snatched_havetotal = 0
syno_fix = 0
allow_packs = 0
search_delay = 1
grabbag_dir = y:\comics
highcount = 0
read2filename = 1
send2read = 0
tab_enable = 0
tab_host = ""
tab_user = ""
tab_pass = ""
tab_directory = ""
storyarcdir = 1
copy2arcdir = 1
use_minsize = 0
minsize = ""
use_maxsize = 0
maxsize = ""
add_to_csv = 1
cvinfo = 0
log_level = 0
enable_extra_scripts = 0
extra_scripts = ""
enable_pre_scripts = 0
pre_scripts = ""
post_processing = 1
post_processing_script = ""
file_opts = move
weekfolder = 1
weekfolder_loc = ""
**locmove = 1**
**newcom_dir = d:\comics**
**fftonewcom_dir = 0**
enable_meta = 0
cbr2cbz_only = 0
ct_tag_cr = 1
ct_tag_cbl = 1
ct_cbz_overwrite = 0
unrar_cmd = None
cmtag_start_year_as_volume = 0
update_ended = 0

**Comment by bguidotti** [comment]
After the newest update, I get:
C:\Users\Bruce\Documents\GitHub\mylar>python Mylar.py -v
16-Aug-2016 22:51:03 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Users\Bruce\Documents\GitHub\mylar
16-Aug-2016 22:51:03 - INFO :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.2
16-Aug-2016 22:51:03 - DEBUG :: MAIN : Logger set to use : Concurrent Rotational Log Handler
16-Aug-2016 22:51:03 - DEBUG :: MAIN : Trying to execute: "git rev-parse HEAD" with shell in C:\Users\Bruce\Documents\GitHub\mylar
16-Aug-2016 22:51:03 - DEBUG :: MAIN : Git output: a84069d8d2bd478e0d9c4d878dd9b04433656d11

16-Aug-2016 22:51:03 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
16-Aug-2016 22:51:03 - INFO :: MAIN : [Cache Check] Cache directory currently set to : C:\Users\Bruce\Documents\GitHub\mylar\cache/
16-Aug-2016 22:51:03 - INFO :: MAIN : Checking to see if the database has all tables....
16-Aug-2016 22:51:03 - INFO :: MAIN : Populating Base Exception listings into Mylar....
16-Aug-2016 22:51:03 - INFO :: MAIN : Populating Custom Exception listings into Mylar....
16-Aug-2016 22:51:03 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
16-Aug-2016 22:51:03 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
16-Aug-2016 22:51:03 - INFO :: MAIN : Retrieving latest version information from github
16-Aug-2016 22:51:03 - DEBUG :: MAIN : Comparing currently installed version [a84069d8d2bd478e0d9c4d878dd9b04433656d11] with latest github version [a84069d8d2bd478e0d9c4d878dd9b04433656d11]
16-Aug-2016 22:51:03 - INFO :: MAIN : Mylar is up to date
16-Aug-2016 22:51:03 - INFO :: MAIN : Performing a one-time mass update to Comic Location
16-Aug-2016 22:51:03 - INFO :: MAIN : [DIRECTORY-CHECK] Found comic directory: d:\comics
16-Aug-2016 22:51:03 - ERROR :: MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 275, in <module>
    main()
  File "Mylar.py", line 207, in main
    mylar.initialize()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\__init__.py", line 1163, in initialize
    helpers.updateComicLocation()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\helpers.py", line 820, in updateComicLocation
    com_done = re.sub('%&', os.sep, comlocation).strip()
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Python27\lib\re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Python27\lib\re.py", line 273, in _compile_repl
    raise error, v # invalid expression
error: bogus escape (end of line)

Traceback (most recent call last):
  File "Mylar.py", line 275, in <module>
    main()
  File "Mylar.py", line 207, in main
    mylar.initialize()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\__init__.py", line 1163, in initialize
    helpers.updateComicLocation()
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\helpers.py", line 820, in updateComicLocation
    com_done = re.sub('%&', os.sep, comlocation).strip()
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Python27\lib\re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Python27\lib\re.py", line 273, in _compile_repl
    raise error, v # invalid expression
sre_constants.error: bogus escape (end of line)

**Comment by evilhero** [comment]
Well that update didn't have anything to do with your issue - so it's understandable that you're still having the problem ;) 

I'll try and look into this later today  - it was working at one point, but it looks like it's having problems escaping the slashes now for some reason.

**Comment by bguidotti** [comment]
Haha! I wasn't implying that it did.  The traceback looked slightly different, so I just posted my newest results. :)  Thanks for checking!

**Comment by evilhero** [comment]
Got it fixed now in my local branch - should be able to push it out in the next few hours ;) Sorry for the long delay in fixing this, haven't been able to sit in front of the machine to do testing until now...

**Comment by bguidotti** [comment]
Awesome! What was the issue? Was I doing something wrong or in a way you didn't expect?

**Comment by evilhero** [comment]
Nothing you did - apparently my testing on Windows machines is somewhat lacking. I do remember testing a few times against this as there were several issues, but it turns out that the slashes used in windows file addresses are actually considered an escape character and was causing some problems. I tested it out on a windows machine, as well as linux now, so the error message you were getting should now be gone when you use the fix ;)
