### ISSUE TITLE
TypeError in PostProcessor

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1350]
I just noticed this error coming up after I clicked "Go Manual Run!".

```
13-Aug-2016 20:48:55 - WARNING :: Thread-243 : A-Force is either Paused or in an Ended status with 100% completion.
13-Aug-2016 20:48:55 - INFO :: Thread-243 : Series_Name: A-Force --- WatchComic: A-Force
13-Aug-2016 20:48:55 - INFO :: Thread-243 : Series_Name: ACTION COMICS --- WatchComic: Action Comics
13-Aug-2016 20:48:55 - INFO :: Thread-243 : [POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 27000 for ComicID: 42563 / IssueID: 441372
13-Aug-2016 20:48:55 - ERROR :: Thread-243 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\PostProcessor.py", line 482, in Process
    if int(watch_issueyear) == int(watchmatch['issue_year']):
TypeError: int() argument must be a string or a number, not 'NoneType'

Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\PostProcessor.py", line 482, in Process
    if int(watch_issueyear) == int(watchmatch['issue_year']):
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by evilhero** [comment]
Either the series or the filename doesn't have an issue year - it's hard for me to tell without looking at the debug logs and knowing what the filename is that's causing it to hang. 

Can you out mylar in verbose mode and try again, and then paste the log back?

**Comment by jerblack** [comment]
I ended up with several files in the format "TITLE # ISSUE_NUMBER" and that is what seems to be generating the error. It doesn't happen for all files in the format though. 

For example, the error is generated with these files:
ACTION COMICS # 027.cbr
ACTION COMICS # 029.cbr
BATMAN # 027.cbr
SUPERGIRL # 025.cbr
JUSTICE LEAGUE # 026.cbr
GREEN LANTERN # 027.cbr

The error is not generated for these however:
AQUAMAN AND THE OTHERS # 006.cbr
ANIMAL MAN # 027.cbr
BATMAN AND TWO FACE # 025.cbr
THE NEW 52 - FUTURES END # 022.cbr
TRINITY OF SIN - PANDORA # 007.cbr

If I had to guess, I would say this is only happening for file names in that format that could possibly match to multiple series. I can manually fix the files, but the real problem is that every time an error is generated on a particular file, it stops the manual run process there and no further files are processed. This makes the import process fragile and at the moment, when I am importing a large number of files, there's a lot of tending to the process that I need to do.

**Comment by evilhero** [comment]
The error should be fixed in the latest development commit I believe. It was due to not having a year in the filename when mylar was expecting one (if/case was wrong). It should now just either skip over said files OR assume it's a vs and post-process them as such, as the only acceptable issues that should be allowed to have a non-volume label in a multi-volume series are v1.
