### ISSUE TITLE
Error during Manual Searching or Force Check on Wanted Page

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1352]
Mylar Version: development
-- git build a850e386d41f3a88dfc8d04192f021a2081a27b6.
Python Version : 2.7.11+

> Uncaught exception: Traceback (most recent call last):
File "/home/ben/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/ben/mylar/mylar/search.py", line 1674, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/home/ben/mylar/mylar/search.py", line 291, in search_init
if searchprov == '32P' and mylar.MODE_32P == 0:
UnboundLocalError: local variable 'searchprov' referenced before assignment

**Comment by evilhero** [comment]
It'd a problem with your provider_order line in the config.ini. Either it got messed up somehow, or you made a provider change of some kind in the GUI and didn't do a restart of mylar. 

Shutdown mylar and edit the config.ini. Then find the provider_order line and delete the entire line. Start up mylar and it will generate a new provider_order on startup that's correct.

**Comment by BenBeyond** [comment]
Thanks for the quick reply, that fixed it.
