### ISSUE TITLE
32P plugin failing auth

### ISSUE THREAD

**Issue by icebal** [evilhero/mylar#1362]
the test in the config tab is successful, but mylar is constantly failing auth in the log and caused IP bans. using Auth mode, and the latest dev. i have had to turn it off, and can get the log of it when the IP ban is resolved.

**Comment by evilhero** [comment]
If the test in the config is successful then it's cached the session cookies and it wouldn't ask again for authentication. Unless the captcha was up during a signon (although with the cookies it wouldn't mattet either, unless it was in during the initial logon), it really shouldn't trip the ip ban. 

I'd need to see the log to try and figure out what exactly is happening - unless you're using a vpn with mylar  I'm kind of at a loss atm why it would happen as I've been using it for almost a year with nothing like this happening (aside from when the captcha was up on the signon page, but the cookie session that Mylar now uses ended that). 

I mean mylar even has an official forum thread on 32p and I've worked with the coder directly on the login /searching so as to not cause any problems for them. So I'm really interested in seeing the logs so I can figure out where the problem might lie...

**Comment by icebal** [comment]
i was working with said coder, and he and i verified it was the same creds. after i changed my pass it started working again. will keep an eye out. i stress we verified it was the correct pass, i swear im not losing my mind!

**Comment by icebal** [comment]
looks to be a permissions issue, I migrated to an SSD and the issue happened again. Righted the permissions on the drive and should be good now, waiting for the ban to lift.

**Comment by evilhero** [comment]
Do you remember what permissions you changed - I'm assuming it was for your Comic Location path, butid be interested in knowing if it was elsewhere( cache directory, or if you use a local watchdir /blackhole). 

Sorry for the problems, I honestly haven't come across this at all and I'm still wanting to try and fix this going forward somehow.

**Comment by icebal** [comment]
the only ones changed were the cache, config files and folders. I will play around with it and see what I can do to make it happen again, I just don't want it to lock out immediately lol.
