### ISSUE TITLE
Multi-select on comicDetails page does nothing

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1367]
At the moment, if you click the multi-select checkbox at the top of the list of comics, nothing gets selected. This should select all the comics on the page.

While you're at it, if you could implement range selection using the shift key in in that view as well, that would be awesome. By that I mean selecting a checkbox next to an issue, holding down the shift key and selecting another checkbox multiple rows down, and the page should automatically select all rows in between the two selected rows. Thanks.

**Comment by evilhero** [comment]
The multi-select works for myself - I'm wondering if it might be browser related (I'm using chrome atm).  But it does work and it does select all the issues on the given page. 

I don't see myself trying to figure out how to implement the shift key selection option tbh. Unless it's just an option in the datatables, I probably wouldn't be able to put it in, as the methodology would be beyond my knowledge.

**Comment by AtariBaby** [comment]
Occurs in iOS 10.2 safari
