### ISSUE TITLE
Just set up Mylar, choosing wanted throws error

### ISSUE THREAD

**Issue by Aaranaw** [evilhero/mylar#1371]
Hi, just set up Mylar, as a test I have selected a comic and gone into the "comic details" page, when I select "wanted" from the drop down menu I get an "there was an error" message on the bottom of the screen. I have checked the logs but there is nothing in there to help diagnose the problem, I have also enabled debugging logs and tried again with no messages to help.
How do I go about figuring out why this is happening?

Thanks.

**Comment by evilhero** [comment]
The wanted error could be related to a number of different things - not having any providers enabled (nzb/torrents), invalid issue date for a given issue (if it was still populating the data), or even the 0 search providers error message. 

Can you restart mylar, make sure the debug logs are on and then try to mark an issue as Wanted again and then paste the relevant section of the log in here?

Also if you could provide the branch and commit you're running it would be helpful too (as well as the OS and version of python too)

**Comment by Aaranaw** [comment]
Cleared the logs, enabled debug then when into the comic and clicked the wanted tab, nothing is added to the log file.

Configuration Options
Mylar Version: master
-- git build 562a8a851204051c1a60a63d80f6b1beb1b499fa.
Python Version : 2.7.12

OS is Ubuntu.

**Comment by evilhero** [comment]
OK so maybe there's a bit of confusion about how to mark an issue as wanted (I'm guessing). 

In order to use the drop down selector on the comic details page you need to select one or more issues using the checkboxes beside each  issue number. Once you've selected the issues you then select the option from the drop down and it will perform that action (ie mark ad wanted) 

You can also use the checkmark icon beside each issue to mark the issue as Wanted, or use the magnifying glass to not mark it as Wanted but perform an immediate search for said issue. 

Hope that helps!

**Comment by dilbaggins** [comment]
got this as well after latest update:

heres the error im getting (when i click the Wanted Menu):

Traceback (most recent call last):
  File "/home/pop/.mylar/cherrypy/_cprequest.py", line 645, in respond
  File "/home/pop/.mylar/cherrypy/lib/encoding.py", line 188, in __call__
  File "/home/pop/.mylar/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/home/pop/.mylar/mylar/webserve.py", line 1853, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by evilhero** [comment]
Shouldn't be happening still, I'll have to look into it again. 

To get rid of the error, just go to your Weekly tab and do a Recreate pullist and it will line things up again.

**Comment by dilbaggins** [comment]
that fixed it thanks @evilhero
