### ISSUE TITLE
Can't import a comic with a special character (") in the name

### ISSUE THREAD

**Issue by flvinny521** [evilhero/mylar#1372]
I have a specific comic I am trying to add in Mylar that has quotation marks in the name. Obviously, a folder can not be created, as a folder name can not contain quotes in Windows. Is there any workaround for this? Is it possible to auto-convert prohibited characters to something else when adding a new title?

**Comment by kellenarb** [comment]
See issue #1369

**Comment by evilhero** [comment]
Series with double quotation marks will be fixed in the next development commit (folder creation)

**Comment by flvinny521** [comment]
@evilhero I just updated in an attempt to test the fix, but I can't get the new dev version to run. I tried updating through the UI, and also installing from scratch.

**Comment by evilhero** [comment]
What's the error message /log  when you run mylar from the command line?

**Comment by flvinny521** [comment]
`Traceback (most recent call last):
  File "D:\Storage\Misc\mylar-development\Mylar.py", line 26, in <module>
    import mylar
  File "D:\Storage\Misc\mylar-development\mylar\__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, sear
ch, PostProcessor, weeklypull, helpers, scheduler
  File "D:\Storage\Misc\mylar-development\mylar\rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "D:\Storage\Misc\mylar-development\mylar\rsscheck.py", line 7, in <module>
    import lib.cfscrape as cfscrape
  File "D:\Storage\Misc\mylar-development\lib\cfscrape\__init__.py", line 7, in <module>
    import lib.js2py as js2py
  File "D:\Storage\Misc\mylar-development\lib\js2py\__init__.py", line 67, in <module>
    from .evaljs import *
  File "D:\Storage\Misc\mylar-development\lib\js2py\evaljs.py", line 4, in <module>
    from .translators import translate_js, DEFAULT_HEADER
  File "D:\Storage\Misc\mylar-development\lib\js2py\translators\__init__.py", line 25, in <module>
    from .pyjsparser import PyJsParser, Node, WrappingNode, node_to_dict
  File "D:\Storage\Misc\mylar-development\lib\js2py\translators\pyjsparser.py", line 21, in <module>
    from .pyjsparserdata import *
  File "D:\Storage\Misc\mylar-development\lib\js2py\translators\pyjsparserdata.py", line 24, in <module>
    import six
ImportError: No module named six`

**Comment by evilhero** [comment]
Ahh crap.  Six.. OK hang on

**Comment by evilhero** [comment]
OK I can't get to my machine atm (hdd),  you can do a 'pip install six' command from a command (assuming you have pip installed and it will install that module and it will work)... Hopefully can get back online and fix this :/

**Comment by flvinny521** [comment]
Simple enough, that did the trick, and I was able to add the comic in question. The renamer still tried to use the double quotes, though, so it failed. I just named the file manually.

**Comment by evilhero** [comment]
Oh the renamed - I just did the import /add... How was it trying to rename - during the import process of moving files, or a manual rename, or even post-processing?

**Comment by flvinny521** [comment]
I moved the single issue over to the automatically created folder, manually ran a "recheck files" to make sure it was located, and then manually ran the renamer from the series detail screen. The log showed the attempted filename still had the double quotes, so I just removed them and renamed the file manually in Windows.
