### ISSUE TITLE
Mylar Master open

### ISSUE THREAD

**Issue by dsawejka** [evilhero/mylar#1382]
Hello, mylar master wont start.
please help.

**Comment by evilhero** [comment]
Need more info - debug logs, problem? What is the error when you start it? 

Help me, to help you.

**Comment by dsawejka** [comment]
When i click on the Mylar.py it opens in Python for 3 secs and then closes.
I am on version 2.7.11

**Comment by dsawejka** [comment]
09-Sep-2016 09:33:58 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 10.0.0.16
09-Sep-2016 09:33:58 - INFO    :: MAIN : Branch detected & set to : master
09-Sep-2016 09:33:58 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
09-Sep-2016 09:33:58 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : G:\mylar-master\mylar-master\cache
09-Sep-2016 09:33:58 - INFO    :: MAIN : Checking to see if the database has all tables....
09-Sep-2016 09:33:58 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
09-Sep-2016 09:33:58 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
09-Sep-2016 09:33:58 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
09-Sep-2016 09:33:58 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
09-Sep-2016 09:33:58 - INFO    :: MAIN : Retrieving latest version information from github
09-Sep-2016 09:33:59 - INFO    :: MAIN : You are running an unknown version of Mylar. Run the updater to identify your version
09-Sep-2016 09:33:59 - INFO    :: MAIN : Remapping the sorting to allow for new additions.
09-Sep-2016 09:33:59 - INFO    :: MAIN : Sucessfully ordered -1 series in your watchlist.
09-Sep-2016 09:33:59 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/

**Comment by evilhero** [comment]
You can't double click on the .py file in windows, it's not an executable. 

Change the extension of Mylar.py to Mylar.pyw and then you should be able to run  it as it will run in the background thereafter.

**Comment by dsawejka** [comment]
Still nothing

**Comment by evilhero** [comment]
You didn't change the extension properly then. Mylar is a Python program which cannot run as an executable in windows. You have to run it from a command line (gitshell preferably or does even, but python has to be in your path) otherwise via : python Mylar.py -v

**Comment by dsawejka** [comment]
I can double click it on my old pc and it opens the web interface.
Now nothing on my new pc.

**Comment by evilhero** [comment]
It's a problem with the new pc then - maybe you don't have python in the environment path. Once again,  try just getting it running before you try changing how to start it...
