### ISSUE TITLE
Service consistently exiting

### ISSUE THREAD

**Issue by JasonMSims** [evilhero/mylar#1383]
A fresh install of Mylar on Ubuntu Mate (RPi2) is consistently moving to Active: active (exited).  below is the service status:

```
media@mediaserver:~$ sudo service mylar status
● mylar.service - LSB: starts instance of mylar
   Loaded: loaded (/etc/init.d/mylar; bad; vendor preset: enabled)
   Active: active (exited) since Sun 2016-09-11 17:53:58 EDT; 5min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16296 ExecStop=/etc/init.d/mylar stop (code=exited, status=0/SUCCESS)
  Process: 16304 ExecStart=/etc/init.d/mylar start (code=exited, status=0/SUCCESS)

Sep 11 17:53:20 mediaserver systemd[1]: Starting LSB: starts instance of mylar...
Sep 11 17:53:20 mediaserver mylar[16304]:  * Removing stale /var/run/mylar/mylar.pid
Sep 11 17:53:21 mediaserver mylar[16304]:  * Starting mylar
Sep 11 17:53:58 mediaserver mylar[16304]:    ...done.
Sep 11 17:53:58 mediaserver systemd[1]: Started LSB: starts instance of mylar.
```

I'm using the default Ubuntu init.d script with the proper variable set in /etc/default/mylar.

I make a habit of turning on debug logging every time I fire up Mylar or reboot.  I didn't see anything in the logs that seems relevant, but have all logs from the last attempted run set aside in case they are needed.  The approximate time the service was running was probably about 4 minutes.

Is it possible that the RPi2 is just being overwhelmed from a system resources standpoint and forces the service to exit?  I didn't run into anything similar to this on Raspbian.

**Comment by evilhero** [comment]
It shouldn't be overwhelmed - well unless you have over a thousand series on your watchlist, then that might take time for it to generate the main page and in that time it might be considered a timeout and kill the service.

Does it run normally if you were to start it via command line and let it run for 4/5 minutes to see if it crashes or something is logged that might be causing it ?

**Comment by JasonMSims** [comment]
Yep, it starts running normally when started via CLI, but only for a few minutes.  Then if I navigate to another page or refresh, no data is sent to the browser, I check the status of the service and it shows active (exited).  During the few minutes that it is running I have tried both not doing anything and navigating through to different pages and viewing the logs in browser, etc.  There are some books that are awaiting post processing and I have a simply bash script tagged on at the end of the post processing, but most of the time, it's not even making it to any of that stuff before the service exits.

**Comment by evilhero** [comment]
Can you run it via the command prompt (not as a service), and let it run so that it's throwing the logs at the console?  If it's exiting after a few minutes, then it's trying to do something and erroring out to the extent that it ends the program for some reason (usually it's a traceback, but the program continues to run). Any tracebacks that are occurring would be in the console, if it wasn't getting logged into the logs due to the nature of the request being performed.

**Comment by JasonMSims** [comment]
Ahhh, now I'm following you.  I just ran the Python script in verbose mode twice, and it was killed after a few minutes.  The first time, it was searching for an issue, and the second time, it was running a post-processing script.  Both times it simply interjects:
```
Killed
```

Into the CLI, and returns the terminal to me.

**Comment by evilhero** [comment]
There were no traceback or error messages in the console prior to the killed message? 

I've never seen it return a killed unless there's more than one mylar instance running and it's trying to kill one in order to start the other. 

Just for curiosity, which version of python are you running mylar against?

**Comment by JasonMSims** [comment]
Correct, there were no tracebacks or errors present at all.  I'm running 2.7.12.  Fun fact though, this morning, I overclocked the rpi2, rebooted, and started up the service again.  Mylar's still running strong currently.

**Comment by evilhero** [comment]
Maybe it is stressing the pi too much - how many issues do you have on your Wanted tab, and how many series do you have on your watchlist?

**Comment by JasonMSims** [comment]
Currently, I have 67 wanted issues (was 84 earlier).  I looked through the UI, but am not sure where to locate the watchlist summary.  According to the logs:

```
INFO	Sucessfully ordered 395 series in your watchlist.
```

**Comment by evilhero** [comment]
Well 395 isn't a lot perse, but it's still a fair amount. I wouldn't have thought that it would be an overload factor, but based on what you've presented it would appear that the RPi2 can't handle that many for whatever reason. Does the Raspbian work without these issues? 

It shouldn't be python related, but the threading calls might be just too much possibly - between loading the GUI, searching, grabbing rss feeds and post-processing on scheduled times. I honestly haven't run into this before, save for if you have lots of series on your watchlist and it takes a few mins to load up...or, what is your search interval set to with the GUI?

**Comment by JasonMSims** [comment]
The search interval is set to 720 minutes.  Raspbian didn't _seem_ to have these issues, but I also was having various search issues that I didn't have sorted until after setting up in Mate (due to the provider order line), so maybe it just wasn't being taxed this hard.  I don't have currently have a Raspbian box, but am setting one up now to test.

**Comment by JasonMSims** [comment]
After moving everything over to a VM and away from the RPi, it seems I'm able to confirm that I was taxing the CPU on the RPi2 too hard.
