### ISSUE TITLE
iOS Safari not opening when Password

### ISSUE THREAD

**Issue by perezbalen** [evilhero/mylar#1384]
Hi

I recently encountered a problem when securing my installation of Mylar.
When Mylar has **HTTP Username and Password**, iOS Safari wont load it (iPhone and iPad). iOS Chrome and desktop Safari will, but not **iOS Safari**; it will load forever (and never ask for  credentials). When there is no HTTP Username and Password, the pages load with no problem.

Currently running: 
Version: cb7da2e6a3f0d65f6f6948a8374fc3ed1996dc30 (development) 
on OS X 10.11.6 El Capitan

**Comment by evilhero** [comment]
Do you have a password manager or something similar running on Safari?  Or autofill - basically anything that has control over your login info and can submit it for you.

**Comment by perezbalen** [comment]
I dont't have password manager in safari 
I do have SMB shares mounted.

**Comment by evilhero** [comment]
Try to unmount the smb shares and see if that helps (you might have to restart mylar if it's running). I'm not sure if you have to unmount on the server, or the ios side of things - but the loading problem seems documented ( https://discussions.apple.com/message/27727310#27727310)

**Comment by perezbalen** [comment]
It doesn't seem to be the problem. I disabled SMB and AFP, restarted everything (even rebooted), and the behavior remains. 
And from what I gather from the apple discussion, the problem is with desktop safari: 

> "Mobile Safari works fine, though of course iOS devices don't auto-fill 401-response logins and are logged in as root."

**Comment by perezbalen** [comment]
Fount it! 
It was actually what @evilhero said first. Safari (in settings) had the website with a different login/password saved, and apparently it was looping trying that password. I deleted that password, and the interface asked again (and now it loads).

Thanks.
