### ISSUE TITLE
Mylar stops working periodically. Best sequence for troubleshooting?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1385]
Hi

Every 2-4 weeks, I'll try to access Mylar, only to discover it's not running. I usually just start it up, eager to get my precious mylar grabbing comics. But today I've got uncharacteristic patience.

Before I manually start it up, what's the best sequence of events to identify why it stops, and how to prevent?

Gregory

**Comment by evilhero** [comment]
Put in debug/verbose mode when you're running it.  The logs will fill up fast (set the log size to like 20mb+), but I'm betting there's a traceback error or 2 in there that's causing mylar to deadlock. 

Otherwise, if you haven't started it up yet, the previous logs would still be available to view so scope out the end of the mylar.log file and see if there are any errors/warnings in there

**Comment by AtariBaby** [comment]
Cool, haven't started yet. Looking now...

**Comment by AtariBaby** [comment]
huh! I have no logs since August 27. I'm positive it has run since then. Was the default location for logs moved from C:\Windows\Mylar\logs ?

**Comment by AtariBaby** [comment]
I'll go ahead and restart it.

**Comment by AtariBaby** [comment]
Hmm. bigger problem! My Mylary.vbs file doesn't start Mylar anymore, and opening Mylar.py doesn't start it, either.

**Comment by evilhero** [comment]
If you've updated recently, the Mylar.py file had some changes in it - so your .vbs file is probably pointing to the wrong .pyw file (I'm assuming it's been renamed to .pyw, not as it is). So just rename the Mylar.py file to Mylar.pyw and you should be good to go again.

**Comment by AtariBaby** [comment]
I renamed mylar.py to .pyw, no change.

I edited the mylar.vbs file line from .py to .pyw, no change.

"ERR_CONNECTION_REFUSED" in Chrome.

Should I change either of those back?

**Comment by evilhero** [comment]
Change it back to the .py file. 

Connection refused would mean either something is still running, or you're accessing the wrong port possibly

**Comment by AtariBaby** [comment]
I changed them back. No idea what to do or what's wrong. I see the port I'm using is still in the config.ini file. I have also rebooted this computer and no change.

**Comment by AtariBaby** [comment]
If I run this from cmd, this is what I see:

```
C:\Users\xboxl_000>python.exe C:\Mylar\Mylar.py
Traceback (most recent call last):
  File "C:\Mylar\Mylar.py", line 26, in <module>
    import mylar
  File "C:\Mylar\mylar\__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "C:\Mylar\mylar\rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "C:\Mylar\mylar\rsscheck.py", line 7, in <module>
    import lib.cfscrape as cfscrape
  File "C:\Mylar\lib\cfscrape\__init__.py", line 7, in <module>
    import lib.js2py as js2py
  File "C:\Mylar\lib\js2py\__init__.py", line 67, in <module>
    from .evaljs import *
  File "C:\Mylar\lib\js2py\evaljs.py", line 4, in <module>
    from .translators import translate_js, DEFAULT_HEADER
  File "C:\Mylar\lib\js2py\translators\__init__.py", line 25, in <module>
    from .pyjsparser import PyJsParser, Node, WrappingNode, node_to_dict
  File "C:\Mylar\lib\js2py\translators\pyjsparser.py", line 21, in <module>
    from .pyjsparserdata import *
  File "C:\Mylar\lib\js2py\translators\pyjsparserdata.py", line 24, in <module>
    import six
ImportError: No module named six
```

**Comment by AtariBaby** [comment]
willing to start from scratch or whatever is best

**Comment by evilhero** [comment]
Ahh OK you're between commits that fixed that error. Over the course of a few commits, transmission support was added and all the libs got moved into the lib directory. It's trying to load a module it can't find now. 

Your best bet at this point is to just do a git pull from within the mylar directory and see if that works. If it doesn't then you'd have to save your config.ini, mylar.db,and cache folder and wipe out your existing installation and do a fresh git clone.

**Comment by AtariBaby** [comment]
![](http://i.giphy.com/cQNRp4QA8z7B6.gif)
