### ISSUE TITLE
tzlocal warning when starting Mylar - Windows 10

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1398]
I'm getting the following warning when starting Mylar (this just started happening with the last update):

Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
C:\Users\Bruce\Documents\GitHub\mylar\lib\js2py\constructors\time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)

**Comment by evilhero** [comment]
It's a warning asking for a local install, it shouldn't break anything ad far as I'm aware.  Do you have pip installed for python? A simple fix is to just do a 'pip install tzlocal'  and it would make the warning go away. 

I can look into including it, but atm I'm unsure of how localized the module is when it's installed.

**Comment by bguidotti** [comment]
Non-Critical - install PIP as suggested.

Thanks!
