### ISSUE TITLE
RSS-Check spams the console

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1399]
Is there a way to get RSS-Check on Windows to stop spamming the Python Console?
It endlessly rolls these three lines:

24-Sep-2016 20:01:45 - INFO :: RSSCHECK : allow_packs:False
24-Sep-2016 20:01:45 - INFO :: RSSCHECK : experimental
24-Sep-2016 20:01:45 - INFO :: RSSCHECK : rss:yes

-Bruce

**Comment by evilhero** [comment]
Yes, I thought I had removed those lines from the logging as they're all indicated earlier in the given search. 

I'll try and push out a quick fix later tonight if I can get to my laptop to address this.

**Comment by bguidotti** [comment]
This is still happening.
