### ISSUE TITLE
Mylar on Syno GUI failures

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1408]
Mylar Version: master
-- git build ed263d8784cb14859def1fd8cca479708f496013.
Python Version : 2.7.11

Running on an Synology Diskstation 716+ via SynoCommunity's Mylar package. 

Mylar asked for an update yesterday.  Today, while I can successfully load the landing page,  clicking the This Week button just hangs with no response; clicking the Wanted Button throws the following error: 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1853, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

Manage, History, Setting, and Logs all work correctly.  

In checking things out, I note that my Version shows I'm on Master branch, but I've updated Versionchecker.py and version.py to point to the Dev branch.  Is that no longer the way to point Mylar to the Dev branch on synology?

**Comment by evilhero** [comment]
The wanted error can be fixed by just  going into your Weekly pull tab and doing a Recreate Pullist. It will then ljne everything back up as it should be (the fix for this is now in development awaiting testing). 

As far as the branch problem, the versionchecker / version py files aren't needed anymore. Haven't been for awhile actually.. You can control the branch via the config.ini and setting the git_branch variable to development instead of master. I'm not sure tho if the syno package locks you into the master branch on startup, as I don't use one.

**Comment by ForumFerret** [comment]
Ah, I see - got updated to Dev version ed263d8784cb14859def1fd8cca479708f496013 at least. 

Still getting the same error when trying to load the Wanted tab and timeout/no response when trying to load "This Week" tab.  Is there any other way to recreate the pull list? I can't load the "This Week" tab, and as such cannot hit the recreate pulllist button.

**Comment by evilhero** [comment]
What is your alt_pull set to in the config.ini?

**Comment by ForumFerret** [comment]
alt_pull=0

**Comment by evilhero** [comment]
Argh it's a mess atm. The error slipped thru dev and is in master, but affects dev to. Think I have it fixed on my local, so gonna do a push to both branches shortly to try and fix things.

**Comment by ForumFerret** [comment]
Thanks EH!

**Comment by ForumFerret** [comment]
Fixed! Updated to latest dev, let it do it's thing, and now I can access Wanted/This Week again.
