### ISSUE TITLE
Is it possible to have more than one user?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1409]
I was thinking of giving a friend of mine access to Mylar, because of the easy click to download feature (which is really brilliant). But that would require giving them my username and pass.

Is it possible for me to add another credential, i.e., to add additional logins? For example, to the config file?

**Comment by evilhero** [comment]
No, there is no user list available for authentication. It might be something to consider as an enhancement, at least on a basic access level (not even considering how far it can go - different user databases, options dependent on access levels, etc)

**Comment by AtariBaby** [comment]
Understood. Don't knock yourself out! Just a thought.
