### ISSUE TITLE
Issues change individual arc options.

### ISSUE THREAD

**Issue by darknessgp** [evilhero/mylar#1413]
Trying to set "Copy watchlisted issues to StoryArc Directory" to true, but running into this error whenever I push the update button on an existing story arc. I receive the error even if I don't change an option.

404 Not Found

The path '/mylar/readOptions' was not found.

Traceback (most recent call last):
  File "/software/mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/software/mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/software/mylar/lib/cherrypy/_cperror.py", line 387, in __call__
    raise self
NotFound: (404, "The path '/mylar/readOptions' was not found.")
Powered by CherryPy 3.2.0

**Comment by evilhero** [comment]
Are you using a reverse proxy with mylar, or using the base_url option?

**Comment by darknessgp** [comment]
Yes, I'm using a reverse proxy with http_root set to /mylar. It appears to work well for everything else.

**Comment by evilhero** [comment]
Ahh yeah with that error I thought so. I need to update the return path for that function (since I don't run reverse proxy with mylar I don't come across these issues until they happen to someone else) - I'll try and commit up a fix it in abit.
