### ISSUE TITLE
Unable to change to development branch on Synology

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1414]
Hi, I followed the steps described on this [issue](https://github.com/evilhero/mylar/issues/354#issuecomment-17786844) to replace master with development on my Synology Mylar package but it didn't work.

I am missing anything?

**Comment by evilhero** [comment]
You don't need to change the py files any longer as far as I'm aware. 

Just need to change the config.ini option for git_branch from master to development (with mylar not running)

**Comment by WedgeSparda** [comment]
@evilhero Great. It worked.

For those using Mylar on a Synology NAS, config.ini file is in folder _/volume1/@appstore/mylar/var_

Thanks you so much
