### ISSUE TITLE
Readlist's "Mark as Read" button is not working

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1421]
I clicked on the "Mark as Read" button on my Readlist but nothing happens: marked comic doesn't dissapear from the list and there is no error or warning on the log.

I'm on _development_ branch.

Thanks.

**Comment by evilhero** [comment]
This is working for myself on the dev branch - clicking on the 'X' icon beside a given issue on the Read List Management screen marks it as read and removes it from the Reading list (it looks like using the dropdown to mark specific issues as'Read' isn't working, but using the 'delete' option does what the 'Read' option should be doing).

Can you confirm (after a restart) that things aren't working using either of the above workflows ?

The only other thing it could possibly be is if you had marked some issues to go on the reading list from long ago, and the methodology to locate the given issues is no longer viable (meaning the db structure has changed), it wouldn't be able to remove them properly.

**Comment by WedgeSparda** [comment]
@evilhero 

Clicking the 'X' icon removes the issue from the Reading list, indeed. But I was referring to the icon with the green tick. I thought this one should mark the issue as read and remove it from the list, not the 'X' icon.

Trying to select some issues and select the option "Read" from the dropdown doesn't work, as you just said. All I get is a display error with the message "You didn't select any issues".

By the way, is there any option to delete all the issues marked as "Read"?

**Comment by evilhero** [comment]
Oh yes, the green checkmark icon changes the status to Read, the X icon removes it from the readlist (sometimes people don't want to remove stuff until they finish it completely, so have to make everyone happy kinda thing). 

There should be an option already on the main reading list page that will remove all read items from the readlist (it won't delete the physical files, only deletes from the readinglist table in the db).

**Comment by WedgeSparda** [comment]
@evilhero Great. Thank you for your time and all your hard work 😃
