### ISSUE TITLE
Something off with the date checker

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1423]
This week I've had some problems grabbing new issues, when I dug into it, it seems there is a problem around the date checker, or I'm reading this wrong?
Attempt to find Green Lanterns issue 9:

```
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : checking search result: Green Lanterns 009 (2016) (2 covers) (digita
l) (Minutemen-Thoth).cbz (- Nem -)
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : sub:Green Lanterns 009 (2016) (2 covers) (digital) (Minutemen-Thoth)
.cbz (- Nem -)
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : size given as: 38.1 MB
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : Wed, 19 Oct 2016 07:15:31 +0100 is before store date of 2016-10-19. 
Ignoring search result as this is not the right issue.
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : Sending request to [TPSE] RSS for Green Lanterns : 09
19-Oct-2016 11:43:34 - DEBUG   :: Thread-14 : ComicID: 91285
```

Looks like it finds it, then fails the check around the date...

Let me know if you need any more logs/info.

**Comment by evilhero** [comment]
That's weird - it pulled for me just fine, albeit from a different provider. I wonder if it's doing something locally with the timestamps that's causing some problems, but i can see where it would be causing a discrepancy in the code. 

I'll try and push out a quick fix for it.

**Comment by weidercs** [comment]
Pacific Time Zone

**Comment by evilhero** [comment]
Ugh ok, so Pacific is 8 hours less than GMT, which is what it Mylar converts it into. Wed, 19 Oct 2016 07:15:31 subtract 8hrs puts it a day earlier, which is Tue. 18 Oct 2016. Mylar will only look for new issues that are released on or after the store date it has on file (which is 2016-10-19). 
For some reason, it;s taking your local time zone into consideration when it's doing the conversions, which I can understand the reasoning, but I'm trying to figure out how to fix this so in doing so it doesn't break things for everyone else.

**Comment by weidercs** [comment]
Yeah it grabbed it successfully from the usenet indexer today, probably a low priority thing as it's only ever happened this one time.  Maybe a little fuzzy date logic to say it's 'good enough' within a day of release?
Thanks for looking...

**Comment by weidercs** [comment]
Not to tell you how to design your application, but you could fuzzy the
date a little and give it a day margin of error since issues are released
less frequently than daily, unless you know of one that is?

**Comment by evilhero** [comment]
Yeah that's what I'm trying to do - but the problem is that it has to convert the time that's being returned from the indexer into a calculatable value, which is where it's incorrectly using the system time instead of what mylar is expecting.
