### ISSUE TITLE
Stuck loading comic info after manual search

### ISSUE THREAD

**Issue by jarodwsams** [evilhero/mylar#1424]
I've just installed Mylar as a Plugin on a FreeNAS 9.10 server. The Mylar version is "master" with source build ID 2b0b28bcec8410909cfd84a2df3616f096890af6.
I searched for a comic, clicked "Add this Comic" on the one I wanted, and now the comicDetails screen is stuck loading. I've got an error in my logs (see below), and nothing will load. I don't know what I need to check or verify or share so you can help me resolve the issue, but I'll get whatever's needed. Help, please.

Log file: [mylar.log.txt](https://github.com/evilhero/mylar/files/543497/mylar.log.txt)

# Screenshots (comicDetails screen and log in UI)
![comicdetails screen](https://cloud.githubusercontent.com/assets/22972834/19586642/a42d90fc-971c-11e6-93e9-2d7918b1ea65.PNG)
![error in log](https://cloud.githubusercontent.com/assets/22972834/19586641/a2031630-971c-11e6-99d5-3aaa22421da4.PNG)

**Comment by evilhero** [comment]
The user running mylar has to have complete permissions to your Comic Location directory and everything beneath (in your case '/mnt/media/Comics'). 

The error is due to not being able to change the permissions on that newly created series directory, which is required in order to maintain monitoring on it properly (rename, move, copy, delete, etc are all done on a series directory)

**Comment by jarodwsams** [comment]
The same user that is running the "mylar" process is the user that owns /mnt/media/comics, and the directory has 777 permissions.

**Comment by jarodwsams** [comment]
> The same user that is running the "mylar" process is the user that owns /mnt/media/comics, and the directory has 777 permissions.
It might be notable that I cannot chmod the directory in question, I believe because it is part of an NFSv4 Samba share. As such, I've used setfacl to grant "full access" to "everyone" on that directory. Still getting the same error, and still chmod does not function on the directory. Could that be the source of the issue?

**Comment by evilhero** [comment]
Yep, it's the freenas plugin. This has come up several times before and its something to do with the way freenas (or the plugin, I'm not sure) enforces the permissions. The only solution that has come up with this problem that has worked everytime is to install mylar using git and not use the plugin. 

This has also come up enough times that I think I might just add an option into the chmod section of mylar that allows one to turn off the chmod that Mylar attempts to perform, and hopefully in doing so it would solve this type of problem.

**Comment by jarodwsams** [comment]
> This has also come up enough times that I think I might just add an option into the chmod section of mylar that allows one to turn off the chmod that Mylar attempts to perform, and hopefully in doing so it would solve this type of problem.

Could one simply clear out the CHMOD option fields to disable the chmod that mylar attempts?

> The only solution that has come up with this problem that has worked everytime is to install mylar using git and not use the plugin.

Would you happen to have installation instructions handy for the current stable release? I tried doing this a few nights ago but hit a wall (don't remember the wall).

**Comment by evilhero** [comment]
I think clearing out the chmod forces it to default to 0755bif I remember correctly, and there's no way atm to turn it off completely. 

I don't have any instructions on how to do it on freenas, I would assume if you can install the git plugin (assuming there is one of course), then from a command line just enter 'git clone https://github.com/evilhero/mylar' and that would put a directory called mylar into the current directory you're in. Then just run it as 'python Mylar.py -v' to run it in the console window, to make sure it works.

**Comment by jarodwsams** [comment]
Thanks! I'll give that a shot. I'll spin up a clean jail and see how far I can get. Looks like newest python I'm going to get from pkg is 2.7.11. Is that sufficient?

**Comment by evilhero** [comment]
Yes, as long as it's not 3.x and higher than 2.7.9 you shouldn't have any problems related to ssl if you use secure indexers.

**Comment by jarodwsams** [comment]
Splendid. I'll try to doc my steps. If it all works I'll share with the class.

**Comment by jarodwsams** [comment]
I've got it up and running, somewhat. I still cannot set the Comic Location to anywhere that is/was ever an NFSv4 Samba share with ACLs. I've got the Comic Location set to a local directory within the jail for now.
I've tried to turn this into an rc.d daemon using the ubuntu init.d script included in the git clone, but I'm running into trouble. I'm not sure what's causing it, but the daemon is not starting at boot.

**Comment by evilhero** [comment]
What do you have for your init.d?

**Comment by jarodwsams** [comment]
Well, it's a FreeBSD-based system so there is no init.d which is why this is more difficult for me. I actually just got the idea of pulling the rc.d script from the PBI version, but it'll need some modifications. I'll post back.

**Comment by jarodwsams** [comment]
Here's my "mylar" sh script located in /usr/local/etc/rc.d/

```
#!/bin/sh

. /etc/rc.subr
name="mylar"
rcvar="${name}_enable"
load_rc_config ${name}

: ${mylar_enable:="NO"}
: ${mylar_user:="media"}
: ${mylar_group:="media"}

command="/usr/local/bin/python2.7"
command_args="/root/mylar/Mylar.py -q --nolaunch"
run_rc_command "$1"
```

This is accompanied by the following in my /etc/rc.conf
`mylar_enable="YES"`

The rc.d/ script is based on the same script used by the PBI/plugin version of Mylar, but for some reason it's not working.

I started down this path because I thought maybe a manual installation of Mylar from Git instead of as a plugin would resolve the permissions issues I was experiencing. The manual method does not resolve the issues, sadly. I think I'm going to drop this and go back to the plugin version to see if I can find a resolution for the permissions issues. Perhaps changing the mylar_user and mylar_group parameters in the plugin's rc.d/ script would resolve the issue?

**Comment by jarodwsams** [comment]
# UPDATE

I got the PBI/Plugin version of Mylar to work without any permissions issues. My solution is probably not ideal because it has Mylar running as root, but it gets the job done. I got the idea while trying to make the manual installation launch at boot. Here are the steps. Feel free to share.

1. Install the Mylar plugin as usual
2. jexec into the new jail created for the plugin
3. Install nano (because I can't for the life of me use vi). You'll probably have to allow an update to pkg, as well.
  - `pkg install nano`
4. Edit the rc.d/ script
  - `nano /usr/local/etc/rc.d/mylar`
5. Find the lines with `mylar_user` and `mylar_group`
6. Change the value of the `mylar_user` parameter to `root`, and `mylar_group` to `wheel`. Ctrl+x to save and exit
7. Restart the jail created for Mylar (usually mylar_1)

After following these steps, you can now have Mylar utilize a directory that is also configured as a Windows Samba share in FreeNAS.

**Comment by jarodwsams** [comment]
I'm going to consider this issue closed since I was able to find an acceptable workaround.

**Comment by evilhero** [comment]
Just an FYI, enforcing permissions (ie. chmod/chown) will be a toggle option in the next commit, so that if mylar is having problems changing perms during an add series, or post-processing you can turn it off the enforcing and use it as is ;)

**Comment by jarodwsams** [comment]
That will definitely come in handy for FreeNAS users :)

**Comment by jarodwsams** [comment]
That's what I had thought, so I ran 'chmod -R 777' on the directory, but
that didn't change anything. Shouldn't that resolve permissions issues?

**Comment by evilhero** [comment]
Well chmod would change the permissions for normal access - but you're accessing it via samba share which forces access rights dependent on the smb.conf file. It might even be enforcing an acl if you're using that, which I think freenas uses normally and causes said problems, but that's just a wild guess. From what I can recall over the other similar issues, we kinda thought it was due to how the user groups are managed/used within the freenas os, and how it doesn't map to the correct user when it's performing an operation. Basically no one really knows yet, as to the exact reason why :(

**Comment by jarodwsams** [comment]
bah! That comment was supposed to have posted days ago!

The issue absolutely is the ACL that Samba forces on the directory *because* it's a Windows-type share. I suspect that if there was no share I would not have had that issue.

You can get around the users/groups issue by way of a workaround. FreeNAS creates a "media" user and group with the same UID and GID in each jail, so if you create the same user/group at the top OS level and give it ownership of the directories in question that resolves *most* permissions issues. Then you run into issues with ACLs (above) if you are also sharing parts of the media-owned directories.
