### ISSUE TITLE
[Feature Request] Support for Telegram notifications

### ISSUE THREAD

**Issue by Bart274** [evilhero/mylar#1426]
Hi,

Could you please try to add Telegram notifications?

Thanks in advance!

**Comment by evilhero** [comment]
I'll have to look into the api for it - first I heard of the app so I'll need to see how easy it is to integrate.

**Comment by Bart274** [comment]
@evilhero any progress on this? I don't know how easy or hard it would be to integrate it, I know headphones and sickrage support it
