### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TRANSMISSION_DIRECTORY'

### ISSUE THREAD

**Issue by ghost** [evilhero/mylar#1428]
The following exception is throw when attempting to access `/mylar/config`. I'm currently running `Version: c8548ab13a4be86a0da2fead8109064fe3b4f13b (development)`. Presumably this issue started overnight when I updated but I cant say for certain as I don't go in the settings very often.

The error leads me to believe that mylar is attempting to set a default value for mylar.TRANSMISSION_DIRECTORY when one is not defined in config.ini. I shutdown mylar and added transmission_directory = None to config.ini, but on startup it removes that line from the configuration. 

If you need any additional details I will be happy to provide them. 

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/app/mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 3875, in config
    "transmission_directory": mylar.TRANSMISSION_DIRECTORY,
AttributeError: 'module' object has no attribute 'TRANSMISSION_DIRECTORY'
```

**Comment by evilhero** [comment]
It sounds like your update got corrupted somehow, or you received something incorrect when trying to retrieve from git. 

Can you shutdown mylar and do a git pull from the cli? I'm wondering if there's an error message being suppressed when performing the update.
