### ISSUE TITLE
Provider Search Failover

### ISSUE THREAD

**Issue by vader083** [evilhero/mylar#1429]
Noticed my nzb provider is down causing the error below, but mylar doesn't move to the next provider to search.  The entire search dies.

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/usr/local/lib/python2.7.9/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1371, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/Mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/Mylar/mylar/search.py", line 639, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-10-26 09:30:35 WARNING Error fetching data from newznab: ('Connection aborted.', error(110, 'Connection timed out'))

**Comment by evilhero** [comment]
Yeah I came across this the other day when doing some testing for other items. I'll add in a catch for the failed connections so at the very least it would continue on to the next provider.
