### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1431]
I'm not sure if this is a problem with Mylar, but all of a sudden last week, I started getting empty folders in the default download location for SabNZB.  It's moving the comics to the correct location as specified in Mylar, but leaving empty folder shells in the default download location.

**Comment by evilhero** [comment]
Yep this was brought up a few days ago and I haven't had chance to push up the changes. It's a problem with the way mylar detects the original folder path, which I'm pretty sure I fixed on my local repo now. 

Should be up in development later today I hope.
