### ISSUE TITLE
DC's Rebirth Annuals not being added to series

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#1432]
Looks like something has changed in comicvine and broke Mylar in adding annuals into the series.

:(

http://comicvine.gamespot.com/dc-rebirth/4015-56950/

Per the above link, 6 annuals are listed.
Thanks
Pipieye

**Comment by evilhero** [comment]
Is it every rebirth series that you're having a problem getting it to pick up the annuals? 

It might have to do with CV not properly labelling the annual with a volume demotion, or a link back to the tie-in series comicid (mylar checks for that if theres no reference it can't link it). 

Have you tried just adding the annuals to the respective series via the green arrow icon in the bottom right of the series detail page? It had to be in the format of 4050-XXXX

**Comment by pipieye** [comment]
Not sure what I did, but start working now. :)

Thanks
