### ISSUE TITLE
_downloadNZB() got an unexpected keyword argument '.Quinch-Empire.nzb'

### ISSUE THREAD

**Issue by PCurd** [evilhero/mylar#1433]
Hi,

When downloading World of Tanks 01 Mylar is finding an NZB on NZBGeek but when SAB tries to pull the NZB from Mylar I get the above error (full trace below).

The URL SAB is trying to pull from is:

http://192.168.0.XXX:8090/api?apikey=MYKEY&cmd=downloadNZB&nzbname=World.of.Tanks.001.2016.Digital.DR.andamp;amp;.Quinch-Empire.nzb

The filename that NZBGeek pushes down is World.of.Tanks.001.(2016).(Digital).(DR.&.Quinch-Empire).nzb

Traceback (most recent call last):
  File "D:\Mylar\mylar\cherrypy_cprequest.py", line 645, in respond
  File "D:\Mylar\mylar\cherrypy\lib\encoding.py", line 188, in **call**
  File "D:\Mylar\mylar\cherrypy_cpdispatch.py", line 29, in **call**
  File "D:\Mylar\mylar\mylar\webserve.py", line 4657, in api
    data = a.fetchData()
  File "D:\Mylar\mylar\mylar\api.py", line 105, in fetchData
    result = methodToCall(**self.kwargs)
TypeError: _downloadNZB() got an unexpected keyword argument '.Quinch-Empire.nzb'

Full Log output:

27-Oct-2016 08:46:52 - INFO    :: Thread-12 : Initiating manual search for World of Tanks issue: 1
27-Oct-2016 08:46:52 - INFO    :: Thread-12 : Issue Title given as : 1: d plus thirty
27-Oct-2016 08:46:52 - INFO    :: Thread-12 : search provider order is ['newznab:NzbGeek', 'newznab:DogNZB', 'newznab:DogNZB']
27-Oct-2016 08:46:52 - INFO    :: Thread-12 : allow_packs set to :False
27-Oct-2016 08:46:52 - INFO    :: Thread-12 : Shhh be very quiet...I'm looking for World of Tanks issue: 1 (2016) using NzbGeek (newznab)
27-Oct-2016 08:46:52 - INFO    :: Thread-12 : pausing for 60 seconds before continuing to avoid hammering
27-Oct-2016 08:47:15 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
27-Oct-2016 08:47:54 - INFO    :: Thread-12 : newznab
27-Oct-2016 08:47:54 - INFO    :: Thread-12 : rss:no
27-Oct-2016 08:47:54 - INFO    :: Thread-12 : allow_packs:False
27-Oct-2016 08:47:54 - INFO    :: Thread-12 : Found World of Tanks (2016) issue: 1 using NzbGeek (newznab)
27-Oct-2016 08:47:54 - INFO    :: Thread-12 : Download URL: https://api.nzbgeek.info/api?apikey=KEY&t=get&id=7cd7b702277b6148c62ee78b7d2c7b3b [VerifySSL:True]
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : filen: .World.of.Tanks.001..2016...Digital...DR.and.Quinch-Empire. -- nzbname: World.of.Tanks.001.2016.Digital.DR.andamp;amp;.Quinch-Empire are not identical. Storing extra value as : .World.of.Tanks.001..2016...Digital...DR.and.Quinch-Empire.
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : Successfully sent nzb file to SABnzbd
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : setting the nzbid for this download grabbed by NzbGeek (newznab) in the nzblog to : 7cd7b702277b6148c62ee78b7d2c7b3b
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : setting the alternate nzbname for this download grabbed by NzbGeek (newznab) in the nzblog to : .World.of.Tanks.001..2016...Digital...DR.and.Quinch-Empire.
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : passing to updater.
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : [UPDATER] Updating status to snatched
27-Oct-2016 08:47:56 - INFO    :: Thread-12 : [UPDATER] Updated the status (Snatched) complete for World of Tanks Issue: 1

**Comment by evilhero** [comment]
Weird, those &amp's should have been stripped out when mylar generated the nzb name. So it's now taking the 'Quinch-Empire' as a value instead of as part of the previous string. 

Will look into this...

**Comment by davalanche** [comment]
I experienced the same issue (double escaped ampersands) a handful of times with NZBGeek and provided a fix in PR #1397 (Commit 29385d8).  Thanks.

**Comment by evilhero** [comment]
Man I'm a dork. I didn't even notice that PR - sorry @davalanche. 

I plan on pushing some stuff today if I can get the time to get on a machine.  Will push that PR at the same time as I push the other things.

**Comment by PCurd** [comment]
I can confirm it's working now after updating Mylar - this issue downloaded with no problems. Thanks both!
