### ISSUE TITLE
[ Feature Request ] Join notification support

### ISSUE THREAD

**Issue by ChronoStriker1** [evilhero/mylar#1434]
API info can be found here
[https://joaoapps.com/join/api/](url)

**Comment by evilhero** [comment]
I'll have to figure it out ;)  I didn't even know this existed, and I'm behind the 8-ball on some other things going into Mylar so those are a priority to get out and working atm. But I'd imagine, with a good api this wouldn't be too hard to implement at all.

**Comment by linxchaos** [comment]
Bumping because I have an interest in this as well, I switched over completely to Join about two years ago and have my other programs working with Join.

**Comment by tehniemer** [comment]
I ditched pushbullet for Join and would like to see it implemented here, it works great with Radarr, Sonarr, and Headphones.
