### ISSUE TITLE
[POST-PROCESSING] Comics do not match anything

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1436]
Trying to run a manual post process to add comics that have been tagged and are .cbz files. Receive the following log entries.

2016-10-31 13:21:14	DEBUG	[POST-PROCESSING] Now Checking if the issue also resides in one of the storyarc's that I am watching.
2016-10-31 13:21:12	DEBUG	[POST-PROCESSING] There are 0 files found that match on your watchlist, 3555 do not match anything.

What setting am I missing to import new comics? How do I add comics to the watchlist? Comics are placed in a folder separate from the main comic storage folder

**Comment by evilhero** [comment]
What is it that you're trying to do exactly?

If you have 3555 issues that you're trying to post-process, it's saying that none of those series exist currently on your watchlist (which is the series that are listed on the main page/homepage).

If you do an Scan Library (off the Manage tab) and perform that process, it will add the series to your watchlist if it can parse the filenames properly. Are your files named in a non-typical 'Series Issue Year' format ?

**Comment by F688** [comment]
Looking at comic issues and you are correct most are new series that I want to add and some had non-typical name format (which I corrected).

The problem I'm encountering is that running a scan library to add these files will take forever as the scan library appears to re-scan all the existing files and some error will occur which will then require re-running the scan. My collection is around 120,000 even though Mylar only is registering 78,000 currently. I have been recheck files (50 series at a time because of freezes/error) for the last month and have seen the issue count grow from 20,000 to 78,000. The problem is the time it takes to read all the issues.

Mostly I'm looking for a quick way to add new files/series. Is there a way to have a scan folder for new comics different from the storage folder? Or to have a scan option to ignore existing files/issues?

**Comment by evilhero** [comment]
Maybe I'm confused abit (it's like early here), are you saying that your scan folder (the import scan or post-processing folder) is the same as your Comic Location folder?

**Comment by F688** [comment]
OK the confusion is all mine. When is said "Scan Comic Library Where do you keep your comics? ..." I misunderstood that that it meant where do I keep my comics permanently (Comic Location folder). I'll change that to the temporary holding folder.

**Comment by evilhero** [comment]
Ah yeah that's some really bad wording based on the interpretation. I'll make it clearer in the next dev commit - thanks for indicating the wording problem :)
