### ISSUE TITLE
[Feature Request] hide ended/paused series from main page

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1439]
Is there a way that you could add the ability to only display the current issues on the front page with either a check box in the settings or just have a tab just at the top of the comics to switch between current and ended/paused.

Not a pressing feature, just one to make the experience even better.

**Comment by evilhero** [comment]
It's doable sure - I'm just not sure how you would go about managing the series that are in an Ended /  Paused state if you're hiding them from the view. I understand the want to only view new series, and let the program take care of the older stuff. 

Maybe a toggle switch on the main page to flip back and forth - putting it in the settings or in the config.ini only seems to me to be too much clicking to get to something that could be done on the current screen.
