### ISSUE TITLE
auth mode search in 32p no longer working

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1452]
as discussed here http://forum.mylarcomics.com/viewtopic.php?f=8&t=1690 the auth mode for searching on 32p no longer works due to them changing their API

**Comment by evilhero** [comment]
Yep, I'm waiting to find out from the 32p folks in regards to what the change was due to, and if it's possible to re-enable the option that Mylar uses so the auth mode would work again without having to go an uglier, alternate route. It's been 2 days since I inquired, but no response as of yet...

**Comment by evilhero** [comment]
See #1455 -  commit Comin tonight to fix this hopefully

**Comment by HypKin** [comment]
thx
