### ISSUE TITLE
Cannot access Pull-List "This Week"

### ISSUE THREAD

**Issue by kmccormi** [evilhero/mylar#1456]
I've searched the forums and this board but can't find any similar threads. I can access all pages of the web interface except "This Week". It simply attempts to connect without ever timing out. 

The other day I noticed I was a few commits behind and tried the usual 'update now' button. It failed to relaunch and I tried launching it manually via 'mylar.pyw'. It failed consistently and then I manually renamed the 'mylar.py' file to a new 'mylar.pyw' file and it launched. (I've never had to do that before). 

That's when I stopped getting access to the pull list. After fiddling around for ages I gave up and deleted the mylar directory after backing up the .ini, cache and .db files. I then did a git clone to get a new install, then ran git checkout development to make sure I was back on the dev branch, then I put the backups in place.  The access issue remains, exactly as before.

Any ideas?

**Comment by kmccormi** [comment]
Forgot to include a snippet from the logs - only thing I could find that seemed relevant:

11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : {'prev_weeknumber': 44, 'weeknumber': '45', 'year': '2016', 'endweek': 'November 12, 2016', 'startweek': 'November 06, 2016', 'current_weeknumber': '45', 'next_weeknumber': 46, 'midweek': '2016-11-09'}
11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : trying to repopulate to different week
11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : Weekly pull list present - checking if it's up-to-date..
11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : pulldate is : 00000000
11-Nov-2016 10:41:31 - WARNING :: CP Server Thread-4 : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
11-Nov-2016 10:41:31 - INFO    :: CP Server Thread-4 : [PULL-LIST] Unable to retrieve weekly pull-list. Dropping down to legacy method of PW-file
11-Nov-2016 10:41:31 - INFO    :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
11-Nov-2016 10:41:31 - INFO    :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..
11-Nov-2016 10:41:31 - INFO    :: WEEKLYCHECK : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
11-Nov-2016 10:41:31 - INFO    :: WEEKLYCHECK : pulldate is : 00000000
11-Nov-2016 10:41:32 - WARNING :: WEEKLYCHECK : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
11-Nov-2016 10:41:32 - INFO    :: WEEKLYCHECK : [PULL-LIST] Unable to retrieve weekly pull-list. Dropping down to legacy method of PW-file



Running on win 10 desktop pc

**Comment by evilhero** [comment]
Well the .pyw change was probably due to the Mylar.py file actually changing in that upgrade, so your existing Mylar.pyw file wasn't copied from the newest source. 

It looks like you're getting handshake errors when trying to get to the pull site (alt_pull =2 method).  You need to make sure you're using python 2.7.9+ and you probably need to ha e the cryptography module installed for requests top ('pip install requests[cryptography] ' I think)

**Comment by kmccormi** [comment]
Thanks for the prompt reply. I was finally able to get cryptography installed and Mylar is running normally. But I also switched off the GoAgent proxy I normally have on 24/7 (getting over the China firewall ain't easy) and that allowed the install to proceed, so maybe there's a connection. I will let Mylar run its normal course for a few hours and then check again with the proxy back on.

Many thanks,
