### ISSUE TITLE
sorry got that thing where I'm stuck with updates that never update

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1457]
Hi

I recall last time I had to "git clone" but when I tried, I got an error that everything already exists in the directory. What should I do?

Gregory

**Comment by AtariBaby** [comment]
if I click "update now", it says "updating" then appears to restart, then the message pops up again that there are new updates.

**Comment by evilhero** [comment]
Try git clone from the command line and then paste back the exact error message it gives. Depending on the error you might have to backup your files, delete the directory and do a fresh git clone.

**Comment by AtariBaby** [comment]
```C:\Mylar>git clone https://github.com/evilhero/mylar.git
fatal: destination path 'mylar' already exists and is not an empty directory.```

**Comment by AtariBaby** [comment]
barring immediate response i will delete as you suggest

**Comment by evilhero** [comment]
sorry, I meant git pull...try git pull first to see what the error is. 

Git clone will reclone you a new copy from the git servers, but it will hammer your existing install (it would have to be done from the parent directory of your current mylar installation)

**Comment by AtariBaby** [comment]
did that, appears to be successful, but i still have the updates message appearing after the "60 seconds".

``
C:\Mylar>git pull https://github.com/evilhero/mylar.git
remote: Counting objects: 160, done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 160 (delta 102), reused 8R7 (delta 36), pack-reused 0
Receiving objects:  93% (149/160)
Receiving objects: 100% (160/160), 65.64 KiB | 0 bytes/s, done.
Resolving deltas: 100% (102/102), completed with 23 local objects.
From https://github.com/evilhero/mylar
 * branch            HEAD       -> FETCH_HEAD
Updating 7c7aef0..646309b
Fast-forward
 mylar/version.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by AtariBaby** [comment]
oh sorry i can't just do a clone because i can't delete the folder because it's running lol. i can't remember how to stop/kill it.

**Comment by evilhero** [comment]
Try shutting down mylar via the Web interface and then restarting windows. Odds are it's locked on a log file or something.. Rebooting would clear it so that you could then do a clean install if need be

**Comment by AtariBaby** [comment]
I tried shutting down, but cannot delete still. I also rebooted. I would possibly have to do safe mode.

**Comment by AtariBaby** [comment]
and then i had a mylar.vbs shortcut in my startup folder. is that still the best way to have it start automtically in windows 10 pro?

**Comment by evilhero** [comment]
For windows yes, there are some other ways but the one I know that works still is the vbs

**Comment by AtariBaby** [comment]
curious to try this nssm method, unless you recommend against.

**Comment by AtariBaby** [comment]
oh lol did all that and now it's stuck with the update message again

**Comment by evilhero** [comment]
Did you use a clean config or put your old one back? Did you do a git clone with the development option enabled? 

Try running it without the vbs.. Right from the command line and doing the update that way. 

Also make sure that git_branch in your config is set to development.

**Comment by AtariBaby** [comment]
I didn't do the development part. I am using the "mylar as a service" approach. I used the old config file. 

Can you tell me what sequence of steps to try next? Sorry.

**Comment by evilhero** [comment]
Im lost too.. Lol. 

Can you tell me what you did so far in sequence (roughly) and we can go from there. 

If mylar isn't running, you can try doing just a plain 'git pull' from within the mylar directory to see if that updates.

**Comment by AtariBaby** [comment]
Here's what I did:

backup config and .db. Ran github for mylar on the c: drive without specifying development or anything else.
pasted the backedup files back into c:/mylar
followed instructions to setup as a service using nssm.exe
accessed the webpage and clicked update, and discovered it was still occurring.

**Comment by AtariBaby** [comment]
- 1. Ah! Fixed it.
- 2. nssm stop mylar
- 3. git pull (already latest)
- 4. git checkout development
- 5. open webpage. no update waiting!

**Comment by AtariBaby** [comment]
Question: this has happened to me a lot lol. Is there some way to avoid it?

**Comment by AtariBaby** [comment]
I do notice whenever this happens and we fix it, I get a bunch of new comics. So unless comics are dropping this minute, something gets jammed up.
