### ISSUE TITLE
New issues are not added to Reading List

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1461]
Hi

Despite I enabled "Automatically send new pulls to Readlist (Added)" option, new issues are not added to the Reading List when they're downloaded.

I'm missing something?

**Comment by evilhero** [comment]
It should be working (just tried it and it worked) - it will only add new pullist items however, if the issue in hand is not on the current week's pullist, then it won't be added to the readinglist based on how the code currently is written.

**Comment by WedgeSparda** [comment]
It's weird. Yesterday I got new issues for this week releases and none of them were added to the reading list. Also, on the Weekly Pull list all the comics are marked as "skipped" despite I follow some of them. In fact, search and download of followed comics is working.

**Comment by evilhero** [comment]
Sometimes the weekly pull doesn't update right away (not sure why exactly haven't looked into it much), so doing a Refresh of the pullist lines things up. Course that doesn't help with the pullist not grabbing said issues since it only occurs on a post-processing run.
