### ISSUE TITLE
More of a request than anything

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1463]
Just wanted to float the idea of making Mylar work with DC++ again. Happy to help in any way, from testing to design to funding. But It's already amazing as is, so no big.

**Comment by evilhero** [comment]
I honestly don't see this happening to be honest, that sounds like something for someone else to do as I really don't have any interest in doing a dc++ client (since I'm not fond of it I suppose)

**Comment by AtariBaby** [comment]
I hear you! It's out of my depth, unless someone here on the forum has interest.
