### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by dustinarden** [evilhero/mylar#1466]
it looks like this was reported before and it was due to the comics not having a date in the title?  Seems as though that was going to be fixed with a commit back in August, but it appears i'm having it now.  Do i just need to manually add a date to the file name to fix this?

Thanks.

```
19-Nov-2016 10:07:28 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 533, in Process
    if int(watch_issueyear) == int(watchmatch['issue_year']):
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by evilhero** [comment]
You shouldn't have to add a date to the filename, and yes it should have been fixed previously (and as far as I was aware it was). 

What is the name of the file that you're having the problem with? Also, in the series detail page for the given series, what is the pub date shown for that specific issue?

**Comment by dustinarden** [comment]
files are mostly a variation if this:
Deadpool - #004.cbz

Pub date is : Publication Date: January 1997 - September 2002

Thanks for your response man!  anything else i can provide i'd be more than happy to.

**Comment by evilhero** [comment]
Yeah that should be fine. The problem that you had mentioned was with 2017 issues, since we're not in 2017 yet. But yours is something different it seems since the series is older. 

Can you just confirm the branch / commit you're running of mylar?

**Comment by dustinarden** [comment]
`Mylar Version: master
-- git build 646309b8f64c560a8dccc5f1e499fdb2ff670b7e.
Python Version : 2.7.11`

**Comment by evilhero** [comment]
yeah that was a stupid mistake that got reverted back at some point in the code - not sure exactly why it wasn't caught earlier (should have been an 'all' instead of 'any'). Will be in the next dev commit, and hopefully master shortly thereafter (I need to push some stuff into master quicker than normal due to some changes that broke things outside of Mylar)

**Comment by dustinarden** [comment]
sounds good !

**Comment by dustinarden** [comment]
I see there was an update available - so i updated.  Now the application doesnt start.  This is on a synology NAS.  Do you happen to know what would have changed that would have caused the app to not start anymore?  When i've seen this in the past its generally due to the account it runs under getting changed, or files/directories having the associated user modified or overwritten or something like that.  Just curious.

Thanks!

**Comment by dustinarden** [comment]
never mind ... it magically started after failing the first time.

**Comment by evilhero** [comment]
The fix for your issue wasn't pushed just yet - there was a problem with the pull-list in general for everyone due to changes on the external site so it needed to get pushed out quickly. I have another going into dev (with your fix) shortly I'm hoping.

**Comment by dustinarden** [comment]
roger that.
