### ISSUE TITLE
weekly folder numbering

### ISSUE THREAD

**Issue by thorinmesser** [evilhero/mylar#1470]
This week (and this has happened before but fixed itself) the weekly folder is named by the week of the year instead of by the date. For example, the folder for this week is named "2016-47" instead of "2016-11-23". Is there a way to go back to the date style? i only see weekfolder and weekfolder_loc in the config file. I am using alt_pull=2 on the develop branch.

Tangentially related, is there a way to generate weekly folders for past weeks? Somehow I didn't get weekly folders for 10-26, 11-02, or 11-09, and i would like to. Thanks!

**Comment by thorinmesser** [comment]
So it looks like weeklypull.py sets the folder name based on the SHIPDATE from the weekly table of the db, and this is the behavior I want and expect. (starting around line 1251) This is assuming I'm reading it correctly, which is a big assumption.

Then webserve.py sets the directory to the week number (on line 3189) instead, even though the hidden field it's using has the correct value already set as "midweek".

**Comment by evilhero** [comment]
Yeah it was probably done as an afterthought to be honest, I hadn't did the midweek stuff at that point so the just having the week number was the only working option. 

I should be able to allow for some customization with the folder naming since the data is all there in the weekinfo variable already.

**Comment by evilhero** [comment]
Just an update, next dev commit will have this:
```
**config.ini**
weekfolder_format = 0 / 1
```
where:
0 = YYYY-WN  (where WN is the weeknumber)
1 = YYYY-MM-DD  (where the actual date is the midweek value for the given pullist week)

As an aside, prior weeks will have their respective folders generated when you click on the download link - and all relevant issues that are in that particular week that are in a Downloaded status will be copied over to said weekly folder.

Still to do: allow option to change from copy to hardlink/symlink/copy.

**Comment by thorinmesser** [comment]
That sounds great, thank you so much!
