### ISSUE TITLE
pullist crashing with alt_pull 2

### ISSUE THREAD

**Issue by adamiltone** [evilhero/mylar#1473]
Hi, 

I modified my config.ini to use alt_pull 2 and when i tried to load next week pull list I got an error and now I can seem to be able to access the pull_list page anymore and I can't reconstruct my pulllist either since the page is no accessible. I tried to change the alt_pull to 1 but nothing changed.

Is there a way to force a pulllist reconstruction ?

Here is my stack list

```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

```
26 %if wantedcount == 0:
27 <h1><center>Weekly Pull list for week ${weekinfo['weeknumber']} :</br>${weekinfo['startweek']} - ${weekinfo['endweek']}</center></h1>
28 %else:
29 <h1><center>Weekly Pull list for week ${weekinfo['weeknumber']} :</br>${weekinfo['startweek']} - ${weekinfo['endweek']} (${wantedcount})</center></h1>
30 %endif
31 </td><td style="vertical-align: middle; text-align: left">
32 <a href="pullist?week=${weekinfo['next_weeknumber']}&year=${weekinfo['year']}" title="Next Week (${weekinfo['next_weeknumber']})"><img src="interfaces/default/images/next.gif" width="16" height="18" Alt="Next"/></a></td>
33 <tr>
34 </table>
```

```
/opt/mylar/data/interfaces/default/weeklypull.html, line 29:
<h1><center>Weekly Pull list for week ${weekinfo['weeknumber']} :</br>${weekinfo['startweek']} - ${weekinfo['endweek']} (${wantedcount})</center></h1>
/opt/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/opt/mylar/mako/runtime.py, line 718:
/opt/mylar/mako/runtime.py, line 692:
/opt/mylar/mako/runtime.py, line 660:
/opt/mylar/mako/template.py, line 296:
/opt/mylar/mylar/webserve.py, line 52:
return template.render(**kwargs)
```

**Comment by evilhero** [comment]
I've seen this happen a few times but could never really test it out in full - I believe it's due to a unicode character in the alt_pull 0 method that can't match up to the alt_pull 2 method (or vice versa) and it gets confused.

I think if you just start up Mylar and then call the 'pullrecreate' function (http://yourmylaraddress/pullrecreate) it should wipe out the existing pull-list data and bring in the new data (assuming you're leaving the alt_pull to 2) without any issues.

**Comment by adamiltone** [comment]
unfortunately the command failed with the same output :(

I think i should try to change to alt_pull 0 and try a reconstruction

**Comment by adamiltone** [comment]
something that I maybe didn't say is that alt_pull 2 was working until the last commits about the pulllist on `development` branch

here is what I did before it collapsed
1. went to my pullist
2. clicked on the arrow to see next week pulllist
3. stacktrace

I don't know if some kind of preference was set when I clicked on the arrow but it might come from this

**Comment by evilhero** [comment]
what version of Mylar are you currently running?

I'm able to switch to the next week, however it's not displaying any results for some reason. I'm not quite sure what's going on as this was working fine last week (or so I thought).

**Comment by adamiltone** [comment]
I am running the development branch with latest commit

**Comment by tomtom602** [comment]
I've got the exact same problem with this week pulllist.
I managed to locate the problem on the ${weekinfo['endweek']} variable.
I don't know yet why it make the page crash, but removing it from the line 29, solve the problem.

**Comment by evilhero** [comment]
This is weird - it's working fine on my end without any errors. 

Did you guys flip from alt_pull 0 to 2 at any point, and/or back again? 

It's just taking the end date of the week.. Ohh, hang on I wonder if you guys are getting error messages related to tzlocal not being installed.

**Comment by evilhero** [comment]
Actually the unicode character might be due to the localization you're in - I'm thinking that it's related to it trying to spell out the word December in a non-English language. Can you both indicate what language you have Mylar running on (or what your system is set to if it's not English)

**Comment by tomtom602** [comment]
I'm in France, I'm running mylar on a raspberry pi with debian jessy. My default language is French, in which december is spled "décembre". That's it.  More other november is effectively spled in French for the start date.

**Comment by evilhero** [comment]
Ok, I think I know how to fix this but I could use your help to test this before I push it out. If you're familiar with editing python modules, it would really help me out if you could replace a few lines with some specific text and give it a try to see if it fixes things for you.

**Comment by tomtom602** [comment]
Yes of course no problem. I know how to code python

**Comment by evilhero** [comment]
Awesome! Ok, in the pulllist function (~ line 1515 of webserve.py), you'll need to change some of the str formats for the time handling. So if you find this portion of code:
```        weekinfo = {'weeknumber':         weeknumber,
                    'startweek':          u"" + startweek.strftime(date_fmt).decode('utf-8'),
                    'midweek':            midweek.strftime('%Y-%m-%d'),
                    'endweek':            u"" + endweek.strftime(date_fmt).decode('utf-8'),
                    'year':               year,
                    'prev_weeknumber':    prev_week,
                    'next_weeknumber':    next_week,
                    'current_weeknumber': current_weeknumber}
```
and replace it with:
```
        date_fmt = "%B %d, %Y"

        weekinfo = {'weeknumber':         weeknumber,
                    'startweek':          u"" + startweek.strftime(date_fmt).decode('utf-8'),
                    'midweek':            midweek.strftime('%Y-%m-%d'),
                    'endweek':            u"" + endweek.strftime(date_fmt).decode('utf-8'),
                    'year':               year,
                    'prev_weeknumber':    prev_week,
                    'next_weeknumber':    next_week,
                    'current_weeknumber': current_weeknumber}
```
save it and then try starting mylar up - it should be able to properly decode the date format.

**Comment by tomtom602** [comment]
Yes that works fine ! :) 
Thanks

**Comment by adamiltone** [comment]
I am also in french, i guess you got it :)
