### ISSUE TITLE
[Feature Request] Protect server with Login

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1474]
I think it would be a good idea to protect the connection to the Mylar server with a login so only allowed users can access to the content. What do you think?

**Comment by evilhero** [comment]
You mean the server that mylar runs on? There already is an option on the General tab labelled as username / password and you can set your https certificate location even.

**Comment by WedgeSparda** [comment]
@evilhero Ouch. My bad. Thanks.
