### ISSUE TITLE
My purty pitchers broke

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1475]
Hi I installed today's update, and when it restarted the images were broken. Not a big deal, but what's the fix? 
![screenshot 2016-11-29 15 52 34](https://cloud.githubusercontent.com/assets/97095/20734074/f4c37984-b64b-11e6-93cf-3b3fdc39a19d.jpg)

**Comment by evilhero** [comment]
Umm no fix - the images are in your cache folder, so make sure that the cache folder has the images (they're labelled as the comicid#) and that you're loading them from the correct cache if you have more than one.

**Comment by AtariBaby** [comment]
Is this c:/mylar/cache? That's mostly empty now except for a handful of images and nzb files.

**Comment by evilhero** [comment]
That's the location of the files that show the pictures on the series pages - so if there isn't the same number of files as there are series in your watchlist, then yup they're gone for some reason. You can check - note the filename of one of the image files, and then in Mylar put in the that comicid for the series page (ie. if it's 79398.jpg then you would put : http://mylaraddress/comicDetails?ComicID=79398 ).

If they're gone, then you'd have to either Refresh each series to get the pics back, or go to the Manage tab/ Manage Comics/mark series and select Refresh Series, or go to Manage tab/Advanced Options/Update all Active Comics. Note that the last one would probably hammer your CV API so after a period of time, when it hits it's hourly max it would just stop responding until the hour has elapsed.

**Comment by AtariBaby** [comment]
I guess they got wiped out in the fresh install you helped me with, but I had backedup the folder. I copied and pasted and all good.

Can I just delete these nzb files in here or will that do something?

**Comment by evilhero** [comment]
Nope they're just remnants gwho have reminds me I need to get that into mylar so it can clean up those files after they're used. 

You can delete them ;)
