### ISSUE TITLE
"select all" and "deselect all" checkbox is not working

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1478]
The checkbox placed for selecting/deselecting all element of the list is not working, for instance, on the Comic Details screen.

![shot](https://cloud.githubusercontent.com/assets/48375/20883033/4691184c-bae4-11e6-8fe8-db3af6f3ef14.png)

I tried with Chrome and Safari on macOS

**Comment by evilhero** [comment]
Try using the 'Select All Filtered' button to select all the issues.  The code got changed a bit in order to accommodate the filter selecting, and it looks like in doing so the checkbox toggle to select all is now broken.

**Comment by WedgeSparda** [comment]
Yes, with the "Select All Filtered" and "Clear All" it works. 
Are you going to remove the master checkbox and use those buttons instead or keep both options?

**Comment by mcaron1234** [comment]
The "Select All Filtered" and "Clear All" works for a group of issues, but there is nothing similar when wanting to select all titles on, for example, the manage comics screen or in the import results management screen.

**Comment by evilhero** [comment]
The select all checkbox works on other screens just fine - it's only broken on the series detail pages atm.

**Comment by mcaron1234** [comment]
So it does - did you fix that in the latest dev commit?  I swear it hasn't been working over the last week or so.  Anyway, sorry to bother you about it.

**Comment by evilhero** [comment]
Haha no worries - but I didn't alter anything in the last commit that would have fixed / broken it. This looks like it got pushed into development a few weeks ago and was never mentioned until now.
