### ISSUE TITLE
Changing Comic Location Path doesn't trickle down to series

### ISSUE THREAD

**Issue by CovertDad** [evilhero/mylar#1480]
I've changed the location on my hard drive where my comics are stored, but each individual series still points to the old location.  If I refresh the files, they are picked up as archived.

Is there any way to enforce the new location on the individual series, en masse?  I really don't want to have to go through importing my books again, or changing each series one-by-one.

**Comment by evilhero** [comment]
Well you can do each one manually if you enjoy being meticulous (series detail page/edit tab/change the location path and then hit the update button), but you can also do it en masse. 

There's a thread on the forums that has more detail : 
https://forum.mylarcomics.com/viewtopic.php?f=12&t=601

You have to make sure that prior to changing the config.ini values as per the thread that you leave the comic location path (in the configuration Gui gear icon) pointing the original location. Only after its updated do you change it to the new location path. 

(I'm on my phone atm, so can't explain further in detail aside from pasting the link, but any questions just holler back)

**Comment by thewindupboy** [comment]
Hi!
Can you confirm that the following steps are correct for me wanting to move my comics to another location?
In config.ini
1. set locmove = 1
2. set newcom_dir = *the new directory...without the trailing slash*
3. Save and restart
4. Once done, set ComicLocation to the new directory
