### ISSUE TITLE
This Week Has No Highlighting

### ISSUE THREAD

**Issue by haygoodhtpc** [evilhero/mylar#1486]
The "This Week" tab usually has highlight to tell me what issues will be released that week. It no longer does for me, but if I switch to sort by "Have" on the main screen, it shows me which series are missing issues for that week.

**Comment by evilhero** [comment]
Everything is working as normal - What branch / commit are you running? 
Are you using the alt_pull = 0 method or alt_pull = 2 (check the config.ini)?

Try doing a 'Recreate Pullist' from the weekly tab to see if that fixes things up (or if there are any errors logged)

**Comment by haygoodhtpc** [comment]
Mylar Version: develop
-- git build 021459c280f450beecb8118d1f602d8d41a33b47

alt_pull = 0 according to my config.ini

**Comment by evilhero** [comment]
Might be something up with the site mylar pulls the list from when using the 0 method.  Shutdown mylar, and set the alt_pull = 2, and then save and start it up. The 2 method uses a completely different site to poll against with much more detailed information for use with mylar (plus some other neat things). 

I'll have to check into the 0 method to see if something is broken, but setting it to 2 now will get you going again...

**Comment by haygoodhtpc** [comment]
The alt_pull = 2 seems to have worked.
