### ISSUE TITLE
Support for Worldwidetorrents

### ISSUE THREAD

**Issue by rvansoest** [evilhero/mylar#1487]
Could you add support for worldwide torrents there are a lot of comics posted. https://worldwidetorrents.eu/torrents-user.php?id=36

**Comment by evilhero** [comment]
It's been included since KAT went offline. The TPSE torrent option within mylar runs against 3 public trackers : torrentproject, demonic, and worldwidetorrents.

**Comment by rvansoest** [comment]
Damn your fast. Didn't make the connection. I've enabled it. Thank you.

**Comment by cesalo** [comment]
I realized that a comic I want is in worldwidetorrents.eu but Mylar can't find it. I have torrent enabled and using transmission to download it. where can I find the details of the search Mylar is trying to do and why can't find it?

**Comment by evilhero** [comment]
Mylar can only retrieve Rss feeds from wwt - so if a release you're looking for wasn't in a previous feed that mylar had grabbed when it was running (it caches all the results), then it has to be in the current feed. 

You might want to look into something like jackett, as it can support some public indexers for non-rss searches, albeit I don't think they have worldwidetorrents as an option yet.

**Comment by cesalo** [comment]
I see .. and the setting: "Enable RSS Feed Searches (nzbs & torrents)" helps with this.

Now I'm seeing this error after enabling it:

29-Jun-2017 06:43:23 - INFO    :: RSSCHECK : RSS Feed Check was last run at : 2017-06-28 20:00:53
29-Jun-2017 06:43:23 - DEBUG   :: RSSCHECK : Updating RSS Run time to : 2017-06-29 06:43:23
29-Jun-2017 06:43:23 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Check.
29-Jun-2017 06:43:23 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Feed Check on TorrentProject.
29-Jun-2017 06:43:40 - DEBUG   :: RSSCHECK : Exception generated in thread RSSCHECK: could not convert string to float: s  | Real-Life | French | 23.78
29-Jun-2017 06:43:40 - DEBUG   :: RSSCHECK : 'Traceback (most recent call last):\n  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/rsscheckit.py", line 62, in run\n    rsscheck.torrents(pickfeed=\'TPSE\')    #TPSE = DEM RSS Check + WWT RSS Check\n  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/rsscheck.py", line 257, in torrents\n    \'size\':     helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz)),\n  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/helpers.py", line 174, in human2bytes\n    assert float(num) and letter in symbols\nValueError: could not convert string to float: s  | Real-Life | French | 23.78\n'

Not sure If I should create a new issue. Now it seems the one failing is TorrentProject but not sure if the others are being checked or if is just stopping there.

**Comment by evilhero** [comment]
Yeah I already know of this and have a fix set to go into dev at some point soon. 

It's actually from the demonoid feed - they changed the format of their feed and because of the change it's throwing off the parser being used trying to calculate the size of the torrents.

**Comment by cesalo** [comment]
Thanks for the quick answer. Last question (I think) what is the RSS feed that you use in WWT? Is the one for Comics / Nem43 Comics? or the main RSS feed? Is there a way to customize that?

**Comment by evilhero** [comment]
It uses both feeds since comics get posted to both - but I believe it takes the last 50 from each for a combined 100 total RSS entries retrieved from WWT. 

There's no way to customize it as there's no need to - comics get posted to those 2 categories only. Adding another category into it would create errors as it wouldn't be a comic feed, or it would contain non-comic items which would cause problems in itself.

**Comment by cesalo** [comment]
Just to clarify this.

Comic -> https://worldwidetorrents.eu/rss.php?cat=50
Nem43 Comics -> https://worldwidetorrents.eu/rss.php?cat=132

For example I see one entry in Nem43 .. position 28 that is "Wanted" and is not being picked up by Mylar. This entry was posted 21h ago.

Shouldn't this issue being picked by the RSS functionality of Mylar?

**Comment by evilhero** [comment]
It depends on the naming convention, as well as how many items have been posted since the 21hrs have elapsed and if said item still resides on the current RSS feed (especially if you weren't running mylar during that 21hrs). 

Post the debug log showing the search, odds are it's either not picking it up because it's not on the feed anymore or its named something different than what Mylar is expecting it to be (ie. Series named different, incorrect volume label, incorrect year, etc)

**Comment by cesalo** [comment]
Let's see:
I have Mylar running 24x7. The item is: Suicide Squad 020 (2017)
Torrent link is: https://worldwidetorrents.eu/torrents-details.php?id=77607
The current RSS Feed: https://worldwidetorrents.eu/rss.php?cat=132 has this issue with title: "Suicide Squad 020 (2017) (2 covers) (digital) (Minutemen-Midas).cbr"
The only reference in the logs I see is:
grep -i suicide mylar.log
`29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : ComicName: Suicide Squad
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : looking for : SUICIDE SQUAD
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : searchsql: %suicidesquad%
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : comparingSUICIDE SQUAD..to..SUICIDE SQUAD
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : watchcomic : Suicide Squad
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : comicnm : SUICIDE SQUAD
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : matched on:SUICIDE SQUAD...SUICIDE SQUAD
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : [Suicide Squad] trying to locate issue 20 to do comparitive issue analysis for pull-list
29-Jun-2017 06:43:04 - DEBUG   :: WEEKLYCHECK : Watchlist hit for : Suicide Squad ISSUE: 20
29-Jun-2017 06:43:05 - DEBUG   :: WEEKLYCHECK : Refreshing: Suicide Squad (2016) [93205]
29-Jun-2017 06:43:05 - DEBUG   :: WEEKLYCHECK : Available to be marked for download - checking...Suicide Squad Issue: 20
29-Jun-2017 06:43:05 - DEBUG   :: WEEKLYCHECK : UpcomingNewValue: {'Status': 'Wanted', 'ComicName': 'Suicide Squad', 'IssueID': u'605068', 'DisplayComicName': 'Suicide Squad', 'IssueNumber': '20', 'IssueDate': '2017-06-28'}
29-Jun-2017 06:43:05 - DEBUG   :: WEEKLYCHECK : Weekly Update for week 26-2017 : SUICIDE SQUAD #20 to a status of Wanted
29-Jun-2017 06:43:05 - INFO    :: WEEKLYCHECK : controlValue:{'COMIC': 'SUICIDE SQUAD', 'ISSUE': '20', 'WEEKNUMBER': 26, 'YEAR': '2017'}`

I have the RSS check every 30m, shouldn't I see an attempt every half hour?

**Comment by evilhero** [comment]
It might be erroring out on the demonoid parsing error and quiting entirely. And there is no way to turn off the feeds for the public torrents - you should see something when you run a force RSS check from the configuration screen where it shows the number of items retrieved from the RSS.
