### ISSUE TITLE
Sort by Active not working

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1489]
I am unable to sort by active on the home page

**Comment by evilhero** [comment]
Yeah cam confirm, although not sure what happened to break it again. I'll have to look into it more and see what's happening.

**Comment by evilhero** [comment]
Incoming....
![activity](https://cloud.githubusercontent.com/assets/909424/21331507/bd5f4020-c610-11e6-9aba-6eb90efbc7ba.png)

**Comment by DrSeussFreak** [comment]
It works!!!
