### ISSUE TITLE
No series getting marked "Ended"

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1493]
I have a couple of series that have not had a new issue since Jan or Feb 2016, but Mylar will not mark them as Ended.  I have tried running "Refresh Comic" on them but nothing changes.

Example Series: American Vampire: Second Cycle, Chewbacca (2015)

Mylar Version: development
-- git build 8a10181d32dc253cd7e766a3978daf429abbacfc.
Python Version : 2.7.12
OS: Ubuntu 16.04.1

**Comment by evilhero** [comment]
Can you confirm what the series are?  (the comicid is in the actual url for the Series page as well). 

I saw this happen a few days ago and coded a fix, but I wasn't sure if it was due to my constant testing of stuff that broke things or not.  The key part in all of this is the Last Issue and Published date for the respective series on the main/home page for mylar.

**Comment by BenBeyond** [comment]
American Vampire: Second Cycle:
http://comicvine.gamespot.com/american-vampire-second-cycle/4050-72399/
ComicID=72399

Chewbacca (2015):
http://comicvine.gamespot.com/chewbacca/4050-85275/
ComicID=85275

**Comment by BenBeyond** [comment]
My last issue date and Publication Date seem to be lining up:
![image](https://cloud.githubusercontent.com/assets/5505883/21326939/cbbfd2bc-c5fa-11e6-99e1-246da9b7f8de.png)

**Comment by evilhero** [comment]
What does it say for last issue and Published date on your main page for that series?

**Comment by BenBeyond** [comment]
![image](https://cloud.githubusercontent.com/assets/5505883/21327073/5f9fd5cc-c5fb-11e6-8ad9-d5cfaa5e54c9.png)

**Comment by evilhero** [comment]
Crap ok, that's not good.  I'll have to check more into that then, I'm on the phone atm so once I can get to a machine I should be able to figure things out better.

**Comment by evilhero** [comment]
Good to go now - was a stupid mixup in the type of check that was being done (should have been True/False but instead was testing for existence/not).

**Comment by BenBeyond** [comment]
Excellent! Thanks.
