### ISSUE TITLE
Sudden post-processing fail error

### ISSUE THREAD

**Issue by waz1500** [evilhero/mylar#1497]
Hi evilhero, 

Updated to the latest git of Mylar development branch a few iterations ago, but ever since I can't get post-processing to work correctly anymore. 
It looks like it's downloading correctly, but after clicking the Go Manual Run! button under Manual Post-Processing it fails and gives me the error below. 
I have post-processing set to copy files and have a Folder location to monitor enabled too. 

Any idea what's causing this error. Checking the mylar.log file also doesn't give me any more info than what is below which makes troubleshooting difficult. 

Mylar Version: development
-- git build b5814c9e228a844332b57fe32669f6b1b394560d.
Python Version : 2.7.9

> Uncaught exception: Traceback (most recent call last):
> File "/opt/Mylar/mylar/logger.py", line 158, in new_run
> old_run(*args, **kwargs)
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.__target(*self.__args, **self.__kwargs)
> File "/opt/Mylar/mylar/PostProcessor.py", line 1150, in Process
> dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
> File "/opt/Mylar/mylar/helpers.py", line 1838, in duplicate_filecheck
> 'to_dupe': os.path.join(series['ComicLocation'], dupchk['Location'])})
> File "/usr/lib/python2.7/posixpath.py", line 75, in join
> if b.startswith('/'):
> AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by evilhero** [comment]
Either your comic location path is empty or the location being dupe checked is empty (I think). 

Can you put mylar into verbose mode (-v on startup, or enable verbose in the logs tab of the GUI) and paste the lines just prior to the error? It has something to do with the paths, but without seeing the debug logs I can't tell atm.

**Comment by waz1500** [comment]
I've checked both locations and both have files. 
Comic Location path /home/morty/sync_folder/COMICS
Folder location to monitor /home/morty/torrents/rtorrent/COMICS_32P

I've enabled verbose mode and attached more info. Hopefully it will help. 

> 2016-12-21 14:19:19	ERROR	Uncaught exception: Traceback (most recent call last):
> File "/opt/Mylar/mylar/logger.py", line 158, in new_run
> old_run(*args, **kwargs)
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.__target(*self.__args, **self.__kwargs)
> File "/opt/Mylar/mylar/PostProcessor.py", line 1150, in Process
> dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
> File "/opt/Mylar/mylar/helpers.py", line 1838, in duplicate_filecheck
> 'to_dupe': os.path.join(series['ComicLocation'], dupchk['Location'])})
> File "/usr/lib/python2.7/posixpath.py", line 75, in join
> if b.startswith('/'):
> AttributeError: 'NoneType' object has no attribute 'startswith'
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Checking series for unrefreshed series syndrome (USS).
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing filesize is 0 bytes as I cannot locate the orginal entry - it is probably archived.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Archived
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Superman 012 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#10] Retaining currently scanned in filename : Justice League 010 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Justice League 010 (2017) (Webrip) (The Last Kryptonian-DCP).cbr has a filesize of : 37792776 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Justice League 010 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#946] Retaining currently scanned in filename : Detective Comics 946 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Detective Comics 946 (2017) (Webrip) (The Last Kryptonian-DCP).cbr has a filesize of : 34812241 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Detective Comics 946 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#12] Retaining currently scanned in filename : Wonder Woman 012 (2017) (2 covers) (digital) (Minutemen-Thoth).cbz
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Wonder Woman 012 (2017) (2 covers) (digital) (Minutemen-Thoth).cbz has a filesize of : 41481524 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Wonder Woman 012 (2017) (2 covers) (digital) (Minutemen-Thoth).cbz
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#8] Retaining currently scanned in filename : Suicide Squad 008 (2017) (2 covers) (digital) (Minutemen-Midas).cbr
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Suicide Squad 008 (2017) (2 covers) (digital) (Minutemen-Midas).cbr has a filesize of : 50174670 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Suicide Squad 008 (2017) (2 covers) (digital) (Minutemen-Midas).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#13] Retaining currently scanned in filename : Superman 013 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Superman 013 (2017) (Webrip) (The Last Kryptonian-DCP).cbr has a filesize of : 37379161 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Superman 013 (2017) (Webrip) (The Last Kryptonian-DCP).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#5] Retaining currently scanned in filename : Red Hood & the Outlaws 005 (2017) (2 covers) (Digital) (Zone-Empire).cbr
> 2016-12-21 14:19:19	DEBUG	[DUPECHECK] Based on duplication preferences I will retain based on : filesize
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing file within db :Red Hood & the Outlaws 005 (2017) (2 covers) (Digital) (Zone-Empire).cbr has a filesize of : 41462953 bytes.
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Downloaded
> 2016-12-21 14:19:19	INFO	[DUPECHECK] Duplicate check for /home/morty/torrents/rtorrent/COMICS_32P/Red Hood & the Outlaws 005 (2017) (2 covers) (Digital) (Zone-Empire).cbr
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#12] Retaining currently scanned in filename : The Flash 012 (2017) (2 covers) (digital) (Minutemen-Thoth).cbzseed
> 2016-12-21 14:19:19	INFO	[DUPECHECK-FILESIZE PRIORITY] [#12] Retaining currently scanned in filename : The Flash 012 (2017) (2 covers) (digital) (Minutemen-Thoth).cbz

**Comment by evilhero** [comment]
Ahh, ok I can see now:
```
2016-12-21 14:19:19	INFO	[DUPECHECK] Existing filesize is 0 bytes as I cannot locate the orginal entry - it is probably archived.
2016-12-21 14:19:19	INFO	[DUPECHECK] Existing Status already set to Archived
```
So the file is in an archived status, so it doesn't have a location attached to it to verify the filesize which is causing the problem. Normally when it's set to Archived status, Mylar will consider it a dupe and not post-process the given issue since alot of users use the Archived status for different purposes, but regardless of the intent it's meant to indicate that the given issue is no longer present physically.

The easiest solution in this case, is to just mark the given issue as Skipped and then Mylar will post-process it (marking it as Wanted would make it run through the search again, when you already have it ready to post-process).

I should be able to add in some kind of catch so that if the archived file doens't exist on the system that it just bypass entirely.

**Comment by waz1500** [comment]
Thanks evilhero! 

Setting all affected issues to Skipped solved the post-process problem. Yay! 
Looking forward to seeing the commit in the upcoming Mylar updates. :)
