### ISSUE TITLE
Torrentproject blocked and WWT not downloading

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1499]
Hi there

For the last little while, Mylar has not been downloading any comics for me. Torrontproject is blocked by my ISP but it seems that WWT is also not working. When I search for a comic on WWT myself, I can find it and download it (at that point Mylar recognises it and post-processes it without issue) but it seems that Mylar cannot successfully find anything using WWT.

Here is the output from Mylar when running a manual search:

22-Dec-2016 12:03:29 - INFO :: Thread-16 : Initiating manual search for Guardians of the Galaxy issue: 15
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Publisher is : Marvel
22-Dec-2016 12:03:29 - INFO :: Thread-16 : Issue Title given as : None
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Checking for torrent enabled.
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : nzbprovider(s): []
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : there are : 1 torrent providers you have selected.
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : there are : 0 nzb providers you have selected.
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Usenet Retention : 1500 days
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : found provider in existing enabled providers.
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : checking against torrent provider: tpse
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : torrent provider found: tpse
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : provider order sequence is now to start with tpse at spot #0
22-Dec-2016 12:03:29 - INFO :: Thread-16 : search provider order is ['tpse']
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Initiating Search via : rss
22-Dec-2016 12:03:29 - INFO :: Thread-16 : allow_packs set to :None
22-Dec-2016 12:03:29 - INFO :: Thread-16 : Shhh be very quiet...I'm looking for Guardians of the Galaxy issue: 15 (2017) using TPSE [RSS]
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : calpha/cnumber: None / None
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Sending request to [TPSE] RSS for Guardians of the Galaxy : 015
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : ComicID: 85290
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : tsearch : guardians%of%%%galaxy%
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : seriesname_alt:None
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Sending request to [TPSE] RSS for Guardians of the Galaxy : 15
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : ComicID: 85290
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : tsearch : guardians%of%%%galaxy%
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : seriesname_alt:None
22-Dec-2016 12:03:29 - INFO :: Thread-16 : Could not find Issue 15 of Guardians of the Galaxy (2015) using TPSE [rss]
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Could not find issue doing a manual search via : rss
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Initiating Search via : api
22-Dec-2016 12:03:29 - INFO :: Thread-16 : allow_packs set to :None
22-Dec-2016 12:03:29 - INFO :: Thread-16 : Shhh be very quiet...I'm looking for Guardians of the Galaxy issue: 15 (2017) using TPSE
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : calpha/cnumber: None / None
22-Dec-2016 12:03:29 - DEBUG :: Thread-16 : Sending request to [TPSE] for guardians of galaxy : 015
ERROR:root:'https://torrentproject.se/rss/guardians%20of%20galaxy%20015/' returned an error. Could not collect tokens.
22-Dec-2016 12:03:31 - WARNING :: Thread-16 : Error fetching RSS Feed Data from TPSE: [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:590)
22-Dec-2016 12:03:31 - ERROR :: Thread-16 : Uncaught exception: Traceback (most recent call last):
  File "/Applications/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/mylar/mylar/webserve.py", line 1415, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
  File "/Applications/mylar/mylar/search.py", line 257, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
  File "/Applications/mylar/mylar/search.py", line 695, in NZB_SEARCH
    for entry in bb['entries']:
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "/Applications/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/mylar/mylar/webserve.py", line 1415, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
  File "/Applications/mylar/mylar/search.py", line 257, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
  File "/Applications/mylar/mylar/search.py", line 695, in NZB_SEARCH
    for entry in bb['entries']:
TypeError: 'NoneType' object has no attribute '__getitem__'

This is running on OS X 10.10.5 with Python 2.7.10

Thank you for such a great program!

**Comment by evilhero** [comment]
Mylar cant search wwt - it can only poll against it's Rss feeds, so if it's not on the feed or mylar wasn't running when the issue got uploaded you wouldn't be able to snatch it (mylar does cache the results however).  For api/backlog searching mylar uses TPSE, which is what it giving you the error. It should be caught better, but it already searched against wwt and didn't get any results so it dropped down to the TPSE search which is giving the error you see.

**Comment by kurnalbert** [comment]
I thought that would be the case. However it doesn't pick up any of the issues from WWT on RSS. 
Mylar is running 24-7 and the issues are going up on WWT but it seems that Mylar doesn't detect them on there. 
I didn't know where to go to try to find logs for it searching on RSS.
