### ISSUE TITLE
Deluge "No module named bencode"

### ISSUE THREAD

**Issue by misleadingrhino** [evilhero/mylar#1517]
Just noticed the Deluge integration and thought I'd switch from a watch directory. 

It looks like it's connecting, but I keep getting the error "No module named bencode"

Below is the relevant section of the log. Happens with every comic. Please let me know if there's anything else needed.

> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Initiating manual search for Civil War II issue: 8
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Issue Title given as : None
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : search provider order is ['32p', 'tpse']
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : allow_packs set to :False
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Civil War II issue: 8 (2017) using 32P [RSS]
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Could not find Issue 8 of Civil War II (2016) using 32P [rss]
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : allow_packs set to :False
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Civil War II issue: 8 (2017) using TPSE [RSS]
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Could not find Issue 8 of Civil War II (2016) using TPSE [rss]
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : allow_packs set to :False
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Civil War II issue: 8 (2017) using 32P
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Could not find Issue 8 of Civil War II (2016) using 32P [api]
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : allow_packs set to :False
> 31-Dec-2016 09:33:30 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Civil War II issue: 8 (2017) using TPSE
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : [TPSE] there were 11 results..
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : TPSE
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : rss:no
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : allow_packs:False
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : Found Civil War II (2017) issue: 8 using TPSE
> 31-Dec-2016 09:33:37 - INFO    :: Thread-15 : matched on Civil War II
> 31-Dec-2016 09:33:42 - INFO    :: Thread-15 : Connected to Deluge! Will try to add torrent now! (rsscheck)
> 31-Dec-2016 09:33:42 - INFO    :: Thread-15 : filepath to torrent file set to : /opt/Mylar/cache/Civil_War_II_8_2017.torrent
> 31-Dec-2016 09:33:42 - INFO    :: Thread-15 : Checking if Torrent Exists!
> 31-Dec-2016 09:33:42 - ERROR   :: Thread-15 : No module named bencode
> 31-Dec-2016 09:33:42 - ERROR   :: Thread-15 : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
> 31-Dec-2016 09:33:42 - INFO    :: Thread-15 : Could not find Issue 8 of Civil War II (2016) using TPSE [api]

The full log file is also attached.

Thank you guys so much for your hard work!
[mylar.txt](https://github.com/evilhero/mylar/files/679674/mylar.txt)

**Comment by evilhero** [comment]
That's weird, the bencode module is included in the mylar subdirectory (it's called bencode.py). Can you confirm that it's there (if you have a .pyc file, delete that maybe).

I see a bunch of different errors in the full log you provided - have you tried to restart Mylar at all since encountering the error?

**Comment by misleadingrhino** [comment]
I restarted and tried again just now, still the same issue. 

I deleted the bencode.pyc file, no change. 

I cleaned out all the old comics so this log file should be a little cleaner. It's everything since a fresh restart after deleting bencode.pyc. 

[mylar2.txt](https://github.com/evilhero/mylar/files/679846/mylar2.txt)

Thanks!

**Comment by evilhero** [comment]
Sorry for the delay, holidays and all ;)

I can confirm this is a bug - I actually had a bencode.py file located in my local repo of Mylar, and I'm assuming the gent who did the PR had the same or had the bencode module installed locally.

I'll get a fix out in the next few moments for this...

**Comment by misleadingrhino** [comment]
New build works. Thanks for the update!
