### ISSUE TITLE
"This Week" pull list is blank

### ISSUE THREAD

**Issue by GTSlayer** [evilhero/mylar#1522]
Having an odd issue with the weekly pull list. Refreshing the pull-list, moves to a localhost:port#/manualpull  url with just the word status appearing on the page. 

Recreating the pull-list just leads to the same blank page. 

Hitting the arrow over to week 2, then back to week 1 for this week causes the stuff to appear, but none of my continuing series are linked or can be added.

The pull list seems to be working fine according to the logs. Only thing that seems odd to me is the pulldate of 00000000.

> 2017-01-02 15:04:27	INFO	AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Inhumans vs X-men'}], 'ComicID': u'96144'}
2017-01-02 15:04:27	INFO	[PULL-LIST] Weekly Pull List successfully loaded with 74 issues.
2017-01-02 15:04:27	INFO	[PULL-LIST] Successfully populated pull-list into Mylar for the week of: 01
2017-01-02 15:04:26	INFO	[WEEKLY-PULL] There are 74 issues for the week of 01, 2017
2017-01-02 15:04:26	INFO	pulldate is : 00000000
2017-01-02 15:04:26	INFO	[PULL-LIST] Populating & Loading pull-list data directly from alternate website
2017-01-02 15:04:26	INFO	Weekly pull list present - checking if it's up-to-date..

**Comment by evilhero** [comment]
The pullist of 00000000 I actually normal, it's just a flag for mylar to know to do a recreate pullist - usually it's done on every startup or every 2/4 hrs depending on how up to date you are. 

The fix for this went into dev yesterday so I'm going to guess that you're running the master build, or you haven't updated to the latest dev commit yet?

**Comment by GTSlayer** [comment]
I'm on Dev but doesn't seem to be pulling new updates. I'll have to pull down the latest version.

**Comment by juliemars** [comment]
@evilhero same issue I am on build da454bd2f93cccafbd99536af8750a6997e30bb5 but the weekly list is blank. I have tried a Git Pull but all I get is

remote: Counting objects: 21, done.
remote: Total 21 (delta 14), reused 14 (delta 14), pack-reused 7
Unpacking objects: 100% (21/21), done.
From https://github.com/evilhero/mylar
   f0f9cda..d688440  master     -> origin/master
Already up-to-date.

I see it reports it as master branch so I ran git checkout development but it says 
Already on 'development'
Your branch is up-to-date with 'origin/development'.

not sure if something else is going wrong?

**Comment by evilhero** [comment]
Make sure that within your config.ini that the variable 'git_branch' is set to development and not master (ie. git_branch = development). When you're editing the config.ini, you can't have Mylar running or else the config won't accept the changes properly. Then when you startup Mylar, you should see the proper commit /branch on the bottom of each page and or on the first tab of the Configuration GUI.

**Comment by juliemars** [comment]
hi evilhero, just checked and config does say dev branch, still no pull lists

**Comment by evilhero** [comment]
Try restarting mylar. Then go to the pullist and try doing a recreate pullist. 

Actually, in your config.ini which alt_pull option are you using : 0, 1, or 2?

**Comment by juliemars** [comment]
Hi evilhero, it was set to 0 I changed it to 2 and it worked, can I ask what the 0,1 and 2 options mean?

**Comment by evilhero** [comment]
0 is the original pull method, where it retrieves a txt listing from previews world. 1 allows mylar to parse the webpage of previews world, which would allow mylar to populate the list a day or so before the 0 method. 

The 2 method is the newest method, but also the one with the most benefits. It polls directly against another site which has up to date pull list data for up to 4 weeks in advance. It also has the comic information linked to cv so that mylar doesn't have to poll cv every few hrs to see if there's a new issue or not (which means way less api hits against cv) . It updates the list every 2 hrs, and mylar can receive the updated list every 2/4 hrs. A bunch of other stuff too, but it's by far the best option available to use currently.

**Comment by DrSeussFreak** [comment]
I'm on "Version: 8e217bcf58c1d397abf52e9b3793f7fabab81995 (development)" and having the same issue

**Comment by evilhero** [comment]
@DrSeussFreak restart Mylar and try doing a Recreate Pullist once Mylar has fully loaded. As long as you're running the latest build with python > 2.7.9, it shouldn't have any problems retrieving the pullist.

You can confirm what your alt_pull variable is set to within the config.ini file as well - 0 will poll against previewsworld which is the default, 2 will use a new method and going forward is probably the better of the 2 options to choose for various reasons.

**Comment by juliemars** [comment]
@evilhero intrestingly the issue came back for me as well, stopped MyLar and checked config and it had reset to Alt_Pull = 0 changed to 2 and restarted MyLar did a recreate that fixed it, not sure why the config is being overwritten though.

**Comment by evilhero** [comment]
@juliemars are you running mylar through a 3rd party app, like a docker or package? Mylar only rewrites the config on save and restart/shutdown - if you had the config.ini open during one of those states it would not have saved properly (just a guess)

**Comment by DrSeussFreak** [comment]
I am not running in on a 3rd party platform, run on windows, and it keeps resetting to 0.  I shut it down, set it to 2, start it up and it changes to 0.

**Comment by evilhero** [comment]
You might have the ini file locked if you start it up as a daemon or in the background since it's windows, and it wouldn't be able to save the config since it was being used.

**Comment by juliemars** [comment]
@evilhero no 3rd party, just running it on RaspberryPi (Minbian  OS I think) 

Intrestingly I went to add a comic today and it wouldn't looked at the log and it said no path, went into the config via the website and it was all blank like a new install. Something has defienetly went wrong for me :)

**Comment by DrSeussFreak** [comment]
Not sure what changed, but it is not sticking with 2, and working as expected

**Comment by rbm-aalsaleh** [comment]
I can also confirm, on development, changing from 0 to 2 fixed the lack of a pull list.

It looks like this might be a related error. It shows up only when I'm using method 0, and repeats multiple times.

2017-01-18 20:25:58	ERROR	this has an alpha-numeric in the issue # which I cannot account for.

I can Try to suss out more information for you if you think it will help.

**Comment by knightabe** [comment]
I can also confirm, on development, changing from 0 to 2 fixed the lack of a pull list.

It looks like this might be a related error. It shows up only when I'm using method 0, and repeats multiple times.

2017-01-18 20:25:58	ERROR	this has an alpha-numeric in the issue # which I cannot account for.

I can Try to suss out more information for you if you think it will help.

**Comment by evilhero** [comment]
Ah Ok I think I can see... It's either the 3.1 issue number, or the bunch of (C:1-1-0) types being shown now for one reason. 

I'll have to flip mine to method 0 and try to see exactly where it's bombing out. 

Thanks for the heads up and giving an indication of where I might be able to start due to that error message.
