### ISSUE TITLE
Any way to disable Demonoid?

### ISSUE THREAD

**Issue by Slyneth** [evilhero/mylar#1523]
Hi.

Thanks for the great program. I am using it with great success with Usenet, but I want to use WWT too but I am not able to. The problem is Demonoid, anytime I try to enable the public torrents for the rss, Demonoid breaks it. This is the warning I get:

    Error fetching RSS Feed Data from DEM: EOF occurred in violation of protocol (_ssl.c:590)

After that RSS search ends without ever looking at WWT. I tried to disable Demonoid by myself and while I managed to do it for RSS searchs, I also broke Newsnab. I upgraded OpenSSL to the last version too. I am on OS X with Homebrew's Python.

So, any way I can disable Demonoid completely by hand?

Thanks.

**Comment by evilhero** [comment]
Demonoid changed their domain - the rss seems to work occasionally (can use either domain it seems), but the actual files to download have to come from the new domain. Unfortunately Mylar rebuilds the url link  to download dynamically depending on the provider, so it's recreating the download link with the incorrect domain.

**Comment by Slyneth** [comment]
I am still having the same problem.

**Comment by evilhero** [comment]
Are you running master or dev and what commit?

I'm not getting any errors when I try - are you getting the exact same error?

**Comment by Slyneth** [comment]
I am at master with 2eb28c4. Error is the same. Python, OpenSSL and pyOpenSSL are the lastest. I even tried overriding OS X's own OpenSSL and using Homebrew's.

When I tried Demonoid with http in rsscheck.py, I can force RSS search succesfully. But Newznab doesn't work then with the same error.

Demonoid isn't really needed anyway, most of their comic torrents are external from WWT, and others are scraped by Torrent Project.

**Comment by Slyneth** [comment]
I reinstalled everything, now Demonoid works well. But I have another problem with RSS now =(:

```
10-Jan-2017 15:47:02 - INFO :: CP Server Thread-4 : Attempting to run RSS Check Forcibly
10-Jan-2017 15:47:02 - INFO :: Thread-12 : RSS Feed Check was last run at : 2017-01-10 15:41:50
10-Jan-2017 15:47:02 - INFO :: Thread-12 : RSS Feed Check First Ever Run.
10-Jan-2017 15:47:02 - DEBUG :: Thread-12 : Updating RSS Run time to : 2017-01-10 15:47:02
10-Jan-2017 15:47:02 - INFO :: Thread-12 : [RSS] Initiating Torrent RSS Check.
10-Jan-2017 15:47:02 - INFO :: Thread-12 : [RSS] Initiating Torrent RSS Feed Check on TorrentProject.
10-Jan-2017 15:47:05 - INFO :: Thread-12 : [DEM] there were 50 results from the New Releases RSS Feed from Demonoid
10-Jan-2017 15:47:05 - INFO :: Thread-12 : FEED: https://www.worldwidetorrents.eu/rss.php?cat=50
10-Jan-2017 15:47:05 - INFO :: RSSCHECK : RSS Feed Check was last run at : 2017-01-10 15:47:02
10-Jan-2017 15:47:05 - DEBUG :: RSSCHECK : RSS Check has taken place less than the threshold - not initiating at this time.
10-Jan-2017 15:47:05 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/Users/msimsek/Applications/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/msimsek/Applications/mylar/mylar/rsscheckit.py", line 62, in run
    rsscheck.torrents(pickfeed='TPSE')    #TPSE = DEM RSS Check + WWT RSS Check
  File "/Users/msimsek/Applications/mylar/mylar/rsscheck.py", line 217, in torrents
    'size':     helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz))   #+ 2 is for the length of the MB/GB in the size.
  File "/Users/msimsek/Applications/mylar/mylar/helpers.py", line 168, in human2bytes
    assert float(num) and letter in symbols
ValueError: invalid literal for float(): 1,008.53

Traceback (most recent call last):
  File "/Users/msimsek/Applications/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/msimsek/Applications/mylar/mylar/rsscheckit.py", line 62, in run
    rsscheck.torrents(pickfeed='TPSE')    #TPSE = DEM RSS Check + WWT RSS Check
  File "/Users/msimsek/Applications/mylar/mylar/rsscheck.py", line 217, in torrents
    'size':     helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz))   #+ 2 is for the length of the MB/GB in the size.
  File "/Users/msimsek/Applications/mylar/mylar/helpers.py", line 168, in human2bytes
    assert float(num) and letter in symbols
ValueError: invalid literal for float(): 1,008.53
10-Jan-2017 15:47:32 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder /Users/msimsek/Library/Application Support/NZBGet/Comics for newly snatched downloads
```

**Comment by evilhero** [comment]
Both wwt and Dem serve a purpose within mylar, and stuff get posted to Dem that is not on wwt. Others have requested the use of Dem, so it makes no sense for me to take it away unless it's not working for everyone, instead of just one. 

It sounds like you're too current with your python stuff and you probably need to do a 'pip install requests[security]'  in order to allow for https sni verification properly and should fix your problem. 

 Note that changing something for Dem, would have no effect on your newznab as they are totally independent, which makes me think that your problem is greater that just the one provider (along with the fact that it worked via http - only Rss is tied to https verification, the actual grab is via non-https which I'll be fixing sooner rather than later)

**Comment by Slyneth** [comment]
Thanks, DEM got fixed after I reinstalled Python, requests were installed by the way. I changed my post the same time you replied. I have another problem now. It seems this is completely on my side, I can do without RSS, not that big of a problem. WWT releases a few hours before Usenet but I can wait.

**Comment by evilhero** [comment]
The error is due to wwt having  a non numeric (a comma) in the size field and mylar wasn't expecting it. I'll try and push out a fix in the next few hrs to correct that since I'm on my phone atm.

The 'requests[security]' install is different than a normal requests install as it installs additional modules that might be required on some systems for ssl/security, but isn't installed during a normal requests install. 

But if it's working now, then obviously you dont need to fix anything on your end ;)
