### ISSUE TITLE
Error trying to download Pull List

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1524]
I get the error below when I tried to download the weekly pull list:

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 645, in respond
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
  File "C:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
  File "C:\Mylar\mylar\webserve.py", line 3321, in MassWeeklyDownload
    issuelist = helpers.listIssues(pulldate['weeknumber'],pulldate['year'])
TypeError: string indices must be integers

Also, would it be possible to have an option to change where the different lists download to instead of the default Mylar directory?

**Comment by evilhero** [comment]
I'm assuming you're using the original pull method (in your config.ini, it's probably alt_pull = 0). 

If so, I'd shutdown mylar, edit the config.ini and change the alt_pull to alt_pull = 2

Save the config, restart mylar and it should truck along fine thereafter. 

I'll have to look into changing the default list location, it makes it difficult to manage when it's outside of mylar's given directories on some systems.

**Comment by wraith1385** [comment]
Actually I'm already using alt_pull = 2 in the config file.  

Also don't worry about the list thing, I just wanted to ask in case it was something easy.

**Comment by evilhero** [comment]
Oh wait.. Download.. Crap, ok I probably didn't update that with the last few PR's. I'll have to fix that... 

I don't mind looking into the download option, it's been asked before and it honestly just slipped my mind to look into it again. I'll see bout incorporating it in the next PR ;)

**Comment by thewindupboy** [comment]
I've actually always gotten this error (see below).
And now, I have no pull list at all.  I had it for a while, then it vanished, then returne, over the past few days.  But now the weekly pull list for week 1, January 01, 2017 - January 07, 2017, is completely blank.

Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 3321, in MassWeeklyDownload
    issuelist = helpers.listIssues(pulldate['weeknumber'],pulldate['year'])
TypeError: string indices must be integers

**Comment by WedgeSparda** [comment]
My pull list is vanished too right now

**Comment by thewindupboy** [comment]
CURSE YOU, 2017!!!!

**Comment by evilhero** [comment]
@thewindupboy : make sure you're running the latest dev commit - you can't download issues using the download buttoned if there's nothing on the pullist to compare against (just guessing, but if there's no list it would cause subsequent errors)

**Comment by thewindupboy** [comment]
Sure, but I have literally always gotten this error, even when I had a pull-list.

**Comment by evilhero** [comment]
Is your alt_pull set to 0 or 2 in the config.ini? If it's not 2 - first shut down mylar, change it to 2, save the config and start mylar up. 

If it's 2 already, try restarting mylar and then do a recreate pullist once it's fully started. Make sure you put mylar in verbose mode to get full debug logs as well if necessary. 

Are you running mylar via a 3rd party package? What os?

**Comment by thewindupboy** [comment]
Changing it to 2 worked!

**Comment by evilhero** [comment]
Alright well then I'm pretty sure that the 0 method is borked up atm -  at least I know where to look ;) 

Thanks for reporting back that it's fixed!

**Comment by thewindupboy** [comment]
And thanks for the fast response!  This is something I should have done a while ago, anyhow, since now I also get the publisher with each title.
