### ISSUE TITLE
Deluge not getting label from Mylar

### ISSUE THREAD

**Issue by misleadingrhino** [evilhero/mylar#1525]
Hey guys, sorry to keep bothering you but I figured you'd want to know. 

Thanks to your last update evil, Deluge is now working!

But it's not sending the label specified in the settings. This is obviously not a huge deal, but I thought you'd like to know. 

This is the relevant section of the log

> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Marking Avengers issue: 1.1 as wanted...
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Issue Title given as : None
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : search provider order is ['32p', 'tpse']
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : allow_packs set to :False
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Shhh be very quiet...I'm looking for Avengers issue: 1.1 (2017) using 32P [RSS]
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Could not find Issue 1.1 of Avengers (2016) using 32P [rss]
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : allow_packs set to :False
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Shhh be very quiet...I'm looking for Avengers issue: 1.1 (2017) using TPSE [RSS]
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : WWT
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : rss:yes
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : allow_packs:False
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : Found Avengers (2017) issue: 1.1 using WWT [RSS]
> 04-Jan-2017 08:09:58 - INFO    :: Thread-12 : matched on Avengers
> 04-Jan-2017 08:09:59 - INFO    :: FOLDERMONITOR : Attempting to retrieve the comic image for series
> 04-Jan-2017 08:09:59 - INFO    :: Thread-12 : Connected to Deluge! Will try to add torrent now! (rsscheck)
> 04-Jan-2017 08:09:59 - INFO    :: Thread-12 : filepath to torrent file set to : /opt/Mylar/cache/Avengers_1.1_2017.torrent
> 04-Jan-2017 08:09:59 - INFO    :: Thread-12 : Checking if Torrent Exists!
> 04-Jan-2017 08:09:59 - INFO    :: Thread-12 : Getting Torrent Info!
> 04-Jan-2017 08:09:59 - INFO    :: Thread-12 : Torrent not added yet, trying to add it now!
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Marking Avengers issue: 3 as wanted...
> 04-Jan-2017 08:10:00 - INFO    :: Thread-12 : setting the nzbid for this download grabbed by WWT in the nzblog to : 26027
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : No Store Date found for given issue. This is probably due to not Refreshing the Series beforehand.
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : I Will assume IssueDate as Store Date, but you should probably Refresh the Series and try again if required.
> 04-Jan-2017 08:10:00 - INFO    :: Thread-12 : Sending Pushover notification
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Issue Title given as : None
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : search provider order is ['32p', 'tpse']
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : allow_packs set to :False
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Shhh be very quiet...I'm looking for Avengers issue: 3 (2017) using 32P [RSS]
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Could not find Issue 3 of Avengers (2016) using 32P [rss]
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : allow_packs set to :False
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Shhh be very quiet...I'm looking for Avengers issue: 3 (2017) using TPSE [RSS]
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : WWT
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : rss:yes
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : allow_packs:False
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : Found Avengers (2017) issue: 3 using WWT [RSS]
> 04-Jan-2017 08:10:00 - INFO    :: Thread-13 : matched on Avengers
> 04-Jan-2017 08:10:01 - INFO    :: Thread-12 : [NOTIFIER] PushOver notifications sent.
> 04-Jan-2017 08:10:01 - INFO    :: Thread-12 : passing to updater.
> 04-Jan-2017 08:10:01 - INFO    :: Thread-12 : [UPDATER] Updating status to snatched
> 04-Jan-2017 08:10:01 - INFO    :: Thread-13 : Connected to Deluge! Will try to add torrent now! (rsscheck)
> 04-Jan-2017 08:10:01 - INFO    :: Thread-13 : filepath to torrent file set to : /opt/Mylar/cache/Avengers_3_2017.torrent
> 04-Jan-2017 08:10:01 - INFO    :: Thread-13 : Checking if Torrent Exists!
> 04-Jan-2017 08:10:01 - INFO    :: Thread-13 : Getting Torrent Info!
> 04-Jan-2017 08:10:01 - INFO    :: Thread-13 : Torrent not added yet, trying to add it now!
> 04-Jan-2017 08:10:01 - INFO    :: Thread-12 : [UPDATER] Updated the status (Snatched) complete for Avengers Issue: 1.1
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : setting the nzbid for this download grabbed by WWT in the nzblog to : 37426
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : Sending Pushover notification
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : [NOTIFIER] PushOver notifications sent.
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : passing to updater.
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : [UPDATER] Updating status to snatched
> 04-Jan-2017 08:10:02 - INFO    :: Thread-13 : [UPDATER] Updated the status (Snatched) complete for Avengers Issue: 3

Attached is the full log, just in case.

[mylar2017-01-04.txt](https://github.com/evilhero/mylar/files/684697/mylar2017-01-04.txt)

Thanks again for all your hard work!

**Comment by evilhero** [comment]
What do you have the label set to in mylar and does the same label already exist within your deluge client (ie. did you create the label previously)?

**Comment by misleadingrhino** [comment]
The label is comics and it already exists in deluge.

**Comment by weidercs** [comment]
Had the same issue this morning, all my pulls went to deluge w/o label (and subsequently went to the wrong directory)

**Comment by evilhero** [comment]
Weird this was working, I'll have to fire up my deluge client to see what's happening

**Comment by misleadingrhino** [comment]
Can confirm fixed. 

Thanks again!
