### ISSUE TITLE
Getting "invalid or corrupt torrent file" with all downloads

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1526]
I'm getting an error with each issue on my watchlist when trying to download.

```
ERROR	Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
ERROR	Query failed with result "invalid or corrupt torrent file".
DEBUG	[WWT] Saved torrent file to : /usr/local/mylar/share/mylar/cache/Champions_4_2017.torrent
```
Is a bit weird that all torrents are invalid or corrupted, isn't it?
Didn't change anything on my config, so I don't know why is this happening.

**Comment by evilhero** [comment]
What client ard you using to download?

**Comment by WedgeSparda** [comment]
Transmission

**Comment by WedgeSparda** [comment]
I just notice that the file permissions for the downloaded torrent files are different than the other files on the cache dir.

-rw-rw-rw- 1 mylar users   412322 Dec 26 10:22 96300.jpg
-rw-rw-rw- 1 mylar users   403977 Dec 14 17:00 96657.jpg
-rw-rw-rw- 1 mylar users   392910 Dec 26 10:25 96661.jpg
-rw------- 1 mylar users        0 Jan  5 12:49 Clean-newreleases.txt
**-rw------- 1 mylar users    28826 Jan  5 13:04 Hawkeye_2_2017.torrent**

Are those permissions right?

**Comment by WedgeSparda** [comment]
So, that's seems to be the problem, because I changed the torrent files permission to 666 and now Transmission is downloading them.

I have this config on the permissions settings

<img width="445" alt="shot" src="https://cloud.githubusercontent.com/assets/48375/21680271/03c1bcd8-d349-11e6-9e02-0250b5c645ab.png">

**Comment by evilhero** [comment]
Well 0660 isn't 666...youd need to set it to 0666 for file chmod to have those file rights. Makes sense, cause if the user running transmission is not in the users group - it would have zero access to the file given your current perms. 

Just curious why you have owner set to admin and no group, when your cache is set to mylar / users.

**Comment by WedgeSparda** [comment]
Ok, I changed to 0666 and I'll see what happens.
I set owner to admin because is the user of my Synology NAS, where Mylar is running. But now that you mentioned I changed the owner to "mylar" and set the group to "users".

**Comment by tresni** [comment]
I think I may know the issue here.  transmissionrpc expects local files to have a "file://" schema.  Otherwise it passes the path to the file to transmission as being on transmission's local filesystem.  Given how mylar runs, I think it would be appropriate to always preface with "file://" so that it base64's the torrent data and passes it to transmission.  I'm testing this locally right now and will report back with success (and a PR) or failure.

**Comment by tresni** [comment]
This seems to resolve the issue for me, submitting a PR:

```
diff --git a/mylar/torrent/clients/transmission.py b/mylar/torrent/clients/transmission.py
index ee3871c..001c3e1 100755
--- a/mylar/torrent/clients/transmission.py
+++ b/mylar/torrent/clients/transmission.py
@@ -76,7 +76,7 @@ class TorrentClient(object):
             down_dir = mylar.CHECK_FOLDER
         else:
             down_dir = mylar.TRANSMISSION_DIRECTORY
-        torrent = self.conn.add_torrent(filepath,
+        torrent = self.conn.add_torrent('file://%s' % filepath,
                                         download_dir=down_dir)

         torrent.start()
```
