### ISSUE TITLE
Problem retrying failed downloads

### ISSUE THREAD

**Issue by dazzla76** [evilhero/mylar#1529]
Hi,

I'm having a problem when hitting the retry button on the history page to give failed downloads another go.  I get the following in the log file when it fails:

Incidentally the downloads failed because SAB was trying to use the Mylar API on the internal docker IP address, i "think" i've fixed it by setting the host_return variable.

```05-Jan-2017 21:17:54 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/
05-Jan-2017 21:17:54 - INFO    :: MAIN : Initializing the DB Updater.
05-Jan-2017 21:17:54 - INFO    :: RSSCHECK : delaying thread for 30 seconds to avoid locks.
05-Jan-2017 21:17:54 - INFO    :: MAIN : Initiating startup-RSS feed checks.
05-Jan-2017 21:17:54 - INFO    :: MAIN : Checking for existance of Weekly Comic listing...
05-Jan-2017 21:17:54 - INFO    :: WEEKLYCHECK : delaying thread for 10 seconds to avoid locks.
05-Jan-2017 21:17:58 - INFO    :: Thread-12 : ComicID:91285
05-Jan-2017 21:17:58 - INFO    :: Thread-12 : Retrying : 574844
05-Jan-2017 21:17:58 - INFO    :: Thread-12 : Located snatched download:
05-Jan-2017 21:17:58 - INFO    :: Thread-12 : --Referencing : dognzb @ 2017-01-05 20:34:31
05-Jan-2017 21:17:58 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/webserve.py", line 1196, in retryissue
    if Provider == 'nzb.su':
NameError: global name 'Provider' is not defined

05-Jan-2017 21:18:04 - INFO    :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
05-Jan-2017 21:18:04 - INFO    :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..```

**Comment by evilhero** [comment]
Yep, that's an error - not sure how it wasn't caught awhile ago (since it's been awhile since I touched that portion of code). I'll look into it and see what's going on and push out a fix soon for it.

If you're still having problems with the send-to-sab and the docker, just shoot me a message. I don't use docker, but I'm pretty sure we can get it working as it's intended ;)

**Comment by ForumFerret** [comment]
Ah, same as me I think:

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/gitmylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/gitmylar/mylar/mylar/webserve.py", line 1280, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
NameError: global name 'Provider' is not defined

That's a git install on a synology nas.

**Comment by evilhero** [comment]
Looks like I missed  call, fix will be up shortly
