### ISSUE TITLE
StoryArc not able to be searched in master

### ISSUE THREAD

**Issue by zeryl** [evilhero/mylar#1535]
Presently on Master (tried dev as well) with version 57d309d38e571b70f346c70103bb8de362df7e22

Searched for World War Hulk storyarc, found it, and hit add.  No matter how many times I hit refresh story arc, I don't get an option to download the associated comics.

I don't have the series added for each issue, but I would have figured it would have just downloaded those available.  With this, I also do not have any option to change from "skipped" to wanted.  I must be missing something, but I don't know what.

**Comment by evilhero** [comment]
The refresh doesn't initiate a search, it only checks against your current watch list and story-arcs directory for existing issues. If you want to run a full search for missing issues of the arc, you'd have to select the 'search for missing' button at the top of the arc details page for the given arc. You can also do a one-off via the  'get it' option where it will do a search immediately for the given issue, but it won't retry the search afterwards (its not automated to search every x hours)

**Comment by zeryl** [comment]
Where is the "get it" option?  I don't see that at all.  And you are absolutely right, the search for missing seems to actually be doing something now (though I don't recall seeing that prior).  Thank you! I think this can be closed.

**Comment by evilhero** [comment]
Sorry I meant "grab it" - it's listed beside each issue in the given arc that is not in a downloaded status.
