### ISSUE TITLE
Mylar won't open

### ISSUE THREAD

**Issue by voipblaster** [evilhero/mylar#1539]
I was trying to configure Mylar to link with nzbget. I was having some difficulties, so I changed the host setting for nzbget in Mylar. As soon as I changed the settings, I got a notification that Mylar was restarting. However, after that screen, Mylar wouldn't open again. Now whenever I try and open Mylar, I get a message 'Safari cannot connect to the Server' and 'Safari can't open the page "localhost:8090/home" because Safari can't connect to the server "localhost"'.  If someone could help me to fix this, I'd really appreciate it. I'm pretty new to this kind of thing (as you can probably tell)! Thank you!

**Comment by evilhero** [comment]
It sounds like you edited the actual Mylar ip to be localhost - in which case, you can only connect to Mylar from the machine that Mylar is running on.  So alot depends on how you're trying to run Mylar, are you running it on a separate machine than what you're trying to access it from? 

When you change the settings, unless you click on restart/shutdown it doesn't do either. Saving the settings just saves the settings, so I'm unsure as to what it is that you actually clicked on to restart the program aside from the actual option itself. 

I would restart your machine that Mylar is running on if possible, and then try to start it up again to see if it can start up. If it can't, or there's some other related problem - post your config.ini file in here (with any apikeys removed obviously) and I can assist more.

It might also help to know what branch / commit you're running of Mylar, how you installed it (via git, source, etc), and how you're running it (as a daemon/from command line/etc)

**Comment by voipblaster** [comment]
Thank you for the help! I'm out at the moment, but when I get home I'll try restarting the machine, and reply with the information you mentioned.

**Comment by voipblaster** [comment]
Ok, so I restarted but I am still getting the same error. 

I downloaded Mylar using this guide https://www.htpcguides.com/install-mylar-mac-osx-usenet-comics/

I am not running Mylar on a separate machine to the one I am trying to access it on. I'm running Mylar from my mac and trying to access it from here. 

I think I am running it from terminal, as I followed from the tutorial. But, as I said, I'm pretty new to this so I might be wrong!

Here is the config.ini pasted below without the apis:

[General]
config_version = 6
dbchoice = sqlite3
dbuser = ""
dbpass = ""
dbname = ""
dynamic_update = 4
comicvine_api = 
cvapi_rate = 2
http_port = 8090
http_host = 0.0.0.0
http_username = ""
http_password = ""
http_root = /
enable_https = 0
https_cert = ""
https_key = ""
https_chain = ""
https_force_on = 0
host_return = ""
api_enabled = 1
api_key = ""
launch_browser = 1
auto_update = 0
log_dir = /Applications/Mylar/logs
max_logsize = 1000000
git_path = ""
cache_dir = /Applications/Mylar/cache
annuals_on = 0
cv_only = 1
cv_onetimer = 1
check_github = 1
check_github_on_startup = 1
check_github_interval = 360
git_user = evilhero
git_branch = master
destination_dir = /Volumes/Backup/Comics
multiple_dest_dirs = ""
create_folders = 1
delete_remove_dir = 0
enforce_perms = 1
chmod_dir = 0777
chmod_file = 0660
chowner = ""
chgroup = ""
usenet_retention = None
alt_pull = 0
search_interval = 360
nzb_startup_search = 0
add_comics = 0
comic_dir = ""
blacklisted_publishers = None
imp_move = 0
imp_rename = 0
imp_metadata = 0
enable_check_folder = 0
download_scan_interval = 5
folder_scan_log_verbose = 0
check_folder = ""
interface = default
dupeconstraint = filesize
ddump = 0
duplicate_dump = ""
pull_refresh = ""
autowant_all = 0
autowant_upcoming = 1
preferred_quality = 0
comic_cover_local = 0
correct_metadata = 0
move_files = 0
rename_files = 0
folder_format = $Series ($Year)
file_format = $Series $Issue ($Year)
blackhole_dir = None
replace_spaces = 0
replace_char = .
zero_level = 0
zero_level_n = none
lowercase_filenames = 0
ignore_havetotal = 0
snatched_havetotal = 0
syno_fix = 0
allow_packs = 0
search_delay = 1
grabbag_dir = GrabBag
highcount = 0
read2filename = 0
send2read = 0
maintainseriesfolder = 0
tab_enable = 0
tab_host = ""
tab_user = ""
tab_pass = ""
tab_directory = ""
storyarcdir = 0
copy2arcdir = 0
arc_folderformat = $arc ($spanyears)
arc_fileops = copy
use_minsize = 0
minsize = ""
use_maxsize = 0
maxsize = ""
add_to_csv = 1
cvinfo = 0
log_level = 0
enable_extra_scripts = 0
extra_scripts = ""
enable_pre_scripts = 0
pre_scripts = ""
post_processing = 1
post_processing_script = ""
file_opts = move
weekfolder = 0
weekfolder_loc = ""
weekfolder_format = 0
locmove = 0
newcom_dir = ""
fftonewcom_dir = 0
enable_meta = 0
cbr2cbz_only = 0
ct_tag_cr = 1
ct_tag_cbl = 1
ct_cbz_overwrite = 0
unrar_cmd = None
cmtag_start_year_as_volume = 0
update_ended = 0
indie_pub = 75
biggie_pub = 55
upcoming_snatched = 1
enable_rss = 1
rss_checkinterval = 20
rss_lastrun = 2017-01-13 03:45:26
failed_download_handling = 0
failed_auto = 0
provider_order = 0, dognzb, 1, Geek, 2, http://
nzb_downloader = 0
torrent_downloader = 0
[Torrents]
enable_torrents = 0
minseeds = 0
torrent_local = 0
local_watchdir = None
torrent_seedbox = 0
seedbox_host = None
seedbox_port = None
seedbox_user = None
seedbox_pass = None
seedbox_watchdir = None
enable_torrent_search = 0
enable_tpse = 0
tpse_proxy = ""
tpse_verify = True
enable_32p = 0
search_32p = 0
mode_32p = 0
passkey_32p = ""
rssfeed_32p = ""
username_32p = ""
password_32p = ""
verify_32p = 1
snatchedtorrent_notify = 0
rtorrent_host = None
rtorrent_authentication = basic
rtorrent_rpc_url = None
rtorrent_ssl = 0
rtorrent_verify = 0
rtorrent_ca_bundle = ""
rtorrent_username = None
rtorrent_password = None
rtorrent_startonload = 0
rtorrent_label = None
rtorrent_directory = None
[SABnzbd]
sab_host = None
sab_username = None
sab_password = None
sab_apikey = None
sab_category = None
sab_priority = None
sab_to_mylar = 0
sab_directory = None
[NZBGet]
nzbget_host = None
nzbget_port = None
nzbget_username = None
nzbget_password = None
nzbget_category = None
nzbget_priority = None
nzbget_directory = None
[NZBsu]
nzbsu = 0
nzbsu_uid = ""
nzbsu_apikey = ""
nzbsu_verify = 1
[DOGnzb]
dognzb = 1
dognzb_apikey =
dognzb_verify = True
[Experimental]
experimental = 0
altexperimental = 1
[Torznab]
enable_torznab = 0
torznab_name = ""
torznab_host = ""
torznab_apikey = ""
torznab_category = ""
torznab_verify = False
[Newznab]
newznab = 1
extra_newznabs = Geek, https://api.nzbgeek.info/, 0, "", 1, http://, http://, 0, "", "", 1
[uTorrent]
utorrent_host = None
utorrent_username = None
utorrent_password = None
utorrent_label = None
[Transmission]
transmission_host = None
transmission_username = None
transmission_password = None
transmission_directory = None
[Deluge]
deluge_host = None
deluge_username = None
deluge_password = None
deluge_label = None
[Prowl]
prowl_enabled = 0
prowl_keys = ""
prowl_onsnatch = 0
prowl_priority = 0
[NMA]
nma_enabled = 0
nma_apikey = ""
nma_priority = 0
nma_onsnatch = 0
[PUSHOVER]
pushover_enabled = 0
pushover_apikey = ""
pushover_userkey = ""
pushover_priority = 0
pushover_onsnatch = 0
[BOXCAR]
boxcar_enabled = 0
boxcar_onsnatch = 0
boxcar_token = ""
[PUSHBULLET]
pushbullet_enabled = 0
pushbullet_apikey = ""
pushbullet_deviceid = None
pushbullet_onsnatch = 0
[TELEGRAM]
telegram_enabled = 0
telegram_token = ""
telegram_userid = ""
telegram_onsnatch = 0

Again, I really appreciate your help!

**Comment by evilhero** [comment]
Ok so if you followed that guide then it looks like you have it running as a daemon (it runs constantly in the background). 

On some machines localhost doesn't resolve properly due to how the machine is configured... Try going to http://127.0.0.1:8090 in your browser - I don't know if you added the http when you pasted your problem initially but not putting the protocol in front can cause problems as well.

**Comment by voipblaster** [comment]
Unfortunately, that's still not loading. It comes up with the same safari page. Is it easy to delete everything and install again?

**Comment by evilhero** [comment]
No its easy - jut reverse the steps you took to install (delete the mylar directory) and then remove the plist file or the autostart you decided to use. Then reinstall as per the directions, but do not do the plist/autostart so you can make sure it works before you set it to run as a daemon. 

You probably have to restart the machine after you delete mylar.

**Comment by voipblaster** [comment]
Perfect, it's all working again now! Thank you so much for the help! I'm really grateful!
