### ISSUE TITLE
show filename in the history section

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1540]
<img width="756" alt="skizze" src="https://cloud.githubusercontent.com/assets/15702664/21954621/c68186c2-da56-11e6-8fe4-27eed7836409.png">

could you show the downloaded filename via tooltip or something like that?

**Comment by evilhero** [comment]
For snatched it's a bit more difficult as mylar doesn't really track the filenames until they're post-processed. Downloaded status ones are easy enough, the snatched might be possible but I'd have to look more into it.

**Comment by HypKin** [comment]
oh ok, it would help a lot for trouble shooting if you knew what torrent was laoded without having to go throug the logs. maybe you could show the torrent file name instead?
