### ISSUE TITLE
Mylar doesn't do pauses when ussing local host address of nzbhydra

### ISSUE THREAD

**Issue by Githubtordl** [evilhero/mylar#1541]
I've been using Mylar with Nzbhydra for a long time and I just switched to using the localhost address of my NzbHydra setup instead of my web address and I've noticed that Mylar doesn't do any pauses like it would do when you use any other indexer (like pauses to stop hammering the server, I've seen requests in the space of a few seconds hitting nzbhydra back to back). If I switch to the web url of Nzbhydra (www.example.com/nzbhydra) then only it starts to treat NzbHydra as a normal indexer.

In the logs I've noticed the following "**local domain bypass for NzbHydraLocal is active.**"   Is there an option hidden somewhere to turn that bypass off?

**Comment by evilhero** [comment]
Yeah mylar doesn't distinguish between nzbhydra and newznabs - so it would assume anything on a local address wouldn't have to adhere to a rate limit. 

I recently added in the opposite (domain with local bypass), so adding in the opposite (local ip without local bypass) shouldn't be too difficult. I'll try and get this out tonight / tomorrow depending on available free time.

**Comment by Githubtordl** [comment]
Thanks

**Comment by evilhero** [comment]
Good to go in latest development commit. You just need to update the name of the newznab entry within Mylar to let it know it's an nzbhydra instance that you want to enforce the limit for. You do this by just appending on the words **[nzbhydra]** to the end of the Newznab Name field for the entry that is for your nzbhydra like so : 
![newznab1](https://cloud.githubusercontent.com/assets/909424/21988589/d25dd31c-dbd5-11e6-95c6-50f9d7517657.png)

**Comment by Githubtordl** [comment]
@evilhero that didn't work :(

Updated to the latest commit on dev,
Done the changes as you requested to the nzbhydra newznab entry, had a look at the logs, no pauses, also see the screenshot from NzbHydra. 

Test done by adding a new comic with 16 issues, all 16 issues were searched in about 3 mins.

Start of log from Mylar when status of issues set to 'wanted', still no pauses before doing the search.

![image](https://cloud.githubusercontent.com/assets/22656503/21993742/55980f48-dc14-11e6-80d8-6d60c28d3e4a.png)


![image](https://cloud.githubusercontent.com/assets/22656503/21993865/d79a9682-dc14-11e6-826d-8097ff7955e3.png)

**Comment by evilhero** [comment]
Sorry, I just saw that it wouldn't work - give me a few moments to fix it

**Comment by Githubtordl** [comment]
Sure

**Comment by Githubtordl** [comment]
It works! thanks for sorting this out so quickly.
