### ISSUE TITLE
QQ: how do i turn on debug logging?

### ISSUE THREAD

**Issue by mgaulton** [evilhero/mylar#1544]
I'm having an issue where the weekly list isn't populating. I've tried both master and development with the same results. My config hasn't changed but was moved to a new machine.

19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : trying to repopulate to week: 03-2017
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : ALT_PULL: 0 PULLBYFILE: True week: 03 year: 2017
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : Weekly pull list present - checking if it's up-to-date..
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : [PULL-LIST] Populating & Loading pull-list data from file
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : No new pull-list available - will re-check again in 24 hours.
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : Checking the Weekly Releases list for comics I'm watching...
19-Jan-2017 15:08:18 - ERROR   :: CP Server Thread-5 :  this has an alpha-numeric in the issue # which I cannot account for.
19-Jan-2017 15:08:18 - ERROR   :: CP Server Thread-5 :  this has an alpha-numeric in the issue # which I cannot account for.
19-Jan-2017 15:08:18 - INFO    :: CP Server Thread-5 : Finished checking for comics on my watchlist.
19-Jan-2017 15:08:20 - INFO    :: CP Server Thread-5 : I have copied 0 issues from week #03 pullist as requested.
19-Jan-2017 15:08:20 - INFO    :: CP Server Thread-5 : trying to repopulate to week: 3-2017
19-Jan-2017 15:08:20 - INFO    :: CP Server Thread-5 : ALT_PULL: 0 PULLBYFILE: True week: 3 year: 2017
19-Jan-2017 15:08:20 - INFO    :: CP Server Thread-5 : Weekly pull list present - checking if it's up-to-date..
19-Jan-2017 15:08:20 - INFO    :: CP Server Thread-5 : [PULL-LIST] Populating & Loading pull-list data from file
19-Jan-2017 15:08:21 - INFO    :: CP Server Thread-5 : No new pull-list available - will re-check again in 24 hours.
19-Jan-2017 15:08:21 - INFO    :: CP Server Thread-5 : Checking the Weekly Releases list for comics I'm watching...
19-Jan-2017 15:08:21 - ERROR   :: CP Server Thread-5 :  this has an alpha-numeric in the issue # which I cannot account for.
19-Jan-2017 15:08:21 - ERROR   :: CP Server Thread-5 :  this has an alpha-numeric in the issue # which I cannot account for.
19-Jan-2017 15:08:21 - INFO    :: CP Server Thread-5 : Finished checking for comics on my watchlist.

**Comment by evilhero** [comment]
To turn on debug you need to either start mylar with the -v switch, or if you have it already started you can enable immediate verbose logging by going into the logs option in the GUI and select the 'Enable Verbose ON' button in the upper right corner (can never remember what the button is called). 

The pull problems should be all resolved as of earlier today, just make sure you're running the most recent dev commit. Otherwise, switching your alt_pull to 2 in the config.ini (with mylar not running) will fix+improve things.

**Comment by mgaulton** [comment]
Found the button "toggle debug" and enabled, didn't really give me anything additionally useful. 

turning on alt_pull resulted in a 500 Error and the below logs
19-Jan-2017 16:27:50 - INFO :: CP Server Thread-3 : [PULL-LIST] Populating & Loading pull-list data directly from webpage
/opt/mylar/mylar-master/lib/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/opt/mylar/mylar-master/lib/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by mgaulton** [comment]
oh wait, i did alt_pull 1, lemme redo

**Comment by mgaulton** [comment]
yep alt_pull 2 worked. you're awesome.

**Comment by mgaulton** [comment]
thanks again!
