### ISSUE TITLE
Mylar Failing to send to SABnzbd from NZBHydra

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1547]
All of a sudden, when Mylar snatches a release from NZBHydra and sends it to SABnzbd, it no longer works.  Not sure what happened, but in SABnzbd I see

`WAIT 39 sec / Trying to fetch NZB from http://10.14.10.6:9093/api?apikey=<apikeyremovedbyme>&cmd=downloadNZB&nzbname=Star.Wars.013.2016.digital.Oroboros-DCP.nzb 0% 0 MB / 0 MB 0:00`

**Comment by evilhero** [comment]
Does mylar answer on 10.14.10.6:9093 ?

You'd have to verify what you have set for mylar host/port within the mylar Gui, as well as what the host_return value is within the config.ini. 

Normally if you have the host set to 0.0.0.0.0 and the host_return blank it's enough to work under normal conditions. If you set the host to local or exact ip, then you night have to set the host_return to the same. 

It just depends on your configuration...

**Comment by DrSeussFreak** [comment]
Changed the settings, and now I get

`2017-01-23 21:08:30	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.`

**Comment by evilhero** [comment]
Whenever you change settings in the configuration, you have to restart mylar for the settings to take effect. It's a long outstanding glitch that I haven't been able to squash as of yet, but hopefully soon (requires a rework of the config).

**Comment by DrSeussFreak** [comment]
Now nothing is going to SABnzbd

`2017-01-23 21:27:23	INFO	Successfully sent nzb file to SABnzbd
2017-01-23 21:27:23	INFO	filen: Star.Wars.021..2016...Digital...BlackManta-Empire..nzb -- nzbname: Star.Wars.021.2016.Digital.BlackManta-Empire are not identical. Storing extra value as : Star.Wars.021..2016...Digital...BlackManta-Empire.
2017-01-23 21:27:21	INFO	Download URL: http://10.0.1.50:9088/getnzb?apikey=<apikeyremoved>&searchresultid=7cfa03b0100a0f08b71a6f8e5d25fd8e8ec1d268 [VerifySSL:False]`

**Comment by evilhero** [comment]
What did you change the values from/to? Try to post debug logs too if you can, it makes it easier to see if something is amiss ;)

**Comment by DrSeussFreak** [comment]
I changed only the host_return value to match the mylar host/port info

Logs attached

[mylar.log.zip](https://github.com/evilhero/mylar/files/725583/mylar.log.zip)

**Comment by evilhero** [comment]
You need to include the protocol and port in the host_return (ie. host_return = http://10.0.1.50:9093).

Unless sab & mylar are on separate machines, ideally set the host ip within the configuration to 0.0.0.0, and blank out the host_return.

**Comment by DrSeussFreak** [comment]
For some reason, in the past, I found that setting it to 0.0.0.0 failed, so I have it set to 10.0.1.50, but setting the host return to the full path with port worked, I just saw my first file in SABnzbd!  Thanks as always!
