### ISSUE TITLE
Show "All" not being saved

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1550]
If I have all series shown at the top via "Show All" and I go into a series, and then go back to the main series list via the Mylar icon in the top left corner, the "All" reverts back to the default of "25".

On a side note, I would love to have an option to make "All" the default whenever and wherever the option lies.

**Comment by evilhero** [comment]
It should be holding the setting within your browser - at least it used to retain it as such (the filter works the same way on the main page, type in a filter, go to filtered series, return to main and it's still filtered). What browser are you browsing on? 

The all default has been requested previously but it being data tables the entire data table module has to be updated to the latest, and the last time I tried the existing tables became an utter mess that I couldn't fix.

**Comment by DrSeussFreak** [comment]
it is not, and on multiple OS's, all using Chrome (Windows 10 and OSX Sierra)

**Comment by evilhero** [comment]
Windows 10 &  chrome works for me for retaining the all setting across multiple pages, as well as on an android &  chrome. 

I do believe there's a setting within chrome the you might need to enable to retain cached states (or something along those lines)

**Comment by DrSeussFreak** [comment]
Then this must be a new setting that changed itself, as this issue just started to occur, and across different Chrome settings (different google acounts per browser).

Just tried it in FireFox, and it works without issue, very confused.

**Comment by DrSeussFreak** [comment]
Have not figured it out, but clearly not an issue with Mylar
