### ISSUE TITLE
issue with .mu issues

### ISSUE THREAD

**Issue by rgecko** [evilhero/mylar#1553]
seems to be an issue refreshing series that have the .mu for the monsters unleashed issues.

**Comment by evilhero** [comment]
It's working on the dev branch, but hasn't been fully tested thus it hasn't been pushed to master just yet. 

The 2 .mu issues from this week have refreshed fine for myself, but haven't heard of any other problems.

**Comment by AustinYQM** [comment]
I am getting 

> Traceback (most recent call last):
>   File "C:\Mylar-Master\cherrypy\_cprequest.py", line 645, in respond
>     response.body = self.handler()
>   File "C:\Mylar-Master\cherrypy\lib\encoding.py", line 188, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "C:\Mylar-Master\cherrypy\_cpdispatch.py", line 29, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "C:\Mylar-Master\mylar\webserve.py", line 1622, in pullist
>     repoll = self.manualpull(weeknumber=weeknumber,year=year)
>   File "C:\Mylar-Master\mylar\webserve.py", line 1860, in manualpull
>     weeklypull.pullit()
>   File "C:\Mylar-Master\mylar\weeklypull.py", line 200, in pullit
>     return pullitcheck()
>   File "C:\Mylar-Master\mylar\weeklypull.py", line 794, in pullitcheck
>     statusupdate = updater.upcoming_update(ComicID=ComicID, ComicName=ComicName, IssueNumber=ComicIssue, IssueDate=ComicDate, forcecheck=forcecheck)
>   File "C:\Mylar-Master\mylar\updater.py", line 396, in upcoming_update
>     cchk = mylar.importer.updateissuedata(ComicID, ComicName, calledfrom='weeklycheck')#mylar.importer.addComictoDB(ComicID,mismatch,pullupd)
>   File "C:\Mylar-Master\mylar\importer.py", line 1289, in updateissuedata
>     decisval = int(decis)
> ValueError: invalid literal for int() with base 10: 'MU'

on ../pullist

I am on the master branch. I dont have anything set up on the dev branch. Is there an easy way to copy all your setting for one branch to another?

**Comment by evilhero** [comment]
If you did a git clone to install mylar, then it's pretty simple : 
git checkout development
Then change the config.ini value of git_branch to development. Start it up, it'll probably ask to update and that's it. 

Note that the above steps have to be performed with mylar not running.

**Comment by rgecko** [comment]
Confirmed all good on dev
