### ISSUE TITLE
"Test PROWL" not actually sending test notification

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1556]
Hi all - 

I'm just getting started with Mylar, so apologies if I'm asking something that is basic.

I'm trying to get Prowl notifications working. When I add my API key and click "Test PROWL", I don't get anything...

I know the key is good as I copied and pasted it into FlexGet to see if it worked... I did hit save and even restarted Mylar to see if that helped. I don't see anything pertinent in the log either.

Any ideas?

**Comment by evilhero** [comment]
To be honest, I've never used PROWL as I don't have an iOS device - but if you could put Mylar into debug mode (-v on startup, or go to the logs tab in the GUI and select 'Toggle Debug Log') and then try to do the Test Prowl option again to see what happens via the logs.

Note that there is a possibility that the actual notification for snatch/download may still work (prowl notification), but the test option is broken.

**Comment by barbequesauce** [comment]
Thanks. I did just that, I put it into debug mode and added a comic I didn't have already (and marked it wanted) - and nothing at all came up...

--
saucebarbeque@hotmail.com

On January 29, 2017 at 19:49:13, evilhero (notifications@github.com<mailto:notifications@github.com>) wrote:

To be honest, I've never used PROWL as I don't have an iOS device - but if you could put Mylar into debug mode (-v on startup, or go to the logs tab in the GUI and select 'Toggle Debug Log') and then try to do the Test Prowl option again to see what happens via the logs.

Note that there is a possibility that the actual notification for snatch/download may still work (prowl notification), but the test option is broken.

**Comment by barbequesauce** [comment]
So - to be clear - with debug logging on (from the command line), I press "Test PROWL" and nothing gets sent or logged. In the GUI, the little green popup pops up in the bottom right of the browser but it stays empty with no text in there...

For what it's worth, LittleSnitch doesn't even see an attempt to connect to api.prowlapp.com.

**Comment by evilhero** [comment]
Yeah sorry I haven't had a chance to delve into it as of yet - I should have time later tonight to try and see what might be going on. I'll fire back an update when I know something more so you're in the loop

**Comment by barbequesauce** [comment]
Thanks - I wasn't pushing, I just wanted to be a little clearer ;)

**Comment by barbequesauce** [comment]
Eh, ignore this. I was having other issues talking to Transmission and with NZBVortex, I finally gave up and nuked the installation. After re-cloning it works nicely...
