### ISSUE TITLE
pyOpenSSL is missing - Windows

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1557]
I tried to enable SSL on my Windows installation of Mylar.
I'm running Python 2.7.x.
I get:
"29-Jan-2017 21:51:38 - WARNING :: MAIN : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled."

Am I missing something silly?
I went and installed the pyOpenSSL package again, just in case.
Same error.

Thanks.

**Comment by evilhero** [comment]
Make sure that the pyopenssl version you're running is the same bit-version as your python (ie. 64-bit python will only work with 64-bit pyopenssl, and same with 32-bit python). You also need openssl installed as pyopenssl is just a wrapper for openssl. 

How are you installing it? The .exe or using 'pip install pyopenssl'?

**Comment by bguidotti** [comment]
This was my mistake - 32 bit version was installed.
User error - closing.

Thanks!
