### ISSUE TITLE
Mylar not installing

### ISSUE THREAD

**Issue by jaaacck** [evilhero/mylar#1558]
I've just found out about Mylar and trying to get it installed. I am currently running python version 2.7.9 as stated on the wiki. My OS is Centos 6.6 ( a bit outdated, I know. But I'd like to keep this version for now)
I've cloned the dev version and when I run 'python Mylar.py' I get the following error:

> `Traceback (most recent call last):
>   File "Mylar.py", line 26, in <module>
>     import mylar
>   File "/apps/mylar/mylar/__init__.py", line 41, in <module>
>     from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
>   File "/apps/mylar/mylar/rsscheckit.py", line 21, in <module>
>     from mylar import logger, rsscheck, helpers, auth32p
>   File "/apps/mylar/mylar/rsscheck.py", line 7, in <module>
>     import cfscrape
>   File "lib/cfscrape/__init__.py", line 6, in <module>
>     import js2py
>   File "lib/js2py/__init__.py", line 67, in <module>
>     from .evaljs import *
>   File "lib/js2py/evaljs.py", line 4, in <module>
>     from .translators import translate_js, DEFAULT_HEADER
>   File "lib/js2py/translators/__init__.py", line 25, in <module>
>     from .pyjsparser import PyJsParser, Node, WrappingNode, node_to_dict
>   File "lib/js2py/translators/pyjsparser.py", line 25
>     REGEXP_SPECIAL_SINGLE = {'\\', '^', '$', '*', '+', '?', '.', '[', ']', '(', ')', '{', '{', '|', '-'}
>                                  ^
> SyntaxError: invalid syntax`

I've also tried running as root just to make sure. 
I have also tried on the master release and still get this same issue. 

Any ideas?

**Comment by evilhero** [comment]
Is the python you're calling the 2.7.9 version or is an earlier/newer version that you have on your system? If you type in just 'python' in the command line, what version is it firing back with?

**Comment by jaaacck** [comment]
Definitely 2.7.9

> `Python 2.7.9 (default, Jan 30 2017, 21:41:12)
>[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
>Type "help", "copyright", "credits" or "license" for more information.
> >>>`

**Comment by evilhero** [comment]
Just realized, there's no ^ at the end of that regex line - you may have gotten a possibile corrupt git or something else is messed up. 

I don't think it's it, but if you're on dev you might have to ensure that the config.ini value for git_branch is set to development and not master. 

 Otherwise, can you try a fresh git clone again to see if it helps?

**Comment by jaaacck** [comment]
Tried changing the git_branch value to development with no luck.

I've also just done a brand new pull of the dev and master and got the same error again.

**Comment by evilhero** [comment]
When you start mylar with the -v switch does it spit back anything or right to the error? Is it the same error as you originally posted or different? 

I've honestly never seen that error before. It looks like it's a js2py problem for some reason, which is a module mylar uses to bypass cloudflare sites - but maybe it's some kind of dependency related problem that might be due to the os (not the 6.6, the Centos)

**Comment by jaaacck** [comment]
This is what I get when I run it with -v. I've also tried running it as a normal user (not sudo) and I get a similar output.

https://hastebin.com/eritixosuc.py

**Comment by evilhero** [comment]
I have never ever seen that kind of output Ik my life when running the script. Then I saw this:
```
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more
```

Looks like you're running mylar against python 2.6.6 which is far too old to use.

**Comment by jaaacck** [comment]
Hmmm.... When running "python -V" I get "Python 2.7.9". Something amiss with my system here. 
Upgrading to Centos 7 this weekend. Hopefully will sort it and a few other problems I'm having. 

I appreciate the speedy help!

**Comment by evilhero** [comment]
Could try doing a 'whereis python' and it should fire back the paths that have python. Then if you can find the location to the right python you could call it directly from the cli instead of just calling 'python'

**Comment by jaaacck** [comment]
I've tried running Mylar in a virtualenvwrapper, directing it to /usr/local/bin/python2.7 - which did not work. 

Easiest option for me here is to upgrade to Centos 7. Kill a few of my other little niggles in the process.
