### ISSUE TITLE
You are bad and you should feel bad

### ISSUE THREAD

**Issue by BRTPOB** [evilhero/mylar#1566]
For using an old jquery datatable that didn't let me actually use the input fields like a normal human being. Whenever you try to search for something, and then delete a character it resets back to the end which makes it super frustrating to try and fix problems. Easiest way of seeing this is by looking at the filter on the main page, typing something in and using an arrow key on the keyboard to try to get to the middle of the word.

**Comment by evilhero** [comment]
I'm part evil, see the nick, 'evilhero'? I'm allowed to have a 50% bad attitude. 

Of course I also have a good side (50% of the time), and so does scotton it appears as he already has a fix up to appease those that mistype - I don't throw stones, as I frequently misspell myself. 

I will merge it later tonight, so in the meantime you need to ensure, and this is very, very important - you need to ensure that you type things correctly first. Don't be in a rush, stop and smell the roses, then type another letter. Go make sweet pre-valentine's day love to your respective other, come back and type in another letter. In the process of responding to this, stop and type yet another letter... I'm sure you get the gist ;) </scarcasm>

**Comment by s-cotton** [comment]
To be fair to Noodles, it is something I had noticed as well, mostly when I try to use Ctrl+Shift+Left to select the previous word.  Glad to see it fixed regardless of the source of white noise
