### ISSUE TITLE
Post-Processing hanging up

### ISSUE THREAD

**Issue by shpanky73** [evilhero/mylar#1569]
First of, love the app, thank you so much evilhero.  I'm running into an issue with using nzbget along with comicrn.py whereby it hangs up.  When trying to post-process, I get an error on mylar in the following:

2017-02-13 10:29:37	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 1175, in Process
dupthis = helpers.duplicate_filecheck(self.nzb_folder, ComicID=comicid, IssueID=issueid)
File "C:\Mylar\mylar\helpers.py", line 1815, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "C:\Python27\lib\genericpath.py", line 57, in getsize
return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: 'G:\\comic books\\Black.Science.005.2014.digital.Son.of.Ultron-Empire'
2017-02-13 10:29:37	INFO	[DUPECHECK] Duplicate check for G:\comic books\Black.Science.005.2014.digital.Son.of.Ultron-Empire

It appears the comic isn't being found in the correct folder (I usually have them moved to a publisher/comic name format).  Any thoughts on how to correct this?  Thank you!

**Comment by evilhero** [comment]
I think what's happening is that nzbget is putting the cbr/cbz file into a folder of the same name (ie. a collection I believe is the term that it uses) - and that's being passed to Mylar as the filename. Because there's no extension, and the file doesn't exist at that location (because it's a path, not the filename itself being passed) - it's causing an error.

I don't run nzbget, so I'll have to delve into things abit more so I can understand what's happening better, and I'll give an update when I do.

**Comment by shpanky73** [comment]
Thank you so much!

**Comment by evilhero** [comment]
One quick question - are you trying to post-process downloads that were snatched by Mylar, or are you just attaching the ComicRN script to comic downloads outside of Mylar for them to post-process ?

**Comment by shpanky73** [comment]
Post-processing comics snatched by mylar.

**Comment by shpanky73** [comment]
@evilhero anything come up in your research?

**Comment by evilhero** [comment]
I haven't had a chance to check into this as of yet as I don't run nzbget normally, let alone use a windows machine - so I need to install and set it up and the try to do the testing.

Can you do me a favor and post the debug log from mylar of a post-processing run using nzbget ? It might help me get my head around things abit better if I can see the leadup to the error before I start doing things on my end.
