### ISSUE TITLE
Sabnzbd stuck on processing

### ISSUE THREAD

**Issue by Tomservov2** [evilhero/mylar#1570]
Sabnzbd stuck on this
![image](https://cloud.githubusercontent.com/assets/25776847/22943015/77f27dea-f2b1-11e6-988e-2c2f3a2d4ef8.png)

got this error in debug log
Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\PostProcessor.py", line 927, in Process
comicid = nzbiss['ComicID']
IndexError: No item with that key

It was working before I updated master build.
tried switching to dev build, no change, restarted both applications, git pull says up to date

love the app, hope you can help me get it working again
Thanks

**Comment by evilhero** [comment]
I was going to say that error is from the dev build, as the master doesn't have that key anywhere.

The file you're trying to download - was it snatched using Mylar or were you just trying to run the ComicRN script against a download outside of Mylar? What was it that you tried to snatch and was it from the series page / story arc / one-off from the pull-list ? 

It's basically saying that it can't find the series in your watchlist, so it can't go any further - but the issue exists (somehow)

**Comment by Tomservov2** [comment]
snatched using mylar then sabnzbd tries to process it and hangs

heres some more of the log if that helps

[POST-PROCESSING] Issueid: 456079
2017-02-14 12:26:35	DEBUG	[POST-PROCESSING] After conversions, nzbname is : Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:26:35	DEBUG	[NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Lumberjanes 003 2014 digital Son of Ultron-Empire
2017-02-14 12:26:35	DEBUG	[NZBNAME] nzbname (remove chars): Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:26:34	DEBUG	[NZBNAME]: Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:26:34	DEBUG	[POST-PROCESSING] nzb folder: F:\Download\Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:26:34	DEBUG	[POST-PROCESSING] nzb name: Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:24:55	DEBUG	[POST-PROCESSING] Manual Run initiated
2017-02-14 12:24:55	DEBUG	[POST-PROCESSING] Not using SABnzbd : Manual Run
2017-02-14 12:24:55	DEBUG	[POST-PROCESSING] nzb folder: F:\Download\Mylar\Manual
2017-02-14 12:24:55	DEBUG	[POST-PROCESSING] nzb name: Manual Run
2017-02-14 12:24:50	DEBUG	If you read this message, debug logging is available
2017-02-14 12:26:35	ERROR	Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\PostProcessor.py", line 927, in Process
comicid = nzbiss['ComicID']
IndexError: No item with that key
2017-02-14 12:26:34	INFO	Starting postprocessing for : Lumberjanes.003.2014.digital.Son.of.Ultron-Empire
2017-02-14 12:26:34	INFO	ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
2017-02-14 12:24:55	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads

**Comment by Tomservov2** [comment]
I guess I should ask, is it better to be on master build or dev, in trying to resolve issue, I saw a lot of recommendation to move to dev.  And if I move to one or the other is there a way to reinstall it and keep settings?

**Comment by evilhero** [comment]
Your timestamps are all over the board in that log post - can you try again and post the debug log with the time stamps in order of sequence as they appear in the logfile/logscreen ? 

Does that particular series exist on your watchlist and is it up-to-date ? (Meaning when you go look at the series, all the issues appear).

At this point it doesn't really matter which build, as master is pretty much level with dev (save for the one push to dev yesterday) - normally, if people are having problems I usually recommend the dev branch just because it gets the fixes the quickest and is sometimes more stable than master (just due to how things break outside of the control of the app).

You have to make sure that your git_branch field in the config.ini is set to the proper branch (you have to shutdown Mylar prior to editing the file or else it won't save the changes properly), so git_branch = development or git_branch = master.

**Comment by Tomservov2** [comment]
![image](https://cloud.githubusercontent.com/assets/25776847/22948701/19f4923c-f2c5-11e6-9fab-8f029f9ae57b.png)
that's the way the log is coming up
series seems up to date and in watchlist
![image](https://cloud.githubusercontent.com/assets/25776847/22948813/804aac24-f2c5-11e6-9b6e-e4f961b24acf.png)

**Comment by evilhero** [comment]
Is your folder monitor set to monitor the same directory to where your downloads go from sab? It looks like it already post-processed it to the point where it removed it from the nzb db (where it stores all the information related to snatches). It's probably best to have the folder monitor be in a different location than your downloads, just for this exact reason (the folder monitor grabbed the file before the sab post-processing which could very well be causing the problem). 

Try to wipe the nzblog of entries (history tab/wipe nzblog), and retry the snatch again but also with the folder monitor checking a different location. 

Try wiping

**Comment by Tomservov2** [comment]
that appears to have been it, manual check was in sub folder of download folder, moved elsewhere, cleared nzblog and all is working again, thanks!

**Comment by PCurd** [comment]
If I may hijack slightly (let me know if my issue is different and I'll raise a new issue) as I have a very similar issue but without folder monitoring enabled. 

I have had similar issues to Tomservov2 when downloading NZBs and manually setting to the Comics category in Sab (i.e. not via Mylar) so I cleared the NZBlog this morning.

I also had two downloads fail to load properly in Sab (Sab went to Mylar for the NZB file and didn't get one) a few days ago. So this morning I deleted them from the Sab queue and manually searched for them again in Mylar (they were at Snatched).

They are found and Sab downloads them, but they get stuck at Running ComicRN.py in Sab as per the first post in this issue. My logs from Mylar:

```

15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Initiating manual search for Dungeons & Dragons issue: 1
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Issue Title given as : shadows of the vampire part one: dead of the night; tyranny of dragons
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : search provider order is ['newznab:NzbGeek', 'newznab:DogNZBa', 'newznab:NZBCat']
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using NzbGeek(newznab) [RSS]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Could not find Issue 1 of Dungeons & Dragons (2016) using NzbGeek [rss]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using DogNZBa(newznab) [RSS]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Could not find Issue 1 of Dungeons & Dragons (2016) using DogNZBa [rss]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using NZBCat(newznab) [RSS]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Could not find Issue 1 of Dungeons & Dragons (2016) using NZBCat [rss]
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using NzbGeek (newznab)
15-Feb-2017 08:54:34 - INFO    :: Thread-14 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Initiating manual search for Dungeons & Dragons issue: 2
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Issue Title given as : shadows of the vampire part two: raven lost
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : search provider order is ['newznab:NzbGeek', 'newznab:DogNZBa', 'newznab:NZBCat']
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : allow_packs set to :None
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 2 (2016) using NzbGeek(newznab) [RSS]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Could not find Issue 2 of Dungeons & Dragons (2016) using NzbGeek [rss]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : allow_packs set to :None
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 2 (2016) using DogNZBa(newznab) [RSS]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Could not find Issue 2 of Dungeons & Dragons (2016) using DogNZBa [rss]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : allow_packs set to :None
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 2 (2016) using NZBCat(newznab) [RSS]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Could not find Issue 2 of Dungeons & Dragons (2016) using NZBCat [rss]
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : allow_packs set to :None
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 2 (2016) using NzbGeek (newznab)
15-Feb-2017 08:54:35 - INFO    :: Thread-15 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:55:36 - INFO    :: Thread-14 : no errors on data retrieval...proceeding
15-Feb-2017 08:55:36 - INFO    :: Thread-14 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : no errors on data retrieval...proceeding
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : newznab
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : rss:no
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : allow_packs:None
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : Found Dungeons & Dragons (2016) issue: 2 using NzbGeek (newznab)
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : prov  : NzbGeek (newznab)[3e1618dd5b5acc34255e65fa4873e8dd]
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
15-Feb-2017 08:55:37 - INFO    :: Thread-15 : Download URL: https://api.nzbgeek.info/api?apikey=xxx&t=get&id=3e1618dd5b5acc34255e65fa4873e8dd [VerifySSL:True]
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : filen: Dungeons.andamp;amp;.Dragons.002..2016...digital...Minutemen-Midas..nzb -- nzbname: Dungeons.and.Dragons.002.2016.digital.Minutemen-Midas are not identical. Storing extra value as : Dungeons.andamp;amp;.Dragons.002..2016...digital...Minutemen-Midas.
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : Successfully sent nzb file to SABnzbd
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : setting the nzbid for this download grabbed by NzbGeek (newznab) in the nzblog to : 3e1618dd5b5acc34255e65fa4873e8dd
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : setting the alternate nzbname for this download grabbed by NzbGeek (newznab) in the nzblog to : Dungeons.andamp;amp;.Dragons.002..2016...digital...Minutemen-Midas.
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : passing to updater.
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : [UPDATER] Updating status to snatched
15-Feb-2017 08:55:39 - INFO    :: Thread-15 : [UPDATER] Updated the status (Snatched) complete for Dungeons & Dragons Issue: 2
15-Feb-2017 08:55:47 - INFO    :: CP Server Thread-11 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
15-Feb-2017 08:55:47 - INFO    :: CP Server Thread-11 : Starting postprocessing for : Dungeons.and.Dragons.002.2016.digital.Minutemen-Midas
15-Feb-2017 08:55:47 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\PostProcessor.py", line 927, in Process
    comicid = nzbiss['ComicID']
IndexError: No item with that key

15-Feb-2017 08:56:38 - INFO    :: Thread-14 : no errors on data retrieval...proceeding
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:56:38 - INFO    :: Thread-14 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : no errors on data retrieval...proceeding
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : Could not find Issue 1 of Dungeons & Dragons (2016) using NzbGeek [api]
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using DogNZBa (newznab)
15-Feb-2017 08:57:40 - INFO    :: Thread-14 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : no errors on data retrieval...proceeding
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : Found Dungeons & Dragons (2016) issue: 1 using DogNZBa (newznab)
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : prov  : DogNZBa (newznab)[63116a0de9f19c9fc3e61f628ff67860]
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
15-Feb-2017 08:58:41 - INFO    :: Thread-14 : Download URL: https://api.dognzb.cr/api?apikey=xxx&t=get&id=xxx [VerifySSL:True]
15-Feb-2017 08:58:42 - ERROR   :: Thread-14 : Unable to download nzb from link: https://api.dognzb.cr/api?apikey=xxx&t=get&id=xxx [https://dognzb.cr/fetch/f85589a0df03b994bdddb4e41a51a957/xxx]
15-Feb-2017 08:58:42 - INFO    :: Thread-14 : Could not find Issue 1 of Dungeons & Dragons (2016) using DogNZBa [api]
15-Feb-2017 08:58:42 - INFO    :: Thread-14 : allow_packs set to :None
15-Feb-2017 08:58:42 - INFO    :: Thread-14 : Shhh be very quiet...I'm looking for Dungeons & Dragons issue: 1 (2016) using NZBCat (newznab)
15-Feb-2017 08:58:43 - INFO    :: Thread-14 : pausing for 60 seconds before continuing to avoid hammering
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : no errors on data retrieval...proceeding
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : newznab
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : rss:no
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : allow_packs:None
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : Found Dungeons & Dragons (2016) issue: 1 using NZBCat (newznab)
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : prov  : NZBCat (newznab)[2b607ac89187fa9db6c94c7dc77fa6b5cc08553f]
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
15-Feb-2017 08:59:45 - INFO    :: Thread-14 : Download URL: https://nzb.cat/api?apikey=xxxx&t=get&id=2b607ac89187fa9db6c94c7dc77fa6b5cc08553f [VerifySSL:True]
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : filen: Dungeons_and_Dragons_001_.2016._.Digital._.LostNerevarine-Empire -- nzbname: Dungeons.and.Dragons.001.2016.Digital.LostNerevarine-Empire are not identical. Storing extra value as : Dungeons.and.Dragons.001..2016...Digital...LostNerevarine-Empire
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : Successfully sent nzb file to SABnzbd
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : setting the nzbid for this download grabbed by NZBCat (newznab) in the nzblog to : 2b607ac89187fa9db6c94c7dc77fa6b5cc08553f
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : setting the alternate nzbname for this download grabbed by NZBCat (newznab) in the nzblog to : Dungeons.and.Dragons.001..2016...Digital...LostNerevarine-Empire
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : passing to updater.
15-Feb-2017 08:59:46 - INFO    :: Thread-14 : [UPDATER] Updating status to snatched
15-Feb-2017 08:59:47 - INFO    :: Thread-14 : [UPDATER] Updated the status (Snatched) complete for Dungeons & Dragons Issue: 1

```

As a second note, it looks like the Dog search used my API key for both the apikey AND the search ID... which is odd - separate issue though!

**Comment by evilhero** [comment]
Pretty sure this is due to the nzbname not being what it expects. Probably dhe to the &  in the title along with some other characters. I'll have to delve into this one a bit more as the last time it was due to the actual provider being used, but it appears it's happening to all of the providers you're using but with incorrectly assigned nzbnames.

**Comment by evilhero** [comment]
Fix up momentarily for the error...

**Comment by PCurd** [comment]
That seems to have fixed for me, thanks! I'll let you know if I see again :)

**Comment by danfozzy** [comment]
can you push this fix to the master please!

**Comment by evilhero** [comment]
No eta - sometime this weekend when I have a chance to do it.

**Comment by psychoflame** [comment]
I'm also now seeing this error since Updating to the latest Development Commits, not sure why it's decided to break though. Seeing these lines in the logs. This error causes the comicRN script to get caught in an infinite loop and hold up all the other items that need to be processed. Logs are


```
2017-12-19 20:36:01 | ERROR | Uncaught exception: Traceback (most recent call last):  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 177, in new_run    old_run(*args, **kwargs)  File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run    self.__target(*self.__args, **self.__kwargs)  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/PostProcessor.py", line 1038, in Process    self.oneoff = nzbiss['OneOff']IndexError: No item with that key
-- | -- | --
2017-12-19 20:36:01 | INFO | Starting postprocessing for : Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD
2017-12-19 20:36:01 | INFO | ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
2017-12-19 20:35:35 | INFO | [UPDATER] Updated the status (Snatched) complete for Red Sonja Issue: 11
2017-12-19 20:35:35 | INFO | [UPDATER] Updating status to snatched
2017-12-19 20:35:35 | INFO | passing to updater.
2017-12-19 20:35:35 | INFO | setting  the alternate nzbname for this download grabbed by experimental in the  nzblog to : Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD.
2017-12-19 20:35:35 | INFO | setting the nzbid for this download grabbed by experimental in the nzblog to : 181048639
2017-12-19 20:36:01 | INFO | Starting postprocessing for : Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD
-- | -- | --
2017-12-19 20:36:01 | INFO | ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
2017-12-19 20:35:35 | INFO | [UPDATER] Updated the status (Snatched) complete for Red Sonja Issue: 11
2017-12-19 20:35:35 | INFO | [UPDATER] Updating status to snatched
2017-12-19 20:35:35 | INFO | passing to updater.
2017-12-19 20:35:35 | INFO | setting  the alternate nzbname for this download grabbed by experimental in the  nzblog to : Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD.
2017-12-19 20:35:35 | INFO | setting the nzbid for this download grabbed by experimental in the nzblog to : 181048639
2017-12-19 20:35:35 | INFO | Successfully sent nzb file to SABnzbd
2017-12-19 20:35:35 | INFO | {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_bI_065']}
2017-12-19 20:35:35 | INFO | sending now to http://10.10.10.51:8080/sabnzbd/api
2017-12-19 20:35:35 | INFO | parameters  set to {'nzbname':  u'Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD.nzb', 'apikey':  'da334ae076a7b134c483350da1ccc953', 'name':  u'http://10.10.10.51:8090/api?apikey=8bfe9c68288677b91a2b338dfe4e2896&cmd=downloadNZB&nzbname=Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD.nzb',  'cmd': 'downloadNZB', 'cat': 'comics', 'priority': '-100', 'mode':  'addurl', 'output': 'json'}
2017-12-19 20:35:35 | INFO | filen:  Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD..nzb -- nzbname:  Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD are not identical.  Storing extra value as :  Red.Sonja.V4.011.2017.5.covers.Digital.TLK-EMPIRE-HD.
2017-12-19 20:35:35 | INFO | download-retrieved  headers: {'content-disposition': 'attachment; filename="Red Sonja V4  011(2017)(5 covers)(Digital)(TLK-EMPIRE-HD).cbr.nzb"',  'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'expires':  'Thu, 21 Dec 2017 04:35:46 GMT', 'server': 'nginx', 'connection':  'close', 'pragma': 'cache', 'cache-control': 'max-age=86400', 'date':  'Wed, 20 Dec 2017 04:35:46 GMT', 'content-type': 'application/x-nzb'}
2017-12-19 20:35:34 | INFO | Download  URL:  http://nzbindex.nl/download/181048639/0-Day-2017.12.6-Red-Sonja-V4-01120175-coversDigitalTLK-EMPIRE-HD.cbr.nzb  [VerifySSL:False]
2017-12-19 20:35:34 | INFO | [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2017-12-19 20:35:34 | INFO | prov  : experimental [RSS][181048639]
2017-12-19 20:35:34 | INFO | Found Red Sonja (2017) issue: 11 using experimental [RSS]
2017-12-19 20:35:34 | INFO | Shhh be very quiet...I'm looking for Red Sonja issue: 11 (2017) using experimental [RSS]
2017-12-19 20:35:34 | INFO | search provider order is ['Experimental']
2017-12-19 20:35:34 | INFO | Issue Title given as : black roads
2017-12-19 20:35:34 | INFO | Initiating manual search for Red Sonja issue: 11
```

**Comment by evilhero** [comment]
@psychoflame do you have completed download handling enabled within Mylar - or are you just using the ComicRN script (it doesn't look like you do, but I need to ask)?

Is this a one-off snatch from the pull-list or is the item on your watchlist and you're initiating a manual search via the series page ? 

Actually here's an even better question, have you ever performed a Wipe NZBLOG from the History tab? I just noticed that it's not recreating the tables on startup properly. If this was the case, a restart of Mylar would fix the issue you're currently having....

**Comment by psychoflame** [comment]
I do have Complete Download Handling enabled in my settings. I've just turned it on, but can't get anything to successfully complete. I had to redo my entire setup, i was using the freenas plugin but i had the issue where i wasn't able to update my install of mylar. So i ended up reinstalling the plugin while preserving my existing settings. I'm calling the comicRN from Sabnzbd, as it should be done. The item in question is something that is on my watchlist, however i was running into the issue where mylar wouldn't move the file for some reason, and i did a bit of digging through issues on here and found one that said disabling the Comictagger and wiping the nzblog should fix this issue, so i tried that then initialed a manual search for this comic and that's where i got this error. I get a similar error though even if mylar automatically adds the comic to Sab though, freezes up my whole Sab queue. I'm gonna try updating and see if that fixes this issue

**Comment by evilhero** [comment]
If you have completed download handling enabled, you cannot use the comicRN script and vice-versa. If you do enable it, you just have to ensure the category that's assigned to comics in your sab is also the same within mylar and that comicrn isn't set to run.

I think one is clobbering the other if I'm not mistaken based in that log (I could be wrong, I just glanced quickly on my phone at the log) - but you can see 2 different instances of the post-processing run on the same issue almost at the same time.

**Comment by psychoflame** [comment]
Yeah that was the issue, It's successfully moving the issues when i disabled ComicRn in Sab. Thought you had to have both enabled. Thank you for the Help Evilhero
