### ISSUE TITLE
Persistent uncaught exception

### ISSUE THREAD

**Issue by xthursdayx** [evilhero/mylar#1580]
Hi, thanks for all your hard work evilhero. Mylar is working pretty well for me these days, but I'm still seeing the uncaught exception that I have copied below. Any ideas?

```
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1417, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/mylar/mylar/search.py", line 1602, in NZB_SEARCH
if foundc == "yes":
UnboundLocalError: local variable 'foundc' referenced before assignment
```

**Comment by evilhero** [comment]
Usually that's due to having an empty newznab entry in your config.ini, or not restarting mylar after a provider change of some kind. If you still have the log can you paste the lead up to that error if it's not what I mentioned above?

**Comment by xthursdayx** [comment]
This is the line before the uncaught exception:

`2017-02-25 18:57:21	WARNING	Connection error trying to retrieve data from newznab: ('Connection aborted.', error(110, 'Connection timed out'))`

**Comment by evilhero** [comment]
Do you have an empty newznab entry in your configuration? That or else one of the newznabs you have isn't responding and it's erroring out (it should handle the error gracefully,, but it's not for some reason). 

Can you confirm your newznabs - if you're unsure you can check the config.ini and you should be be to tell if there's an empty entry on that line

**Comment by xthursdayx** [comment]
I think it may be because I still have OZNZB listed even though the site is no longer available. I've unenabled it and will see if the problem persists. Thanks!
