### ISSUE TITLE
500 server error on wanted page

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1585]
I'm getting an error when I click on Wanted

Traceback (most recent call last):
  File "D:\mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "D:\mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "D:\mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\mylar\mylar\webserve.py", line 1600, in pullist
    'endweek':            u"" + endweek.strftime(date_fmt).decode('utf-8'),
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 1: invalid continuation byte

why? :(((

**Comment by evilhero** [comment]
It might have to do with your default language - I'm assuming you're using a non-english one on your OS? 

This was fixed awhile ago - what branch / commit of mylar are you running and on what OS?

**Comment by HypKin** [comment]
sorry its the "this week" page.

i'm on dev branch, german windows 10

Version: d94ae388de1ceedbcfdaed4cf6902e686d41155f

**Comment by evilhero** [comment]
Weird it should convert... From a python command line, can you type in ```get_locale();``` and see what the response is. I'm going to guess the locale isn't set to a utf-8 locale.

**Comment by HypKin** [comment]
just getting
File "<stdin>", line1, in <module>
NameError: name 'locale' is not defined

seems like there is something wrong with my python installation :( i'll look into it.

**Comment by HypKin** [comment]
ok i set the locale now i get de_DE, cp1252

i guess the cp1252 should be utf-8 right?

**Comment by evilhero** [comment]
Well in theory yes, but there is no utf-8 for de_DE - it's the only place in Mylar where the date is displayed like that from what I can see (the search returns that format, but it doesn't have to display it so it shouldn't error out on that)...I've added in a simple catch exception to the page, if it can't convert it as it currently, it will drop down to cp1252 and attempt that encoding (I have to leave it as is as it affected other locales which was fixed but obviously not for german in this particular case).

I'll have a fix up shortly into dev, just running through some things quickly on my windows machine...

**Comment by HypKin** [comment]
thx for the quick fix, its working again now :)
