### ISSUE TITLE
Search for older comics?

### ISSUE THREAD

**Issue by ImDevinC** [evilhero/mylar#1586]
Is it possible to search for older comics? I just installed Mylar and am trying to find older comics, but am having issues getting downloads started. Not using NZB, just torrents.

**Comment by evilhero** [comment]
Older comics would be dependent on the source you're searching against. As long as the series is added to mylar, it'll look - but public torrent search is limited to torrentproject and worldwidetorrents (which is probably too 'new' to have alot of older comics). 32p would be the best bet if you can find a way in.

**Comment by ImDevinC** [comment]
Thanks for the quick follow up!
