### ISSUE TITLE
Feature request : add a "last updated" column in the home page

### ISSUE THREAD

**Issue by tchirou** [evilhero/mylar#1587]
Hello
Would it be possible to consider adding a "last updated" column in /home to be able to know with one glance if all series have been updated recently and that there is no problem of refresh ?
Thanks a lot

**Comment by evilhero** [comment]
It's more about the screen real-estate - the data-tables don't allow for that field to be present and it's not necessarily an important overview-type of column to add to the main page (ie. keep it lean). 

However, it is currently available in another screen (Manage tab / Manage Comics) where you can sort all of your series by Date Last Updated.

**Comment by tchirou** [comment]
Oh thanks, I haven't saw that. It is perfect this way
Many thanks !

Le 9 mars 2017 à 19:18, evilhero <notifications@github.com> a écrit :

It's more about the screen real-estate - the data-tables don't allow for
that field to be present and it's not necessarily an important
overview-type of column to add to the main page (ie. keep it lean).

However, it is currently available in another screen (Manage tab / Manage
Comics) where you can sort all of your series by Date Last Updated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1587#issuecomment-285434693>, or mute
the thread
