### ISSUE TITLE
HTTPS proxy

### ISSUE THREAD

**Issue by timball** [evilhero/mylar#1589]
No support for either HTTPS or SOCK5 proxy. 

need a setting in config.ini
need to set httplib to use proxy

--timball

**Comment by evilhero** [comment]
Need more info than just 2 lines. In what manner are you using this for, or how are you wanting to use mylar with it even.

I can enable proxy support via cherrypy (it's disabled in mylar currently), but that won't cover https most likely.

**Comment by timball** [comment]
So in my setup i proxy all searcher requests thru tor, then my downloader grabs everything thru a vpn. 

letting mylar have a proxy setting would make this easier. i can send a PR. 

--timball

**Comment by evilhero** [comment]
If you can do a PR, that would save me a lot of time - especially since I can't test/troubleshoot against that particular item, and wouldn't be able to accomplish it within any amount of reasonable timeframe.
