### ISSUE TITLE
Story Arc Management move method

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1594]
Hello,

Before opening an issue I would like to be sure I'm not making something wrong.
I have a lot of series im following. However for reading purposes and use of ubiquooty I wanted to store the arc story separately.
So i went to arc management and i chose the move option and added a first arc to try it out.
But it actually copied the comic from the volume folder to the story arc folder, taking twice much spaced.
When you open an arc you are actually only presented with a copy check box and not a menu with move, copy, symlink, hardlink like on the arc management home page.
It this behaviour normal ?

If the move option works, would it still counts as an issue I possess in the comic page (and when clicking download, it would download it from the arc folder) or how should it work ?

Thanks for your help and you work, it's really much appreciated

**Comment by evilhero** [comment]
The move option wouldnt move the issues from your series directories as that would be counterproductive to managing the series themselves, thus the copy. The move/hardlink options are for post-processing moreso than the watchlist matches to the arc directory, which is also why the options don't appear on the actual arc page itself (it's a global arc option, not a per arc one). 

I believe I was going to try and add linking during the watchlist matching part of adding an arc, but honestly I can't remember if I did that (if you choose hardlink / symlink on the main arc page, you'll know right away if it's working or not I'm going to bet).

**Comment by yongbi85** [comment]
Thanks I will give it a try. I need to use the arc management to know in which order to read the arc issues :p
Even when retagging comic rack wouldnt see the alternative number in the arc sadly
