### ISSUE TITLE
[Feature request] Metatagging based on date

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1597]
Hello, me again
When you have a large library and grab the comic 0days every week it is possible that all metadata are not available when you grab the issues.
Would it be possible to introduce a metatagging option somewhere to enable refresh metadata for comics not older than xx days ?
Like if you input 30 it would scan your comic collection (database) for comics added less than 30 days ago and queue them for metatagging refresh ?

**Comment by evilhero** [comment]
It's an interesting notion for sure, aside from the influx of CV API hits that would be incurred, it could be something that's doable provided that it's not trying to metatag like 300 issues during each go round (cause it probably would hit the CV API limit prior to that I'm guessing).

**Comment by yongbi85** [comment]
I dont meant it to be automated more like a job you start on request.
