### ISSUE TITLE
[Enhancement Request] Folder volume naming

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1600]
Mylar Version: master
-- git build 3fa3cfe.
Python Version : 2.7.13

Hello,

I have a very large collection of comics and i was using $VolumeY so far but I'm considering switching to $VolumeN because of some comics who got rebooted twice in 2016 (which totally meeses up the comic folder and delete the comics as it keep replacing them, best example : deadpool & the mercs for money)
Would be like : $Publisher/$Series/$VolumeN
However if volume is 1 it won't create a v1 folder...
So for example in this case it would do
Marvel/Deadpool & The Mercs For Money/the v1 comics directly here
Marvel/Deadpool & The Mercs For Money/V2/the v2 comics there...

Is there any way to force mylar to use the v1 tag ? or if no v2 then VYear or so ?

Thanks again for your work

Edit : NVM sorry my bad, it works if there is a volume... (but when the series is added at the begginning on comicvine it has no volume so would be nice to be able to always create v1 just in case.
Deadpool & mercs for the money v2 was only done because the v1 worked well, but v1 had no volume beginning of 2016 and there is no way to automatically rename folder so it would be best if it was possible to have an option like "always create v1 folder"

Edit2 : $VolumeN is actually creating folder with name like 1 , 2 , 3, etc. instead of V1, V2, V3, etc.
$VolumeY is working fine. I guess there is V + str missing for the VolumeN tag (on folder side only)

**Comment by yongbi85** [comment]
If I read the code right (as I said not a python programmer but i can grasp some notion)
You have an issue on the file filerenamer.py


It is
79		new_name = self.replaceToken( new_name, md.series, '%series%')
80		new_name = self.replaceToken( new_name, md.volume, '%volume%')

Should be i guess

79		new_name = self.replaceToken( new_name, md.series, '%series%')
80		new_name = self.replaceToken( new_name, md.volume, 'v%volume%')

**Comment by yongbi85** [comment]
I'm trying to find the issue myself but i'm not a python programer so..
on importer.py (don't know if this is the script that is used also when adding a comic through the search) but on line362

        comversion = comic['ComicVersion']

shouldn't it be

        comversion = 'v' + comic['ComicVersion']

**Comment by evilhero** [comment]
No, it's storing it in the dB as 'v#', not just as the numeric. The problem moreso is how you have the volume label set for each series you're looking at (series detail page/edit settings/volume label) - it should be stored as v#. 

The post-processing run and the individual renamers take care of the volume label itself. It also is highly dependent on how you're adding the series into mylar - via the search / add series / import?

**Comment by yongbi85** [comment]
I have them stored as v#
Just checked on new x-men and it shows v2 in the edit settings
I'm adding deadpool through the search button on top left of mylar or through tampermonkey
Just tryed to add deadpool again through both methods (deleting every time between), i get the same issue
As said for comics name it is working well, but not for folder creation

**Comment by evilhero** [comment]
Upon checking further, it's because the Volume label isn't an available option for Folder Naming (if you look on the configuration tab / Advanced Settings / Renaming Options) - the only available options for folders are `$Publisher, $Series and $Year`. The $VolumeN / $VolumeY logistics has to done/copied over and tested for folders in order for it to work. I'll mark this as an enhancement request, because that's what it actually is.

**Comment by yongbi85** [comment]
Ok, thank you very much.
Could you point me to where is the folder naming handled in the code ? I'm willing to try some coding on my end on some additionnal naming style
