### ISSUE TITLE
[Support request] Use existing metadata

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1602]
Hello again
I was wondering when you do an import and check the use existing metadata does it scan for comicinfo.xml (comicvine) or zip header (cbl) by default when an issue has both?
I used to use both option but i dont use cbl anymore and i corrected some metadata with comicvine scrapper through comicrack so im hoping it prefer comicinfo over headers.

If it uses cbl by default when both are present, is there any way to remove the comment attribute on all cbz comics ?
Been searchin the web for the zip -z usage to remove comment on all files but didnt find anything that could help me and metatagging the issue again through mylar seems to reuse the old headers even if cbl is unchecked in the options

Thanks for your help

**Comment by evilhero** [comment]
It checks for comicinfo first, if not found it tries the comment. 

For mylar to remove the zip comment you need to make sure you have overwrite tags enabled, and then have the comicrack tag enabled, save the settings and restart mylar. Note that it will not preserve any tags you have, which means any custom comicinfo tags you did would get wiped in the process as it has to recreate the zip from scratch. 

On an aside, the zip -z "" option with a blank value should wipe out the existing zip comments for a given file.

**Comment by yongbi85** [comment]
Perfect consider this support request closed then.
I dont need to delete the comments then but if needed i will make a bash which lists all .cbz in my comic dir and then apply the command zip -z "" on all of them
