### ISSUE TITLE
NotifyMyAndroid Not Working

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1605]
NMA is not sending notifications, testing works fine, but outside of that it will not send.  I have it disabled on snatch, is it setup to notify on completed download?  If not, please make this an enhancement request.

**Comment by evilhero** [comment]
As long as you have it enabled, it will notify on post-processing completion of the given item. Notifying on snatch is the only thing that requires an enable option. 

Are you downloading via torrents or newsgroups? For torrent post-processing notification you can enable the option for 'notify on completed torrent post-processing'. 

Notifying on completed download would be something entirely different and would require mylar to be able to monitor the client's queue.

**Comment by DrSeussFreak** [comment]
I do newsgroups, although I do have torrents enabled for the 1 torznab entry allowed.  Post processing is not currently working for me.

**Comment by evilhero** [comment]
Post-processing notifications? Does the post-processing complete successfully otherwise? Do you have a debug log showing a recent post-processing rum of an issue that didn't notify?

**Comment by DrSeussFreak** [comment]
No recent log, but post processing works fine

**Comment by evilhero** [comment]
So where are the notifications not happening from - the sab or torznab entry, cause the torznab wouldn't notify on completion (cause that would be torrents, and dropping it into the folder monitor). 

I just tried both groups and torrents and got notifications about both (with torrents I had the 'manual post-processing - notify on completed torrents' enabled). 

Do you not see something in the logs in regards to the NMA status being returned during the post-processing (in verbose mode, mine said ```[NMA] Status code returned: 200```)

**Comment by DrSeussFreak** [comment]
filtering for NMA in logs shows nothing.  I enabled debug mode tested the connection, then I saw `[NMA] Status code returned: 200`. I will add a series and have it auto-pull the books and report back

**Comment by DrSeussFreak** [comment]
In the process of doing this, I have disabled torrents, and I have NZBHydra configured, but I am seeing the following error

`2017-03-26 12:58:00	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.`

**Comment by DrSeussFreak** [comment]
I manually downloaded the file, but Mylar did the post-processing, and no NMA record was recorded

**Comment by evilhero** [comment]
Mylar will not notify of completed post-processing if it's snatched outside of Mylar. You need to have mylar snatch the file and do the post-processing and then it will notify on that completion (since it can track the id's since it was snatched by mylar). Notification of completed manual post-processing might be doable (it was at one point), but there are those that post-process hundreds of issues at a time manually and obviously the option to turn off such notifications would have to be included.

The 0 search providers error happens when you make a configuration change to your providers, save the config and don't restart Mylar. On any configuration change where you enable/disable a provider, and then save the configuration a restart of Mylar is required in order to load the proper values (since it only loads the sequences during startup).  You probably need to now shutdown Mylar, edit the config.ini, and delete the entire provider_order line, save & close the config.ini, and then start up Mylar again for the new sequence to take effect.

**Comment by DrSeussFreak** [comment]
So just shutdown, checked the config.ini and all looked great, started it back up and went to "This Week".  Clicked back to last week and get the following error

`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\ProgramData\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\ProgramData\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\ProgramData\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\ProgramData\Mylar\mylar\webserve.py", line 1561, in pullist
    weekinfo = helpers.weekly_info(week, year)
  File "C:\ProgramData\Mylar\mylar\helpers.py", line 2418, in weekly_info
    startofyear = date(year,1,1)
NameError: global name 'date' is not defined`

Don't seem to have any log entries, running in debug mode though.

**Comment by DrSeussFreak** [comment]
On a side note, I had Mylar search and send a file to SabNZBd, it notified me on snatch but not for completing post-processing

**Comment by evilhero** [comment]
Ah crap the date is due to the latest commit. I'll patch that momentarily. 

As far as the sab post-processing, do you still have the debug logs for that?

**Comment by DrSeussFreak** [comment]
Log attacged
[mylar.zip](https://github.com/evilhero/mylar/files/872745/mylar.zip)

**Comment by DrSeussFreak** [comment]
latetst update fixed the issue with browsing previews weeks

**Comment by DrSeussFreak** [comment]
NMA is dead, so closing this ticket
