### ISSUE TITLE
Post Processing not working on Sab

### ISSUE THREAD

**Issue by elmerfdz** [evilhero/mylar#1608]
I've just noticed post processing isn't working. It gets stuck on post processing for 5mins, sometimes more and than times out with the error in screenshot.

Mylar Log file: https://pastebin.com/sZC8GyuH

Sabnzbd error screenshot: 
![image](https://cloud.githubusercontent.com/assets/22656503/24458183/19ae2a6c-1490-11e7-859e-4eb673f41e70.png)

**Comment by evilhero** [comment]
I think your IPs are messed up somewhere. Nzbhydra is on localhost, but your mylar is running on 172.21.35.134? 

If that's correct you need to make sure that mylar is listening on the correct interface and that the autoProcessComics.cfg host is set to the same identical value. If you want mylar to listen on all interfaces, set the host to 0.0.0.0

**Comment by elmerfdz** [comment]
I've narrowed down the problem. I've had HTTPS enabled on Mylar, seems like the scripts aren't playing nice with HTTPS enabled, disabling HTTPS fixed my issue. 

But I want to have HTTPS enabled on Mylar, could you please look into what's causing this on the script?

**Comment by evilhero** [comment]
There's nothing to take a look at - it works, there's literally something messed up with your configuration.

Look at the screenshot you posted initially - the dos window shows it's trying to open an non-https url, saying it's denied and then you mention that you're running https for Mylar. So of course it's going to get rejected as it can't accept anything but https connections. 

You need to ensure that your autoProcessComics.cfg is set to EXACTLY the same information as what you have within the Mylar configuration tab (if you have https enabled for mylar and your certificate is ok, you need to set the value for ssl to 1 within the autoProcessComics.cfg file).

It also looks like you're trying to run a reverse proxy or something as your webroot shouldn't be /mylar  with a port designation (your screenshot says http://localhost:8090/mylar/) - one of the main reasons to use a reverse proxy is to not have to use a port designation as that's handled by the reverse proxy itself.

**Comment by elmerfdz** [comment]
thanks for your help
