### ISSUE TITLE
Mylar quit downloading issues, and when I search for an issue that exists, I get this.

### ISSUE THREAD

**Issue by ghost** [evilhero/mylar#1611]
Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1418, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/Mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/Mylar/mylar/search.py", line 643, in NZB_SEARCH
r = requests.get(findurl, params=payload, verify=verify, headers=headers)
File "lib/requests/api.py", line 69, in get
return request('get', url, params=params, **kwargs)
File "lib/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "lib/requests/sessions.py", line 465, in request
resp = self.send(prep, **send_kwargs)
File "lib/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "lib/requests/adapters.py", line 370, in send
timeout=timeout
File "lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
body=body, headers=headers)
File "lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
File "lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
if 'timed out' in str(err) or 'did not complete (read)' in str(err): # Python 2.6
TypeError: __str__ returned non-string (type Error)

**Comment by evilhero** [comment]
Either one of your providers is timing out waiting for a response (it's down, or your api is maxed?), or you're using an older version of python with mylar (the Python 2.6 at the end doesn't seem normal but it's a comment too). 

You can confirm your version of python that you're running mylar with  by going to the first tab in the configuration and seeing what it says.

**Comment by dudeslife** [comment]
@evilhero 

python 2.7.12

**Comment by evilhero** [comment]
Then the nzb provider you're using is returning a timed out response for some reason. What's the provider and can you verify that you're not over your api limit, or that there are no problems with them?

**Comment by dudeslife** [comment]
@evilhero 

it's my indexer. on the same machine as Mylar.

**Comment by evilhero** [comment]
And you're sure you're running mylar against the right python version (I know you said you installed an additional python version in another thread). 

If it's not the python, then it's something to do with the index - it's not letting you access it or something related due to the timeout response.

**Comment by dudeslife** [comment]
@evilhero 

correct python confirmed:

Mylar Version: development
-- git build f8241e9b6c11276626c858b3c1f115901653d2a4.
Python Version : 2.7.12

indexer is working correctly with other apps

**Comment by evilhero** [comment]
Well your git version of mylar is a bit behind.. But aside from that, it should be working fine if the other questions I asked were good. 

Can you post the debug logs leading up to that error - there's something occuring at some point that's causing some issues, but it's really difficult to tell at this point without more detailed logs.

**Comment by dudeslife** [comment]
@evilhero 

regarding my git version, a pull is telling me Im up to date.

Here is my log with debug info:

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1418, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/Mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/Mylar/mylar/search.py", line 643, in NZB_SEARCH
r = requests.get(findurl, params=payload, verify=verify, headers=headers)
File "/opt/Mylar/lib/requests/api.py", line 69, in get
return request('get', url, params=params, **kwargs)
File "/opt/Mylar/lib/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/opt/Mylar/lib/requests/sessions.py", line 465, in request
resp = self.send(prep, **send_kwargs)
File "/opt/Mylar/lib/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/opt/Mylar/lib/requests/adapters.py", line 370, in send
timeout=timeout
File "/opt/Mylar/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
body=body, headers=headers)
File "/opt/Mylar/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
File "/opt/Mylar/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
if 'timed out' in str(err) or 'did not complete (read)' in str(err): # Python 2.6
TypeError: __str__ returned non-string (type Error)
2017-04-01 12:04:12	DEBUG	[SSL: True] Search URL: https://myIndexer.org/api?t=search&q=Public%20Domain%20Comic%20020&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2017-04-01 12:03:12	INFO	pausing for 60 seconds before continuing to avoid hammering
2017-04-01 12:03:12	DEBUG	calpha/cnumber: None / None
2017-04-01 12:03:12	INFO	Shhh be very quiet...I'm looking for Public Domain Comic issue: 20 (2017) using myIndexer (newznab)
2017-04-01 12:03:12	DEBUG	using Newznab host of : myIndexer
2017-04-01 12:03:12	DEBUG	Initiating Search via : api
2017-04-01 12:03:12	INFO	search provider order is ['newznab:myIndexer']

**Comment by evilhero** [comment]
I honestly don't see that commit version anywhere in the logs now (thought it was 2 months old, but nope). 

How did you install mylar - and you might want to make sure that the git_branch in the config.ini is set to development. 

Has the indexer always worked with mylar - as far as the https stuff even?  If it's a self-signed certificate, you can't verify the ssl (you probably know that, but just saying it anyways)

**Comment by dudeslife** [comment]
git_branch = development

I added just another indexer to test and it worked correctly, so the problem must be with my indexer.

**Comment by evilhero** [comment]
Weird it might be related to requests package that mylar uses - it's a very uncommon error, but it looks like the error is still present in requests 2.9.1 (mylar uses 2.7.0).

Thr 'quick fix' is to turn off the verify ssl option for that indexer within mylar (make sure to save the config & restart mylar thereafter). I'll have to look into it more, aside from you installing cryptography ```pip install requests[cryptography] ```, I might have to upgrade requests within mylar once the bug has been confirmed as fixed.

**Comment by evilhero** [comment]
What happens when you try to do a check for updates within the mylar app?

**Comment by dudeslife** [comment]
2017-04-01 12:37:05	WARNING	Could not get commits behind from github
2017-04-01 12:37:05	INFO	Retrieving latest version information from github

**Comment by evilhero** [comment]
How did you install mylar initially? 

Sometimes if you send too many requests to github, it temp blocks you for a few mins.. It might just be that happening (it happens to me on my own repo sometimes even)

**Comment by dudeslife** [comment]
so long ago, I don't remember how I installed.

**Comment by evilhero** [comment]
That might be related to the problem at hand with updating then. 

You can start fresh - it's easy enough. Backup your config.ini, mylar.db and your entire cache directory (it has all the jpgs for the series covers). Wipe the dir. Reinstall it back into same location with the git clone option (I would do a git clone https://github.com/evilhero/mylar -b development). Move everything back, start it up and you should be on dev with the current commit showing ;)

**Comment by dudeslife** [comment]
Ok that solved the Git update issue. I don't know where to begin downloading probs. a downgrade of Requests module?

**Comment by evilhero** [comment]
No, cause it uses the internal requests library so your own version doesn't have anything to do with that part. You could try installing the cryptography module for requests, that seems to have helped alot of people with ssl related problems (to install it's ```pip install requests[cryptography] ```. 

Aside from that if that doesn't work (if you leave verify ssl on and it doesn't work still), turn off the verify ssl option for that newznab entry in the mylar configuration GUI. Save it a d then restart mylar and it'll work, but it'll spam a message a few times about being an insecure connection because it can't be verified properly)

**Comment by dudeslife** [comment]
Verify SSL is not ticked.

and crypto is already installed and up to date. 

argh.

**Comment by dudeslife** [comment]
its a DYNDns domain and the self signed cert matches.

I always restart after any changes.  I have no way of know if it ever really worked as it was never the only indexer in the config. There was always at least one other above it.  Now I am really irritated. :)

**Comment by evilhero** [comment]
I don't know if you can verify a self-signed certificate properly, which is why the verify=False option is used in those types of situations (unchecking verify ssl for the newznab is equivalent to a False setting). I know you can pass the requests module your public .pem file for the verify option instead of True/False, but that option isn't available in Mylar as it would be a really advanced option to use and I have like zero way to test anything involved with it.

**Comment by evilhero** [comment]
There is something you can try...I mean it's outside of the realm, but it's fairly easy and then we would both know right away if upgrading requests will work.

Here's what you can try:
- download the requests source - just do a (git clone https://github.com/https://github.com/kennethreitz/requests.git) into an empty directory (outside of mylar) 
- cd into the requests directory that was just created, and inside you'll see a requests subdirectory.
- copy that entire requests subdirectory into your mylar/lib/ folder and overwrite the requests directory therein. Then cd to the mylar/lib/requests directory and delete all the .pyc files within as they'll be pointing to the incorrect version.
- start up mylar and try and cross fingers !

**Comment by dudeslife** [comment]
there is no requests dir within mylar to overwrite. should there be on there already?

**Comment by dudeslife** [comment]
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/home/me/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "/home/me/mylar/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/home/me/mylar/mylar/rsscheck.py", line 6, in <module>
    import requests
  File "lib/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning

**Comment by evilhero** [comment]
Maybe try updating your local version of requests ```pip install -U requests```.  That'll update your local version of urllib3 which it's trying to reference. Like I said, this is a very unique problem that doesn't happen very often it seems, so it's going to require a bit of outside thought to get it to work...

or did you uninstall urllib3 previously ?

**Comment by dudeslife** [comment]
requests already up to date.

**Comment by evilhero** [comment]
When you're doing the pip, are you doing it against your version of python that you're running Mylar against and not your local version ? I mean, if you're running python with 'python 2.7', then you need to do your pip installs against ```pip-2.7 install package``` (if your pip is >0.8). If your pip is >=1.5, then it's ```pip2.7 install package```

**Comment by dudeslife** [comment]
yeah, this is my pip

$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by evilhero** [comment]
k, so then when you do the requests update - are you doing it as ```pip2.7 install requests``` ?

**Comment by dudeslife** [comment]
$ sudo pip2.7 install -U requests
Downloading/unpacking requests from https://pypi.python.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl#md5=5e432dcf5bd1e3402ea1656700d99365
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB): 584kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests
Cleaning up...

**Comment by dudeslife** [comment]
still not working. 

I think we will just have to accept that it's a unique issue and probably not solvable. :(

thanks for all of your help and for a great app.

**Comment by evilhero** [comment]
Well, the weird thing is - that 2.2.1 is probably the max that your OS python will allow (assuming you're not running python 2.7.9+ as the OS system which is what it's saying). The requests version that's the newest is 2.13 (13 is higher than 2.1).

You can force install the version by doing ```sudo pip install --ignore-installed requests```

This usually happens when a package (requests) is installed via another manager other than pip (possibly apt-get or the like)
