### ISSUE TITLE
rtorrent RPC error

### ISSUE THREAD

**Issue by Herjar** [evilhero/mylar#1612]
I just changed from using a watch directory to rTorrent RPC method. The connection works fine and it downloads the torrent, but I get an error right after it starts the torrent. It then seems like it stops processing it and does not mark the issue as downloaded. Here is the error I get.: 
`Successfully loaded torrent.
[True] Now starting torrent.

Uncaught exception: Traceback (most recent call last):
File "/media/a6a3/home/herjar/.mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/media/a6a3/home/herjar/python/python2/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/media/a6a3/home/herjar/.mylar/mylar/webserve.py", line 1418, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 1574, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/media/a6a3/home/herjar/.mylar/mylar/search.py", line 2187, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
File "/media/a6a3/home/herjar/.mylar/mylar/rsscheck.py", line 1008, in torsend2client
torrent_info = rp.main(filepath=filepath)
File "/media/a6a3/home/herjar/.mylar/mylar/test.py", line 63, in main
torrent_hash = self.get_the_hash(filepath)
File "/media/a6a3/home/herjar/.mylar/mylar/test.py", line 96, in get_the_hash
metainfo = bencode.decode(torrent_file.read())
AttributeError: 'module' object has no attribute 'decode'`

**Comment by evilhero** [comment]
First, you need to make sure you're up to date on whichever branch you're running of mylar. 

Make sure that if there is a  bencode.pyc file that it is not present in the mylar subdirectory (ie. /opt/mylar/mylar/bencode.pyc) - if it is, delete it. If there is a bencode.py file in that same location, delete it as well (there shouldn't be if you're on a recent commit) 

The bencode.py file got moved into the lib subfolder awhile ago, but the .pyc file remained on some systems in its' original location and if it exists it'll try using that mistakingly.

**Comment by Herjar** [comment]
Deleting bencode.pyc fixed it. Thank you.
