### ISSUE TITLE
Error after updating to latest build

### ISSUE THREAD

**Issue by andrews89** [evilhero/mylar#1615]
I'm not sure what I've done wrong here, but now whenever I attempt to refresh a comic I receive: 

	Uncaught exception: Traceback (most recent call last):
    File "/home/plex/plex-system/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
    File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "/home/plex/plex-system/mylar/mylar/updater.py", line 286, in dbUpdate
    cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
    File "/home/plex/plex-system/mylar/mylar/importer.py", line 431, in addComictoDB
    logger.warn('Unable to download image from CV URL link: ' + comic['ComicImage'] + ' [Status Code returned: ' + str(r.status_code) + ']')
    UnboundLocalError: local variable 'r' referenced before assignment

Originally had the wrong version of python (2.7.6) before installing pyenv and adding pyenv local 2.7.9 (with that version installed) to the local directory.  Not sure if this is part of my issue.

**Comment by evilhero** [comment]
Are you sure you're running mylar with the 2.7.9? 

You can check by going to the first tab in the configuration GUI and it'll tell you the version and location. The modules you installed for 2.7.6 need to be installed for 2.7.9 (they're not is leva cross different versions).

**Comment by andrews89** [comment]
Sorry for the bother, you were 100% right - still using 2.7.6 (handy to have the version there, I somehow never noticed it).  I forgot to go into the default file and change the python_bin path to the shims from pyenv.  Thank you so much for helping, and again, sorry for the bother!
