### ISSUE TITLE
Metadata Tagging changes permission of files at post processing.

### ISSUE THREAD

**Issue by ShoGinn** [evilhero/mylar#1616]
When post processing if Metadata tagging is enabled the file is effectively added to the Comic Location Path with the permissions 0600.

The issue with this in my case is changing the permissions after is not an option due to container limitations on my system.

How can we do the tagging while maintaining the file permissions of the downloaded item?

**Comment by evilhero** [comment]
It probably has some dependency on the OS you're running - and if you're using ACL's or enforcing some permissions on the OS level. 

It might be possible for mylar to get the guid and uid of the file prior to copy/move for metatagging,  and then reset the guid, uid after the tagging so it can move them back. Even with the copy/move that mylar  currently uses during post-processing(shutil.copy/shutil.move), the permission bits are copied from the original location.

Now that I think of this, I'm betting that since the file is created in the cache directory it's inheriting the 0500 because of the directory perms and when it moves it out that's what it's set to (seeing as how the permission bits are supposed to be identical during a copy/move).

Can you confirm that the cbr / cbz that gets placed into the cache folder have the same permissions as the location it was copied from, and then that the converted cbz done during metatagging has the 0500 permissions ?

**Comment by ShoGinn** [comment]
System versions are:
Ubuntu 16.04 (Unprivileged LXC on ProxMox)
SABNZBd 2.0.0RC3

Permissions are hard locked after "creation"
So if I move any files thats the permissions... no changing it.
I could modify the container but its all a pain ;)

My main reason is that I currently use Ubooquity to read the comics, and that is ran under a different UID but same GUID. But since its 0500 the file cannot be read.

---

One thing I can confirm is that when I disable the metatagging the file being copied is 0666.

If I enable the tagging it is copied as 0500.

I checked the Cache folder
```
# file: cache/
# owner: mylar
# group: media
user::rwx
group::rwx
other::rwx
```
And the files in it are 0500 which is odd..

-
If I turn off meta tagging and let it move the files and then re-enable the tagging and "manually" tag.

The permissions remain at 0666.

**Comment by evilhero** [comment]
Do you have enforce permissions enabled within the mylar config at all? If you do what are your settings, if you don't - have you tried enabling it and seeing if it helps at all?

**Comment by ShoGinn** [comment]
@evilhero I have enabled enforce permissions but unfortunately due to the nature of unprivileged containers once a file is created no changes can be made to the file in regards to permissions/ownership. So it fails... 

My fix has been to run a cronjob to 0666 all CBZ files on the server (not at all optimal)

I have looked into the cache folder to see what is happening during the conversion, and when it creates the mylar_f93dks folders the files inside are 0500.

Once it copies from there it remains that file attributes.

**Comment by evilhero** [comment]
So if the folder in the cache is being created at 0500, then you would think that either the user running mylar (and doing the copy) doesn't have enough privileges, or the perms are inherited from the parent dir and enforced by the OS. Unless you are enforcing via acl, it shouldnt be more difficult than that. 

If a file is copied / moved into the cache folder from outside the container, what are the default perms it's supposed to have if nothing is specified? Just read-only owner?

**Comment by ShoGinn** [comment]
So thats my question, when the conversion process happens is unzip/unrar creating permissions? 

I think that the user running mylar has plenty of permissions for the area it controls. But in my situation once that file is then moved it retains the original permissions (0500).

So yes, it is inherited from the parent dir (in this case the cache) because my download folder without conversion is 0666 (tested).

ACL's are disabled on my OS due to the nature of the unprivileged container. Which is why I'm having difficulty in post-processing. All my other media server apps do the permissions in the cache folders etc before moving.

**Comment by ShoGinn** [comment]
To refine whats going on:

I have an Ubuntu 16.04 LXC on ProxMox that is setup as unprivileged.

On ProxMox I have a NFS folder mounted and then a mount point created inside the server running mylar.

The mylar server has a user "mylar" with a shared group "media" to allow for other services to access files/write to them etc. 

I am pretty lax on the file permissions but most of the time 0644 is appropriate in my usage.

So the mylar service has no problem writing to the /opt/mylar/ folder as it owns it as well as any other media group owner. So cache when auto created is 755 but the files inside (covers for comics) are 0500

**Comment by ShoGinn** [comment]
So im a big dummy with my octals ;) its 0600 not 0500 for all above. (i'll edit above to reflect)

**Comment by ShoGinn** [comment]
So disregard this whole issue..

My fix on this was to delete the cache directory
Then remove the chown portion (blank out the UID/GID)

And then just add 0666 as the chmod

And low and behold your program works beautifully. 

Count this as another dumb user problem.

(Took me forever to turn on debug and figure out what I was doing wrong)

Hope this thread at least helps one person.

**Comment by evilhero** [comment]
Well I wouldn't exactly call it dumb, but it was definitely unique as I was pretty stumped. 

Glad you got it working finally regardless, and thanks for posting back the solution as well :)

**Comment by ShoGinn** [comment]
@evilhero I think if you added to the wiki that UID/GID isn't required it might help others. (But maybe it was just me) I try to RTFM before I ask these questions. ;)
