### ISSUE TITLE
type error  on wanted page

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1620]
i did a force check of the wanted issues and now i'm getting the following error:

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```
71 <tr class="${issue['Status']} grade${grade}">
72 <td id="select"><input type="checkbox" name="${issue['IssueID']}" class="checkbox" value="${issue['IssueID']}"/></td>
73 <td id="comicname"><a href="comicDetails?ComicID=${issue['ComicID']}">
74 <%
75 if any(d['IssueID'] == str(issue['IssueID']) for d in ann_list):
76 adjcomicname = issue['ComicName'] + ' Annual'
77 else:
78 adjcomicname = issue['ComicName']
79 endif
```

i'm on windows, dev channel

**Comment by evilhero** [comment]
Do you have annual integration enabled or disabled by chance - and do you have any annuals currently marked as Wanted?

**Comment by HypKin** [comment]
yes annual integration is enabled, and at least 1 annual is marked as wanted (titans annual 1)

**Comment by HypKin** [comment]
i manually changed the wanted annual to skipped and now the wanted page is working again

**Comment by evilhero** [comment]
I'll have to look into it more as I can't replicate it on my end atm.. Do you have the titans annual showing up on the titans series page, or do you have the annual as its own watchlisted series - or both?

**Comment by HypKin** [comment]
the annual was on auto watch but also integrated into the main series.

cant replicate it too really, but i also had a "none none none" entry (so everything was "none") in the wanted list that i set to ignore just before the error occured i think.

**Comment by evilhero** [comment]
auto-watch might be screwing up with annuals alone, then you tack on the annual integration option...well it can make things a mess really really quickly. At least I have a starting point now, knowing that it was indicating it as a 'none none none' entry helps too, as that has to get generated at one point and there are only so many points that it actually happens (just trying to find that particular point would be the trial & error part).

Thanks for the info, I'll give an update in here when I can figure out more on the issue ;)
