### ISSUE TITLE
Pullist returns 500 Internal Server Error (QNAP)

### ISSUE THREAD

**Issue by azuravian** [evilhero/mylar#1622]
Running on a QNAP and moved over my database with no issues.  Set config.ini to use alt_pull = 2 (also tried 0) and I get the following when trying to open the pull list:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/webserve.py", line 1568, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/webserve.py", line 1806, in manualpull
    weeklypull.pullit()
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/weeklypull.py", line 200, in pullit
    return pullitcheck()
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/weeklypull.py", line 794, in pullitcheck
    statusupdate = updater.upcoming_update(ComicID=ComicID, ComicName=ComicName, IssueNumber=ComicIssue, IssueDate=ComicDate, forcecheck=forcecheck)
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/updater.py", line 427, in upcoming_update
    whackness = dbUpdate([ComicID], calledfrom='weekly')
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/updater.py", line 140, in dbUpdate
    whack = helpers.havetotals(refreshit=ComicID)
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/helpers.py", line 1274, in havetotals
    comiclist.append({"ComicID":      comicref['ComicID'],
IndexError: No item with that key
```

**Comment by evilhero** [comment]
What branch /commit are you running of mylar - and are you shutting down mylar before you edit the config.ini file? 

It sounds that you might have a bad entry in the db that's causing an error (maybe a series that's stuck in a loading status)?

**Comment by azuravian** [comment]
This is using the master branch of mylar.  Version: 32134e796e267cf7aa3004abe4626e4fd61c644a

Is there any way to tell what series might be causing the error, I could remove that series and re-add later.

**Comment by evilhero** [comment]
You could go to the Manage tab/ Manage comics and see if any series  therein are in a loading state. 

Another way to narrow it down  is to go to your Wanted tab. At the bottom it will show all the issues from the current week that are on your watchlist. Since the pull is erroring out, it'll be one of those series that's causing a problem.

**Comment by azuravian** [comment]
Interestingly enough, I have nothing in this week's upcoming.  

![2017-04-16_1341](https://cloud.githubusercontent.com/assets/7379812/25072992/7a8ad74a-22aa-11e7-8c60-136b1d5a0479.png)

**Comment by azuravian** [comment]
Just found another interesting tidbit.  I might not have ever been using alt_pull = 2.  Every time I change it, whether I shutdown, change, then restart or not, it reverts back to alt_pull = 0.

**Comment by evilhero** [comment]
It sounds like you're either not editing the correct config.ini file, or you don't have perms to change it? 

When mylar starts up, if you go to the config tab it will show the location where it's loading the config.ini from. I'm betting since you're probably used a package installer (or you're running as a daemon) that the location it shows is different than what you're tyring to edit.

**Comment by azuravian** [comment]
And it's fixed.  On the QNAP, after shutting down Mylar within the web interface, I had to stop the service before editing the config.ini to alt_pull = 2.  After doing that and then starting the service back, I'm good to go.  Sorry for the wild goose chase.

**Comment by evilhero** [comment]
Ha, no worries - the problem with me helping people with different configs is that I don't run them, so it's a lot of trial and error to find a solution. 

Glad you figured it out and got it sorted!
