### ISSUE TITLE
I cant see any snatches

### ISSUE THREAD

**Issue by Arathen** [evilhero/mylar#1623]
This is a kinda trivial cosmetic issue, so I almost feel guilty reporting it. I recently switched from using Blackhole to using the rtorrent scgi interface as a downloader. Ever since then, snatches are not reported in the History tab. I can see all the Post-Processed history, but no snatches whatsoever. Its kinda handy to know whats snatched so I can see if anything failed post processing, but like I said, not a world-ending situation :)

Mylar Version: development
-- git build 13cbe739c6a8a86905a1873519c8dffa5edf3240.
Python Version : 2.7.12
OS is Ubuntu 16.04.2 armhf on a Raspberry Pi 2.

As always, thank you so much for all the work you put into such an awesome tool :)

**Comment by evilhero** [comment]
Are the items in a snatched status on the series detail pages, but just not in the history tab? I haven't changed much of anything lately to do with the blackhole, so I'll need to look into this and see what's happening exactly.

**Comment by Arathen** [comment]
Blackhole still works fine. Its rtorrent scgi that doesnt record a snatch. Also, im using 32p exclusively at the moment, so the problem definitely does affect it.

Ill need to check again to see whether the issue is marked as snatched on the series detail page. I didnt think to look at that. Sorry.
