### ISSUE TITLE
Does Mylar have a webserver?

### ISSUE THREAD

**Issue by benyjr** [evilhero/mylar#1624]
I can't seem to access Mylar remotely, be it from inside my home network , or from outside.  I can only seem to use it on the machine it's running on.

Sickrage, Transmission, and Mythtv, I have no problem accessing remotely.  Just Mylar.

Am I missing something?  Or is that just the way Mylary is?

**Comment by evilhero** [comment]
Don't use localhost as the host for Mylar if you wish to access it from different machines. Setting it to 'localhost' will make Mylar only listen to the local interface for connections (ie. you have to be on the machine to access it). If you want to have other machines access it, then you should use either '0.0.0.0' (if you want any machine, internal or external to access it), or even the ip address of the machine itself - either or will allow you to remote access. Do note that if you have a router or the like (like most people do), you'll probbably need to forward ports if you want to access from outside your network.

**Comment by benyjr** [comment]
Cool! Thank you!

**Comment by thingdeux** [comment]
@benyjr - Please close this issue / question.
