### ISSUE TITLE
Feature Request - Add Upcoming Wanted API Method

### ISSUE THREAD

**Issue by hubbcaps** [evilhero/mylar#1626]
Basically requesting a combination of both Upcoming and Wanted methods, particularly showing the release date of the upcoming issue.

**Comment by evilhero** [comment]
I'll look into this - I've been wanting to restructuring the api into a restful api, so not sure if I'll do this before or after... But I'll see how easy it is to do atm

**Comment by hubbcaps** [comment]
It actually appears Upcoming already provides this. I thought the upcoming method provided basically the full pull list of the week, however it actually seems to only show what's already listed as wanted and upcoming. So that's cool and I think this is good to close out.
