### ISSUE TITLE
manual TPSE search not marking snatched

### ISSUE THREAD

**Issue by JaBaine** [evilhero/mylar#1628]
I was trying a manual TPSE search and noticed that even though the torrent was downloaded to the watch directory the issue was not marked as snatched 

here is what I found in the log file

02-May-2017 13:13:48 - INFO    :: Thread-15 : Initiating manual search for Adam Strange/Future Quest Special issue: 1
02-May-2017 13:13:48 - INFO    :: Thread-15 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Adam Strange-Future Quest Special
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : Publisher is : DC Comics
02-May-2017 13:13:48 - INFO    :: Thread-15 : Issue Title given as : strangequest; out of the alley
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : Checking for torrent enabled.
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : nzbprovider(s): ['nzb.su']
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : there are : 1 torrent providers you have selected.
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : there are : 1 nzb providers you have selected.
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : Usenet Retention : 1302 days
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : found provider in existing enabled providers.
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : checking against torrent provider: tpse
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : torrent provider found: tpse
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : provider order sequence is now to start with tpse at spot #0
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : found provider in existing enabled providers.
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : checking against nzb provider: nzb.su
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : provider order sequence is now to start with nzb.su at spot #1
02-May-2017 13:13:48 - INFO    :: Thread-15 : search provider order is ['tpse', 'nzb.su']
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : Initiating Search via : api
02-May-2017 13:13:48 - INFO    :: Thread-15 : Shhh be very quiet...I'm looking for Adam Strange/Future Quest Special issue: 1 (2017) using TPSE
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : calpha/cnumber: None / None
02-May-2017 13:13:48 - DEBUG   :: Thread-15 : Sending request to [TPSE] for adam strange future quest special : 001
02-May-2017 13:13:59 - INFO    :: Thread-15 : [TPSE] there were 2 results..
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : checking search result: DC Week+ 03 29 2017 aka DC Week 291 HTD (2017)
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : sub:DC Week+ 03 29 2017 aka DC Week 291 HTD (2017)
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : size given as: 682.6 MB
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Fri, 31 Mar 2017 01:50:13 +0000 is after store date of 2017-03-29
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Entry: DC Week+ 03 29 2017 aka DC Week 291 HTD (2017)
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Cleantitle: dc week  03 29 2017 aka dc week 291 htd (2017)
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Cleantitle: dc week  03 29 2017 aka dc week 291 htd (2017)
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 0. Bracket Word: dc week  03 29 2017 aka dc week 291 htd 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Comic: dc week  03 29 2017 aka dc week 291 htd 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : UseFuzzy is  : None
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ComVersChk : 0
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 1. Bracket Word: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : year detected: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : year looking for: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 2017 - right years match baby!
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : original nzb comic and issue: dc week  03 29 2017 aka dc week 291 htd 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : adjusted nzb comic and issue: dc week  03 29 2017 aka dc week 291 htd 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : comic_iss is : 291htd
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : issue number seperated. Rejoining to complete comparison properly to : htd
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : adjusting from: dc week  03 29 2017 aka dc week 291 htd  to: 291htd
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ['dc', 'week', '03', '29', '2017', 'aka', 'dc', 'week', '291', 'htd'] nzb series word count: 8
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ['adam', 'strange', 'future', 'quest', 'special'] watchlist word count: 5
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : splitst : 8
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : len-watchcomic : 5
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : incorrect comic lengths after removal...not a match.
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : checking search result: DC Week+ 03 29 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : sub:DC Week+ 03 29 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : size given as: 698.1 MB
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Wed, 29 Mar 2017 15:25:34 +0000 is after store date of 2017-03-29
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Entry: DC Week+ 03 29 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Cleantitle: dc week  03 29 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : detected invalid nzb filename - attempting to detect year to continue
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Cleantitle: dc week  03 29 (2017) 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 0. Bracket Word: dc week  03 29 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Comic: dc week  03 29 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : UseFuzzy is  : None
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ComVersChk : 0
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 1. Bracket Word: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : year detected: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : year looking for: 2017
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : 2017 - right years match baby!
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : original nzb comic and issue: dc week  03 29 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : adjusted nzb comic and issue: dc week  03 29 
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : chg_comic:dc week 03
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : chg_comic: DCWEEK03
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : findcomic_chksplit: ADAMSTRANGEFUTUREQUESTSPECIAL
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : changeup to decimal: .29
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : adjusting from: dc week  03 29  to: 03.29
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ['dc', 'week', '03', '29'] nzb series word count: 2
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : ['adam', 'strange', 'future', 'quest', 'special'] watchlist word count: 5
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : splitst : 2
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : len-watchcomic : 5
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : incorrect comic lengths after removal...not a match.
02-May-2017 13:13:59 - DEBUG   :: Thread-15 : Sending request to [TPSE] for adam strange future quest special : 01
02-May-2017 13:14:12 - INFO    :: Thread-15 : [TPSE] there were 4 results..
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : checking search result: 0 Day Week of (2017) 03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : sub:0 Day Week of (2017) 03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : size given as: 9.67 GB
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Fri, 07 Apr 2017 11:49:53 +0000 is after store date of 2017-03-29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Entry: 0 Day Week of (2017) 03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Cleantitle: 0 day week of (2017) 03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Cleantitle: 0 day week of (2017) 03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 0. Bracket Word: 0 day week of 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Comic: 0 day week of 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : UseFuzzy is  : None
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ComVersChk : 0
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : mini-series detected : 0 day week of 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 1. Bracket Word: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : year detected: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : year looking for: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 2017 - right years match baby!
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 2. Bracket Word:  03 29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : original nzb comic and issue: 0 day week of 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : adjusted nzb comic and issue: 0 day week of 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : comic_iss is : weekof
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : issue number seperated. Rejoining to complete comparison properly to : of
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : adjusting from: 0 day week of  to: weekof
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ['0', 'day', 'week', 'of'] nzb series word count: 2
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ['adam', 'strange', 'future', 'quest', 'special'] watchlist word count: 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitst : 2
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : len-watchcomic : 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : incorrect comic lengths after removal...not a match.
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : checking search result: Adam Strange Future Quest Special 01 (2017) 2 covers digital Minutemen Slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : sub:Adam Strange Future Quest Special 01 (2017) 2 covers digital Minutemen Slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : size given as: 63.8 MB
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Sat, 01 Apr 2017 21:54:45 +0000 is after store date of 2017-03-29
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Entry: Adam Strange Future Quest Special 01 (2017) 2 covers digital Minutemen Slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Cleantitle: adam strange future quest special 01 (2017) 2 covers digital minutemen slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Cleantitle: adam strange future quest special 01 (2017) 2 covers digital minutemen slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 0. Bracket Word: adam strange future quest special 01 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Comic: adam strange future quest special 01 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : UseFuzzy is  : None
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ComVersChk : 0
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 1. Bracket Word: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : year detected: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : year looking for: 2017
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 2017 - right years match baby!
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 2. Bracket Word:  2 covers digital minutemen slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : covers detected:  2 covers digital minutemen slayer cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : original nzb comic and issue: adam strange future quest special 01 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : adjusted nzb comic and issue: adam strange future quest special 01 
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : adjusting from: adam strange future quest special 01  to: 01
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ['adam', 'strange', 'future', 'quest', 'special', '01'] nzb series word count: 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ['adam', 'strange', 'future', 'quest', 'special'] watchlist word count: 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitst : 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : len-watchcomic : 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : length match..proceeding
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : search-length: 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Watchlist-length: 5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit: adam
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount : 0
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 0 Comparing: adam .to. adam
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : word matched on : adam
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit: strange
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount : 1
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 1 Comparing: strange .to. strange
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : word matched on : strange
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit: future
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount : 2
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 2 Comparing: future .to. future
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : word matched on : future
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit: quest
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount : 3
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 3 Comparing: quest .to. quest
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : word matched on : quest
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit: special
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount : 4
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : 4 Comparing: special .to. special
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : word matched on : special
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : scount:5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : splitit-len:5
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Match to series : 100.0 %.
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : it's a go captain... - we matched 100.0%!
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : this should be a match!
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : issue we are looking for is : 1
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : integer value of issue we are looking for : 1000
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : issue we found for is : 01
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : integer value of issue we have found : 1000
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : nzbname used for post-processing:Adam.Strange.Future.Quest.Special.01.(2017).2.covers.digital.Minutemen.Slayer.cbr
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : issues match!
02-May-2017 13:14:12 - INFO    :: Thread-15 : Found Adam Strange/Future Quest Special (2017) issue: 1 using TPSE
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : link given by: TPSE
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : ComicName:Adam Strange/Future Quest Special
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : link:59473003519A47AECD332F6D8368586D7AB108CE
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : Torrent Provider:TPSE
02-May-2017 13:14:12 - INFO    :: Thread-15 : matched on Adam Strange/Future Quest Special
02-May-2017 13:14:12 - DEBUG   :: Thread-15 : filename for torrent set to : D:\Media\Unsorted Media\_Downloads\Adam_Strange-Future_Quest_Special_1_2017.torrent
02-May-2017 13:14:13 - DEBUG   :: Thread-15 : Grabbing torrent from url:http://torrentproject.se/torrent/59473003519A47AECD332F6D8368586D7AB108CE.torrent
02-May-2017 13:14:13 - DEBUG   :: Thread-15 : [TPSE] Saved torrent file to : D:\Media\Unsorted Media\_Downloads\Adam_Strange-Future_Quest_Special_1_2017.torrent
02-May-2017 13:14:13 - ERROR   :: Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files (x86)\mylar\mylar\webserve.py", line 1450, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
  File "C:\Program Files (x86)\mylar\mylar\search.py", line 259, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
  File "C:\Program Files (x86)\mylar\mylar\search.py", line 1608, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "C:\Program Files (x86)\mylar\mylar\search.py", line 2244, in searcher
    rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
  File "C:\Program Files (x86)\mylar\mylar\rsscheck.py", line 1091, in torsend2client
    torrent_info = helpers.get_the_hash(filepath)
  File "C:\Program Files (x86)\mylar\mylar\helpers.py", line 2856, in get_the_hash
    metainfo = bencode.decode(torrent_file.read())
AttributeError: 'module' object has no attribute 'decode'

**Comment by evilhero** [comment]
Awhile ago the bencode.py module was moved from the mylar/ subdirectory into the lib/ directory - and on some systems (for whatever reason), it's leaving the pyc file behind which is what is being used in this case. So the fix, is to just delete the bencode.pyc file from the mylar/ subdirectory (if you see a bencode.py file you should delete that too, although it should have been removed automatically by git if you're on a semi-recent update and moved into the lib/ subdirectory).

**Comment by JaBaine** [comment]
that did it thanks
