### ISSUE TITLE
Errors when doing force check

### ISSUE THREAD

**Issue by edasque** [evilhero/mylar#1632]
```python
Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1728, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 701, in NZB_SEARCH
for entry in bb['entries']:
TypeError: string indices must be integers, not str
```

Any idea why this errors out?

**Comment by evilhero** [comment]
What's the provider being used, and is there any message prior to this in the logs indicating a timeout or something similar? 

It's saying basically there were no results, but normally it handles such a response with no problems - which makes me think it's either an indexer related problem or something similar perhaps.

**Comment by edasque** [comment]
Well, the issue seems to be that the UI is updating the config in problematic ways and maybe there is configuration information beyond config.ini.

For example where does this come from:

search provider order is ['newznab:NZBGeek', '', '', 'newznab:NZBGeek', 'dognzb', 'Experimental']

I'll try to disable newznab again but this has caused the original problem in the past.

**Comment by edasque** [comment]
Yeah that resulted in:

You have a blank newznab entry within your configuration. Remove it, save the config and restart mylar to fix things. Skipping this blank provider until fixed.

And this:

search provider order is ['', '', 'dognzb', 'Experimental']

And this on force check:

```
Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1728, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 701, in NZB_SEARCH
for entry in bb['entries']:
TypeError: string indices must be integers, not str
```

**Comment by edasque** [comment]
I edited by hand the config.ini with Mylar closed which seemed to improve things. We will see if force check finally downloads a lot of the old issues it missed during RSS feed processing at the time.

**Comment by evilhero** [comment]
Anytime you make a provider change of any kind you need to save the config and restart mylar. Failure to do this will give you the '0 search providers' error and cause other weird problems that can't be duplicated usually very reliably. 

You also cannot edit the config.ini with mylar running as mylar writes to it at various times, and if it writes to the config.ini before you can restart mylar (so that it can load the new values otherwise it has no way of knowing the changes), it will hammer any changes and overwrite them.

**Comment by edasque** [comment]
Thank you. After cleaning up the config while Mylar was shut down and starting again, the force check downloaded a lot of back issues it missed at the time during RSS checks.
