### ISSUE TITLE
Error when using "Force Check" in Wanted Tab

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1639]
Mylar Install Details:
Configuration Options
Mylar Version: development
-- git build d70eab5a4aee38e1eeaca49c66943bad46101fa0.
Python Version : 2.7.12

Error in Log (Debug enabled):
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/search.py", line 1727, in searchforissue
for result in sorted(results, key=itemgetter('StoreDate'), reverse=True):
NameError: global name 'itemgetter' is not defined

Nothing else appears in the log except for "Initiating Search scan at the scheduled interval of 360 minutes."

**Comment by evilhero** [comment]
Yep stupid mistake on my part where I forgot to import the module initially. Fixed in latest dev as well as corrected an invalid sort key - thanks for the quick heads up!

**Comment by BenBeyond** [comment]
Uodated to newest dev, but it seems the new sort key is causing a new error...

Error in log:
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/search.py", line 1728, in searchforissue
for result in sorted(results, key=itemgetter('ReleaseDate'), reverse=True):
KeyError: 'ReleaseDate'

**Comment by evilhero** [comment]
Ugh yeah that was my mistake... Incorrect key reference that I thought was wrong initially. Fixed now - thanks again for the quick heads-up!

**Comment by BenBeyond** [comment]
All good now! Thanks a ton, really love Mylar!
