### ISSUE TITLE
Request - Ability to have multiple destination directories

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1642]
Running out of storage space on drive 4TB drive looking to split collection between 2 hard drives without raiding.

**Comment by evilhero** [comment]
You can already do this - set the multiple_destination_directories option in the config.ini to the full path of where the new comic location is. 

Mylar will still monitor all your comics in the old comic location, and will create directories in the new comic location as required (if you have more than one of the same issue in both locations, mylar will not count it twice). 

Post-processing will send everything to the comic location path that's specific in the GUI. So in your case, you probably want to set your multiple_destination_directories to your old location, and the comic location to your new path.

**Comment by F688** [comment]
Thanks, so can I move lets say all the Marvel\ folder to the new drive. Redirect the comic series in Mylar to this new drive and then Mylar will sort Marvel comics to the new and the other service to the old drive? FYI, the processing speed is awesome now.

**Comment by F688** [comment]
Any suggestion on converting to webp?

**Comment by evilhero** [comment]
Set multiple_dest_dirs to your D:/Comics/ and the destination_dir to the path on your new hdd. It will replicate folders as required into the new path, but monitor both locations for content. You wouldn't have to move anything unless you wanted to, mylar should create a Marvel/ folder beneath your new path and the subsequent series as they are refreshed / added. 

I haven't revisited it in a long time, but it should still be working as expected (aside from creating empty directories in your new path when it's refreshing a series, as it creates the directory for new content, but all of the old content is in the other location)

**Comment by F688** [comment]
Thanks, just look for a solution to fit my preferences. I use Ubooquity as a server and was concerned about navigating between two or more directories to get to one series when my hard drive fills up. I ask about webp because it reduces file size without quality loss, I found a convertor (CbxConverter) which reduces the files be 50%. You can read webp formated .cbz files with Ubooquity, but it converts it to jpeg so there is a delay when loading each page, so webp is not an option at this stage. I will look into swapping my drive to larger hard drive. Thanks for the feedback as always.
