### ISSUE TITLE
NGinX setup for reverse proxy

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1644]
Struggling with this - http_root is set to /mylar and my location clause in my nginx site is below. I see a 302 in the nginx access log (no error), nothing in the Mylar logs (even at debug), no issue with http://host:9093/mylar, but the page redirects to http://reverseproxy/mylar/home, and I get a blank screen... any ideas?

```
location /mylar {                                                                                                             
    proxy_pass http://host:9095/mylar;                                                                        
    proxy_set_header Host $host;                                                                                                
    proxy_set_header X-Real-IP $remote_addr;                                                                                    
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                                                
    proxy_set_header X-Forwarded-Proto $scheme;                                                                                 
    auth_basic "Access Restricted";
    auth_basic_user_file "/etc/nginx/.htpasswd";
    access_log /var/log/nginx/mylar.access.log;
    error_log /var/log/nginx/mylar.error.log;
  }
```

**Comment by evilhero** [comment]
My nginx-fu isn't that great, but the port you're tagging in the location isn't the same as what you mention in your description (9093 vs 9095), and I had thought that you need to put the 127.0.0.1:9095 instead of just declaring a value for host (that might not even exist as $host in the proxy_pass setting).

**Comment by barbequesauce** [comment]
Yeah, the port number was a typo as I was writing the issue... ignore that...

I've noticed that my config works fine with CP & SG; Mylar, HP, and LazyLibrarian all have the same problem (I guess their codebases and dependencies are more similar), for what that's worth.

What I've noticed is that when Mylar/HP/LL come back from the reverse proxy their initial page (e.g. https://reverse.proxy.com:44333/mylar) is fine; there seems to be an immediate redirect to /<http_base>/home in all three apps, and that redirect seems to strip the web server port (44333) from the proxy server URL. Not sure why just yet...

**Comment by davalanche** [comment]
I have had Mylar behind nginx for a maybe a year now.. It's been a while since I've needed to look at the config for it but maybe try:

proxy_set_header Host $host:$server_port;

Instead of:

proxy_set_header Host $host;

**Comment by barbequesauce** [comment]
Thanks. This has put me down an interesting track of how cherrypy rewrites urls... learning a lot...

**Comment by barbequesauce** [comment]
So I've figured out what's happening - I'm leaning towards calling it a site-specific configuration. So, I'll leave a workaround here for posterity...

To fully explain the situation: 

1. client-side, I'm connecting to the nginx server over https (https://web.proxy.com)
2. client-side, I'm clicking a relative link on the home page (https://web.proxy.com/mylar)
3. nginx-side, that link is reverse-proxied to mylar's http server (*** not https ***)(http://internal.server.local:9095/mylar)
4. mylar-side, mylar rebuilds the URL from the config before cherrypy is first initialized - without http, since https is not enabled on my mylar server by design (/opt/mylar/mylar/webstart.py, starting on line 51)
5. mylar-side, responses are then sent to nginx using that rebuilt URL instead of the URL being called by nginx
6. nginx-side, the host is rewritten out of the URL... but http is left in place instead of changing to https

My solution was to add a proxy_redirect to my nginx config, telling nginx to look out for http URLs and make them https.
```

  location /mylar {
    proxy_pass http://internal.server.local:9095;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect http:// https://;
    auth_basic "Access Restricted";
    auth_basic_user_file "/etc/nginx/.htpasswd";
    access_log /var/log/nginx/mylar.access.log;
    error_log /var/log/nginx/mylar.error.log;
  }
```
