### ISSUE TITLE
wish for new feature, support for Synology DS Station download client

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#1651]
Right now I use a Watch dir to get my Synologys DS Station to download. Other programs similar to Mylar, like sickbeard, have the possibility to choose  DS Station as a download client.
DS station is build on Transmission, so it would probably be quite easy to implement it in a similar fashion.

**Comment by evilhero** [comment]
I honestly don't see this happening anytime soon. I don't have a synology to test against and I don't have the time to dedicate to just best guesses as to what will work vs what won't plus all the innards that have to be linked into mylar, which is most of the grunt work. 

I'd accept a PR, but don't think I'd be doing this myself atm at least.
