### ISSUE TITLE
all issues in weekly pulllist are "wanted"

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1654]
since last week all issues in my pull list/weekly list are always "wanted" even though not all are downloaded.

I'm currently on Master version 48d4d871972139654a85c1a6d137fa29736f5859 on a windows machine.

**Comment by evilhero** [comment]
What is your alt_pull method set to (in the config.ini)? 

Have you tried to do a recreate pullist to see if that fixes things at all? 

Are the issues failing during post-processing or file-checking where they aren't being marked as Downloaded?

**Comment by HypKin** [comment]
currently to 0.

yes i tried to recreate it - no doesnt fix it

not sure about your third question, didn't look at it into too much detail until now.


i happenend to have a little problem with the mylar cache  that completly filled my harddisk and after that my config.ini was reset to all defaults. so i'm not really sure at the moment how to answer your third question haha.

**Comment by evilhero** [comment]
Yeah full HD would probably mean the dB wouldn't be able to be written to, so the status would never change. 

There was a fix that went into dev a few commits ago pertaining to cache folder cleanup on failed post-processing runs (think it was probably you that brought forth the initial problem). I plan on putting in some other removal-type stuff for the cache, but that pertains to removing .torrent files. Was the cache full of metatagging folders again? 

You should probably set you alt_pull to 2 (with mylar not running) to take advantage of, well everything. Srsly, alt_pull 0 works and it's fine for an initial / default type of setup, but to leverage what mylar is able to do using alt_pull 2 sheds more light on the situation ;)

**Comment by HypKin** [comment]
ok, i think i know what happenend, I started an update on mylar from the web frontend with full harddisk and 0 space left. after a few tries the config.ini was reset to the default settings. thats... not so good haha.
