### ISSUE TITLE
Not using usenet indexers

### ISSUE THREAD

**Issue by atytel** [evilhero/mylar#1657]
Mylar refuses to use usenet indexers and will only search with torrent indexers.

**Comment by evilhero** [comment]
Need more info - mylar works perfectly fine with indexers and torrents combined. If you added a provider or made a provider change (such as adding/enabling /disabling), you need to make sure that you save the config and restart mylar for the changes to take effect. Not doing this will screw up the provider order sequence thats generated on startup only which mylar uses to prioritize indexers for searches.

**Comment by dudeslife** [comment]
I am having the same problem. I havent made any mods to my indexers. the logs don't show anything unusual. It just isn't finding them.

**Comment by thingdeux** [comment]
@atytel - Please verify you're still seeing this issue or provide logs.  If not, please close it out.
