### ISSUE TITLE
	[IMPORT] Unable to complete the scan: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by atytel** [evilhero/mylar#1661]
Title.
Please help this happens when trying to use the scan feature

**Comment by evilhero** [comment]
Ok, you need to provide more info than just 'title.' Provide a debug log / more detailed information or else I can't help at all. 

Check your logs (after putting mylar into verbose mode), and see what is actually happening when you hit the error and then paste in from the start of the  scan to the error in detail.
