### ISSUE TITLE
Can't add comic - Invalid Numeric issue

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#1662]
This is the error I'm getting. The comic remains with no issues listed:

24-Jun-2017 16:01:40 - INFO    :: Thread-15 : Now adding/updating issues for Civil War II
24-Jun-2017 16:01:40 - DEBUG   :: Thread-15 : [] invalid numeric for issue - cannot be found. Ignoring.
24-Jun-2017 16:01:40 - DEBUG   :: Thread-15 : this does not have an issue # that I can parse properly.
24-Jun-2017 16:01:40 - WARNING :: Thread-15 : Unable to complete Refreshing / Adding issue data - this WILL create future problems if not addressed.

This is the version I'm using:

Mylar Version: master
-- git build 48d4d871972139654a85c1a6d137fa29736f5859.
Python Version : 2.7.12

Other comics are added wit no issues. This is the first I found something similar. Any idea?

Thanks in advance.

**Comment by evilhero** [comment]
Are you trying to add the hardcover / tpb version of the series? If you are that will probably fail as mylar can only accurately track individual issues. The comicid you're trying to add is in the url of the series detail page - if it's anything other than  90521 then it's the non-issue versions.

**Comment by cesalo** [comment]
I was trying to add: https://comicvine.gamespot.com/civil-war-ii/4050-99010/
It's listing 8 issues so I thought was good.
I've found the one you said and that worked fine.
Thanks a lot for your help.

**Comment by evilhero** [comment]
Yeah Panini is marvel's French publication name. Normally it's not a problem, but it looks like they actually have the last issue as #day instead of #8 for some weird reason. If you don't want to see any Panini published comics when you search, you can add 'panini comics' to the balcklisted_publishers field in the config.ini and it won't display them as an option anymore.

**Comment by cesalo** [comment]
Thanks a lot for the help.
