### ISSUE TITLE
Search failing, "foundNZB" - but I don't have any NZB providers

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1663]
So I've finally found time to troubleshoot why things aren't clicking. Turns out there's an error when searching for Batman 25. No idea what's causing it... I found it interesting that it seems to be in a function called "foundNZB", as I'm only using torrents... but I haven't dug into the code to see if the name is a red herring.

Log file [here](https://gist.github.com/barbequesauce/2e6944bd670faa930ee5d9890aaed92d)... any help is appreciated!

**Comment by evilhero** [comment]
Heh, yeah don't pay too much attention to the naming - when I started coding things I was just concentrating on usenet, so named everything after that. When the switch to torrents came, I left all the already named items as is - which in looking back wasn't a great idea but that's where it kinda stands now. The foundnzb if I recall just holds a tuple containing information about the snatched item or if nothing was found, the nothing result. 

It actually looks like it's erroring out on doing the timestamp conversion that's used to compare the posting date of the file to the store date of the issue to see if it's a valid release. I can't tell for sure from the log, but is it from wwt / dem / TPSE? Some of those feeds don't have a proper timestamp and it messes up the calcs.

**Comment by barbequesauce** [comment]
Your guess is as good as mine -it could be any of those...

**Comment by evilhero** [comment]
Well it should say just above that where it does the ```shhh...I'm searching for``` kinda line - it should say the provider it's going against which would be TPSE since within Mylar it's all encompassing, but then after that line it should say something like ```[TPSE] there were 15 results...```.

**Comment by barbequesauce** [comment]
I keep missing it in the logs while in debug...

But I think this might be related?

25-Jun-2017 08:05:01 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Check.
25-Jun-2017 08:05:01 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Feed Check on TorrentProject.
25-Jun-2017 08:05:10 - DEBUG   :: RSSCHECK : Exception generated in thread RSSCHECK: could not convert string to float: s  | Super Hero | English | 638.85
25-Jun-2017 08:05:10 - DEBUG   :: RSSCHECK : 'Traceback (most recent call last):\n  File "/opt/mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/opt/mylar/mylar/rsscheckit.py", line 62, in run\n    rsscheck.torrents(pickfeed=\'TPSE\')    #TPSE = DEM RSS Check + WWT RSS Check\n  File "/opt/mylar/mylar/rsscheck.py", line 260, in torrents\n    \'size\':     helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz)),\n  File "/opt/mylar/mylar/helpers.py", line 174, in human2bytes\n    assert float(num) and letter in symbols\nValueError: could not convert string to float: s  | Super Hero | English | 638.85\n'

**Comment by barbequesauce** [comment]
Aha! finally captured it... sorry it's backwards, I had to use the web interface as the log file was... unwieldy...

```
2017-06-25 08:51:52	DEBUG	Sending request to [TPSE] RSS for Batman : 025
2017-06-25 08:51:52	DEBUG	calpha/cnumber: None / None
2017-06-25 08:51:52	INFO	Shhh be very quiet...I'm looking for Batman issue: 25 (2017) using TPSE [RSS]
2017-06-25 08:51:52	DEBUG	Initiating Search via : rss
2017-06-25 08:51:52	INFO	search provider order is ['tpse']
2017-06-25 08:51:52	DEBUG	provider order sequence is now to start with tpse at spot #1
2017-06-25 08:51:52	DEBUG	torrent provider found: tpse
2017-06-25 08:51:52	DEBUG	checking against torrent provider: tpse
2017-06-25 08:51:52	DEBUG	found provider in existing enabled providers.
2017-06-25 08:51:52	DEBUG	Usenet Retention : 1500 days
2017-06-25 08:51:52	DEBUG	there are : 0 nzb providers you have selected.
2017-06-25 08:51:52	DEBUG	there are : 1 torrent providers you have selected.
2017-06-25 08:51:52	DEBUG	nzbprovider(s): []
2017-06-25 08:51:52	DEBUG	Checking for torrent enabled.
```

**Comment by evilhero** [comment]
Ok, it looks like it's actually failing on the parsing of the demonoid rss feed due to how the size of the torrent is being presented. I'll see if I can work out something to fix this, as in looking at this abit more it looks like they changed the format of the feed (again), so the parser is mixing up the results and taking the entire line instead of just the filesize...

**Comment by barbequesauce** [comment]
#1667 seems to have fixed my problem. Thanks for that, and thanks for a great product with great support!

**Comment by evilhero** [comment]
Sorry my bad ;) I only quickly glanced at the one issue where it was mentioned and didn't scroll down.
