### ISSUE TITLE
Ability to add multiple Torznab

### ISSUE THREAD

**Issue by stitchemd** [evilhero/mylar#1665]
I'd like to request the ability to add multiple TorzNab addresses.

**Comment by evilhero** [comment]
It's on the road map of things, but other items of more pressing nature are being dealt with first. Hopefully before the end of next month it should be in place (I hope).

**Comment by cesalo** [comment]
Could Jackett help here? maybe .. not sure what is needed.

**Comment by barbequesauce** [comment]
I've asked them to support WWT previously and they've indicated they have enough public trackers already; that said, it should work to get torrents from other sites.

**Comment by cesalo** [comment]
I just updated: https://github.com/Jackett/Jackett/issues/1439
Hopefully they will finally do it.

**Comment by evilhero** [comment]
I think the problem, at least what the initial request was asking, was the ability to allow for more than one torznab entry within mylar. As it stands now, you can only have one entry, which means one torrent provider. 

@barbecuesauce : weird that they don't include it - but they still have an open request for it from less than a month ago labelled as an enhancement so it might get done at some point. There might also be forks of jackett that support WWT, although I don't know of any atm.

**Comment by hbooo** [comment]
Any news on this? It would be really helpful to be able to add several torznab

**Comment by evilhero** [comment]
I'll have to look into it again - I keep on forgetting to do it as other stuff pops up that requires near immediate fixes, and then it falls by the wayside for other things.
