### ISSUE TITLE
Metatagger fails to create temporary directory

### ISSUE THREAD

**Issue by timm088** [evilhero/mylar#1666]
Trying to understand this in the debug log

* I'm now running mylar in a Docker container, works well. However, I'm seeing an error when I attempt to metatag an issue.

Mylar _does_ create the folder, but bombs out at the file level .. Would this be because it can't move or copy the file?

> 28-Jun-2017 23:12:58 - DEBUG :: CP Server Thread-5 : CBZ file detected. Checking for .xml within file
> 28-Jun-2017 23:13:04 - DEBUG :: CP Server Thread-5 : [META-TAGGER] dirName:/home/comics/theComics
> 28-Jun-2017 23:13:04 - DEBUG :: CP Server Thread-5 : ComicTagger Path location for internal comictagger.py set to : /mylar/comictagger.py
> 28-Jun-2017 23:13:04 - DEBUG :: CP Server Thread-5 : [META-TAGGER] Filename is : TheComics/TheComic.cbz
> 28-Jun-2017 23:13:04 - INFO :: CP Server Thread-5 : Filepath: TheComics/TheComic.cbz
> 28-Jun-2017 23:13:04 - INFO :: CP Server Thread-5 : Filename: TheComic.cbz
> 28-Jun-2017 23:13:04 - INFO :: CP Server Thread-5 : New_Folder: /mylar/cache/mylar_7bnxMZ
> 28-Jun-2017 23:13:04 - INFO :: CP Server Thread-5 : New_Filepath: /mylar/cache/mylar_7bnxMZ/TheComic.cbz
> 28-Jun-2017 23:13:04 - INFO :: CP Server Thread-5 : Attempting to move: copy
> 28-Jun-2017 23:13:04 - WARNING :: CP Server Thread-5 : [META-TAGGER] Unexpected Error: <type 'exceptions.IOError'>
> 28-Jun-2017 23:13:04 - WARNING :: CP Server Thread-5 : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
> 28-Jun-2017 23:13:04 - DEBUG :: CP Server Thread-5 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.

**Comment by evilhero** [comment]
Weird how it has 'move:copy'... How exactly are you invoking the metatagging (ie. ComicRN, manual post-processing, manual metatagging)? 

Does the user running mylar have permission to copy/move from the original location, and does the user have permission to write/create in the cache location?

**Comment by timm088** [comment]
Above output is from a manual metatag run.

Some more details

* The setting for post-processing action was set to move, that gave the above error.
* I set to copy, and also get the same error as shown above. 
* I ran mylar in a docker container with a mounted NFS volume (the container can copy data from the comics directory anywhere)

**Comment by evilhero** [comment]
For some reason it's having problems copying / moving the file from the source to the destination. It could be permissions related, as it does a 'shutil.copy' which apparently copies the permission bits across so maybe it's having problems setting them to be identical. 

You're not out of space in the location where the cache folder is located (had to ask)? 

If you're familiar with Python you can try initiating it from the python cli: 
```
import shutil
shutil.copy(src,dst)
```
From within the mylar root directory, and it should throw the same error perhaps more verbatim - if it doesn't, then you know it's due to a user:group type of problem most likely.

**Comment by timm088** [comment]
Ok thanks @evilhero. Did some more digging

* not out of space (the containers have full access to system hard drive, which had 200+gb free)
* mylar has no trouble writing the database or config files (for what its worth)
* It runs fine in the python cli, i.e., can copy from the mounted volume to any local folder
* not sure where else the issue is with permissions, the UID, user:groups are exactly the same across the container, host and shared nfs

Where did you find the information about shutil? python doco?

**Comment by timm088** [comment]
Ok, problem solved. 

* Turns out, in my change to docker, I overlooked the fact that each comic has a directory set (that I guess its written to the mylar.db?)
* That location was wrong, so meta tagging was going to fail. Didn't notice it, had not done a recheck of files since moving to docker

Now that I've edited the comic location to match the new mounted location, all good, can meta tag.

Any way to bulk update these series locations?

**Comment by evilhero** [comment]
Ahhh ok well that's good that you figured it out in my absence (sorry too, Canada day here was an all day-event). 

As far as updating the other paths, you can check a forum post [url=https://forum.mylarcomics.com/viewtopic.php?f=12&t=1784#p9353] here[/url] describing how to update it to the new location (just ignore the stuff where it says to backup/install as you just want to update the locations and it's a lengthy post). 

If you have any problems, just shout back and I'll help. 

While I remember - if you're doing the above method, make sure to change the Comic Location path in the GUI to the new location after you've completed the process described in that post.
