### ISSUE TITLE
config.ini corrupted, maybe?

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1675]
So, long story short I accidentally rm -rf my root. Yeah, I'm an idiot.

Luckily, my nightly dd's are saving my a** for 99.9999% of my stuff. However, it looks like mylar's config.ini is in a weird format during runtime though? I've tried pulling it back from two nightly dd's and it looks unreadable in both images.

Any way to recover? Alternately, how can I recreate without blowing away my database?

**Comment by HypKin** [comment]
depends on what you changed.

something similiar happenend to me a few weeks ago, but all i had to change where the differen paths to my files, the pull method and the branch.

i also had previously changed the way mylar should write the files, i added a # prior to the issue numbers, so i changed that layout too. and thats it.

**Comment by barbequesauce** [comment]
Thanks. Did you pull a "clean" one from github, or did mylar create a blank one after deleting and starting?

**Comment by HypKin** [comment]
mine got reseted to the clean/default one when i tried to update mylar but had a completly full harddisk... so i had something that was identical to the version you get after a fresh install.

**Comment by barbequesauce** [comment]
Yep, that worked. Now to dig up all my API keys...

Thanks.
