### ISSUE TITLE
clean install hell.

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1676]
So... 

```
sudo git clone https://github.com/evilhero/mylar.git
cd mylar
python Mylar.py
```
Brings me to...
```
Mylar Version: master
-- git build f9b08c6da681c1132c2305878af911ef3cf336db.
Python Version : 2.7.9
```
and a nagging "You are 52 commits behind", so I update. Debug shows a successful update and no nag screen:
```
Mylar Version: master
-- git build 442c3d936a781c379e4a8b882f36836a125c9e0e.
``` 
I'd rather be on development, so I shut it back down again and:
`git checkout development`
that gets me:
```
Your branch is ahead of 'origin/development' by 53 commits.
  (use "git push" to publish your local commits)
```
Okayyyy.... Start it back up and now the config screen shows:
```
Mylar Version: master
-- git build 442c3d936a781c379e4a8b882f36836a125c9e0e.
```

After some grumbling, I turn debug on and check version:
```
07-Jul-2017 15:30:41 - DEBUG :: CP Server Thread-3 : If you read this message, debug logging is available
07-Jul-2017 15:30:44 - INFO :: CP Server Thread-3 : Retrieving latest version information from github
07-Jul-2017 15:30:45 - DEBUG :: CP Server Thread-3 : Comparing currently installed version [442c3d936a781c379e4a8b882f36836a125c9e0e] with latest github version [48d4d871972139654a85c1a6d137fa29736f5859]
07-Jul-2017 15:30:45 - WARNING :: CP Server Thread-3 : Could not get commits behind from github
```

I can't make heads or tails of this. I've blown it away four times assuming I'm screwing  something up, and i still get the same results... any ideas why I can't get a clean dev branch running?

**Comment by evilhero** [comment]
Make sure mylar isn't running and set your git_branch to development in the config.ini. Start it up and then do the update if says you're behind and you should be good after that point as far as branch goes.

**Comment by barbequesauce** [comment]
You're the best, that worked like a charm. Thank you!
