### ISSUE TITLE
Uncaught Exception Local Variable 'rss" referenced before assignment

### ISSUE THREAD

**Issue by hir0pr0** [evilhero/mylar#1679]
Comics not downloading. When I manually search I get the error below.

I am using Sabnzbd with Dognzbd. It doesn't seem to matter if I have Experimental Search on or not.

I don't have a empty Newsnab as I saw was the reason for other similar issues before.

I am on the latest master: f9f992298b2a06207e6b39a39166d1d02792916b

Let me know if any more information would be relevant. 

Error:
15-Jul-2017 10:22:25 - INFO    :: Thread-16 : no errors on data retrieval...proceeding
15-Jul-2017 10:22:25 - ERROR   :: Thread-16 : Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files\mylar\mylar\webserve.py", line 1465, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
  File "C:\Program Files\mylar\mylar\search.py", line 263, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
  File "C:\Program Files\mylar\mylar\search.py", line 858, in NZB_SEARCH
    if all([nzbprov == '32P', dateconv is None, rss == 'no']):
UnboundLocalError: local variable 'rss' referenced before assignment

**Comment by hir0pr0** [comment]
Changing "rss" to "RSS" seems to solve the issue.

**Comment by evilhero** [comment]
Yep, can confirm - was a typo on my part. For some reason there was both 'RSS' and 'rss' variables which the 2nd one didn't have any purpose. Unfortunately I used the lower-case variable and didn't test it against an nzb provider - thus the error. Thanks for the headsup tho, commit up shortly into both dev & master to fix this one...

**Comment by hir0pr0** [comment]
No problem!
