### ISSUE TITLE
torrent watchfolder - nothing is post processed

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1684]
i'm using copy and rename with a watchfolder, but everything that got snatched today is not being post processed.

how do I efficently log this?

**Comment by evilhero** [comment]
Go to the Logs tab in the GUI, and enable verbose logging. Then let the folder monitor run at it's normal pace, and then you'll have the debug log and I can help troubleshoot things from that point better.

**Comment by HypKin** [comment]
its working now after 3 restarts of mylar...
