### ISSUE TITLE
Auto Update Mylar

### ISSUE THREAD

**Issue by hitnrun30** [evilhero/mylar#1686]
Is there a way that Mylar can auto update itself.  If I don't go to the site for a few days and there have been commits, i will see the little yellow box on the bottom and update.  I would rather it automatically do that.

**Comment by evilhero** [comment]
Auto-updating always opens up a big can of worms given how everyone runs it on different systems and such - maybe at some point, the logistics are in place for it, but it's nowhere near done nor ready to be used without being tested for reliability across different types of installs (ie. git, source, 3party, docker)
