### ISSUE TITLE
Mylar failing to update

### ISSUE THREAD

**Issue by PC001** [evilhero/mylar#1688]
Hi,

Thanks for a great product!

But :)

I'm not able to run an update. I get the following error;
`28-Jul-2017 12:49:51 - WARNING :: CP Server Thread-11 : Could not get commits behind from github`

Mylar is running on Ubuntu 16.04, latest patches just applied.

Thanks for your help!

**Comment by evilhero** [comment]
That can happen if either github is having problems, or you've hit github too quickly (some kind of ddos protection, but you have to have done it a few times farily quickly in a row) - it doesn't last very long however. 

Try shutting down Mylar - wait a few minutes and then try to start again, with any luck you should get past that prompt and be able to update (if you're behind that is).

**Comment by PC001** [comment]
Thanks for the prompt response - I meant to post back earlier :(

Anyway, I waited and tried again just now, but got the same result.
Are you able to run a github update ok?

**Comment by evilhero** [comment]
Yep, everything is working as expected - retrieves current git and commits behind just fine.

Have you tried just shutting down Mylar and doing a 'git pull' in the root of Mylar to see if anything comes back error-wise? I'm wondering if maybe one of the updates you mentioned might have changed something on your system that affects the git stuff (longshot, but hey you never know).
