### ISSUE TITLE
rename all?

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1689]
is there an option to rename all series at once? i changed my rename pattern and dont want to go through all of them :(

**Comment by evilhero** [comment]
No there isn't - although hindsight being 20/20 there really should be. I'll try and add in an option into the Manage Comics section where you can select mulitiple series with a mass rename option (have to test it out abit, but shouldn't be too difficult as the functions already exist)

**Comment by HypKin** [comment]
just may be a problem with the execution time? id guess trying to rename 10000 issues for example could take a few minutes to take effect so youÄd probably need to halt everything else?

**Comment by baz1860** [comment]
Was this ever implemented? I've had a look in the 'Manage Comics' section, and can't find that option and as I've jest changed my naming pattern, it'd be a godsend right now!

**Comment by evilhero** [comment]
Sorry, the code was present (and probably was for awhile I'd wager) - but the option was never added to the GUI dropdown. I'm guessing it was due to lack of testing, but here's the chance to test things out...

**Comment by baz1860** [comment]
Testing in progress now - thank you!

**Comment by baz1860** [comment]
Ok, Its working perfectly with one small caveat: The number of issues of any individual comic being renamed isn't zeroed after renaming - as you can see by the number of Gotham Academy: Second Semester comics that have apparently been renamed...

2018-03-02 21:22:32 | INFO | I have renamed 2157 issues of Gotham Academy: Second Semester

**Comment by evilhero** [comment]
Counts should be in line now - just a silly mistake on my part ;)
