### ISSUE TITLE
Getting the following error when trying to download

### ISSUE THREAD

**Issue by Cwis3man** [evilhero/mylar#1691]
File "/opt/mylar/mylar/logger.py", line 165, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/search.py", line 1785, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/opt/mylar/mylar/search.py", line 243, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff)
File "/opt/mylar/mylar/search.py", line 1626, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/opt/mylar/mylar/search.py", line 2266, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
File "/opt/mylar/mylar/rsscheck.py", line 1163, in torsend2client
torrent_info = helpers.get_the_hash(filepath)
File "/opt/mylar/mylar/helpers.py", line 2944, in get_the_hash
metainfo = bencode.decode(torrent_file.read())
AttributeError: 'module' object has no attribute 'decode'

**Comment by evilhero** [comment]
In the mylar subdirectory there's a bencode.py file, and/or a bencode.pyc file that shouldn't be there. 

Make sure Mylar isn't running, then delete both the bencode files, as well as deleting all the .pyc files in the mylar subdirectory. Start it back up and you'll be good to go. 

The bencode module got moved into the /lib folder awhile ago, but for some reason it's leaving the .pyc file in its old location which it tried to use wrongly.

**Comment by Cwis3man** [comment]
I'm using a docker version of Mylar- I guess the docker would have to be updated to have this fixed.

**Comment by evilhero** [comment]
Shouldn't matter.. Docker still uses the same files - it's just some weird glitch with git and not cleaning up all the files for some reason. Most dockers pull a clean git clone/pull on startup, and deleting the .pyc files are just runtime versions of the .py files which are safe to delete as they get regenerated on startup.

**Comment by Cwis3man** [comment]
I was able to get into the docker and try to see what's going on. 

```
root@a495205e2253:/app/mylar/mylar$ ls
Failed.py          api.py          comicbookdb.pyc  dbupdater.pyc      ftpsshup.pyc  librarysync.py   mb.py        notifiers.py     rsscheck.py     scheduler.pyc  test.py       version.py          webserve.py     weeklypullit.py
Failed.pyc         auth32p.py      cv.py            filechecker.py     helpers.py    librarysync.pyc  mb.pyc       notifiers.pyc    rsscheck.pyc    search.py      torrent       version.pyc         webserve.pyc    weeklypullit.pyc
PostProcessor.py   auth32p.pyc     cv.pyc           filechecker.pyc    helpers.pyc   locg.py          moveit.py    parseit.py       rsscheckit.py   search.pyc     updater.py    versioncheck.py     webstart.py
PostProcessor.pyc  cache.py        db.py            findcomicfeed.py   importer.py   locg.pyc         moveit.pyc   parseit.pyc      rsscheckit.pyc  searchit.py    updater.pyc   versioncheck.pyc    webstart.pyc
__init__.py        cmtagmylar.py   db.pyc           findcomicfeed.pyc  importer.pyc  logger.py        newpull.py   readinglist.py   sabparse.py     searchit.pyc   utorrent.py   versioncheckit.py   weeklypull.py
__init__.pyc       comicbookdb.py  dbupdater.py     ftpsshup.py        latest.py     logger.pyc       newpull.pyc  readinglist.pyc  scheduler.py    solicit.py     utorrent.pyc  versioncheckit.pyc  weeklypull.pyc
```

There were no Benecode files in there, I did however delete all the .pyc files and start again, but I'm still receiving the same error.

**Comment by evilhero** [comment]
Have you tried using it without the blackhole method (like sending directly to the torrent client via one if the options in the configuration)?
