### ISSUE TITLE
Mylar losing configuration settings

### ISSUE THREAD

**Issue by tctx79** [evilhero/mylar#1692]
Hello,

I am dealing with a recurring issue where all of my configuration changes will completely be wiped out and revert to the original settings.  Has this happened to anyone else?  I had thought it might be something to do with the update checking github and pulling an updated/new config.ini for some reason and resetting the config file, but that doesn't really make any sense.

Very frustrating...I will have Mylar up and running great, then it hiccups and all of a sudden when I check the config settings it's back to blank fields..
**edit**
Forgot to add that I have tried both master and development branches, and run it with and without the full path to git.exe.  I'm probably doing something wrong or out of order but I've not been able to come up with a solution by searching the issues.

**Comment by evilhero** [comment]
Sounds like the config.ini file is set to read only, or the user running mylar doesn't have enough permissions to save to the file. 

Mylar doesn't pull down a new config.ini like ever - it generates a clean one if it can't find one in the location it's supposed to be in. 

So check the perms, make sure thr config.ini has proper write access and it should work.

**Comment by tctx79** [comment]
So being that I am running this on windows 10, the user running it is a local admin account, and properties of config.ini show full access' can you suggest where I might be missing something?

**Comment by evilhero** [comment]
How exactly are you starting mylar? As how it's started, might dictate the permissions being used, or what it can do to files.

**Comment by tctx79** [comment]
I am double clicking on the Mylar.py file from windows explorer.  Do I need to be right-clicking and running as administrator?

**Comment by evilhero** [comment]
No you can't double click on the file to run it since it's not an executable. Either rebate the Mylar.py to Mylar.pyw (which you could then double click), or set it up to run as a service via a windows script (if you google 'mylar vbs startup script' you should find the info on how to set it up).

**Comment by tctx79** [comment]
Well just FYI you can actually double click the .py file from windows explorer and it does open and run the program.  Same with headphones and lazylibrarian.

**Comment by evilhero** [comment]
It runs, but it suppresses output and will cause errors in a program that calls external modules using subprocess (like mylar does a few times), or it encounters a traceback  error. Once it encounters the error, it has no where to send the error output to so it dies (as there is no active window for it to send it to). So, you really shouldn't be double-clicking on a .py file (double-clicking on a .pyw file will work however). 

Check the mylar.log file and see what the last log line was before it dies and that might help (if you're not restarting mylar after you save the config, that would cause problems when searching).

**Comment by tctx79** [comment]
Ahh ok that makes sense.  I do restart after confit changes, but had no idea I was causing my own problems running it by double clicking.  Thank,you!

So really should I be starting this from the command line by just typing python mylar.py ?

**Comment by evilhero** [comment]
Well command line is recommended just so that if it errors you'll see it immediately in the console it runs in (some errors don't get logged depending on what type of error it is), but using a .vbs script to start it and run it in the background is what alot of people use (so there's no window open on the desktop) with success. 

Personally when I use it on a Windows machine I just run it via git shell (basically a dos prompt but can use git commands natively), but I also don't leave it running as I only test stuff on it for the most part.
