### ISSUE TITLE
Error 500 on home page

### ISSUE THREAD

**Issue by tomtom602** [evilhero/mylar#1693]
Hi, 
I've got this problem since yesterday.
On the home page or the manage comics page, the error come from the same problem for what I could see.

this is the detail of the error :
 Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "/opt/Mylar/mylar/helpers.py", line 1329, in havetotals
    c_date = datetime.date(int(latestdate[:4]), int(latestdate[5:7]), 1)
ValueError: invalid literal for int() with base 10: 'Unkn'

with the "text" changing from 'Unkn' to 'None'
I opened the data base and did the request that is done in this code.
what I se is that I have 2 comics that have a weird LatestDate:
- mister miracle #1 --> Unknown-Unknown-01
- x men blue 9 --> None

If I edit the DB for those 2 lines, then the home page become accessible anew.
but when those comics are refreshed, the error come back.

when checking the logs I see two lines in error that seem to correspond to my problem :

2017-08-10 05:21:05 | ERROR | Invalid Latest Date returned for X-Men: Blue. Series needs to be refreshed so that is what I am going to do.
-- | -- | --
2017-08-10 05:19:45 | ERROR | Setting Latest Date to be 2017-01-01. You should inform CV that the issue data is stale.

hope you can resolve that problem

FYI : the problem doesn't seem to block mylar in any other way, the other pages are accessible (with URL modification) and my comics are being grabed.

**Comment by evilhero** [comment]
Not quite sure what's going on in your particular case, x-men blue doesn't have an issue 9 in it as of yet so I'm at a loss as to how it's saying it's the latest issue/date. 

I would try to remove both series from Mylar and then try to readd them.  

I added both to test, and both came in clean with no errors, aside from the fact that the 1st issue of Miracle had an issue date of 0000-00-00 which would clean up itself eventually (that's CV's fault for not posting the date, but you can edit the date within Mylar by just clicking on the date in the pub date column of the series page, and putting in the street date of the given issue: 2017-07-09).

**Comment by tomtom602** [comment]
Hello,
thank you for you response.
deleting and readding the comic have corrected the issue. thanks.

thank you for all your work on that awesome tool :)
