### ISSUE TITLE
Uncaught Exception when Refreshing or Adding Series

### ISSUE THREAD

**Issue by JacksonB** [evilhero/mylar#1694]
It looks like some of the series listed on Comicvine have been edited to have a date range or more than just a single number for the year.

[Example here](https://comicvine.gamespot.com/batman/4050-91273/)

This causes Mylar to throw an exception when refreshing the series or adding a series with the following error:

```10-Aug-2017 07:49:54 - INFO    :: Thread-14 : Now adding/updating: Batgirl    
10-Aug-2017 07:49:54 - INFO    :: Thread-14 : 2016-                           
10-Aug-2017 07:49:54 - ERROR   :: Thread-14 : Uncaught exception: Traceback (m
ost recent call last):                                                        
  File "/opt/mylar/mylar/logger.py", line 165, in new_run                     
    old_run(*args, **kwargs)                                                  
  File "/usr/lib/python2.7/threading.py", line 763, in run                    
    self.__target(*self.__args, **self.__kwargs)                              
  File "/opt/mylar/mylar/importer.py", line 171, in addComictoDB              
    if any([int(SeriesYear) > int(datetime.datetime.now().year) + 1, int(Serie
sYear) == 2099]) and csyear is not None:                                      
ValueError: invalid literal for int() with base 10: '2016-'
```

I’m not sure of the reasoning to the change nor am I familiar enough with Comicvine to determine if I can edit it back (or even if I’m able to). So far I’ve only seen it on Batman and Batgirl 2016 but those were just quick spot checks.

So ultimately I’m not sure if this should be corrected from Mylar’s or Comicvine’s side.

**Comment by evilhero** [comment]
Crap, yeah it looks they're doing something again with the listing with no notice :/

Mylar uses the start date (which is what the 2016- now is) in a calculation to determine if a series is running or ended - which looks like now its causing problems cause they're doing the range. 

I'll have to look into this more as there are some series that work fine, and others don't - so it's not going to be a mass overhaul and I'll have to account for both methods now which makes it really tricky. 

You can edit it back in cv, but I'm not sure if non-staff can change a series year Ike that, or why it was even changed in the first place (aside from someone thinking they could do it for their own needs and screw it up for more than just mylar users lol)

**Comment by JacksonB** [comment]
I went through his history and submitted corrections to the less than 10. Hopefully it is just the one user that it stops there.

**Comment by evilhero** [comment]
Looks like those corrections you did were applied and fixed before I could get the commit out (sorry personal commitments). I pushed it anyways, just in case it happens again, it shouldn't cause any errors in regards to adding/refreshing both series and story arcs.

Thanks for doing a hands-on fix yourself, and providing all the necessary info as well :)
