### ISSUE TITLE
Metadata Tagging not working anymore

### ISSUE THREAD

**Issue by sifu36** [evilhero/mylar#1696]
Hi!
Somehow tagging is not working anymore for manual tagging and new downloads.
Although log says "Successfully wrote metadata", there is no xml file is available in the file.
I'm running the latest development branch on Debian, Python 2.7.13

python comictagger.py --version
ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN]
Modified version of ComicTagger (Copyright (c) 2012-2014 Anthony Beville)

12-Aug-2017 11:12:25 - DEBUG   :: CP Server Thread-5 : CBZ file detected. Checking for .xml within file
12-Aug-2017 11:12:26 - DEBUG   :: CP Server Thread-5 : Extracting primary image comic 066-000.jpg as coverfile for display.
12-Aug-2017 11:12:26 - WARNING :: CP Server Thread-5 : No metadata available in zipfile comment field.
12-Aug-2017 11:12:33 - DEBUG   :: CP Server Thread-5 : CBZ file detected. Checking for .xml within file
12-Aug-2017 11:12:33 - DEBUG   :: CP Server Thread-5 : Extracting primary image comic_001_(1995)/comic 001-000.jpg as coverfile for display.
12-Aug-2017 11:12:33 - WARNING :: CP Server Thread-5 : No metadata available in zipfile comment field.
12-Aug-2017 11:12:49 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] dirName:/mnt/comics/Comics/Vertigo/comic_(1995)
12-Aug-2017 11:12:49 - DEBUG   :: CP Server Thread-6 : ComicTagger Path location for internal comictagger.py set to : /home/ds/.mylar/comictagger.py
12-Aug-2017 11:12:49 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Filename is : /mnt/comics/Comics/Vertigo/comic_(1995)/comic_001_(1995).cbz
12-Aug-2017 11:12:49 - INFO    :: CP Server Thread-6 : Filepath: /mnt/comics/Comics/Vertigo/comic_(1995)/comic_001_(1995).cbz
12-Aug-2017 11:12:49 - INFO    :: CP Server Thread-6 : Filename: comic_001_(1995).cbz
12-Aug-2017 11:12:49 - INFO    :: CP Server Thread-6 : New_Folder: /home/ds/.mylar/cache/mylar_pxJ5z7
12-Aug-2017 11:12:49 - INFO    :: CP Server Thread-6 : New_Filepath: /home/ds/.mylar/cache/mylar_pxJ5z7/comic_001_(1995).cbz
12-Aug-2017 11:12:49 - INFO    :: CP Server Thread-6 : Attempting to move: move
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Paths / Locations:
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] scriptname : Mylar.py
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] downloadpath : /mnt/comics/Comics/Vertigo/comic_(1995)
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] sabnzbdscriptpath :
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] comicpath : /home/ds/.mylar/cache/mylar_pxJ5z7
12-Aug-2017 11:12:50 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] CR Tagging enabled.
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Will modify existing tag blocks even if it exists.
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Enabling ComicTagger script: ['/usr/bin/python', '/home/ds/.mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/home/ds/.mylar/cache/mylar_pxJ5z7/comic_001_(1995).cbz']
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Executing command: ['/usr/bin/python', '/home/ds/.mylar/comictagger.py', '-e', '--delete-rar', u'/home/ds/.mylar/cache/mylar_pxJ5z7/comic_001_(1995).cbz']
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Absolute path to script: /usr/bin/python
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Output: Archive is not a RAR.
12-Aug-2017 11:12:53 - WARNING :: CP Server Thread-6 : [META-TAGGER][COMIC-TAGGER] file is not in a RAR format: comic_001_(1995).cbz
12-Aug-2017 11:12:53 - INFO    :: CP Server Thread-6 : [MANUAL META-TAGGING] Sucessfully wrote metadata to .cbz (comic_001_(1995).cbz) - Continuing..
12-Aug-2017 11:12:53 - DEBUG   :: CP Server Thread-6 : [MANUAL META-TAGGING] Tidying up. Deleting temporary cache directory : /home/ds/.mylar/cache/mylar_pxJ5z7

Thank you!

**Comment by evilhero** [comment]
It looks like it's having problems with the actual fileas it's indicating it's not a valid archive.

Have you tried metatagging different files and/or just a cbr file (instead of a cbz file)? The 'successfully wrote...' is a mislabeled error, as it's saying it's not a valid file for CT to convert which usually happens when the file is corrupt (if you try to open the file to see the contents, it won't be able to extract the entire file properly). I have proper logging for metatagging errors coming in next dev commit too. 

Has metatagging worked for you previously?

**Comment by sifu36** [comment]
Yes metatagging worked previously.
If I extract the cbz into a folder an create a new zip file (with 7z) rename it to cbz, it still won't tag.
I also tried a cbr, same issue.
New downloads are mostly cbr, it tries to tag them, but still no metatag available.

**Comment by evilhero** [comment]
Weird... You might have to enable the logging for CT from within the cmtagmylar.py file.  With Mylar shut down, edit the mylar/cmtagmylar.py file and around lines 205/206 you'll see 2 lines commented out:
```#logger.info(out) 
#logger.info(err)```
Just remove the # from each of those lines, save the file and try again. It will log the console output from CT during tagging so you can see exactly what the error is.

**Comment by sifu36** [comment]
Changed the lines. Now it's telling me it has no permission...really weird.
It has all the permissions and the folder is created in the cache folder.

12-Aug-2017 13:39:13 - DEBUG   :: CP Server Thread-4 : [META-TAGGER] dirName:/mnt/comics/Comics/Vertigo/comic_(1995)
12-Aug-2017 13:39:13 - DEBUG   :: CP Server Thread-4 : ComicTagger Path location for internal comictagger.py set to : /home/ds/.mylar/comictagger.py
12-Aug-2017 13:39:13 - DEBUG   :: CP Server Thread-4 : [META-TAGGER] Filename is : comic_(1995)/comic_001_(1995).cbz
12-Aug-2017 13:39:13 - INFO    :: CP Server Thread-4 : Filepath: comic_(1995)/comic_001_(1995).cbz
12-Aug-2017 13:39:13 - INFO    :: CP Server Thread-4 : Filename: comic_001_(1995).cbz
12-Aug-2017 13:39:13 - INFO    :: CP Server Thread-4 : New_Folder: /home/ds/.mylar/cache/mylar_1V_X68
12-Aug-2017 13:39:13 - INFO    :: CP Server Thread-4 : New_Filepath: /home/ds/.mylar/cache/mylar_1V_X68/comic_001_(1995).cbz
12-Aug-2017 13:39:13 - INFO    :: CP Server Thread-4 : Attempting to move: move
12-Aug-2017 13:39:13 - WARNING :: CP Server Thread-4 : [META-TAGGER] Unexpected Error: <type 'exceptions.IOError'>
12-Aug-2017 13:39:13 - WARNING :: CP Server Thread-4 : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
12-Aug-2017 13:39:13 - DEBUG   :: CP Server Thread-4 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.

**Comment by evilhero** [comment]
The location it's metatagging from (your series dir it looks like), does the user running mylar have full rights to it?  What are the perms on the cache folder that it created, and any files within that temp directory? 

IO Error could also mean that you're out of space on the cache drive.

**Comment by sifu36** [comment]
Perms on cache folder
drwxrwxrwx 16 ds ds   36864 Aug 12 14:03 cache

the temp folder is created by root.

there is enough free space.

**Comment by evilhero** [comment]
You're running mylar as root? 

And what about the location it's copying the file from - your series dir it looks like since it looks like you're doing manual metatagging.

**Comment by sifu36** [comment]
yeah this time it's root but I tried it with my user...the same issue...
final location is on my NAS.
When I try to manual metatag now it seems to move it to the temp folder (but no file in the directory) and the file is afterwards gone. issue is then in Archived state and gone.

**Comment by evilhero** [comment]
So is Mylar is running on a separate box than the final destination ?

You could try to disable the clean up call, that way the file will remain in the cache folder and you can see what the perms/state of the file(s) are after a failed run.

On roughly line 66:
`        tidyup(og_filepath, new_filepath, new_folder, manualmeta)
`
change it to:
`
        #tidyup(og_filepath, new_filepath, new_folder, manualmeta)
`

**Comment by sifu36** [comment]
Tried you suggestion, log says it created it but still deletes the folder.

**Comment by evilhero** [comment]
You didn't answer the first part of the question - is Mylar running on a separate box than the final destination ?

There's a tidyup command in the PostProcessor.py that's being called which is doing the cleanup thereafter.  We can get around that by editing the cmtagmylar.py file and around line 66 (inbetween the logger.warn about the unable to create temporary directory and the tidyup call, put in a `sys.exit(1)`, so like this:
`
logger.warn(module + ' Unable to create temporary directory to perform meta-tagging. Processing without metatagging.')
sys.exit(1)
tidyup(og_filepath, new_filepath, new_folder, manualmeta)
`
That will cause the program to complete halt after the initial error, instead of starting the tidyup process that's removing the files....

**Comment by sifu36** [comment]
Yes, Mylar is running on seperate box. Final destination is a NAS.

Ok will try that tomorrow. Thanks!

**Comment by sifu36** [comment]
Hi again!
Tried your suggestion but it folder wasn't left...now here comes the fun part.
I already tried to do a clean install (backing up config.ini and the database).
I thought, try it again and now it's working!

I really don't know what happenend... :(
But thank you very much for the support! 👍 

Is there a way to check which files has no metatags?

**Comment by evilhero** [comment]
No there is no way within Mylar itself, the 'i' icon beside each issue is just indicating that metadata might be present (ie. it's a .cbz file). You'd have to do a mass manual metatag for the series' that you think you might have missed issues on, or manually do them individually based on your history.

**Comment by sifu36** [comment]
Hi!
Yeah, I figured it out too. History helped.
Thanks for the support!
