### ISSUE TITLE
WWT is down.

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1702]
Looks like WWT is down this week, it's not Mylar having issues.... domain name might have been seized according to chatter on Reddit. 

If you have a way to confirm status with staff, please share...

**Comment by weidercs** [comment]
Domain registrar suspended their hostname resolution.  You can get around by manually putting this entry into your hosts file:

104.24.123.242 worldwidetorrents.eu

**Comment by barbequesauce** [comment]
This doesn't work for me - 403 client error forbidden.

I'm thinking staff is moving things around to get through the registrar issue.

**Comment by barbequesauce** [comment]
Recycled mylar with that hosts file entry and everything is moving along nicely.

Note that dotted ip in a browser will fail due to CloudFlare protection.

**Comment by weidercs** [comment]
looks like they've changed their domain to worldwidetorrents.me mylar will need to update to use that new domain name.

**Comment by evilhero** [comment]
I'll get a patch out to both branches tomorrow - just can't get to my machine until then unfortunately. 

Thanks for updating the issue thread with new information that can be used :)
