### ISSUE TITLE
500 Server Error rss_last: TypeError: a float is required

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1709]
Just went to activate Miatrix to give it a try. Saved the changes, then saw the update notification and hit update.

Now, when I try to go to config, I get this. Nothing in debug logs...

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 4359, in config
    "rss_last": datetime.datetime.fromtimestamp(mylar.SCHED_RSS_LAST).replace(microsecond=0),
TypeError: a float is required
Powered by CherryPy 3.2.0

**Comment by evilhero** [comment]
Yep, I forgot to initialise the rss_last variable on the web GUI if it was the initial startup ;)  Thanks for the headsup - fix is now in development.

**Comment by barbequesauce** [comment]
Much more better. Thanks.
