### ISSUE TITLE
Mylar not starting up

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1710]
Since the latest development update/commit mylar wont startup and is not creating a log for me to see what the error is. I've started from a fresh install and the same issue. THe Python screen pops up as normal and then within 1/2 a second disapears again. Running the development version on Windows 10.  Any suggestions would be great!

**Comment by evilhero** [comment]
It's probably due to the Mylar.py file having changed out in the last development commit - but just to make sure, how are you starting Mylar? Are you double-clicking on a .pyw file, the .py file or running a vbs script of some kind ? 

Note that if it's the .pyw file (which it kinda sounds like based on that description), you'd have to make a copy of the new Mylar.py file and name it as Mylar.pyw (overwriting the existing one).

**Comment by jimbojnr81** [comment]
I don't have a mylar.pyw file, just the .py file which is the one i'm executing to run mylar. I'm getting the issue event with a complete fresh install from a latest download before making any changes to the setup (reloading my config file, database, cache folder etc)

**Comment by evilhero** [comment]
That's weird - I just downloaded the zip from the repo and did a fresh install, and then double-clicked on the Mylar.py file and it loaded the browser on startup and displayed the GUI with no errors (with no config.ini set or anything). I'm also using Windows 10. Have you tried just doing a ```python Mylar.py``` from the dos command line (or git shell if you're using git for windows) to see if that will throw the error to the console ? 

Are  you using git to retrieve the install initially, or are you downloading the zip ? Do you happen to be running a non-english OS or the like (thinking it might be something system date related, although I wouldn't know what exactly at this point)?

**Comment by jimbojnr81** [comment]
Just tried running it from the console with no luck. 
I'm downloading the Zip file directly. OS is just standard English although the date is in English UK/Australian DD/MM/YYYY. 

I have just recently just installed a new antivirus so ill uninstall that and see, also ill reinstall python too just in case.

**Comment by jimbojnr81** [comment]
Still no luck, however on a whim i thought id try another program that runs on python just to see and no luck with that, so it seems to be Python.

**Comment by evilhero** [comment]
Which version of python are you running - or do you have more than one version on your system (if you go to a command prompt and just type in 'python' it will open up the interpreter with the version it's using).

**Comment by jimbojnr81** [comment]
I'm running 2.7.13 only version i have on the PC.

**Comment by evilhero** [comment]
Hmm, would seem to be ok - I'm using 2.7.10 on Win and not having those issues. 

Can I ask where you downloaded your python from? There are some different versions flying around that have some things missing on purpose (to make it more lightweight), and it's possible if you didn't grab the python installer from python.org that it's one of those.

I don't think you'd have to install python as as an Administrator, but if not that might play some role in some manner?

So just to reiterate - when you go to a dos command prompt, and cd to the mylar directory and then issue a 'python Mylar.py', what exactly is thrown back on the screen ?

**Comment by jimbojnr81** [comment]
I'm downloading pything strains from python.org. 

When I open a command prompt and run python mylar.py nothing happens, no error mesage, nothing, it just returns to the print without the command.

I had a previous version of the dev mylar (it's 6 commits behind) that I had lying around and that has booted up no problem (even when I copy the db, config file and cache folder from the one not working). I'm going to make a copy of it and update it to see if that causes the same issue.

**Comment by jimbojnr81** [comment]
I've just updated my old working version of Mylar and the same thing has happened, it wont start up.

**Comment by evilhero** [comment]
I'm not sure if that was a typo or not, but what is 'pything strains?'

It seems like it's unable to perform some basic startup stuff based on what you're saying, plus the fact that the other python program doesn't work... Just seems really weird even after an install.

I'm assuming your python path is in your environment path?

**Comment by jimbojnr81** [comment]
Damn auto correct, that should have been "downloading python straight from python.org". 

As a last ditch go i downgraded my version of Python to 2.7.10 and its now working (in hindsight, that should have been the first thing i tried). The previous version of Mylar was working fine on 2.7.11 onward though. 

Anyway, all good, lesson learnt, stick with python 2.7.10.

**Comment by evilhero** [comment]
Weird, it shouldn't have mattered as others are running 2.7.13.  I'll see if I can fire up that version on my windows machine and reproduce the problem to try and track it down.

Thanks coming back and explaining what worked. It helps narrow down the problem even more ;)

**Comment by PCurd** [comment]
I'm running 2.7.11 on Windows 10, under Development, and just updated,
everything started fine.

**Comment by baldspice** [comment]
I am having the same issue.  Windows 10 , Python 2.7.13rc1
Screen dump of error attached 
![image](https://user-images.githubusercontent.com/32018791/30513691-ea1f7d08-9ac4-11e7-8e4f-5d9e74bf6447.png)

**Comment by evilhero** [comment]
@baldspice it looks like your config.ini has an invalid character on line 1 of the .ini file.

Seems to be a different error than the original OP, at least based on that screenshot.

**Comment by baldspice** [comment]
I thought it might be the same thing as I saw the same symptoms (.bat file i use to kick it off would flash a few lines of code and then close).  Thanks for pointing me in the right direction

FYI for anyone else who has the same issue - I opened my config.ini and it looked blank.  However it was full of spaces/tabs.  I selected all, deleted, saved and everything started working again :)
