### ISSUE TITLE
chkthis error when searching

### ISSUE THREAD

**Issue by hutch0** [evilhero/mylar#1711]
Getting this when trying to search for issues. I thought it was a product of the latest pull, so I rolled back two commits, but it looks like it was there too.

Uncaught exception: Traceback (most recent call last):File "/home/downloader/mylar/mylar/logger.py", line 165, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/home/downloader/mylar/mylar/webserve.py", line 1263, in retryissuemodcomicname = chkthis['ComicName']NameError: global name 'chkthis' is not defined
--

I'm not sure if it could be related to the fix I had to do for the db. It looks like the code is looking for a column named IssueNumber, but the db has Issue_Number, so I just created the column it's looking for.

**Comment by hutch0** [comment]
Sorry, I just realized I'm only getting that error when retrying an nzb that was already snatched. Hope that helps a bit more.

**Comment by evilhero** [comment]
The retry option was fixed at one point, but it looks like it's failing again due to some db naming conventions like you mentioned.

I'll look into this later today and scope out what's happening - I believe I might have tested against torrents only since that was what was being discussed initially with the problems. Ill know more once I delve into it...

**Comment by evilhero** [comment]
I just looked at this - that line doesn't even exist in either of the branches that are most current, so you're using a not-current branch, or you pasted the log from when you rolled it back a few commits previous ;)

Can you get back up to date on a branch, and then try the retry again and paste in the log from an up-to-date branch, as of right now the error can't be reproduced on a current build.

**Comment by hutch0** [comment]
Sorry I didn't get back to your sooner. In short, I'm an idiot.  I figured since you said the issue doesn't exist in the current branches, I'd update. It said I was already up to date though, so instead I did a hard reset and cleaned it. Didn't realize that would blow away my db though. Spent most of last night re-adding my library . If it comes up again, I'll let you know.

Thanks for the great work!
