### ISSUE TITLE
No longer able to manually Rename Files

### ISSUE THREAD

**Issue by waden34** [evilhero/mylar#1715]
If I try to use the Rename Files button on a series page (no series are working for me currently) I get a popup saying: There was a error.
When new files are found in my watch folder to Post Process, they are moved and renamed successfully.

Nothing at all is logged to the mylar log file. From the Development console in Chrome, I see the below error on the Network tab for manualRename?comicid=42563.

I reinstalled both Mylar and Python. I'm using the most recent development branch. I tried reverting to the master branch and get a slightly different error.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 2176, in manualRename
    comicdir = comic['ComicLocation']
TypeError: 'NoneType' object has no attribute '__getitem__'
Powered by CherryPy 3.2.0

Master branch error:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 2075, in manualRename
    renameiss = helpers.rename_param(comicid, comicname, issue['Issue_Number'], filename, comicyear=None, issueid=None, annualize=annualize)
  File "C:\Mylar\mylar\helpers.py", line 377, in rename_param
    logger.fdebug('character space denoted as : ' + iss_space)
TypeError: cannot concatenate 'str' and 'bool' objects

**Comment by evilhero** [comment]
Yep, that was me trying to add in a way to manually rename a batch of series at a time via the Manage Comics page - and then forgetting to finish testing it due to other problems. Since the batch-option isn't present just yet, I quick fixed this one so that it won't be a problem again :)

Thanks for the heads-up (seriously, I probably wouldn't have found it on my own as I don't usually test with the rename function enabled)...

**Comment by waden34** [comment]
Wow, that was insanely fast. I verified that the update fixed the problem. Thanks for the great work!

**Comment by evilhero** [comment]
Yep, again nice catch - although that one was in there for awhile, which makes it really curious as it has never come up til now, but again stupid variable reference that was not being used at all, so just removed it entirely. Fix is in development now, thanks for the bug report!
