### ISSUE TITLE
Issues renaming when the issue is ½

### ISSUE THREAD

**Issue by Vuzrak** [evilhero/mylar#1718]
It seems to error out and abort the renaming process if it tries to rename a file with ½ as the issue number.

**Comment by evilhero** [comment]
Parsing /renaming a file with that issue number should be working (it's testing ok anyways).

Can you post the debug log for a rename that's failed so I can see the name of the file that you're trying to rename, as well as the leadup to, including the error?

**Comment by Vuzrak** [comment]
[mylar.txt](https://github.com/evilhero/mylar/files/1317769/mylar.txt)

The log stops there when it try's to rename the file.

The current filename is "Buffy the Vampire Slayer Angel 000.5 (1999).cbr" was trying to rename it to "Buffy the Vampire Slayer Angel - 000.5 (1999).cbr"

**Comment by evilhero** [comment]
Heh, your log cut off right at the part where it was starting to do the given issue - can you paste the remainder of it for the ½ issue so I can see the complete workflow?

**Comment by Vuzrak** [comment]
That was actually the entire log for it, the only reason I know there was a error was because a toast message popped up saying error.

**Comment by evilhero** [comment]
Oh, ok - can you give the full name of the file that you were trying to rename then ? That part is missing from the log, and I'll need to know it do the right kind of testing.

**Comment by Vuzrak** [comment]
I posted that at the bottom of the message above.

**Comment by evilhero** [comment]
Ahh, sorry - mobile cuts off some of the text message for some reason. I'll test against that name then...thanks

**Comment by evilhero** [comment]
Ok, I have this fixed on my local repo - but it's not exactly to my liking atm:
```
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : comicid: 6368
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : issue# as per cv: ½
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : issueid:376903
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : issueid is now : 376903
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : issue number formatted: .5
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Zero Suppression set to : 00x
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : issue detected less than 10
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Zero level supplement set to 00x. Issue will be set as : 000.5
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Pretty Comic Issue is : 000.5
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Issue Year : 1999
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Publisher: Dark Horse Comics
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Series: Buffy the Vampire Slayer: Angel
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Year: 1999
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Comic Location: /Buffy the Vampire Slayer Angel V1 (1999)
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : not an annual - removing from filename paramaters
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : new format: $Series $VolumeY $Issue ($monthname $Year)
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Altering series name due to filenaming restrictions: Buffy the Vampire Slayer Angel
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : New Filename: Buffy the Vampire Slayer Angel V1999 000.5 (January 1999).cbr
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Source: buffy the vampire slayer angel 000.5 (1999).cbr
20-Sep-2017 12:34:01 - DEBUG :: CP Server Thread-2 : Destination: /Buffy the Vampire Slayer Angel V1 (1999)/buffy the vampire slayer angel v1999 000.5 (january 1999).cbr
20-Sep-2017 12:34:01 - INFO :: CP Server Thread-2 : Renaming buffy the vampire slayer angel 000.5 (1999).cbr ... to ... Buffy the Vampire Slayer Angel - 000.5 (January 1999).cbr
20-Sep-2017 12:34:01 - INFO :: CP Server Thread-2 : I have renamed 1 issues of Buffy the Vampire Slayer: Angel
```
The reason why I said it's not to my liking as I'm thinking there are quite a few people that would like to keep the unicode issue number (½) just as that within the filename, as opposed to converting it to 0.5. So I'm going to add an option to 'keep unicode issue numbers as unicode' somewhere in the rename option for this purpose - but leaving it wouldn't affect your usage as it's the desired format you require (ie. don't check it when it's available).

I'll try and get this out to the dev branch later today once I'm finished some more testing...

**Comment by Vuzrak** [comment]
I'm actually fine with it naming it either .5  or ½, my main issue was it just crashing and stopping when it detected the .5.

**Comment by evilhero** [comment]
Forgot to add to latest dev commit that just went up - this should now be fixed and working. If you want to enable the unicode option I mentioned above, just set the config.ini value of UNICODE_FILENAME to 1 (it defaults to 0 which is disabled), otherwise leaving it at 0 will keep your existing numbering.

**Comment by Vuzrak** [comment]
That seemed to have fixed it.
