### ISSUE TITLE
Scan comic library fails

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1720]
A prefix is added to the path causing it to fail:
\\?\D:\Library\eComics
Don't see that with the master version, only dev.

**Comment by evilhero** [comment]
It should be 2 `\\` instead of just the one. The command `\\?\` tells windows to denote the unicode path length and thereby bypass the length limit normally associated with Windows environments.

I'll have to confirm again, as it was working properly prior. Otherwise, I'll just remove it and make mention of it as a way to bypass the path length limit.

**Comment by SUBnet192** [comment]
That's actually not the issue, i pasted it wrong. everytime you click save and scan, it adds the \\?
I did it 3 times...

\\?\\\?\\\?\D:\Library\eComics

and of course the logs report: 

Cannot find directory: \\?\\\?\\\?\D:\Library\eComics. Not scanning

**Comment by SUBnet192** [comment]
Following the latest fix, I now get this:

	[IMPORT] Unable to complete the scan: object of type 'NoneType' has no len()

**Comment by SUBnet192** [comment]
Commenting out those 2 lines fixes the issue for me (completely removing the \\?\ updates...)
#       if 'windows' in mylar.OS_DETECT.lower() and '\\\\?\\' not in path:
#            path = "\\\\?\\" + path

**Comment by evilhero** [comment]
Yeah something's up, or that line is just erroneous - but some other stuff with the pull is happening atm so I'll have to get back to this later today.

**Comment by SUBnet192** [comment]
Appreciate the time and effort. I've had/seen many issues in the past, and sort of ignored them but I think I'll start posting more as I find them, hopefully you wont find me annoying :)

**Comment by SUBnet192** [comment]
even after fresh git clone I have the same issue. I had to remove those two lines for the path prefix to fix it.
