### ISSUE TITLE
Updating dev version fails

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1722]
I get popups to the effect that there are  3 commits available., I select update, it shutsdown and comes back saying there's still 3 commits available.

**Comment by evilhero** [comment]
It's assuming there's some kind of local changes, so it can't update. You need to do a 'git pull' from the command line and see what the error actually is - if it's not being logged (or else run Mylar from the command line instead of as a daemon, and when it does the update the error will break in the console).

**Comment by SUBnet192** [comment]
I shutdown the service, deleted the folder, downloaded the latest bundle, unzipped in the folder, restored my ini file only (no db) and I get a note that there are new version available, 6 commits behind. I click update, same behaviour... shutdown, restart, still says 6 commits behind

**Comment by SUBnet192** [comment]
20-Sep-2017 17:41:50 - INFO :: MAIN : Background Schedulers successfully started...
20-Sep-2017 17:41:59 - INFO :: MAIN : Received signal: update
20-Sep-2017 17:41:59 - INFO :: MAIN : Trying to gracefully shutdown the background schedulers...
20-Sep-2017 17:42:10 - INFO :: MAIN : Mylar is updating...
20-Sep-2017 17:42:12 - INFO :: MAIN : Mylar is restarting...
20-Sep-2017 17:42:12 - INFO :: MAIN : Restarting Mylar with ['C:\\Python27\\python.exe', 'C:\\Mylar\\Mylar.py', '--nolaunch']

RESULT: 6 commits behind still...

**Comment by evilhero** [comment]
You need to make sure the git_branch in the config.ini is set to the branch you're actually physically on. The git_branch is used to check against github, and the physical branch is what is being pulled against.

**Comment by SUBnet192** [comment]
git_branch = development

**Comment by SUBnet192** [comment]
20-Sep-2017 18:19:39 - INFO :: MAIN : Mylar is updating...
20-Sep-2017 18:19:39 - DEBUG :: MAIN : Trying to execute: "git pull origin development" with shell in C:\Mylar
20-Sep-2017 18:19:41 - DEBUG :: MAIN : Git output: From https://github.com/evilhero/mylar
 * branch            development -> FETCH_HEAD
Updating 595ed45..edfdf98
error: Your local changes to the following files would be overwritten by merge:
        data/interfaces/default/comicdetails.html
        data/interfaces/default/css/data_table.css
        mylar/__init__.py
        mylar/filechecker.py
        mylar/helpers.py
        mylar/importer.py
        mylar/search.py
        mylar/updater.py
        mylar/webserve.py
Please commit your changes or stash them before you merge.
Aborting

20-Sep-2017 18:19:41 - INFO :: MAIN : Mylar is restarting...
20-Sep-2017 18:19:41 - INFO :: MAIN : Restarting Mylar with ['C:\\Python27\\python.exe', 'C:\\Mylar\\mylar.py', '--nolaunch']

The only one I did update was the webserve.py to fix the search path issue with the double backslash

**Comment by evilhero** [comment]
Might have to do with the change from dev to master, or vice versa. Best bet is to delete the dir (backup you left config.ini and mylar.db and cache die), and then reclone it

**Comment by SUBnet192** [comment]
I did! That's a fresh install. I kept only the INI

**Comment by evilhero** [comment]
Are you downloading the zip from github and trying to do a git pull at the same location?

You have to pick one or the other and stick to that so the updater works. I'm confused at the moment looking at the posts/log as to what source you're using (could be that I'm frazzled from the other issues lol)

**Comment by SUBnet192** [comment]
I downloaded fro  Github. Never did git pull

---
Marc Bouchard

________________________________

**Comment by evilhero** [comment]
That might be part of the problem - can you try to do the git clone method of installing instead of snatching the zip? It looks like it's trying to get stuff via the source but using git, and I haven't looked at the source update code in a very long time, but I know that the git method works.

**Comment by SUBnet192** [comment]
This has worked for me for years. It started about a month ago with the failures to update.

**Comment by evilhero** [comment]
That's probably when we started moving around some of the structure of the directories, which resulted in stuff like this happening - especially to windows users.

You have 2 choices atm I would guess :
- grab the most recent zip source from github and try from scratch again - at this point, I can only assume that those files are holding things back so it won't update.

- You can rename all of those files to have an extension of .backup or something, and them try to do the update as you have it now which should look things to progress as per normal (and then once updated, just go back and delete them).

I would think option 2 would be easier to try initially...

**Comment by SUBnet192** [comment]
I don’t mind reinstalling (I do all the time to freshen up the database and cleanup old junk), that’s why the mass import issues are important to me ☺ )
I’ll try the rename as suggested, we’ll see. Thanks !

**Comment by SUBnet192** [comment]
I started from scratch doing a git clone and it works. There was another update not long ago and I was able to apply it. GUess downloading the source doesn't work the same? odd... :)

**Comment by SUBnet192** [comment]
Closing this.
