### ISSUE TITLE
Recheck files not triggered after manually importing (after batch import)

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1724]
When a batch import is completed, some series with duplicate matches have to be manually selected. When we do this, it does add the series to the catalog, but we have to manually trigger a "recheck files" to see which issues we have/are missing. Initial status is set to "None"

**Comment by evilhero** [comment]
You're going to have to start posting debug logs with the issues. It takes me time to try and duplicate the problem and then fix it - whereas you can save a huge step for me by including the debug logs and then I can concentrate on fixing ;)

And it should be manually rechecking, but there's a problem  with status being set to None across the board now for some reason that I'm trying to track down

**Comment by SUBnet192** [comment]
Will do :)
