### ISSUE TITLE
Error message when importing about certificates?

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1730]
21-Sep-2017 16:58:25 - DEBUG :: Thread-14 : Default search mode - this will match on ALL search words
21-Sep-2017 16:58:26 - INFO :: Thread-16 : Attempting to retrieve the comic image for series
C:\mylar\lib\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by evilhero** [comment]
What's the provider being used and do you have verify ssl checked off since its an https site?

**Comment by SUBnet192** [comment]
Missed that one. My bad. Thanks :)
