### ISSUE TITLE
Can't update mylar

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1735]
I'm having issues updating mylar.  I get the message to update, but when I do, it goes to the waiting screen and nothing happens.
Also, I don't think I'm used to seeing the following on the terminal window 
27-Sep-2017 20:10:20 - WARNING :: CP Server Thread-6 : sqlresult: UPDATE weekly SET STATUS = ?, PUBLISHER = ?, SHIPDATE = ?, ISSUEID = ?, YEAR = ?, COMIC = ?, WEEKNUMBER = ?, COMICID = ? WHERE ISSUE = ? AND DYNAMICNAME = ?

**Comment by barbequesauce** [comment]
Have you managed to capture debug logs of either event? It’s rather hard to diagnose without an idea of what is happening...

What operating system are you on? What version of Python? What kind of installation (docker, zip or git)?

**Comment by Spartan304** [comment]
Came here to report the same issue.  I'm on the development branch git build 8d199d3ec7e45bf8d2845822ee6126fef1ad33a0 running Python 2.7.9 installed via git.  I checked the logs via GUI and see no errors even after turning debug log on with the mylar.log file from the logs directory saying the same thing.  Is there a deeper log file located elsewhere you would need to look at?

**Comment by evilhero** [comment]
What OS are you guys running on?

And if you've installed via git - try going to a command prompt and into the mylar directory and doing a 'git pull' and see what the result is.

**Comment by Spartan304** [comment]
Ubuntu Server 16.04 for me.  After git pull 5 files were changed with 32 insertions and 29 deletions. I restarted Mylar and tried to update again with the same behavior although now it's reporting I'm on git build 1fa3de4cb1c1571bc1080a0db0bc3a5b62f6be69 but it's still saying I am 5 commits behind.

**Comment by DGMayor** [comment]
Same here, Windows 7.

**Comment by evilhero** [comment]
@DGMayor : try going into lib/apscheduler and removing all of the .pyc files therein (or just rename the entire apscheduler directory to apscheduler.back or something). Then try either doing an update in program, or doing a `git pull` from the command line of the mylar directory.

I haven't been able to figure out exactly why it's dying for some and not others, but I'm almost positive it has something to do with the apscheduler system being revamped :/

**Comment by DGMayor** [comment]
So I just updated Git on my machine (had a really old version) and it let me do a pull, but now Mylar reports unknown version and in the config page, for Gi versiont, it says None.

**Comment by DGMayor** [comment]
Tried updating git_path in my config.ini, but still reporting none / unknown version.

**Comment by dreaganluna** [comment]
I can confrim that updating Git on my Windows 7 machine (from v1.9.x to 2.x.x) made updates work again.

**Comment by thewindupboy** [comment]
BTW, this is happening again (macbook)

**Comment by evilhero** [comment]
Try updating your git or setting the git_path in your config.ini to the location of your git install

**Comment by thewindupboy** [comment]
Welp, that seems to have worked, thanks!
