### ISSUE TITLE
Wrong Series listed in Weekly Pull List

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1737]
HI, me again (sorry)

I have just noticed that there are some series (Batman Beyond for example) that are showing up in the Weekly Pull List, as they should, but when adding them for the first time they add an old/previous series. 

![image](https://user-images.githubusercontent.com/5010165/30998474-22bd1e16-a512-11e7-9eb7-d9435a315b5c.png)

**Comment by evilhero** [comment]
Yeah that happens occasionally with rebooted series - once the issue numbers get higher than the old volume this will also occur. They require manual changes on the backend that Mylar polls against, and I just updated it so if you do a ```Recreate Pullist``` you'll get the proper id now ;)

**Comment by jimbojnr81** [comment]
yep, that's done the trick! thank you!
