### ISSUE TITLE
URL Fetching failed; File not on server

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1743]
Hello, 

I'm getting this error when mylar is trying to send to sabnzbd. I've tried changing the IP's of both mylar and sabnzbd from localhost to the actual ip of the machine with no luck (when i change Sabnzbds IP in mylar another error pops up saying it cannot send to sabnzbd).

API's are all correct and no error messages in mylar when the ip is set to localhost or 0.0.0.0. Both programs are on the same machine running ubuntu 16.04 and mylar is development version all updaed (although it says development in the settings>information tab, as well as in the config file, yet at the bottom of the page next to version number its still saqying master). 

Other programs (sonarr & radarr) have no issue sending to sabnzbd. any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/5010165/31692082-1247cabe-b3e4-11e7-93da-6aba4b3e0722.png)

**Comment by evilhero** [comment]
Probably you should be using the 0.0.0.0 so it will listen on all interfaces - changing it to direct ip should work however, but localhost/0.0.0.0 would be the normal way things work.

Did you setup the autoProcessComics.cfg file with the correct info? I'm assuming you're running the comicRN.py file after a successful snatch by sab

**Comment by jimbojnr81** [comment]
Yeah autoProcessComics.cfg has the correct info and comicRN.py is setup to run after successful snach.   

Mylar's ip set to localhost and within mylar, Sab's ip is set to localhost aswell.

**Comment by jimbojnr81** [comment]
All good! I just reinstalled mylar fresh (copied over my db config and cache) ant its working now! I must have buggered up something without realizing.
