### ISSUE TITLE
Search for missing in Story Arc does nothing.

### ISSUE THREAD

**Issue by cerinthus** [evilhero/mylar#1748]
As per title.

Logs only give three lines of info when clicked:

2017-10-19 20:28:15 | INFO | Secret Empire
2017-10-19 20:28:15 | INFO | StoryArcs
2017-10-19 20:28:15 | INFO | /home/rick/Documents/Comics

Clicking grab manually works fine, but with longer arcs like Secret Empire this is more than slightly undesirable

**Comment by Outcats** [comment]
I was about to post the same problem, I get the same in my log file. Tried both master and development branch fresh installs.

I'm on Windows 10 by the way.

**Comment by evilhero** [comment]
I'll check into this in a bit, this was all working previously so a recent commit probably broke something and you both are the first to mention it.

**Comment by evilhero** [comment]
Yeah, when the one-off stuff got changed around to allow for some better handling - the grabs via the bulk option for arcs became broken as there was no way to distinguish between what's on your watchlist vs what's not (for story arc issues only). 

I think I have it fixed now - but I'm working through the post-processing of said issues now cause of the same problem ;)

**Comment by Outcats** [comment]
Good to hear, if you need it testing out if it's released in dev/live, let us know.

**Comment by Outcats** [comment]
Hey EvilHero, any update on this issue?

**Comment by evilhero** [comment]
Yeah it's still being worked on - personal life this weekend kinda sucked the life out of things for me. 

I hope to push it out either later today or tomorrow, mainly because I wasn't paying attention when I started and I did all the fixes on a separate huge local commit that's really intertwined with every module. So now I have to either piecemeal things back to push out the changes for this issue,  or just try and get the huge commit to fly properly and hope for the best ;)

**Comment by barbequesauce** [comment]
Go big or go home!

Seriously - maybe post it to a different repo (dev2 or something) and a few of us guinea pigs can choose to kick the tires before the much-larger pool of development users get it?

**Comment by barbequesauce** [comment]
Different *branch not repo

**Comment by Outcats** [comment]
Sounds good to me ether way! 

Sorry to hear about your weekend though...

**Comment by evilhero** [comment]
Yeah I might not have much of a choice with this commit - I've tested the crap out of it, but as is always the case when something goes live, there will be problems. Hoping to push it out today...

**Comment by evilhero** [comment]
Ok, so I was a day late ;)

Config-upgrade is the new branch that holds all the lovely changes for those wanting to test the waters. I'm going to create a separate issue thread just for that branch, as there's a lot of changes that are in there plus all the bug-fixes and such - hopefully the more feedback I can get about it, the quicker I can push it into the development branch for mass consumption...
