### ISSUE TITLE
Story Arc folder request

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1749]
Would it be at all possible to set the storyarc folder path to be outside of the comic folders? Similar to what is being done with weekfolder_loc.

**Comment by evilhero** [comment]
Should be able to yes, haven't looked at that particular piece of code in awhile - but I believe with some modifications it should be doable. I'll add this as an enhancement request and try to get it done in the next commit or two...

**Comment by barbequesauce** [comment]
I love this idea...

That said, I’m thinking of all the arcs I’ve already collected. It would be great if Mylar could check first to see if an issue is already downloaded and either copy or link it into the arc folder...
