### ISSUE TITLE
Attempting to Access the Pulllist returns a Server 500 Error

### ISSUE THREAD

**Issue by psychoflame** [evilhero/mylar#1750]
Hey, I'm running into a werid issue whenever i try to access the Pullist. whenever i try to access the 'This Week' tab it always errors out with a 500 Internal Server Error. The error that shows up on the Webpage is 

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 1510, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 1760, in manualpull
    weeklypull.pullit()
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/weeklypull.py", line 63, in pullit
    newpull.newpull()
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/newpull.py", line 30, in newpull
    getthedate = soup.findAll("div", {"class": "Headline"})[0]
IndexError: list index out of range
 
```

The Werid thing is, that checking the logs with debuging enable all i see is this below and nothing else 
```

20-Oct-2017 20:39:15 - INFO    :: Thread-12 : Update complete
20-Oct-2017 20:39:36 - INFO    :: CP Server Thread-3 : Web logs cleared
20-Oct-2017 20:39:42 - INFO    :: CP Server Thread-3 : Verbose toggled, set to True
20-Oct-2017 20:39:42 - DEBUG   :: CP Server Thread-3 : If you read this message, debug logging is available
20-Oct-2017 20:39:45 - INFO    :: CP Server Thread-3 : trying to repopulate to week: 42-2017
20-Oct-2017 20:39:45 - INFO    :: CP Server Thread-3 : ALT_PULL: 1 PULLBYFILE: False week: 42 year: 2017
20-Oct-2017 20:39:45 - INFO    :: CP Server Thread-3 : Weekly pull list present - checking if it's up-to-date..
20-Oct-2017 20:39:45 - INFO    :: CP Server Thread-3 : [PULL-LIST] Populating & Loading pull-list data directly from webpage
```

Any idea what's going on here? Thanks

**Comment by evilhero** [comment]
Off-hand it looks like they changed the layout to the page that mylar parses for new pull that it goes to when you're using alt_pull = 1.

Ideally you should be using alt_pull = 2 for the best results. Proper naming, more accurate matching, more frequent pullist updates, along with being able to go a few weeks into the future for pullist information is just some of the benefits. There's alot more than that, but the vast majority of it is underneath the GUI where all the magic happens ;) 

Just make sure to have mylar not running when you change alt_pull to 2. Then when it starts back up, you'll see the change immediately when you view the pullist.

**Comment by psychoflame** [comment]
Yep that did it for me. I could've swore i had the alt_pull on the correct setting, but i just moved my mylar install over to a new install and it stopped working. Thanks Evilhero
