### ISSUE TITLE
Config-upgrade branch   ** all issues/problems  in here**

### ISSUE THREAD

**Issue by evilhero** [evilhero/mylar#1752]
This is going to be the issue portion for the config-upgrade branch since it's such a massive overhaul of the existing configuration - items are bound to have been missed by myself during testing things.

There are also a bunch of fixes/improvements within this branch, just because they got intertwined with the config changes and it was a mess to keep things separate. Here's a short list:

- the most important part, **no more restarts required after saving the config!** The provider order sequence is generated on each save dynamically now going forward, and there's even a little indication of what the provider order is currently at the top of the Providers tab in the configuration tab. This will change dynamically after each save of the config as well (it will not change if you're just enabling/disabling providers without saving the configuration).
- when starting Mylar up, it will dynamically load up the old config.ini file, convert it and then save the new version as config.ini. Prior to re-saving it, it will save a backup as config.ini.backup in the mylar root just in case. If you're having problems with loading up the new config on subsequent starts, you should be able to just copy the config.ini.backup to config.ini and it will startup as per normal (it can load either config versions for use, but if it's not at the new level it will always try to convert it).
- there is a ```minimal_ini``` now included in the config.ini. What this does is allow for a 'minimal'  config.ini, meaning that only fields in which the values are different than the default will be applied to the config for saving, otherwise it will be ignored as they are defaults. Note that you can make this change to an old config.ini prior to starting Mylar and having it convert (minimal_ini = True under the General section), and when it converts it to the new ini it will bring across the minimal_ini value and thereby only write minimal values to the .ini
- the weeklypull will show the volume / series year beside each series that it can predetermine. This is based on the the site Mylar polls against, not what's in your watchlist currently. Eventually, this information will be used for better matching and perhaps color coding to indicate that it matches on the poll site, but not on your watchlist (which would cause problems with pulls).
- #1748 is addressed in this branch
- #1744 is addressed in this branch
- #1745 should be fixed in here.
- probably a bunch of other stuff, but I can't recall atm....

**Comment by barbequesauce** [comment]
I have four more issues to find and snatch for this week, then I'll get on the upgrade train...

**Comment by evilhero** [comment]
Sounds good - I appreciate anything that can be done to help test this one out, and the more the merrier :)

**Comment by barbequesauce** [comment]
```
pi@machine:/opt/mylar $ 26-Oct-2017 11:26:20 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: /opt/mylar
26-Oct-2017 11:26:20 - INFO :: MainThread : Initializing startup sequence....
Updating config to newest version : 7
26-Oct-2017 11:26:20 - INFO :: MainThread : provider_order: 0, tpse, 1, dognzb, 2, 32p
'NoneType' object has no attribute '__getitem__'
FATAL ERROR
```

**Comment by evilhero** [comment]
Can you enable debug mode on the cli startup and try starting it up again (ie. python Mylar.py -v)...there's a bunch of debug lines that are between the last line and the error and it might help pinpoint things down for me in troubleshooting it

**Comment by lamahmud** [comment]
I'm getting:
macmini:mylar $ python /Applications/mylar/Mylar.py 
Traceback (most recent call last):
  File "/Applications/mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/Applications/mylar/mylar/__init__.py", line 36, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/Applications/mylar/lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "/Applications/mylar/lib/apscheduler/schedulers/base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

This happened after I attempted to update my copy of Mylar.  Now I can't get even a fresh copy to work.  It was working right before I tried to update.

**Comment by evilhero** [comment]
See #1754 - you need to update one of your modules that python uses.

**Comment by ForumFerret** [comment]
Does this branch update One-offs at all evilhero? I updated to a226658876af19d60d3c4291ea158644731f143b and I don't see the One-Offs directory string in the config.ini anymore; tried out config-update and didn't see it in the config.ini after that either.

**Comment by allkindsofralph** [comment]
Was this abandoned? I thought it was merged to development, but in development it still says I need to restart to make changes

**Comment by evilhero** [comment]
Yes, it's been merged - and you do have to restart after any web interface changes as is noted in the GUI. This is normal with any application when changing interface settings. Everything else is applied instantly.

This issue will be closed, cause well - it's merged.
