### ISSUE TITLE
Unable to find file in directory

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1753]
I manually placed a file into the directory for the series, hit "Recheck Files" and the app fails to find the file, even though it is named correctly.  

I have a screenshot of the directory with the files, issue 1 was found by mylar, copied and renamed automatically.  Issue 2, I put there, and you this is the issue I am referring to.

<img width="621" alt="screen shot 2017-10-26 at 10 05 08 am" src="https://user-images.githubusercontent.com/175500/32060750-5a71b4b0-ba35-11e7-978a-7ef4b5ddd298.png">

Debug log is pasted below

> 2017-10-26 10:00:29 | INFO | [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 1 in an Archived state [ Total Issue Count: 1 / 2 ]
> -- | -- | --
> 2017-10-26 10:00:29 | DEBUG | [FILE-RESCAN] Ensuring permissions/ownership enforced for series: Punisher MAX: The Platoon
> 2017-10-26 10:00:29 | DEBUG | [FILE-RESCAN] Adjusting have total to 1 because of this many archive files already in Archive status :1
> 2017-10-26 10:00:29 | INFO | [FILE-RESCAN] Total files located: 0
> 2017-10-26 10:00:29 | INFO | [FILE-RESCAN] Updated the status of 2 issues for Punisher MAX: The Platoon (2017) that were not found.
> 2017-10-26 10:00:29 | DEBUG | [ANNUAL-CHK] No annuals with identical issue numbering across annual volumes were detected for this series
> 2017-10-26 10:00:29 | DEBUG | No issues with identical issue numbering were detected for this series
> 2017-10-26 10:00:29 | INFO | FAILED FILES: [{'issue_number': '1', 'sub': None, 'issue_year': '2017', 'comiclocation': u'Z:\\Max/Punisher The Platoon [2017]', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Punisher The Platoon', 'comicfilename': 'Punisher The Platoon - 2017 - 1.cbz', 'series_volume': None}, {'issue_number': '2', 'sub': None, 'issue_year': '2017', 'comiclocation': u'Z:\\Max/Punisher The Platoon [2017]', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Punisher The Platoon', 'comicfilename': 'Punisher The Platoon - 2017 - 2.cbr', 'series_volume': None}]
> 2017-10-26 10:00:29 | INFO | [NO MATCH] Punisher The Platoon - 2017 - 2.cbr [WATCHLIST:Punisher MAX: The Platoon]
> 2017-10-26 10:00:29 | DEBUG | Possible Alternate Names to match against (if necessary): [u'PunisherMax\|Platoon']
> 2017-10-26 10:00:29 | INFO | Series_Name: Punisher The Platoon --- WatchComic: Punisher MAX: The Platoon
> 2017-10-26 10:00:29 | DEBUG | series title possibly: Punisher The Platoon
> 2017-10-26 10:00:29 | DEBUG | issue verified as : 2
> 2017-10-26 10:00:29 | DEBUG | issue_position: 6
> 2017-10-26 10:00:29 | DEBUG | Already validated year, ignoring as possible issue number: 2017
> 2017-10-26 10:00:29 | DEBUG | issue number :2
> 2017-10-26 10:00:29 | DEBUG | Issue set to: 2
> 2017-10-26 10:00:29 | DEBUG | Numeric detected as the last digit after a hyphen. Typically this is the issue number.
> 2017-10-26 10:00:29 | DEBUG | yearposition: 4
> 2017-10-26 10:00:29 | DEBUG | hyphen located at position: 21
> 2017-10-26 10:00:29 | DEBUG | possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '2017', 'mod_position': 23}, {'position': 6, 'validcountchk': False, 'number': '2', 'mod_position': 30}]
> 2017-10-26 10:00:29 | DEBUG | highest_series_position: 4
> 2017-10-26 10:00:29 | DEBUG | year verified as: 2017
> 2017-10-26 10:00:29 | DEBUG | year verified as : 2017
> 2017-10-26 10:00:29 | DEBUG | sctd: 2017
> 2017-10-26 10:00:29 | DEBUG | datecheck: [{'date': '2017', 'position': 4, 'mod_position': 23}]
> 2017-10-26 10:00:29 | DEBUG | date: 2017
> 2017-10-26 10:00:29 | DEBUG | checking date : 2017
> 2017-10-26 10:00:29 | INFO | [FILENAME]: Punisher The Platoon - 2017 - 2.cbr
> 2017-10-26 10:00:29 | INFO | [NO MATCH] Punisher The Platoon - 2017 - 1.cbz [WATCHLIST:Punisher MAX: The Platoon]
> 2017-10-26 10:00:29 | DEBUG | Possible Alternate Names to match against (if necessary): [u'PunisherMax\|Platoon']
> 2017-10-26 10:00:29 | INFO | Series_Name: Punisher The Platoon --- WatchComic: Punisher MAX: The Platoon
> 2017-10-26 10:00:29 | DEBUG | series title possibly: Punisher The Platoon
> 2017-10-26 10:00:29 | DEBUG | issue verified as : 1
> 2017-10-26 10:00:29 | DEBUG | issue_position: 6
> 2017-10-26 10:00:29 | DEBUG | Already validated year, ignoring as possible issue number: 2017
> 2017-10-26 10:00:29 | DEBUG | issue number :1
> 2017-10-26 10:00:29 | DEBUG | Issue set to: 1
> 2017-10-26 10:00:28 | DEBUG | Numeric detected as the last digit after a hyphen. Typically this is the issue number.
> 2017-10-26 10:00:28 | DEBUG | yearposition: 4
> 2017-10-26 10:00:28 | DEBUG | hyphen located at position: 21
> 2017-10-26 10:00:28 | DEBUG | possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '2017', 'mod_position': 23}, {'position': 6, 'validcountchk': False, 'number': '1', 'mod_position': 30}]
> 2017-10-26 10:00:28 | DEBUG | highest_series_position: 4
> 2017-10-26 10:00:28 | DEBUG | year verified as: 2017
> 2017-10-26 10:00:28 | DEBUG | year verified as : 2017
> 2017-10-26 10:00:28 | DEBUG | sctd: 2017
> 2017-10-26 10:00:28 | DEBUG | datecheck: [{'date': '2017', 'position': 4, 'mod_position': 23}]
> 2017-10-26 10:00:28 | DEBUG | date: 2017
> 2017-10-26 10:00:28 | DEBUG | checking date : 2017
> 2017-10-26 10:00:28 | INFO | [FILENAME]: Punisher The Platoon - 2017 - 1.cbz
> 2017-10-26 10:00:28 | INFO | there are 2 files.
> 2017-10-26 10:00:28 | INFO | [FILE-RESCAN] Now checking files for Punisher MAX: The Platoon (2017) in Z:\Max/Punisher The Platoon [2017]
> 2017-10-26 10:00:23 | DEBUG | If you read this message, debug logging is available
> 2017-10-26 10:00:23 | INFO | Verbose toggled, set to True
> 2017-10-26 10:00:21 | INFO | Verbose toggled, set to False
> 2017-10-26 10:00:17 | INFO | Web logs cleared

**Comment by evilhero** [comment]
The filename has to match what the series title is - in this case, from the log it shows:

> Possible Alternate Names to match against (if necessary): [u'PunisherMax\|Platoon']
2017-10-26 10:00:29 | INFO | Series_Name: Punisher The Platoon --- WatchComic: Punisher MAX: The Platoon

The filename has to have the full series name in it - you have ```Punisher The Platoon``` and it should be ```Punisher MAX The Platoon``` (or ```Punisher MAX - The Platoon```, etc).

If you want to keep the filenames as is, then make use of the alternate search name field in the Edit Settings box for the given series, and put in ```Punisher The Platoon```, update the settings, and do a Recheck Files and it will pick them up as is.

**Comment by DrSeussFreak** [comment]
So I manually edited the series to update the directory to "Punisher Max The Platoon [2017]" and then manually updated the files to match that pattern as well.  The only other modification I had made, prior to this, was to add "Punisher Max The Platoon" to the alternate search field, as it created itself as "Punisher the Platoon".

Any idea on why it was created incorrectly, or if that is not they case, why it suddenly needed to be updated?

**Comment by evilhero** [comment]
Offhand, and without seeing the logs that happened during the initial scan/rename, it's really difficult to figure out where it got tripped up. 

Based on my little detective work - it was probably on CV's end where they decided to change the series name to the correct title, and from what I can recall of the workflow within Mylar in that case, the series name doesn't get updated (and thereby the location dir, etc). This has happened a few other times, and in these cases it's a manual process whereby the directory has to get renamed, Mylar pointed to the correct series, and then either renaming each issue manually to coincide with the new series title, or use the Alternate Search Name so it picks up the old naming convention. Something to try and account for going forward for sure, but it's really tricky to get it all working in sequence (I'll still try, but it might be kinda fun)....

You view the initial series creation by CV [here](https://comicvine.gamespot.com/wiki/moderation/1360904/) and then the change that occured just yesterday [here](https://comicvine.gamespot.com/wiki/moderation/1380026/) which actually changes the series title from ```Punisher: The Platoon``` to ```Punisher MAX: The Platoon```.

**Comment by DrSeussFreak** [comment]
Fair enough, thanks, I will close this, as I am all set :)
