### ISSUE TITLE
Cannot open Mylar (Synology, git install) 

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1754]
Just ran a git pull on my Synology instance of Mylar and can no longer open Mylar: 

git log reports I'm on 8673896d2f1ac69391c3d3c9bea021e565f2c85b

admin@ds716:/volume1/@appstore/gitmylar/mylar$ python Mylar.py 
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/volume1/@appstore/gitmylar/mylar/mylar/__init__.py", line 36, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "lib/apscheduler/schedulers/base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

**Comment by evilhero** [comment]
See #1740 for a further explanation, but you probably need to do either a sudo apt-get install --reinstall python-pkg-resources or a pip install setuptools depending on your OS / setup.

**Comment by ForumFerret** [comment]
Ah! Yes, that got it squared away. Thanks!
