### ISSUE TITLE
Telegram: notifications send for nzbd, not for torrents

### ISSUE THREAD

**Issue by Bart274** [evilhero/mylar#1757]
I'm using Telegram for my notifications. 
I noticed that when Mylar finds a comic and tries to download it with sabnzbd I get a notification that it has been snatched.
When Mylar finds a comic and tries to download it with uTorrent (using blackhole) it doesn't send a notification that is has snatched an issue and it also doesn't send a notification when the download has been completed.

**Comment by evilhero** [comment]
Once a torrent is sent to your client, Mylar has no way monitor the given client for completeness. There's a way to monitor a remote client using rutorrrent and deluge that exist within Mylar, but nothing in regards to the other clients as it's very time consuming to code something like that (especially when you don't use the application at all).

As far as notifications, it should be notifying using blackhole, so I'll have to look into that - but I'm pretty sure if you send it directly to the utorrent client via Mylar it will notify for that. The only option that's available for notifications after completion with torrents is with post-processing - it can send a notification when post-processing on a torrent that was snatched with Mylar completes (this would happen via manual post-processing).

**Comment by Bart274** [comment]
It doesn't notify me at all for torrents.

Would it be possible to have an option to send notifications for every comic that has been post processed? So it would also notify you of comics that are added to your library that you manually downloaded?

I just noticed something else: I have had several successful downloads now with SabNzbd, there were completed and post processed by Mylar, they were added to my library, but I was notified about them, eventhough I was notified of the snatch by Mylar.

**Comment by Bart274** [comment]
The notifications for every post processing would be awesome (sickrage does that for example) but that's not urgent 😊 

About that last part, indeed a 'not' is missing. Let me put it like this:
- Snatched with sabnzbd: notification sent
- Post processed after download with sabnzbd: no notification sent
- Snatched with blackhole for utorrent: no notification sent
- Post processed after download with utorrent: no notification sent
