### ISSUE TITLE
Error 500 on Clicking "Download" from Weekly Pull List screen

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1779]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/gitmylar/mylar/mylar/webserve.py", line 3499, in MassWeeklyDownload
    if mylar.WEEKFOLDER:
AttributeError: 'module' object has no attribute 'WEEKFOLDER'

Mylar Ver: 7be5b02ff65f2e1af74f1e30434c7d029bd1e356 (fresh clone) 

When trying to click the download button to pull all my recent downloads into the weekly folder, I get the above error. 

the option for storing comics in weekly directory is checked.

**Comment by evilhero** [comment]
Yep dat's a bug. Fix will be in development in a few minutes (just makin' breakfast)...

**Comment by ForumFerret** [comment]
No worries, you enjoy your Thanksgiving! Or your Saturday if you’re not US-ian 😁

I was able to work around it by getting some issues to redownload

**Comment by evilhero** [comment]
This has been fixed in dev - just forgot to tag the issue when I committed cause that's how I roll...  Happy belated turkeys !!
