### ISSUE TITLE
OPDS Story Arcs

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1789]
Up until recently, when navigating to a Story Arc through the OPDS feed, it would only list issues of comics that I have added separately as wanted, it would not list comics that had not been added to the wanted list.

After the most recent update, when navigating to Story Arcs through the OPDS feed, it cannot load the Story Arc at all, my reader app gives me an error that it cannot download the feed.

This is on the latest version on the Development branch running on macOS.

**Comment by LordJay23** [comment]
Hmm, it SHOULD only list issues that have been downloaded.  I'll take a look, thanks.

**Comment by allkindsofralph** [comment]
I just tried this as well and it does not list anything when I go into story arcs

**Comment by LordJay23** [comment]
I thought I had this fixed. Are you running the newest dev build?

**Comment by allkindsofralph** [comment]
I am. I am only 1 commit behind

**Comment by LordJay23** [comment]
So are you getting nothing when you go in to the Story Arcs LIST or when you go into an individual story arc?

**Comment by allkindsofralph** [comment]
I can see the story arc folders but the files for the comics do not appear. They work fine through Ubooquity but not through Mylar OPDS

**Comment by kurnalbert** [comment]
I am seeing the exact same. Lists the story arcs themselves but no comics within them. Also working through Ubooquity here.

**Comment by LordJay23** [comment]
Ok, could you both do the following?  browse to the /opds?cmd=StoryArcs address on your mylar installation, find a link that says /opds?cmd=StoryArc&ArcID=<something> and paste that in?  I wanna know if you're getting an error, or no results.

**Comment by LordJay23** [comment]
Nevermind, I see what it is.

**Comment by LordJay23** [comment]
This will hopefully be fixed by #1798

**Comment by LordJay23** [comment]
Ok, let me know, #1798 is live.

**Comment by kurnalbert** [comment]
Thanks for the work on this so far. I now have comics showing back up in StoryArcs but it is still only showing comics where the series is in the watchlist. Before selecting the StoryArc it shows the total number of comics in the arc correctly, but tapping on it will only show the comics that are in watchlist, it doesn't display any series if they are not in the watchlist.

**Comment by LordJay23** [comment]
Ok, let me look further.  I may not have the correct understanding about how those books are stored, precisely.

**Comment by LordJay23** [comment]
Ok, I think #1804 will fix this.  Really.  This time for sure.

**Comment by LordJay23** [comment]
Ok, so “for sure” is more hyperbole, or at the very least “cartoon quote”.  But still... I think it’ll work.  I have to assume, since I don’t have any examples to test with.  So, fingers crossed.

**Comment by LordJay23** [comment]
Please try the newest build and let me know.

**Comment by kurnalbert** [comment]
Thank you for all your work on this. It's most of the way there, it now lists every comic from the StoryArc, but when I try to download a comic, it will still only download a comic if it is on the main watchlist, any of the others which are listed, it will produce an error and say it was unable to download.

Once again, thank you for all the work you've done on this!

**Comment by LordJay23** [comment]
Closer and closer.  I was actually afraid of that.  But that's not a difficult fix, I think.    I just don't  have the individual issue link pointing in the right place.

**Comment by LordJay23** [comment]
#1806 and fingers crossed :)

**Comment by kurnalbert** [comment]
I feel really bad saying this but I'm afraid it's still the same.

**Comment by LordJay23** [comment]
Don't feel bad, we'll get there :)  Ok, let me look a bit further.

**Comment by LordJay23** [comment]
Ok, new build.  Could you try now?  I cleaned up a few things, and I was successfully able to pull an issue that only existed in the storyarcs folder.

**Comment by kurnalbert** [comment]
This time round, I'm getting an error stating that the comic couldn't be downloaded because it is damaged or encrypted, not an error I have seen before!
I don't know if this helps with tracking down the error, but it is also not showing the thumbnails for comics not in the main watchlist either.

**Comment by LordJay23** [comment]
It won’t since the thumbnails aren’t stored for anything except non-annual issues in the watchlist.   Could you manually go to the link from iPad feed in a browser and tell me what you get?

**Comment by LordJay23** [comment]
From the feed

**Comment by kurnalbert** [comment]
I just wanted to update this issue. For the most part, the OPDS feed is working now, however there are some series which won't correctly download comics when viewed through Chunky. I have had the developer of Chunky have a look at it and he has said that some of the file-links do not work, they fail with the error '<feed><error>Comic Not Found</error></feed>'.

If you wanted to have a look at all, I can share you a link to my OPDS feed.

Thanks!

**Comment by kurnalbert** [comment]
This was specifically series in the Story Arcs directory by the way.

**Comment by barbequesauce** [comment]
OK. It may be Unicode characters or the like. Which arc and specific files are not working? Can you grab a copy of the feed with wget or curl and then post it to pastebin/dpaste/gist etc please?

**Comment by kurnalbert** [comment]
Four out of the five arcs currently in the Story Arcs directory do not work.

An example is Civil War II, pastebin is here: https://pastebin.com/Sgc8qt0c

The Chunky developer said that when fetching issue 529170 it is returning the Comic Not Found error. When trying to view that arc, none of the comics will download at all.

**Comment by barbequesauce** [comment]
So two more pieces of background, please - 

Can you provide a full directory listing (ls -al) showing permissions etc for the file in question please?
Can you provide a debug log including both an attempt to open the file via OPDS and a file check of the series (not arc)? (From the series page, press the “Recheck Files” button at the top.)

**Comment by kurnalbert** [comment]
Thank you for looking in to this.

The directory listing is here: https://pastebin.com/V6ZWRh8T

The debug log when trying to open that file only logs:

2018-05-23 14:15:31 | DEBUG | Recieved OPDS command: Issue
-- | -- | --


The comics in this arc only exist in the Story Arcs section of Mylar, I don't have the series watched on the main list. I wonder if this is where the issue lies as I know we had some problems before with the OPDS feed struggling to display comics that weren't on the main wanted list.

**Comment by evilhero** [comment]
I didn't write the OPDS stuff, and bbq has been trying to help (thanks!) - but I glanced at this really quickly and think I noticed what was happening. Hoping this fixes the problem - please let us know if it does!

**Comment by kurnalbert** [comment]
That has completely fixed the issue! Thank you both so much for all of your work on this!
