### ISSUE TITLE
Can't Start After Latest Development Update - Git Error

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#1790]
Hi,

I get this error when starting Mylar as a service on my linux server.

Starting LSB: starts instance of mylar...
Nov 29 07:33:46 bree mylar[23354]:  * Removing stale /var/run/mylar/mylar.pid
Nov 29 07:33:46 bree mylar[23354]:  * Starting mylar
Nov 29 07:33:48 bree mylar[23354]: local variable 'git_locations' referenced before assignment
Nov 29 07:33:48 bree mylar[23354]: FATAL ERROR
Nov 29 07:33:48 bree mylar[23354]:    ...fail!
Nov 29 07:33:48 bree systemd[1]: mylar.service: Control process exited, code=exited status=1
Nov 29 07:33:48 bree systemd[1]: Failed to start LSB: starts instance of mylar.
Nov 29 07:33:48 bree systemd[1]: mylar.service: Unit entered failed state.
Nov 29 07:33:48 bree systemd[1]: mylar.service: Failed with result 'exit-code'.

I'm not sure if this is a problem on my end with git?  I did notice some changes to git in the last update.

Thanks

**Comment by barbequesauce** [comment]
There was some additional error checking added around your git_path. 

What is your git_path set to in config.ini?

**Comment by kev0153** [comment]
git_path = none

Is this the problem?

**Comment by evilhero** [comment]
It is/ was - yes. 

I just pushed a fix into development for the git_location error, so you have 2 options atm available based on your error: 
- Update and leave everything as is - if your git install location is in your environment path, then it will run as per normal
- Otherwise, you'd have to manually add in the path to the git_path variable in the config.ini.

**Comment by kev0153** [comment]
sorry I'm not up to speed on git as I should be, what should my git_path be?  thanks

**Comment by evilhero** [comment]
Odds are you probably don't have to do anything - if it throws an error then you'll have to change things (as linux users, git gets added to the environment path by default based on location usually). 

But yes, you can find your location just by doing a simple ```whereis git``` on the command line and it will return the results (usually it's in /usr/bin/git or something similar on *nix systems)

**Comment by kev0153** [comment]
that last update seems to have fixed it - thanks
