### ISSUE TITLE
Trying to start Mylar 

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1792]
Any help would be great, not sure what happened. I have installed it new also. Just not starting. 

python Mylar.py
29-Nov-2017 12:27:41 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: /volume1/@appstore/mylar
29-Nov-2017 12:27:41 - INFO :: MainThread : Initializing startup sequence....
29-Nov-2017 12:27:41 - ERROR :: MainThread : No User Comicvine API key specified. I will not work very well due to api limits - http://api.comicvine.com/ and get your own free key.
29-Nov-2017 12:27:41 - INFO :: MainThread : Successfully discovered local IP and locking it in as : 192.168.2.129
29-Nov-2017 12:27:41 - INFO :: MainThread : Config GIT Branch: None
local variable 'git_locations' referenced before assignment
FATAL ERROR

**Comment by barbequesauce** [comment]
Two things there - first, you need a Comicvine API key as it mentions in the readme. Sign up [here](https://comicvine.gamespot.com/login-signup/), then go [here](https://comicvine.gamespot.com/api/) and create a key. That should go into your config.ini. 

For the fatal error, a fix for this went in this morning... update and you should be okay now.

**Comment by evilhero** [comment]
This got fixed in development a short while ago - just make sure you're up-to-date prior to staring

**Comment by lostkt87** [comment]
Yes, I know about the comicvine api. I’m not worried about that one. My system was setup. Then stopped working. I made copies my cache, Mylar.db, and config.ini. I wanted to start new because it was not starting up. Now I see why. 

Thank you for the help will try in a little bit.
