### ISSUE TITLE
UI: request

### ISSUE THREAD

**Issue by allkindsofralph** [evilhero/mylar#1793]
Any chance on getting an option to put tabs for the library page to separate by publisher? Also if you do that to be able to set a default tab for viewing?

**Comment by evilhero** [comment]
I honestly don't see this happening anytime soon. Adding tabs to the main interface is going to make the load time even longer, not to mention having a tab for each publisher would create an insane amount of tabs (and be useless as a result) for those that have large watchlists.

Maybe if/when the UI gets a redesign, but that would be a bigger undertaking than I'm wanting to do by myself atm.

**Comment by allkindsofralph** [comment]
No worries haha thanks for everything tho! I donated last night! thanks for all your work on the project! All the other problems I had were fixed when I switched to a VM running ubuntu and now im switching all my other software over too
