### ISSUE TITLE
adding comics

### ISSUE THREAD

**Issue by kcmccombs** [evilhero/mylar#1808]
when i am trying to add comics the screen refreshes every few seconds and this is some of the log i am also running this on Rockstor and unraid with the same results can someone help with this. Thanks

Timestamp | Level | Message
-- | -- | --
2017-12-08 15:58:33 | WARNING | Error trying to validate/create directory. Aborting this process at this time.
2017-12-08 15:58:33 | WARNING | [DIRECTORY-CHECK] Could not create directory: m_tank/Comics/Superman (2016)[[Errno 13] Permission denied: 'm_tank']. Aborting.
2017-12-08 15:58:33 | INFO | [DIRECTORY-CHECK] Creating comic directory (0777) : m_tank/Comics/Superman (2016)
2017-12-08 15:58:33 | WARNING | [DIRECTORY-CHECK] Could not find comic directory: m_tank/Comics/Superman (2016)

**Comment by evilhero** [comment]
Says right in the error message  - ```permission denied trying to  create the directory```.

Not sure what m_tank is (maybe m:/tank?) , but you have to ensure that the user running mylar has proper permissions to the entire m_tank/Comics directory and subdirectory.

If you're running mylar that was installed thru some third party app (ie. docker) you need to make sure of the perms associated with the docker (and don't run as root).

**Comment by kcmccombs** [comment]
thanks for a quick reply i understand the errors not sure why i am getting them.
m_tank is a poll and comics is  a sub-directory of m_tank my uid gid are the owner of both and the docker i am also the owner of so that's why i am posting here for some advice where to look.

**Comment by evilhero** [comment]
Pretty sure the comics location has to be accessible from within the docker, as it's saying it doesn't have permission/cannot find m_tank itself therefore it cannot create the directory. 

I'm not 100% sure what a poll is, unless it's some kind of mapped mount - but if that's what it is, then it's not accessible from within the docker.

Otherwise, you'd have to inquire with the docker maintainer as I have no affiliation with any of them, let alone run a docker.

**Comment by kcmccombs** [comment]
okay made some changes i got add a comic but now it tells me i have no search providers i have 4 added anything you can help with this thanks again

**Comment by kcmccombs** [comment]
never mind i believe it is working now thanks again

**Comment by hubbcaps** [comment]
Usually I see this issue with SELinux enabled on the host system even when the user inside the container is the same GID:UID as the host user that owns the directory.

Check to see if it's enabled:

`sestatus`

If it says enabled or permissive, SELinux is on.

In that case, you can change the SELinux context of the path you have mylar pointing to on the host system with SELinux:

`chcon -Rt svirt_sandbox_file_t /path/to/volume`

or you could append :z or :Z to the end of the volume to apply the context via the container spin up process as seen here

http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

If this isn't an SELinux issue, you should verify that the host user that owns the path is indeed the same GID:UID as the user running mylar inside the container.
