### ISSUE TITLE
7000 Series randomly added

### ISSUE THREAD

**Issue by Bussterj** [evilhero/mylar#1814]
Hi I tried looking to see if my problem had raised before but couldn't see it, mylar keeps adding 7000 odd series to my library. I have reinstalled a couple of times but it keeps happening.

What logs and such do you need?

Thanks in advance!

**Comment by evilhero** [comment]
Are you trying to add a series initially after a clean install even ? 

Like for it to got thru the process of adding series, it must be initiated in some way first. 

Debug logs would be good - your mylar branch & commit you're running along with the OS. 

Any kind of workflow that you're attempting to do when you notice the 7000+ would help too (that's alot - you would probably hit CV limits before getting that high I'd imagine, but I wouldn't know for sure).

**Comment by Bussterj** [comment]
I added 10 - 20 again all is good I don't touch anything and a week or so later i notice again they have added 7000+ again. I have Mylar installed on a unattended server which I remote connect via windows or use web interface. I added a user and password to the web interface just in case on this reinstall. With this being on my server I don't really notice. I do have Plex installed on the same windows installation (which uses python not sure how python works so don't know if they can affect each other)

Mylar Version:  master
 -- source  build a226658876af19d60d3c4291ea158644731f143b.
Python Version : 2.7.12
--

I looked in my logs folder and there are only 5 files start from the 13th within that it is already searching for comics which it had already added the series for. Looking at my newly added folders and comics it started sometime on the 12th. I there anywhere else I should be looking for logs or older ones?

Cheers

**Comment by evilhero** [comment]
Plex wouldn't affect it, and it's really hard for mylar itself to just add comics as all of the intended ways requires either an item to be searched for, or an exact comicid entered.

It may be that someone was adding stuff in, but again hard to tell without seeing some kind of debug logs. You'd have to recreate and watch to see what happens, kill mylar before it gets to far into the process do that the logs don't roll over and paste that in here so it can be looked over.
