### ISSUE TITLE
No Pull List Data (ref #1742 ) 

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1815]
Hi EH
After updating to latest this morning, I'm getting no data in the pull list for this week, and 

2017-12-14 16:57:37 | INFO | ALT_PULL: 2 PULLBYFILE: False week: 50 year: 2017
-- | -- | --
2017-12-14 16:57:37 | INFO | trying to repopulate to week: 50-2017

in logs during 'recreate pull list' from weekly.  Did the back end get hosed up?

**Comment by evilhero** [comment]
Yep it has got a MySQL reference error - it requires me to fix it manually but I'm probably not going to be able to get to until later tonight unfortunately.

**Comment by ForumFerret** [comment]
No worries, just wanted to make sure it had been brought to your attention.

Thanks!

**Comment by evilhero** [comment]
Should be good to go now. All fixed up!
