### ISSUE TITLE
Only searching for 1 comic.

### ISSUE THREAD

**Issue by DouglasHicks** [evilhero/mylar#1818]
Howdy. I appreciate all the work you're doing!

Im hoping you (or someone out there) can help. Ive got a lot of comics on my want list, but it only seems to search for one and then stop. As you can see here, I marked a bunch of issues of aquaman as WANTED and then did a FORCE CHECK.

It found issue #2 and then stopped doing stuff. I was hesitant to mark this as an issue, so, please excuse me if Im just a dummy and have something set up incorrectly.

note, I XXXX'ed my API keys.
note2, I see that traceback error. Im not sure if related?
note3,version : ba005073ab6dc6a6dfefc7a7e1a0fafe590139d1 

18-Dec-2017 19:19:03 - INFO    :: CP Server Thread-4 : Marking issues: [u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'23', u'24', u'25'] as Wanted
18-Dec-2017 19:19:03 - INFO    :: Thread-24 : Issue Title given as : the drowning part two: full circle
18-Dec-2017 19:19:03 - INFO    :: Thread-24 : search provider order is ['nzb.su']
18-Dec-2017 19:19:03 - INFO    :: Thread-24 : Shhh be very quiet...I'm looking for Aquaman issue: 2 (2016) using nzb.su
18-Dec-2017 19:19:03 - INFO    :: Thread-24 : pausing for 60 seconds before continuing to avoid hammering
18-Dec-2017 19:19:51 - INFO    :: Thread-12 : Update complete
18-Dec-2017 19:20:03 - INFO    :: Thread-24 : no errors on data retrieval...proceeding
18-Dec-2017 19:20:03 - INFO    :: Thread-24 : Found Aquaman (2016) issue: 2 using nzb.su
18-Dec-2017 19:20:03 - INFO    :: Thread-24 : Download URL: https://api.nzb.su/api?apikey=XXXXXXXXXXXXXXXXXX&t=get&id=XXXXXXXXXXXXXXXXXXXXX[VerifySSL:True]
18-Dec-2017 19:20:04 - INFO    :: Thread-24 : download-retrieved headers: {'content-length': '8846', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-disposition': 'attachment; filename="Aquaman_002_(2016)_(Digital)_(BlackManta-Empire).nzb"', 'strict-transport-security': 'max-age=2592000', 'x-dnzb-name': 'Aquaman 002 (2016) (Digital) (BlackManta-Empire)', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'x-dnzb-details': 'https://api.nzb.su/details/XXXXXXXXXXXXXXXXXX', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate', 'date': 'Tue, 19 Dec 2017 01:20:03 GMT', 'x-dnzb-category': 'Books > Comics', 'content-type': 'application/x-nzb'}
18-Dec-2017 19:20:04 - INFO    :: Thread-24 : parameters set to {'nzbname': u'Aquaman.002.2016.Digital.BlackManta-Empire.nzb', 'apikey': 'XXXXXXXXXXXXXXXXXXX', 'name': u'http://192.168.0.12:8090/api?apikey=XXXXXXXXXXXXXXXXXX&cmd=downloadNZB&nzbname=Aquaman.002.2016.Digital.BlackManta-Empire.nzb', 'cmd': 'downloadNZB', 'cat': 'comics', 'priority': '-100', 'mode': 'addurl', 'output': 'json'}
18-Dec-2017 19:20:04 - INFO    :: Thread-24 : sending now to http://localhost:8080/api
18-Dec-2017 19:20:04 - INFO    :: Thread-24 : {u'status': True}
18-Dec-2017 19:20:04 - ERROR   :: Thread-24 : Uncaught exception: Traceback (most recent call last):
  File "c:\Mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\Mylar\mylar\search.py", line 1874, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
  File "c:\Mylar\mylar\search.py", line 255, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
  File "c:\Mylar\mylar\search.py", line 1624, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "c:\Mylar\mylar\search.py", line 2476, in searcher
    sendtosab = ss.sender()
  File "c:\Mylar\mylar\sabnzbd.py", line 52, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
KeyError: 'nzo_ids'

18-Dec-2017 19:20:16 - INFO    :: CP Server Thread-5 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
18-Dec-2017 19:20:16 - INFO    :: CP Server Thread-5 : Starting postprocessing for : Aquaman.002.2016.Digital.BlackManta-Empire
18-Dec-2017 19:20:16 - ERROR   :: Post-Processing : [POST-PROCESSING] Unable to locate downloaded file within items I have snatched. Attempting to parse the filename directly and process.
18-Dec-2017 19:20:16 - INFO    :: Post-Processing : there are 1 files.
18-Dec-2017 19:20:16 - INFO    :: Post-Processing : I have located 1 files that I should be able to post-process. Continuing...
18-Dec-2017 19:20:16 - INFO    :: Post-Processing : manual list: [{'ComicName': u'Aquaman', 'IssueID': u'538479', 'ComicLocation': u'F:\\tempcomics\\Aquaman.002.2016.Digital.BlackManta-Empire\\Aquaman 002 (2016) (Digital) (BlackManta-Empire).cbr', 'Series': 'Aquaman', 'One-Off': False, 'AltSeries': None, 'IssueNumber': u'2', 'ComicID': u'91738'}]
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for F:\tempcomics\Aquaman.002.2016.Digital.BlackManta-Empire\Aquaman 002 (2016) (Digital) (BlackManta-Empire).cbr
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for Aquaman issue: 2
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: F:/Comics\Aquaman (2016)
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING] move successful to : F:/Comics\Aquaman (2016)\Aquaman 2 (2016).cbr
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Aquaman issue: 2
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Now checking files for Aquaman (2016) in F:/Comics\Aquaman (2016)
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : there are 6 files.
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Updated the status of 24 issues for Aquaman (2016) that were not found.
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Total files located: 6
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] I have physically found 6 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 6 / 30 ]
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING] Post-Processing completed for: Aquaman issue: 2
18-Dec-2017 19:20:33 - INFO    :: Post-Processing : [POST-PROCESSING] Manual post-processing completed for 1 issues.

**Comment by evilhero** [comment]
Well there's no need to mark them as wanted and do a force check. Marking them as wanted does an immediate rss+api search for each given issue sequentially. It can take upwards of a few minutes per issue tho as it has to wait between api calls to the indexers so as to not get banned.

The error tho would stop further searches due to the traceback. It looks like you have completed download laid handling enabled for sabnzbd, as well as you're using the comicRN.py script in your sabnzbd for comics. If you do, it's either one or the other (not both) - if you enable completed download handling, remove the comicRN.py script so it doesn't run on completion.

**Comment by DouglasHicks** [comment]
Wow. I appreciate the quick response.

Roger that on the force check/wanted. Thanks.

I only had SAB set to run the post processing script but I went ahead and disabled ALL post processing in SAB and Mylar, and I still seem to be getting the traceback error. Ive deleted/redownloaded Mylar and also re-installed Python in an attempt to resolve. I saw in another thread you asked the guy to remove all .pyc files ...so I tried that, too. Ha.

It still only seems to work for the first comic, and then stalls. No matter how long I leave it alone. If I initiate another force check, it will do one file, and then stall.

Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\search.py", line 1790, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "C:\Mylar\mylar\search.py", line 255, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
File "C:\Mylar\mylar\search.py", line 1624, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "C:\Mylar\mylar\search.py", line 2476, in searcher
sendtosab = ss.sender()
File "C:\Mylar\mylar\sabnzbd.py", line 52, in sender
'nzo_id': ''.join(sendresponse['nzo_ids']),
KeyError: 'nzo_ids'

**Comment by evilhero** [comment]
Are you running an old version of sabnzbd by chance?

Can you provide what your settings are on the Download Settings tab within mylar? Also what your Quality & Post-Processing tab as well?
