### ISSUE TITLE
Manual Post Processing moving comics to /root/comics instead of destination dir

### ISSUE THREAD

**Issue by xkelly** [evilhero/mylar#1820]
Destination directory is set as /volume1/media/ebooks/comics. Post processing hand off from NZBGet puts them in this directory. When I manually post process files, Mylar creates a comics folder in the root of the system drive and moves them there. Been filling up my system drive. Running a Synology NAS. Not using the package. Just a git setup. On the dev branch. Was on docker, but gave up after being 120 commits behind. i checked the config.ini and all paths look correct.

Thoughts?

**Comment by evilhero** [comment]
It sounds like your config isn't being saved properly or the like, as Mylar would only create series directories beneath the destination_dir location in the config.ini (named the Comic Location in the GUI). Shutdown Mylar and then check on the config.ini to ensure that the location is set properly. Then when you start it up, check the config GUI to make sure it says the same thing. But really, without seeing a full debug log of a manual post-process, it's almost impossible to figure out based on just a description of the problem. 

As far as the docker, most of the dockers are forcibly set to go against the master branch - which development just merged with a few days ago, thus the 120+ commit upgrade requirement. There were probably some issues based on the size of the upgrade that might have caused some problems - the easiest would have been to just create a new docker with your existing config.ini, mylar.db and cache directories dropped into the new location.

**Comment by xkelly** [comment]
Hey there. A few updates:

1. I did what you suggested and stopped mylar, checked the config file. It shows the correct destination directory, just as before: destination_dir = /volume1/media/ebooks/comics. Restarted mylar and checked the config GUI, it also shows correct, same as before. Weird thing is, the nzbget user name and password are incorrect, so I'm wondering, can it be picking up a different config.ini than the one in /opt/mylar?

Stopping mylar:  i don't know what the command is to stop it. ended uping disabling the auto start task and restarting the nas. What is the command to stop mylar in terminal? I'm using this command to start it:  python /opt/Mylar/Mylar.py -d

2. Regarding docker. For convenience and ease of tweaking, I would prefer to use docker. Just wish someone would publish a reliable package on the dev branch. I followed your instructions, though, and am not on the latest master. 

And random: did try to install the synocommunity package in order to put that on the dev branch (had it working on my previous syno nas), but the package won't start after install. Not sure why (docker and the git installs were both off). Still prefer docker, so no big deal. 

Want to try and fix the git install, but might end up sticking with docker at the end of the day.

Thanks.

**Comment by evilhero** [comment]
It's possible it's picking up a different ini - if you go to the Configuration page, on the first tab it will show the location where it's loading the ini from.

If you're using a git install, it will load the ini from the default location which is the root of mylar itself. However the package installers (like synology) tend to put the ini in a different location. The location can be changed (if not using the default location) by simply using the config switch on the command line when starting mylar.

I have no affiliation with any of the dockers, plus I don't run docker so I'm really unable to help with the docker stuff at this time. There has been talk about bringing back the ability to switch branches from within the GUI, which would allow dockers to use the dev branch in theory, but most dockers are locked to the master branch on startup.

Is the docker working atm on the master branch for you currently? If it helps, the master branch is the same as the development branch at the moment at least.

**Comment by xkelly** [comment]
Hey - happy holidays.

Yes, docker is working for me on the master branch. Will use that for now.
