### ISSUE TITLE
NZBHydra Issue

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1833]
Hi -

Mylar searches through Hydra and finds issues, but the nzb file isn't being pushed to NZBGet. It works with apps like Sonarr and Radarr. Any ideas? 

logger.warn('Unable to send nzb file to NZBGet. There was a parameter error as there are no values present: %s' % nzbget_params)
NameError: global name 'nzbget_params' is not defined

**Comment by glberen** [comment]
I think I fixed this with a setting in Hydra. Turns out it wasn't a mylar problem looks like.

That said, mylar reports that issues were not found, however when I look at the search history in Hydra, multiple results are returned. Any idea why Mylar isn't finding issues?

**Comment by evilhero** [comment]
Not related to 1296 at all - it does however say right in the log you posted what the problem is ```uh-oh: [Errno 111] Connection refused```

Check your nzbget settings within mylar - something is either entered wrong or missing as it cannot connect to your nzbget instance.

**Comment by glberen** [comment]
That IP is the Hydra IP. Do I need to enter the NZBGet IP instead?

**Comment by evilhero** [comment]
You need to enter your nzbget information into the nzbget section under downloaders within Mylar. 

Mylar can't send nzbs to your client if it's not a download client (nzbhydra is not a downloader, it's a search utility)

**Comment by glberen** [comment]
You were right. 

I found the problem. It was just me being super-dumb. Sorry for taking up your time with this. I appreciate your help.

**Comment by evilhero** [comment]
No worries - glad it was an easy fix!
