### ISSUE TITLE
Sorry, but XXXXX is not a comic archive!

### ISSUE THREAD

**Issue by CovertDad** [evilhero/mylar#1840]
I've recently installed Mylar on my Mac system, and am getting a very curious error.

When it downloads new books from Usenet, on some I get the following error:
`Failed to convert cbr to cbz - check permissions on folder : /Applications/Mylar/cache and/or the location`

When I look further into the log, there's an even more curious error:
`Sorry, but /Applications/Mylar/cache/mylar_ZaCq7s/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr  is not a comic archive!`

I've included what I think is the pertinent log information:
`09-Jan-2018 12:33:14 - INFO    :: Thread-12 : I have located 2 files that I should be able to post-process. Continuing...
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : manual list: [{'ComicName': u'Manifest Destiny', 'IssueID': u'587444', 'ComicLocation': u'/Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.027.2017.Digital.Zone-Empire/Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr', 'Series': 'Manifest Destiny', 'One-Off': False, 'AltSeries': None, 'IssueNumber': u'27', 'ComicID': u'69138'}, {'ComicName': u'Manifest Destiny', 'IssueID': u'601826', 'ComicLocation': u'/Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.029.2017.Digital.Zone-Empire/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr', 'Series': 'Manifest Destiny', 'One-Off': False, 'AltSeries': None, 'IssueNumber': u'29', 'ComicID': u'69138'}]
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : [DUPECHECK] Duplicate check for /Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.027.2017.Digital.Zone-Empire/Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : [POST-PROCESSING] [1/2] Starting Post-Processing for Manifest Destiny issue: 27
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : Filepath: /Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.027.2017.Digital.Zone-Empire/Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : Filename: Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : New_Folder: /Applications/Mylar/cache/mylar_ft0tSx
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : New_Filepath: /Applications/Mylar/cache/mylar_ft0tSx/Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:14 - INFO    :: Thread-12 : Attempting to move: move
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : Sorry, but /Applications/Mylar/cache/mylar_ft0tSx/Manifest Destiny 027 (2017) (Digital) (Zone-Empire).cbr  is not a comic archive!

09-Jan-2018 12:33:15 - INFO    :: Thread-12 : None
09-Jan-2018 12:33:15 - WARNING :: Thread-12 : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Mylar/cache and/or the location where Mylar is trying to tag the files from.
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media/comics/Manifest.Destiny.(2013)
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : [DUPECHECK] Duplicate check for /Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.029.2017.Digital.Zone-Empire/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : [POST-PROCESSING] [2/2] Starting Post-Processing for Manifest Destiny issue: 29
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : Filepath: /Users/[redacted]/Downloads/complete/comics/Manifest.Destiny.029.2017.Digital.Zone-Empire/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : Filename: Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : New_Folder: /Applications/Mylar/cache/mylar_ZaCq7s
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : New_Filepath: /Applications/Mylar/cache/mylar_ZaCq7s/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr
09-Jan-2018 12:33:15 - INFO    :: Thread-12 : Attempting to move: move
09-Jan-2018 12:33:16 - INFO    :: Thread-12 : Sorry, but /Applications/Mylar/cache/mylar_ZaCq7s/Manifest Destiny 029 (2017) (Digital) (Zone-Empire).cbr  is not a comic archive!

09-Jan-2018 12:33:16 - INFO    :: Thread-12 : None
09-Jan-2018 12:33:16 - WARNING :: Thread-12 : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Mylar/cache and/or the location where Mylar is trying to tag the files from.
09-Jan-2018 12:33:16 - INFO    :: Thread-12 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Media/comics/Manifest.Destiny.(2013)
09-Jan-2018 12:33:16 - INFO    :: Thread-12 : [POST-PROCESSING] Manual post-processing completed for 2 issues [FAILED: 4]`

I've extracted the contents of the cbr file, either through UnRar (5.50) or through an extraction program (Keka, 7Zip on Windows), there are no reported errors.  Also, if I extract the cbr and recompress as a cbz, it imports just fine.

Any clue as to what could be causing this error?

**Comment by evilhero** [comment]
This seems to only occur on MACs for some reason, but the problem is that it cannot locate your unrar executable in order to unrar. 

There's a ctsettings.ini file located in the lib/comictaggerlib/ctsettings/ of the mylar folder where you can indicate the full path to your unrar binary. You will have to restart mylar after making the ini change.
