### ISSUE TITLE
New forms based login page not respecting http_root on redirects

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1842]
So I pulled the most recent code, and changed the authentication method from 'Basic' to 'Forms' (mostly because I wanted my password manager to be able to auto-fill). The problem is that when I go to mylar and it redirects me to the login page, it doesn't include the http_root that I specified (for reverse proxy). If I edit the URL in the address bar and manually add the appropriate http_root to it, it almost works; first it redirects to a different address that puts my username and password in clear text directly in the address bar, but is also missing the http_root again, then when I add it back manually again, it redirects me to the root of my server (http://server.domain.com (without the "/mylar"), and then when I add the http_root back again it finally brings me to the Mylar home page.

**Comment by evilhero** [comment]
Should be all working now - thanks @barbequesauce for helping with the testing as I don't run a reverse proxy.

**Comment by skywayskase** [comment]
Confirming that this is now working as expected. Thanks for the quick turn around!
