### ISSUE TITLE
Torznab search provider not working

### ISSUE THREAD

**Issue by bartoncasey** [evilhero/mylar#1850]
No amount of checkbox fiddling will allow one to enable Torznab searching. I'm 90% sure it's because of the typo in the preferred provider order array:

https://github.com/evilhero/mylar/blob/053626a96bd1a8601b2ca87066261408e8c1cd30/mylar/config.py#L824

**Comment by evilhero** [comment]
Yep that's probably a correct guess. Not sure how it went this long without getting noticed, but definitely would cause problems.

When I get back to a machine, I'll push out the fix. Thanks for even finding and mentioning the incorrect reference.

**Comment by barbequesauce** [comment]
Possible fix in #1851
