### ISSUE TITLE
Search provider order; request gui to alter order

### ISSUE THREAD

**Issue by samkatakouzinos** [evilhero/mylar#1860]
Please allow the gui to alter the search order in config.ini.

[Providers]
provider_order =

**Comment by evilhero** [comment]
I'll mark this as an enhancement, but doing drag&drop type stuff in the GUI is not a strong suit of mine in any way, shape or form. 

I doubt this will get done anytime soon, but I'll add it as an enhancement just in case I happen to get around to it, or someone else wants to help out and do a PR for it.
