### ISSUE TITLE
URL Disappears after Login

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1862]
After I login I am redirected to index/, it drops the URL from the address bar

**Comment by evilhero** [comment]
This just got mentioned a little while ago, but we've been unable to duplicate it on both a non-reverse proxy setup, and a reverse-proxy setup. Can you give more info as to your setup:

What OS are you running? 
Are you using a reverse proxy, or some other sort of redirect?
Which branch/commit are you running ?

**Comment by DrSeussFreak** [comment]
Windows 10, nothing special is in place, straight login 

Version: 413da0f46c2cf4b1f020945f810d1e56efb4c2c4 (development)

**Comment by evilhero** [comment]
Ok, looks like it's a problem that's only occurring on Windows 10 machines that have Mylar locally installed regardless of browser (trying to figure out what's going on atm).

**Comment by DrSeussFreak** [comment]
let me know if you need me to do any testing

**Comment by DrSeussFreak** [comment]
I've updated, I will let you know if it comes back.  And best commit comment ever :)

**Comment by DrSeussFreak** [comment]
Thanks, issue resolved!
