### ISSUE TITLE
annuals not counting towards the "have" number of issues, but is still counted

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1866]
![image](https://user-images.githubusercontent.com/15702664/36627716-41f88e7e-1947-11e8-94e0-93bde19a323b.png)

so as you can see in the screenshot, all issues with downloaded annuals have the small issue that the maximum number of available issues doesn't include the number of annuals, but the annuals are still counted.

Version: a1709db0a7ef163058614d63400833acd711644e (development)

**Comment by evilhero** [comment]
Was this after a pp run, or after a refresh of the series occurred? Normally when it flips to orange, and the have is greater than the total, when the system cycles it rechecks the series for validity.

I'm assuming you have annual integration enabled - but I haven't been able to duplicate this as of yet just by straight running mylar normally..

If you could provide a debug log of the recheck files, it might help narrow down the count discrepancies.

**Comment by verbumfeit** [comment]
I had the same Problem, it was resolved when I refreshed the series

**Comment by HypKin** [comment]
yep, just tried it, refreshing does the trick!
