### ISSUE TITLE
Change slack notification to put title in text

### ISSUE THREAD

**Issue by francispeixoto** [evilhero/mylar#1867]
The slack notification currently displays the title of the comic as an attachment, meaning that slack notifications will only display "Download and Postprocessing completed" until the user opens it to see which comic was processed. Comic book Wednesday means a lot of repetitive and low information notifications coming in all at once.

Putting the title directly in the notification text rather than an attachment makes that notification much more useful at a glance.

**Comment by barbequesauce** [comment]
check fixes #1869 & #1868 for dev & master respectively.
