### ISSUE TITLE
Manual Meta-Tagging not removing CBR

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1875]
when I manual meta-tag a file in Mylar, it creates the CBZ and fails to remove the CBR

**Comment by evilhero** [comment]
From what screen are you trying the metatagging from? Are you up to date on your branch? (bunch of fixes happened recently over last few days that might affect this)

**Comment by DrSeussFreak** [comment]
I am up-to-date running Version: 1304866298e06694ba87887beec335fd16e174ce (development).

I am in the comics screen, and it makes no difference if I select manual metatag for the entire series, or just on an individual issue

**Comment by evilhero** [comment]
Yep, was a problem with the new metatagging code that wasn't expecting the file to remain in the original location. Should be all fixed now in development!

**Comment by DrSeussFreak** [comment]
Confirmed working now, thanks!
