### ISSUE TITLE
Error after comic has been added to utorrent

### ISSUE THREAD

**Issue by arqcan** [evilhero/mylar#1876]
Mylar Version: development
-- git build 79a1fd7aec0c2851075cdb95e578c0f0951d63e8.
Python Version : 2.7.14

I have an issue that when i manually search for a comic, via the magnifying glass, it finds the torrent and adds it to utorrent. It then generates the following error, I've included a few more bits of the log;

Uncaught exception: Traceback (most recent call last):  File "c:\Mylar\mylar\logger.py", line 177, in new_run    old_run(*args, **kwargs)  File "c:\Python27\lib\threading.py", line 754, in run    self.__target(*self.__args, **self.__kwargs)  File "c:\Mylar\mylar\webserve.py", line 1409, in queueissue     foundcom, prov = search.search_init(ComicName, ComicIssue,  ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate,  IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode,  ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe,  allow_packs=AllowPacks)  File "c:\Mylar\mylar\search.py", line 317, in search_init     findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear,  Publisher, IssueDate, StoreDate, searchprov, send_prov_count,  IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion,  SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID,  issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName,  allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit,  manual=manual)  File "c:\Mylar\mylar\search.py", line 1706, in NZB_SEARCH    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host)  File "c:\Mylar\mylar\search.py", line 2473, in searcher     rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear,  link, nzbprov, nzbid)  #nzbid = hash for usage with public torrents  File "c:\Mylar\mylar\rsscheck.py", line 1106, in torsend2client    torrent_info['hash'] = tiTypeError: list indices must be integers, not str
--
2018-02-28 21:24:51 | INFO | label mylarcomics successfully applied
2018-02-28 21:24:51 | INFO | Hash: FC8C29849301E72BC5D6D70670E047BFFA1C52C7
2018-02-28 21:24:51 | INFO | Successfully added torrent to uTorrent client.
2018-02-28 21:24:51 | DEBUG | [WWT] Saved torrent file to : c:\Mylar\cache\Darth_Vader_12_2018.torrent
2018-02-28 21:24:42 | DEBUG | Grabbing torrent [id:173043] from url:https://worldwidetorrents.me/download.php
2018-02-28 21:24:42 | DEBUG | filename for torrent set to : c:\Mylar\cache\Darth_Vader_12_2018.torrent
2018-02-28 21:24:42 | INFO | matched on Darth Vader
2018-02-28 21:24:42 | DEBUG | Torrent Provider:WWT
2018-02-28 21:24:42 | DEBUG | link:173043
2018-02-28 21:24:42 | DEBUG | ComicName:Darth Vader
2018-02-28 21:24:42 | DEBUG | link given by: WWT

However I just noticed that when the download finished the download was processed via the monitored folder. Is the error anything to worry about, what is happening when the program errors out?

**Comment by evilhero** [comment]
It's either that you're pulling from wwt, or that you're using uTorrent and the response thrown back by either/both is not what Mylar is expecting.

I'll have to check into this more as I don't use either of those options, and I'll have to replicate it to figure out what's happening.

The error itself is just supposed to return a check to make sure everything has started on the client and to log the values for retry, and to update the status' correctly.. Worst case is, the client returns an error and mylar would think it didn't  downloaded ok (I'm guessing)

**Comment by arqcan** [comment]
Thanks for getting back to me, it looks like its working for a manual search and i can put up with the error.

I have noticed that no new comics were picked up yesterday despite me being able to see them in the RSS feeds that I have in utorrent or on WWT. When i do a manual search for all comics it will find one missing and then  and then stops searching. I left if overnight to see if it would catch up but nothing was pulled down through the night. Do you have any suggestion as to what this issue might be?

**Comment by evilhero** [comment]
The error is probably stopping the search process entirely if I were to guess. So we'll have to track down as to why it's occuring and fix it.

**Comment by evilhero** [comment]
Argh - ok, that was a stupid mistake. Not sure how that got by exactly without throwing the error previously, but it should be able to send now without any further error messages after the successful send. Let me know if it's not working for you though...

**Comment by arqcan** [comment]
My apologies, this error has now been fixed.
