### ISSUE TITLE
Manual Metatag with existing CBZ file deletes file

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1881]
If I am in a series page, and choose to manually metatag the whole series, as I manually added the series, the existing CBZ files are removed altogether...

**Comment by DrSeussFreak** [comment]
I am on 

Version: dbb36711bb20b9d7b852c82a3d8f99b0e1f0fdad (development)

**Comment by evilhero** [comment]
Crap - yeah I can confirm this is a big bug. 

I'm looking at it right now to see if I can quickly push out a fix...

**Comment by evilhero** [comment]
All Fixed in development now. 

Not sure how I missed that - hopefully you didn't loose too much cause of that stupid thing. Sorry dude, that one was completely my fault because of the post-processing/metatagging changes that went into development late last week.

**Comment by DrSeussFreak** [comment]
Nothing that I couldn't easily replace :)

Confirmed the fix in Version: 284ddb822c2aed4fd5515568d57c55b7c96b04e9 (development)
