### ISSUE TITLE
Reset to "No Password"?

### ISSUE THREAD

**Issue by dmz94** [evilhero/mylar#1887]
First - a big thank you to EH for all the hard work and effort. The tools keeps getting better and better. 

I use LastPass and it accidentally filled in a user name and password for Mylar while I was updating some settings in configuration. 

It took me a few tries but I guessed which one. So I am back in. 

I am trying to set it back to "no password" but I cannot seem to get it to do so. I am restarting Mylar. 

When I set it to "none" - the account and password fields disappear so I cannot see what is in there. If I leave it as one of the secure options, I clear the fields but no joy. 

Ideas? Thanks again...

**Comment by barbequesauce** [comment]
I had this as well. An interim fix is to shut down and edit those lines in the config.ini. 

If you want to disable login completely you’ll need to remove the http_username and http_password lines entirely and set authentication to 0.

**Comment by dmz94** [comment]
All sorted - thanks! I had looked there but it did not click on which entries I should have chnaged.

I appreciate the help. 

I imagine it is low priority but it would be a nice thing to fix....

Thanks again!
