### ISSUE TITLE
Add Comic by ComicID?

### ISSUE THREAD

**Issue by Tucker28** [evilhero/mylar#1888]
I am trying to add A+X and the + in the title I am sure is the problem... as it brings up 40 pages of anything with an A and X in the title. Using quotes doesn't affect the search. The Comicvine ID is 53535, so I figured I would try to add it like that, but that doesn't work either.

**Comment by evilhero** [comment]
Make sure you're up to date on dev - the fix for the '+' in the series title went into dev 2 days ago.

Otherwise to add directly by ID you enter in the full  comicid into the search bar (ie. for series on cv, the format is 4050-XXXXXX)

**Comment by Tucker28** [comment]
Thank You! That worked. I'll update tonight.
Cheers!
