### ISSUE TITLE
IssueStatus not updated to Downloaded after Post-Processing Completes, Original File not Deleted from Download Location

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1890]
I have always been set to move and not copy. 

Instead of piling up in post-processing temp space, the file just gets overwritten repeatedly, but with metadata tagged and renamed. Original file does not get deleted. The process does not clone any files in the cache folder.

Selecting the [Rechecki Files] button on a Comic Detail page updates the issue status and allows duplicate detection handling to occur on the original file.

https://pastebin.com/RsrBt7hN

**Comment by evilhero** [comment]
This is the way it works (now at least);
- file gets copied to cache folder for metatagging.
- metatagging takes place, original file is retained in cache folder temporarily
- new file gets moved to series dir
- if it's successful, clean up happens where it deletes both cache folder & original location
- counts get updated and the status updated.

Based on your logs, it's not tidying up properly (so it's leaving the original location), and then it's crapping out during the update so it can never update the counts and the status properly. 

But all of this should have been fixed a few dev commits ago - are you running an up-to-date version of the development branch of Mylar ?

**Comment by lodasi** [comment]
Yes, I updated about an hour before the logs posted.

**Comment by evilhero** [comment]
Ok, then give me the setup you're using - as of this point in time, it's either isolated to your OS (which looks like Windows, which is highly probable), or your settings. By setup I mean, OS, OS-version, if your series folders reside on the same machine as the one running Mylar (ie. if they're stored on a NAS as an example), etc...

**Comment by lodasi** [comment]
Windows 10. Series folders are on a drive mounted on that computer. No permissions issues or drive size concerns.

**Comment by evilhero** [comment]
k, I'll have to fire up windows to test this out then. At this particular moment in time, it would appear it's something particular to just windows (again, surprise, surprise!). Not sure if I get this out today. given the March Break time - but I'll see what I can figure out...

**Comment by psychoflame** [comment]
I actually had this exact same problem running mylar from a freebsd jail as well. I moved my install from freebsd to linux so not sure if its still an issue on freesd
