### ISSUE TITLE
Unable to install mylar - Receiving error 

### ISSUE THREAD

**Issue by sbalani** [evilhero/mylar#1892]
File "c:\Mylar\Mylar.py", line 93
    print 'Expecting subcommand with the maintenance positional argumeent'
                                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Expecting subcommand with the maintenance positional argumeent')?

I am getting this error whilst attempting to instlal. Seems to be a problem with the code?

Followed these instructions to install, https://www.htpcguides.com/install-mylar-windows-usenet-comics/

Although they seem rather outdated...is there a newer set of instructions?

**Comment by evilhero** [comment]
How exactly are you running Mylar?

It looks like you're getting a python 3 related error (python 3 requires you to put parenthesis around print statements), but Mylar only works with the 2.7.x branch.

Nothing wrong with the startup code, tested against several variant OS' including windows - it would seem to be a problem with the way you're starting the program (double-clicking on the Mylar.py ? Having both python 3 & 2 installed and running the wrong command to target python 2? etc)
