### ISSUE TITLE
json import fails

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1893]
latest dev, fresh install.  json import fails with the following: 

16-Mar-2018 12:23:16 - INFO    :: mylar.shutdown.1175 : MAIN : Mylar is shutting down...
16-Mar-2018 12:24:10 - INFO    :: mylar.getVersion.112 : MainThread : Branch detected & set to : development
16-Mar-2018 12:24:10 - INFO    :: mylar.daemonize.336 : MAIN : Daemonized to PID: 9300
16-Mar-2018 12:24:10 - INFO    :: mylar.main.224 : MAIN : [MAINTENANCE-MODE] Initializing maintenance mode
16-Mar-2018 12:24:10 - INFO    :: mylar.main.242 : MAIN : [MAINTENANCE-MODE] file indicated as being in json format - path accepted as jsonexport.json
16-Mar-2018 12:24:10 - INFO    :: mylar.json_import.71 : MAIN : [MAINTENANCE-MODE][JSON-IMPORT] Found 58 series within json listing. Preparing to mass import to existing db.
16-Mar-2018 12:24:11 - INFO    :: mylar.importIT.123 : MAIN : [MAINTENANCE-MODE][JSON-IMPORT] Found 58 series in previous db. Preparing to migrate into existing db.
16-Mar-2018 12:24:11 - INFO    :: mylar.importIT.126 : MAIN : [MAINTENANCE-MODE][JSON-IMPORT] [1/58] now attempting to add 100082 to watchlist...
16-Mar-2018 12:24:11 - ERROR   :: mylar.excepthook.155 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 334, in <module>
    main()
  File "Mylar.py", line 244, in main
    j = ij.json_import()
  File "/volume1/@appstore/gitmylar/mylar/mylar/maintenance.py", line 72, in json_import
    self.importIT()
  File "/volume1/@appstore/gitmylar/mylar/mylar/maintenance.py", line 133, in importIT
    maintenance_info = importer.addComictoDB(re.sub('4050-', '', x['ComicID']).strip(), calledfrom='maintenance')
  File "/volume1/@appstore/gitmylar/mylar/mylar/importer.py", line 91, in addComictoDB
    helpers.ComicSort(comicorder=mylar.COMICSORT, imported=comicid)
  File "/volume1/@appstore/gitmylar/mylar/mylar/helpers.py", line 771, in ComicSort
    if comicorder['LastOrderNo'] == '999':
TypeError: 'NoneType' object has no attribute '__getitem__'

Json to be imported is: 

root@ds716:/volume1/@appstore/gitmylar/mylar# cat jsonexport.json 
[{"ComicID": "100082"}, {"ComicID": "100709"}, {"ComicID": "100712"}, {"ComicID": "100753"}, {"ComicID": "101195"}, {"ComicID": "101484"}, {"ComicID": "101960"}, {"ComicID": "102764"}, {"ComicID": "102917"}, {"ComicID": "104818"}, {"ComicID": "104981"}, {"ComicID": "105506"}, {"ComicID": "105965"}, {"ComicID": "106133"}, {"ComicID": "106705"}, {"ComicID": "107368"}, {"ComicID": "107493"}, {"ComicID": "107513"}, {"ComicID": "108548"}, {"ComicID": "108800"}, {"ComicID": "108809"}, {"ComicID": "17993"}, {"ComicID": "32910"}, {"ComicID": "45154"}, {"ComicID": "79398"}, {"ComicID": "85094"}, {"ComicID": "85558"}, {"ComicID": "86113"}, {"ComicID": "88214"}, {"ComicID": "91078"}, {"ComicID": "91098"}, {"ComicID": "91273"}, {"ComicID": "91298"}, {"ComicID": "91738"}, {"ComicID": "91774"}, {"ComicID": "92373"}, {"ComicID": "92542"}, {"ComicID": "92557"}, {"ComicID": "92569"}, {"ComicID": "92577"}, {"ComicID": "92728"}, {"ComicID": "92966"}, {"ComicID": "93179"}, {"ComicID": "93381"}, {"ComicID": "93948"}, {"ComicID": "94296"}, {"ComicID": "94643"}, {"ComicID": "95201"}, {"ComicID": "95211"}, {"ComicID": "95242"}, {"ComicID": "95402"}, {"ComicID": "95596"}, {"ComicID": "96284"}, {"ComicID": "96661"}, {"ComicID": "98910"}, {"ComicID": "98913"}, {"ComicID": "99261"}, {"ComicID": "99849"}]

**Comment by ForumFerret** [comment]
That lets the import get started; now failing on the following: 

17-Mar-2018 14:56:50 - INFO    :: mylar.importIT.126 : MAIN : [MAINTENANCE-MODE][JSON-IMPORT] [3/58] now attempting to add 100712 to watchlist...
17-Mar-2018 14:56:53 - INFO    :: mylar.addComictoDB.113 : MAIN : Now adding/updating: X-Men: Blue
17-Mar-2018 14:56:53 - INFO    :: mylar.addComictoDB.166 : MAIN : Sucessfully retrieved details for X-Men: Blue
17-Mar-2018 14:56:53 - INFO    :: mylar.addComictoDB.172 : MAIN : Previous version detected as None - seeing if update required
17-Mar-2018 14:56:53 - INFO    :: mylar.addComictoDB.245 : MAIN : Directory (/volume1/Diskstation/Media/Comics/X-Men Blue (2017)) already exists! Continuing...
17-Mar-2018 14:56:55 - INFO    :: mylar.getImage.3415 : MAIN : Attempting to retrieve the comic image for series
17-Mar-2018 14:57:00 - INFO    :: mylar.addComictoDB.330 : MAIN : Sucessfully retrieved issue details for X-Men: Blue
17-Mar-2018 14:57:05 - INFO    :: mylar.manualAnnual.1039 : MAIN : Successfully integrated 1 annuals into the series: X-Men: Blue
17-Mar-2018 14:57:05 - INFO    :: mylar.updateissuedata.1092 : MAIN : Now adding/updating issues for X-Men: Blue
17-Mar-2018 14:57:10 - INFO    :: mylar.manualAnnual.1039 : MAIN : Successfully integrated 1 annuals into the series: X-Men: Blue
17-Mar-2018 14:57:10 - INFO    :: mylar.addComictoDB.400 : MAIN : Updating complete for: X-Men: Blue
17-Mar-2018 14:57:10 - INFO    :: mylar.forceRescan.930 : MAIN : [FILE-RESCAN] Now checking files for X-Men: Blue (2017) in /volume1/Diskstation/Media/Comics/X-Men Blue (2017)
17-Mar-2018 14:57:10 - INFO    :: mylar.traverse_directories.1170 : MAIN : there are 22 files.
17-Mar-2018 14:57:15 - INFO    :: mylar.forceRescan.1451 : MAIN : [FILE-RESCAN] Updated the status of 1 issues for X-Men: Blue (2017) that were not found.
17-Mar-2018 14:57:15 - INFO    :: mylar.forceRescan.1453 : MAIN : [FILE-RESCAN] Total files located: 22
17-Mar-2018 14:57:15 - INFO    :: mylar.forceRescan.1553 : MAIN : [FILE-RESCAN] I have physically found 22 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 22 / 24 ]
17-Mar-2018 14:57:15 - INFO    :: mylar.addComictoDB.442 : MAIN : Checking this week pullist for new issues of X-Men: Blue
17-Mar-2018 14:57:16 - ERROR   :: mylar.excepthook.155 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 334, in <module>
    main()
  File "Mylar.py", line 244, in main
    j = ij.json_import()
  File "/volume1/@appstore/gitmylar/mylar/mylar/maintenance.py", line 72, in json_import
    self.importIT()
  File "/volume1/@appstore/gitmylar/mylar/mylar/maintenance.py", line 133, in importIT
    maintenance_info = importer.addComictoDB(re.sub('4050-', '', x['ComicID']).strip(), calledfrom='maintenance')
  File "/volume1/@appstore/gitmylar/mylar/mylar/importer.py", line 447, in addComictoDB
    updater.newpullcheck(ComicName=cn_pull, ComicID=comicid, issue=latestiss)
  File "/volume1/@appstore/gitmylar/mylar/mylar/updater.py", line 640, in newpullcheck
    mylar.weeklypull.new_pullcheck(weeknumber=mylar.CURRENT_WEEKNUMBER, pullyear=mylar.CURRENT_YEAR, comic1off_name=ComicName, comic1off_id=ComicID, issue=issue)
  File "/volume1/@appstore/gitmylar/mylar/mylar/weeklypull.py", line 1070, in new_pullcheck
    statusupdate = updater.upcoming_update(ComicID=comicid, ComicName=comicname, IssueNumber=week['issue'], IssueDate=ComicDate, forcecheck=forcecheck, weekinfo={'weeknumber':weeknumber,'year':pullyear})
  File "/volume1/@appstore/gitmylar/mylar/mylar/updater.py", line 402, in upcoming_update
    c_obj_date = datetime.datetime.strptime(str(mylar.CONFIG.PULL_REFRESH),"%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .174081

**Comment by evilhero** [comment]
Weird, I guess if you had started Mylar first and then quit it might have bypassed that error - but it was mainly due to the weekly pull not getting created on startup and storing the time it was pulled properly (another issue, but caused the error in the end).
