### ISSUE TITLE
API hits on (site name redacted because fight club)

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1897]
Hi

My account was briefly suspended there. I think the most likely reason is that Mylar was hitting it too much. I can just disable that indexer if best. But I was wondering if I can make that determination by logging at the logs or something, and if it's possible to have Mylar stay within these limits: 48 API hits (calls) / last 24 h, 5 NZB downloads (or grabs) / last 24 h

I have a primary indexer, dognzbs, and I donate to them, so I don't have to worry about exceeding their limits. So I wouldn't want to restrict that limit, only for (name redacted because fight club). Is that possible?

Hope you're well. Thanks for Mylar!

**Comment by evilhero** [comment]
Mylar should be getting specific responses from the given provider when it has hit the API limit, and it should then disable it at that point. You should get something in the logs when it returns a bad response along the lines of ```Unable to retrieve search results from <provider> [Status Code returned: <statuscode>]``` - if you're getting that then it's seeing that it's an invalid response and then (if the status code is 503) it'll log an additional line of ```Unavailable indexer detected. Disabling for a short duration and will try again.```

So it kinda does that, it will disable it - and the only way it gets re-enabled is if you restart Mylar or it's manually enabled in the configuration. I guess it depends on what's being returned from nzbs.in exactly and if it falls into that category that it would disable it properly.

There's also nzbhydra, which I believe can do some sort of rate limiting - although tbh, I don't use it so I'm just going off of a general assumption.

I'm well - long time no chat bro!

**Comment by evilhero** [comment]
Are you positive it's mylar that's causing it? You shouldn't be getting disabled for just going over the api limit, normally disabled comes from hammering/sharing of account. Mylar only calls the api at a minimum every 60s, so I mean as far as count if you have a more than 10 wanted issues it could go over 48 calls/24hrs I suppose. 

If you have it enabled, do you happen to see Ik the logs the error message returned after you've been disabled?

**Comment by AtariBaby** [comment]
I'm not certain! However their forum said Sonarr works well with them and so probably not it. That's all I got so far. I'm only using Sonarr and Mylar these days.

This what you wanted? First Error going back into mylar logs:
`23-Mar-2018 16:49:08 - ERROR   :: Thread-22 : [ERROR CODE: 401] API access suspended - Contact the support
23-Mar-2018 16:49:08 - WARNING :: Thread-22 : API Error. Check the error message and take action if required.
23-Mar-2018 16:49:08 - INFO    :: Thread-22 : Could not find Issue 8 of Dark Knight III: The Master Race Collector's Edition (2015) using nzbs.in [api]`

**Comment by AtariBaby** [comment]
Sorry I am breaking the rules of the site, would you mind removing reference to them? I can start a new thread if best, or drop it.

FYI this is what they told me:

> Its the same issue as before, Mylar is making API requests well above your limits, this time 40% to be exact.
> This must mean your interval settings or other settings are wrong. As already suggested in my previous comment, make sure you stay within your limits, tune your settings down if needed, and don't leave it going for several days without checking. The first post of this topic provides sufficient details to narrow your issue down to your settings, and set them accordingly.

**Comment by evilhero** [comment]
I mean, every 6hrs it does an hit per issue of your wanted list by default. But 48 hits/24hrs is really low regardless, especially if you're sharing amongst other downloaders. Like that's just searching for 10-12 issues on your wanted list alone (within 24 hrs) 

If that's the response based on the default settings, and mylar isn't hammering (1 hit/60s is more than adequate and in most other apps there isn't as much as a 60s delay between requests), I'd probably suggest not using it as you're just gonna keep on getting disabled at this point (I'm also assuming this is their free tier account).

I have some plans for changing up the search to allow for better management of provider resources, but atm those aren't on the immediate plate as there are other things I'm trying to iron out. Probably in the next month hopefully I can roll out the new methods that would fix this type of stuff from occuring.

**Comment by AtariBaby** [comment]
It's okay, I'll just take it out of mylar! thanks.
