### ISSUE TITLE
Parser library error message?

### ISSUE THREAD

**Issue by dma9** [evilhero/mylar#1902]
I keep seeing this error pop up in the logs and was wondering if there might be something I should fix with my installation of mylar to address it. Any suggestions would be most appreciated

> Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/search.py", line 2043, in searchIssueIDList
foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/opt/mylar/mylar/search.py", line 317, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual)
File "/opt/mylar/mylar/search.py", line 562, in NZB_SEARCH
bb = ww.wwt_connect()
File "/opt/mylar/mylar/wwt.py", line 53, in wwt_connect
soup = BeautifulSoup(r.content, "html5lib")
File "/opt/mylar/lib/bs4/__init__.py", line 165, in __init__
% ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by evilhero** [comment]
It's due to the new method of parsing the wwt site (it can now do direct searches as opposed to relying solely on the RSS feeds).

You need to have html5lib installed for the parser to work, but it's as simple as doing ```pip install html5lib```from the command line.

I keep on forgetting to add in a better warning to indicate the problem, but will do that in the next dev push.

**Comment by dma9** [comment]
Thanks very much - that did the trick. And sorry - I should have probably figured out it was that which was missing.

**Comment by bakaneko59** [comment]
Running this on Windows. Pardon my ignorance but how do I install the html5lib in this situation?
