### ISSUE TITLE
Not dowloading issues posted earlier than "publication date"

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#1903]
Just checked my wanted list in Mylar, and was wondering why some issues were not downloaded even if they were present on the RSS-feed from 32p.
I checked the logs - switched to debug and found the following

`...is before store date of 2018-03-14. Ignoring search result as this is not the right issue.`

Does this mean that mylar will never download issues that has been posted on 32p before the "publication date"?

I can understand it if it is posted 3 months before. But there should be some sort of grace period of a month or so.

**Comment by evilhero** [comment]
You're getting confused between the dates. The store date is BEFORE the publication date always, usually by at least a month if not more. What you see in the series detail page for a given series is the publication date.

When mylar locates an issue that name matches, it goes thru various checks to ensure it's the correct series prior to actually snatching. If the posting date of a given issue (according to when it's posted on 32p) is earlier than the actual store date - it ignores the result because there's no physical way an issue can be posted online before it's available for purchase (ie. store date). This only happened once a few years ago when one particular issue leaked out a few months in advance. 

So check the debug logs and see what it's actually saying and what the series is that's being compared (could be different volume, etc) and then check that the date for the given issue in mylar is valid.

**Comment by Lasborg** [comment]
OK that explains a lot. About the dates.

But it raises another issue. Looking at the wanted list at least a handfull should have been downloaded earlier (issues are not in the current feed) one of these is the series Slots no 6 posted a week ago.
The issue  Kill and be Killed no 17 is in the current feed, and it had not snatched it.
I have had similar issues before and it helped when I turned of 32p (i use legacy mode as i am using a vpn for downloading), saved the settings, and then enabled 32p and did another save. And then it snatched it.
The ones not in the current RSS cannot be found.
So this makes me believe that something is going on in mylar with 32p settings or maybe it is an RSS issue.

Is there any way I can help identify what causes it.

I am using Version: feaf102ed339726ed1a9a9b34c354799ffdef517 (development)

**Comment by evilhero** [comment]
Enable debug logging, and then do a manual search for one of those issues (probably the one on the feed) - odds are it's not matching for some other reason. If the name on CV (ie  what's in Mylar) is different than what it's called on 32p it will never match unless you use the Alternate Search Name option filled in correctly)

**Comment by Lasborg** [comment]
The problem is not naming on 32p. It matches perfectly what mylar expects
Kill or Be Killed did not get picked up before. Now after disabling and reenabling 32p in Mylar search provider settings it works. 
I can't replicate it now, as it is working - but i recon that within the next month it will stop working again, i will check up on it at post debug logs when it stops working.

**Comment by Lasborg** [comment]
Just checked my to day what has not been downloaded, there were a couple. 

The one i tested with manual search was Moonshine 008
Here is the log on pastebin [](https://pastebin.com/rchEwvL1 )

It is clear that mylar sees a lot of Moonshine issues, but not the latest one .
The latest issue was posted a week ago. 
Mylar is setup to check RSS every 60 minutes, and the NAS is only turned for off one hour in the middle of the night - so every new posts on 32p should be caught by the RSS scanner.


Mylar Version: development
-- git build b0d2ab54304bec051782489c074c27d55302a1b4.
Python Version : 2.7.13

**Comment by evilhero** [comment]
That particular entry would have to be in your RSS cache from that particular point in time when it was in the feed (so like on March 21st @8pm EST).  There's nothing irregular in that pastebin that would indicate something is amiss, aside from not having an entry for the given issue that you're requesting.

Pure speculation, but I'd wager that either Mylar wasn't on at that particular point, or something else stopped it from retrieving the feed (perhaps a backend error that you didn't see in the logs), which would stop that particular thread from firing off until you restarted Mylar later that night, and then the item would have been off of the feed by that time. I honestly don't think it's anything particular to your machine itself, but more of a timing issue/backend error that occurred and that was one of the issues that got caught in the 'whitehole' of nothingness...

**Comment by Lasborg** [comment]
I have been thinking along those lines as well. But I find it odd that in a setup where there is only one hour downtime, and an RSS update every hour. The "new issues RSS" usually contains  2-4 days worths of new issues. So shouldn't it then just update the RSS when it is back running again. Is there something i am not understanding about how RSS and RSS cache works.

What is a good RSS strategy? - I think that maybe every hour is to much and mylar is having issues populating the RSS cache?
