### ISSUE TITLE
Mylar won't start since 127b109

### ISSUE THREAD

**Issue by antdesca** [evilhero/mylar#1915]
Hi, 

Mylar can't seem to be able to start since the last commits on the development branch.

This is the output when I try to start

```
python /opt/mylar/Mylar.py -d
language detected as non-English (fr_FR). Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
Logging level over-ridden by startup value. Changing from 0 to 1
09-avril-2018 09:10:04 - INFO :: MainThread : __init__.py:initialize:192 : Checking to see if the database has all tables....
09-avril-2018 09:10:04 - INFO :: MainThread : __init__.py:csv_load:1118 : Populating Base Exception listings into Mylar....
09-avril-2018 09:10:04 - INFO :: MainThread : __init__.py:csv_load:1120 : Populating Custom Exception listings into Mylar....
09-avril-2018 09:10:05 - INFO :: MainThread : __init__.py:dbcheck:1064 : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
09-avril-2018 09:10:05 - INFO :: MainThread : __init__.py:dbcheck:1066 : Correcting Null entries that make the main page break on startup.
09-avril-2018 09:10:05 - INFO :: MainThread : __init__.py:initialize:206 : Successfully discovered local IP and locking it in as : 192.168.1.28
09-avril-2018 09:10:05 - INFO :: MainThread : __init__.py:initialize:223 : Config GIT Branch: development
09-avril-2018 09:10:05 - INFO :: MainThread : versioncheck.py:checkGithub:161 : Retrieving latest version information from github
09-avril-2018 09:10:06 - INFO :: MainThread : versioncheck.py:checkGithub:188 : Mylar is up to date
09-avril-2018 09:10:06 - INFO :: MainThread : __init__.py:initialize:275 : Remapping the sorting to allow for new additions.
09-avril-2018 09:10:06 - INFO :: MainThread : helpers.py:ComicSort:754 : Sucessfully ordered 76 series in your watchlist.
09-avril-2018 09:10:06 - INFO :: MainThread : filechecker.py:validateAndCreateDirectory:1348 : [DIRECTORY-CHECK] Found comic directory: /opt/mylar
```

After that the process stops running (and I got no errors displayed)

I am running Mylar on a Debian server and my locale is French.

**Comment by antdesca** [comment]
it's strange, it seems my service (`/etc/init.d`) is the faulty one. Even if the prompt returns after i try to start mylar manually (command line), the service is started.

I am using this script https://www.htpcguides.com/install-mylar-ubuntu-usenet-comics/

**Comment by evilhero** [comment]
So running it from the command line (with the -d option or without) works fine and is responsive?

**Comment by royaljack** [comment]
I'm running into a same issue with my Synology after updating today on the development branch. If anyone could point me to instructions on pulling log info off the Synology I'd be glad to share the logs if they are useful.

**Comment by evilhero** [comment]
Paste in what your /etc/default/mylar file is. Either you have a stray value in there, or there's something amiss with the actual init.d now and I'm not quite sure why that would be.

**Comment by antdesca** [comment]
I really don't know what's happening.

From the command line, the service starts and I got the prompt back (so I can exit the terminal) but it doesn't work when I try to start it from the service...

**Comment by evilhero** [comment]
You'd have to check your startup logs to see exactly what the problem is with your service. You can also try ```sudo service mylar status``` to see the last few lines from the startup sequence. 

Also make sure you have the correct perms on the /opt/mylar directory itself. The /opt directory is usually chowned to root:root by default, so if something changed that - you'd have to make sure it's accessible/writeable by the user running Mylar. 

Running it with the -d switch is not the same as running it as a service. The -d switch just puts the job in the background, but alot of the default options are not enabled unless you enable them via the switches as well (ie. data_dir, config, etc). Running it as a service (ie. starting it with the ```sudo service mylar start```) will load up all the proper values from the mylar default file.

**Comment by antdesca** [comment]
here is the output of mylar status

```
sudo service mylar status
● mylar.service - LSB: starts instance of mylar
   Loaded: loaded (/etc/init.d/mylar)
   Active: active (exited) since jeu. 2018-04-26 11:45:19 CEST; 12s ago
  Process: 14561 ExecStop=/etc/init.d/mylar stop (code=exited, status=0/SUCCESS)
  Process: 20738 ExecStart=/etc/init.d/mylar start (code=exited, status=0/SUCCESS)

avril 26 11:45:12 mylar[20738]: Removing stale /var/run/mylar/mylar.pid ... (warning).
avril 26 11:45:19 mylar[20738]: Starting mylar:language detected as non-English (fr_FR). Forcing specific logging module - errors W...the logs
avril 26 11:45:19 mylar[20738]: Quiet logging mode enabled...
avril 26 11:45:19 mylar[20738]: Initializing startup sequence....
avril 26 11:45:19 mylar[20738]: .
avril 26 11:45:19 systemd[1]: Started LSB: starts instance of mylar.
Hint: Some lines were ellipsized, use -l to show in full.
```

I didn't change anything about permission recently
That's really strange :(

**Comment by evilhero** [comment]
Try removing the -q (or --quiet) option from the etc/default/mylar file (unless you modified the /etc/init.d, then remove it from there)
