### ISSUE TITLE
post processing not working on dev

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1916]
the last time post processing (copy) worked for me was on 4.4.18 - since the updates after that on the dev channel mylar doesn't find anything. 

i have a full page of snatched issues without any postprocessed items :/

what is the best way to log this and give you the information needed?

**Comment by evilhero** [comment]
It depends on how you're trying to post-process them. If you're trying to post-process them with the ComicRN script - you'd need to enable debug logging, then try to re-snatch a given issue and paste the resulting log from that. 

If you're doing manual post-processing, the simplest way is to move one of the files you already snatched into it's own folder and point the manual post-processing option (Manage tab/ Manual Post-Processing) to that specific folder, and then paste the logs herein.

**Comment by HypKin** [comment]
snatching/finding of issues also doesn't work for me on dev. i just reverted to master, and mylar started downloading again. i don't have time to further look into it today, just wanted to tell you about the problem asap. 

i will try again with dev tomorrow i think.
