### ISSUE TITLE
requests module is acctualy requests2

### ISSUE THREAD

**Issue by waykohler** [evilhero/mylar#1918]
In autoprocesscomics.py there is this error message.
    print "Requests module not found on system. I'll revert so this will work, but you probably should install "
    print "requests to bypass this in the future (ie. pip install requests)"

It should be like this.
    print "Requests2 module not found on system. I'll revert so this will work, but you probably should install "
    print "requests2 to bypass this in the future (ie. pip install requests2)"

**Comment by evilhero** [comment]
Actually that's a testing line that should have been changed back to ```import requests```. I set it to requests2 so it would never load, and always trip the exception (and load the default stuff so I could debug/test things).

There is no requests2 - it's just ```requests``` as the statement indicates.

I'll have to correct the reference in the code - thanks for pointing it out (it works either way, just requests is needed to get around some auth login problems)

**Comment by waykohler** [comment]
Ah, I see.
pip install requests2 does work though
