### ISSUE TITLE
Functions not working after update

### ISSUE THREAD

**Issue by Nightwing90** [evilhero/mylar#1928]
Hi,

I've just updated to the newest version. Since the new version, some functions are not working anymore.

First is the recheck files button. It doesn't find my new files (checked the names and those are good, older comics from the series which were previously good have the same names). 

The mylar.py output says:

> 21-apr-2018 10:31:51 - DEBUG :: Thread-18 : filechecker.py:parseit:909 : Alternate series / issue title: The Brave and the Bold [Batman and Wonder Woman]
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Martijn\Documents\mylar-master\mylar\updater.py", line 934, in forceRescan
    tmpval = tval.listFiles()
  File "C:\Users\Martijn\Documents\mylar-master\mylar\filechecker.py", line 203, in listFiles
    logger.info('FAILED FILES: %s', self.failed_files)
TypeError: info() takes exactly 1 argument (2 given)

The other function is the Rename Files button. Mylar says "There was a error". Mylar.py says:

> 21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:269 : <type 'str'>
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:270 : <type 'unicode'>
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:271 : comicid: 108800
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:272 : issue# as per cv: 1
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:291 : issueid:660627
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:322 : issueid is now : 660627
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:465 : Zero Suppression set to : 00x
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:494 : issue detected less than 10
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:505 : Zero level supplement set to 00x. Issue will be set as : 001
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:539 : Pretty Comic Issue is : 001
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:549 : Issue Year : 2018
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:550 : Publisher: DC Comics
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:551 : Series: The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:552 : Year: 2018
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:553 : Comic Location: \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:561 : No version # found for series, removing from filename
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:562 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:570 : not an annual - removing from filename paramaters
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:571 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:633 : Altering series name due to filenaming restrictions: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:669 : New Filename: The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:677 : Source: The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:678 : Destination: \\nasmartijn\comic\Batman\The Brave And The Bold\The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:03 - INFO :: CP Server Thread-6 : webserve.py:manualRename:2199 : Not renaming The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz as it is in desired format already.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:269 : <type 'str'>
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:270 : <type 'unicode'>
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:271 : comicid: 108800
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:272 : issue# as per cv: 2
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:291 : issueid:663544
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:322 : issueid is now : 663544
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:465 : Zero Suppression set to : 00x
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:494 : issue detected less than 10
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:505 : Zero level supplement set to 00x. Issue will be set as : 002
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:539 : Pretty Comic Issue is : 002
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:549 : Issue Year : 2018
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:550 : Publisher: DC Comics
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:551 : Series: The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:552 : Year: 2018
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:553 : Comic Location: \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:561 : No version # found for series, removing from filename
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:562 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:570 : not an annual - removing from filename paramaters
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:571 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:633 : Altering series name due to filenaming restrictions: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:669 : New Filename: The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:677 : Source: The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : helpers.py:rename_param:678 : Destination: \\nasmartijn\comic\Batman\The Brave And The Bold\The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:03 - INFO :: CP Server Thread-6 : webserve.py:manualRename:2199 : Not renaming The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz as it is in desired format already.
21-apr-2018 10:33:03 - INFO :: CP Server Thread-6 : webserve.py:manualRename:2201 : I have renamed 0 issues of The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:03 - INFO :: CP Server Thread-6 : updater.py:forceRescan:930 : [FILE-RESCAN] Now checking files for The Brave and the Bold: Batman and Wonder Woman (2018) in \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:03 - INFO :: CP Server Thread-6 : filechecker.py:traverse_directories:1177 : there are 4 files.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:305 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:308 : NEW split_file3: ['!ongoing']
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:329 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:614 : datecheck: []
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:656 : No year present within title - ignoring as a variable.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:658 : highest_series_position: 1
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:736 : issue_position: 1
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:745 : No issue number present in filename.
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:871 : sf_highest_series_pos: ['ongoing']
21-apr-2018 10:33:03 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:903 : series title possibly: ongoing
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:921 : Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 10, 'mod_position': 51}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:658 : highest_series_position: 10
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 9, 'validcountchk': False, 'number': '001', 'mod_position': 47}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:736 : issue_position: 9
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:747 : issue verified as : 001
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 10, 'mod_position': 51}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:658 : highest_series_position: 10
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 9, 'validcountchk': False, 'number': '002', 'mod_position': 47}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:736 : issue_position: 9
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:747 : issue verified as : 002
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:277 : Scanner group tag discovered: The Last Kryptonian-DCP
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 11, 'mod_position': 53}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:658 : highest_series_position: 11
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 10, 'validcountchk': False, 'number': '003', 'mod_position': 49}]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:736 : issue_position: 10
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:747 : issue verified as : 003
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:855 : ALT-SERIES NAME [ISSUE TITLE]: The Brave and the Bold [Batman and Wonder Woman]
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', '-', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold - Batman and Wonder Woman
21-apr-2018 10:33:04 - DEBUG :: CP Server Thread-6 : filechecker.py:parseit:909 : Alternate series / issue title: The Brave and the Bold [Batman and Wonder Woman]
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:269 : <type 'str'>
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:270 : <type 'unicode'>
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:271 : comicid: 108800
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:272 : issue# as per cv: 1
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:291 : issueid:660627
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:322 : issueid is now : 660627
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:465 : Zero Suppression set to : 00x
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:494 : issue detected less than 10
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:505 : Zero level supplement set to 00x. Issue will be set as : 001
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:539 : Pretty Comic Issue is : 001
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:549 : Issue Year : 2018
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:550 : Publisher: DC Comics
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:551 : Series: The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:552 : Year: 2018
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:553 : Comic Location: \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:561 : No version # found for series, removing from filename
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:562 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:570 : not an annual - removing from filename paramaters
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:571 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:633 : Altering series name due to filenaming restrictions: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:669 : New Filename: The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:677 : Source: The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:678 : Destination: \\nasmartijn\comic\Batman\The Brave And The Bold\The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz
21-apr-2018 10:33:17 - INFO :: CP Server Thread-8 : webserve.py:manualRename:2199 : Not renaming The Brave and the Bold Batman and Wonder Woman 001 (2018).cbz as it is in desired format already.
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:269 : <type 'str'>
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:270 : <type 'unicode'>
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:271 : comicid: 108800
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:272 : issue# as per cv: 2
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:291 : issueid:663544
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:322 : issueid is now : 663544
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:465 : Zero Suppression set to : 00x
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:494 : issue detected less than 10
21-apr-2018 10:33:17 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:505 : Zero level supplement set to 00x. Issue will be set as : 002
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:539 : Pretty Comic Issue is : 002
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:549 : Issue Year : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:550 : Publisher: DC Comics
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:551 : Series: The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:552 : Year: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:553 : Comic Location: \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:561 : No version # found for series, removing from filename
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:562 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:570 : not an annual - removing from filename paramaters
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:571 : new format: $Series $Issue ($Year)
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:633 : Altering series name due to filenaming restrictions: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:669 : New Filename: The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:677 : Source: The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : helpers.py:rename_param:678 : Destination: \\nasmartijn\comic\Batman\The Brave And The Bold\The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz
21-apr-2018 10:33:18 - INFO :: CP Server Thread-8 : webserve.py:manualRename:2199 : Not renaming The Brave and the Bold Batman and Wonder Woman 002 (2018).cbz as it is in desired format already.
21-apr-2018 10:33:18 - INFO :: CP Server Thread-8 : webserve.py:manualRename:2201 : I have renamed 0 issues of The Brave and the Bold: Batman and Wonder Woman
21-apr-2018 10:33:18 - INFO :: CP Server Thread-8 : updater.py:forceRescan:930 : [FILE-RESCAN] Now checking files for The Brave and the Bold: Batman and Wonder Woman (2018) in \\nasmartijn\comic\Batman\The Brave And The Bold
21-apr-2018 10:33:18 - INFO :: CP Server Thread-8 : filechecker.py:traverse_directories:1177 : there are 4 files.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:305 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:308 : NEW split_file3: ['!ongoing']
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:329 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:614 : datecheck: []
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:656 : No year present within title - ignoring as a variable.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:658 : highest_series_position: 1
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:736 : issue_position: 1
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:745 : No issue number present in filename.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:871 : sf_highest_series_pos: ['ongoing']
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:903 : series title possibly: ongoing
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:921 : Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 10, 'mod_position': 51}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:658 : highest_series_position: 10
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 9, 'validcountchk': False, 'number': '001', 'mod_position': 47}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:736 : issue_position: 9
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:747 : issue verified as : 001
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 10, 'mod_position': 51}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:658 : highest_series_position: 10
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 9, 'validcountchk': False, 'number': '002', 'mod_position': 47}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:736 : issue_position: 9
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:747 : issue verified as : 002
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold Batman and Wonder Woman
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:277 : Scanner group tag discovered: The Last Kryptonian-DCP
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:360 : checking date : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:363 : date: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:614 : datecheck: [{'date': '2018', 'position': 11, 'mod_position': 53}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:620 : sctd: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:629 : year verified as : 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:635 : year verified as: 2018
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:658 : highest_series_position: 11
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:664 : possible_issuenumbers: [{'position': 10, 'validcountchk': False, 'number': '003', 'mod_position': 49}]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:736 : issue_position: 10
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:747 : issue verified as : 003
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:855 : ALT-SERIES NAME [ISSUE TITLE]: The Brave and the Bold [Batman and Wonder Woman]
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:871 : sf_highest_series_pos: ['The', 'Brave', 'and', 'the', 'Bold', '-', 'Batman', 'and', 'Wonder', 'Woman']
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:903 : series title possibly: The Brave and the Bold - Batman and Wonder Woman
21-apr-2018 10:33:18 - DEBUG :: CP Server Thread-8 : filechecker.py:parseit:909 : Alternate series / issue title: The Brave and the Bold [Batman and Wonder Woman]

**Comment by evilhero** [comment]
Looks like they're both related to the initial error you posted. Do you also have a filename with the word ```ongoing``` in it (as the series title doesn't have that wording and it might be throwing it off)

**Comment by Nightwing90** [comment]
Yes this was indeed the case. I've got some fake cbz files with the name ongoing as a reference for myself if the serie in ongoing or not. I've updatet Mylar and it works!

Thank you so much!
