### ISSUE TITLE
Updated to lastest master and webapp won't start

### ISSUE THREAD

**Issue by vader083** [evilhero/mylar#1930]
import mylar
File "/app/mylar/mylar/__init__.py", line 41, in <module>
from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
File "/app/mylar/mylar/logger.py", line 41, in <module>
if not LOG_LANG.startswith('en'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by evilhero** [comment]
See #1929 - I'm guessing you're running a docker version of mylar.

**Comment by vader083** [comment]
yes I am, thanks!
