### ISSUE TITLE
Experimental not matching - truncated results

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#1934]
27-Apr-2018 18:19:15 - DEBUG :: mylar.NZB_SEARCH.536 : Thread-225 : findloop: 0 / findcount: 1
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.787 : Thread-225 : checking search result: 0Day 04.25.18 pt1 [07/76] -  (2018)
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.797 : Thread-225 : sub:0Day 04.25.18 pt1 [07/76] -  (2018)
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.844 : Thread-225 : comsize_b: 45947672
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.881 : Thread-225 : size given as: 43.8 MB
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.986 : Thread-225 : Wed, 25 Apr 2018 18:34:03 +0200 is after store date of 2018-04-25
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1004 : Thread-225 : Entry: 0Day 04.25.18 pt1 [07/76] -  (2018)
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1036 : Thread-225 : Cleantitle: 0day 04 25 18 pt1  07 76  -  (2018)
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1151 : Thread-225 : Cleantitle: 0day 04 25 18 pt1  07 76  -  (2018)
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1178 : Thread-225 : 0. Bracket Word: 0day 04 25 18 pt1  07 76  -  
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1184 : Thread-225 : Comic: 0day 04 25 18 pt1  07 76  -  
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1185 : Thread-225 : UseFuzzy is  : 0
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1186 : Thread-225 : ComVersChk : 6
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1178 : Thread-225 : 1. Bracket Word: 2018
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1195 : Thread-225 : year detected: 2018
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1197 : Thread-225 : year looking for: 2018
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1199 : Thread-225 : 2018 - right years match baby!
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1403 : Thread-225 : original nzb comic and issue: 0day 04 25 18 pt1  07 76  -  
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1414 : Thread-225 : [Avengers 690] I have found a -  within the nzbname @ position: 26
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1419 : Thread-225 : There is no hyphen present in the series title.
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1420 : Thread-225 : Assuming position start is : 26
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1464 : Thread-225 : adjusted nzb comic and issue: 0day 04 25 18 pt1  07 76     
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1485 : Thread-225 : chg_comic:0day 04 25 18 pt1 07
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1492 : Thread-225 : chg_comic: 0DAY042518PT107
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1493 : Thread-225 : findcomic_chksplit: AVENGERS690
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1498 : Thread-225 : changeup to decimal: .76
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1545 : Thread-225 : adjusting from: 0day 04 25 18 pt1  07 76      to: 07.76
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1554 : Thread-225 : ['0day', '04', '25', '18', 'pt1', '07', '76'] nzb series word count: 5
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1555 : Thread-225 : ['avengers', '690'] watchlist word count: 2
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1621 : Thread-225 : splitst : 5
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1622 : Thread-225 : len-watchcomic : 2
27-Apr-2018 18:19:23 - DEBUG :: mylar.NZB_SEARCH.1624 : Thread-225 : incorrect comic lengths after removal...not a match.

When searching manually for "Avengers 690 cbr" in nzbindex.nl is showing the following:
0Day 04.25.18 pt1 [07/76] - "Avengers 690 (2018) (Digital) (Zone-Empire).cbr" yEnc

Maybe only parse words between the " <title/filename> " (quotes) instead ???
Also maybe add the 690 issue number into the search for more focus hit, instead of hitting all results with the word Avengers in it???

Thanks,
Pipi

**Comment by evilhero** [comment]
Easy fix. It checks for certain keywords when looking at the headers about what to ignore vs. what to actually parse. It was ignoring ```0-Day```,```0 Day```, but wasn't ignoring ```0Day```. Fix is in latest commit - tested and pulled exact issue in your post.

**Comment by pipieye** [comment]
Thanks :)
Will try out new commit.
Pipi
