### ISSUE TITLE
Freenas (master) Parser Library (HTML5LIB)

### ISSUE THREAD

**Issue by whipflash191** [evilhero/mylar#1935]
Im installing Mylar for the first time on my NAS using the plugin system (have also update Mylar in app to source build ver: c047a88463b593f1753b8ccefc045ab2b8046fb7) and have managed to install html5lib through pip install html5lib successfully however Mylar still throws the the following error

> 2018-04-28 17:51:14 | ERROR | 

> Uncaught exception: Traceback (most recent call last):File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 335, in new_runold_run(*args, **kwargs)File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 1419, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 334, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host)File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 617, in NZB_SEARCHbb = ww.wwt_connect()File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/wwt.py", line 53, in wwt_connectsoup = BeautifulSoup(r.content, "html5lib")File "/usr/pbi/mylar-amd64/share/mylar/mylar/bs4/__init__.py", line 155, in __init__% ",".join(features))ValueError: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

Is there something i missed? or is this a possible bug caused by running on freenas?

**Comment by evilhero** [comment]
It looks like you don't have a valid version of html5lib installed. If you go to a python prompt (command line) and type in ```import html5lib``` does it work?

**Comment by whipflash191** [comment]
okay so in the python command line inside my jail i ran 'import `html5lib` which didnt throw any errors but unfortunately didnt fix my issue. I then install python-html5lib using `pkg install py27-html5lib` which aslo hasnt worked. I can copy and paste the log entry again but it appears to be the same.

**Comment by evilhero** [comment]
Ok so you're using the newest html5lib and a depreciated bs4 (cause that's included with mylar). This worked for someone else, should work for you too - with mylar shutdown, go into the mylar/lib folder and rename the bs4 directory to bs4.backup. Then make sure your bs4 is the most recent version (pip install beautifulsoup --upgrade) and then see if that works.

**Comment by whipflash191** [comment]
hmm ive tried this but there is no bs4 folder in my mylar/lib on my freenas and pip auto installed the upgrade too /usr/local/lib/python2.7/site-packages and not mylar/lib in the usr folder. upon looking in the same folder in mylar (/usr/pbi/mylar-amd64/lib/python2.7/site-packages) theres no bs4 folder OR html5lib. i installed html5lib using `pip install --target=/usr/pbi/mylar-amd64/lib/python2.7/site-pa
ckages html5lib` which throws an error on startup. I cant read the whole log (yay crappy webgui shell) but the error ends in `attributeError: 'module' object has no attribute '_base'` there is a bs4 folder in `usr/pbi/mylar-amd64/share/mylar/mylar/` though.

**Comment by whipflash191** [comment]
ok so there is no bs4 folder in mylar/mylar/lib. I got rid of the folder in mylar/mylar and now how have a new startup error

 `Starting mylar.                                                                 
Traceback (most recent call last):                                              
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/Mylar.py", line 26, in <module>  
    import mylar                                                                
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/__init__.py", line 41, in <
module>                                                                         
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit
, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, 
PostProcessor, weeklypull, helpers, scheduler                                   
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/rsscheckit.py", line 21, in
 <module>                                                                       
    from mylar import logger, rsscheck, helpers, auth32p                        
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/rsscheck.py", line 13, in <
module>                                                                         
    from mylar import db, logger, ftpsshup, helpers, auth32p                    
  File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/auth32p.py", line 4, in <mo
dule>                                                                           
    from bs4 import BeautifulSoup                                               
ImportError: No module named bs4                                                
/usr/local/etc/rc.d/mylar: WARNING: failed to start mylar`

I have made sure html5lib and bs4 are installed on the system.

**Comment by evilhero** [comment]
That's a beautifulsoup error. It can't find your local install of bs4 and it's throwing the error.

Are you installing it to the correct target? I've never tried using the target option, so I'm wondering if that's causing some problems.

If you do a ```pip list```,  what does it show for beautifulsoup (I'm guessing you would have to be the user running mylar when issuing the command)

**Comment by whipflash191** [comment]
pip list shows 
`BeautifulSoup (3.2.1)                                                           
html5lib (1.0.1)`

when i ran `pip install` for bs4 i didnt target it so it ended up in the `usr/local/lib/python2.7/site-packages` instead of the mylar folder

**Comment by evilhero** [comment]
I think you need to do the pip install for ```beautifulsoup4```, not ```beautifulsoup```. The newest version of bs4 is 4.6.0.

**Comment by whipflash191** [comment]
ok so that solved my problem! for the record i did the following steps:

`1. pkg install py27-pip
 2. pip install beautifulsoup4
 3. pip install html5lib
 4. pip install --target=/usr/pbi/mylar-amd64/lib/python2.7/site-pa ckages html5lib`

the app launches now and searches correctly! im just having issues with it sending to transmission
`
ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
-- | --
| ERROR | incomplete format
`
my transmission login details are all correct so im not sure whats happening there :P

**Comment by evilhero** [comment]
The transmission host can't be preceded by a protocol (ie. don't put http/https). Just put in the ip or 'localhost'

**Comment by evilhero** [comment]
Ok, we're onto another issue now. Can you close this ticket since it's now working, and then open a new ticket for the new issue and provide the debug logs leading up to the error? You don't need to specify a port for transmission in mylar because it uses the rpc port.

**Comment by whipflash191** [comment]
can do!
