### ISSUE TITLE
[Freenas] Mylar webgui crashing

### ISSUE THREAD

**Issue by whipflash191** [evilhero/mylar#1939]
The webgui randomly becomes unreachable until a jail restart is forced. I checked the log and it isnt showing any errors.

**Comment by evilhero** [comment]
It sounds like you might have a port conflict - are any other apps using the same port as mylar? Sometimes there's a slight delay in returning a page if mylar is busy doing something - is there something you're doing right before it becomes unresponsive?

**Comment by whipflash191** [comment]
I just checked all my apps ports and nothing else appears to be using it. Occasionally it happens when i click of the page but most of the time ill just switch to the tab and find its already gone down. Sometimes it comes back up and sometimes it doesnt. Restarting the app doesnt seem to help but restarting the whole jail does. I also found a couple of these errors in the log this morning. Not sure if they are related

`WARNING	('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known'))`

**Comment by evilhero** [comment]
Well those might be related - what do you have for your mylar host address in the GUI? 

The error is basically saying that it can't resolve an address provided. Whether or not that is the mylar host, or some other address that mylar uses, it doesn't say - but the host ip would be a good start.

**Comment by whipflash191** [comment]
my host ip is set to the default 0.0.0.0

**Comment by evilhero** [comment]
What are the debug lines prior to that connection aborted error  - it might be something totally unrelated to the actual web display, but because it's timing out it might be delaying the response by a good amount of time.

**Comment by whipflash191** [comment]
so i checked the log file and heres what i found at those lines:
`mylar.locg.58 : Thread-25 : ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known')) `
`mylar.pull_the_file.1268 : Thread-25 : ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known))`

`mylar.locg.58 : Thread-26 : ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known')) `
`mylar.pull_the_file.1268 : Thread-26 : ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known))`

**Comment by evilhero** [comment]
Those are connection errors from your machine to the pullist. For some reason, you're not able to retrieve the pullist - what version of python are you running mylar with (first tab on the GUI shows)?

**Comment by whipflash191** [comment]
2.7.9, ive only had those errors show up twice though.

**Comment by evilhero** [comment]
Yeah those errors would seem to indicate you lost internet connection at those times for whatever reason.

You're running this as a package right for FreeNAS?  Have you thought about cloning it directly from github and running it that way?

**Comment by whipflash191** [comment]
i have but honestly im not really familiar enough with freenas enough to feel comfortable with it. I might have to though if i keep encountering more issues (which i am)
