### ISSUE TITLE
mylar post processing annuals over and over again

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1942]
![image](https://user-images.githubusercontent.com/15702664/39539058-fc440c00-4e3e-11e8-86a7-1e42e0384a0e.png)

so had this issue with 3 different annuals now, 

when i try to open the comic  i get this error

![image](https://user-images.githubusercontent.com/15702664/39539107-175801e0-4e3f-11e8-9f06-1f6e1cfd5089.png)

refreshing the whole series via the manage comic screen helps and stops all of this.

**Comment by evilhero** [comment]
Are you running an up-to-date version of Mylar? 

There was a fix last week (#0c2563468429a29e633f0f1c2461e971b94d92c1) that addressed this exact issue whereby during a post-processing run, the annuals weren't being correctly updated after a successful post-process. The end result would be a NULL value for the issuename which is exactly what's happening here.

**Comment by HypKin** [comment]
im currently on Version: c047a88463b593f1753b8ccefc045ab2b8046fb7 (master)

**Comment by evilhero** [comment]
Yeah fix isn't in master as of yet, I believe it's still needing to undergo some additional testing (other aspects of that commit) that have caused some issues. Hopefully can push it to master in a day or so to clear up this issue.

**Comment by bguidotti** [comment]
I concur with Aimhere2k.  Deathstroke Annuals and Batman Annuals are downloading over and over again.
Specifically: 

Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire
Deathstroke.Annual.002.2016.Digital.Zone-Empire
Batman.Annual.001.2017.Digital.Zone-Empire
Batman.Annual.002.2018.Digital.Zone-Empire

I'm running version DEV 8d626ec36152996ba9791b52166385f6dfcda8a1 on Windows 10 64-bit.

Let me know if you need some other logs.

**Comment by bguidotti** [comment]
My alt_pull is set to 2 and I have the issue. They just downloaded again 30 minutes ago.

**Comment by evilhero** [comment]
Can you post the debug log for  the download? Is it correctly post-processing the given issues or do they always stay in a Snatched status? If not, what's the status before/after the snatch?

**Comment by bguidotti** [comment]
From my perspective, they are post-processing each time.
I've turned on Debug Logging in Mylar now, but didn't have it on before.
**Here is an excerpt from SAB:**

Loading config from C:\Program Files\SABnzbd\scripts\autoProcessComics.cfg
Opening URL: http://localhost:8090/post_process?nzb_name=Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire&failed=0&apc_version=1.0&comicrn_version=1.01&nzb_folder=d%3A%5CComics%5CDeathstroke-Annual.001.2015.Digital.ThatGuy-Empire
nzb name: Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire
nzb folder: d:\Comics\Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire
nzbname: Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire
Annual detected.
Issue Year: 2015
Publisher: DC Comics
Series: Deathstroke
Year: 2014
Comic Location: d:\comics\Deathstroke (2014)
Comic Version: v3
Original Filename: Deathstroke - Annual 001 (2015) (Digital) (ThatGuy-Empire).cbz [.cbz]
New Filename: Deathstroke Annual 001 (2015)
Source:d:\Comics\Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire\Deathstroke - Annual 001 (2015) (Digital) (ThatGuy-Empire).cbz
Destination:d:\comics\Deathstroke (2014)\Deathstroke Annual 001 (2015).cbz
[move] d:\Comics\Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire\Deathstroke - Annual 001 (2015) (Digital) (ThatGuy-Empire).cbz - to - d:\comics\Deathstroke (2014)\Deathstroke Annual 001 (2015).cbz
Removed temporary directory : d:\Comics\Deathstroke-Annual.001.2015.Digital.ThatGuy-Empire
Post Processing SUCCESSFUL!

**Comment by bguidotti** [comment]
I noticed that my Deathstroke (2014) folder was showing 50/32 downloaded.
I did a refresh comic; now it shows 32/32.  I will watch to see if that fixed it. Maybe that comic index was corrupted or something.

**Comment by evilhero** [comment]
What was happening prior to the bugfix was that annuals were being updated  incorrectly to the issues table, instead of the annuals table. So you would end up with annuals in the issues table in a Downloaded status that wasn't linked to any series, but the annuals table still had the given annual in the last status prior to post-process (ie. Snatched). So it would just completely cycle over and over cause it could never update properly, and since on each pp run it increments the total you're numbers were way out of whack. The refresh would return everything to an initial starting point that was correct until the next pp attempt.

This seems to have occurred only with the annuals that were snatched during that specific timeframe, which is why almost everyone is having the same problems with the same issues (best guess atm, but it lines up). Going forward since the update, things should work again for annuals - the real test will be when an  annual comes out again.

**Comment by bguidotti** [comment]
That makes since @evilhero 
If it was my issue, I would consider it closed.
Thanks!
