### ISSUE TITLE
torznab auto search hangs

### ISSUE THREAD

**Issue by casret** [evilhero/mylar#1949]
When I have my torznab indexer set, the autosearch will stop at the first issue and not go on:

```
10-May-2018 08:23:05 - INFO    :: mylar.search_init.364 : Thread-20 : Could not find Issue 13 of Uber: Invasion (2016) using hydra [api]
10-May-2018 08:23:05 - DEBUG   :: mylar.NZB_SEARCH.432 : Thread-20 : using Torznab host of : hydra tor
10-May-2018 08:23:05 - INFO    :: mylar.NZB_SEARCH.475 : Thread-20 : Shhh be very quiet...I'm looking for Uber: Invasion issue: 13 (2018) using hydra tor (tor
znab).
10-May-2018 08:23:05 - DEBUG   :: mylar.NZB_SEARCH.536 : Thread-20 : findloop: 0 / findcount: 1
```

I never see the 'pausing 60 seconds' or the search url log line.  In the manage activity screen the auto-search will continue to show as active and never proceed past that first issue.  The request does not seem to get to the indexer if I look it it's logs.

**Comment by evilhero** [comment]
What branch / commit are you running?

Do you have all the fields filled out for the torznab provider?

Are you using hydra v1 or v2?

**Comment by casret** [comment]
58b59d49bff7dbcfedb108c659bd5081c1cbb888
hydra v2

The category is not filled out.  What should I put in there?

**Comment by evilhero** [comment]
Wait - you don't set hydra as a torznab, you set it as a newznab entry. Torznab is for jackett/cardigann usage, which hydra doesn't use (last I checked)

**Comment by casret** [comment]
Hydra2 will multiplex torznab endpoints as well, so you can stick hydra2 in front of jackett.
