### ISSUE TITLE
Uncaught exception on adding a comic to Mylar watch list

### ISSUE THREAD

**Issue by adispi** [evilhero/mylar#1953]
Packages from:  https://github.com/Safihre/spksrc/releases/
Python: python_x64-6.1_2.7.14-18
Mylar: mylar_noarch-all_20180228-4

Synology 918+ 6.1.6 update 1

Mylar show phyton crash on adding a comic to wanted:

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/var/packages/python/target/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 233, in addComictoDB
comlocation = os.path.join(mylar.CONFIG.DESTINATION_DIR, helpers.replace_all(chunk_folder_format, values))
File "/usr/local/mylar/env/lib/python2.7/posixpath.py", line 70, in join
elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by evilhero** [comment]
Make sure to read the READ.me - you NEED to set a Comic Location. Mylar will not work if it is not set.

**Comment by adispi** [comment]
every place in the gui that have asked for a path was given.
must i do it from command line?

**Comment by adispi** [comment]
after going over all the menues several times, i added it manually via shell.
as soon as i added it via shell the option appeared in the gui.

thank you.
adi
