### ISSUE TITLE
Could not locate exceptions.csv file

### ISSUE THREAD

**Issue by kalfun** [evilhero/mylar#1955]
I'm getting the following error: Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar.

**Comment by evilhero** [comment]
Th exceptions.csv file is located in the root of Mylar. What happened to yours ?

**Comment by kalfun** [comment]
Not sure. I've reinstalled it a few times, it's not there... I'm on Ubuntu btw.

**Comment by kalfun** [comment]
I'm installing it with plexguide and Ubuntu 18, so I'm not sure what i'm doing wrong.
