### ISSUE TITLE
NZBGet Support Broken If No Authentication is Set?

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1959]
Disclaimer: I'm new to Mylar (but not Headphones, Sickrage, Sonarr, LazyLibrarian et al) so it's possible I'm just doing something stupid.

**NOTES:**

- Debug log excerpts are semi-redacted (my internal domain name).

- NZBGet and Mylar are both running in Docker containers (not bridged).  All folders are 777 and they are all using the same PGUID and PUID.

- NZBGet is properly configured and works with other applications.  It also passes Mylar's test.

- All my stuff is setup for intranet ONLY so I'm not bothering with SSL or Authentication.    Unfortunately Mylar cannot handle this properly as it uses "None" and "None" for the username and password for NZBGet even if you blank the fields out.

```
2018-05-17 18:59:38 | DEBUG | Now attempting to test NZBGet connection
2018-05-17 18:59:38 | INFO | Now testing connection to NZBGet @ http://nzbget.XXXXX.net:16789
2018-05-17 18:59:38 | INFO | nzb_url: http://:@nzbget.XXXXX.net:16789/xmlrpc
2018-05-17 18:59:38 | INFO | Successfully verified connection to NZBGet at nzbget.XXXXX.net:16789

```
The URL here looks a little goofy ( nzb_url: http://:@nzbget.XXXXX.net:16789/xmlrpc) since there is not any authentication set but it passed the test.

I'm using an Invader ZIM comic as a test... it finds it ok from the indexer but then when it tries to send it to NZBGet, it loses it's mind.

```
2018-05-17 18:59:51 | DEBUG | [FILENAME] end nzbname: Invader.Zim.016.2016.digital.dargh-Empire.nzb
2018-05-17 18:59:51 | DEBUG | Cache Directory successfully found at : /config/mylar/cache
2018-05-17 18:59:51 | DEBUG | sending now to http://None:None@nzbget.XXXXX.net:16789/xmlrpc
2018-05-17 18:59:51 | WARNING | uh-oh: cannot marshal None unless allow_none is enabled
```

Here we see that Mylar is using the DISPLAY authentication (None and None) as actual authentication.  

Naturally, everything now explodes:

`2018-05-17 18:59:51 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 336, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/webserve.py", line 1427, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks, torrentid_32p=TorrentID_32p)File "/app/mylar/mylar/search.py", line 334, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)File "/app/mylar/mylar/search.py", line 1783, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host)File "/app/mylar/mylar/search.py", line 2674, in searcherlogger.warn('Unable to send nzb file to NZBGet. There was a parameter error as there are no values present: %s' % nzbget_params)NameError: global name 'nzbget_params' is not defined`

**Comment by LeeThompson** [comment]
I just did a test with "mylar" as user and password for nzbGet, same exception so I think it's just broken.

Blackhole works fine.

**Comment by evilhero** [comment]
It seems it's just the test connection button isn't working properly with a username/password not being set, as well as with a username/password being set. Regardless of the combination, it will return a valid response from the nzbget server because - I was getting the same result regardless of the combo being used testing it now briefly. I'll have to find another API endpoint to test against possibly. I don't use nzbget, so when I had tested it I might have misconfig'd something, but it was pretty much default settings for everything.

User/Pass + sending to nzbget works fine though - the user/pass not being set needs to get fixed for sends, as well as the test connection button for both.

**Comment by LeeThompson** [comment]
Figured it out ... somewhat.  In Mylar if you set an nzbget category name (i.e. mylar or comics) it works.
