### ISSUE TITLE
Wanted page (upcoming) returns Type Error

### ISSUE THREAD

**Issue by dabadgreek** [evilhero/mylar#1963]
After last update to 6ab1715c53f95c758f5c5d09e56b003c74b0f593 wanted (upcoming) page is now throwing a Mako Runtime Error:
Error !
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
%> <tr class="${issue['Status']} grade${grade}"> <% linkit = 'comicDetails?ComicID=%s' % issue['ComicID'] try: if issue['StoryArcID'] is not None: lineheader = issue['StoryArc'] linkit = 'detailStoryArc?StoryArcID=%s&StoryArcName=%s' % (issue['StoryArcID'],issue['StoryArc'])

**Comment by evilhero** [comment]
Do you happen to have any story arcs in your story arc management section ? 

That error is indicating that there's an empty reference somewhere, or even that you don't have any story arcs present.

**Comment by dabadgreek** [comment]
Sorry for confusion on my part.  I checked advanced settings no story arcs listed under story arc management

**Comment by dabadgreek** [comment]
Thank you for the quick response.
