### ISSUE TITLE
Mylar not finding comics.

### ISSUE THREAD

**Issue by kalfun** [evilhero/mylar#1964]
Running Mylar on Ubuntu 18, I encounter this error.

2018-05-24 14:31:47 | WARNING | There were no files located - check the debugging logs if you think this is in error.
-- | -- | --
2018-05-24 14:31:47 | INFO | there are 0 files.
2018-05-24 14:31:47 | DEBUG | [POST-PROCESSING] Manual Run initiated
2018-05-24 14:31:47 | DEBUG | [POST-PROCESSING] Not using SABnzbd : Manual Run
2018-05-24 14:31:47 | DEBUG | [POST-PROCESSING] nzb folder: /mnt2/sab/complete/comics
2018-05-24 14:31:47 | DEBUG | [POST-PROCESSING] nzb name: Manual Run
2018-05-24 14:31:47 | INFO | Starting postprocessing for : Manual Run

Permissions are set to 777 and under the right user/group, and the downloaded comics are in that specified folder.

**Comment by evilhero** [comment]
Are the files in the given directory cbr/cbz files or something else ? 

If there are files within, do the files to be post-processed have the correct permissions for the user running Mylar to be able to read ? If they're being downloaded from sab, they might have the sab user's permissions by default unless otherwise adjusted (especially if you're running via dockers)

**Comment by kalfun** [comment]
Just checked the permissions again. The folder containing each file is 777, whereas the file inside is 0666. I'm assuming that's the issue?

**Comment by evilhero** [comment]
It could very well be - chmod them and see if the scan picks it up at that point?

The scanner just lists the directory, so if it can't list it usually permissions/ownership is the problem.

**Comment by evilhero** [comment]
The manual scan doesn't use Completed Download Handling - that's just for items that are snatched by Mylar for the given download client.

Is the location of the manual scan an external drive or something not local to the OS itself?

And are the files in the folder cbr/cbz type files, or something else?

**Comment by kalfun** [comment]
The location of the manual scan is my second internal ssd. I put all my completed downloads in that drive due to disk space reasons.  

And the files in the folder are cbr/cbz type files.

**Comment by evilhero** [comment]
Gonna sound stupid but are you sure the path provided is correct and accessible?

I mean there's really no reason why it wouldn't be able to scan in a directory if the path provided exists (it's just trying to list the directory contents).

What about perms leading up to the final location (ie. /mnt2, sab, complete) - are they all reachable by the user running mylar?

Or even, ```su``` to the user which runs mylar and cd into /mnt2/sab/complete/comics and see if you can do a simple ```ls``` command
