### ISSUE TITLE
Everything goes to Snatched

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1966]
Hey, it looks like issues are getting set to snatched, but I can't find any nzb files downloaded, and it never downloads the comic.
I also can't auto-update mylar, anymore.

**Comment by barbequesauce** [comment]
Are you on master or development? What commit are you on? what platform? What NZB client are you using? How about a log file from debug mode?

Need some details to help... Thanks!

**Comment by thewindupboy** [comment]
I'm sorry, it's been a long week.  I think I'm on a pretty old version of mylar.  I'd like to update.  But when I click the check for new version link. I get a warning in to log : Could not get the latest commit from github

**Comment by thewindupboy** [comment]
6754ad0b8b6e0d4c9f5b13c7ab0ed1946792c77e (development)

**Comment by thewindupboy** [comment]
grrr . "6754ad0b8b6e0d4c9f5b13c7ab0ed1946792c77e (development)"

**Comment by evilhero** [comment]
Update your version of git. Git removed some obsolete certificate authentication from their git module which will break older versions of git trying to use things.

**Comment by thewindupboy** [comment]
I don't have git installed

**Comment by thewindupboy** [comment]
OK, I'm on 2.17 of git, and same problem

**Comment by thewindupboy** [comment]
Using 'which git' I saw I was using /usr/local/bin/git and set that as my git_path
 git_user = evilhero
check_github=True
git-branch = development

**Comment by thewindupboy** [comment]
Honestly, I've been using this for years, I can't remember how I installed it.  And I'd really rather not have to worry about going through configuring it again :)

**Comment by wraith1385** [comment]
So I'm up to date on everything, 

Mylar Version: development
-- git build 5e6b861fadcbd6a43412e0a4e8a7cdee6e8e945c.

I'm having the same issue, but when Mylar snatches something, it's sending to SabNZB and getting the error below for everything.  SabNZB version 2.3.4 [2a113f7]:

 Invalid NZB file Justice.League.-.No.Justice.04.of.04.2018.Digital.Zone-Empire.nzb, skipping (reason=junk after document element, line=2)

**Comment by evilhero** [comment]
Well you still havent answered some questions - what OS? Are mylar and sab on the same machine? Debug logs showing the startup sequence (start mylar with the -v switch).

Odds are it sounds like it was a source install, which means you'd have to backup some files, wipe the dir and redownload the source. 

The best way would be to backup your mylar.db, config.ini and entire cache directory. Wipe the directory entirely. Install mylar via git clone with the -v switch (git clone https://github.com/evilhero/mylar/mylar.git -b development) Put back the files you backed up and you should be good  and up to date.

**Comment by evilhero** [comment]
@wraith1385: is that error in sab or in mylar? What's the nzb provider you're snatching from (is it the same one everytime)?

**Comment by thewindupboy** [comment]
OSX 10.13.4
SABNZB is on the same machine
I'll try the reinstall tomorrow, thanks!

**Comment by wraith1385** [comment]
That error is in sab.  It looks like the provider is nzb.su, but I have 3 configured so I don't know if it used it every time. 

Also, it should be noted that I can download the files fine going directly from the indexer to sab.

**Comment by evilhero** [comment]
Can you disable nzb.su,ans try one of the other providers to see if it's universal regardless of the provider? It might be the link is invalid that nzb.su is returning if its from the RSS feed instead of the API (if you enable debug logs, you'll get much more information which will be helpful in figuring this out)

**Comment by thewindupboy** [comment]
I tried doing the install using that command and I got
fatal: repository 'https://github.com/evilhero/mylar/mylar.git/' not found

**Comment by evilhero** [comment]
@wraith1385 : so it sounds like it's a problem with the link that mylar is using to retrieve the nzb from nzb.su. The log didn't mention, was it found via the RSS or API? You might have to provide more logging so I can see the nzb.su url that it's trying.

@thewindupboy : don't put a trailing slash after mylar.git, or just remove the entire /mylar.git from the command.

**Comment by thewindupboy** [comment]
OK, I'm all installed now.  But the problem is still happening.  I started mylar with the -v and here's the log file.  

[mylar_06012018.log](https://github.com/evilhero/mylar/files/2062562/mylar_06012018.log)

**Comment by barbequesauce** [comment]
Looking at this, it found Saga 52 and sent it to SAB no issue. What does SAB look like? stuff downloaded or not?

Side note - you're still having issues with git.... 

`01-Jun-2018 07:44:11 - WARNING :: mylar.checkGithub.175 : MAIN : [ERROR] Could not get the latest commit from github: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)`

**Comment by thewindupboy** [comment]
SAB shows no sign of receiving anything from mylar.  I currently have Saga 52 marked as 'snatched'.  I see no sign of any NZB file either.

Yeah, I'll deal with the git issue later ;)

**Comment by barbequesauce** [comment]
Can you post the SAB log file from the same time period (07:40-07:50am) please?

**Comment by thewindupboy** [comment]
Attached.

[sabnzbd.log](https://github.com/evilhero/mylar/files/2062910/sabnzbd.log)

**Comment by evilhero** [comment]
Look in the mylar/cache folder for one of the .nzb files that you've attempted to download and open it up in a text editor (ie. vim/pico/nano) and see what's inside.

**Comment by thewindupboy** [comment]
OK, I opened up Saga 52, attached.  Looks ok? (changed the extension so I could attach here)

[Saga.052.2018.Digital.Zone-Empire.txt](https://github.com/evilhero/mylar/files/2062943/Saga.052.2018.Digital.Zone-Empire.txt)

**Comment by evilhero** [comment]
No one has access to nzb.su to verify their api calls, or if they've changed at all. So if you want this to work with nzb.su, you're going to have to go their website, go to Menu, Useful Links, API and see what it says for the api link format and paste back in here (xxx out your apikey)

**Comment by thewindupboy** [comment]
So, amusingly, when I do that, I get:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="200" description="Missing parameter"/>

**Comment by evilhero** [comment]
Yeah, they changed their API help url, but I guess the actual menu link is pointing to the old reference (just found this out from someone else helping out). 

It looks like the download link that's being returned when using the API is pointing to a link that is only accessible if you're logged onto the site and not using the API. I'm just trying to confirm this, as I came across this with some other indexers a few days ago and fixed the references, but nzb.su might be a bit different.

**Comment by thewindupboy** [comment]
OK, cool, let me know when you find out?  Any thoughts on my git problem? (which, obvs, is not actually a mylar problem)

**Comment by thewindupboy** [comment]
From the NZB.SU guy:

API is obfuscated in there... dunno if that's intentional by the software, so i can't see if you actually have it in there correctly... but it works fine.

`https://api.nzb.su/api?t=search&q=avengers%20marvel%20legacy%20primer&o=xml&cat=7030&apikey=*my api key*
`
I changed the q= to just drop something so specific that didn't appear to be there.  You can use that to test your stuff in a browser.

**Comment by evilhero** [comment]
Yeah the apikey is obfuscated on purpose - it's just appears like that in the logs, the actual submitted line has the apikey as per your configuration settings. 

It's not the actual search that's the problem, but the download url that it's trying to retrieve.  Specifically, upon retrieving the nzb from nzb.su, the nzb itself contains ```<b>Notice</b>:  Undefined offset: 1 in <b>``` at the beginning of the nzb which is causing sab to reject it for being an invalid nzb. The remainder of the nzb is valid however, so why it's adding that to the nzb is the question.

We have another user who tested nzb.su and was able to download fine using the latest development build of Mylar. You'll have to confirm yourself that your apikey and userid are both correct in Mylar for nzb.su.

**Comment by thewindupboy** [comment]
WHOA!  OK, everything seems to be working now.
Looks like my user id got overwritten.  When I brought mylar down, added it into the config.ini, and brought it back up, everything started processing fine!

THanks all!

**Comment by thewindupboy** [comment]
Nope, that wasn't it, he made a change on his end and now everything is working.  However, post-processing is not happening.  I think that got overwritten when I reinstalled.

**Comment by barbequesauce** [comment]
when you say "everything is working", you mean valid NZBs are being sent to SAB?

Are you using ComicRN or completed download handling for post-processing?

**Comment by thewindupboy** [comment]
Yes, valid NZBs are being sent, and comics are being downloaded.  However, they are not being moved to dropbox.  I believe this was being handled by ComicRN

**Comment by evilhero** [comment]
Post the debug log for the post-processing attempt. ComicRN changed in the last few months, so it uses an APIKEY instead of a username/password in the autoProcessComics.cfg file. So if you're using the new ComicRN, then you'll need to update your .cfg file

**Comment by thewindupboy** [comment]
Attached

[mylar (1).log](https://github.com/evilhero/mylar/files/2063231/mylar.1.log)

**Comment by evilhero** [comment]
There is no post-processing information in that log. Snatch another issue (or review the log) and look for the post-processing sections (or ComicRN within the text, or process)

**Comment by thewindupboy** [comment]
ok, downloaded another one.  There's no text in the resulting log that mentions ComicRN

**Comment by thewindupboy** [comment]
AH!  OK, the problem is that I installed mylar to a different location when I reinstalled!  So, I need to get that configured correctly

**Comment by evilhero** [comment]
You have 2 options with post-processing & SAB:
- setup ComicRN, autoProcessComics.py and autoProcessComics.cfg again. Use the Mylar APIKEY in the .cfg file instead of username/password (if you're just copying your old .cfg). If you don't have requests installed for you OS - install requests for python (ie. ```pip install requests```).
- Enable Completed Download Handling in the SABnzbd section within Mylar. Save the config and restart Mylar. Make sure that you are NOT using ComicRN within SABnzbd as you will get race conditions and post-processing errors if you do.

**Comment by thewindupboy** [comment]
Cool, will do, thanks!

**Comment by thewindupboy** [comment]
Again, thank you to everyone for all your help, you guys really are the best!

**Comment by wraith1385** [comment]
So, I have to assume the nzb.su fixed something, because I didn't change anything but reenabled it as a search option to do some testing and it's working fine now.

**Comment by thewindupboy** [comment]
Yeah, they took out that weird line `<b>Notice</b>: Undefined offset: 1 in <b> ` I think.
