### ISSUE TITLE
windows 10: best way to install from scratch and keep comics?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1967]
Hi
Recently I've had some issues and you indicated it could be the age of my install. right now it won't start at all, so I thought maybe now is a good time to unisntall reinstall, but I'd like to keep all my comics. Can you remind me how? Windows 10 Pro 64
Thanks!

**Comment by evilhero** [comment]
If the paths are all the same and nothing has changed as far as to the location of the comics and where Mylar is going to be running (ie. switching from linux to win), you'd just have back up your config.ini, mylar.db and cache folder. Wipe the mylar directory. Then do a git clone and point it to the location that was just wiped. Move the backup files back, and that should be it.

**Comment by AtariBaby** [comment]
Thanks. Has the config file change significantly? Is there an advantage to just copying and pasting relevant data?

--
Gregory Fleming
415-218-4101
Misspelled from my iPhone

**Comment by evilhero** [comment]
If using the newest version with the old config, your best bet is to use your existing config.ini (make sure it's backed up first), and then start Mylar. It will attempt to auto-convert it to the new .ini format and version on  startup. 

Doing it by hand wouldn't be a good move, just cause there are new fields / values in the new format, as well as a complete layout change.

**Comment by AtariBaby** [comment]
Works great. Thanks!
