### ISSUE TITLE
ERROR: 	[RSS-FEEDS] Unable to retrieve any information from 32P for RSS Feeds. Skipping for now.

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#1968]
I seem to be getting the above error message whenever Mylar attempts to search for a comic. Not sure why, though, as when I "test" the 32P connection, it comes back as successful, shows inkdrops, all that jazz. Any ideas?

**Comment by evilhero** [comment]
Nothing wrong with the 32P RSS feeds (at least now). Are you still getting the error during a normal search?

Try to enable debug/verbose mode, and then go into the configuration tab / Providers and under the Enable RSS/Feed searches (make sure it's checked), click on the Force RSS option to the right. It will then just attempt to check the RSS Feeds so you'll get an immediate response as to the success/failure.
