### ISSUE TITLE
Unable to convert CBR-->CBZ

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1970]
I am running the latest release - Version: 5e6b861fadcbd6a43412e0a4e8a7cdee6e8e945c (development) and CBR --> CBZ keeps failing with this error

> [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /opt/Mylar/cache and/or the location where Mylar is trying to tag the files from.

/opt/Mylar/cache is owned by the mylar user and group, which is the user to run Mylar, and the permissions are 777.  

Debug log entry is below

> 8-06-07 12:43:55 | DEBUG | [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
> -- | -- | --
> 2018-06-07 12:43:54 | WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /opt/Mylar/cache and/or the location where Mylar is trying to tag the files from.
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] Absolute path to script: /usr/bin/python
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] Executing command: ['/usr/bin/python', '/opt/Mylar/comictagger.py', '-e', '--delete-rar', u'/opt/Mylar/cache/mylar_j3eQtM/Crossed Plus One Hundred Mimic - 0000 - 2.cbr']
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['/usr/bin/python', '/opt/Mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/opt/Mylar/cache/mylar_j3eQtM/Crossed Plus One Hundred Mimic - 0000 - 2.cbr']
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] CBL Tagging enabled.
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] CR Tagging enabled.
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] Running the ComicTagger Add-on for Mylar
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] comicpath : /opt/Mylar/cache/mylar_j3eQtM
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] sabnzbdscriptpath :
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] downloadpath : /media/comics/Avatar Press/Crossed Plus One Hundred Mimic [2018]
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] scriptname : Mylar.py
> 2018-06-07 12:43:53 | DEBUG | [META-TAGGER] Paths / Locations:
> 2018-06-07 12:43:52 | DEBUG | New_Filepath: /opt/Mylar/cache/mylar_j3eQtM/Crossed Plus One Hundred Mimic - 0000 - 2.cbr
> 2018-06-07 12:43:52 | DEBUG | New_Folder: /opt/Mylar/cache/mylar_j3eQtM
> 2018-06-07 12:43:52 | DEBUG | Filename: Crossed Plus One Hundred Mimic - 0000 - 2.cbr
> 2018-06-07 12:43:52 | DEBUG | Filepath: /media/comics/Avatar Press/Crossed Plus One Hundred Mimic [2018]/Crossed Plus One Hundred Mimic - 0000 - 2.cbr
> 2018-06-07 12:43:52 | DEBUG | [META-TAGGER] Filename is : /media/comics/Avatar Press/Crossed Plus One Hundred Mimic [2018]/Crossed Plus One Hundred Mimic - 0000 - 2.cbr
> 2018-06-07 12:43:52 | DEBUG | ComicTagger Path location for internal comictagger.py set to : /opt/Mylar/comictagger.py
> 2018-06-07 12:43:52 | DEBUG | [META-TAGGER] dirName:/media/comics/Avatar Press/Crossed Plus One Hundred Mimic [2018]
> 2018-06-07 12:43:42 | INFO | Web logs cleared
>

**Comment by DrSeussFreak** [comment]
/media/comics/Avatar/Crossed Plus One Hundred Mimic [2018] has 777 permissions owned by nobody:users and the files underneath are the same.

Renaming works without issue, so it clearly has permissions.

**Comment by DrSeussFreak** [comment]
It is every issue, I used that as an example.  I have run the following numerous times, and it has stuck.
`chown -R mylar:mylar /opt/Mylar && chmod -R 777 /opt/Mylar`
I am click on an individual issue, the metatag option there, to do it.  This was for a file I manually donwloaded (the name didn't meet with the configured convention, so I did it manually), but for issues Mylar grabbed and moved itself, this also failed.  It was able to move the files, no problem, renaming them in the process, but it was unable to convert it.

So it may be a permissions issue, but I am not sure how or what.

**Comment by evilhero** [comment]
Can you try something with permissions in the source location? Can you change the perms on the file you're metatagging to be mylar:mylar instead of nobody:users and making sure that the perms are set to at least 775 for testing purposes. Then try the metatagging again on that specific issue and see what happens

**Comment by DrSeussFreak** [comment]
So /media is a CFIS share to my NAS, the users don't map, hence the nobody:user ownership.  /SabNZBd is a NFS share to another Ubuntu box, and it is able to copy comics from /SabNZBd to /media, renaming them & setting permissions in the process.  If I su - to mylar, I can create a file, and remove it in /media/comics/Avatar/*

**Comment by evilhero** [comment]
Which box does the mylar application reside on?

If it can't create a file with the proper perms, it will default to your CIFS default perm settings which I'm guessing might not be set for default usage (most people dont set it unless they're having problems)

**Comment by DrSeussFreak** [comment]
mylar sits on "media-01" (Ubuntu 18.04)
sabnzbd sites on "sabnzbd-01" (Ubuntu 18.04)
/media is on NAS "nx-01" (Synology)

/etc/fstab is configured as follows

`//nx-01/comics /media/comics  cifs  credentials=/home/dsf/.smbcredentials,uid=nobody,gid=users,iocharset=utf8,noperm,sec=ntlm,vers=1.0 0  0`

**Comment by barbequesauce** [comment]
Tagging in on this given that I run CIFS and evilhero doesnt... it sounds like you're able to create files but not update them. Sounds weird, I know, but CIFS does allow that possibility...

What's the real ACL on \\nx-01\comics (both the share ACL and the filesystem ACL)?
What's in your .smbcredentials file (dont post the password)?

**Comment by DrSeussFreak** [comment]
on NX-01, it is all GUI based, and it is mapped to the dsf user as r/w permissions, there is nothing special there.  As for Ubuntu, not sure what you are looking for on media-01, as nothing special is configured, I just added the mylar (and sonarr and radarr) users to the users group.

/home/dsf/.smbcredentials contains
> username=dsf
> password=NotMyRealPW

**Comment by barbequesauce** [comment]
In CIFS there's a concept of a dropbox - you can write a file once but never modify it again. That's what I was hoping to see in the ACL.

Just for giggles - can you create a text file in /media/comics while sudo'ed to the mylar user, and save it? then try and edit/save the same file and see if it sticks...

**Comment by DrSeussFreak** [comment]
Just created a file, saved/quit, opened it, changed it, saved/quit - 4 times over, no problems.

I have sonarr and radarr running on the same machine (same setup but with radarr and sonarr accounts), they have no problems changing anything on the /media CIFS share

**Comment by DrSeussFreak** [comment]
HAH, ok, so I had just installed both, I had not thought of it, re-ran the post-processing step and it worked perfectly!  Nice catch, thanks :)

**Comment by barbequesauce** [comment]
great to hear!
