### ISSUE TITLE
Metatagger Error: File is not expected size: (NUMBER) vs 0

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1980]
Seeing this sometimes, I don't quite understand what's wrong, if I use Winrar or 7-Zip to test or extract the comic archive it works fine.  (To fix it, I manually extract and rezip the files and rename to .cbz).

`2018-06-09 11:09:27 | DEBUG | [META-TAGGER] readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 1]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 2]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 3]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 4]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 5]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 6]readArchiveFile(): [file is not expected size: 1561836 vs 0] /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbr:Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer)/Nightwing 016-000.jpg [attempt # 7]Error while copying to /config/mylar/cache/mylar_oZxqeW/Nightwing 016 (2017) (2 covers) (digital) (Minutemen-Slayer).cbz: Archive failed to export!
`

**Comment by evilhero** [comment]
Should be all fixed in latest development commit.

**Comment by LeeThompson** [comment]
Will try it out,
