### ISSUE TITLE
Parsing Issues

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1984]
When trying to match the following filenames failed to match with a series in the wanted list:

```
Brave and the Bold 064 DC 1966-Mar 36p c2c (Flattermann)
Brave and the Bold 133 DC 1977-Apr 36p c2c (flattermann mazen)
Brave and the Bold 136 DC 1977-Sep 36p c2c flattermann
```

When I renamed them by putting the years and other markers (e.g.: (c2c) (Flattermann)) in parentheses and removing the page count and month, Mylar recognized them.   (I haven't done an exhaustive test to try to isolate exactly what was confusing it, probably the page count.)

**Comment by LeeThompson** [comment]
Some scene members do some odd formatting, such as page counts and not using ()'s.  Parsing out page counts could be as simple as checking to see if a 'p' immediately follows a 1-3 digit number (and it will usually be after volume, issue and year).

**Comment by evilhero** [comment]
Unfortunately something that might seem simple is far more complex when you add in all the various naming conventions people use, along with all the different permutations of issue numbers, series titles, date sequences, etc.

If it can be added in without breaking other parts of the parser, I have no problems making the change. Pull requests are welcome for this.
