### ISSUE TITLE
rTorrent API changes

### ISSUE THREAD

**Issue by sparky3387** [evilhero/mylar#1987]
With newer versions of rtorrent API 
calls such as d.multicall no longer work, using the diffs from Couchpotato I managed to update the rtorrent library to use the new API calls, and it is now working well for me.

I have attached a patch file for review.
[rtorrent.txt](https://github.com/evilhero/mylar/files/2102332/rtorrent.txt)

(Edit: Cant attach a patch file so have created a GIST)

https://gist.github.com/sparky3387/58f294206595f1b571b24cdb02b0ddd0

**Comment by evilhero** [comment]
Nice job!

I'll have to make sure that this doesn't break non-updated versions of rtorrent, as there are lots that can't/won't update to the newest version, so I shall do some testing and merge if it's not problematic on that front :)

**Comment by evilhero** [comment]
Commit is live in development now (#24130a8) - much thanks for the gist that helped me fine-tune the changes so that it works regardless of rtorrent client version now :)
