### ISSUE TITLE
Feature Request: Manage Queue

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1990]
It would be helpful if under the Manage tab if we could see/edit/remove the download queue (torrent/nzb/etc), I see messages in the log like:

`Unable to locate item in active queue. Could it be finished already ?`

But it's hard to troubleshoot if it's a failed download or what because I don't know what comic/issue it's actually looking for.

**Comment by barbequesauce** [comment]
I think the History tab is what you're looking for, combined with looking at earlier lines of the log to know which NZB is the problem child...

**Comment by evilhero** [comment]
The active queue message is actually the active queue of your nzbget client. If it can't locate it in the active queue, then it checks the history of your client to see if it completed and then goes from there.
