### ISSUE TITLE
Moved Mylar to a new install location but it won't update

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#1992]
So, the VM I had Mylar on died so I have moved everything to the host.
I am having issues with 32p banning my IP but I will sort it with them. I did a clone as per the install instructions but now every time I start Mylar it says I am 68 commits behind and it doesn't update.

Configuration Options
Mylar Version: master
-- git build 60f69c0e285fb0de08968552b61895410d062016.
Python Version : 2.7.12Language : en_GB.UTF-8
--

**Comment by evilhero** [comment]
That git build is from the development branch, not the master. So either you git_branch field in the config.ini is set to development (and you cloned without the -b switch/didn't do a git checkout development), or its set to master (and you cloned with the -v switch, or did a git checkout development).

If you do a git status from the command line in the mylar directory it will show you what branch you're on.  Then make sure the git_branch in the config.ini is set to the same branch.
