### ISSUE TITLE
Wanted page not working

### ISSUE THREAD

**Issue by tomtom602** [evilhero/mylar#2004]
Since a week ago, I can't access my wanted page

I always have the error bellow :

Error !
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
71                        %>
72
73                        <tr class="${issue['Status']} grade${grade}">
74                                <%
75                                      linkit = 'comicDetails?ComicID=%s' % issue['ComicID']
76                                      try:
77                                          if issue['StoryArcID'] is not None:
78                                              lineheader = issue['StoryArc']
79                                              linkit = 'detailStoryArc?StoryArcID=%s&StoryArcName=%s' % 
(issue['StoryArcID'],issue['StoryArc'])
```
/opt/mylar/data/interfaces/default/upcoming.html, line 74:
`74                                <%`
/opt/mylar/data/interfaces/default/base.html, line 87:
`87			${next.body()}`
/opt/mylar/lib/mako/runtime.py, line 899:
`899     callable_(context, *args, **kwargs)`
/opt/mylar/lib/mako/runtime.py, line 873:
`873     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)`
/opt/mylar/lib/mako/runtime.py, line 838:
`838     **_kwargs_for_callable(callable_, data))`
/opt/mylar/lib/mako/template.py, line 462:
`462     return runtime._render(self, self.callable_, args, data)`
/opt/mylar/mylar/webserve.py, line 56:
`56      return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)`

**Comment by tomtom602** [comment]
Hi,
Sorry and thanks. 
I restarted Mylar and the problem have desapeared. I thought I did try that but obviously I didn't... 

Thanks

**Comment by barbequesauce** [comment]
Out of curiosity, what version are you on? The (hoped-for) fix is recent...

**Comment by tomtom602** [comment]
81252f3ebb42b1821c9ea66b8d258410a024fa8d (master) 

I did install an update a few days ago

**Comment by barbequesauce** [comment]
OK cool - that has the fix that should prevent this from recurring... thanks.
