### ISSUE TITLE
status idea

### ISSUE THREAD

**Issue by llpowwowll** [evilhero/mylar#201]
Ok I don't know if this is possible but with the whole idea of automation, would there be any to to automate a color scheme of status. 

Let me explain what I was thinking. I noticed on the home page of the application where it lists all comic titles and gives status, that some of the title's status says ended but the line is colored green and some say ended but the line is colored red. The reason they are red is because I have manually gone in and selected pause comic. I like the feature, but what I was thinking (if this is even possible) is if the series is ended after status lookup and mylar recognizes as having all the issues in the series then it would color the line green automatically. If the series has ended and there are issues still missing then it would color the line yellow. Just a thought I had. Let me know what you think...

**Comment by evilhero** [comment]
This kind of setup should be in the next development build. 

http://i.imgur.com/0Lhev4C.png

**Comment by evilhero** [comment]
There's more info on the mylar forums [here](http://mylar.forumatic.com/viewtopic.php?f=12&t=683#p3387)
