### ISSUE TITLE
Allow the User-Agent to be configurable

### ISSUE THREAD

**Issue by knobunc** [evilhero/mylar#2015]
The User-Agent header is sent as python-requests.  It would be nice to allow us to set that to a configurable string (especially for NZBHydra2 integration).

**Comment by evilhero** [comment]
Actually the user agent is a mutated version of python-requests with some Mylar information at the end. The "Mylar"  agent is used for all searches, so I'm not sure where you're seeing something contrary to that. 

I'm not sure what the benefit of having a custom header would do, as then it would seem you're trying to fool something into thinking you're something else. The only request that I can think of that uses the actual python-requests string is when it hits CV and that's for obvious reasons. Nzbhydra/2 works just fine regardless of the header being sent as well from what I've seen.

That being said, you could always just change the variable in the __init__.py module, but like I said changing thing ls might break stuff (ie. The backend that's used for the weekly pull as an example)

**Comment by knobunc** [comment]
Aha... It's the "test" button on the provider that sends python-requests:
```
	0x00d0:  4163 6365 7074 3a20 2a2f 2a0d 0a55 7365  Accept:.*/*..Use
	0x00e0:  722d 4167 656e 743a 2070 7974 686f 6e2d  r-Agent:.python-
	0x00f0:  7265 7175 6573 7473 2f32 2e37 2e30 2043  requests/2.7.0.C
	0x0100:  5079 7468 6f6e 2f32 2e37 2e31 3520 4c69  Python/2.7.15.Li
	0x0110:  6e75 782f 342e 3135 2e34 2d32 3030 2e66  nux/4.15.4-200.f
```
The searches correctly send Mylar.  I was just trying to get something intelligible in the NZBHydra stats, but when I sniffed the test I messed myself up.

Thanks!

**Comment by evilhero** [comment]
Argh, stupid test options I forgot about ;)

I'll set those to use the proper user agent as they should be sending the same string as the searches, etc.

Thanks for the detailed information too - the test buttons will be fixed in the next dev commit ;)

**Comment by knobunc** [comment]
Thank you!
