### ISSUE TITLE
NameError: 'coverfile' is not defined. Alternate Cover Image

### ISSUE THREAD

**Issue by trumblejoe** [evilhero/mylar#2017]
12-Jul-2018 03:56:00 - INFO :: mylar.addComictoDB.256 : Thread-20 : Directory (/home6/merciless1/files/rclone/gdriveCryptPrivatePlain/Comics/Batman Legends of the Dark Knight Halloween Special (1993)) already exists! Continuing...
12-Jul-2018 03:56:04 - INFO :: mylar.getImage.3516 : Thread-20 : Attempting to retrieve the comic image for series
12-Jul-2018 03:56:05 - INFO :: mylar.getImage.3546 : Thread-20 : Image size invalid [19989 bytes] - trying to get alternate cover image.
12-Jul-2018 03:56:05 - INFO :: mylar.addComictoDB.281 : Thread-20 : Attempting to retrieve alternate comic image for the series.
12-Jul-2018 03:56:07 - INFO :: mylar.getImage.3516 : Thread-20 : Attempting to retrieve the comic image for series
12-Jul-2018 03:56:09 - INFO :: mylar.getImage.3546 : Thread-20 : Image size invalid [26717 bytes] - trying to get alternate cover image.
12-Jul-2018 03:56:09 - ERROR :: mylar.excepthook.314 : Thread-20 : Uncaught exception: Traceback (most recent call last):
  File "/home6/merciless1/Mylar/mylar/logger.py", line 336, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home6/merciless1/Mylar/mylar/importer.py", line 295, in addComictoDB
    logger.error('Unable to save cover (' + str(coverfile) + ') into series directory (' + str(comiclocal) + ') at this time.')
NameError: global name 'coverfile' is not defined

Traceback (most recent call last):
  File "/home6/merciless1/Mylar/mylar/logger.py", line 336, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home6/merciless1/Mylar/mylar/importer.py", line 295, in addComictoDB
    logger.error('Unable to save cover (' + str(coverfile) + ') into series directory (' + str(comiclocal) + ') at this time.')
NameError: global name 'coverfile' is not defined

Up to date Development version of Mylar. Relevant setting selected: 'Place cover.jpg into comic folder' is selected. I do not have 'Alternate Series Covers' selected.

Was attempting to add comic from the home page. The image is not in the cache folder.

**Comment by trumblejoe** [comment]
The offending code is here, line 3498 helpers.py

if int(coversize) < 30000 or str(r.status_code) != '200':
        if str(r.status_code) != '200':
            logger.info('Trying to grab an alternate cover due to problems trying to retrieve the main cover image.')
        else:
            logger.info('Image size invalid [' + str(coversize) + ' bytes] - trying to get alternate cover image.')
        logger.fdebug('invalid image link is here: ' + url)

        if os.path.exists(coverfile):
            os.remove(coverfile)


----
Perhaps an obvious placeholder image could be used if the alternate cover image is not available?

**Comment by trumblejoe** [comment]
"Have you tried to re-add the given series to see if it's working now and
maybe it was just a CV glitch?"

Yes, I've tried the comic mentioned in the logs several times now
unsuccessfully. I have been adding in other comics without issues during
this time.

**Comment by zxvv** [comment]
The cover size for the example above was 15K for small, and 26K for large.
So, I created a pull request to reduce the minimum JPG cover size to 10K bytes.
I didn't see any discussion of other related issues, and looking at helper.py, my first impression is that this seems isolated enough that it should only affect the cover images.

**Comment by evilhero** [comment]
Weird, I was able to add both East of West and the Halloween Batman with no issues once I fixed the logging error (and that's all I had fixed at that point). 

Can you both please update to the latest development and then try to add those series again to see if they are able to get the covers properly with the fix now in place?

**Comment by zxvv** [comment]
Using dev version 76f802c083743b747cd01c1c5c81064a964197b2, East of West is added successfully.
It saved the cvinfo file and downloaded issues, but the cover is not saved to the folder in the 'comic location path', and is not shown in the comic details page.
The log shows:

Unable to save cover (/downloads/rutorrent/comics/East of West (2013)/cover.jpg) into series directory (/downloads/rutorrent/comics/East of West (2013)) at this time.

**Comment by zxvv** [comment]
Reducing the minimum cover.jpg file size might help this: #2025
