### ISSUE TITLE
Annuals aren't recognized

### ISSUE THREAD

**Issue by leaderdog** [evilhero/mylar#2024]
Hi Evilhero,

Haven't had this issue in a long time.  I can't get Mylar to recognize annuals.

I selected the annuals and chose "downloaded" from the download and it doesn't like them.

`17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.855 : Thread-37 : ALT-SERIES NAME [ISSUE TITLE]: Adventure Time [None]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.871 : Thread-37 : sf_highest_series_pos: ['Adventure', 'Time', '-']
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.903 : Thread-37 : series title possibly: Adventure Time
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.909 : Thread-37 : Alternate series / issue title: Adventure Time [None]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.listFiles.142 : Thread-37 : [FILENAME]: Adventure Time - Annual 001 - 2013.cbr
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.360 : Thread-37 : checking date : 2013
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.363 : Thread-37 : date: 2013
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.614 : Thread-37 : datecheck: [{'date': '2013', 'position': 6, 'mod_position': 30}]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.620 : Thread-37 : sctd: 2018
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.629 : Thread-37 : year verified as : 2013
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.635 : Thread-37 : year verified as: 2013
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.658 : Thread-37 : highest_series_position: 6
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.664 : Thread-37 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '001', 'mod_position': 24}, {'position': 6, 'validcountchk': False, 'number': '2013', 'mod_position': 30}]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.670 : Thread-37 : hyphen located at position: 15
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.672 : Thread-37 : yearposition: 6
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.681 : Thread-37 : Numeric detected as the last digit after a hyphen. Typically this is the issue number.
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.702 : Thread-37 : Already validated year, ignoring as possible issue number: 2013
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.707 : Thread-37 : issue number :001
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.736 : Thread-37 : issue_position: 4
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.747 : Thread-37 : issue verified as : 001
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.855 : Thread-37 : ALT-SERIES NAME [ISSUE TITLE]: Adventure Time [Annual]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.871 : Thread-37 : sf_highest_series_pos: ['Adventure', 'Time', '-', 'Annual']
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.903 : Thread-37 : series title possibly: Adventure Time - Annual
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.909 : Thread-37 : Alternate series / issue title: Adventure Time [Annual]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.listFiles.142 : Thread-37 : [FILENAME]: Adventure Time - Annual 001 - 2014.cbr
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.360 : Thread-37 : checking date : 2014
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.363 : Thread-37 : date: 2014
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.614 : Thread-37 : datecheck: [{'date': '2014', 'position': 6, 'mod_position': 30}]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.620 : Thread-37 : sctd: 2018
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.629 : Thread-37 : year verified as : 2014
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.635 : Thread-37 : year verified as: 2014
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.658 : Thread-37 : highest_series_position: 6
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.664 : Thread-37 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '001', 'mod_position': 24}, {'position': 6, 'validcountchk': False, 'number': '2014', 'mod_position': 30}]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.670 : Thread-37 : hyphen located at position: 15
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.672 : Thread-37 : yearposition: 6
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.681 : Thread-37 : Numeric detected as the last digit after a hyphen. Typically this is the issue number.
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.702 : Thread-37 : Already validated year, ignoring as possible issue number: 2014
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.707 : Thread-37 : issue number :001
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.736 : Thread-37 : issue_position: 4
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.747 : Thread-37 : issue verified as : 001
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.855 : Thread-37 : ALT-SERIES NAME [ISSUE TITLE]: Adventure Time [Annual]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.871 : Thread-37 : sf_highest_series_pos: ['Adventure', 'Time', '-', 'Annual']
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.903 : Thread-37 : series title possibly: Adventure Time - Annual
17-Jul-2018 12:57:33 - DEBUG   :: mylar.parseit.909 : Thread-37 : Alternate series / issue title: Adventure Time [Annual]
17-Jul-2018 12:57:33 - DEBUG   :: mylar.forceRescan.1006 : Thread-37 : No issues with identical issue numbering were detected for this series`

added the debug so not so messy.
[debug.txt](https://github.com/evilhero/mylar/files/2203814/debug.txt)

The files are there:
`Adventure Time - Annual 001 - 2013.cbr`
`Adventure Time - Annual 001 - 2014.cbr`

Does it just not like the date at the end?  Should I have it before the 001?  It used to work,  Now most all annuals are rejected and sitting in the Wanted List even tho they are in the folder.

Thanks.

wow the code looks like crap on here compared to your website.

**Comment by trumblejoe** [comment]
Try the filename format, Adventure Time Annual 001 (2014)

Annuals really are a PITA, I've found the easiest way is to add them by comicvine id, and then use Manual Post Processing to bring them into Mylar. I tried adding cvid files to everything, but it was way too much of a time-sink. Manual Post Processing isn't much better on that front, but it is a little better at the moment.

**Comment by leaderdog** [comment]
The odd thing is, it was fine before,  I don't know what was changed because I didn't change anything.  

Mylar did download some annuals today, but sadly I wasn't smart enough to look at them before they were cleared from sab.

Can you change the file format for just the annuals?  I'm not interested in having the date on every file.

But I do appreciate the reply.

**Comment by evilhero** [comment]
Annuals are flaring up again, and CV isn't handling them all the same way which is resulting in problems when Mylar goes to do specific tasks that it thinks is one way and it turns out to be completely different (hard to automate something when it's constantly changing between series).

That being said, your filenames just have the - in the wrong spot in one instance. Mylar assumes the issue number is ```001```, not ```Annual 001``` and because of that the series (in Mylar's determinations) should be just ```Adventure Time Annual``` and not ```Adventure Time```. The placement of the - within the filename tells Mylar (on a basic level) that it's a stop-gap and to think of both the preceding/following as independent statements. This is in large part due to the Annual Integration feature within Mylar, and how if it's not enabled - things would go boom.

So if you named it ```Adventure Time Annual - 001 - 2013.cbr``` it would filecheck just fine.

You can also change your File Format by using the ```$Annual``` tag (ie. ```$Series $Annual - $Issue - $Year```). If the issue that's being formatted isn't considered an Annual by Mylar, the $Annual tag gets removed entirely and it would just appear like a normal issue (in your case,  ```$Series - $Issue - $Year```)

**Comment by leaderdog** [comment]
I'll give that a whirl,  aw nuts, this means I have to go through almost all my annuals and rename them manually?  heh ouch.

The only thing I'm curious about is, they were marked as downloaded before, did cv change it so these ones were no longer recognized?  Did Mylar just do it's own refresh and decide it was now different?

Is it not possible for Mylar to just accept a title with "Annual" in it, as it's probably an annual? ;)
Perhaps there is the odd title that would have annual in it that wasn't an annual.  I don't have one in my library of books, but hey there could be one out there. :)

**Comment by leaderdog** [comment]
hmm, just tried it with: 
`(Classic) Battlestar Galactica v2 - Annual 2014 - 001.cbr`
I changed it to:
`(Classic) Battlestar Galactica v2 Annual - 001 - 2014.cbr`

It didn't like it, I turned on debug and did it again and this is what I get:

`20-Jul-2018 17:22:12 - DEBUG   :: mylar.listFiles.142 : Thread-38 : [FILENAME]: (Classic) Battlestar Galactica v2 Annual - 001 - 2014.cbr
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.527 : Thread-38 : volume label detected as : Volume 2 @ position: 3
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.360 : Thread-38 : checking date : 2014
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.363 : Thread-38 : date: 2014
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.614 : Thread-38 : datecheck: [{'date': '2014', 'position': 8, 'mod_position': 49}]
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.620 : Thread-38 : sctd: 2018
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.629 : Thread-38 : year verified as : 2014
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.635 : Thread-38 : year verified as: 2014
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.658 : Thread-38 : highest_series_position: 8
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.664 : Thread-38 : possible_issuenumbers: [{'position': 6, 'validcountchk': False, 'number': '001', 'mod_position': 43}, {'position': 8, 'validcountchk': False, 'number': '2014', 'mod_position': 49}]
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.670 : Thread-38 : hyphen located at position: 41
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.672 : Thread-38 : yearposition: 8
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.681 : Thread-38 : Numeric detected as the last digit after a hyphen. Typically this is the issue number.
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.702 : Thread-38 : Already validated year, ignoring as possible issue number: 2014
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.707 : Thread-38 : issue number :001
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.736 : Thread-38 : issue_position: 6
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.747 : Thread-38 : issue verified as : 001
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.752 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.754 : Thread-38 : new split: ['(Classic)', 'Battlestar', 'Galactica', 'Annual', '-', '001', 'v2', '-', '2014']
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.763 : Thread-38 : Volume detected as : v2
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.815 : Thread-38 : There are 3 extra words between the issue # and the year position. Deciphering if issue title or part of series title.
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.871 : Thread-38 : sf_highest_series_pos: ['(Classic)', 'Battlestar', 'Galactica', 'Annual']
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.903 : Thread-38 : series title possibly: (Classic) Battlestar Galactica Annual
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.905 : Thread-38 : [SPLITVALUE] possible issue title: v2 -
20-Jul-2018 17:22:12 - DEBUG   :: mylar.parseit.909 : Thread-38 : Alternate series / issue title: (Classic) Battlestar Galactica Annual v2 - [v2 -]
20-Jul-2018 17:22:13 - DEBUG   :: mylar.forceRescan.1006 : Thread-38 : No issues with identical issue numbering were detected for this series
20-Jul-2018 17:22:13 - DEBUG   :: mylar.forceRescan.1028 : Thread-38 : [ANNUAL-CHK] No annuals with identical issue numbering across annual volumes were detected for this series
20-Jul-2018 17:22:13 - DEBUG   :: mylar.forceRescan.1070 : Thread-38 : [FILE-RESCAN] temploc: Annual 001
20-Jul-2018 17:22:13 - DEBUG   :: mylar.issuedigits.1065 : Thread-38 : [] Invalid numeric for issue - cannot be found. Ignoring.
20-Jul-2018 17:22:13 - DEBUG   :: mylar.issuedigits.1082 : Thread-38 : this does not have an issue # that I can parse properly.
20-Jul-2018 17:22:13 - INFO    :: mylar.forceRescan.1461 : Thread-38 : [FILE-RESCAN] Total files located: 12
20-Jul-2018 17:22:13 - DEBUG   :: mylar.forceRescan.1559 : Thread-38 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: (Classic) Battlestar Galactica
20-Jul-2018 17:22:13 - INFO    :: mylar.forceRescan.1561 : Thread-38 : [FILE-RESCAN] I have physically found 12 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 12 / 13 ]
`

Same with Adventure time, renamed to this:
`Adventure Time Annual - 001 - 2013.cbr`

didn't change status and code:

`20-Jul-2018 17:30:21 - INFO    :: mylar.forceRescan.937 : Thread-40 : [FILE-RESCAN] Now checking files for Adventure Time (2012) in H:\boom studios/Adventure Time (2012)
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1298 : Thread-40 : as_start: 27 --- !!73436
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1303 : Thread-40 : as_start: 34 --- !!73436
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1306 : Thread-40 : [FILECHECKER] Extracted comicid for given annual : 73436
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1298 : Thread-40 : as_start: 26 --- !!62389
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1303 : Thread-40 : as_start: 33 --- !!62389
20-Jul-2018 17:30:21 - DEBUG   :: mylar.altcheck.1306 : Thread-40 : [FILECHECKER] Extracted comicid for given annual : 62389
20-Jul-2018 17:30:21 - INFO    :: mylar.traverse_directories.1198 : Thread-40 : there are 77 files.
20-Jul-2018 17:30:21 - DEBUG   :: mylar.listFiles.142 : Thread-40 : [FILENAME]: Adventure Time - 001.cbr
20-Jul-2018 17:30:21 - DEBUG   :: mylar.parseit.614 : Thread-40 : datecheck: []
20-Jul-2018 17:30:21 - DEBUG   :: mylar.parseit.656 : Thread-40 : No year present within title - ignoring as a variable.
20-Jul-2018 17:30:21 - DEBUG   :: mylar.parseit.658 : Thread-40 : highest_series_position: 4
20-Jul-2018 17:30:21 - DEBUG   :: mylar.parseit.664 : Thread-40 : possible_issuenumbers: [{'position': 3, 'validcountchk': False, 'number': '001', 'mod_position': 17}]
20-Jul-2018 17:30:21 - DEBUG   :: mylar.parseit.736 : Thread-40 : issue_position: 3

20-Jul-2018 17:30:27 - DEBUG   :: mylar.forceRescan.1070 : Thread-40 : [FILE-RESCAN] temploc: Annual 001
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1065 : Thread-40 : [] Invalid numeric for issue - cannot be found. Ignoring.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1082 : Thread-40 : this does not have an issue # that I can parse properly.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1065 : Thread-40 : [] Invalid numeric for issue - cannot be found. Ignoring.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1082 : Thread-40 : this does not have an issue # that I can parse properly.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.forceRescan.1070 : Thread-40 : [FILE-RESCAN] temploc: Annual 001
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1065 : Thread-40 : [] Invalid numeric for issue - cannot be found. Ignoring.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1082 : Thread-40 : this does not have an issue # that I can parse properly.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1065 : Thread-40 : [] Invalid numeric for issue - cannot be found. Ignoring.
20-Jul-2018 17:30:27 - DEBUG   :: mylar.issuedigits.1082 : Thread-40 : this does not have an issue # that I can parse properly.
20-Jul-2018 17:30:27 - INFO    :: mylar.forceRescan.1461 : Thread-40 : [FILE-RESCAN] Total files located: 75
20-Jul-2018 17:30:27 - DEBUG   :: mylar.forceRescan.1559 : Thread-40 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: Adventure Time
20-Jul-2018 17:30:27 - INFO    :: mylar.forceRescan.1561 : Thread-40 : [FILE-RESCAN] I have physically found 75 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 75 / 77 ]
`

I didn't add the file format yet, does that make a difference at this point?

**Comment by evilhero** [comment]
Wowza, 

Ok there was a bug in the code itself that was introduced into development ~10 commits ago in regards to being able to handle 'specials' as if they were 'annuals'. 

I've got it working in my local repo now (tested using the formats described by above @leaderdog for both Adventure Time & (C)BG), and all seems to working. I just need to code-dive abit more to make sure I got all the remnants as it was an initial minor code change, but it's carrying values thru to other modules which then affect other things.

**Comment by leaderdog** [comment]
oooooooooooooooooh yeaah!  that got it!  nice work as always!

All variations of Annual were recognized.

`Adventure Time - Annual 001 - 2014.cbr`
`Adventure Time Annual - 001 - 2013.cbr`
`Adventure Time - Annual 2013 - 001.cbr`
`(Classic) Battlestar Galactica v2 - Annual 2014 - 001.cbr`

Thanks for fixing it!

**Comment by Webby2687** [comment]
I'm having issues with annuals not being recognized, looking through this thread I was hoping renaming the files to match the examples above would help. Using Action Comics (2011) as an example, all of the 57 main comics were found. 

I have tried formatting files in the following variants with no luck:

`Action Comics Vol.2 Annual #01 (of 03) (December, 2012).cbr`
`Action Comics Vol.2 - Annual #01 (of 03) (December, 2012).cbr`
`Action Comics Vol. 2 - Annual #01 (of 03) (December, 2012).cbr`
`Action Comics - Vol. 2 - Annual #01 (of 03) (December, 2012).cbr`

Log for one example:
> 2019-03-23 11:41:21 | INFO | [FILE-RESCAN] I have physically found 57 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 57 / 60 ]
> -- | -- | --
> 2019-03-23 11:41:21 | INFO | [FILE-RESCAN] Total files located: 57
> 2019-03-23 11:41:20 | INFO | FAILED FILES: [{'series_volume': 'v2', 'issue_year': '2012', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics .2 -', 'scangroup': None, 'alt_series': 'Action Comics .2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics Vol.2 - Annual #01 (of 03) (December, 2012).cbr', 'issue_number': 'Annual 01', 'alt_issue': None}, {'series_volume': 'v2', 'issue_year': '2013', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics .2 -', 'scangroup': None, 'alt_series': 'Action Comics .2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics Vol.2 - Annual #02 (of 03) (December, 2013).cbr', 'issue_number': 'Annual 02', 'alt_issue': None}, {'series_volume': 'v2', 'issue_year': '2014', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics .2 -', 'scangroup': None, 'alt_series': 'Action Comics .2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics Vol.2 - Annual #03 (of 03) (September, 2014).cbr', 'issue_number': 'Annual 03', 'alt_issue': None}]
> 2019-03-23 11:41:20 | INFO | there are 60 files.
> 2019-03-23 11:41:20 | INFO | [FILE-RESCAN] Now checking files for Action Comics (2011) in F:\Kyle\Comics\Files\DC Comics\Action Comics\Vol 2

Log for same example, just slightly different file formatting:

> 
> 2019-03-23 11:57:30 | INFO | [FILE-RESCAN] I have physically found 57 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 57 / 60 ]
> -- | -- | --
> 2019-03-23 11:57:30 | INFO | [FILE-RESCAN] Total files located: 57
> 2019-03-23 11:57:29 | INFO | FAILED FILES: [{'series_volume': 'v2', 'issue_year': '2012', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics - 2 -', 'scangroup': None, 'alt_series': 'Action Comics - 2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics - Vol. 2 - Annual #01 (of 03) (December, 2012).cbr', 'issue_number': 'Annual 01', 'alt_issue': None}, {'series_volume': 'v2', 'issue_year': '2013', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics - 2 -', 'scangroup': None, 'alt_series': 'Action Comics - 2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics - Vol. 2 - Annual #02 (of 03) (December, 2013).cbr', 'issue_number': 'Annual 02', 'alt_issue': None}, {'series_volume': 'v2', 'issue_year': '2014', 'comiclocation': u'F:\\Kyle\\Comics\\Files\\DC Comics\\Action Comics\\Vol 2', 'series_name': 'Action Comics - 2 -', 'scangroup': None, 'alt_series': 'Action Comics - 2 - Annual Vol (of 03)', 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Action Comics - Vol. 2 - Annual #03 (of 03) (September, 2014).cbr', 'issue_number': 'Annual 03', 'alt_issue': None}]
> 2019-03-23 11:57:29 | INFO | there are 60 files.
> 2019-03-23 11:57:29 | INFO | [FILE-RESCAN] Now checking files for Action Comics (2011) in F:\Kyle\Comics\Files\DC Comics\Action Comics\Vol 2
> 
> 
>

**Comment by evilhero** [comment]
The problem is with the ```Vol. 2``` - specifically the decimal/period in there. When Mylar encounters a volume label, it removes the label entirely from the equation in order to get the actual series title. In this case, the decimal is throwing off the removal (instead of removing ```Vol. 2```, it's just removing the ```Vol.``` and leaving the ```2```). So I'll have to look at this some more, but it isn't going to be an easy fix as fixing for one thing will break 10 other things usually with the parser, but I'll see what can be done.

In the meantime, simply changing the naming structure abit will get those files scanned in - specifically renaming the ```Vol. 2``` to either ```V2``` or ```Vol2``` (note that case doesn't matter).

One thing to note as well,  is that you might want to avoid ```(of 3)``` unless it's an actual limited run. Tagging that to annuals causes problems as an annual isn't a limited run (ie. at the start of the 1st annual, it is not known at that time how many annuals there will be for the series, which is what the ```(of 3)``` should denote). The parser should ignore those values, however if/when the time comes when the ```(of 3)``` determines matches based on limited run values it might mess up future matching. Just a word of warning more than anything else.

**Comment by Webby2687** [comment]
Thank you for the quick response on this. I've been testing this and it appears to be working for annuals. I did find two other issues that seem to be tangentially related. I'll open a new issue for these though as they don't deal with annuals. Thanks again!
