### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#2028]
Just updated to Version: 1d9a28c10e291f30c08392450787774040e2f47c (development) and after doing so, I do my normal sort, Publisher. Comic, Status and then Active.  all of the 30 Days of Night series I have stay at the top.  They never move based on the sorting.

**Comment by barbequesauce** [comment]
Known issue relative to the addition of the alphabetical index at top, pending fix from the js library owner.

**Comment by barbequesauce** [comment]
Linking to open [issue](url
https://github.com/gyrocode/jquery-datatables-alphabetSearch/issues/3#issuecomment-413549471) in library dependency for this fix.
