### ISSUE TITLE
Extra padding option for long running comics - 000x

### ISSUE THREAD

**Issue by frameset** [evilhero/mylar#2046]
I make use of the excellent rename feature which pads short issue numbers to be longer, for example "Cool Comic 1" gets renamed to "Cool Comic 001", which is handy for reading in external applications since it will sort them into order.

However several long running comics now have issue numbers in the thousands, so this no longer works. Could you add an option for 000x, either globally or selectable in the per individual comic series settings.

**Comment by evilhero** [comment]
Should be able to do with some quick code changes that shouldn't be too difficult. I'll mark this as an enhancement request, since otherwise I probably won't remember it if something else happens.

**Comment by FrancisKunz** [comment]
Hi,

Just get the same question, any news about this enhancement ?

**Comment by kingfenix** [comment]
any updates on this? is there a way to edit something somewhere or some manual way to achieve this?

**Comment by barbequesauce** [comment]
This repository is largely unsupported as it's Python2. I believe this specific issue has been addressed in the Py3 version (https://github.com/mylar3/mylar3)

**Comment by kingfenix** [comment]
I am running python 3 version mylar 3, and it still only has 00x, nothing for 4 digits yet. Please and Thanks!

________________________________

**Comment by kingfenix** [comment]
just added this old request to new version so you can track it there

https://github.com/mylar3/mylar3/issues/539


________________________________
