### ISSUE TITLE
Sort by columns broken with the latest update

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#2058]
Hi,

The sort by Have column has stopped working since the latest update.
When clicking on sort by have instead of sorting by the proportion of have downloads it now sorts by the title first letter. If I click the sort field again is reverses the first letter sort order, still A-Z but De titles appear before Da titles for example.

I've also noticed that sorting by Publisher has the same odd effect now, clicking it sorts by the first letter of the title, clicking again reverses the order per letter. 

From what I can see now all columns are doing the same thing, could the new implementation be rolled back until it can be implemented correctly?

Would it also be possible to fix the sort so that it is still selected after a refresh of the page?

Mylar Version: master
-- source build 04fc85c4b0b2e887d79bd2ae13d189d0260509de.
Python Version : 2.7.14
Language : en_GB.cp1252

Many thanks

**Comment by barbequesauce** [comment]
Hi - 
It’s a known issue. The alphabetical index is done using a third-party library, and the ability to disable it to allow sorting of other columns is a pending request with that library owner (see [here](https://github.com/gyrocode/jquery-datatables-alphabetSearch/issues/3#issuecomment-413549471)).

I can certainly back out the change until we have an answer from that library owner, but I’m out of town until next week...

**Comment by BRTPOB** [comment]
> is out of town.
> replies to bug reports.

**Comment by barbequesauce** [comment]
Customer service baby!
