### ISSUE TITLE
// Shown in Home View

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#2069]
Hi there,

Minor Issue but thought it needed pointing out
On the home view on Mylar in the top left hand column I see two forward slashes which I'm sure shouldn't be there. I get this when accessing by ip, localhost and remote access on whichever machine I use.

Many thanks :)

Mylar Version: master
-- source build b98e0fc8263a1b6962fe75b1a0bd664c24188d19.
Python Version : 2.7.14
Language : en_GB.cp1252
Operating System: Windows 10 Pro Build 1803

**Comment by barbequesauce** [comment]
Thanks - this is related to the removal of the alphabetic index. The fix (with a working alphabetic index) is in the development branch presently...

**Comment by rutskiuk** [comment]
Wow, that was quick :) cheers
