### ISSUE TITLE
OPDS triggering a TypeError

### ISSUE THREAD

**Issue by AegisToast** [evilhero/mylar#2070]
OPDS doesn't seem to be working, though it's more than possible I'm doing something wrong. I'm running the latest Docker container, which I pulled this morning.

When I navigate to https://myurl.com/opds/ I get the following error:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 5160, in opds
    data = op.fetchData()
  File "/app/mylar/mylar/opds.py", line 84, in fetchData
    result = methodToCall(**self.kwargs)
  File "/app/mylar/mylar/opds.py", line 202, in _root
    gbd = mylar.CONFIG.GRABBAG_DIR + '/*'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I know the call is going to the right url, though, because Mylar logs these two lines every time I do it:

```
2018-07-28 07:20:30 | DEBUG | {}
2018-07-28 07:20:30 | DEBUG | Recieved OPDS command: root
```

I have several comics in my library and on my reading list, but is it possible those aren't being included in the OPDS library for some reason? That error makes me think it's not finding anything to return.

**Comment by barbequesauce** [comment]
Which branch and commit are you running?

There was a bug that came up last week relative to the grabbag_dir config setting not being set... a recent commit in development fixed it..

**Comment by AegisToast** [comment]
Well there you go!

The Docker image I was using (linuxserver/mylar) was using the master branch and was last built a couple days before #2058 (about 20 days ago). I built my own image using the development branch and it's working now.

Thanks for the help!
