### ISSUE TITLE
[Enhancement request] Library Genesis as Search provider

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#2072]
Hello,

I was wondering (since some old comics can't be found on newsgroup or torrent sometimes), would it be possible to integrate library genesis as search provider and download directly in http ?
Lazylibrarian did it for ebooks : https://github.com/DobyTang/LazyLibrarian

So i was wondering if that would be a possible enhancement to mylar ?

**Comment by barbequesauce** [comment]
I think this is a good idea, but it’s not simple -

The workflow for torrents and nzbs are basically the same, while libgen is direct download and would be a bolt-on of a new set of processes. That said, there are a number of DDL sites out there that could be integrated similarly to libgen.

If EvilHero likes the idea I can put it on my medium-term list, but there are a few other items that will happen first...

**Comment by sam5558** [comment]
+1 for this proposition.

The only source i found for getting my Mangas (in french) is libgen.io so i desperatly want this feature with Mylar.

**Comment by yongbi85** [comment]
I’m bumping this just in case..
For information LazyLibrarian decided to integrate comics but mylar is way better for those for sure.
The only thing is that damn direct download...
https://gitlab.com/LazyLibrarian/LazyLibrarian

**Comment by barbequesauce** [comment]
It's on the to-do list for sure - there's some kinks with the base code that are being worked through first. Stay tuned!
