### ISSUE TITLE
Minor possible graphics bug

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2073]
HI

Were you aware of this appearance? It's fully functional, just looks odd.
![screen shot 2018-09-09 at 9 32 38 am](https://user-images.githubusercontent.com/97095/45266780-50efb600-b415-11e8-8c03-e8a41dce6523.jpg)

**Comment by barbequesauce** [comment]
Where do you see this?

**Comment by AtariBaby** [comment]
Hi!

I should have done a better screenshot, duh! This is a new (re)installation on Windows 10 Pro, on Chrome, all fully updated. It appears at the top and bottoms of these pages. Upon further investigation, it doesn't appear this way on my Mac and Safari.

![screen shot 2018-09-09 at 12 52 54 pm](https://user-images.githubusercontent.com/97095/45268369-03cd0d80-b430-11e8-8d23-50e4ab753af1.jpg)

**Comment by evilhero** [comment]
Chrome will cache stuff which will cause problems when viewing (I don't know the logistics but it's a pain).

Try going into an incognito tab within chrome and viewing the mylar home page. There's a good chance it'll display normally as the other browsers are fine you said.

**Comment by AtariBaby** [comment]
Curiously, I did incognito and it looked fine! I then deleted the entire Chrome image cache and restarted, but the problem still exists. I guess just close it, because it's something only affecting me and it's a minor graphical issue only.

**Comment by AtariBaby** [comment]
It does but sounds like it's specific to a little quirk with chrome. I am happy to do things if it will help you guys, but don't want to waste anyone's valuable time. Very grateful for all you do! It's not a problem for me at all.

**Comment by barbequesauce** [comment]
So I installed Chrome to see what it's caching - apparently the .js and .css files get cached. 

I know in a previous response you said you deleted the image cache, but just in case... using "Clear Browsing Data" under Preferences - Advanced seems to clear out the problem files. You'll want to select a time range of "All Time"; All the "Basic" checkboxes should be checked. That will remove files as indicated [here](https://stackoverflow.com/questions/36246168/how-to-find-cache-information-in-chrome); note that the /js & .css are inside those blob db's and not stored as flat files.
