### ISSUE TITLE
Issues with importing The Dead (v2014)

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2088]
When I try to import The Dead it is locking up Mylar with the following error.  I don't see any errors in my file naming, The Dead Vol.2014 #04 (2015), that would cause this or any obvious issues with the wiki entry. 

06-Oct-2018 15:25:19 - INFO :: mylar.preSearchit.4037 : Thread-13 : [IMPORT][The Dead (v2014)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
06-Oct-2018 15:25:55 - ERROR :: mylar.excepthook.314 : Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\mylar\logger.py", line 336, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\mylar\webserve.py", line 4231, in preSearchit
    totalyear_range = int(result_year) + totalissues    #2000 + (101 / 12) 2000 +8.4 = 2008
ValueError: invalid literal for int() with base 10: '198-'

I was able to search for the show manually to add it that way and then manual post-processing worked fine. I am running the master branch Version: b98e0fc8263a1b6962fe75b1a0bd664c24188d19 (master)

**Comment by hubbcaps** [comment]
Hey Evilhero,

Long time no talk, need to get my IRC bouncer back up. Hope you're doing well.

I'm getting a lot of these types of errors lately as well.

Example search that leads to it:

match_check: {'justthedigits': '001 MU', 'match_type': None, 'issue_year': '2017', 'comiclocation': None, 'series_name': u'Uncanny Inhumans', 'annual_comicid': None, 'volume': None, 'scangroup': None, 'alt_series': None, 'series_volume': None, 'sub': None, 'comicfilename': u'Uncanny.Inhumans.001.MU.2017.Digital.Zone-Empire', 'process_status': 'match', 'alt_issue': None}

and the traceback:

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/helpers.py", line 3059, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/app/mylar/mylar/search.py", line 1822, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 353, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 1365, in NZB_SEARCH
pc_in = int(parsed_comic['issue_number'])
ValueError: invalid literal for int() with base 10: '001 MU'
```

I'm also getting it for issues that have AU included in them, and for decimal issues like 100.5 etc etc

If there's any other info I can provide let me know. Everytime mylar hits one of these now it really bogs down everything and ends up in some DB locking errors being spewed until it gives up the operation or I restart mylar

**Comment by evilhero** [comment]
Heya man! 

Yeah long time no talk - those of us in the irc were wondering what happened to you and hoping that everything's alright. Glad to see you're still kicking it - definitely should hop back on when you get a chance and catch-up,

As far as the error, I can reproduce that on my end now - so I should be able to take care of it. The search code got a bit of an upgrade recently so that it uses the the filechecker module to verify/parse the search results. Which was fine and seemed to work better than previously, but then I added in TPB/GN support and it's been a game of catchup ever since...

So I'll look into the alpha/decimal problems with issue numbering - I'm going to guess that the db locking is due to the search queue getting locked up and never being able to release properly due to the error. Hopefully once the parser can handle the alpha/decimal stuff properly the lockups shouldn't occur anymore.

**Comment by hubbcaps** [comment]
Ayyy that commit seems to have done the trick! Go the above mentioned issue DL'd, gonna work on getting the others I set to skip back to wanted once this queue of 4k issues gets worked through lol

Appreciate you fixing it so quick dude. Ima try to get ZNC set back up next weekend and get back into chat, life's been crazy the past few months. Hopefully see you guys soon!
