### ISSUE TITLE
Sort order not preserved between sessions

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#2089]
Hi,

I have noticed that the sort order doesn't seem to preserve between sessions. I can change the sort order and that works perfectly but if I reboot and reload it goes back to the default - ie by name.

Many thanks :)

Mylar Version: master
-- source build b98e0fc8263a1b6962fe75b1a0bd664c24188d19.
Python Version : 2.7.14
Language : en_GB.cp1252
Operating System: Windows 10 Pro Build 1803

**Comment by barbequesauce** [comment]
PR #2091 looks like it will address this.

**Comment by rutskiuk** [comment]
Looking good to me, both the sort order and the number of entries per page seem to be preserved between sessions. Any news when this will be pushed out to master?

**Comment by barbequesauce** [comment]
There’s no real schedule on that - it’s basically a question of how much net change there is, and how stable the accumulated changes are(evilhero’s free time comes into the equation as well)
