### ISSUE TITLE
error before even installing

### ISSUE THREAD

**Issue by EarthboundPanda** [evilhero/mylar#2094]
im literally brand new to git and github so please dont judge, but when i type "python c:\Mylar\Mylar.py" into the cmd i get this.

File "c:\Mylar\Mylar.py", line 66
    print 'language detected as non-English (%s). Forcing specific logging module - errors WILL NOT be captured in the logs' % logger.LOG_LANG

help...

**Comment by EarthboundPanda** [comment]
Yes it is set to English.. i checked.

**Comment by evilhero** [comment]
Mylar only works with python 2.7.x, it looks like you're trying to run mylar using python 3.

**Comment by EarthboundPanda** [comment]
It worked! thanks!
