### ISSUE TITLE
mylar won't start (cannot open /etc/init.d/functions)

### ISSUE THREAD

**Issue by sinfulz** [evilhero/mylar#2097]
When running this command:
`systemctl status mylar.service journalctl - xe`

I get this output:
```
● mylar.service - LSB: starts Mylar
   Loaded: loaded (/etc/init.d/mylar; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-10-14 22:47:31 AEDT; 20s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25032 ExecStart=/etc/init.d/mylar start (code=exited, status=2)

Oct 14 22:47:31 mediaserver systemd[1]: Starting LSB: starts Mylar...
Oct 14 22:47:31 mediaserver mylar[25032]: /etc/init.d/mylar: 14: .: Can't open /etc/init.d/functions
Oct 14 22:47:31 mediaserver systemd[1]: mylar.service: Control process exited, code=exited status=2
Oct 14 22:47:31 mediaserver systemd[1]: Failed to start LSB: starts Mylar.
Oct 14 22:47:31 mediaserver systemd[1]: mylar.service: Unit entered failed state.
Oct 14 22:47:31 mediaserver systemd[1]: mylar.service: Failed with result 'exit-code'.
```
I am running the latest version of mylar.
Thanks

**Comment by evilhero** [comment]
Have you tried running mylar as a non-daemon to see if it works?

How did you setup your systemd with mylar (did you follow instructions somewhere)?

It looks almost like you don't have a systemd setup for mylar - you execstart is pointing to init.d which is incorrect as it should be pointing to your /etc/systemd/system/mylar.service file in which the execstart contains the full run command, not an init.d call.

**Comment by adriangigliotti** [comment]
> Have you tried running mylar as a non-daemon to see if it works?
> 
> How did you setup your systemd with mylar (did you follow instructions somewhere)?
> 
> It looks almost like you don't have a systemd setup for mylar - you execstart is pointing to init.d which is incorrect as it should be pointing to your /etc/systemd/system/mylar.service file in which the execstart contains the full run command, not an init.d call.

So I fixed the error message by manually creating a /etc/init.d/functions file. 
I now recieve another error which I fixed, which then resulted in another error; and so on.

I also realised the tutorial written for Mylar is for Ubuntu 14.04 (which is outdated). 
Are you able to do a quick writeup for Ubuntu 16.04? I would love to get this working!

Thank you.

**Comment by evilhero** [comment]
Have you checked the read.me file in the init-scripts/systemd folder within the mylar repository for instructions?

You're setting up initd, and trying to run it as systemd, and that won't work. Try to follow the read.me in the above location and use the files included therein as a template for your own system as required/indicated.

**Comment by adriangigliotti** [comment]
Followed exactly what you said

> Check the read.me file in the init-scripts/systemd folder within the mylar repository for instructions on systemd setup.
> 
> You're setting up initd, and trying to run it as systemd, and that won't work. Try to follow the read.me in the above location and use the files included therein as a template for your own system as required/indicated.

Although when running:
`sudo systemctl enable mylar`
I get this error:
```
Synchronizing state of mylar.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable mylar
insserv: warning: script 'K01mylar' missing LSB tags and overrides
insserv: warning: script 'mylar' missing LSB tags and overrides
update-rc.d: error: mylar Default-Start contains no runlevels, aborting.
```
I also found a few errors with your `read.me` file I will try and correct and create a pull request.

Side note: I noticed after installing Mylar there is a `centos.init.d` file in `/opt/Mylar/init-scripts`. I am running Mylar on Ubuntu. (not sure if this causes any issues).

Looking forward to your reply.
Cheers.

**Comment by evilhero** [comment]
If you're planning on using systemd (which is what Ubuntu 16.04 uses) you just need the files in the systemd folder, not the ones in the init.d folder. 

Lots of us use Ubuntu with no problems (I'm running 16.04 myself with the systemd setup as per the instructions included).

It looks like you have some extra scripts thay are causing problems (ie. K01mylar whatever that is), and you may not have setup the config options correctly in the mylar.service file since its throwing LSB errors.

**Comment by adriangigliotti** [comment]
> If you're planning on using systemd (which is what Ubuntu 16.04 uses) you just need the files in the systemd folder, not the ones in the init.d folder.
> 
> Lots of us use Ubuntu with no problems (I'm running 16.04 myself with the systemd setup as per the instructions included).
> 
> It looks like you have some extra scripts that are causing problems (ie. K01mylar whatever that is), and you may not have setup the config options correctly in the mylar.service file since its throwing LSB errors.

Still no luck. I tried to clean up the init.d (mylar) files but I am still receiving an error:

```
sudo systemctl enable mylar
Synchronizing state of mylar.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable mylar
insserv: warning: current stop runlevel(s) (empty) of script `mylar' overrides LSB defaults (0 1 6).
insserv: warning: current stop runlevel(s) (empty) of script `mylar' overrides LSB defaults (0 1 6).
Failed to execute operation: Too many levels of symbolic links
```

Do you have Discord so we can communicate easier and get this working?

Cheers.

**Comment by barbequesauce** [comment]
A few of us hang out on IRC. #mylar on irc.freenode.net. Typically more people around on weekdays...

**Comment by barbequesauce** [comment]
Are you all sorted?

**Comment by barbequesauce** [comment]
Are you all sorted here?

**Comment by DrSeussFreak** [comment]
I was running into this same issue, I just rebuilt my home lab.  If you utilize /opt/Mylar/init-scripts/init.d over /opt/Mylar/init-scripts/systemd you should be fine.  

My /etc/default/mylar looks like

```
MYLAR_USER=mylar
MYLAR_HOME=/opt/Mylar
MYLAR_DATA=/opt/Mylar
```

and the /etc/init.d/mylar is an exact copy of /opt/Mylar/init-scripts/init.d/ubuntu.init.d.

I then ran systemctl enable mylar and service mylar start, I am golden.
