### ISSUE TITLE
not finding files that I can see in NZB Hydra

### ISSUE THREAD

**Issue by Tomservov2** [evilhero/mylar#2098]
[mylar.log](https://github.com/evilhero/mylar/files/2492632/mylar.log)
![hydra results](https://user-images.githubusercontent.com/25776847/47167436-21f61b00-d2c4-11e8-98b6-73123e72990b.JPG)

**Comment by Tomservov2** [comment]
Tried rss, tried not.  finally re-installed and redid all config to make sure it wasn't something messed up in there.

**Comment by evilhero** [comment]
Pretty sure mylar won't be able to parse those titles as they have the header "crap" at teh beginning which mylar assumes is part of the filename. Seeing as how those results are probably from one of your 2 raw indexers - ttlry enabling experimental search within Mylar. The experimental search option looks at nzbindex and is able to parse out the crap as that's what's expected. Doing so from an actual nzb indexer, well really whatever indexer has that kind of stuff as the title for an nzb isn't doing the job of parsing the titles properly for the indexer.

**Comment by Tomservov2** [comment]
A - Figured out I was using old NZB Hydra, switched to version 2
B - Got NZB Geek working with it, so good now

Would be nice if I could filter for just the filename on NZB Index somehow

Thanks
