### ISSUE TITLE
Mylar won't recognize issue number

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2102]
I am having an issue with Mylar recognizing a specific issue number.  The issue in question is

**Quantum and Woody! 0.0001½**

I am using comic tagger to name this file and the current file name is as follows

**Quantum and Woody! #000.0001½ (2017).cbz**

No other issues have had this problem so far, seems specific to this.

**Comment by edimusxero** [comment]
awesome, thanks

**Comment by JPNYC81** [comment]
Same thing happens for issues with a "point something" on the comicvine and issue filename.
**https://comicvine.gamespot.com/original-sin/4050-73241/**
Original Sin 3.1, Original Sin 3.2, ...
gets pulled down and registered but cannot be matched cause it cannot be parsed properly.

**Comment by evilhero** [comment]
Unfortunately, not the same thing as OP had posted in regards to. Please don't add on to an existing issue with a different problem as tracking issues that do this are impossible for me to address properly. 

That being said, Mylar will parse decimal issues fine - however it will depend entirely on how you have your files named. Subsetting decimal issues with an issue title within the filename will not be able to be parsed properly.

Please indicate what your naming convention is for the files with the problem, as issues with decimal places for that particular series parse in fine for me. 

Ideally if you can start a new issue with thr relevant problem/information it would be more helpful.

**Comment by JPNYC81** [comment]
sorry about that.
Yeah, it's the subtitle that's doing it. I guess it can be ignored.
