### ISSUE TITLE
Manual Post Processing: Incorrect duplicate detection

### ISSUE THREAD

**Issue by blackswansolutions** [evilhero/mylar#2104]
I think I've come across an edge case problem with the manual post processing (not sure if it affects anywhere else)

What appears to be happening is if comics with a hyphen/dash "-" in the name happen to match a comic/series on both sides of the dash it's being detected as two separate issues to be processed. 

Once the processing begins the issue is processed (usually fairly correctly) as usual. However immediately after the processing tries to process the same issue again, needless to say the issue is no longer there and "I can't find it, it's been renamed or something" error is spat out.. 

22-Oct-2018 14:53:18 - INFO :: mylar.Process_next.1745 : Thread-94 : [POST-PROCESSING] [33/124] Starting Post-Processing for Batgirl and the Birds of Prey issue: 1
22-Oct-2018 14:53:20 - WARNING :: mylar.run.232 : Thread-94 : [META-TAGGER][COMIC-TAGGER] file is not in a RAR format: Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz
22-Oct-2018 14:53:20 - INFO :: mylar.run.184 : Thread-94 : [META-TAGGER] ComicRack tagging meta-tagging processing started.
22-Oct-2018 14:53:24 - INFO :: mylar.run.255 : Thread-94 : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/Users/dan/Mylar/cache/mylar_9BbFCX/Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz]
22-Oct-2018 14:53:24 - INFO :: mylar.run.184 : Thread-94 : [META-TAGGER] Comicbooklover tagging meta-tagging processing started.
22-Oct-2018 14:53:27 - INFO :: mylar.run.255 : Thread-94 : [META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [/Users/dan/Mylar/cache/mylar_9BbFCX/Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz]
22-Oct-2018 14:53:27 - INFO :: mylar.Process_next.2073 : Thread-94 : [POST-PROCESSING] Sucessfully wrote metadata to.cbz (Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz) - Continuing..
22-Oct-2018 14:53:27 - INFO :: mylar.validateAndCreateDirectory.1369 : Thread-94 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Storage/Comics/DC Comics/Batgirl and the Birds of Prey (2016)
22-Oct-2018 14:53:27 - INFO :: mylar.Process_next.2245 : Thread-94 : [POST-PROCESSING] move successful to : /Volumes/Storage/Comics/DC Comics/Batgirl and the Birds of Prey (2016)/Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz
22-Oct-2018 14:53:27 - ERROR :: mylar.tidyup.275 : Thread-94 : [POST-PROCESSING] /Volumes/Storage/Import/2011/Batgirl & the Birds of Prey Rebirth (2016) not empty. Skipping removal of directory - this will either be caught in furtherpost-processing or it will have to be manually deleted.
22-Oct-2018 14:53:27 - INFO :: mylar.foundsearch.857 : Thread-94 : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
22-Oct-2018 14:53:27 - INFO :: mylar.foundsearch.914 : Thread-94 : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Batgirl and the Birds of Prey issue: 1
22-Oct-2018 14:53:27 - INFO :: mylar.Process_next.2405 : Thread-94 : [POST-PROCESSING] Post-Processing completed for: Batgirl and the Birds of Prey #1
22-Oct-2018 14:53:27 - INFO :: mylar.duplicate_filecheck.2089 : Thread-94 : [DUPECHECK] Duplicate check for /Volumes/Storage/Import/2011/Batgirl & the Birds of Prey Rebirth (2016)/Batgirl and the Birds of Prey - Rebirth 01 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz
22-Oct-2018 14:53:27 - WARNING :: mylar.duplicate_filecheck.2093 : Thread-94 : [DUPECHECK] File cannot be located inlocation specified. Something has moved or altered the name.
22-Oct-2018 14:53:27 - WARNING :: mylar.duplicate_filecheck.2094 : Thread-94 : [DUPECHECK] Make sure if you are using ComicRN, you do not have Completed Download Handling enabled (or vice-versa). Aborting
22-Oct-2018 14:53:27 - ERROR :: mylar.excepthook.315 : Thread-94 : Uncaught exception: Traceback (most recent call last):
  File "/Users/dan/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/dan/Mylar/mylar/PostProcessor.py", line 1314, in Process
    if dupthis['action'] == 'dupe_src' or dupthis['action'] == 'dupe_file':
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "/Users/dan/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/dan/Mylar/mylar/PostProcessor.py", line 1314, in Process
    if dupthis['action'] == 'dupe_src' or dupthis['action'] == 'dupe_file':
TypeError: 'NoneType' object has no attribute '__getitem__'

Orginally I thought it just wasnt processing  the names well when they had hyphens in the issue name, wasn't until the last couple of times when I realised that it seems to happen when there's a match on both sides of the hyphen (in the above case, batgirl and the birds of prey and also rebirth.)

**Comment by evilhero** [comment]
It's actually due to the fact that Mylar is matching on more than one series in your watchlist for the given series, the fact that the dash is present is a contributing factor to a degree. When Mylar sees a dash in the filename, and the series does not contain a given dash, it assumes it could be the start of an issue title. So when it sees ```Birds of Prey - Rebirth``` it will double-match (assuming you have both Birds of Prey and Birds of Prey: Rebirth in your watchlist), once for ```Birds of Prey``` and another for ```Birds of Prey - Rebirth```. It does the double-matching because, well standards suck and people generally suck for having any kind of normalized naming scheme, so it has to try to adapt to alot of different schemes.

Now this should have been addressed in the one of the recent development commits, where it would stop after the initial post-processing run. The problem in this case, and in another of said issue, is that it's actually post-processing the issue into the wrong series which isn't a very good thing, at all.

I'll look into this again today with some free time hopefully, and can figure out the multiple matching problem as once that's fixed, then your problem should go away...

**Comment by dantreacy** [comment]
Thanks for the details, that makes sense looking at when it has happened. 

I seem to remember from quite some time ago there was a script floating around (it MAY have been on the ComicRack forums) that did a pretty excellent job of "normalising" a myriad of disparate naming schemes that people seemed to use. Unfortunately I haven't been able to find the script again and haven't had a chance to revive the old PC machine I'm pretty sure it was running on back then. The script itself was excellent, worked all kinds of magic. I can't remember if it was a perl or python script, pretty sure it would have been one of the two. Just thought I'd mention it, in case you weren't aware of it as regardless of the language, shouldn't be too difficult to grab the regex's or even the algo to possibly help or add on to the work being done.  If i get a chance in the next few weeks will do my best to see if I can find it.  

Let me know if you need any other help testing stuff.

**Comment by evilhero** [comment]
I tested against the same series' you were trying - got the exact same error. I then tested it against the fix and it post-processed against the correct series and didn't try to pp the same item again. So hopefully this fixes things going forward.... please let me know if things work (as this also addresses 2 other similar issues that are probably related to this).

**Comment by dantreacy** [comment]
My evidence at this stage is anecdotal but from some intitial testing it appears the original duplicate bug is gone, however it seems from my testing that the updated script seems to only be picking up a single issue from each series if manual PP is run on a group of mixed comics. 

I also tried on a single clean directory with the missing issues from a series that was missing issues in the DB when I ran MPP on that it appeared to only chose one issue each run through over Bout 4 or 5 run throughs. Yet when I revert to the previous commit (before the fix) I ran MPP again and the remaining 8 issues in the series were grabbed all at once.

**Comment by evilhero** [comment]
In hindsight, and without even looking at the code based on your description, I know exactly what it's doing and how to fix it. 

I based the fix off of just comicid when it should have been a varied combination of both comicid & issueid when trying to determine duplication.

I'll get a fix out in the a.m. for this, as I'm pretty sure this is a relatively quick fix.

**Comment by evilhero** [comment]
One day late (due to circumstances outside of my control), but this should all be fixed up for all the manual post-processing issues mentioned in this thread. I tested against the initial series that were causing problems, as well as multiple issues of the same series within the same manual post-processing directory and everything went well. :)
