### ISSUE TITLE
Story Arc Love (Enhancements)

### ISSUE THREAD

**Issue by evilhero** [evilhero/mylar#2108]
We're trying to improve the story arc feature within Mylar, as it's been present for awhile now and has always been hidden away, and worked on silently as things were needed.

So now's hopefully the time to add in some love for story arcs - and some enhancements. This is what was suggested thus far via irc:

- make it more prominent in the menu (ie. main page option)
- reading order sequence can get out of sort / mess. 
- Poster/Banner GUI options could stand to be made clearer and perhaps more intuitive.
- Recheck files option (it's the ```Search for Watchlist matches``` but it's not really clear what it encompasses) 
- add the wanted/snatched/etc mass change options just like is present for series
- when adding an arc, add in all the series in the given arc that are not currently in the watchlist, into the watchlist.
- if a tradepaperback is listed in the arc (cause you know, stupid people), reverse lookupthestuff and use that information so that it will show the individual issues instead of the tpb.

**Comment by frameset** [comment]
I'm happy to see this, especially the re-ordering. ComicVine took away the ability for its wiki editors to re-order the list of issues on their site, instead ordering strictly by release date.

Obviously anyone who actually reads comics knows why this is terrible, so being able to re-order in mylar for reading via OPDS is exciting!

**Comment by barbequesauce** [comment]
When you remove an arc, can we add a popup asking if we should remove files as well (like with a series)?
