### ISSUE TITLE
Ignored Issues Still Being Counted

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#2111]
I have noticed that if I ignore an issue - like a preview issue for example it is still being counted in the total. If I ignore an issue I would expect it to be ignored not just for downloads but also for the proportion of downloads so the ignored issue is not counted in the total. 
I'm not sure if this counts as a bug or a request for enhancement but certainly the current behaviour has the effect of reminding you of something you have already asked to be ignored.

![image](https://user-images.githubusercontent.com/25068977/48380046-40d2ac00-e6ce-11e8-9fae-b1e131b0a4d0.png)

![image](https://user-images.githubusercontent.com/25068977/48380067-547e1280-e6ce-11e8-862d-caca8c3cd94f.png)

**Comment by evilhero** [comment]
Not quite sure if this is possible without messing up some other factors that go into the counts portion. I'll look into it as I get what you're saying - but I honestly can't quite recall atm what it's original intent was (ie. just for display, or something far deeper code-wise).

**Comment by Tailchakra** [comment]
+1 to this. Sonarr/Radarr and Lidarr do this aswell. Maybe -1 the total for every ignored or just set ignored to the same as downloaded?

**Comment by evilhero** [comment]
Just looking into this now, but it looks like this has already been included within Mylar, but as a hidden config option in the config.ini.

The value in the config.ini of ```ignore_havetotal``` should be set to True, which will then increment the have count as if the item was downloaded while maintaining the status of Ignored. You do have to do a Recheck Files after you change the status to Ignored in order for the counts to be adjusted properly however.

**Comment by rutskiuk** [comment]
I had a quick look at how SickChill works with ignored TV episodes and that reduces the total rather than increasing the number of downloads:

![image](https://user-images.githubusercontent.com/25068977/48719013-669f0a00-ec14-11e8-8e77-d1b837ec2b97.png)
Became this when an episode was ignored
![image](https://user-images.githubusercontent.com/25068977/48718933-3ce5e300-ec14-11e8-8c53-b8a5dfbf789b.png)

**Comment by rutskiuk** [comment]
Brilliant! Shut down, edited the ignore_total, started Mylar, rechecked the files and it's now just what I was looking for (seriously, those preview issues have been nagging me for years).
