### ISSUE TITLE
Mylar won't start

### ISSUE THREAD

**Issue by hmdrmch** [evilhero/mylar#2119]
Installed on a clean Ubuntu 16.04 headless server with the guide provided from https://www.htpcguides.com/install-mylar-ubuntu-usenet-comics/

Got the following error when trying to run from command line:

Traceback (most recent call last):
  File "/opt/Mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/Mylar/mylar/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/opt/Mylar/lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "/opt/Mylar/lib/apscheduler/schedulers/base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

Not sure what to do from here.

**Comment by evilhero** [comment]
as taken from https://github.com/evilhero/mylar/issues/1929#issuecomment-383571703:
Looks like your pkg_resources module isn't there any more for some reason. You have to reinstall it. Normally it's either ```pip install pkg_resources --upgrade``` or ```sudo apt-get install --reinstall python-pkg-resources``` (for Ubuntu /debian)

**Comment by hmdrmch** [comment]
Great stuff! That did the trick. Thanks a bunch.
