### ISSUE TITLE
Issue finding files for series with number in title

### ISSUE THREAD

**Issue by miracle152005** [evilhero/mylar#2121]
Hi,

I have an issue with finding the files for a series with a number in the title.
Series:
Actionverse Featuring the F1rst Hero (2016)

Log:
`FAILED FILES: [{'issue_year': '2015', 'comiclocation': u'E:\\Comics\\Action Lab/Actionverse Featuring the F1rst Hero (2016)', 'series_name': 'Actionverse Featuring the F1rst Hero', 'alt_series': None, 'scangroup': None, 'series_volume': 'v2016', 'sub': None, 'parse_status': 'failure', 'comicfilename': 'Actionverse Featuring the F1rst Hero V2016 #001 (2015-03-31).cbz', 'issue_number': '001', 'alt_issue': None}]`

Could you please take a look and provide hints how to rename the files?

Thanks.

Best regards
miracle152005

**Comment by evilhero** [comment]
Update to the latest development build (f213bb0) - the fix is now in there to account for this problem as it was a problem with the way the file parser was handling series that had the word ```the``` within the series title (F1rs```t He```ro).

**Comment by miracle152005** [comment]
Thanks.
Its working now.
