### ISSUE TITLE
Week 46 Pull list disappeared 

### ISSUE THREAD

**Issue by ChapeLu** [evilhero/mylar#2123]
Hi,

Somehow my Week 46 list got corrupted, it's empty, tried to recreate it few times with no luck:

27-Nov-2018 23:17:15 - DEBUG   :: mylar.toggleVerbose.3628 : CP Server Thread-4 : If you can read this message, debug logging is now working
27-Nov-2018 23:17:21 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:17:21 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:17:22 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:17:22 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:18:56 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 48-2018
27-Nov-2018 23:18:56 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 48 year: 2018
27-Nov-2018 23:18:57 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 119 issues for the week of 48, 2018
27-Nov-2018 23:18:58 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 48
27-Nov-2018 23:19:02 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:19:02 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:19:04 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:19:04 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:19:22 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:19:22 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:19:22 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:19:22 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:19:44 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:19:44 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:19:45 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:19:45 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:19:49 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:19:49 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:19:49 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:19:49 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:20:03 - INFO    :: mylar.pullrecreate.1910 : CP Server Thread-4 : Deleted existing pull-list data for week 46, 2018. Now Recreating the Pull-list...
27-Nov-2018 23:20:03 - INFO    :: mylar.pullit.70 : CP Server Thread-4 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
27-Nov-2018 23:20:03 - INFO    :: mylar.pullit.74 : CP Server Thread-4 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 46, 2018
27-Nov-2018 23:20:04 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:20:04 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:20:04 - INFO    :: mylar.pullit.82 : CP Server Thread-4 : [PULL-LIST] Weekly Pull List successfully loaded with 0 issues.
27-Nov-2018 23:20:04 - INFO    :: mylar.LoadAlternateSearchNames.1313 : CP Server Thread-4 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Poe Dameron'}], 'ComicID': u'89380'}
27-Nov-2018 23:20:04 - INFO    :: mylar.LoadAlternateSearchNames.1313 : CP Server Thread-4 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Doctor Aphra'}], 'ComicID': u'96284'}
27-Nov-2018 23:20:05 - INFO    :: mylar.LoadAlternateSearchNames.1313 : CP Server Thread-4 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Immortal Hulk'}], 'ComicID': u'111425'}
27-Nov-2018 23:20:05 - DEBUG   :: mylar.new_pullcheck.944 : CP Server Thread-4 : [WALKSOFTLY] You are watching for: 165 comics
27-Nov-2018 23:20:05 - DEBUG   :: mylar.future_check.1419 : CP Server Thread-4 : cflist: [{'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'Amazing Spider-Man & Venom: Venom Inc. Alpha', 'IssueDate': u'2017-12-06', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'Amazing Spider-Man & Venom: Venom Inc. Omega', 'IssueDate': u'2018-01-17', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'Star Wars: DJ: Most Wanted', 'IssueDate': u'2018-01-31', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'The Hunt for Wolverine', 'IssueDate': u'2018-04-25', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'Hunt for Wolverine: The Adamantium Agenda', 'IssueDate': u'2018-05-09', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'Ant-Man and Wasp Living Legends', 'IssueDate': u'2018-06-06', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'Marvel Comics', 'ComicName': u'X-Men: Wakanda Forever', 'IssueDate': u'2018-07-25', 'IssueNumber': u'1'}]
27-Nov-2018 23:20:05 - INFO    :: mylar.future_check.1424 : CP Server Thread-4 : I will be looking to see if any information has been released for 7 series that are NEW series
27-Nov-2018 23:20:05 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for Amazing Spider-Man & Venom: Venom Inc. Alpha[#1] (2017)
27-Nov-2018 23:20:08 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 1 search results...
27-Nov-2018 23:20:08 - DEBUG   :: mylar.findComic.315 : CP Server Thread-4 : [RESULT][2017] ComicName:Amazing Spider-Man: Venom Inc. Alpha -- 2017 [Series years: [u'2017']]
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1441 : CP Server Thread-4 : Publisher of series to be added: Marvel Comics
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1443 : CP Server Thread-4 : Comparing Amazing Spider-Man: Venom Inc. Alpha - to - Amazing Spider-Man & Venom: Venom Inc. Alpha
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1469 : CP Server Thread-4 : Comparing modified names: amazingspidermanvenomincalpha - to - amazingspidermanvenomvenomincalpha
27-Nov-2018 23:20:08 - INFO    :: mylar.future_check.1481 : CP Server Thread-4 : Unable to determine a successful match at this time (this is still a WIP so it will eventually work). Not going to attempt auto-adding at this time.
27-Nov-2018 23:20:08 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc alpha', 'comicid': u'106662'}
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: -100%
27-Nov-2018 23:20:08 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 1 / 7
27-Nov-2018 23:20:08 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for Amazing Spider-Man & Venom: Venom Inc. Alpha[#1] (2017)
27-Nov-2018 23:20:08 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for Amazing Spider-Man & Venom: Venom Inc. Omega[#1] (2018)
27-Nov-2018 23:20:12 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 1 search results...
27-Nov-2018 23:20:12 - DEBUG   :: mylar.findComic.315 : CP Server Thread-4 : [RESULT][2018] ComicName:Amazing Spider-Man: Venom Inc. Omega -- 2018 [Series years: [u'2018']]
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1441 : CP Server Thread-4 : Publisher of series to be added: Marvel Comics
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1443 : CP Server Thread-4 : Comparing Amazing Spider-Man: Venom Inc. Omega - to - Amazing Spider-Man & Venom: Venom Inc. Omega
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1469 : CP Server Thread-4 : Comparing modified names: amazingspidermanvenomincomega - to - amazingspidermanvenomvenomincomega
27-Nov-2018 23:20:12 - INFO    :: mylar.future_check.1481 : CP Server Thread-4 : Unable to determine a successful match at this time (this is still a WIP so it will eventually work). Not going to attempt auto-adding at this time.
27-Nov-2018 23:20:12 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc alpha', 'comicid': u'106662'}
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: -100%
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 1 / 7
27-Nov-2018 23:20:12 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc omega', 'comicid': u'107934'}
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: -100%
27-Nov-2018 23:20:12 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 1 / 7
27-Nov-2018 23:20:12 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for Amazing Spider-Man & Venom: Venom Inc. Omega[#1] (2018)
27-Nov-2018 23:20:12 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for Star Wars: DJ: Most Wanted[#1] (2018)
27-Nov-2018 23:20:15 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 1 search results...
27-Nov-2018 23:20:15 - DEBUG   :: mylar.findComic.315 : CP Server Thread-4 : [RESULT][2018] ComicName:Star Wars: The Last Jedi - DJ - Most Wanted -- 2018 [Series years: [u'2018']]
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1441 : CP Server Thread-4 : Publisher of series to be added: Marvel Comics
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1443 : CP Server Thread-4 : Comparing Star Wars: The Last Jedi - DJ - Most Wanted - to - Star Wars: DJ: Most Wanted
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1469 : CP Server Thread-4 : Comparing modified names: starwarslastjedidjmostwanted - to - starwarsdjmostwanted
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1481 : CP Server Thread-4 : Unable to determine a successful match at this time (this is still a WIP so it will eventually work). Not going to attempt auto-adding at this time.
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc alpha', 'comicid': u'106662'}
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 5
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc omega', 'comicid': u'107934'}
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 5
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'star warslast jedi  dj  most wanted', 'comicid': u'108265'}
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:15 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 1 / 5
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for Star Wars: DJ: Most Wanted[#1] (2018)
27-Nov-2018 23:20:15 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for The Hunt for Wolverine[#1] (2018)
27-Nov-2018 23:20:18 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 0 search results...
27-Nov-2018 23:20:18 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for The Hunt for Wolverine[#1] (2018)
27-Nov-2018 23:20:18 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for Hunt for Wolverine: The Adamantium Agenda[#1] (2018)
27-Nov-2018 23:20:21 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 0 search results...
27-Nov-2018 23:20:21 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for Hunt for Wolverine: The Adamantium Agenda[#1] (2018)
27-Nov-2018 23:20:21 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for Ant-Man and Wasp Living Legends[#1] (2018)
27-Nov-2018 23:20:24 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 0 search results...
27-Nov-2018 23:20:24 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for Ant-Man and Wasp Living Legends[#1] (2018)
27-Nov-2018 23:20:24 - INFO    :: mylar.future_check.1435 : CP Server Thread-4 : looking for new data for X-Men: Wakanda Forever[#1] (2018)
27-Nov-2018 23:20:27 - DEBUG   :: mylar.findComic.142 : CP Server Thread-4 : there are 1 search results...
27-Nov-2018 23:20:27 - DEBUG   :: mylar.findComic.315 : CP Server Thread-4 : [RESULT][2018] ComicName:Wakanda Forever: X-Men -- 2018 [Series years: [u'2018']]
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1441 : CP Server Thread-4 : Publisher of series to be added: Marvel Comics
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1443 : CP Server Thread-4 : Comparing Wakanda Forever: X-Men - to - X-Men: Wakanda Forever
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1469 : CP Server Thread-4 : Comparing modified names: wakandaforeverxmen - to - xmenwakandaforever
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1481 : CP Server Thread-4 : Unable to determine a successful match at this time (this is still a WIP so it will eventually work). Not going to attempt auto-adding at this time.
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc alpha', 'comicid': u'106662'}
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 3
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'amazing spiderman venom inc omega', 'comicid': u'107934'}
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 3
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'star warslast jedi  dj  most wanted', 'comicid': u'108265'}
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: 0%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 3
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1484 : CP Server Thread-4 : {'name': u'wakanda forever xmen', 'comicid': u'112472'}
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1486 : CP Server Thread-4 : length match differential set for an allowance of 20%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1487 : CP Server Thread-4 : actual differential in length between result and series title: -100%
27-Nov-2018 23:20:27 - DEBUG   :: mylar.future_check.1523 : CP Server Thread-4 : word match score of : 0 / 3
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1550 : CP Server Thread-4 : No series information available as of yet for X-Men: Wakanda Forever[#1] (2018)
27-Nov-2018 23:20:27 - INFO    :: mylar.future_check.1553 : CP Server Thread-4 : Finished attempting to auto-add new series.
27-Nov-2018 23:20:31 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:20:31 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:20:31 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:20:31 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:20:50 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:20:50 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:20:50 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:20:50 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
27-Nov-2018 23:20:53 - INFO    :: mylar.pullist.1609 : CP Server Thread-4 : trying to repopulate to week: 46-2018
27-Nov-2018 23:20:53 - INFO    :: mylar.manualpull.1892 : CP Server Thread-4 : ALT_PULL: 2 PULLBYFILE: False week: 46 year: 2018
27-Nov-2018 23:20:54 - INFO    :: mylar.locg.70 : CP Server Thread-4 : [WEEKLY-PULL] There are 0 issues for the week of 46, 2018
27-Nov-2018 23:20:54 - INFO    :: mylar.locg.129 : CP Server Thread-4 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46

Then I decided to change alt_pull to 0 (had 2 before) and now can't access the page at all I get is:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 1610, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/app/mylar/mylar/webserve.py", line 1897, in manualpull
    weeklypull.pullit()
  File "/app/mylar/mylar/weeklypull.py", line 359, in pullit
    comicnm = issname[1]
IndexError: list index out of range

alt pull 1 is stuck on:

2018-11-27 23:52:56	INFO	[PULL-LIST] Populating & Loading pull-list data directly from webpage
2018-11-27 23:52:56	INFO	Weekly pull list present - checking if it's up-to-date..
2018-11-27 23:52:56	INFO	ALT_PULL: 1 PULLBYFILE: False week: 46 year: 2018
2018-11-27 23:52:56	INFO	trying to repopulate to week: 46-2018

and I get the same 500 Internal Server Error.

Going back to alt pull 2 fixes this but it still pulls 0 issues:

2018-11-27 23:49:32 | INFO | [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 46
-- | -- | --
2018-11-27 23:49:32 | INFO | [WEEKLY-PULL] There are 0 issues for the week of 46, 2018

I'm on Version: 3e12599502bc99343da8564762bd46277f5cdd8c (master), was on dev before but as I'm running this on Unraid in a Docker this is the easiest way to do it.

Any thoughts?
Kind Regards
ChapeL

**Comment by evilhero** [comment]
Backend SQL problem. Please hold while an operator attempts to solve the problem ```**queue cool jazz elevator music**```

**Comment by ChapeLu** [comment]
Wow this was quick, I was still editing my post. Will wait, Thanks :)

**Comment by ChapeLu** [comment]
Works now. Thank you.

**Comment by evilhero** [comment]
All back-end issues have been resolved and everything should be back to normal again. You will have to perform a ```Recreate Pullist``` option from within the Weekly tab in order to re-synchronise your pull-list properly. 

I'm just gonna sit here and listen to some more of that ```cool jazz elevator music```...
