### ISSUE TITLE
Download directory for qbittorrent doesn't work

### ISSUE THREAD

**Issue by foolsh** [evilhero/mylar#2124]
When setting the download directory for Qbittorrent options, Mylar lets it download to the default directory in Qbittorrent.

qBittorrent v4.1.4
Mylar git build 3e12599502bc99343da8564762bd46277f5cdd8c.
Python Version : 2.7.15rc1
Ubuntu 18.04

**Comment by evilhero** [comment]
Ok, it should be fixed now - although I haven't tested it since I don't run qB, it should now apply the download directory option to all newly added torrents. Let me know if this actually worked or not...
