### ISSUE TITLE
NZB_SEARCH result infinite loop

### ISSUE THREAD

**Issue by max6166** [evilhero/mylar#2135]
The log sequence below keeps repeating until my CPUs are maxed out and I have to kill Mylar's process. I believe the action that caused this was manually importing  a tagged file called "Archie - 1941 003 (2019).cbz". By the way, you are my EvilHero. Thanks for all your great work. 

`06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1292 : Thread-15 : blank brackets removed: archie giant series magazine (1954) - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492 (world of archie) (1980) (c2c) (jojo)
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1219 : Thread-15 : 0. Bracket Word: archie giant series magazine
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1225 : Thread-15 : Comic: archie giant series magazine
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1226 : Thread-15 : UseFuzzy is  : None
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1227 : Thread-15 : ComVersChk : 0
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1232 : Thread-15 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1219 : Thread-15 : 1. Bracket Word: 1954
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1236 : Thread-15 : year detected: 1954
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1238 : Thread-15 : year looking for: 2015
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1243 : Thread-15 : 2015 - not right - years do not match
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1263 : Thread-15 : 2015 - not the right year.
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1219 : Thread-15 : 2. Bracket Word:  - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492
06-Dec-2018 17:26:41 - DEBUG   :: mylar.NZB_SEARCH.1283 : Thread-15 : Publisher detected within title :  - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492
`

**Comment by evilhero** [comment]
That's the search actually firing off - I can see why it's erroring altho I dunno why it's not spitting out the error itself.  Is that the entirety of the debug log for the search loop? 

What providers do you have enabled (or is hitting in this particular case)?

**Comment by max6166** [comment]
Yes, it just loops that chunk of the log. The provider is NZBGeek.

**Comment by evilhero** [comment]
Weird, you're missing some logging lines from that log post for some reason - so I'm wondering if you're up-to-date on whatever branch you're currently running ?

What series was being searched for? The log context doesn't provide that in this instance, so I'm trying to piece things together with that short log paste, and atm, I'm not doing very well with it

**Comment by max6166** [comment]
I have been trying to get you more info on this issue, but I haven't been able to. If you could decipher the log for me, I might be able to find the cause. 

I am on the latest branch. I just start Mylar, leave it alone for a while, and eventually this "archie giant series magazine" loop starts happening. I am not monitoring "archie giant series magazine", though I do monitor a few Archie series. 

Here is a more recent example of the same looping portion of the debug log:
---
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1261 : Thread-13 : blank brackets removed: archie giant series magazine (1954) - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492 (world of archie) (1980) (c2c) (jojo)
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1188 : Thread-13 : 0. Bracket Word: archie giant series magazine
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1194 : Thread-13 : Comic: archie giant series magazine
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1195 : Thread-13 : UseFuzzy is  : None
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1196 : Thread-13 : ComVersChk : 0
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1201 : Thread-13 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1188 : Thread-13 : 1. Bracket Word: 1954
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1205 : Thread-13 : year detected: 1954
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1207 : Thread-13 : year looking for: 2015
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1212 : Thread-13 : 2015 - not right - years do not match
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1232 : Thread-13 : 2015 - not the right year.
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1188 : Thread-13 : 2. Bracket Word:  - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1252 : Thread-13 : Publisher detected within title :  - issues 1-35, 136-251, 452-632 fills requested 122 of 132 archie giant series magazine 492
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1253 : Thread-13 : cnt is : 2 --- Publisher is: Archie Comics
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1256 : Thread-13 : removing publisher from title
28-Dec-2018 16:39:45 - DEBUG   :: mylar.NZB_SEARCH.1258 : Thread-13 : pubremoved : archie giant series magazine (1954) - issues 1-35, 136-251, 452-632  fills requested   122 of 132  archie giant series magazine 492 (world of archie) (1980) (c2c) (jojo)

**Comment by max6166** [comment]
Problem vanished after switching to dev branch.
