### ISSUE TITLE
Windows 10 / Python 2.7.15 error on search - parser library missing?

### ISSUE THREAD

**Issue by FrankEBailey** [evilhero/mylar#2145]
Uncaught exception: Traceback (most recent call last):
File "q:\Mylar\mylar\logger.py", line 336, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "q:\Mylar\mylar\helpers.py", line 3007, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "q:\Mylar\mylar\search.py", line 2118, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)
File "q:\Mylar\mylar\search.py", line 336, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)
File "q:\Mylar\mylar\search.py", line 619, in NZB_SEARCH
bb = ww.wwt_connect()
File "q:\Mylar\mylar\wwt.py", line 53, in wwt_connect
soup = BeautifulSoup(r.content, "html5lib")
File "q:\Mylar\lib\bs4\__init__.py", line 165, in __init__
% ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by evilhero** [comment]
You need to install the html5lib parser library as it can't be included with mylar. 

This is a requirement if you use the public torrents option only. See #1902 for more details.

**Comment by FrankEBailey** [comment]
Thanks!
