### ISSUE TITLE
Add Comic failing

### ISSUE THREAD

**Issue by Tomservov2** [evilhero/mylar#2146]
When I attempt to add a comic, it shows added on the weekly list, then when I click it is stuck in loading mode.

When I look at manage comics it shows the following
![image](https://user-images.githubusercontent.com/25776847/50131171-91e23c80-0246-11e9-9f18-2869efbd7518.png)

and says this in the logs

This is what was in the logs

2018-12-17 21:44:44	ERROR	Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\importer.py", line 215, in addComictoDB
comlocation = dothedew.folder_create()
File "c:\Mylar\mylar\filers.py", line 130, in folder_create
comlocation = re.sub('/', '\\', comlocation)
File "c:\Python27\lib\re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "c:\Python27\lib\re.py", line 286, in _subx
template = _compile_repl(template, pattern)
File "c:\Python27\lib\re.py", line 273, in _compile_repl
raise error, v # invalid expression
error: bogus escape (end of line)
2018-12-17 21:44:44	DEBUG	new folder format: $Publisher/$Series
2018-12-17 21:44:44	DEBUG	No version # found for series, removing from folder format
2018-12-17 21:44:44	INFO	Previous version detected as None - seeing if update required
2018-12-17 21:44:44	INFO	Sucessfully retrieved details for Goddess Mode
2018-12-17 21:44:44	INFO	Now adding/updating: Goddess Mode

Tried a re-install, backed up config/cache/mylar.db

Then tried again, not sure if I got the same error or not, since i got 100 pages of this in the logs.

2018-12-17 22:15:12 | INFO | i: 1
-- | -- | --
2018-12-17 22:15:12 | INFO | i: 1
2018-12-17 22:15:12 | INFO | i: 1
2018-12-17 22:15:12 | INFO | i: 1
2018-12-17 22:15:12 | INFO | i: 1
2018-12-17 22:15:12 | INFO | i: 1

but the same thing is happening after re install.

Does "git clone https://github.com/evilhero/mylar -b development c:\Mylar" still pull the right thing?  Cuz it worked seemingly

Anyways, thanks in advance for looking at it

**Comment by evilhero** [comment]
You're on windows, not linux - try and reverse the slash in the folder format from / to \ as the system thinks that that is an actual code break not a directory separation. I'll try and fix the adjustments so it won't throw the error and correct it accordingly.

And yep, that's the correct way to clone the development branch. 

Odds are you have a blank space in the filter box on the logging page and that's why it's throwing back the multiple lines of identical logging. If that doesn't do it, you can also just wipe out all the log files from the logs directory within the Mylar root folder and Mylar will recreate as needed, which should also clean things up if necessary (maybe make sure Mylar isn't running when you do this as it might complain about not being able to find a file to write to otherwise)

**Comment by Tomservov2** [comment]
May have solved my own issue

Tried re install but from git shell and using "git clone https://github.com/evilhero/mylar.git c:/mylar" instead

seems to be working for now

The command worked with the backward \ , it seemed to do the pull to the right directory.  But this other method seems to have worked

Hopefully I'm good

**Comment by hitnrun30** [comment]
I still get this error with even the latest update.  it will not add any new comics.

Line 12 : 16-Jan-2019 12:30:28 - INFO :: mylar.addComictoDB.84 : Thread-30 : aliases currently: None 
Line 13 : 16-Jan-2019 12:30:28 - INFO :: mylar.dbUpdate.117 : Thread-30 : [20/20] Refreshing :Comic ID: 116514 (None) [116514] 
Line 14 : 16-Jan-2019 12:30:28 - ERROR :: mylar.dbUpdate.106 : Thread-30 : Comic ID: 116514 failed during a previous add /refresh as it has no Last Update timestamp. Forcing refresh now. 
Line 15 : 16-Jan-2019 12:30:17 - INFO :: mylar.run.2571 : Thread-16 : [FOLDER-CHECK] Finished checking for newly snatched downloads 
Line 16 : 16-Jan-2019 12:30:17 - WARNING :: mylar.Process.385 : Thread-16 : There were no files located - check the debugging logs if you think this is in error. 
Line 17 : 16-Jan-2019 12:30:17 - INFO :: mylar.traverse_directories.1320 : Thread-16 : there are 0 files. 
Line 18 : 16-Jan-2019 12:30:17 - INFO :: mylar.run.2568 : Thread-16 : [FOLDER-CHECK] Checking folder C:\Temp\Download for newly snatched downloads 
Line 19 : 16-Jan-2019 12:29:48 - WARNING :: mylar.havetotals.1387 : CP Server Thread-9 : Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate. 
Line 20 : 16-Jan-2019 12:29:17 - INFO :: mylar.run.2571 : Thread-29 : [FOLDER-CHECK] Finished checking for newly snatched downloads 
Line 21 : 16-Jan-2019 12:29:17 - WARNING :: mylar.Process.385 : Thread-29 : There were no files located - check the debugging logs if you think this is in error. 
Line 22 : 16-Jan-2019 12:29:17 - INFO :: mylar.traverse_directories.1320 : Thread-29 : there are 0 files. 
Line 23 : 16-Jan-2019 12:29:17 - INFO :: mylar.run.2568 : Thread-29 : [FOLDER-CHECK] Checking folder C:\Temp\Download for newly snatched downloads 
Line 24 : 16-Jan-2019 12:28:33 - WARNING :: mylar.havetotals.1387 : CP Server Thread-7 : Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate. 
Line 25 : ] 
Line 26 : 'git <command> [<revision>...] -- [<file>...]' 
Line 27 : Use '--' to separate paths from revisions, like this: 
Line 28 : 16-Jan-2019 12:28:33 - ERROR :: mylar.runGit.59 : CP Server Thread-7 : Git returned bad info. Are you sure this is a git installation? [fatal: ambiguous argument '%cr': unknown revision or path not in the working tree. 
Line 29 : 16-Jan-2019 12:28:33 - ERROR :: mylar.runGit.58 : CP Server Thread-7 : Error: None 
Line 30 : 16-Jan-2019 12:28:23 - WARNING :: mylar.havetotals.1387 : CP Server Thread-6 : Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate. 
Line 31 : 16-Jan-2019 12:28:17 - INFO :: mylar.run.2571 : Thread-20 : [FOLDER-CHECK] Finished checking for newly snatched downloads 
Line 32 : 16-Jan-2019 12:28:17 - WARNING :: mylar.Process.385 : Thread-20 : There were no files located - check the debugging logs if you think this is in error. 
Line 33 : 16-Jan-2019 12:28:17 - INFO :: mylar.traverse_directories.1320 : Thread-20 : there are 0 files. 
Line 34 : 16-Jan-2019 12:28:17 - INFO :: mylar.run.2568 : Thread-20 : [FOLDER-CHECK] Checking folder C:\Temp\Download for newly snatched downloads 
Line 35 : 16-Jan-2019 12:28:15 - WARNING :: mylar.havetotals.1387 : CP Server Thread-4 : Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate. 
Line 36 : 
Line 37 : error: bogus escape (end of line) 
Line 38 : raise error, v # invalid expression 
Line 39 : File "C:\Python27\lib\re.py", line 273, in _compile_repl 
Line 40 : template = _compile_repl(template, pattern) 
Line 41 : File "C:\Python27\lib\re.py", line 286, in _subx 
Line 42 : return _compile(pattern, flags).sub(repl, string, count) 
Line 43 : File "C:\Python27\lib\re.py", line 155, in sub 
Line 44 : comlocation = re.sub('/', '\\', comlocation) 
Line 45 : File "C:\HTPC\Mylar\mylar\filers.py", line 130, in folder_create 
Line 46 : comlocation = dothedew.folder_create() 
Line 47 : File "C:\HTPC\Mylar\mylar\importer.py", line 218, in addComictoDB 
Line 48 : self.__target(*self.__args, **self.__kwargs) 
Line 49 : File "C:\Python27\lib\threading.py", line 754, in run 
Line 50 : old_run(*args, **kwargs) 
Line 51 : File "C:\HTPC\Mylar\mylar\logger.py", line 337, in new_run 
Line 52 : 16-Jan-2019 12:28:08 - ERROR :: mylar.excepthook.315 : Thread-32 : Uncaught exception: Traceback (most recent call last): 
Line 53 : 16-Jan-2019 12:28:08 - INFO :: mylar.addComictoDB.185 : Thread-32 : Previous version detected as None - seeing if update required 
Line 54 : 16-Jan-2019 12:28:08 - INFO :: mylar.addComictoDB.179 : Thread-32 : Sucessfully retrieved details for Star Wars: Age of Republic Special 
Line 55 : 16-Jan-2019 12:28:08 - INFO :: mylar.addComictoDB.126 : Thread-32 : Now adding/updating: Star Wars: Age of Republic Special 
Line 56 : 16-Jan-2019 12:28:05 - INFO :: mylar.addbyid.434 : CP Server Thread-2 : Attempting to add directly by ComicVineID: 116514

**Comment by evilhero** [comment]
@hitnrun30 can you enable debug logging and perform the add again? It might have to do with your folder format string, but without seeing the debug log I can't tell what's happening...

Also can you confirm you're up-to-date on your branch? It's returning a git error, which shouldn't stop the updater from running, but just to make sure.

**Comment by hitnrun30** [comment]
Yes im up to date, i just got the last version before the log below was made


2019-01-16 12:45:50 | WARNING | Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate.
-- | -- | --
2019-01-16 12:45:44 | WARNING | Comic ID: 116514 has not finished loading. Nulling some values so things display properly until they can populate.
2019-01-16 12:45:42 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\HTPC\Mylar\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "C:\HTPC\Mylar\mylar\importer.py", line 218, in addComictoDBcomlocation = dothedew.folder_create()File "C:\HTPC\Mylar\mylar\filers.py", line 130, in folder_createcomlocation = re.sub('/', '\\', comlocation)File "C:\Python27\lib\re.py", line 155, in subreturn _compile(pattern, flags).sub(repl, string, count)File "C:\Python27\lib\re.py", line 286, in _subxtemplate = _compile_repl(template, pattern)File "C:\Python27\lib\re.py", line 273, in _compile_replraise error, v # invalid expressionerror: bogus escape (end of line)
2019-01-16 12:45:42 | DEBUG | new folder format: $Publisher/$Series
2019-01-16 12:45:42 | DEBUG | No version # found for series, removing from folder format
2019-01-16 12:45:42 | INFO | Previous version detected as None - seeing if update required
2019-01-16 12:45:42 | INFO | Sucessfully retrieved details for Star Wars: Age of Republic Special
2019-01-16 12:45:42 | INFO | Now adding/updating: Star Wars: Age of Republic Special

**Comment by evilhero** [comment]
Your Folder Format slash is going the wrong way for your OS (since you're on Windows).

Change your Folder Format to ```$Publisher\$Series```, save the configuration and you'll be good to go from that point.

**Comment by hitnrun30** [comment]
That did it, I always had it the other way, was there a change at some point that made this mess up?

**Comment by evilhero** [comment]
No it wasn't a mess up, but actually a correction. 

It came up that alot of users (running Windows for the most part) had the slash going the literal way as was shown in the example in the configuration. Unfortunately, on Windows systems, having the slash the opposite way means that it's a escape sequence that follows so if the next character after it was something that was system recognisable (ie. ```/n```) it would completely mess up adds, post-processes, file checks, etc.

So with the patch, Mylar attempts to fix things by replacing the slashes accordingly - only when it encounters an actual escape sequence (as what occurred with that series) it throws the traceback as an indicator. We'll have to try to figure out a better error message if possible that just throwing the error...

**Comment by hitnrun30** [comment]
Is there any other place to worry about it?

**Comment by evilhero** [comment]
No just the Folder Format string as that's the only place where the slash could be entered and it affects your directory structure as it is used when performing file functions.

The best thing to do after changing the format string is to perform a refresh of all your series (Mylar should be doing it for every series at a rate of roughly one series every 5 minutes every week - but it's abit glitchy with how it enforces the only once/week thing). This will ensure that all your series have the correct slash in the path and you won't get these types of errors going forward.

If you go to the ```Manage tab --> Manage Comics --> select all the series --> Refresh Series from the dropdown```

To keep it simpler and easier to manage, maybe do one page/time if you set the page to display 25 and sort it by the Updated column (oldest to newest).
