### ISSUE TITLE
Unable to find files on filescan for series "Tarot of the black Rose"

### ISSUE THREAD

**Issue by miracle152005** [evilhero/mylar#2147]
Hi,

I am currently unable to find files on the file system for the series "Tarot of the black Rose".
I currently think it has something to do with the "of" in the title and filenames.
Here is an excerpt of the logfile:

018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose', 'V2000', '110']
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:583 : volume label detected as : Volume 2000 @ position: 6
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:717 : datecheck: []
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:761 : highest_series_position: 8
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 7, 'validcountchk': False, 'number': '110', 'mod_position': 36}]
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:839 : issue_position: 7
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:856 : issue verified as : 110
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:872 : Volume detected as : v2000
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:980 : sf_highest_series_pos: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose']
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:1012 : series title possibly: Tarot Witch of the Black Rose
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:listFiles:143 : [FILENAME]: Tarot Witch of the Black Rose V2000 111.cbz
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:341 : checking now: the
21-Dez-2018 19:26:24 - ERROR   :: Thread-68 : filechecker.py:parseit:349 : Exception: could not convert string to float: the
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose', 'V2000', '111']
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:583 : volume label detected as : Volume 2000 @ position: 6
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:717 : datecheck: []
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:761 : highest_series_position: 8
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 7, 'validcountchk': False, 'number': '111', 'mod_position': 36}]
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:839 : issue_position: 7
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:856 : issue verified as : 111
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:872 : Volume detected as : v2000
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:980 : sf_highest_series_pos: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose']
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:1012 : series title possibly: Tarot Witch of the Black Rose
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:listFiles:143 : [FILENAME]: Tarot Witch of the Black Rose V2000 112.cbz
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:341 : checking now: the
21-Dez-2018 19:26:24 - ERROR   :: Thread-68 : filechecker.py:parseit:349 : Exception: could not convert string to float: the
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose', 'V2000', '112']
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:583 : volume label detected as : Volume 2000 @ position: 6
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:717 : datecheck: []
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:761 : highest_series_position: 8
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 7, 'validcountchk': False, 'number': '112', 'mod_position': 36}]
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:839 : issue_position: 7
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:856 : issue verified as : 112
21-Dez-2018 19:26:24 - DEBUG   :: Thread-68 : filechecker.py:parseit:872 : Volume detected as : v2000
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:980 : sf_highest_series_pos: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose']
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:1012 : series title possibly: Tarot Witch of the Black Rose
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:listFiles:143 : [FILENAME]: Tarot Witch of the Black Rose V2000 113.cbz
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:341 : checking now: the
21-Dez-2018 19:26:25 - ERROR   :: Thread-68 : filechecker.py:parseit:349 : Exception: could not convert string to float: the
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose', 'V2000', '113']
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:583 : volume label detected as : Volume 2000 @ position: 6
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:717 : datecheck: []
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:761 : highest_series_position: 8
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 7, 'validcountchk': False, 'number': '113', 'mod_position': 36}]
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:839 : issue_position: 7
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:856 : issue verified as : 113
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:872 : Volume detected as : v2000
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:980 : sf_highest_series_pos: ['Tarot', 'Witch', 'of', 'the', 'Black', 'Rose']
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : filechecker.py:parseit:1012 : series title possibly: Tarot Witch of the Black Rose
21-Dez-2018 19:26:25 - DEBUG   :: Thread-68 : updater.py:forceRescan:1024 : No issues with identical issue numbering were detected for this series

Could you please take a look?

Thanks 
Best regards
miracle152005

**Comment by barbequesauce** [comment]
Fixes in Dev seem to fix this... thanks evilhero!

**Comment by miracle152005** [comment]
Updated to the latest development version.
Error is still there when I use "Recheck Files" and no files are added to the issues.
Still getting this exception:
 filechecker.py:parseit:349 : Exception: could not convert string to float: the

**Comment by miracle152005** [comment]
Thanks that worked.
