### ISSUE TITLE
Settings 500 After Git Pull

### ISSUE THREAD

**Issue by teamcoltra** [evilhero/mylar#2153]
I have:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/teamcoltra/.piracy/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/teamcoltra/.piracy/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/teamcoltra/.piracy/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/teamcoltra/.piracy/mylar/mylar/webserve.py", line 4621, in config
    "authentication": int(mylar.CONFIG.AUTHENTICATION),
TypeError: int() argument must be a string or a number, not 'NoneType'
Powered by CherryPy 3.6.0
```

Which I'm sure just means I need to have a new config variable that didn't exist before, but I'm not sure what I need to change to fix it. 

This error only effects the settings page.

**Comment by evilhero** [comment]
Do you have authentication enabled within Mylar ?

By default, when Mylar loads up a configuration that does not have the variable in the .ini, it sets it to a value of 0 (so 0 = no authentication. 1 = forms popup, 2 =login page). 

Are you running a current commit of either master / development of Mylar? It sounds like you might be running an out-of-date version possibly.

**Comment by teamcoltra** [comment]
I got this from doing a git pull on Development... I was on an old version for a long time. My authentication is currently set to 0. I do have HTTP authentication on though.

From that section:

```
[Interface]
http_password = ********
https_chain = None
authentication = 0
http_port = 8090
login_timeout = 43800
http_root = /
https_force_on = False
https_cert = None
http_host = 0.0.0.0
enable_https = False
https_key = None
host_return = None
http_username = teamcoltra
alphaindex = True
```

**Comment by evilhero** [comment]
If you have authentication set to 0 (which is None), it doesn't matter what you have set for username/password as it won't do be used. Sounds like you're stuck in some weird config setting loop here or the like.

Try changing the authentication value to either 1 or 2 (with Mylar not running). Then start it up and enter in your username/password when prompted. Once in Mylar, go to the configuration, and on the Web Interface tab check to see what the value of the authentication mode is set to. Change accordingly if needed, save the config and then restart Mylar so the changes can take effect and hopefully it'll all be straightened out.

**Comment by teamcoltra** [comment]
This issue has resolved itself after a couple of computer resets, I'm not sure what the problem was... but it seems to be fixed now. I did have the 0 setting before and used HTTP login but :\ who knows.
