### ISSUE TITLE
500 on /pulllist

### ISSUE THREAD

**Issue by francispeixoto** [evilhero/mylar#2154]
I'm getting a 500 in /pulllist. I just now noticed, but I imagine it affects /upcoming since it seems mylar has slipped the latest NCBD. 

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last): File "lib/cherrypy/_cprequest.py", line 670, in respond response.body = self.handler() File "lib/cherrypy/lib/encoding.py", line 217, in __call__ self.body = self.oldhandler(*args, **kwargs) File "lib/cherrypy/_cpdispatch.py", line 61, in __call__ return self.callable(*self.args, **self.kwargs) File "/opt/mylar/mylar/webserve.py", line 1610, in pullist repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year']) File "/opt/mylar/mylar/webserve.py", line 1897, in manualpull weeklypull.pullit() File "/opt/mylar/mylar/weeklypull.py", line 359, in pullit comicnm = issname[1] IndexError: list index out of range
```

**Comment by barbequesauce** [comment]
"slipped the latest NCBD"? what does that mean?

Can you post the debug log from around that error? need to see what it was doing in the few seconds/minutes before it threw that traceback...

**Comment by francispeixoto** [comment]
@barbequesauce sorry. I meant skipped. Autocorrect is tricky if you're not paying attention. 

Here's the debug logs from calling that page:

```
TimestampLevelMessage2018-12-31 10:52:07INFOPreparing to update to the new listing.2018-12-31 10:52:07DEBUGtoday: 201811282018-12-31 10:52:07DEBUGshipdate: 201901022018-12-31 10:52:07DEBUGno substitues.csv file located - not performing substitutions on weekly pull list2018-12-31 10:52:05INFO[PULL-LIST] Populating & Loading pull-list data from file2018-12-31 10:52:05INFOWeekly pull list present - checking if it's up-to-date..2018-12-31 10:52:05INFOALT_PULL: 0 PULLBYFILE: True week: 52 year: 20182018-12-31 10:52:05INFOtrying to repopulate to week: 52-2018
```

**Comment by evilhero** [comment]
Your alt_pull is set to 0 in the config.ini. Shutdown mylar, edit the config.ini and change the alt_pull value to 2. Save it and start it and you should be good.

Also there is no week 52-2018 (it will be blank). You need to go to the following week (use the right arrow key in the upper part of the page) for the current week. This has been fixed in development, but a week 52 will still show up in the  master branch incorrectly.

It won't affect anything adversely as week 52/2018 = week 0/2019 with respect to the actual dates used.

**Comment by francispeixoto** [comment]
@evilhero I'm back up, thanks! Why was this setting like this in the first place? I don't remember ever touching it.

**Comment by evilhero** [comment]
Well normally it defaults to an ```alt_pull = 2```, but if for some reason your Mylar client cannot reach the API backend site, then it attempts to drop down to an old method to be used (```alt_pull = 0```). This is on purpose as the original intent was that if the backend site went offline, experienced SQL problems, or anything similiar it would still be able to populate the list using another method. Unfortunately, it looks like they've changed the layout/structure of the site, so when the parser tries to poll against it it's failling and resulting in an error. 

In these cases, where it's changed on it's own from 2 to 0, usually what has happened is that a config change was made and the config was saved.  When it's saved, the alt_pull is set to 0 it and it will save that value and replace the original value of 2. Thereby causing grief thereafter as it will no longer be using the newer method to retrieve the pullist.

We're aware of the issue, but unfortunately with the holidays and some other issues creeping up it's been a bit hard to track down and fix properly.
