### ISSUE TITLE
[Feature Request] Auto-Update

### ISSUE THREAD

**Issue by rg9400** [evilhero/mylar#2155]
It would be nice if there can be a toggle for auto updates. It can check based on a certain time interval, and if an update is found, it can install it automatically.

**Comment by barbequesauce** [comment]
today's dev commits enabled this... you'll find "auto_update = False" in your config.ini. Shut Mylar down, change it to True, and then restart/update; the next update after that should be frictionless.

Note there is no GUI switch for this as it's a power-user feature...

**Comment by evilhero** [comment]
Just an FYI that the auto-update feature will only work with git installations.

**Comment by rg9400** [comment]
Really appreciate it guys! I enabled it and will wait for the next update to test if it worked

**Comment by rg9400** [comment]
When does Mylar check for the latest version? It's been 22 hours since the latest commit, but it hasn't auto-updated yet. Last time, simply clicking "Check for Version" did go through a frictionless update in the sense that I did not have to manually click "Restart Mylar" or whatever the previous option used to be. But I was hoping that it would check and update on its own on a set schedule.

I am on Windows 10 using a native git installation by the way.

**Comment by barbequesauce** [comment]
Default check is very six hours.

That said, there is no visual indication that an auto update occurred other than the hash at the bottom of the screen changing when you change pages afterward.

There is also the possibility that you have other files in the Mylar directory, and git is confused about them - so it can’t update.

What does “git status” tell you?

**Comment by rg9400** [comment]
Version is currently `Version: cfb42fb6e51fdaa58c1bf9664a4610e5ccab6dcc (development)` which I think is a commit behind

git status gives this
```
c:\mylar>git status
On branch development
Your branch is up to date with 'origin/development'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        config.ini.backup

nothing added to commit but untracked files present (use "git add" to track)
```

Do I need to delete that file for it to work properly?

**Comment by barbequesauce** [comment]
No, you’re good... “up to date” is what we are looking for...

**Comment by rg9400** [comment]
hmm, you're correct. But when I used the "Check Version" button in Mylar, it did end up updating.

Now the footer reads `Version: ee3f1cfa0cf3d14b3ffc6dc27e22f66a40dfe595 (development)`.

**Comment by evilhero** [comment]
Git status will only show the local repo/working directory. It doesn't show how many commits behind you are etc. That's something that mylar (and other apps) have to check manually.

So you're up to date with your original clone/last update, but you weren't up to date with the latest changes.

Do you have the auto_update variable set to True in the [General] section of your config.ini?

**Comment by rg9400** [comment]
Yes, and "Check Version" does behave differently after enabling it. It goes straight to the update and restart...previously, it used to show me how many commits I was behind and if I wanted to restart to update.

**Comment by evilhero** [comment]
Yeah we'll have to fix the Check Version option so it can perform the popup as opposed to assuming everything is an unattended upgrade.

**Comment by rg9400** [comment]
I tried removing that file and waited for the last update, but no dice. Could it be related to the fact that I am running Mylar on Windows (even though it is a git install)?
