### ISSUE TITLE
32p download package files

### ISSUE THREAD

**Issue by a-nunes** [evilhero/mylar#2157]
I've been trying to use Mylar with 32p, when it's the single file, like "The Flash #3" Mylar works beatifully. But, when the file is a package, it just drop it out and doesn't download the torrent file.

E.g.: The Flash v5 #1-60, it finds the package file, compare 1-60 with the title of the issue, when it doesn't match, it just follow up and doesn't download nothing.

There's a way make Mylar download all package?

**Comment by evilhero** [comment]
You have to Enable Pack Downloads under the Edit Settings tab on the series detail page for the specific series you want. This option will only be available if you have 32P enabled as a provider using Authentication Mode (it will not work with Legacy).

Keep in mind as well, that the volumes have to match or else Mylar will not consider it a match (aside from the v0, v1 stuff of course). And there are several series that have different volume numbering than what Mylar/CV has.

**Comment by a-nunes** [comment]
Thank you very much, it worked perfectly.
