### ISSUE TITLE
Unable to find files during scan for "The Books of Faerie (1997)" 

### ISSUE THREAD

**Issue by miracle152005** [evilhero/mylar#2159]
Hi,

I am unable to find files for the series "The Books of Fearie (1997)" [CVID:5942]
The series should be correctly identified as "Print"

The logfile looks like this:
04-Jan-2019 06:00:20 - INFO    :: Thread-70 : updater.py:forceRescan:949 : [FILE-RESCAN] Now checking files for The Books of Faerie (1997) in E:\Comics\Vertigo\The Books of Faerie (1997)
04-Jan-2019 06:00:20 - INFO    :: Thread-70 : filechecker.py:traverse_directories:1320 : there are 3 files.
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie V1997 001.cbr
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 06:00:20 - ERROR   :: Thread-70 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', 'V1997', '001']
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:583 : volume label detected as : Volume 1997 @ position: 4
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:717 : datecheck: []
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:761 : highest_series_position: 6
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 5, 'validcountchk': False, 'number': '001', 'mod_position': 26}]
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:839 : issue_position: 5
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:856 : issue verified as : 001
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:872 : Volume detected as : v1997
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 06:00:20 - DEBUG   :: Thread-70 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie V1997 002.cbr
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 06:00:21 - ERROR   :: Thread-70 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', 'V1997', '002']
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:583 : volume label detected as : Volume 1997 @ position: 4
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:717 : datecheck: []
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:761 : highest_series_position: 6
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 5, 'validcountchk': False, 'number': '002', 'mod_position': 26}]
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:839 : issue_position: 5
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:856 : issue verified as : 002
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:872 : Volume detected as : v1997
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie V1997 003.cbr
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 06:00:21 - ERROR   :: Thread-70 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', 'V1997', '003']
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:583 : volume label detected as : Volume 1997 @ position: 4
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:717 : datecheck: []
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:759 : No year present within title - ignoring as a variable.
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:761 : highest_series_position: 6
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 5, 'validcountchk': False, 'number': '003', 'mod_position': 26}]
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:839 : issue_position: 5
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:856 : issue verified as : 003
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:872 : Volume detected as : v1997
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : updater.py:forceRescan:1024 : No issues with identical issue numbering were detected for this series
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : updater.py:forceRescan:1088 : [FILE-RESCAN] temploc: 1997
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : updater.py:forceRescan:1088 : [FILE-RESCAN] temploc: 1997
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : updater.py:forceRescan:1088 : [FILE-RESCAN] temploc: 1997
04-Jan-2019 06:00:21 - INFO    :: Thread-70 : updater.py:forceRescan:1480 : [FILE-RESCAN] Total files located: 0
04-Jan-2019 06:00:21 - DEBUG   :: Thread-70 : updater.py:forceRescan:1587 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: The Books of Faerie
04-Jan-2019 06:00:21 - INFO    :: Thread-70 : updater.py:forceRescan:1589 : [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 3 ]

Could you please take a look.

Thanks.

Best regards
miracle152005

**Comment by barbequesauce** [comment]
Looks like referring to the year as a volume is messing it up, as that won’t match to the CV data. Try renaming the file to “The Books of Faerie 001 (2017).cbr” and see how it processes...

**Comment by miracle152005** [comment]
Still happening.
Here is an updated log:

04-Jan-2019 12:44:59 - DEBUG   :: CP Server Thread-5 : webserve.py:toggleVerbose:3719 : If you can read this message, debug logging is now working
04-Jan-2019 12:45:06 - INFO    :: Thread-34 : updater.py:forceRescan:949 : [FILE-RESCAN] Now checking files for The Books of Faerie (1997) in E:\Comics\Vertigo\The Books of Faerie (1997)
04-Jan-2019 12:45:06 - INFO    :: Thread-34 : filechecker.py:traverse_directories:1320 : there are 3 files.
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie 001 (1997).cbr
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 12:45:06 - ERROR   :: Thread-34 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', '001', '(1997)']
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:411 : checking date : 1997
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:414 : date: 1997
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:717 : datecheck: [{'date': '1997', 'position': 5, 'mod_position': 24}]
04-Jan-2019 12:45:06 - DEBUG   :: Thread-34 : filechecker.py:parseit:723 : sctd: 2019
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:732 : year verified as : 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:738 : year verified as: 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:761 : highest_series_position: 5
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '001', 'mod_position': 20}]
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:839 : issue_position: 4
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:856 : issue verified as : 001
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie 002 (1997).cbr
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 12:45:07 - ERROR   :: Thread-34 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', '002', '(1997)']
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:411 : checking date : 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:414 : date: 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:717 : datecheck: [{'date': '1997', 'position': 5, 'mod_position': 24}]
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:723 : sctd: 2019
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:732 : year verified as : 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:738 : year verified as: 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:761 : highest_series_position: 5
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '002', 'mod_position': 20}]
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:839 : issue_position: 4
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:856 : issue verified as : 002
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:listFiles:143 : [FILENAME]: The Books of Faerie 003 (1997).cbr
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:341 : checking now: Faerie
04-Jan-2019 12:45:07 - ERROR   :: Thread-34 : filechecker.py:parseit:349 : Exception: could not convert string to float: Faerie
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:376 : NEWLY SPLIT REORGD: ['The', 'Books', 'of', 'Faerie', '003', '(1997)']
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:411 : checking date : 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:414 : date: 1997
04-Jan-2019 12:45:07 - DEBUG   :: Thread-34 : filechecker.py:parseit:717 : datecheck: [{'date': '1997', 'position': 5, 'mod_position': 24}]
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:723 : sctd: 2019
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:732 : year verified as : 1997
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:738 : year verified as: 1997
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:761 : highest_series_position: 5
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:767 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '003', 'mod_position': 20}]
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:839 : issue_position: 4
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:856 : issue verified as : 003
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie

**Comment by barbequesauce** [comment]
That all looks good / what’s the next part of the log?

**Comment by miracle152005** [comment]
There is no next part.
At least not an the same thread.
The next log entries are for scheduled dbUpdates:

04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:980 : sf_highest_series_pos: ['The', 'Books', 'of', 'Faerie']
04-Jan-2019 12:45:08 - DEBUG   :: Thread-34 : filechecker.py:parseit:1012 : series title possibly: The Books of Faerie
04-Jan-2019 12:49:40 - INFO    :: Thread-23 : updater.py:dbUpdate:37 : Updating only Continuing Series (option enabled) - this might cause problems with the pull-list matching for rebooted series
04-Jan-2019 12:49:40 - DEBUG   :: Thread-23 : updater.py:dbUpdate:85 : Refresh sequence set to fire every 5 minutes for 7 day(s)
04-Jan-2019 12:49:40 - DEBUG   :: Thread-23 : helpers.py:job_management:3480 : ReScheduled job: DB Updater to 2019-01-04 11:54:40
04-Jan-2019 12:49:40 - INFO    :: Thread-23 : updater.py:dbUpdate:353 : Update complete

My question would be if even the errors in the log are ok?

**Comment by barbequesauce** [comment]
If you’re asking about the “Exception: could not convert string to float” lines, yes they’re ok - at some point they will be changed to debug messages.

Not sure why these aren’t matching. What does it say next to “Edition” on the series detail page?

**Comment by miracle152005** [comment]
It says "Print" as the Edition, forcing it as TPB also does not change the outcome.
