### ISSUE TITLE
Nzbindex stopped working

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#2165]
NZBindex no longer functioning from mylar.

I have noticed around the december time frame last 2 weeks of the month, auto does not work anymore and manual has not worked since before that.

I see on some of the logs mylar seems to be going to beta.nzbindex ????

Is there supposed to be new settings need to be activated for this to work again?

Cheers.
Pipi

**Comment by evilhero** [comment]
Looks like they update their website so the current parser doesn't work anymore most likely, and / or the regex's are failing.

Will have to look into it more and see exactly what's up...

**Comment by evilhero** [comment]
Should be all working now - there's some new search methods that can be used (eventually), but it looks like they haven't implemented them as of yet. But this fix gets things working again so at least things will be retrieved properly...
