### ISSUE TITLE
Mylar cannot create directory in network share

### ISSUE THREAD

**Issue by arqcan** [evilhero/mylar#2168]
I have 2 PCs one with my myar instance running and the torrent client and the other is where my comics are store.

When i add the network location of the stored comics into Mylar, i get errors saying that it is unable to create the directory in the comics location.

2019-01-16 15:38:33 | WARNING | [DIRECTORY-CHECK] Could not create directory: E:\Hawkman (2018)[[Error 3] The system cannot find the path specified: u'E:\\']. Aborting.
-- | -- | --
2019-01-16 15:38:33 | INFO | [DIRECTORY-CHECK] Creating comic directory (0777) : E:\Hawkman (2018)
2019-01-16 15:38:33 | WARNING | [DIRECTORY-CHECK] Could not find comic directory: E:\Hawkman (2018)

I have tested this in numerous different ways:

\\[servername]\[share]
\\[ip address]\[share
e:\\[share]  - this is done as a mapped drive in windows.

The share permissions are correct as i can read/write/modify the folders on all of the pcs with all of the users on the PCs. If i set the comics location to a local drive, everything works fine. Is this a known issue with mylar and network shares or is there a fix?

**Comment by barbequesauce** [comment]
Are you running Mylar interactively in your logged in session, or as a service?

If the former, can you run "net use" and paste the output here?

If the latter, remote shares (and therefore mapped drives) are not visible to service accounts unless running under a domain account.

**Comment by arqcan** [comment]
Thanks for the help I think I have it sorted now, I moved to running it from just a command line rather than as a service and it appears to be working now.
