### ISSUE TITLE
Error after search runs and then all subsequent searches queued

### ISSUE THREAD

**Issue by TheOttoman2012** [evilhero/mylar#2171]
I've had Mylar for a few years, and I've got over 900 titles, and have been finding that it hasn't been searching and downloading anymore, As a troubleshooting exercise, I loaded up a fresh install using the latest build and then began importing titles using the Importer tool. After I got about 30 titles in, I began doing some manual searches and received this error:

```
Uncaught exception: Traceback (most recent call last):
File "D:\Mylar_2019\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "D:\Mylar_2019\mylar\helpers.py", line 3059, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "D:\Mylar_2019\mylar\search.py", line 1822, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "D:\Mylar_2019\mylar\search.py", line 353, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "D:\Mylar_2019\mylar\search.py", line 1458, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
File "D:\Mylar_2019\mylar\search.py", line 2584, in searcher
sendtosab = ss.sender()
File "D:\Mylar_2019\mylar\sabnzbd.py", line 53, in sender
'nzo_id': ''.join(sendresponse['nzo_ids']),
KeyError: 'nzo_ids'
```

After this, if I do any other searches I get "Now Queueing _ComicBookTitle (2000) #1_ for search" which just hangs forever until I restart.

**Comment by evilhero** [comment]
The nzo_ids is a reference to sabnzbd - so mylar is trying to send it to your sabnzbd client, but is failing.

Do you have completed downoad handling enabled or are you using the ComicRN script?

Also is your version of sabnzbd an older version? It came up a few weeks ago that older versions of sabnzbd don't return the nzo_ids that mylar uses to track things so it will cause an error - and subsequently further searches won't get performed.

**Comment by TheOttoman2012** [comment]
So I didn't notice, but yes, in fact, there was an update to sabnzbd that I hadn't done.

I upgraded, and the issue disappeared. 
Thanks, and sorry for reporting a non-mylar issue.

**Comment by evilhero** [comment]
That's good news - no worries about the issue. 

Would you happen to know which version of sabnzbd  you were on before upgrading? I've been trying to track down the version that's lacking the nzo_ids reference so it can be adjusted within mylar, but haven't been able to find it as of yet.

**Comment by TheOttoman2012** [comment]
It was an oldie... 0.7.18
