### ISSUE TITLE
Can´t access to config page

### ISSUE THREAD

**Issue by RoyNewo** [evilhero/mylar#2172]
After the last update i´ve started to got this error everytime when i try to en ter in the config page:

Error !
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 138: ordinal not in range(128)
</fieldset> <fieldset> <legend>Branch history</legend> <div>${config['branch_history']}</div> </fieldset> <fieldset> <div class="row"> <label style="font-size:16px;font-weight:bold;">Provider Usage (${config['dltotals']})</label> <a href="#" onclick="show_stats();"><span style="vertical-align:bottom;text-align:center;float:right;">Show Stats</span></a>
/opt/Mylar/data/interfaces/default/config.html, line 102:
<div>${config['branch_history']}</div>
/opt/Mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/opt/Mylar/lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
/opt/Mylar/lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/Mylar/lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
/opt/Mylar/lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/opt/Mylar/mylar/webserve.py, line 57:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

I tried to reinstall mylar and i´ve still got the same issue.
I´m working in Ubunut 18.04

**Comment by evilhero** [comment]
Are you running a git install or source ?

Is there anything in the logs if you start mylar with the -v option (or enable verbose logging via the Logs tab within Mylar) and try to access the configuration page ?

Everything is working fine here on ubuntu 16.04 & Windows 10, so not sure if it's a localized problem or something else as I cannot reproduce atm.

**Comment by RoyNewo** [comment]
cristian@cristian-desktop:/opt/Mylar$ git log --pretty=format:"%h - %cr - %an - %s %B" -n 5
d0ce300 - hace 8 días - evilhero - Merge branch 'development' Merge branch 'development'

d2e0364 - hace 8 días - evilhero - FIX: Fix for TPB/One-Shot file rechecking expecting an issue number, but one not being present due to the type FIX: Fix for TPB/One-Shot file rechecking expecting an issue number, but one not being present due to the type

8a350ba - hace 8 días - evilhero - FIX:(#2165) fix for Experimental Search not returning results FIX:(#2165) fix for Experimental Search not returning results

3c3db41 - hace 8 días - evilhero - Merge branch 'development' Merge branch 'development'

c9f6d99 - hace 8 días - evilhero - FIX:(#2166) When post-processing issues that exist with more than one volume and the issue numbers are identical, in some cases would incorrectly take the wrong series if both series volumes existed in an watched arc FIX:(#2166) When post-processing issues that exist with more than one volume and the issue numbers are identical, in some cases would incorrectly take the wrong series if both series volumes existed in an watched arc
cristian@cristian-desktop:/opt/Mylar$ git log --pretty=format:"%h - %cr - %an - %s %B" -n 5 --encoding=UTF-8
d0ce300 - hace 8 días - evilhero - Merge branch 'development' Merge branch 'development'

d2e0364 - hace 8 días - evilhero - FIX: Fix for TPB/One-Shot file rechecking expecting an issue number, but one not being present due to the type FIX: Fix for TPB/One-Shot file rechecking expecting an issue number, but one not being present due to the type

8a350ba - hace 8 días - evilhero - FIX:(#2165) fix for Experimental Search not returning results FIX:(#2165) fix for Experimental Search not returning results

3c3db41 - hace 8 días - evilhero - Merge branch 'development' Merge branch 'development'

c9f6d99 - hace 8 días - evilhero - FIX:(#2166) When post-processing issues that exist with more than one volume and the issue numbers are identical, in some cases would incorrectly take the wrong series if both series volumes existed in an watched arc FIX:(#2166) When post-processing issues that exist with more than one volume and the issue numbers are identical, in some cases would incorrectly take the wrong series if both series volumes existed in an watched arc
cristian@cristian-desktop:/opt/Mylar$

**Comment by evilhero** [comment]
Ok, you're running master - but nothing has changed with regards to those lines in awhile. Were you really behind on updating prior to today?

Any fix that happens will hit development first, so I might have to cherry-pick into master - although I dunno if it's going to work since I can't really test it.

**Comment by RoyNewo** [comment]
no, problem i´m just informing about the problem, i recently started to use mylar and i was trying to improve my config with jackett program, so i don´t mind wait
