### ISSUE TITLE
The file cannot be found in the location provided

### ISSUE THREAD

**Issue by judzk** [evilhero/mylar#2180]
**Describe the bug**
Since 1 week i got a error when i try to PP :
[POST-PROCESSING] The file cannot be found in the location provided
The file is paste from "monitor folder" to "the cache folder" and then nothing, after 3 days my cache was 50go ...

**Screenshots/Logs**
https://pastebin.com/m5JD9dJX

**Environment (please complete the following information):**
Ubuntu 16
The last master

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
Seems to be using the OS version of bs4 instead of the mylar-bundled version... can you attach the actual debug log file please from startup instead of a c&p from the web log page? Theres some data in there that is not displayed on the web pager for readability...

**Comment by judzk** [comment]
[mylar.log](https://github.com/evilhero/mylar/files/2818328/mylar.log)

**Comment by barbequesauce** [comment]
When Mylar starts up (actually on line 7 of Mylar.py - it's the first meaningful activity in startup)  it prepends its lib directory into PYTHONPATH. For some reason that's being ignored in your case and the OS libs are being used, not sure why...

What's PYTHONPATH set to in a new shell? You're not using virtualenv or docker or any encapsulation stuff, right?

**Comment by evilhero** [comment]
Do you have a bs4 directory in the root of mylar by chance ?

**Comment by judzk** [comment]
nop, don't have one

**Comment by evilhero** [comment]
How do you run mylar - ie. what command do you give to start it ? 

also, try going into the command line and into the root of the mylar directory and typing in:
```python comictaggerpy --version'

**Comment by judzk** [comment]
I use `python Mylar.py -d`
or this service
[mylar.txt](https://github.com/evilhero/mylar/files/2818705/mylar.txt)
For comictagger
`/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
ComicTagger 1.25.2 [ninjas.walk.alone / SHURIKEN]
Modified version of ComicTagger (Copyright (c) 2012-2014 Anthony Beville)
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
`

**Comment by evilhero** [comment]
Try going into your ```root_of_mylar/lib/comictaggerlib/``` folder. Do you see a comicapi folder or even a bs4 file or folder in there ?

**Comment by judzk** [comment]
i have a comicapi and a bs4 folder in lib

**Comment by judzk** [comment]
Sorry for the delay, lot of work.
so i don't any folder in comictaggerlib
Mylar/lib/bs4/ some file and folder here
Mylar/lib/comictagger , some file too , one comicapi with files but no bs4 

When a delete all the .pyc i got a new error :
```
/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
PyQt4 is not available.  ComicTagger is limited to command-line mode.
You must specify at least one filename.  Use the -h option for more info
```

**Comment by barbequesauce** [comment]
So that’s easy then - your bs4 libraries are missing. Not sure why git doesn’t complain about it when you update...

Best bet - re-install to a new folder and then copy over your mylar.db, config.ini, and cache folder (including everything inside).

**Comment by judzk** [comment]
nop :( same error with a fresh install
```
[META-TAGGER] Output: /usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
'The soupsieve package is not installed. CSS selectors cannot be used.'
Cannot find /usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
'The soupsieve package is not installed. CSS selectors cannot be used.'
```

**Comment by barbequesauce** [comment]
OK so here's the thing...

- bs4 is distributed with Mylar in its lib folder.
- Early in Mylar's startup, it pushes that lib folder to the front of the list of places to look for libraries like bs4.
- For some reason, your machine is ignoring that and looking in the "normal" places first - but we cant put together why. 

What else is running on this machine? Is it a stock python install, or built from source? Are you using any environmental stuff like pyenv?
