### ISSUE TITLE
Not grabbing any issues but then will work on restart

### ISSUE THREAD

**Issue by drmikenz** [evilhero/mylar#2184]
Desc: Searches using any of the NZB indexers don't return hits for comics which are there when searching manually on the index itself. Unsure if DDL is finding anything. Seem possible at 16:49:22 but could be totally wrong ;)  Consistent notes in the log about booktype not matching. 

See log: 
[Mylar 3.2.19.log](https://github.com/evilhero/mylar/files/2825225/Mylar.3.2.19.log)

then upon restart it -sometimes- just works and immediately finds and snatches the files:
[Mylarlogsuccess.log](https://github.com/evilhero/mylar/files/2825228/Mylarlogsuccess.log)

Environment (please complete the following information):

OS: MacOS Mojave
Branch / commit: Dev/
Additional information Add any other information about the problem here.

**Comment by evilhero** [comment]
Mylar will not download a TPB if it's of the same series but you're looking for a specific issue. That's what the errors are indicating when it says that ```booktypes do not match``` - basically it found a TPB, but you're searching for an issue, so it's a no-match.

There have been several fixes over the last few days in regards to the DDL option - so you might want to try and update and then see if that helps at all.

**Comment by drmikenz** [comment]
Hmm, well in this case these don't seem to be TPBs, and the error is "Looking for None, this is a issue. Ignoring this result", when as far as I know i'm searching for an issue . From the log:

03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.844 : Thread-39 : checking search result: Batman Beyond #7 (2017)\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.854 : Thread-39 : sub:Batman Beyond #7 (2017)\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.903 : Thread-39 : comsize_b: 23068672\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.940 : Thread-39 : size given as: 22.0 MB\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.986 : Thread-39 : store date used is : 2019-01-02\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.987 : Thread-39 : date used is : 2019-01-02\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.992 : Thread-39 : [ddl] postdate_int: Wed, 26 Apr 2017 00:00:00\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.1030 : Thread-39 : usedate: 2019-01-02\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.1086 : Thread-39 : Wed, 26 Apr 2017 00:00:00 is after store date of 2019-01-02\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.1097 : Thread-39 : Entry: Batman Beyond #7 (2017)\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.391 : Thread-39 : NEWLY SPLIT REORGD: [u'Batman', u'Beyond', u'7', u'(2017)']\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.426 : Thread-39 : checking date : 2017\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.429 : Thread-39 : date: 2017\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.739 : Thread-39 : datecheck: [\{'date': u'2017', 'position': 3, 'mod_position': 17\}]\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.745 : Thread-39 : sctd: 2019\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.754 : Thread-39 : year verified as : 2017\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.760 : Thread-39 : year verified as: 2017\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.783 : Thread-39 : highest_series_position: 3\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.789 : Thread-39 : possible_issuenumbers: [\{'position': 2, 'validcountchk': False, 'number': u'7', 'mod_position': 15\}]\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.861 : Thread-39 : issue_position: 2\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.878 : Thread-39 : issue verified as : 7\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.1002 : Thread-39 : sf_highest_series_pos: [u'Batman', u'Beyond']\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.parseit.1034 : Thread-39 : series title possibly: Batman Beyond\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.1114 : Thread-39 : parsed_info: \{'series_volume': None, 'booktype': 'issue', 'issueid': None, 'sub': None, 'comiclocation': None, 'reading_order': None, 'parse_status': 'success', 'dynamic_name': u'BatmanBeyond', 'series_name': u'Batman Beyond', 'comicfilename': u'Batman Beyond #7 (2017)', 'issue_number': u'7', 'issue_year': '2017', 'scangroup': None, 'alt_series': None, 'alt_issue': None, 'series_name_decoded': 'Batman Beyond'\}\
03-Feb-2019 16:49:25 - DEBUG   :: mylar.NZB_SEARCH.1125 : Thread-39 : Booktypes do not match. Looking for None, this is a issue. Ignoring this result.

**Comment by barbequesauce** [comment]
What OS? Master or dev? What commit?

**Comment by drmikenz** [comment]
Just checked the lastest Dev commit: 6c487d5c54fb192dfd6c239a78e9f4feaca20798 and still the same issue

OS: Mac OS Mojave.

**Comment by evilhero** [comment]
How are these searches firing off ? It doesn't look like you're performing a manual search for each issue (ie. the magnifying glass on the series detail page) - are you doing a Force Check for issues from the Wanted page, or via some other method?

**Comment by drmikenz** [comment]
> How are these searches firing off ? It doesn't look like you're performing a manual search for each issue (ie. the magnifying glass on the series detail page) - are you doing a Force Check for issues from the Wanted page, or via some other method?
> 
> EDIT. If I'm right - you're marking selected issues as Wanted via one of the dropdown's on either the series detail page, or the Wanted tab...

You are correct! Adding a series, then selecting something like mark all skipped as wanted. Downloaded the new committ and will let you know :)
