### ISSUE TITLE
Error when going to THIS WEEK

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#2191]
Running on OSX

I get the following error on the This Week screen
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/jhandloff/mylar/mylar/webserve.py", line 1595, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/Users/jhandloff/mylar/mylar/webserve.py", line 1879, in manualpull
    return mylar.locg.locg(weeknumber=weeknumber,year=year)
  File "/Users/jhandloff/mylar/mylar/locg.py", line 68, in locg
    data = r.json()
  File "lib/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "lib/simplejson/__init__.py", line 428, in loads
    return _default_decoder.decode(s)
  File "lib/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "lib/simplejson/decoder.py", line 418, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "lib/simplejson/scanner.py", line 71, in scan_once
    return _scan_once(string, idx)
  File "lib/simplejson/scanner.py", line 44, in _scan_once
    return parse_array((string, idx + 1), _scan_once)
  File "lib/simplejson/decoder.py", line 296, in JSONArray
    raise JSONDecodeError("Expecting , delimiter", s, end)
JSONDecodeError: Expecting , delimiter: line 1 column 5 (char 5)

From the logs:

2019-02-08 16:15:25 | DEBUG | Now searching experimental for issue number: 04 to try and ensure all the bases are covered
-- | -- | --
2019-02-08 16:15:24 | INFO | ALT_PULL: 2 PULLBYFILE: False week: 05 year: 2019
2019-02-08 16:15:24 | INFO | trying to repopulate to week: 05-2019
2019-02-08 16:15:20 | DEBUG | If you can read this message, debug logging is now workin

**Comment by barbequesauce** [comment]
Thanks. Which branch are you running, and what commit?

Can you attach the whole debug log file please? That snippet doesnt really have enough to understand what's happening...

**Comment by thewindupboy** [comment]
Version: 5e6b861fadcbd6a43412e0a4e8a7cdee6e8e945c (development)
[mylar.log](https://github.com/evilhero/mylar/files/2846940/mylar.log)

**Comment by barbequesauce** [comment]
Ah. There were a lot of changes since your last update in May.... including a security fix. Mylar will not work until you update...

**Comment by thewindupboy** [comment]
It worked yesterday, though!  
OK, how do I update?

**Comment by barbequesauce** [comment]
Is it a git install, or a zip?

If it's a git install, just click the "Check for Updates" link on the bottom right.
If it's a zip install, download the zip from [here](https://github.com/evilhero/mylar/archive/master.zip) and overlay the install with the contents.

**Comment by thewindupboy** [comment]
When I click th check for updates, the command window shows
08-Feb-2019 16:46:45 - WARNING :: mylar.checkGithub.175 : CP Server Thread-9 : [ERROR] Could not get the latest commit from github: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)

This is an older macbook, so it might suck

**Comment by barbequesauce** [comment]
looks like you need to update git too. what version of macOS?

**Comment by thewindupboy** [comment]
10.13.6 on OSX

**Comment by barbequesauce** [comment]
Updater is [here](https://git-scm.com/download/mac)

**Comment by thewindupboy** [comment]
Updaed git, restarted mylar, clicked check for new version:

08-Feb-2019 16:56:33 - WARNING :: mylar.checkGithub.175 : CP Server Thread-6 : [ERROR] Could not get the latest commit from github: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)

**Comment by barbequesauce** [comment]
Looks like python is on the old side too... you can try 'pip install --update requests'

**Comment by thewindupboy** [comment]
No such option --update

**Comment by barbequesauce** [comment]
sorry 'pip install requests --upgrade'

long time since I had to do this

**Comment by thewindupboy** [comment]
Because nothing is simple ;)

Downloading/unpacking requests
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement requests
Cleaning up...
No distributions at all found for requests
Storing debug log for failure in /Users/jhandloff/.pip/pip.log

**Comment by barbequesauce** [comment]
wow.

`sudo pip install --index-url https://pypi.python.org/simple/ --upgrade pip`

If that works (fingers crossed) then you should be able to do

`sudo pip install requests --upgrade`

**Comment by thewindupboy** [comment]
Nope.  Pox.

**Comment by evilhero** [comment]
Try ```pip install requests[security] ```

Also make sure to add your path to the git_path in your config.ini (without mylar running)

Sorry @barbequesauce, on phone and the thing keeps buzzing like a pimp in a brothel...

**Comment by thewindupboy** [comment]
[Git]
git_user = evilhero
check_github = True
git_path = /usr/local/bin/git
check_github_on_startup = True
git_branch = development

**Comment by thewindupboy** [comment]
pip install requests[security]
didn't help

**Comment by claym** [comment]
for what it's worth, i was having this problem and updating to latest development fixed it

**Comment by barbequesauce** [comment]
Yep @claym he has a few problems, current one is that python is still using a version of TLS that Github is blocking

**Comment by evilhero** [comment]
Update pip ```curl https://bootstrap.pypa.io/get-pip.py | python```

The try updating requests again

**Comment by thewindupboy** [comment]
OK, did both, and a whole bunch of stuff happened

**Comment by evilhero** [comment]
Does update work on mylar now?

**Comment by thewindupboy** [comment]
Nope, same problem

**Comment by evilhero** [comment]
You're gonna have it install from source :
- Download the source from github for mylar.
- Backup your existing mylar cache directory, your mylar.db and the config.ini. - Wipe your existing installation. 
- Extract the source zip to that directory.
- Drop back in all the backed up items above into the new directory.
- run mylar.

**Comment by thewindupboy** [comment]
OK, I can do that.  Thanks!

**Comment by thewindupboy** [comment]
That solved it!  Thank you!

**Comment by thewindupboy** [comment]
That said, I'm now getting a "You're running an unknown version of Mylar Update or Close" and when I choose Update, mylar restarts as if it updated, but...

**Comment by evilhero** [comment]
Check the debug log - what does it say when you attempt to update?

**Comment by thewindupboy** [comment]
Changed to master, same problem.  Attaching the log file
[mylar.log](https://github.com/evilhero/mylar/files/2847362/mylar.log)

**Comment by evilhero** [comment]
You might have missed some hidden contents in the old directory when you went to delete?

It looks like there might be a .git folder in the root of mylar, delete that. Also set your ```check_github = False``` and ```check _github_on_startup = False```

**Comment by thewindupboy** [comment]
Didn't help.  Worth noting that at the bottom of the page, it says "Version: None (master)"

**Comment by evilhero** [comment]
Did you restart mylar? What do the debug logs say now when you try the update

**Comment by thewindupboy** [comment]
But it is working, and I'm going to be switching to a new box soon enough.  Thanks for all your help, @evilhero  and @barbequesauce

**Comment by evilhero** [comment]
Your pull won't work unless you get rid of the None for your commit...

**Comment by thewindupboy** [comment]
Sure, but Mylar is, itself, working, and for now that'll do.  Like I said, I'll be doing a fresh install on a new machine soon enough :)

**Comment by phairplay** [comment]
hi, im on the latest dev updated 5mins ago and ive come here about the same issue

`Version: 33c09924f67b980d3a3331e3f0c56c5841f5cb9b (development)`
running on windows
the error i get is:

```
Traceback (most recent call last):
  File "C:\Mylar\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Mylar\lib\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\lib\cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 1649, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "C:\Mylar\mylar\webserve.py", line 1939, in manualpull
    weeklypull.pullit()
  File "C:\Mylar\mylar\weeklypull.py", line 361, in pullit
    comicnm = issname[1]
IndexError: list index out of range
```
i refresh the page then go to the log page and picked out the following


```
2019-02-09 20:38:20 | INFO | Preparing to update to the new listing.
-- | -- | --
2019-02-09 20:38:20 | DEBUG | today: 20181128
2019-02-09 20:38:20 | DEBUG | shipdate: 20190206
2019-02-09 20:38:20 | DEBUG | no substitues.csv file located - not performing substitutions on weekly pull list
2019-02-09 20:38:19 | INFO | [PULL-LIST] Populating & Loading pull-list data from file
2019-02-09 20:38:19 | INFO | Weekly pull list present - checking if it's up-to-date..
2019-02-09 20:38:19 | INFO | ALT_PULL: 0 PULLBYFILE: True week: 05 year: 2019
2019-02-09 20:38:19 | INFO | trying to repopulate to week: 05-2019
2019-02-09 20:38:10 | DEBUG | If you can read this message, debug logging is now working
```

**Comment by evilhero** [comment]
Set your ```alt_pull = 2``` in the config.ini (with Mylar not running). 

It looks like it defaulted back to 0, I guess because it couldn't connect to the site the first few times due to not running a newer commit, and then upon saving the config it saved the 0 as your new alt_pull value (this is a known issue unfortunately)...

**Comment by phairplay** [comment]
fixed many thanks
