### ISSUE TITLE
32 pages error

### ISSUE THREAD

**Issue by vader083** [evilhero/mylar#2192]
**Describe the bug**
Unable to download issues from 32 pages, it searches and gets results but fails with stack trace below.  This might be a duplicate b/c I seen another 32 pages issue 6 days ago.

**Screenshots/Logs**
File "/app/mylar/mylar/search.py", line 353, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 651, in NZB_SEARCH
bb = a.searchit()
File "/app/mylar/mylar/auth32p.py", line 354, in searchit
searchResults = d.text
UnboundLocalError: local variable 'd' referenced before assignment

**Environment (please complete the following information):**
 -docker UNRAID

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
What commit and branch?

**Comment by evilhero** [comment]
Make sure you're running an up to date version of Mylar. If you're not, 32P won't work and your pull won't work as well as you need to be up to date due to security fixes.

**Comment by vader083** [comment]
I'm running with the latest docker , I just pulled and ran a search and get the error.  Here are some addition lines before the stack trace


2019-02-10 20:34:58 | ERROR | [32P-AUTHENTICATION] ['location'] Could not POST URL https://32pag.es/ajax.php
-- | -- | --
2019-02-10 20:34:48 | DEBUG | payload: {u'action': u'groupsearch', u'issue': u'3', u'id': u'24515'}
2019-02-10 20:34:48 | DEBUG | Unable  to properly verify reference on 32P - will update the 32P reference  point once the issue has been successfully matched against.
2019-02-10 20:34:48 | DEBUG | 1 series match the tile being searched for on 32P...
2019-02-10 20:34:48 | DEBUG | 1 series listed for searching that match.
2019-02-10 20:34:48 | DEBUG | [MATCH] Prodigy. [24515]
2019-02-10 20:34:48 | DEBUG | searchresult: Prodigy --- Prodigy [Image]

**Comment by barbequesauce** [comment]
Which docker image is that? Linuxserver? We asked them to rebuild the image earlier this week, with that error I doubt you’re on the rebuilt image...

**Comment by vader083** [comment]
yeah linuxserver, ok than either they're not uptodate or it's me.  Thanks for the help.

**Comment by evilhero** [comment]
The fix for 32p upgrading their stuff is in dev still (it got pushed a few days after the security fix as that was more of a priority). I believe the docker image is probably against what we asked for, which was the security patch commit.

Will try to push the 32P fix to master tomorrow if it can be managed against all the current changes in development.

**Comment by silentArtifact** [comment]
Has there been any luck with this? It looks like the issue's still happening for me.

**Comment by evilhero** [comment]
Master merged into development just a few moments ago. The 32P fixes that were needed are all in there now, so everyone should be OK going forward  (I hope)...

**Comment by silentArtifact** [comment]
You're a damn hero. :P Now to wait for the linuxserver container to update. Thanks for all your hard work on this!
