### ISSUE TITLE
Unable to Add/Import Comic ID 30345

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#2195]
I have been unable to get The Walking Dead 2004 to add either by selecting it as a new series or by importing existing files. The page loads continually and in the logs I get:
Comic ID: 30345 has not finished loading. Nulling some values so things display properly until they can populate

When I load the Debug logs I get:
Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 104, in addComictoDB
comic = cv.getComic(comicid, 'comic')
File "C:\Mylar\mylar\cv.py", line 156, in getComic
return GetComicInfo(comicid, dom)
File "C:\Mylar\mylar\cv.py", line 384, in GetComicInfo
fc_id = fc['data-ref-id']
File "lib\bs4\element.py", line 1011, in __getitem__
return self.attrs[key]
KeyError: 'data-ref-id'

 - OS: Windows10
 - Branch / commit: Dev 63dc7bf0ba0637495d73dd7902e3fd4e26f61fc8 

I have been able to add other comics but this one is problematic. I had this problem initially with the master branch and switched to development on a different machine but still have the same problem. Any words of wisdom?

**Comment by evilhero** [comment]
Should be fixed in development commit d4e930d now.

**Comment by rutskiuk** [comment]
Yep, that did it :)
