### ISSUE TITLE
One-off Post-processing uses same source-dir and dest-dir intead of grabbag_dir

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#2203]
**Describe the bug**
In several instances post processing/completed download handling incorrectly uses the directory the one-off has been downloaded to as both the source and destination directories in post-processing move steps; after this, the cleanup deletes the download folder and cbr causing the downloaded file to disappear. 

**Screenshots/Logs**
4-Feb-2019 14:46:48 - DEBUG   :: mylar.searchforissue.1852 : SEARCH-QUEUE : I found Robyn Hood: Outlaw #1
14-Feb-2019 14:46:48 - DEBUG   :: mylar.foundsearch.723 : SEARCH-QUEUE : [UPDATER] comicid: 117078
14-Feb-2019 14:46:48 - DEBUG   :: mylar.foundsearch.724 : SEARCH-QUEUE : [UPDATER] issueid: 700616
14-Feb-2019 14:46:48 - INFO    :: mylar.foundsearch.757 : SEARCH-QUEUE : [UPDATER] Updating status to snatched
14-Feb-2019 14:46:48 - DEBUG   :: mylar.foundsearch.758 : SEARCH-QUEUE : [UPDATER] Provider is experimental
14-Feb-2019 14:46:49 - INFO    :: mylar.foundsearch.860 : SEARCH-QUEUE : [UPDATER] Updated the status (Snatched) complete for Robyn Hood: Outlaw Issue: 1
14-Feb-2019 14:46:58 - DEBUG   :: mylar.processor.116 : AUTO-COMPLETE-NZB : Item is no longer in active queue. It should be finished by my calculations
14-Feb-2019 14:46:58 - DEBUG   :: mylar.processor.161 : AUTO-COMPLETE-NZB : File has now downloaded!
14-Feb-2019 14:47:04 - DEBUG   :: mylar.historycheck.173 : AUTO-COMPLETE-NZB : found matching completed item in history. Job has a status of SUCCESS/HEALTH
14-Feb-2019 14:47:04 - DEBUG   :: mylar.historycheck.192 : AUTO-COMPLETE-NZB : Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire has final file size of 32MB
14-Feb-2019 14:47:04 - DEBUG   :: mylar.historycheck.195 : AUTO-COMPLETE-NZB : location found @ /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_monitor.3173 : AUTO-COMPLETE-NZB : File successfully downloaded - now initiating completed downloading handling.
14-Feb-2019 14:47:04 - INFO    :: mylar.postprocess_main.3091 : POST-PROCESS-QUEUE : Now loading from post-processing queue: {'issueid': u'700616', 'apicall': True, 'nzb_name': 'Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire', 'nzb_folder': '/volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire', 'failed': False, 'ddl': False, 'comicid': u'117078'}
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.350 : Thread-14 : [POST-PROCESSING] nzb name: Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.351 : Thread-14 : [POST-PROCESSING] nzb folder: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.368 : Thread-14 : [POST-PROCESSING] Using NZBGET
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.369 : Thread-14 : [POST-PROCESSING] NZB name as passed from NZBGet: Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.411 : Thread-14 : [POST-PROCESSING] Now post-processing directly against ComicID: 117078 / IssueID: 700616
14-Feb-2019 14:47:04 - INFO    :: mylar.traverse_directories.1354 : Thread-14 : there are 1 files.
14-Feb-2019 14:47:04 - DEBUG   :: mylar.listFiles.146 : Thread-14 : [FILENAME]: Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.286 : Thread-14 : Scanner group tag discovered: The Seeker-Empire
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.391 : Thread-14 : NEWLY SPLIT REORGD: ['Robyn', 'Hood', '-', 'Outlaw', '01', '(of 06)', '(2019)', '(digital)']
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.501 : Thread-14 : Mini-Series Count detected. Maximum issue # set to : 6
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.504 : Thread-14 : Issue Number SHOULD BE: 01
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.426 : Thread-14 : checking date : 2019
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.429 : Thread-14 : date: 2019
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.739 : Thread-14 : datecheck: [{'date': '2019', 'position': 6, 'mod_position': 31}]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.745 : Thread-14 : sctd: 2019
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.754 : Thread-14 : year verified as : 2019
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.760 : Thread-14 : year verified as: 2019
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.783 : Thread-14 : highest_series_position: 6
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.789 : Thread-14 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '01', 'mod_position': 20}]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.861 : Thread-14 : issue_position: 4
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.878 : Thread-14 : issue verified as : 01
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.986 : Thread-14 : ALT-SERIES NAME [ISSUE TITLE]: Robyn Hood [Outlaw]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.1002 : Thread-14 : sf_highest_series_pos: ['Robyn', 'Hood', '-', 'Outlaw']
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.1034 : Thread-14 : series title possibly: Robyn Hood - Outlaw
14-Feb-2019 14:47:04 - DEBUG   :: mylar.parseit.1047 : Thread-14 : Alternate series / issue title: Robyn Hood [Outlaw]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.448 : Thread-14 : [POST-PROCESSING] Alternate series naming detected: Robyn Hood
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.1227 : Thread-14 : [POST-PROCESSING][ONEOFF-SELECTION][self.nzb_name: Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.1276 : Thread-14 : temploc: 01
14-Feb-2019 14:47:04 - INFO    :: mylar.Process.1280 : Thread-14 : watchmatch: {'justthedigits': '01', 'issueid': None, 'match_type': None, 'sub': None, 'comiclocation': '/volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire', 'booktype': 'issue', 'series_name': 'Robyn Hood - Outlaw', 'comicfilename': 'Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr', 'annual_comicid': None, 'issue_year': '2019', 'volume': None, 'process_status': 'match', 'scangroup': 'The Seeker-Empire', 'alt_series': 'Robyn Hood', 'alt_issue': 'Outlaw', 'series_volume': None}
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.1310 : Thread-14 : [POST-PROCESSING][SUCCESSFUL MATCH: Robyn Hood: Outlaw-117078] Match Verified for Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - DEBUG   :: mylar.Process.1315 : Thread-14 : [POST-PROCESSING] There are 0 files found that match on your watchlist, 1 files are considered one-off's, and 1 files do not match anything
14-Feb-2019 14:47:04 - INFO    :: mylar.Process.1581 : Thread-14 : [PPINFO-POST-PROCESSING-ATTEMPT] {'publisher': u'Zenescope', 'comicname': u'Robyn Hood: Outlaw', 'issuenumber': u'1', 'comiclocation': u'/volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr', 'sarc': None, 'oneoff': True, 'issueid': u'700616', 'comicid': u'117078'}
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1678 : Thread-14 : [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1681 : Thread-14 : [POST-PROCESSING] issuenzb not found.
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1699 : Thread-14 : [POST-PROCESSING] [ONE-OFF POST-PROCESSING] One-off download detected. Post-processing as a non-watchlist item.
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1730 : Thread-14 : [POST-PROCESSING] One-off mode enabled for Post-Processing. Will move into Grab-bag directory: /volume1/Diskstation/Media/Comics/Grabbag
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1825 : Thread-14 : [POST-PROCESSING] Source Path : /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - INFO    :: mylar.validateAndCreateDirectory.1566 : Thread-14 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /volume1/Diskstation/Media/Comics/Grabbag
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.274 : Thread-14 : <type 'str'>
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.275 : Thread-14 : <type 'unicode'>
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.276 : Thread-14 : comicid: 117078
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.277 : Thread-14 : issue# as per cv: 1
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.296 : Thread-14 : issueid:700616
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.327 : Thread-14 : issueid is now : 700616
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.333 : Thread-14 : not an issue, checking against annuals
14-Feb-2019 14:47:04 - DEBUG   :: mylar.rename_param.336 : Thread-14 : Unable to rename - cannot locate issue id within db
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1857 : Thread-14 : [POST-PROCESSING] Destination Path : /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - INFO    :: mylar.nzb_or_oneoff_pp.1858 : Thread-14 : [POST-PROCESSING][move] /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr into directory : /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - DEBUG   :: mylar.get_free_space.3616 : Thread-14 : [FREESPACE-CHECK] /volume1/Diskstation/Media/Comics/Grabbag has 1.3TiB free
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.229 : Thread-14 : File Option: move [META-ENABLED: False]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.230 : Thread-14 : odir: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire [filename: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr][self.nzb_folder: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.231 : Thread-14 : sub_path: None [cacheonly: False][del_nzbdir: True]
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.302 : Thread-14 : [POST-PROCESSING] Attempting to remove file: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.309 : Thread-14 : [POST-PROCESSING] Tidying up. Deleting original folder location : /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:04 - DEBUG   :: mylar.tidyup.315 : Thread-14 : [POST-PROCESSING] Removed original folder location: /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire
14-Feb-2019 14:47:05 - INFO    :: mylar.nzb_or_oneoff_pp.1892 : Thread-14 : [POST-PROCESSING] IssueID is : 700616
14-Feb-2019 14:47:05 - INFO    :: mylar.nzb_or_oneoff_pp.1895 : Thread-14 : [POST-PROCESSING] Writing to db: {'Status': 'Downloaded'} -- {'IssueID': u'700616'}
14-Feb-2019 14:47:05 - INFO    :: mylar.nzb_or_oneoff_pp.1897 : Thread-14 : [POST-PROCESSING] Updated status to Downloaded
14-Feb-2019 14:47:05 - INFO    :: mylar.nzb_or_oneoff_pp.1899 : Thread-14 : [POST-PROCESSING] Updated history for one-off's for tracking purposes
14-Feb-2019 14:47:05 - INFO    :: mylar.nzb_or_oneoff_pp.1900 : Thread-14 : [POST-PROCESSING] Post-Processing completed for: [ Robyn Hood: Outlaw #1 ] /volume1/Downloads/nzbget/completed/comics/Robyn.Hood.-.Outlaw.01.of.06.2019.digital.The.Seeker-Empire/Robyn Hood - Outlaw 01 (of 06) (2019) (digital) (The Seeker-Empire).cbr

**Environment (please complete the following information):**
 - OS: Synology
 - Branch / commit: Dev/a73fe4716606797c3f8902fe2d7f596f269da413

**Comment by evilhero** [comment]
Fix is now in development for this - seemed to be only occurring if one-off's were being snatched from the pull-list with no metatagging enabled.
