### ISSUE TITLE
RSSCheck uses illegal newznab action

### ISSUE THREAD

**Issue by theotherp** [evilhero/mylar#2207]
**Describe the bug**
The newznab RSS check sets `t=7030` which doesn't make sense because `t` should be an action like "search". The `cat` parameter should be set to 7030. See http://newznab.readthedocs.io/en/latest/misc/api/

See https://github.com/evilhero/mylar/blob/master/mylar/rsscheck.py#L441 and following

**Comment by evilhero** [comment]
The t parameter is available when using the ```rss``` endpoint, which is what those RSS calls are doing - they're not calling the api endpoint. There are however 2 separate instances which call the api, but  they both use the t=search parameter.

The idea behind the rss endpoint being used was to avoid api hits for users (plus having an option when the api is down, but the RSS is up in some cases)

**Comment by theotherp** [comment]
Oh, that makes sense. Kind of - I've tested a couple of indexers and all count RSS hits the same as API hits.

**Comment by evilhero** [comment]
There are still a few that don't count the general RSS feed retrieval as an API hit actually (dog & geek being 2) - granted the numbers aren't as great as they once were (those RSS calls were done years ago).

**Comment by theotherp** [comment]
Interesting, didn't know that. I'll update NZBHydra to accept those kinds of queries.
