### ISSUE TITLE
Traceback error when moving to duplicates

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2208]
**Describe the bug**
I am getting this error upon attempting to import an issue. It looks like Mylar thinks the duplicate file failed to move, but checking the directory the duplicate is in the correct Duplicate directory. The file in my import folder also didn't move to my directory. 

It doesn't seem to matter the file or series. It does seem to be tied to if the duplicate file to be moved is in the Mylar directory rather than the import directory.

**Screenshots/Logs**
19-Feb-2019 22:40:20 - INFO :: mylar.toggleVerbose.3764 : CP Server Thread-11 : Verbose (DEBUG) logging is enabled
19-Feb-2019 22:40:20 - DEBUG :: mylar.toggleVerbose.3765 : CP Server Thread-11 : If you can read this message, debug logging is now working
19-Feb-2019 22:40:27 - INFO :: mylar.post_process.818 : CP Server Thread-11 : Starting postprocessing for : Manual Run
19-Feb-2019 22:40:27 - DEBUG :: mylar.Process.350 : Thread-15 : [POST-PROCESSING] nzb name: Manual Run
19-Feb-2019 22:40:27 - DEBUG :: mylar.Process.351 : Thread-15 : [POST-PROCESSING] nzb folder: Y:\Import\Army of DarknessBubba Ho-Tep (2019)
19-Feb-2019 22:40:27 - DEBUG :: mylar.Process.391 : Thread-15 : [POST-PROCESSING] Manual Run initiated
19-Feb-2019 22:40:27 - INFO :: mylar.traverse_directories.1354 : Thread-15 : there are 1 files.
19-Feb-2019 22:40:27 - DEBUG :: mylar.listFiles.146 : Thread-15 : [FILENAME]: Army of Darkness Bubba Ho-Tep Vol.2019 #01.cbz
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.359 : Thread-15 : checking now: Darkness
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.391 : Thread-15 : NEWLY SPLIT REORGD: ['Army', 'of', 'Darkness', 'Bubba', 'Ho-Tep', 'Vol', '.2019', '01']
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.613 : Thread-15 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.595 : Thread-15 : volume_found: 5
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.605 : Thread-15 : volume label detected as : Volume 2019 @ position: 6
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.739 : Thread-15 : datecheck: []
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.781 : Thread-15 : No year present within title - ignoring as a variable.
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.783 : Thread-15 : highest_series_position: 8
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.789 : Thread-15 : possible_issuenumbers: [{'position': 7, 'validcountchk': False, 'number': '01', 'mod_position': 35}]
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.861 : Thread-15 : issue_position: 7
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.878 : Thread-15 : issue verified as : 01
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.883 : Thread-15 : Extra item(s) are present between the volume label and the issue number. Checking..
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.885 : Thread-15 : new split: ['Army', 'of', 'Darkness', 'Bubba', 'Ho-Tep', '.2019', '01', 'Vol']
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.894 : Thread-15 : Volume detected as : v2019
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.1002 : Thread-15 : sf_highest_series_pos: ['Army', 'of', 'Darkness', 'Bubba', 'Ho-Tep']
19-Feb-2019 22:40:27 - DEBUG :: mylar.parseit.1034 : Thread-15 : series title possibly: Army of Darkness Bubba Ho-Tep
19-Feb-2019 22:40:27 - INFO :: mylar.Process.399 : Thread-15 : I have located 1 files that I should be able to post-process. Continuing...
19-Feb-2019 22:40:27 - INFO :: mylar.Process.533 : Thread-15 : Now checking: Army of Darkness/Bubba Ho-Tep [117045]
19-Feb-2019 22:40:28 - INFO :: mylar.Process.755 : Thread-15 : [POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 1000 for ComicID: 117045 / IssueID: 700594
19-Feb-2019 22:40:28 - DEBUG :: mylar.Process.772 : Thread-15 : [POST-PROCESSING][ISSUE-VERIFY][SeriesYear-Volume MATCH] Series Year of 2019 matched to volume/year label of 2019
19-Feb-2019 22:40:28 - DEBUG :: mylar.Process.820 : Thread-15 : [POST-PROCESSING][CLOCATION] Y:\Import\Army of DarknessBubba Ho-Tep (2019)
19-Feb-2019 22:40:28 - DEBUG :: mylar.Process.863 : Thread-15 : [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : Army of Darkness Bubba Ho-Tep [117045]
19-Feb-2019 22:40:28 - DEBUG :: mylar.Process.871 : Thread-15 : [POST-PROCESSING][SUCCESSFUL MATCH: Army of Darkness/Bubba Ho-Tep-117045] Match verified for Army of Darkness Bubba Ho-Tep Vol.2019 #01.cbz
19-Feb-2019 22:40:28 - DEBUG :: mylar.Process.1315 : Thread-15 : [POST-PROCESSING] There are 1 files found that match on your watchlist, 0 files are considered one-off's, and 0 files do not match anything
19-Feb-2019 22:40:28 - INFO :: mylar.duplicate_filecheck.2129 : Thread-15 : [DUPECHECK] Duplicate check for Y:\Import\Army of DarknessBubba Ho-Tep (2019)\Army of Darkness Bubba Ho-Tep Vol.2019 #01.cbz
19-Feb-2019 22:40:28 - INFO :: mylar.duplicate_filecheck.2160 : Thread-15 : [DUPECHECK] Existing Status already set to Downloaded
19-Feb-2019 22:40:28 - INFO :: mylar.duplicate_filecheck.2189 : Thread-15 : [DUPECHECK] Existing file within db :Army of DarknessBubba Ho-Tep Vol.2019 #01 (2019).cbz has a filesize of : 60004567 bytes.
19-Feb-2019 22:40:28 - DEBUG :: mylar.duplicate_filecheck.2204 : Thread-15 : [DUPECHECK] Based on duplication preferences I will retain based on : filesize
19-Feb-2019 22:40:28 - INFO :: mylar.duplicate_filecheck.2256 : Thread-15 : [DUPECHECK-FILESIZE PRIORITY] [#1] Retaining newly scanned in filename : Y:\Import\Army of DarknessBubba Ho-Tep (2019)\Army of Darkness Bubba Ho-Tep Vol.2019 #01.cbz
19-Feb-2019 22:40:28 - INFO :: mylar.duplicate_process.200 : Thread-15 : [DUPLICATE-CLEANUP] New File will be post-processed. Moving duplicate [Y:\Mylar\Dynamite Entertainment\Army of Darkness-Bubba Ho-Tep (2019)\Army of DarknessBubba Ho-Tep Vol.2019 #01 (2019).cbz] to Duplicate Dump Folder for manual intervention.
19-Feb-2019 22:40:28 - INFO :: mylar.validateAndCreateDirectory.1566 : Thread-15 : [DUPLICATE-CLEANUP][DIRECTORY-CHECK] Found comic directory: Y:\Duplicates\
19-Feb-2019 22:40:28 - ERROR :: mylar.excepthook.315 : Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\mylar\PostProcessor.py", line 1626, in Process
    dupchkit = self.duplicate_process(dupthis)
  File "C:\Mylar\mylar\mylar\PostProcessor.py", line 215, in duplicate_process
    logger.warn('[DUPLICATE-CLEANUP] Failed to move  ... to ... %s' % (path_to_move, os.path.join(mylar.CONFIG.DUPLICATE_DUMP, file_to_move)))
TypeError: not all arguments converted during string formatting

Traceback (most recent call last):
  File "C:\Mylar\mylar\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\mylar\PostProcessor.py", line 1626, in Process
    dupchkit = self.duplicate_process(dupthis)
  File "C:\Mylar\mylar\mylar\PostProcessor.py", line 215, in duplicate_process
    logger.warn('[DUPLICATE-CLEANUP] Failed to move  ... to ... %s' % (path_to_move, os.path.join(mylar.CONFIG.DUPLICATE_DUMP, file_to_move)))
TypeError: not all arguments converted during string formatting

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: Master/339281c3991308c54673bd12e10c77006aeb403e

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Stupid typo on my part while I was trying to clean up some logging lines. Fixed in both branches now (was just an incorrect variable reference in the logging line).

**Comment by Nobrumski** [comment]
Thanks looks like that fixed it.
