### ISSUE TITLE
Enhancement: add option to create date folder on move to duplicates

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2210]
I was testing the fix for the typo in moving duplicates and I had another error. I realized the new error was due to having a file with the same name already in the duplicate folder. I don't always clean out my duplicate folder in a timely manner and thought it might be helpful if possible if when moving to duplicates it put the file in a folder with today's date. 

This way there are less chances for the issue of being unable to move a duplicate due to identical named files and also I would be able to see when a duplicate was moved.

**Comment by evilhero** [comment]
Was an easy enough thing to add.

Just set your ```duplicate_dated_folders``` option in the config.ini to True (with Mylar not running of course). It will then create dated folders within the duplicate folder when it's required to move duplicates.

If you don't have the value present in your .ini after updating, just go into the configuration screen, save the settings, shut it down and it will be there then

**Comment by Nobrumski** [comment]
Thanks, this works great
