### ISSUE TITLE
Unable to import issues with valid filename

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2211]
**Describe the bug**
I am having a strange issue when trying to add some series either via import or scan comic library. In this example it has to do with Uncanny X-men (2018). I even tried manually adding Uncanny X-men (2018) in Mylar and seeing if it would import. It fails to do so in this example. The only change in my setup was I updated the ComicVine scraper in ComicRack to the latest version which I didn't realize I had an old copy installed. The filenames appear to be ok. I usually scrape and rename my files using ComicRack and the Comic Vine Scraper script. Then move them to an import folder for Mylar to add to the library. 

It looks like the hangup is possibly on the Vol.2018 part of the name. I don't know if I need to change the format though it works for other files fine. It just seems to be random more recent series. 

If I tell Mylar to scan the import folder and then try to import the result, it adds the issues to the Uncanny X-men (1981).

**Screenshots/Logs**
20-Feb-2019 21:37:05 - DEBUG :: mylar.toggleVerbose.3765 : CP Server Thread-10 : If you can read this message, debug logging is now working
20-Feb-2019 21:37:13 - INFO :: mylar.post_process.818 : CP Server Thread-10 : Starting postprocessing for : Manual Run
20-Feb-2019 21:37:13 - DEBUG :: mylar.Process.350 : Thread-38 : [POST-PROCESSING] nzb name: Manual Run
20-Feb-2019 21:37:13 - DEBUG :: mylar.Process.351 : Thread-38 : [POST-PROCESSING] nzb folder: Y:\Import\Uncanny X-Men (2018)
20-Feb-2019 21:37:13 - DEBUG :: mylar.Process.391 : Thread-38 : [POST-PROCESSING] Manual Run initiated
20-Feb-2019 21:37:13 - INFO :: mylar.traverse_directories.1354 : Thread-38 : there are 10 files.
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #02.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '02']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '02', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 02
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '02', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #03.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '03']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '03', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 03
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '03', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #04.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '04']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '04', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 04
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '04', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #05.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '05']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '05', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 05
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '05', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #06.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '06']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '06', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 06
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '06', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #07.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '07']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '07', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 07
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '07', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #08.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '08']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '08', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 08
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '08', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #09.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '09']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '09', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 09
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '09', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #10.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '10']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '10', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 10
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '10', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - DEBUG :: mylar.listFiles.146 : Thread-38 : [FILENAME]: Uncanny X-Men Vol.2018 #11.cbz
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.391 : Thread-38 : NEWLY SPLIT REORGD: ['Uncanny', 'X-Men', 'Vol', '.2018', '11']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.613 : Thread-38 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.595 : Thread-38 : volume_found: 2
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.605 : Thread-38 : volume label detected as : Volume 2018 @ position: 3
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.739 : Thread-38 : datecheck: []
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.781 : Thread-38 : No year present within title - ignoring as a variable.
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.783 : Thread-38 : highest_series_position: 5
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.789 : Thread-38 : possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '11', 'mod_position': 24}]
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.861 : Thread-38 : issue_position: 4
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.878 : Thread-38 : issue verified as : 11
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.883 : Thread-38 : Extra item(s) are present between the volume label and the issue number. Checking..
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.885 : Thread-38 : new split: ['Uncanny', 'X-Men', '.2018', '11', 'Vol']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.894 : Thread-38 : Volume detected as : v2018
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1002 : Thread-38 : sf_highest_series_pos: ['Uncanny', 'X-Men']
20-Feb-2019 21:37:13 - DEBUG :: mylar.parseit.1034 : Thread-38 : series title possibly: Uncanny X-Men
20-Feb-2019 21:37:13 - INFO :: mylar.Process.399 : Thread-38 : I have located 10 files that I should be able to post-process. Continuing...
20-Feb-2019 21:37:13 - INFO :: mylar.Process.533 : Thread-38 : Now checking: The Uncanny X-Men [3092]
20-Feb-2019 21:37:13 - INFO :: mylar.Process.533 : Thread-38 : Now checking: Uncanny X-Men [115285]
20-Feb-2019 21:37:13 - INFO :: mylar.Process.533 : Thread-38 : Now checking: Uncanny X-Men [87190]
20-Feb-2019 21:37:13 - INFO :: mylar.Process.533 : Thread-38 : Now checking: Uncanny X-Men [57181]
20-Feb-2019 21:37:13 - INFO :: mylar.Process.533 : Thread-38 : Now checking: Uncanny X-Men [43785]
20-Feb-2019 21:37:13 - DEBUG :: mylar.Process.661 : Thread-38 : [POST-PROCESSING] No corresponding issue #02 found for 3092

**Environment (please complete the following information):**
 - OS: [Windows 10
 - Branch / commit: [Master/f837fea

**Additional information**
I used to have the year published at the end of the filename in parenthesis, but tried removing it in case this was now causing issues.

**Comment by evilhero** [comment]
This is now in development awaiting testing as of dev commit 45da4ad.

Also, just for future, post-processing is different than import. Interchanging them as if they were the same option within Mylar really confuses the issue (and me as well). Post-Processing will take issues that exist on your watchlist/storyarcs and post-process them into your required folders. Import will take issues that do not exist on your watchlist and add the series into your watchlist and then move the files into said series directory (no post-processing is done, except for renaming).

**Comment by Nobrumski** [comment]
Gotcha. Thanks for the quick fix and sorry for the mix-up. I think since I always saw it happen during the import process I was thinking it was part of the import process and not separating them into two different processes. 

My workflow is to scan the folder for manual post processing and if files are left behind I then run them through import.
