### ISSUE TITLE
Filter out Panini comics in search

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2215]
Would be a great feature to add an option in the settings that would ignore Panini comics completely.  Just a thought.

**Comment by evilhero** [comment]
In your config.ini, there should be a blacklisted_publishers field. Just put in whatever specific publisher you want Mylar to ignore during search results separated by commas (ie. ```blacklisted_publishers = panini comics, deagostini```). Keep in mind that it has to be named exactly as it appears in the list, otherwise it won't be ignored.

**Comment by edimusxero** [comment]
Perfect, thank you

**Comment by BanditBanditBandit** [comment]
:D great information here!

blacklisted_publishers = panini comics, delcourt, planeta deagostini, abril, egmont

this removes the french, german and italian republishing companies.

**Comment by baz1860** [comment]
Would adding ‘Marvel UK’ also blacklist Marvel or is a full match required?

**Comment by evilhero** [comment]
It matches based on full words- so ```Marvel UK``` will only blacklist all Marvel UK publications, and not Marvel ones.
