### ISSUE TITLE
Nothing listed for week 8 (February 24, 2019 - March 02, 2019)

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2220]
Week 8 - February 24, 2019 - March 02, 2019 shows no titles, the previous week does and the week after but nothing for this week.  I have tried to refresh the pull list and recreate the pull list to no avail.

**Comment by barbequesauce** [comment]
Problem caused by CV data issues... should be ok if you recreate the pull now.

**Comment by edimusxero** [comment]
Yep, it works now.  Thanks
