### ISSUE TITLE
Error when trying to mass import Quantum and Woody (2017) due to first issue #

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2223]
**Describe the bug**
I was doing an import on an old directory and when it tried to add Quantum and Woody (2017) via mass import it failed with the below error due to the first issue number. Now I was able to add the series via search and then manually post process the files so I don't know if it is possible to make the necessary changes that would allow the series addition when mass importing that appear to be there when adding via search. 

**Screenshots/Logs**
28-Feb-2019 21:18:35 - INFO :: mylar.preSearchit.4267 : Thread-36 : [IMPORT][Quantum and Woody! (v2017)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
28-Feb-2019 21:18:35 - DEBUG :: mylar.preSearchit.4274 : Thread-36 : [IMPORT] [!none] dynamicname: quantumwoody
28-Feb-2019 21:18:35 - DEBUG :: mylar.preSearchit.4275 : Thread-36 : [IMPORT] [!none] volume: v2017
28-Feb-2019 21:18:35 - DEBUG :: mylar.preSearchit.4338 : Thread-36 : Minimum issue now set to : 0.0001« - it was 0
28-Feb-2019 21:18:35 - DEBUG :: mylar.preSearchit.4341 : Thread-36 : Start issue now set to : 0.0001« - it was 10000000
28-Feb-2019 21:18:35 - ERROR :: mylar.excepthook.315 : Thread-36 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar-D\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar-D\mylar\webserve.py", line 4342, in preSearchit
    startISSUE = str(getiss)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 6: ordinal not in range(128)

Traceback (most recent call last):
  File "C:\Mylar\mylar-D\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar-D\mylar\webserve.py", line 4342, in preSearchit
    startISSUE = str(getiss)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 6: ordinal not in range(128)

**Environment (please complete the following information):**
 - OS: [Windows10]
 - Branch / commit: [Dev/c13425.]

**Comment by barbequesauce** [comment]
What was the first filename? Not sure it was in that debug log...

**Comment by Nobrumski** [comment]
The first issue is Quantum and Woody! (Vol.2017) #0.0001½. It looks like the log is converting the 1/2 to the double arrow.

**Comment by barbequesauce** [comment]
Related to #2102
