### ISSUE TITLE
Mylar hanging on alternatenames returned after updating pull-list

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#2226]
**Describe the bug**
I just pulled the latest commit and now Mylar is getting stuck during the alternatenames returned process at initial launch. It may not be related to the typo fix. 

**Screenshots/Logs**
c:\Mylar\mylar-D>mylar.py -v
log language set to en_US
Verbose/Debugging mode enabled...
Initializing startup sequence....
04-Mar-2019 21:16:56 - DEBUG :: mylar.configure.767 : MainThread : Log dir: C:\Mylar\mylar-D\logs
04-Mar-2019 21:16:56 - DEBUG :: mylar.configure.786 : MainThread : [Cache Check] Cache directory not found in configuration. Defaulting location to : C:\Mylar\mylar-D\cache
04-Mar-2019 21:16:56 - DEBUG :: mylar.configure.835 : MainThread : [Grabbag Directory] Setting One-Off directory to default location: Y:\Mylar2\Grabbag
04-Mar-2019 21:16:56 - INFO :: mylar.initialize.185 : MainThread : Checking to see if the database has all tables....
04-Mar-2019 21:16:56 - INFO :: mylar.csv_load.1367 : MainThread : Populating Base Exception listings into Mylar....
04-Mar-2019 21:16:56 - INFO :: mylar.csv_load.1369 : MainThread : Populating Custom Exception listings into Mylar....
04-Mar-2019 21:16:56 - INFO :: mylar.dbcheck.1313 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
04-Mar-2019 21:16:56 - INFO :: mylar.dbcheck.1315 : MainThread : Correcting Null entries that make the main page break on startup.
04-Mar-2019 21:16:56 - INFO :: mylar.initialize.199 : MainThread : Successfully discovered local IP and locking it in as : 192.168.254.36
04-Mar-2019 21:16:56 - DEBUG :: mylar.initialize.211 : MainThread : Logger set to use : Rotational Log Handler (default)
04-Mar-2019 21:16:56 - DEBUG :: mylar.initialize.213 : MainThread : ConcurrentLogHandler package not installed. Using builtin log handler for Rotational logs (default)
04-Mar-2019 21:16:56 - DEBUG :: mylar.initialize.214 : MainThread : [Windows Users] If you are experiencing log file locking and want this auto-enabled, you need to install Python Extensions for Windows ( http://sourceforge.net/projects/pywin32/ )
04-Mar-2019 21:16:56 - DEBUG :: mylar.initialize.244 : MainThread : SEARCH_TIER_DATE set to : 2019-02-18
04-Mar-2019 21:16:56 - INFO :: mylar.initialize.258 : MainThread : Remapping the sorting to allow for new additions.
04-Mar-2019 21:16:56 - INFO :: mylar.ComicSort.759 : MainThread : Sucessfully ordered 2882 series in your watchlist.
04-Mar-2019 21:16:56 - INFO :: mylar.validateAndCreateDirectory.1567 : MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Mylar\mylar-D
04-Mar-2019 21:16:56 - INFO :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8095/
04-Mar-2019 21:16:57 - INFO :: mylar.getVersion.119 : MAIN : Branch detected & set to : development
04-Mar-2019 21:16:57 - INFO :: mylar.versionload.309 : MAIN : Version information: development [bcb2e0cc10614e7142cedde180241cb123fb5010]
04-Mar-2019 21:16:58 - INFO :: mylar.start.352 : MAIN : DB Updater sccheduled to fire every 5 minutes
04-Mar-2019 21:16:58 - DEBUG :: mylar.start.362 : MAIN : [AUTO-SEARCH] Search last run @ 2019-03-04 05:34:59.687000
04-Mar-2019 21:16:58 - DEBUG :: mylar.start.368 : MAIN : [AUTO-SEARCH]Auto-Search set to a delay of one minute before initialization as it has been 1241.97248333 minutes since the last run
04-Mar-2019 21:16:58 - INFO :: mylar.queue_schedule.521 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
04-Mar-2019 21:16:58 - INFO :: mylar.queue_schedule.524 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
04-Mar-2019 21:16:58 - INFO :: mylar.queue_schedule.532 : MAIN : [POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
04-Mar-2019 21:16:58 - INFO :: mylar.queue_schedule.535 : MAIN : [POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
04-Mar-2019 21:16:58 - INFO :: mylar.start.401 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
04-Mar-2019 21:16:58 - INFO :: mylar.start.422 : MAIN : [WEEKLY] Weekly Pull-Update initializing immediately as it has been 20.6130219444 hours since the last run
04-Mar-2019 21:16:58 - INFO :: mylar.start.459 : MAIN : [FOLDER MONITOR] Enabling folder monitor for : Y:\Import every 15 minutes.
04-Mar-2019 21:16:58 - INFO :: mylar.start.467 : MAIN : Firing up the Background Schedulers now....
04-Mar-2019 21:16:58 - INFO :: mylar.start.471 : MAIN : Background Schedulers successfully started...
04-Mar-2019 21:16:58 - INFO :: mylar.run.27 : Thread-12 : [WEEKLY] Checking Weekly Pull-list for new releases/updates
04-Mar-2019 21:16:58 - INFO :: mylar.pullit.41 : Thread-12 : Weekly pull list present - checking if it's up-to-date..
04-Mar-2019 21:16:58 - INFO :: mylar.pullit.70 : Thread-12 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
04-Mar-2019 21:16:58 - INFO :: mylar.locg.27 : Thread-12 : pulldate is : 00000000
04-Mar-2019 21:17:00 - INFO :: mylar.locg.70 : Thread-12 : [WEEKLY-PULL] There are 91 issues for the week of 09, 2019
04-Mar-2019 21:17:00 - INFO :: mylar.locg.96 : Thread-12 : Re-creating pullist to ensure everything's fresh.
04-Mar-2019 21:17:01 - INFO :: mylar.locg.131 : Thread-12 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 09
04-Mar-2019 21:17:01 - INFO :: mylar.pullit.82 : Thread-12 : [PULL-LIST] Weekly Pull List successfully loaded with 91 issues.
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Adventures of the Super-Sons'}], 'ComicID': u'112561'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Belladonna: Fire and Fury'}], 'ComicID': u'106668'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Spawn Kills Everyone 2'}], 'ComicID': u'115907'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Doctor Aphra'}], 'ComicID': u'96284'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'The Wicked and The Divine'}], 'ComicID': u'74863'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Spider-Man vs. Deadpool'}], 'ComicID': u'87182'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'I Want To Eat Your Pancreas: The Complete Manga Collection'}], 'ComicID': u'116471'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Magi: The Labyrinth of Magic'}], 'ComicID': u'66335'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Robots Versus Princesses'}], 'ComicID': u'112597'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Star Wars: Solo Adaptation'}], 'ComicID': u'114269'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Die! Die! Die!'}], 'ComicID': u'112222'}
04-Mar-2019 21:17:01 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Stargate Atlantis/Stargate Universe Anthology Ongoing'}], 'ComicID': u'115763'}
04-Mar-2019 21:17:02 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Mega Ghost'}], 'ComicID': u'115895'}

**Environment (please complete the following information):**
 - OS: [Windows10]
 - Branch / commit: [Dev/bcb2e0c]

**Additional information**
I launched with 6a9edb4 which ran fine and then I was alerted to the new update. Immediately upon restart it locked up.

**Comment by Nobrumski** [comment]
After sitting for about 7 minutes per the log, it finally started working so not sure what is causing it to hang. There were no errors.

04-Mar-2019 21:24:02 - INFO :: mylar.LoadAlternateSearchNames.1337 : Thread-12 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Mega Ghost'}], 'ComicID': u'115895'}
04-Mar-2019 21:31:11 - INFO :: mylar.dbUpdate.117 : Thread-13 : [2247/2883] Refreshing :Adam Strange/Future Quest Special (2017) [100350]
04-Mar-2019 21:31:11 - INFO :: mylar.addComictoDB.84 : Thread-13 : aliases currently: None
04-Mar-2019 21:31:11 - INFO :: mylar.validateAndCreateDirectory.1567 : Thread-13 : [DIRECTORY-CHECK] Found comic directory: Y:\Mylar2\DC Comics\Adam Strange-Future Quest Special (2017)
04-Mar-2019 21:31:14 - INFO :: mylar.addComictoDB.126 : Thread-13 : Now adding/updating: Adam Strange/Future Quest Special
04-Mar-2019 21:31:14 - INFO :: mylar.addComictoDB.179 : Thread-13 : Sucessfully retrieved details for Adam Strange/Future Quest Special

**Comment by evilhero** [comment]
I would think that the 7 minute delay is probably Mylar going thru your search queue since you have it set to search on startup - so that would take priority if it's been x hrs since it last ran.

What's interesting in this is that you started it with the -v switch, yet it seems to not be logging debug levels about midewy thru the log for some reason. There's a significant amoint of logging missing for some reason.

**Comment by Nobrumski** [comment]
If you are referring to the interval settings under web interface, I have NZB search on startup not checked. I also have zero search providers checked. The only on startup option I have marked is to launch the browser that I see. I have never had the search options checked other than to monitor my blackhole as I import my existing collection. 

I will let it run today with debug on. It still sat for 7 minutes again this morning on initial launch. I don't leave it running since it is on a computer that isn't always on and I am only importing stuff when I have time to sit and clean up my existing books.

**Comment by Nobrumski** [comment]
I left it running all day and everything was working fine until I tried to do an import. As soon as I tried to do the import and it went to check this week **pullist** it hung. Now I bolded pullist since that is what the text says, but I doubt the text has anything to do with the issue. Since I am not trying to grab issues and just want to import them manually is there another setting I need to turn off so it isn't trying to search. 

I also pulled the latest update and upon restart turned debugging on that way before this happened again. 

05-Mar-2019 20:45:23 - INFO :: mylar.addComictoDB.413 : Thread-36 : Mass import - Move files
05-Mar-2019 20:45:23 - DEBUG :: mylar.movefiles.18 : Thread-36 : comlocation is : Y:\Mylar2\Marvel\Star Wars Age of Republic Anakin Skywalker (2019)
05-Mar-2019 20:45:23 - DEBUG :: mylar.movefiles.19 : Thread-36 : original comicname is : Star Wars: Age of Republic: Anakin Skywalker
05-Mar-2019 20:45:23 - DEBUG :: mylar.movefiles.40 : Thread-36 : Renaming files not enabled, keeping original filename(s)
05-Mar-2019 20:45:23 - INFO :: mylar.movefiles.43 : Thread-36 : moving Y:\Import\Star Wars - Age of Republic - Anakin Skywalker (2019)\Star Wars - Age of Republic - Anakin Skywalker #01 (Vol.2019).cbz ... to Y:\Mylar2\Marvel\Star Wars Age of Republic Anakin Skywalker (2019)\Star Wars - Age of Republic - Anakin Skywalker #01 (Vol.2019).cbz
05-Mar-2019 20:45:23 - DEBUG :: mylar.movefiles.52 : Thread-36 : all files moved.
05-Mar-2019 20:45:23 - INFO :: mylar.movefiles.56 : Thread-36 : files_moved: [{'srid': '758941', 'import_id': u'36289201', 'filename': u'Star Wars - Age of Republic - Anakin Skywalker #01 (Vol.2019).cbz'}]
05-Mar-2019 20:45:23 - DEBUG :: mylar.addComictoDB.421 : Thread-36 : issue: 1 status before chk :Wanted
05-Mar-2019 20:45:23 - INFO :: mylar.forceRescan.952 : Thread-36 : [FILE-RESCAN] Now checking files for Star Wars: Age of Republic: Anakin Skywalker (2019) in Y:\Mylar2\Marvel\Star Wars Age of Republic Anakin Skywalker (2019)
05-Mar-2019 20:45:23 - INFO :: mylar.traverse_directories.1355 : Thread-36 : there are 1 files.
05-Mar-2019 20:45:23 - DEBUG :: mylar.listFiles.146 : Thread-36 : [FILENAME]: Star Wars - Age of Republic - Anakin Skywalker #01 (Vol.2019).cbz
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.360 : Thread-36 : checking now: Republic
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.392 : Thread-36 : NEWLY SPLIT REORGD: ['Star', 'Wars', '-', 'Age', 'of', 'Republic', '-', 'Anakin', 'Skywalker', '01', 'Vol', '.2019']
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.614 : Thread-36 : volume label detected, but vol. number is not adjacent, adjusting scope to include number.
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.596 : Thread-36 : volume_found: 10
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.606 : Thread-36 : volume label detected as : Volume 2019 @ position: 11
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.740 : Thread-36 : datecheck: []
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.782 : Thread-36 : No year present within title - ignoring as a variable.
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.784 : Thread-36 : highest_series_position: 12
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.790 : Thread-36 : possible_issuenumbers: [{'position': 9, 'validcountchk': False, 'number': '01', 'mod_position': 48}]
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.862 : Thread-36 : issue_position: 9
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.879 : Thread-36 : issue verified as : 01
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.895 : Thread-36 : Volume detected as : v2019
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.987 : Thread-36 : ALT-SERIES NAME [ISSUE TITLE]: Star Wars [Age of Republic - Anakin Skywalker]
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.1003 : Thread-36 : sf_highest_series_pos: ['Star', 'Wars', '-', 'Age', 'of', 'Republic', '-', 'Anakin', 'Skywalker']
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.1035 : Thread-36 : series title possibly: Star Wars - Age of Republic - Anakin Skywalker
05-Mar-2019 20:45:23 - DEBUG :: mylar.parseit.1048 : Thread-36 : Alternate series / issue title: Star Wars [Age of Republic - Anakin Skywalker]
05-Mar-2019 20:45:24 - DEBUG :: mylar.forceRescan.1035 : Thread-36 : No issues with identical issue numbering were detected for this series
05-Mar-2019 20:45:24 - DEBUG :: mylar.forceRescan.1100 : Thread-36 : temploc: 2019
05-Mar-2019 20:45:24 - INFO :: mylar.forceRescan.1506 : Thread-36 : [FILE-RESCAN] Total files located: 0
05-Mar-2019 20:45:24 - DEBUG :: mylar.forceRescan.1613 : Thread-36 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: Star Wars: Age of Republic: Anakin Skywalker
05-Mar-2019 20:45:24 - INFO :: mylar.forceRescan.1615 : Thread-36 : [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 1 ]
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.424 : Thread-36 : issue: 1 status after chk :Wanted
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.426 : Thread-36 : pullupd: None
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.427 : Thread-36 : lastpubdate: Present
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.428 : Thread-36 : series_status: Active
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.433 : Thread-36 : latestissue: #1
05-Mar-2019 20:45:24 - DEBUG :: mylar.addComictoDB.440 : Thread-36 : latestissue status: Wanted
05-Mar-2019 20:45:24 - INFO :: mylar.addComictoDB.442 : Thread-36 : Checking this week pullist for new issues of Star Wars: Age of Republic: Anakin Skywalker
05-Mar-2019 20:52:32 - INFO :: mylar.addComictoDB.470 : Thread-36 : Attempting to grab wanted issues for : Star Wars: Age of Republic: Anakin Skywalker
05-Mar-2019 20:52:32 - DEBUG :: mylar.addComictoDB.473 : Thread-36 : Searching for : 1
05-Mar-2019 20:52:32 - DEBUG :: mylar.addComictoDB.474 : Thread-36 : Status of : Wanted
05-Mar-2019 20:52:32 - WARNING :: mylar.searchforissue.1862 : Thread-36 : There are no search providers enabled atm - not performing an Force Check for obvious reasons
05-Mar-2019 20:52:32 - INFO :: mylar.addComictoDB.478 : Thread-36 : Finished grabbing what I could.
05-Mar-2019 20:52:32 - INFO :: mylar.addComictoDB.504 : Thread-36 : Successfully imported : Star Wars: Age of Republic: Anakin Skywalker

**Comment by Nobrumski** [comment]
It appears turning off Automatically Mark Upcoming Issues as Wanted and Automatically Mark All Issues as Wanted fixes the issue. I am hoping post processing will still move issues that are marked as skipped since I know some programs won't.

I still wonder though if there are no search providers why it doesn't just mark them as wanted and not search once it sees no search options are set.

**Comment by Nobrumski** [comment]
Looks like I spoke too soon. It is currently hung while accessing the pull-list.

05-Mar-2019 23:55:34 - INFO :: mylar.run.27 : Thread-18 : [WEEKLY] Checking Weekly Pull-list for new releases/updates
05-Mar-2019 23:55:34 - INFO :: mylar.pullit.41 : Thread-18 : Weekly pull list present - checking if it's up-to-date..
05-Mar-2019 23:55:34 - INFO :: mylar.pullit.70 : Thread-18 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
05-Mar-2019 23:55:34 - INFO :: mylar.locg.27 : Thread-18 : pulldate is : 00000000
05-Mar-2019 23:55:35 - INFO :: mylar.locg.70 : Thread-18 : [WEEKLY-PULL] There are 88 issues for the week of 09, 2019
05-Mar-2019 23:55:35 - INFO :: mylar.locg.96 : Thread-18 : Re-creating pullist to ensure everything's fresh.
05-Mar-2019 23:55:36 - INFO :: mylar.locg.131 : Thread-18 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 09
05-Mar-2019 23:55:36 - INFO :: mylar.pullit.82 : Thread-18 : [PULL-LIST] Weekly Pull List successfully loaded with 88 issues.
05-Mar-2019 23:55:36 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Adventures of the Super-Sons'}], 'ComicID': u'112561'}
05-Mar-2019 23:55:36 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Belladonna: Fire and Fury'}], 'ComicID': u'106668'}
05-Mar-2019 23:55:36 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Spawn Kills Everyone 2'}], 'ComicID': u'115907'}
05-Mar-2019 23:55:36 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Doctor Aphra'}], 'ComicID': u'96284'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'The Wicked and The Divine'}], 'ComicID': u'74863'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Spider-Man vs. Deadpool'}], 'ComicID': u'87182'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'I Want To Eat Your Pancreas: The Complete Manga Collection'}], 'ComicID': u'116471'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Magi: The Labyrinth of Magic'}], 'ComicID': u'66335'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Robots Versus Princesses'}], 'ComicID': u'112597'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Star Wars: Solo Adaptation'}], 'ComicID': u'114269'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Die! Die! Die!'}], 'ComicID': u'112222'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Stargate Atlantis/Stargate Universe Anthology Ongoing'}], 'ComicID': u'115763'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Mega Ghost'}], 'ComicID': u'115895'}
05-Mar-2019 23:55:37 - INFO :: mylar.LoadAlternateSearchNames.1343 : Thread-18 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Infinity Wars:'}], 'ComicID': u'116253'}

**Comment by evilhero** [comment]
No one else has mentioned anything in regards to being unable to pull from the pullist - which leads me to believe this is, unfortunately isolated to your installation for some reason. There was a fix that went into development last night to address the .HU issue that appears in this week's pullist, although that wouldn't affect anything with regards to the pull unless you had that particular series in your watchlist (otherwise, it just wouldn't show it in the pull).

```I still wonder though if there are no search providers why it doesn't just mark them as wanted and not search once it sees no search options are set.```
Simply because we are not miracle workers, and cannot foresee how every single option will interact with other options until such time as things happen. Some aspects of the code haven't been touched upon in 
 years, and with alot of code changes recently, things might stop working due to those changes.

It also did not start any search whatsoever, but simply called the module to begin the search, indicated that there were no providers enabled and as such terminated any searching - the status would still indicate as Wanted. That search warning would have no impact on anything else thereafter.

**Comment by Nobrumski** [comment]
Yeah I wouldn't be surprised if it had to with my workflow. I probably just had too many episodes marked as wanted causing it to hang. I flipped everything to skipped so hopefully that remedies the issue for me. 

I wasn't criticizing or blaming you so I hope it didn't come across that way. I was more thinking  out loud.
