### ISSUE TITLE
Can't search for anything

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2228]
When searching for a series I am getting the following error

> 500 Internal Server Error

> The server encountered an unexpected condition which prevented it from fulfilling the request.

> Traceback (most recent call last):
>   File "lib/cherrypy/_cprequest.py", line 670, in respond
>     response.body = self.handler()
>  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
>    return self.callable(*self.args, **self.kwargs)
>   File "/usr/local/src/mylar/mylar/webserve.py", line 291, in searchit
>     searchresults = mb.findComic(name, mode, issue=None)
>  File "/usr/local/src/mylar/mylar/mb.py", line 138, in findComic
>     searched = pullsearch(comicapi, comicquery, 0, type)
>  File "/usr/local/src/mylar/mylar/mb.py", line 79, in pullsearch
>     except ExpatError:
> NameError: global name 'ExpatError' is not defined

It has been working fine.  I have rebooted the service as well as the sever to no avail.

**Comment by evilhero** [comment]
ExpatError means there's a problem either with CV returning a response or you even being able to reach CV. 

Check your API key on CV to see if it's gone over the hourly limit, and / or wait like 10-15 mins and try again maybe.

Can you reach comicvine.com from a browser on the same machine as Mylar ?

**Comment by nickv2002** [comment]
Just had this same error. Looks like comic vine is down again. Possibly worth putting in a try/catch block with better error reporting for this?

Thanks for all your work!

**Comment by evilhero** [comment]
@nickv2002 The log above was actually the exception trapping the error, but the exception errored out - it was a user contributed PR that was merged awhile ago, but was never tested as CV was ( at that time at least) not experiencing much downtime.

Looking more into it, looks like the xml.parsers.expat was not imported so it's can't call the exception loop.
