### ISSUE TITLE
My comics weren't downloading for nearly a month and are barely downloading after restart

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2230]
**Describe the bug**
I looked at Sab and Mylar and noticed that I had not downloaded new comics for nearly 30 days. I restarted Mylar and three comics downloaded, and nothing more for 20 minutes now. This also strikes me as odd, given that I have a few hundred titles in Mylar. Subsequent restarts had no effect.

**Screenshots/Logs**
Include a DEBUG log using the log files and do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro, updated
 - Branch / commit: 
Configuration OptionsMylar Version: development-- git build ccf78bb51de42f1448b32163926a7bea1f8e6b68.Python Version : 2.7.14
--

**Additional information**
Add any other information about the problem here.

**Comment by BRTPOB** [comment]
AtariBaby, can you attach your logs for this? That would help troubleshoot this further.

**Comment by AtariBaby** [comment]
[debugmylar.log](https://github.com/evilhero/mylar/files/2948886/debugmylar.log)

**Comment by AtariBaby** [comment]
Wow you're fast! I was just going to attach. That is turning on DEBUG and restarting. Let me know what more I can do.

**Comment by barbequesauce** [comment]
So I’m looking back trying to find the commit you’re on, and can’t find it...

We had some security fixes put in last month, which could very well have broken things for you. Can you get up to date and see if the problem goes away please?

**Comment by BRTPOB** [comment]
We'll really need to wait for evilhero to show up and confirm, but it looks like from your logs that you just didn't find any of the comics you're searching for. I did find 2 different issues though. The first is that you've got newznab setup for a host that's simply http://, which won't work since...that is just the beginning of a URL.

The other is that nzb.cat (whatever that is) was failing to allow the RSS feed to be parsed, so basically you've got the experimental feed working, and you've got dog enabled, but from what I gather dog has been hit or miss recently.

**Comment by AtariBaby** [comment]
Thanks for these parts you guys. I'm glad to see that our evilhero has such capable help these days.

What is the proper way to update these days? And if it's okay to ask, is there a good free option out there to supplement dog? I can of course look into it further myself.

**Comment by BRTPOB** [comment]
Honestly, I have no idea what the best nzb providers are any longer. I was running my own indexer for a while, but everything is so obfuscated to hell it's kind of useless. You can try enabling DDL in options once you get upgraded. If you used git, the easiest way is just "git pull".

**Comment by AtariBaby** [comment]
right, I think that's how I installed it.

**Comment by barbequesauce** [comment]
Or just click “update” in the yellow pop up, bottom right corner... if there isn’t one, click “check for new version” in the bottom right.

**Comment by AtariBaby** [comment]
It said "check successful" and then nothing more happened. Same version listed as above.

**Comment by AtariBaby** [comment]
Uh oh, I did git pull in my mylar directory and now I see this:

**Comment by barbequesauce** [comment]
Navigate to the main page now and you should see the yellow pop up asking you to update. If I remember correctly the error is a transitory thing, you just had bad timing in trying to open a page while a db update was happening...

**Comment by AtariBaby** [comment]
hmm. version is still the same. is development branch still a thing? I did git pull a second time, and it says "already up to date"

**Comment by AtariBaby** [comment]
here's my branch history, never noticed that before:
[88af219][PR] Merge https://github.com/evilhero/mylar {13 minutes ago/ataribaby}
[f837fea] FIX:(#2208) incorrect variable reference when performing duplicate cleanup in post-processing {2 weeks ago/evilhero}
[339281c] Merge branch 'development' {3 weeks ago/evilhero}

**Comment by BRTPOB** [comment]
Wait, what? You merged something? That looks like you did more than just "git pull".

**Comment by barbequesauce** [comment]
Yeah there’s something else going on here, explains why I couldn’t find your commit. Did you fork the repo?

**Comment by AtariBaby** [comment]
not intentionally! i lack the skills to do that AFAIK

**Comment by BRTPOB** [comment]
What command(s) did you run? It might be easier for you to just start over. Backup your mylar.db and config files, then pull a brand new instance of the dev code.

**Comment by AtariBaby** [comment]
okay i do that with "git clone"? before I did "git pull https://github.com/evilhero/mylar"

**Comment by BRTPOB** [comment]
Yeah, git clone is how you make a new copy of the code.

**Comment by AtariBaby** [comment]
Is my config.ini now incompatible?

**Comment by AtariBaby** [comment]
I'm having a weird issue. On mylar/home, all the items there point to an old directory that's not supposed to be used anymore. In the configuration, the new, correct directory is shown as the location. 

Should I a) delete mylar, b) clone again, and c) rebuild the .db file or some other file?

**Comment by AtariBaby** [comment]
sorry for all the trouble

**Comment by barbequesauce** [comment]
No sweat - sorry for the break in responses, life uh gets in the way....

There is a technique to move locations around in the database - @evilhero can provide some details when he gets time.

That said - importing your existing library into a clean dB might be a better approach...

**Comment by evilhero** [comment]
You can try the --maintenance -export option to export your series db into a json file. The on a clean db, run the --maintenance -import option to import that json file. The caveat with this approach is prior to running the import statement, you have to ensure that your destination_dir is set to the new location and your folder format is set as required. If it's done correctly it should pick up your existing structure as being identical to your folder format and scan in your files during the maintenance import. Nice thing about this method is that it won't touch your files, just recreates the dB from the json (it repolls everything from CV)

**Comment by AtariBaby** [comment]
I'm happy to re-do it but there are a few options and i'm not sure how best to go about it.

**Comment by AtariBaby** [comment]
hi evilhero i'll do it! your guys are very nice and super helpful

**Comment by AtariBaby** [comment]
oh sorry, this is command line stuff and works on windows? where do I do this?

**Comment by BRTPOB** [comment]
Yeah, this is all CLI stuff. You'd run this from the Mylar folder using Python, so it would be python Mylar.py --maintenance -export on the old DB, then on a brand new one you'd run python Mylar.py --maintenance -import.

**Comment by AtariBaby** [comment]
haha i predict i'll fuck this up but i'm going for it :p

**Comment by AtariBaby** [comment]
do i need to start with a clean install again? i already used the scan and "add to wanted" features. although again, i seem to have only downloaded about a dozen comics from yesterday.

**Comment by BRTPOB** [comment]
no, if you just remove/rename the mylar.db (with Mylar shut down) that would suffice.

**Comment by AtariBaby** [comment]
lots of problems guys. it rebukes me that i need to use "maintenance" and not "--maintenance" and it doesn't recognize the word export. does mylar need to be running?

**Comment by AtariBaby** [comment]
```
usage: Mylar.py [-h] [-v] [-q] [-d] [-p PORT] [-b] [-w] [--datadir DATADIR]
                [--config CONFIG] [--nolaunch] [--pidfile PIDFILE] [--safe]
                {maintenance} ...
```

**Comment by evilhero** [comment]
```python Mylar.py maintenance --help
log language set to en_CA
usage: Mylar.py maintenance [-h] [-xj EXPORTJSON] [-id IMPORTDATABASE]
                            [-ij IMPORTJSON] [-st] [-u] [-fs]

optional arguments:
  -h, --help            show this help message and exit
  -xj EXPORTJSON, --exportjson EXPORTJSON
                        Export existing mylar.db to json file
  -id IMPORTDATABASE, --importdatabase IMPORTDATABASE
                        Import a mylar.db into current db
  -ij IMPORTJSON, --importjson IMPORTJSON
                        Import a specified json file containing just
                        {"ComicID": "XXXXX"} into current db
  -st, --importstatus   Provide current maintenance status
  -u, --update          force mylar to perform an update as if in GUI
  -fs, --fixslashes     remove double-slashes from within paths in db```

Remember to specify the .json file when doing the actual command ```python Mylar.py maintenance --exportjson  export.json``` as well as with the importjson command.

It will lock up the session as it performs the command (mylar cant be running for obvious reasons) - however you can use the status switch and it will show you how many items it has left to process and what it's currently on (if I recall correctly). The ideal way is to initiate the importjson command using screen so you don't lock up your cli - and then you can query the job with the status switch to see how it's going.

**Comment by AtariBaby** [comment]
okay i'll try that command! thanks

**Comment by evilhero** [comment]
The exportjson command should only take a few seconds, the importjson command however will take much longer depending on your watchlist size.

**Comment by AtariBaby** [comment]
Hi so I entered `Mylar.py maintenance [-h] [-xj EXPORTJSON] [-id IMPORTDATABASE]
                            [-ij IMPORTJSON] [-st] [-u] [-fs]` and got another error 

`c:\mylar>Mylar.py maintenance [-h] [-xj EXPORTJSON] [-id IMPORTDATABASE]
log language set to en_US
usage: Mylar.py [-h] [-v] [-q] [-d] [-p PORT] [-b] [-w] [--datadir DATADIR]
                [--config CONFIG] [--nolaunch] [--pidfile PIDFILE] [--safe]
                {maintenance} ...
Mylar.py: error: unrecognized arguments: [-h] [-xj EXPORTJSON] [-id IMPORTDATABASE]`

**Comment by evilhero** [comment]
Lol that's the help command you just pasted back. You have to call mylar using any of those arguments, like ```python Mylar.py maintenance --exportjson export.json```

**Comment by AtariBaby** [comment]
sorry! okay going in

**Comment by AtariBaby** [comment]
I did the export. I deleted the db file. Now I can’t get Mylar to start

**Comment by BRTPOB** [comment]
What is the error you're getting?

**Comment by AtariBaby** [comment]
it's not starting by anyway i know how to start it. webpages say "site can't be reached" now

**Comment by BRTPOB** [comment]
What command are you using to run Mylar?

**Comment by AtariBaby** [comment]
double-clicking mylar.py, or typing python mylar.py

**Comment by BRTPOB** [comment]
ok, if you run it in the console (which you should), what is the error that's being thrown when you try to type in python Mylar.py?

**Comment by AtariBaby** [comment]
there's no error. just hit enter and then you have a new c: prompt

**Comment by BRTPOB** [comment]
that means it's not running for some reason. Try doing python Mylar.py --daemon

**Comment by AtariBaby** [comment]
same thing: just a new prompt

**Comment by BRTPOB** [comment]
OK, I don't understand why Mylar isn't running for you. Have you changed your Python pathing at all?

**Comment by AtariBaby** [comment]
no, i changed nothing. i'm doing this in command prompt just to be clear. but i've never had it stop working like this before

**Comment by AtariBaby** [comment]
install from scratch?

**Comment by barbequesauce** [comment]
so... you're in a command prompt and you've changed directory to the mylar folder, right?

Then you're typing "python Mylar.py" ?

and there's no screen output?

**Comment by AtariBaby** [comment]
![9E58795D-B670-4E20-886F-02B21DFE3318](https://user-images.githubusercontent.com/97095/54214971-63ba7480-44a4-11e9-883c-11737c11205c.jpeg)

**Comment by evilhero** [comment]
What does typing just ```python``` on the command prompt return ?

**Comment by AtariBaby** [comment]
`C:\mylar>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

**Comment by AtariBaby** [comment]
lol interestingly i'm on intel and windows 64 but that's neither here nor there

**Comment by AtariBaby** [comment]
You may be on to something. Mylar.py is 0 KB, that's right is it?
![Screen Shot 2019-03-12 at 10 02 11 AM](https://user-images.githubusercontent.com/97095/54221212-49869380-44b0-11e9-8d62-95a8243bf82c.jpg)

**Comment by BRTPOB** [comment]
No, that's not right. Means you somehow wiped your entire Mylar file out. You need to re-pull it.

**Comment by AtariBaby** [comment]
should i just pull the whole thing? or just the mylar.py?

**Comment by BRTPOB** [comment]
Just try to pull the entire thing down again.

**Comment by AtariBaby** [comment]
oh i got mylar.py from my backup

**Comment by BRTPOB** [comment]
Unless that backup is from this new instance that you recently pulled down, it is not going to work and if you try to use it it's going to cause even more problems for you.

**Comment by AtariBaby** [comment]
lol thanks for being patient with me. i did the "git pull". will the import command still work?

**Comment by BRTPOB** [comment]
It should, yes, but let's not worry about that. Let's make sure that you can actually *run* Mylar first.

**Comment by AtariBaby** [comment]
it runs. the mylar.py is 15KB from 9/18/2018 does that sound right?

i have shut it back down. should i put in my config.ini and try the import command? can anyone tell me exactly what that command is?

**Comment by BRTPOB** [comment]
Uh not if it's Development or Master, no. That file is wildly out of date.

**Comment by AtariBaby** [comment]
augh! can't believe i've managed to catastrophically mess this up over days. what should I do?

**Comment by BRTPOB** [comment]
Nuke it. Delete the folder, start over.

**Comment by AtariBaby** [comment]
Okay so sorry

**Comment by BRTPOB** [comment]
Honestly don't apologize, as long as the issue gets resolved it's fine.

**Comment by AtariBaby** [comment]
let me just try to list this out:
delete mylar
new instance
confirm starts
shut down
paste config.ini and mylar.db from before
Run exportjson command from above
delete mylar.db
run import command (please supply command so i don't screw it up)
hopefully enjoy mylar again lol

**Comment by evilhero** [comment]
That's the correct sequence to do things in, yes.

export command: ```python Mylar.py maintenance --exportjson export.json```

import command: ```python Mylar.py maintenance --importjson export.json```

Keep the import command window open until it's finished, and you'll get a completed message in display to indicate that it's finished.

**Comment by AtariBaby** [comment]
<iframe src="https://giphy.com/embed/c1bCgiMFrFLSHEA74B" width="480" height="250" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/high-quality-highqualitygifs-c1bCgiMFrFLSHEA74B">via GIPHY</a></p>

**Comment by AtariBaby** [comment]
![hw9pfmapvrn01](https://user-images.githubusercontent.com/97095/54316881-f9d2c580-459e-11e9-8398-a0abb839d24e.gif)

**Comment by BRTPOB** [comment]
...what exactly are you trying to tell us?

**Comment by AtariBaby** [comment]
Lol sorry. I mean to say that I am powerful like Thanos because Mylar is working now. My follow up post didn’t show up for some reason.

What is the best way now to force it to recent Carmax and get me all the ones I haven’t downloaded in recent weeks?

THANK YOU ALL

**Comment by AtariBaby** [comment]
AH WAIT NO. It's downloading to the old location. the new location was definitely in config.ini. Did the export / import carry the old location over, after all?

**Comment by AtariBaby** [comment]
Do I need to replace comicsrn.py maybe? Those are in a separate scripts folder on the pc

**Comment by evilhero** [comment]
The ComicRN script has nothing to do with the importjson - you started from a clean db, so whatever you had in your config.ini is what it used during the importjson process (all it knew with the json is the comicid's, nothing else whatsoever, no files, no locations, nodda). 

So make sure you set the download location properly in your download clients (or if you specify a download location in a download directory option within Mylar for sabnzbd/nzbget/torrent client/etc).

The destination_dir config.ini variable is where your default comic locations got set to. If that was wrong, then every series it imported was wrong as well. You can check - go to the series detail page for a given series - it will say the Directory where it expects to find things. If that's wrong, then you need to make sure your config.ini is pointing to the correct location, and probably do the importjson all over again.

**Comment by AtariBaby** [comment]
well in sab, comicrn is selected and folder/path is blank.
in mylar/config.ini, the new directory is the one in there. 
If I go to older comics details in mylar, the old location is there.
If I add a new comic in mylar, the new location is there.
I guess I could go through this process one more time, as it will be a great headache to change hundreds of titles in the web interface.

**Comment by AtariBaby** [comment]
Oh wow, now we're golden! I must have tripped over my feet during my previous attempt. This time, everything seems to be in the new location, and mylar did not attempt to recreate the old location. Whew.

I was watching the import process and I saw it ended with errors. It may be unimportant but thought you might want to see:
`14-Mar-2019 21:18:29 - WARNING :: mylar.pullsearch.74 : MAIN : Error fetching data from ComicVine: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
14-Mar-2019 21:18:29 - ERROR :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 348, in <module>
    main()
  File "Mylar.py", line 251, in main
    j = ij.json_import()
  File "C:\mylar\mylar\maintenance.py", line 72, in json_import
    self.importIT()
  File "C:\mylar\mylar\maintenance.py", line 161, in importIT
    maintenance_info = importer.addComictoDB(re.sub('4050-', '', x['ComicID']).strip(), calledfrom='maintenance')
  File "C:\mylar\mylar\importer.py", line 344, in addComictoDB
    updateddata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
  File "C:\mylar\mylar\importer.py", line 1077, in updateissuedata
    annualchk = annual_check(comicname, SeriesYear, comicid, issuetype, issuechk, annualchk)
  File "C:\mylar\mylar\importer.py", line 1465, in annual_check
    if len(sresults) > 0:
TypeError: object of type 'bool' has no len()

Traceback (most recent call last):
  File "Mylar.py", line 348, in <module>
    main()
  File "Mylar.py", line 251, in main
    j = ij.json_import()
  File "C:\mylar\mylar\maintenance.py", line 72, in json_import
    self.importIT()
  File "C:\mylar\mylar\maintenance.py", line 161, in importIT
    maintenance_info = importer.addComictoDB(re.sub('4050-', '', x['ComicID']).strip(), calledfrom='maintenance')
  File "C:\mylar\mylar\importer.py", line 344, in addComictoDB
    updateddata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
  File "C:\mylar\mylar\importer.py", line 1077, in updateissuedata
    annualchk = annual_check(comicname, SeriesYear, comicid, issuetype, issuechk, annualchk)
  File "C:\mylar\mylar\importer.py", line 1465, in annual_check
    if len(sresults) > 0:
TypeError: object of type 'bool' has no len()`
