### ISSUE TITLE
Issue code, 'HU' not recognized

### ISSUE THREAD

**Issue by idledae** [evilhero/mylar#2233]
**Describe the bug**
It seems the latest issue of "The Amazing Spider-Man" (2018) has an issue code that isn't recognized in Mylar and is causing an error and subsequently, comic information loading loops.

**Environment (please complete the following information):**
 - Windows 10
 - Branch / commit: master/f837fea36114c5bdb7d0b1e2647ad335d270a1c5

![image](https://user-images.githubusercontent.com/1676108/54090650-b4b75500-434c-11e9-8573-ad6ef4aac432.png)
[snippet-mylar.log](https://github.com/evilhero/mylar/files/2949970/snippet-mylar.log)

**Comment by barbequesauce** [comment]
The fix for this is in development at this point; it should be merged in the near future.

**Comment by evilhero** [comment]
The fix for this problem has now been merged into master as of yesterday.

**Comment by idledae** [comment]
awesome! confirmed working
