### ISSUE TITLE
Issue count not updating

### ISSUE THREAD

**Issue by BanditTech** [evilhero/mylar#2236]
**Describe the bug**
issue count got stuck at a value and will not update.
refreshed page, even marked all as wanted and rescan. restart everything.. will not update the number even though I have all of them. just seemed to happen to Deadly Class only so far.

**Screenshots/Logs**
![Capture](https://user-images.githubusercontent.com/13251996/54286256-b48fa300-4560-11e9-9bd1-60823f1770a0.PNG)

**Environment (please complete the following information):**
 - windows 10
 - dev branch

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Needs debug logs to help more. Screenshot only doesn't help much as it's really difficult to recreate the problem on our end just from that one item.
