### ISSUE TITLE
Can't add comics after updates

### ISSUE THREAD

**Issue by Bussterj** [evilhero/mylar#2237]
After updating from a release I downloaded 29/11/18 I can no longer add any series to my library. After downgrading I can continue fine.
Here is the error I get in my logs

Please advise

[mylar.log](https://github.com/evilhero/mylar/files/2963018/mylar.log)

**Comment by evilhero** [comment]
Please follow the template when filling out an issue, otherwise it will be a while before an actual response is received.

**Comment by evilhero** [comment]
Your Comic Location path has a directory slash in it going the wrong way (windows directory slashes should all go ```\```,  not ```/```)

**Comment by Bussterj** [comment]
Sorry for not following the template!
It was the Folder Format that had the / in it!
Fixed and working again :)
