### ISSUE TITLE
[Enhancement Request] Issue Number

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#2240]
Not sure if ComicVine provides this information, but it'd be great if the metadata pulled would include the issue number of the issue as well as the series. I currently use Calibre to organize and read my comics, and I generally have to manually update the issue numbers. Not the end of the world! But it'd be awesome to have. Thanks for all the great work!

**Comment by evilhero** [comment]
I'm not sure if I follow - mylar uses CT to get the metadata into the cbz file. So as long as you enable metatagging within Mylar, when it post-processes an issue it will metatag the issue with all the relevant information - issue number and series are obviously in there as well in addition to a ton of other information. 

Does calibre not read the cbz file metadata within the file?

**Comment by silentArtifact** [comment]
It does read the metadata, but issues imported all share the same issue number, for whatever reason. Maybe this is a calibre issue, then, not a mylar issue.

In fact, re-reading the metadata in one of the most recently tagged issues, it does have the correct number, but calibre didn't read it. I'm guessing Calibre isn't looking for "issue" as a term, if I had to bet.
