### ISSUE TITLE
[Enhancement Request] Mass folder path replace/update

### ISSUE THREAD

**Issue by Bussterj** [evilhero/mylar#2241]
Hi is there any way of changing all my folder paths at once either updating all to the default path or some kind of find replace system? I've had a look but couldn't find a way of doing it without going into each one. I tried searching mylar files to see if I could do anything in Wordpad but couldn't find where the paths are stored. I had to move my files to a new drive as they were too big and I don't fancy manually changing 450+ paths manually.
Look forward to your reply and keep up the good work

**Comment by evilhero** [comment]
This is already present in Mylar - but it's a few hidden config.ini options that need to be enabled/altered as it's not something that is used normally.

You can find instructions on how to use it here: [here](https://forum.mylarcomics.com/viewtopic.php?f=12&t=601&sid=bea95e783df1cd3baa9daeab1a2002c2#p2889).

The key to the whole process is to not change your Comic Location path from the old setting until after the above process has successfully completed - then change it to the new location.

**Comment by Bussterj** [comment]
Thanks but the forum has banned my IP?

**Comment by evilhero** [comment]
Probably because your IP is either in a range that a spammer used. Can you pass me the IP - minus the 4th octet and I'll add remove the offending entry?

**Comment by Bussterj** [comment]
31.127.62.
Thanks

**Comment by evilhero** [comment]
k, try it again.

**Comment by Bussterj** [comment]
That seems to have to done the trick many thanks :)
I knew there would be a way 👍
