### ISSUE TITLE
Can't search or download

### ISSUE THREAD

**Issue by wiswtf** [evilhero/mylar#2249]
Hi.

Running Mylar on my RPi3 with Dietpi as my OS and jackett serving me torznab api for WWT with the Nem comics category.

Now, I also have Public search and DDL on, but it just won't seem to search or download. I get this error in the logs:

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/helpers.py", line 3144, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/opt/Mylar/mylar/search.py", line 1855, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 359, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 669, in NZB_SEARCH
bb = ww.wwt_connect()
File "/opt/Mylar/mylar/wwt.py", line 57, in wwt_connect
soup = BeautifulSoup(r.content, "html5lib")
File "/opt/Mylar/lib/bs4/__init__.py", line 165, in __init__
% ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

What should I do?

**Comment by barbequesauce** [comment]
Why are you putting Jackett in the mix? Mylar supports WWT directly.

That said - as the error says, install html5lib. For Raspbian that’s as simple as `sudo pip install html5lib`; I’d expect the same for DietPi....

**Comment by WiseMMO** [comment]
> Why are you putting Jackett in the mix? Mylar supports WWT directly.
> 
> That said - as the error says, install html5lib. For Raspbian that’s as simple as `sudo pip install html5lib`; I’d expect the same for DietPi....

Thank you. I will try it out.
I put Jackett into the mix simply because in the past I've had issues with search providers already inside downloaderrs and Jackett has always proven to be the most stable... do you think I could disable it?

**Comment by barbequesauce** [comment]
I would recommend removing Jackett from the equation, yes.

**Comment by WiseMMO** [comment]
I must find another way to install that lib, as I don't think I can use pip on dietpi and a simple apt-get doesn't find it. I will remove Jackett, thank you

**Comment by WiseMMO** [comment]
Turns out I can install python-pip from the dietpi software interface, I will test out if this fixed the problem!
