### ISSUE TITLE
Errors when SabNZBD is on separate (Windows) machine

### ISSUE THREAD

**Issue by hugo-vrijswijk** [evilhero/mylar#2250]
**Describe the bug**
I am having an issue when running SabNZBD on a raspberry pi (Docker) with SabNZBD on a separate machine. The configuration for sab is set to a separate machine, with the download directory being set to a windows path (`D:\Downloads`).

When trying to add a comic, the following errors are logged. The comic summary screen will also have no information and continually refresh:

```
04-Apr-2019 22:50:57 - ERROR   :: mylar.folder_create.118 : Thread-13 : [ERROR] 'NoneType' object has no attribute 'ends
with'
04-Apr-2019 22:50:57 - ERROR   :: mylar.folder_create.119 : Thread-13 : Cannot determine Comic Location path properly. C
heck your Comic Location and Folder Format for any errors.
04-Apr-2019 22:50:57 - ERROR   :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call las
t):
  File "/app/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/importer.py", line 222, in addComictoDB
    if os.path.isdir(comlocation):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
 
04-Apr-2019 22:51:20 - WARNING :: mylar.havetotals.1408 : CP Server Thread-4 : Comic ID: 115777 has not finished loading
. Nulling some values so things display properly until they can populate.
```

**Environment (please complete the following information):**
 - OS: Raspbian (Docker)
 - tag: pyouroboros/ouroboros:latest

**Comment by evilhero** [comment]
You need to specify a comic location path prior to running mylar (check the readme.md for information).

The download path for sab within mylar  must be accessible by both instances.
