### ISSUE TITLE
Cloudflare Errors on WWT

### ISSUE THREAD

**Issue by davalanche** [evilhero/mylar#2266]
During my testing of #2265 I was encountering Cloudflare related errors on WWT.

I updated cfscrape from 1.9.5 to 1.9.7 locally but there was no improvement.

I tracked down Anorov/cloudflare-scrape#206, which appears to work, and am using it as a workaround until the cfscrape library sees an official update and that is merged in.

Just thought I'd note this for anyone else having issues.

Thanks.

**Comment by geezer500** [comment]
What did you do for the fix/workaround?

**Comment by davalanche** [comment]
I copied cfscrape/__init__.py from lukele:update-challenge-solver into my local cfscrape directory.

It looks like some are switching their applications to use VeNoMouS/cloudscraper..

**Comment by geezer500** [comment]
Thanks...

I had seen VeNoMouS/cloudscraper link, and was a little unsure as to what you were referring to..
I have tried the cfscrape/__init__.py you linked, but it has made no difference for me.

I run Mylar in a docker container, So I assume that there is an issue with the container itself (although everything else works).
