### ISSUE TITLE
Exportjson Synology package to docker

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#2270]
Hello,
I’ve been a real happy mylar user for some years now but i have finally decided to move from syno package community setup to docker setup.
Unfortunately all my comics are for the moment on /volume1/Comics and on the docker i would like to link this volume to /comics
I know i could just use -v /volume1/Comics/:/volume1/Comics/ when running the docker and just be done with it (as well as copying over config and db files) but i think it would be neater with /comics
So i’ve seen some thread and decided to try python Mylar.py maintenance --exportjson whatever.json.
When i type this commande from the Mylar.py folder i get the following result in SSH in synology :
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/volume1/@appstore/mylar/share/mylar/mylar/__init__.py", line 36, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "lib/apscheduler/schedulers/base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

Any help is appreciated on how to proceed to move over my db (it is quite huge so i would prefer having to reimport all manually)

**Comment by barbequesauce** [comment]
pkg_resources is part of setup tools, not Mylar. If you can, try `pip uninstall -y setuptools ; pip install setuptools`

**Comment by yongbi85** [comment]
I will try this, but as it is on a Synology I’m not sure pip will work…Any risk in trying this ?
And also any other possibility ? even with a SQL lite DB tool and using update on some fields ?
If i know which fields to update i could just do an udate and string replacement

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : barbequesauce <notifications@github.com>
Envoyé : Thursday, May 2, 2019 7:48:35 PM
À : evilhero/mylar
Cc : yongbi85; Author
Objet : Re: [evilhero/mylar] Exportjson Synology package to docker (#2270)


pkg_resources is part of setup tools, not Mylar. If you can, try pip uninstall -y setuptools ; pip install setuptools

**Comment by barbequesauce** [comment]
yeah Synology is always a problem (as is docker, fwiw).

Maybe @evilhero has an idea on other ways to export/import?

**Comment by evilhero** [comment]
You'd have to edit the comics.ComicLocation path for each entry therein, as well as the annuals.ComicLocation of you have annuals integration enabled. There might be other places, but those are the two main ones.

As well you'd have to ensure that your Comic Location path in the GUI is pointing to the correct location so subsequent adds will be created in the proper pathing.

**Comment by yongbi85** [comment]
Thanks actually needed to do comics.ComicLocation and storyarc.Location
just did an update and set replace, seems to have worked like a charm :p
