### ISSUE TITLE
32P + Graphic Novels/One Shots - Mylar never matches.

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#2273]
So, this has finally annoyed me enough that I am raising an issue. Basically I have never ever got this to work. Let's take My Favorite Thing is Monsters. 32p series id is 20304.

06-May-2019 16:33:54 - INFO    :: mylar.queueissue.1473 : Thread-37 : [WANTED-SEARCH] Now Queueing My Favorite Thing Is Monsters (2017) #1 for search
06-May-2019 16:34:09 - DEBUG   :: mylar.search_init.426 : SEARCH-QUEUE : findit: {'status': False}
06-May-2019 16:34:09 - INFO    :: mylar.search_init.430 : SEARCH-QUEUE : Finished searching via : api. Issue not found - status kept as Wanted.
06-May-2019 16:34:14 - INFO    :: mylar.search_queue.3142 : SEARCH-QUEUE : [SEARCH-QUEUE] Now loading item from search queue: {'comicname': u'My Favorite Thing Is Monsters', 'issueid': u'581502', 'seriesyear': u'2017', 'booktype': u'One-Shot', 'issuenumber': u'1', 'comicid': u'98917'}
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.63 : SEARCH-QUEUE : Publisher is : Fantagraphics
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.71 : SEARCH-QUEUE : Issue Title given as : vol. 1
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.102 : SEARCH-QUEUE : Checking for torrent enabled.
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.153 : SEARCH-QUEUE : nzbprovider(s): []
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.156 : SEARCH-QUEUE : There are 1 torrent providers you have selected.
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.161 : SEARCH-QUEUE : There are : 0 nzb providers you have selected
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.180 : SEARCH-QUEUE : search provider order is ['32p']
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.247 : SEARCH-QUEUE : calpha/cnumber: None / None
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.283 : SEARCH-QUEUE : Initiating Search via : rss
06-May-2019 16:34:14 - INFO    :: mylar.NZB_SEARCH.504 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for My Favorite Thing Is Monsters (2017) using 32P [RSS].
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.577 : SEARCH-QUEUE : findloop: 0 / findcount: 1
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.633 : SEARCH-QUEUE : Sending request to [32P] RSS for My Favorite Thing Is Monsters :
06-May-2019 16:34:14 - DEBUG   :: mylar.torrentdbsearch.731 : SEARCH-QUEUE : no Alternate name given. Aborting search.
06-May-2019 16:34:14 - INFO    :: mylar.search_init.393 : SEARCH-QUEUE : Could not find My Favorite Thing Is Monsters (2017) using 32P [rss]
06-May-2019 16:34:14 - INFO    :: mylar.NZB_SEARCH.513 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for My Favorite Thing Is Monsters issue: 02-15 (2017) using 32P [RSS].
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.577 : SEARCH-QUEUE : findloop: 0 / findcount: 1
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.633 : SEARCH-QUEUE : Sending request to [32P] RSS for My Favorite Thing Is Monsters : 2017-02-15
06-May-2019 16:34:14 - DEBUG   :: mylar.torrentdbsearch.731 : SEARCH-QUEUE : no Alternate name given. Aborting search.
06-May-2019 16:34:14 - INFO    :: mylar.search_init.393 : SEARCH-QUEUE : Could not find My Favorite Thing Is Monsters (2017) using 32P [rss]
06-May-2019 16:34:14 - INFO    :: mylar.NZB_SEARCH.513 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for My Favorite Thing Is Monsters issue: 02-15 (2017) using 32P [RSS].
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.577 : SEARCH-QUEUE : findloop: 0 / findcount: 1
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.633 : SEARCH-QUEUE : Sending request to [32P] RSS for My Favorite Thing Is Monsters : 2017-02-15
06-May-2019 16:34:14 - DEBUG   :: mylar.torrentdbsearch.731 : SEARCH-QUEUE : no Alternate name given. Aborting search.
06-May-2019 16:34:14 - INFO    :: mylar.search_init.393 : SEARCH-QUEUE : Could not find My Favorite Thing Is Monsters (2017) using 32P [rss]
06-May-2019 16:34:14 - INFO    :: mylar.NZB_SEARCH.513 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for My Favorite Thing Is Monsters issue: 02-15 (2017) using 32P [RSS].
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.577 : SEARCH-QUEUE : findloop: 0 / findcount: 1
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.633 : SEARCH-QUEUE : Sending request to [32P] RSS for My Favorite Thing Is Monsters : 2017-02-15
06-May-2019 16:34:14 - DEBUG   :: mylar.torrentdbsearch.731 : SEARCH-QUEUE : no Alternate name given. Aborting search.
06-May-2019 16:34:14 - INFO    :: mylar.search_init.393 : SEARCH-QUEUE : Could not find My Favorite Thing Is Monsters (2017) using 32P [rss]
06-May-2019 16:34:14 - DEBUG   :: mylar.search_init.283 : SEARCH-QUEUE : Initiating Search via : api
06-May-2019 16:34:14 - INFO    :: mylar.NZB_SEARCH.504 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for My Favorite Thing Is Monsters (2017) using 32P.
06-May-2019 16:34:14 - DEBUG   :: mylar.NZB_SEARCH.577 : SEARCH-QUEUE : findloop: 0 / findcount: 1
06-May-2019 16:34:14 - DEBUG   :: mylar.__init__.463 : SEARCH-QUEUE : [32P-AUTHENTICATION] Session cookie found. Attempting to load...
06-May-2019 16:34:14 - DEBUG   :: mylar.valid_skey_attempt.548 : SEARCH-QUEUE : inkdrops: {u'status': u'success', u'results': [{u'inkdrops': u'8021658.7282', u'userid': 21838}]}
06-May-2019 16:34:14 - DEBUG   :: mylar.login.666 : SEARCH-QUEUE : [32P-AUTHENTICATION] Session key-based login was good.
06-May-2019 16:34:14 - DEBUG   :: mylar.__init__.68 : SEARCH-QUEUE : [32P-AUTHENTICATION] [LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
06-May-2019 16:34:14 - DEBUG   :: mylar.searchit.335 : SEARCH-QUEUE : 1 series match the tile being searched for on 32P...
06-May-2019 16:34:14 - DEBUG   :: mylar.searchit.364 : SEARCH-QUEUE : payload: {u'action': u'groupsearch', u'issue': None, u'id': u'20304'}
06-May-2019 16:34:16 - DEBUG   :: mylar.searchit.401 : SEARCH-QUEUE : 32P did not return any valid search results.
06-May-2019 16:34:16 - INFO    :: mylar.search_init.393 : SEARCH-QUEUE : Could not find My Favorite Thing Is Monsters (2017) using 32P [api]

Ubuntu 16.04
Mylar Version: development
-- git build f1e8702d34b268db120f5454cd6fe88f6a4a621a.
Python Version : 2.7.12

I can download the issue manually but then the file name matcher won't work. I have found this with every GN/Collection/One Shot I have ever tried to find.

**Comment by evilhero** [comment]
32p doesn't allow for one-shot/GN/TPB proper matching due to how their system is.

I have something done that will address the matching of these issues, but it's not ready as of yet for primetime, as it's a different method of searching 32p than currently in the program. 

There's no reason why the parser wouldn't match if you manually download the issue. The series name has to match to the filename, and the edition within Mylar has to be indicated as a One-Shot or TPB format, for filenames to match that have no issue number. Odds are the files are stupidly named. 

Get the file parser debug log for one of the ones that don't match and I can see what's going on in regards to the parser.

**Comment by Lusiphur** [comment]
Actually, this time, the file parser got it which was a bit of a surprise. Usually that requires a lot of rename ‘/s//‘ and searing on my part.

Right, issue answered and I will await the new feature. Thanks as always for the prompt support.
