### ISSUE TITLE
Recurrence of issue 809 - batwoman issue 0 detected as duplicate

### ISSUE THREAD

**Issue by samsonious** [evilhero/mylar#2274]
This issue seems to have been reintroduced at some point in the 5 years since the fix went in. Scanning just returns a duplicate issue detected

2019-05-09 12:50:21 | DEBUG | [DUPECHECK] Duplicate issue detected [Batwoman 0 (2012).cbr] [Batwoman 0 (2011).cbz] 

Is there any way to force the matching to avoid this? Similar to how you can add a comic using the comicid?

**Comment by evilhero** [comment]
Can you please post debug logs showing the lead up to that line ?

**Comment by samsonious** [comment]
09-May-2019 12:50:16 - DEBUG   :: mylar.forceRescan.1038 : Thread-165 : Multiple issues with identical numbering were detected. Attempting to accomodate.
09-May-2019 12:50:17 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 6
09-May-2019 12:50:17 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [314712] Issue match - fcdigit: 6000 ... int_iss: 6000
09-May-2019 12:50:17 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#6 --- 6000
09-May-2019 12:50:17 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 6 (2012).cbr
09-May-2019 12:50:17 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 28475403
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 30
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [450509] Issue match - fcdigit: 30000 ... int_iss: 30000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#30 --- 30000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 30 (2014).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 37440732
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 11
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [346226] Issue match - fcdigit: 11000 ... int_iss: 11000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#11 --- 11000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 11 (2012).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 29034616
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 21
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [411786] Issue match - fcdigit: 21000 ... int_iss: 21000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#21 --- 21000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 21 (2013).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 40102195
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 0
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [246454] Issue match - fcdigit: 0 ... int_iss: 0
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1157 : Thread-165 : [FILE-RESCAN] IssueID matches to multiple issues : 246454. Checking dupe.
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1158 : Thread-165 : [FILE-RESCAN] miISSUEYEAR: 2011 -- issyear : 2011
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1168 : Thread-165 : [FILE-RESCAN] Did not match to year within filename : 2011
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [357623] Issue match - fcdigit: 0 ... int_iss: 0
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1157 : Thread-165 : [FILE-RESCAN] IssueID matches to multiple issues : 357623. Checking dupe.
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1158 : Thread-165 : [FILE-RESCAN] miISSUEYEAR: 2012 -- issyear : 2012
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1164 : Thread-165 : [FILE-RESCAN] Matched to year within filename : 2012
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#0 --- 0
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 0 (2012).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 27419561
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 26
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [440195] Issue match - fcdigit: 26000 ... int_iss: 26000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#26 --- 26000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 26 (2014).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 33000593
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 35
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [468019] Issue match - fcdigit: 35000 ... int_iss: 35000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#35 --- 35000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 35 (2014).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 40804165
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 2
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [294821] Issue match - fcdigit: 2000 ... int_iss: 2000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#2 --- 2000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 2 (2011).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 29495859
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 16
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [381381] Issue match - fcdigit: 16000 ... int_iss: 16000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#16 --- 16000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 16 (2013).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 30149061
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 37
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [473586] Issue match - fcdigit: 37000 ... int_iss: 37000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#37 --- 37000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 37 (2015).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 28721671
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 27
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [442871] Issue match - fcdigit: 27000 ... int_iss: 27000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#27 --- 27000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 27 (2014).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 40929163
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 9
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [335899] Issue match - fcdigit: 9000 ... int_iss: 9000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#9 --- 9000
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 9 (2012).cbr
09-May-2019 12:50:18 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 27111538
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 22
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [417792] Issue match - fcdigit: 22000 ... int_iss: 22000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#22 --- 22000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 22 (2013).cbr
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 33721921
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 34
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [462848] Issue match - fcdigit: 34000 ... int_iss: 34000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#34 --- 34000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 34 (2014).cbr
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 31251604
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 3
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [301648] Issue match - fcdigit: 3000 ... int_iss: 3000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#3 --- 3000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 3 (2012).cbr
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 29636739
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 12
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [350901] Issue match - fcdigit: 12000 ... int_iss: 12000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#12 --- 12000
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 12 (2012).cbr
09-May-2019 12:50:19 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 31865804
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 17
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [387212] Issue match - fcdigit: 17000 ... int_iss: 17000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#17 --- 17000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 17 (2013).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 30627157
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 23
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [422433] Issue match - fcdigit: 23000 ... int_iss: 23000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#23 --- 23000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 23 (2013).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 34521734
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 18
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [394649] Issue match - fcdigit: 18000 ... int_iss: 18000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#18 --- 18000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 18 (2013).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 30600728
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 38
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [476742] Issue match - fcdigit: 38000 ... int_iss: 38000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#38 --- 38000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 38 (2015).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 39704648
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 29
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [447949] Issue match - fcdigit: 29000 ... int_iss: 29000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#29 --- 29000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 29 (2014).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 34659536
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 13
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [362160] Issue match - fcdigit: 13000 ... int_iss: 13000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#13 --- 13000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 13 (2012).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 30971199
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 33
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [459627] Issue match - fcdigit: 33000 ... int_iss: 33000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#33 --- 33000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 33 (2014).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 34179098
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 7
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [321189] Issue match - fcdigit: 7000 ... int_iss: 7000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#7 --- 7000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 7 (2012).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 33782332
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 5
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [310752] Issue match - fcdigit: 5000 ... int_iss: 5000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#5 --- 5000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 5 (2012).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 26632510
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 1
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [292565] Issue match - fcdigit: 1000 ... int_iss: 1000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#1 --- 1000
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 1 (2011).cbr
09-May-2019 12:50:20 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 32522157
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 15
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [373260] Issue match - fcdigit: 15000 ... int_iss: 15000
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1233 : Thread-165 : [FILE-RESCAN] Matched...issue: Batwoman#15 --- 15000
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1238 : Thread-165 : [FILE-RESCAN] .......filename: Batwoman 15 (2013).cbr
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1239 : Thread-165 : [FILE-RESCAN] .......filesize: 26164159
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1100 : Thread-165 : temploc: 0
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1140 : Thread-165 : [FILE-RESCAN] [246454] Issue match - fcdigit: 0 ... int_iss: 0
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1157 : Thread-165 : [FILE-RESCAN] IssueID matches to multiple issues : 246454. Checking dupe.
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1158 : Thread-165 : [FILE-RESCAN] miISSUEYEAR: 2011 -- issyear : 2011
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1164 : Thread-165 : [FILE-RESCAN] Matched to year within filename : 2011
09-May-2019 12:50:21 - DEBUG   :: mylar.forceRescan.1178 : Thread-165 : [DUPECHECK] Duplicate issue detected [Batwoman 0 (2012).cbr] [Batwoman 0 (2011).cbz]

**Comment by evilhero** [comment]
This should be fixed in development now.

As far as duplicates, this is not the ideal solution, but it works and retains only one copy within Mylar for the purposes of tracking. Ideally it should be taking the duplicates for each duplicate issue number and comparing them to take the best match against the duplicate options, but right now it will just take the first match and ignore the remainder matches. (This paragraph doesn't really apply to your issue, since the series in your case has the same issue numbers - as opposed to having multiple files of the same issue number in a series where there is only one relevant issue number and how it should be handled).
