### ISSUE TITLE
Experimental (nzbindex) yet again

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#2275]
Am I the only one having this issue?? Seems for more than a month now no match found on experimental (API), whether it be automatic or manual.
No errors showing up on the logs, just no match, yet if i go to the nzbindex site and search i can find and get the nzbs.
If there another free nzb search site that can be used here instead?
Thanks :)
Pipi

**Comment by evilhero** [comment]
Yeah it looks like they finally removed the old domain name, but we're still using the old one. 

Updated and fixed (and verified working now) in latest development commit d280ce0
