### ISSUE TITLE
DDL Quietly Fails if /ddl_location is set to a location that doesn't exist

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#2278]
**Describe the bug**
DDL Quietly Fails if /ddl_location is set to a location that doesn't exist

**Screenshots/Logs**
16-May-2019 16:37:15 - INFO    :: mylar.ddl_requeue.2233 : CP Server Thread-9 : [DDL-RESTART] Successfully restarted Lucifer #8 (2019) [ 27 MB] for downloading..
16-May-2019 16:37:19 - INFO    :: mylar.ddl_downloader.3055 : DDL-QUEUE : Now loading request from DDL queue: Lucifer #8 (2019)
16-May-2019 16:37:21 - DEBUG   :: mylar.downloadit.346 : DDL-QUEUE : remote filesize: 28756365
16-May-2019 16:37:21 - ERROR   :: mylar.downloadit.399 : DDL-QUEUE : [ERROR] [Errno 2] No such file or directory: u'/volume1/Diskstation/Media/Comics/Grabbag/Lucifer 008 (2019) (digital) (Son of Ultron-Empire).cbr'
16-May-2019 16:37:21 - INFO    :: mylar.ddl_downloader.3097 : DDL-QUEUE : [Status: False] Failed to download: {'path': None, 'success': False, 'filename': u'Lucifer 008 (2019) (digital) (Son of Ultron-Empire).cbr'} 

**Environment (please complete the following information):**
 - OS: Synology Diskstation 
 - Branch / commit: Version: 7696edbc8b6fd893550965a0ea892143e53e23bd (development)

**Comment by barbequesauce** [comment]
On my to-do list...
