### ISSUE TITLE
Mylar not importing some downloads

### ISSUE THREAD

**Issue by whatwhynd** [evilhero/mylar#2279]
Hi, apologies if this has been covered already, happy to be referred to it if so. I did try searching but couldn't seem to find the solution.

Running Mylar and Sab via containers. Mylar sent the files to sab, sab downloaded them, and sorted a few of them into the correct folder that Mylar created, but then left the rest in the downloads folder for some reason? Clearly if it's importing some of them then it must be set up correctly? 

The file names of the ones imported and the ones that have not been imported are in the exact same format, no different characters other than the numbers. 

Thanks in advance! And if evilhero is reading this, thanks for making such an amazing tool!

**Comment by evilhero** [comment]
We'd need to see the debug logs to see what's happening in regards to the send and post-processing. 

What type of post-processing are you using - the ComicRN script, the Completed Download Handling, or the Folder Monitor (which you shouldn't use in conjunction with SAB probably anyways).

Please try to follow the issue template when posting new issues too - it's not that we're being dicks, but almost 90% of the stuff we need to see is the same thing over and over again (ie. branch/commit of mylar, OS running on, debug logs). It just saves us time troubleshooting, and gets y'all back to what you need to do quicker as well hopefully...

**Comment by kanine** [comment]
I was having the same issues (sorry devs but I can't help with the troubleshooting).

What I can say though is once I configured Sabnzdb to use the script approach it started working just fine.
