### ISSUE TITLE
Variant cover handling

### ISSUE THREAD

**Issue by Otsdarva68** [evilhero/mylar#2280]
**Describe the bug**
Mylar is pulling variant-cover-only nzbs thinking they are the full issue. It would be cool if it could recognize variant covers from usenet and include them in the same folder with a different name. I doubt this is the first time anyone has experienced this; is there a known workaround/fix?

**Environment (please complete the following information):**
 - OS: Archlinux
 - Branch / commit: d280ce0b0bedd5d802f7d44d186ba887c7dca803

**Comment by evilhero** [comment]
The only workaround atm is to set your minimum filesize to something like 10mb (or less, but 10 is usualy a safe bet) - that way it will avoid any releases that are just covers only in most cases, while still being able to grab normal releases.

Unfortunately, with the complete lack of filename standards for comics, being able to extract variant only covers just from a filename is really tough - not impossible. It might be a doable item at some point in the near future, albeit right now I believe myself and the other devs that contribute are knee-deep in other mylar-related items that are taking all of our free coding time.

**Comment by Otsdarva68** [comment]
Minimum filesize; I should have thought of that. Thanks!
