### ISSUE TITLE
Weekly Directory sorting issue

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#2287]
this is more of a request than an issue. The current weekly directory labels the folders as 2019-2 however i'm having some issues with my comic reader/library app. its sorting the folders 2019-1, 2019-11, 2019-2 instead of 2019-1, 2019-2, 2019-11. Is there anyway to just add a zero, like is being  done for renaming files, 2019-01, 2019-02 etc?

**Comment by evilhero** [comment]
Yep, should be easy enough to do - I thought we had changed it to do the padding, but either it reverted at some point, or we just never did it.
