### ISSUE TITLE
Error on loading of the wanted page

### ISSUE THREAD

**Issue by tomtom602** [evilhero/mylar#2289]
**Describe the bug**
On loading of the wanted page I've got the error below
This problem only occurs on this page

**Screenshots/Logs**
Error !
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
%> <tr class="${issue['Status']} grade${grade}"> <% linkit = 'comicDetails?ComicID=%s' % issue['ComicID'] try: if issue['StoryArcID'] is not None: lineheader = issue['StoryArc'] linkit = 'detailStoryArc?StoryArcID=%s&StoryArcName=%s' % (issue['StoryArcID'],issue['StoryArc'])
/usr/local/share/mylar/data/interfaces/default/upcoming.html, line 89:
<%
/usr/local/share/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/usr/local/share/mylar/lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
/usr/local/share/mylar/lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/share/mylar/lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
/usr/local/share/mylar/lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/usr/local/share/mylar/mylar/webserve.py, line 57:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

**Environment (please complete the following information):**
Version: 298534958d22214155d50eddedb339838af21e5e (master)
Running on freebsd

**Comment by evilhero** [comment]
Do you have storyarcs enabled within Mylar (or have any storyarcs listed in the story arc section)?

**Comment by tomtom602** [comment]
I do have one story arc.
for info, I managed to access to the wanted page without error by deactivating the option "enable series annual integration"
is there a link between this option and the story arcs ?

**Comment by evilhero** [comment]
No, there's no link aside from if you have a series on your watchlist that's in a given arc and that happens to be an annual (in theory at least).

What is the story arc that you have present - there might be some linking problem happening, but without knowing the arc present it's a crapshoot at guessing.

**Comment by tomtom602** [comment]
The story arc is : war of the realms
With id: 60216
