### ISSUE TITLE
[Question] How are download failures supposed to work?

### ISSUE THREAD

**Issue by ForceConstant** [evilhero/mylar#2290]
I have a bunch of comic issues, that were sent to sabnzb but failed because there were not enough parts, or was corrupted, etc. And my wanted list is filling up with Snatched issues. How is mylar supposed to handle this, or is there something I can do manually to account for this?

Thanks.

**Comment by barbequesauce** [comment]
Depends... are you using the comicrn script to post-process, or completed download handling?



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ForceConstant** [comment]
@barbequesauce I am using the comicrn script.

**Comment by evilhero** [comment]
Do you have Failed Download Handling enabled within Mylar? 

If it's enabled, Mylar will mark that specific download as failed if/when it encounters a failure post-processing an item that is corrupt, or invalid. Once it's marked as failed, it will be ignored on subsequent runs, and it will kick off a search to find an alternate match and try and download that.

If it's not enabled, then it will do nothing when it encounters an invalid/corrupt file during post-processing and just indicate as such in the logs.

**Comment by ForceConstant** [comment]
@evilhero I don't see an option anywhere for "Failed Download Handling", where is this option?

**Comment by evilhero** [comment]
Configuration --> Quality & Post-Processing.

**Comment by ForceConstant** [comment]
@evilhero Ah I see it and unfortunately it is already checked. So looking at sabnzbd it doesn't seem to run post-processing script if there is a failure. Do I need to change something there?

**Comment by evilhero** [comment]
We need to see the debug logs (from the files, not the GUI) from Mylar showing a send/fail attempt. Don't really care about sabnzbd logs.
