### ISSUE TITLE
Digital/Print versions

### ISSUE THREAD

**Issue by Jbaal** [evilhero/mylar#2292]
Not really a bug but I have some problems with the digitals and prints versions of some series.

As you can see, **Batman: Arkham Knight** has 2 editions:
https://comicvine.gamespot.com/batman-arkham-knight/4050-80292/
https://comicvine.gamespot.com/batman-arkham-knight/4050-80592/

But Mylar see the both of them as a print version.

I've used this Folder Format:
_$Publisher/$Type/$Series $VolumeN ($Year)_
to deal with the fact that the year is the same, but now I run with this issue.

How does Mylar choose the type of a volume? I tried some changes on the comicvine page with no results...

Edit: It would be better to add a radio-type choice in the form which edit the serie (with Digital, HC, TPB, Print, One-Shot and None), overwriting the default choice made by Mylar.

**Comment by evilhero** [comment]
Mylar parses the description and the deck for common terms/phrases that are used to denote what the edition is. Normally it's pretty reliable, however in this case the wording was different than other volumes on CV and as such (digital was indicated, but in the next line print was mentioned throwing off the calc), it choose print. I've corrected Mylar to account for that terminology, however if you're editing CV - I would suggest attempting to stick to the same wording to denote the editions if you're wanting Mylar to auto-detect things properly.

Adding a radio type of button might be possible, however the implications of doing so have wide-reaching effects throughout the program. It has more implications than just changing the ```$Type``` variable in the format strings.  

The edition affects how the file parser looks at the files, how the search matches, and also how the post-process runs. Right now it only cares about Print, TPBs, One-Shots or Annuals ( and everything else is lumped into one of those 4 ). Adding even more flavours to the options while giving more choice, increases the complexity of matching/parsing by tenfold for each addition and in doing so will cause problems with incorrect matches.

So while it's nice to have, I also relish my sanity most days. Not saying it won't happen, just not going to happen anytime soon most likely.

**Comment by Jbaal** [comment]
Thanx for the clarification, I indeed prefer Mylar to manage everything by itself, I'll work on the comicvine pages with the same kind of issues instead ;)

I understand the complexity of such a work, thanx a lot for what you've already done, I'll try to make more feedbacks on the issues I'm dealing with if that can help
