### ISSUE TITLE
Cover Only Hits on API Calls

### ISSUE THREAD

**Issue by kanine** [evilhero/mylar#2294]
**Describe the bug**
When doing searches for backlogs, often a 'Cover Only' is retrieved. This is evident both in files sizes (<5Mb) and the name often featuring cover.only or similar variant.

**Environment (please complete the following information):**
 - Windows10
 - Development 0af13913eaf120ced01bddeafb23ceedbcdfc0e8

**Additional information**
Can I suggest we have an option to filter these out either as configurable option in case there are folks collecting these, or just a straight default action.

**Comment by barbequesauce** [comment]
Would the Minimum File Size option on the Quality & Post Processing tab of settings cover this?

**Comment by kanine** [comment]
Yeah it would probably help, I hadn't noticed that before, I'll try with a 5Mb option that should cut out a bit.
