### ISSUE TITLE
Error for Guardians Of The Galaxy 2019

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#2299]
So, this comic was pulling fine, but this week, the logs started showing:

ERROR | Uncaught exception: Traceback (most recent call last):File "/home/hd27/moleboy/apps/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/home/hd27/moleboy/apps/mylar/mylar/PostProcessor.py", line 1651, in Processself.Process_next(comicid, issueid, issuenumOG, ml, stat)File "/home/hd27/moleboy/apps/mylar/mylar/PostProcessor.py", line 2712, in Process_nextweeklypull.weekly_check(comicid, issuenum, file=(nfilename +ext), path=dst, module=module, issueid=issueid)File "/home/hd27/moleboy/apps/mylar/mylar/weeklypull.py", line 1321, in weekly_checksend2read(comicid, issueid, issuenum)File "/home/hd27/moleboy/apps/mylar/mylar/weeklypull.py", line 1392, in send2readread.addtoreadlist()File "/home/hd27/moleboy/apps/mylar/mylar/readinglist.py", line 70, in addtoreadlistif os.path.exists(os.path.join(comicinfo['ComicLocation'], readlist['Location'])):File "/usr/lib/python2.7/posixpath.py", line 68, in joinif b.startswith('/'):AttributeError: 'NoneType' object has no attribute 'startswith'
-- | --

If I try navigating to the series I get:
Error !
TypeError: object of type 'NoneType' has no len()
<td id="select"><input type="checkbox" name="${issue['IssueID']}" class="issCheck checkbox" value="${issue['IssueID']}"/></td> <td id="int_issuenumber">${issue['Int_IssueNumber']}</td> <td id="issuenumber">${issue['Issue_Number']}</td> <% if len(issue['IssueName']) > 70: issuename = "%s..." % issue['IssueName'][:70] else: issuename = issue['IssueName'] endif
/home/hd27/moleboy/apps/mylar/data/interfaces/default/comicdetails.html, line 367:
<%
/home/hd27/moleboy/apps/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
/home/hd27/moleboy/apps/mylar/lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/home/hd27/moleboy/apps/mylar/mylar/webserve.py, line 57:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

I can delete the series, and readd it, and all the currently retrieved issues show up, but the error will repeat, when the search runs again.

**Comment by evilhero** [comment]
Check your paths in Mylar to make sure all the slashes are going the right way.

Other than that, please follow the issue template - looking at that log on a phone makes me want to light my phone on fire with a blowtorch. Full debug logs showing the leadup to the error specifically.
