### ISSUE TITLE
NoneType and Int error during "recheck files"

### ISSUE THREAD

**Issue by airix1** [evilhero/mylar#2307]
When clicking "recheck files" on a series, "an error occurred" is shown and the file recheck fails.

` ERROR   :: mylar.excepthook.315 : Thread-28 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/updater.py", line 956, in forceRescan
    tmpval = tval.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 147, in listFiles
    runresults = self.parseit(self.dir, filename, filedir)
  File "/opt/mylar/mylar/filechecker.py", line 909, in parseit
    if all([highest_series_pos + 1 != volume_found['position'], highest_series_pos != volume_found['position'] + 1, sep_volume == False, booktype == 'issue', len(possible_issuenumbers) > 0$
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

 - OS: linux
 - Branch / commit: Master: 68a8e77

**Comment by evilhero** [comment]
debug logs are needed.

**Comment by airix1** [comment]
[mylar.log](https://github.com/evilhero/mylar/files/3365236/mylar.log)

**Comment by evilhero** [comment]
Your filenames do not have an issue year where it's expected due to having the month within the filename. Having just the month isn't indicitive of the year of the issue.

Either remove the month from the filenames or just add the year after the month (ie. ```(December 2014)```).

**Comment by airix1** [comment]
Yup, that fixed it.
Strange, none of my other series have the issue year in the name and don't get that error. I can live with this work around for my naming convention.  
Thanks again for such a great application!
