### ISSUE TITLE
Unable to Send Torrent

### ISSUE THREAD

**Issue by mediumwalter** [evilhero/mylar#2308]
New setup on raspberry pi getting "Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)"

Full debug log below:
https://pastebin.com/NBduiLLq

Config:
https://pastebin.com/Yd8jt2NA

 - OS: Raspbian
 - Branch / commit: Version: 6a1f96167cf9cad6bf2e0ef7881b398e75b98169 (development)

**Comment by barbequesauce** [comment]
Are you using Deluge or Transmission?

In either case, the format should be IP:Port, and that config looks like both are set to IP only...

**Comment by mediumwalter** [comment]
Oh wow that was not very smart of me. Thanks for pointing out the obvious haha
