### ISSUE TITLE
post processing not working with specific filename format (name, date (issue))

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#2315]
I'm on master branch, not getting files processed that have a filename formatted like this

Mighty Morphin' Power Rangers, 2019-06-26 (#40) (digital).cbr

anything i can do on my part to handle these?

**Comment by evilhero** [comment]
The brackets around the issue number are causing the problem it looks like (```(#40)```). Remove the brackets so it's just ```#40``` and things will go thru based on those filenames. 

Fix will be coming soon-ish to accommodate the ```(#XX)``` format within a filename.
