### ISSUE TITLE
Migrated server not downloading

### ISSUE THREAD

**Issue by the-Dakta** [evilhero/mylar#2320]
**Describe the bug**
After moving my server to a new machine, comics are not downloading and the logs are reporting some weird permissions errors around directories.

**Screenshots/Logs**
https://termbin.com/k8ec

**Environment (please complete the following information):**
 - OS: Distro.......: Ubuntu 18.04.2 LTS
  Kernel.......: Linux 4.18.0-25-generic
 - Branch / commit: Docker (Version: 68a8e77ad15a960b62106616c38e277ff0ec01cb ((HEAD detached at 68a8e77)))

**Additional information**
It seems to authenticate with 32pag.es and IPT just fine, and I even saw it actually download a torrent once, but it never hit deluge. It also (now at least) seems to connect to deluge okay. Additionally there are periodically mentions of permissions issues because it is trying to create or read a directory in just /comics/___ when in reality the path it should be going through is /mnt/data/Books/Comics/. I've checked all of the paths in my configurations and all of them seem to be accurate. I've also adjusted permissions on that path to ensure that Mylar -should- have access to write.

**Comment by barbequesauce** [comment]
Sorry... docker messes with paths in some way that we don't really grok... you'll see lots of issues here and in the forums of people struggling to get deluge and mylar talking in docker, we haven't found that magic combination yet.

I'd suggest going back to whoever rolled your docker image and try to have them diagnose it... I'm happy to join the conversation if needed.

**Comment by the-Dakta** [comment]
So I thought the paths might be an issue in docker as well, but they're mapped 1:1 in docker. So /mnt in docker maps to /mnt on my machine. And /comics/ is listed nowhere in my config or my docker image.

That being said, those paths wouldn't be an issue with it not downloading anything, right? Any recommendations for that?

**Comment by barbequesauce** [comment]
Are you sending torrents to Deluge using RPC or black hole? If RPC, is it being received on the far side? if black hole, is Deluge picking it up?

Most of the issues have been around what happens after deluge completes downloading - the file is visible from deluge but mylar doesnt see it.

**Comment by the-Dakta** [comment]
I'm using the Deluge demon. The Mylar logs make it seem like they're connecting to eachother, but Deluge doesn't receive anything.

**Comment by barbequesauce** [comment]
can you send a log with interaction? the log posted above only has imports...

**Comment by the-Dakta** [comment]
So I just dug through the other logs stored and all of them only either have the post processing reports or the errors before I realized it was asking for the daemon and not the webui login information, so I I'm actually not sure where that went to be honest. This is the closest I could find: https://termbin.com/bpna

**Comment by the-Dakta** [comment]
Okay it turns out telling it to test the connection again gives me: `

2019-08-02 15:30:33 | WARNING | [Deluge] Could not establish connection to 192.168.1.42:58846. Error returned:
-- | -- | --
2019-08-02 15:30:33 | ERROR | Could not connect to Deluge: 192.168.1.42

`

**Comment by barbequesauce** [comment]
huh. ok.

so - from inside the mylar container - can you telnet to 192.168.1.42:58846 ?

**Comment by the-Dakta** [comment]
In the container bash I get:

telnet: command not found

unfortunately

**Comment by barbequesauce** [comment]
Is netcat installed? That would be a valid test as well

**Comment by the-Dakta** [comment]
unfortunately not. And looking at the command list I don't see any that would help with testing a network connection.

**Comment by barbequesauce** [comment]
Silly question - what version of Deluge are you using?

Wondering if you’re hitting the same wall as @carpelaborum in #2321

**Comment by evilhero** [comment]
Mylar also has to comply with the deluge auth file for remote access. 

You need to ensure that you have a username / password / level indicated in the appropriate deluge auth file to allow for remote usage.

**Comment by the-Dakta** [comment]
Deluge 2.0.3-2-201906121747-ubuntu18.04.1

And Mylar is using the same username and password as in my Deluge auth file. Mylar, as far as I can tell, doesn't ask for the deluge authentication level (which in the auth file is set as admin).

**Comment by barbequesauce** [comment]
So it is connected to 2321. I should have time to wrangle a PR this week to add in a new client to the config screens and add the new client.py. If you're comfortable working with diffs and editing the source, I could use a tester...

It might take some time to get merged in as evilhero's time is quite limited during the summer months when everyone is off school...

**Comment by the-Dakta** [comment]
Since I'm running it from a docker image I'm not sure about messing with any source right now. To be honest I'm thinking about just connecting it to my windows PC QBittorrent instead in the mean time, but also comics aren't a huge priority so I'm okay as is for now. Either way, I appreciate y'alls help

**Comment by the-Dakta** [comment]
So I'm trying to set it up with my QBittorrent install on my Windows PC instead. I've edited the mylar conf file with the appropriate settings, enabled web ui in qbittorrent, and then changed the settings in the mylar ui but I get `[qBittorrent] Could not establish connection to 192.168.1.149:8080. Error returned: No connection adapters were found for '192.168.1.149:8080/api/v2/app/preferences'`

**Comment by the-Dakta** [comment]
I ended up just turning off failed download handling and it seems to be grabbing them now.
