### ISSUE TITLE
Not compatible with new DelugeVPN 2.0+

### ISSUE THREAD

**Issue by Carpelaborem** [evilhero/mylar#2321]
**Describe the bug**
When using the newest version of Deluge, Mylar will not connect to Deluge.  This is because with 2.0 of Deluge, the protocol has changed.

**Screenshots/Logs**
This is from the DELUGE log file:
19:27:05 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 172.17.0.1:55564
19:27:05 [WARNING ][deluge.transfer               :114 ] Error occurred when parsing message header: Received invalid protocol version: 120. PROTOCOL_VERSION is 1..
19:27:05 [WARNING ][deluge.transfer               :116 ] This version of Deluge cannot communicate with the sender of this data.
19:27:05 [WARNING ][deluge.transfer               :136 ] Failed to decompress (0 bytes) and load serialized data with rencode: Error -5 while decompressing data: incomplete or truncated stream
19:27:25 [INFO    ][deluge.core.rpcserver         :197 ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Environment (please complete the following information):**
 - OS: Linux / Docker
 - Branch / commit: Master /  68a8e77

**Additional information**
The deluge client in the /app/mylar/lib/deluge_client is 3 years old.  To be compatible with the newest deluge, you need a newer version of the deluge client.py from here:  https://github.com/JohnDoee/deluge-client/tree/master/deluge_client

I've tested replacing this file and it works accordingly.

**Comment by barbequesauce** [comment]
Interesting, thank you. I wonder how many of the open issues here, on the forums, and on 32p are related to this?

I hope the client.py is backwards compatible....

**Comment by Carpelaborem** [comment]
Unfortunately, I wouldn't think so, since it's a change in the communication protocol :(

**Comment by Carpelaborem** [comment]
And you're welcome :)  Took me a few hours to track down, since I didn't know the code base on either end.

**Comment by barbequesauce** [comment]
So it is connected to 2320. I should have time to wrangle a PR this week to add in a new client to the config screens and add the new client.py. If you're comfortable working with diffs and editing the source, I could use a tester...

It might take some time to get merged in as evilhero's time is quite limited during the summer months when everyone is off school...

**Comment by barbequesauce** [comment]
Still arguing with deluge on this, it’s coming...

**Comment by barbequesauce** [comment]
Should be good to go now with 66897c15499bac615211cf7186a072e75336c0e6
