### ISSUE TITLE
WWT be gone, yo

### ISSUE THREAD

**Issue by BRTPOB** [evilhero/mylar#2327]
Turns out WWT is down for the count. Seems all of the uploaders moved to EZTV and the link (per reddit, link here: https://www.reddit.com/r/trackers/comments/cjh9ge/best_public_comic_tracker/ewgjo0f/).

Can we remove it so that it stops throwing errors in peoples' logs, and maybe update to use EZTV instead?

**Comment by joker999** [comment]
OR this https://www.ettv.to/torrents.php?cat=55
