### ISSUE TITLE
Feature Request: Custom Stylesheet

### ISSUE THREAD

**Issue by m00n22** [evilhero/mylar#2329]
Would be awesome to be able to create and use a custom style sheet to modify the look/feel of Mylar.

I would love a mobile responsive Mylar (but seeing that's a huge undertaking) this would be the next best thing. Being able to create and use a custom css like SickChill let's you do (also my request).

![Image of SickChillCustomCSS](https://snag.gy/jrRofk.jpg)

To create a complete skin or some minor css change:

![Image of CustomCSSImplementation](https://snag.gy/keZUtw.jpg)

**Comment by barbequesauce** [comment]
There’s already a huge effort underway to get the interface bootstrap-enabled. That’s forcing a rewrite of much of the base code. Not sure the feasibility of custom CSS following, but that would at least get you to a responsive design...

**Comment by m00n22** [comment]
@barbequesauce that would be awesome. I checked both bootstrap request post, but both seemed dead. Hope it's still in the works!

**Comment by barbequesauce** [comment]
A different developer picked up the mantle and is moving it forward...
