### ISSUE TITLE
Feature Request: Remember Page Viewing Options

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#2331]
This is a request based out of preference.  Every time I login, I have to re-sort my comics how I like them, and set the page to show All, rather than 25 titles.  Is it possible to remember my sorting/viewing options so I don't need to do this every time I login?

**Comment by barbequesauce** [comment]
What branch & commit are you running, and what OS / Browser? This should work as of commit 
https://github.com/evilhero/mylar/commit/742a7c974897e0539989b33b9b4de386ec128858

**Comment by DrSeussFreak** [comment]
I am on Mac OS 10.14.6 (18G87)
Mylar: Version: 9fb9ab4d732fad1c181df54e419975e5ec823d2a (development)
Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

It saves while the browser remains open, but once I close the browser the settings revert, and I need to tell it to show all my comics ,and re-sort everything the way I like it.

**Comment by barbequesauce** [comment]
Could have guessed Chrome. There are persistence challenges I haven’t been able to solve there.

Just for my own sanity, you’re not running incognito are you?

**Comment by DrSeussFreak** [comment]
I am not running in incognito mode

**Comment by barbequesauce** [comment]
Just checking ;) 

Evilhero this one is mine
