### ISSUE TITLE
blacklisted_publishers not workingas intended

### ISSUE THREAD

**Issue by Buttonskill** [evilhero/mylar#2332]
I can't seem to remove specified publishers utilizing the hidden config.ini feature.  For background, I'm running 3 instances of Mylar in containers to keep comic lists manageable.  Aside from the general undesirables like Panini Comics, I'd like DC comics removed from Marvel instance, Marvel removed from DC, and so on.  

Here's what my indie comics syntax looks like:
`blacklisted_publishers = Editorial Novaro, Panini Comics, Editrice Cenisio, Planeta DeAgostini, Vanderhout, Editora Brasil-America Limitada, Les Humanoïdes Associés, Catalan Communications, Panini, Ediciones Zinco, TwoMorrows Publishing, Urban Comics, Super Genius Comics, Les Humanoïdes Associés, Titan Comics, ECC Ediciones, Taschen, Ave Fenix Comics y Libros, Titan Magazines, Comix-Art, Atlantic BD, Editorial Televisa, Tangent Comics, Hjemmet, Grupo Editorial Vid, Norma Editorial, Play Press, Dino Comics, TM-Semic, Semic, Egmont, JuniorPress BV, Chick Publications, Interpresse, Ehapa Verlag, Editions Héritage, Sage - Sagédition, Ehapa Verlag, Novedades Editores, Editorial Bruguera, Atlantic Förlag, Novedades Editores, Editora Brasil-América Limitada, Se-Bladene, Williams Förlag, DC Comics, Marvel Comics, DC, Marvel, Clasics\/Williams`

Yet they still appear when tested on Superman search:
![image](https://user-images.githubusercontent.com/5286858/63215063-bba17b00-c0d5-11e9-9b29-1ea24c8010f5.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.042
 - Branch / commit: [e.g. Dev/38aksi1]

And thank you for all the sorting hours you've gifted back to me by creating Mylar.

**Comment by barbequesauce** [comment]
I’m wondering if the accents and umlauts are causing issues. Can you please start Mylar in debug mode and create a new pull list, then post the debug log file (not from the webpage) on completion?

**Comment by Buttonskill** [comment]
You got it.

`17-Aug-2019 11:38:36 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:37 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:38 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:39 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:40 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:41 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:42 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:42 - INFO    :: mylar.pullrecreate.1943 : CP Server Thread-11 : Deleted existing pull-list data for week 32, 2019. Now Recreating the Pull-list...
17-Aug-2019 11:38:42 - INFO    :: mylar.pullit.70 : CP Server Thread-11 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
17-Aug-2019 11:38:42 - INFO    :: mylar.pullit.74 : CP Server Thread-11 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 32, 2019
17-Aug-2019 11:38:43 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:43 - INFO    :: mylar.locg.70 : CP Server Thread-11 : [WEEKLY-PULL] There are 90 issues for the week of 32, 2019
17-Aug-2019 11:38:44 - INFO    :: mylar.locg.131 : CP Server Thread-11 : [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 32
17-Aug-2019 11:38:44 - INFO    :: mylar.pullit.82 : CP Server Thread-11 : [PULL-LIST] Weekly Pull List successfully loaded with 90 issues.
17-Aug-2019 11:38:44 - INFO    :: mylar.LoadAlternateSearchNames.1347 : CP Server Thread-11 : AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Rick & Morty'}], 'ComicID': u'81059'}
17-Aug-2019 11:38:44 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.946 : CP Server Thread-11 : [WALKSOFTLY] You are watching for: 8 comics
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.976 : CP Server Thread-11 : [WEEKLY-PULL-ID] Series Match to ID --- Usagi Yojimbo [119731]
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.1017 : CP Server Thread-11 : [WEEKLY-PULL] Issue Match to ID --- Usagi Yojimbo #3[119731/716153]
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.1067 : CP Server Thread-11 : Watchlist hit for : Usagi Yojimbo #: 3
17-Aug-2019 11:38:44 - DEBUG   :: mylar.latest_update.357 : CP Server Thread-11 : 119731 - updating latest_date to : 2019-08-14
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.406 : CP Server Thread-11 : pull_refresh: 2019-08-17 11:38:00
17-Aug-2019 11:38:44 - INFO    :: mylar.dbUpdate.122 : CP Server Thread-11 : Refreshing/Updating: Usagi Yojimbo (2019) [119731]
17-Aug-2019 11:38:44 - DEBUG   :: mylar.dbUpdate.141 : CP Server Thread-11 : CV_OneTimer option enabled...
17-Aug-2019 11:38:44 - DEBUG   :: mylar.dbUpdate.143 : CP Server Thread-11 : Gathering the status of all issues for the series.
17-Aug-2019 11:38:44 - DEBUG   :: mylar.dbUpdate.153 : CP Server Thread-11 : Checking how out of whack the series is.
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.496 : CP Server Thread-11 : Comic series already up-to-date ... no need to refresh at this time.
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.498 : CP Server Thread-11 : Available to be marked for download - checking...Usagi Yojimbo Issue: 3
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.499 : CP Server Thread-11 : ...Existing status: Downloaded
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.548 : CP Server Thread-11 : ...Already have issue - keeping existing status of : Downloaded
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.559 : CP Server Thread-11 : --attempt to find errant adds to Wanted list
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.560 : CP Server Thread-11 : UpcomingNewValue: {'Status': 'Downloaded', 'ComicName': u'Usagi Yojimbo', 'IssueID': u'716153', 'DisplayComicName': u'Usagi Yojimbo', 'IssueNumber': '3', 'IssueDate': '2019-08-14'}
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.561 : CP Server Thread-11 : UpcomingcontrolValue: {'ComicID': u'119731'}
17-Aug-2019 11:38:44 - DEBUG   :: mylar.upcoming_update.582 : CP Server Thread-11 : updating Pull-list to reflect status change: Downloaded[Downloaded]
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.1076 : CP Server Thread-11 : statusupdate: {'Status': u'Downloaded', 'IssueID': u'716153', 'ComicID': u'119731'}
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.1092 : CP Server Thread-11 : date_downloaded: None
17-Aug-2019 11:38:44 - DEBUG   :: mylar.new_pullcheck.1179 : CP Server Thread-11 : issue exists in db already: 716153
17-Aug-2019 11:38:44 - DEBUG   :: mylar.future_check.1412 : CP Server Thread-11 : cflist: []
17-Aug-2019 11:38:44 - INFO    :: mylar.future_check.1415 : CP Server Thread-11 : No series have been marked as being on auto-watch.
17-Aug-2019 11:38:45 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:46 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:47 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:48 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:49 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:50 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:51 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:52 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:53 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
17-Aug-2019 11:38:54 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar
`

**Comment by evilhero** [comment]
I think what he meant to say was have debug enabled, and then do a search for a series via the upper search bar. We need to see if it's referencing the blacklisted list properly or if it's not. I don't think the special characters would impact things, altho it would have to write it to the ini file as a utf-8 encoded object.

**Comment by BRTPOB** [comment]
Are you sure that's the full Mylar log? It seems kind of...scant. Shows no searching or anything that you were looking for, just restarting.

**Comment by Buttonskill** [comment]
>Are you sure that's the full Mylar log? It seems kind of...scant. Shows no searching or anything that you were looking for, just restarting.

No, you're right.  There was a folder check in there that I omitted with the intention of reducing time spent analyzing it.  Just habit.   When I share a log I tend to keep it succinct and focused on the repro.

>I think what he meant to say was have debug enabled, and then do a search for a series via the upper search bar. We need to see if it's referencing the blacklisted list properly or if it's not. I don't think the special characters would impact things, altho it would have to write it to the ini file as a utf-8 encoded object.

I was wondering why the pull list was relevant there.  Here's a restart search:
[mylar.log](https://github.com/evilhero/mylar/files/3513261/mylar.log)

But keep in mind that my config.ini for this search has been reduced to
`blacklisted_publishers = Panini Comics, DC Comics, Marvel Comics`
..in an attempt to rule out the umlauts and such.

![image](https://user-images.githubusercontent.com/5286858/63227215-1059fa00-c199-11e9-8a46-12e3b434a69d.png)

**Comment by BRTPOB** [comment]
OK, so I have to believe it's how you've got yours setup. I just added DC Comics to my blacklist, thus it looks like this: `blacklisted_publishers = Panini Comics, DK Publishing, ECC Ediciones, Planeta DeAgostini, Dino Comics, RW Uitgeverij, Grupo Editorial Vid, Editorial Televisa, ID Komiks, DC Comics`

This is what my search results look like:

![image](https://user-images.githubusercontent.com/7201028/63227320-f6420b00-c1dc-11e9-8c77-05adf35a61bb.png)

**Comment by evilhero** [comment]
Are you using a seperate  config.ini for each docker? Are you restarting mylar after each manual config.ini change (you shouldn't be editing it at all when it's running)?

**Comment by Buttonskill** [comment]
>Are you using a seperate config.ini for each docker? Are you restarting mylar after each manual config.ini change (you shouldn't be editing it at all when it's running)? 

That's correct.  Separate config.ini's for each container.   General path I stick to:

1. Copy config.ini to another directory 
2. edit in notepad++ or nano
3. stop the container
4. copy and overwrite /mylar/config.ini
5. Start container

>Does the blacklisted_publishers appear under the [CV] section of the ini?

It's under [CV] section too

`
[CV]`
`cv_verify = True`
`cv_only = True`
`cvinfo = True`
`blacklisted_publishers = Panini Comics, DC Comics, Marvel Comics
`

**Comment by BRTPOB** [comment]
Question: why aren't you just killing Mylar instead of adding in the additional steps of copying to/from?

**Comment by Buttonskill** [comment]
>Question: why aren't you just killing Mylar instead of adding in the additional steps of copying to/from?

Ease of editing?  More personal preference editing in notepad++ I suppose.  Log can be open in one tab, config.ini in another, etc.

**Comment by evilhero** [comment]
Just realized, the commit you're running doesn't seem to be current - ```38aksi1``` and I can't find a reference to it thus far. Can you confirm your actual commit that you're using by taking the first 7 characters from the bottom of any mylar page (or from the 1st tab in the configuration, which also shows where your ini is being loaded from as well)

**Comment by Buttonskill** [comment]
Absolutely:

68a8e77

My docker compose pulls:
`    image: "linuxserver/mylar:amd64-latest"`

Which I was hoping would put me on the development branch, but it doesn't look like that's supported.  Merely pulls the latest master from the looks of it.

**Comment by evilhero** [comment]
Yep docker will always lock you on master as they believe development is too unstable (they generalize for every repo, however Mylar's dev branch is probably more stable due to the frequent commits normally).

I'll have to code dive this when I get a chance. My free time is non existant until the kidlets go back to school in a few weeks - but after that I'll be committing fixes/enhancements like a demon to make up for the past 2 months of my self-imposed exile / "vacation."

**Comment by Buttonskill** [comment]
No worries at all.  Hell, prioritize the real issues when you get back at it.  Nothing is really _broken_ here, and I can respect that this issue can be considered pedantic by comparison.  

This is really somewhat of an entrypoint for me to hopefully contribute.    I've messed around in other instances and made attempts to support python 3 with comicRN.py (Not this one.  The instance in question here is clean), but mostly been lurking for a year and found all my answers in your other responses..  And there's a lot of responses.
