### ISSUE TITLE
Uncaught exception: Traceback (most recent call last):

### ISSUE THREAD

**Issue by WraithTDK** [evilhero/mylar#2333]
I'm having a real devil of a time getting Mylar to recognize downloaded comics in the monitored folder. I thought it was just a matter of it getting confused by the tags scanner put at the end of file names.  But I just noticed that when running a manual post-processing, the logs show the following:

Uncaught exception: Traceback (most recent call last):File "/opt/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/opt/mylar/mylar/PostProcessor.py", line 403, in Processfilelist = flc.listFiles()File "/opt/mylar/mylar/filechecker.py", line 147, in listFilesrunresults = self.parseit(self.dir, filename, filedir)File "/opt/mylar/mylar/filechecker.py", line 1056, in parseitelif 'XCV' in issue_number:TypeError: argument of type 'NoneType' is not iterable
--

Is there a way to better train Mylar to recognize filenames? Teach it to ignore tags? Or just manually point it at a file and tell it "this file is this item on my want-list"?

**Comment by barbequesauce** [comment]
No clue where to start with this. Please close the issue and resubmit using the template, we need more information... sorry...

**Comment by WraithTDK** [comment]
What template?

**Comment by barbequesauce** [comment]
When you click “new issue” and then “get started”, it presents a form with questions to be answered - describe the bug, screenshots or logs, environment including OS and branch/commit...
