### ISSUE TITLE
Uncaught exception: Traceback

### ISSUE THREAD

**Issue by carakesa** [evilhero/mylar#2334]
Not quite sure what to make of this.  I thought I had it cleared up when I disabled SSL for everything (that may be a separate issue!).

One thing that stands out to me is the references to 32P, but I don't know if that's normal or not.  I'm not using 32P and do not have it enabled.  I do have a few Torznab entries loaded, but currently disabled for troubleshooting.

Version: 9fb9ab4d732fad1c181df54e419975e5ec823d2a (development)

`
ERROR | Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/helpers.py", line 3147, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/opt/Mylar/mylar/search.py", line 1855, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 359, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, 
send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, 
IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, 
allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, 
torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 1487, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, 
torznab=torznab_host, rss=RSS)File "/opt/Mylar/mylar/search.py", line 2486, in searcherss = nzbget.NZBGet()File "/opt/Mylar/mylar/nzbget.py", line 38, in __init__val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignment`
-- | --

**Comment by barbequesauce** [comment]
No clue where to start with this. Please close the issue and resubmit using the template, we need more information... sorry...
