### ISSUE TITLE
Uncaught exception: Traceback

### ISSUE THREAD

**Issue by carakesa** [evilhero/mylar#2335]
**Describe the bug**
Error on boot, references 32p which is not enabled per the GUI

**Screenshots/Logs**
`
[mylar.zip](https://github.com/evilhero/mylar/files/3512972/mylar.zip)

17-Aug-2019 22:44:20 - DEBUG   :: mylar.job_management.3576 : Thread-14 : ReScheduled job: Folder Monitor to 2019-08-18 02:54:20
17-Aug-2019 22:44:20 - INFO    :: mylar.dbUpdate.353 : Thread-12 : Update complete
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@17-Aug-2$
  File "/opt/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Mylar/mylar/helpers.py", line 3147, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/opt/Mylar/mylar/search.py", line 1855, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueA$
  File "/opt/Mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersi$
  File "/opt/Mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/opt/Mylar/mylar/search.py", line 2486, in searcher
    ss = nzbget.NZBGet()
  File "/opt/Mylar/mylar/nzbget.py", line 38, in __init__
    val = (protocol,)
UnboundLocalError: local variable 'protocol' referenced before assignment

17-Aug-2019 22:57:01 - WARNING :: mylar.Process.405 : Thread-14 : There were no files located - check the debugging logs if you think this is in error.
17-Aug-2019 23:02:18 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/opt/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Mylar/mylar/helpers.py", line 3147, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/opt/Mylar/mylar/search.py", line 1855, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueA$
  File "/opt/Mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersi$
  File "/opt/Mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/opt/Mylar/mylar/search.py", line 2486, in searcher
    ss = nzbget.NZBGet()
  File "/opt/Mylar/mylar/nzbget.py", line 38, in __init__
    val = (protocol,)
UnboundLocalError: local variable 'protocol' referenced before assignment

17-Aug-2019 23:03:37 - INFO    :: mylar.toggleVerbose.4015 : CP Server Thread-11 : Verbose (DEBUG) logging is enabled
17-Aug-2019 23:03:37 - DEBUG   :: mylar.toggleVerbose.4016 : CP Server Thread-11 : If you can read this message, debug logging is now working
17-Aug-2019 23:06:29 - DEBUG   :: mylar.dbUpdate.85 : Thread-12 : Refresh sequence set to fire every 5 minutes for 7 day(s)
17-Aug-2019 23:06:29 - DEBUG   :: mylar.job_management.3576 : Thread-12 : ReScheduled job: DB Updater to 2019-08-18 03:11:29`

**Environment (please complete the following information):**
Linux (Diet Pi Buster)
 Version: 9fb9ab4d732fad1c181df54e419975e5ec823d2a (development)

**Additional information**

Full logs are attached in a zip - ran with debug on. 

I see some extraneous searches (or at least unrelated results) going on.  ie  NZB results for boxing vs. comics showing in the logs....

**Comment by barbequesauce** [comment]
It looks like you don’t have a protocol set in your NZBGet config - the “NZBGet Host” option should look something like 

```
http://0.0.0.0
```

Or

```
https://thisotherserver.local
```

That should address the two tracebacks in the case while I dig into your logs...

**Comment by carakesa** [comment]
changed NZBGet Host from "0.0.0.0" to "http://0.0.0.0"

Now pulling in results from nzb.su

Going to try enabling Torrents and SSL again and 'see what happens'.
