### ISSUE TITLE
Directory being deleted when post processing DDL

### ISSUE THREAD

**Issue by stumueller** [evilhero/mylar#2338]
I have recebtly set up DDL using getcomics.info

I have added DDL_Location = L:\Complete\Temp to the config.ini server

Now I get issues snatched and downloaded fine, but one they have post processed and gone into my comic directory the folder Temp gets removed from L:\Complete so is not there hte next time it goes to do a DDL

Thanks

**Comment by barbequesauce** [comment]
Please follow the case template...
