### ISSUE TITLE
Downloads are not being copied from download location

### ISSUE THREAD

**Issue by jakewaudby** [evilhero/mylar#2344]
Comics are being downloaded but not copying across
Additionally when i try to run manual post processing on folder /downloads/Comics i get the following pop-up error

"Manual post-processing unable to run at this time."

I do not see anything obvious in the logs

OTOH if i run
Scan Comic Library and select "Move Files" and "Rename Files" on the same directory (/downloads/Comics) i can import comics. 

Mylar Version: (HEAD detached at 68a8e77)
Running inside a docker container hosted on OMV.

I feel sure this is a configuration issue but i've been battling it for some time, any help is appreciated.

Thanks 
jake

**Comment by barbequesauce** [comment]
That message usually means there is a problem with the PP queue. It's tough to tell without debug logs and the other items asked for in the issue template...
