### ISSUE TITLE
Traceback TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by trenna05** [evilhero/mylar#2345]
**Describe the bug**
When running a force check, it uploads the file to remote rtorrent seedbox but fails to download using the auto-snatch script. I've checked every folder location, rebuilt it and re-downloaded the docker but for the life of me can't figure out what is wrong. Thanks for taking a look :)

**Screenshots/Logs**
Log of affected area.
[log.txt](https://github.com/evilhero/mylar/files/3584029/log.txt)

**Environment (please complete the following information):**
 - OS: docker from linuxserver.io
commit: 68a8e77ad15a960b62106616c38e277ff0ec01cb

**Additional information**
Doesn't seem to matter what the file is, the permissions of the folder or where i locate it. I'm sure it is something simple but for the life of me can't seem to figure out. Any help would be super but understand if you don't get it. Wicked app thanks for making it.

**Comment by evilhero** [comment]
It's looking for the hash of the torrent - probably cause it's not expecting anyone to be using the auto-snatch script (lol). I'll have to dig into it abit, I know that I had fixed a reference previously to a similar error, just can't remember if it was this particular instance or something else.

**Comment by trenna05** [comment]
Thanks for looking into it for me. Understand if it can't be fixed. Thanks and let me know if I can help in anyway. The service is great thanks for making it.
