### ISSUE TITLE
Issues are being searched for, but nothing is found until a manual search is invoked. 

### ISSUE THREAD

**Issue by ivtechboyinpa** [evilhero/mylar#2349]
**Describe the bug**
Mylar processes all the "Wanted" comics without actually searching for them. To be specific, it says that it's looking for each issue in each of my configured indexers, says it couldn't find anything and moves onto the next issue. 

But, if I go into the comic page and click the button to manually search for a download, it finds a download instantly (I just tested it with Titans Hunt #6, which is also present in the log.)

**Screenshots/Logs**
[mylar.log](https://github.com/evilhero/mylar/files/3627596/mylar.log)

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Branch / commit: Latest Development

**Comment by barbequesauce** [comment]
Thanks - need a debug log though - start mylar with the -v flag, or click the "toggle debug logging" button on the log screen prior to forcing a search...

**Comment by ivtechboyinpa** [comment]
Let me know if this is of any help to you, and if you need anything else. 

[mylar.log](https://github.com/evilhero/mylar/files/3627838/mylar.log)

**Comment by barbequesauce** [comment]
Grasping here... what do you have Usenet retention set to?

**Comment by ivtechboyinpa** [comment]
I think I had it set to the max from my usenet provider which was 3937. Originally I had it at 0 but I thought that was causing problems.

**Comment by ivtechboyinpa** [comment]
@barbequesauce So I think it was a problem to do with the search queue locking. I've been working on a couple issues I found and I haven't had the issue since, so that's what I'm attributing it to. I'm gonna close this now.
