### ISSUE TITLE
Mail notification is missing headers

### ISSUE THREAD

**Issue by NoxInmortus** [evilhero/mylar#2352]
**Describe the bug**
Mail notification is missing headers and thus the notification goes into spam (at least with google mail).

**Environment (please complete the following information):**
 - Debian, latest docker image from linuxserver.io

**Additional information**

I have a SMTP fully working, and when using it with mylar, the notification goes into spam. After testing with https://www.mail-tester.com, it seems headers are missing :

-1.396 | MISSING_DATE | Missing Date: header
-0.14 | MISSING_MID | Missing Message-Id: header

Also there is not HTML message version. Google and other mail providers like this stuff.

**Comment by evilhero** [comment]
No idea where to start with this - the mail option was a PR from someone else, and I haven't looked at anything related to it. Unless someone does a PR for this, I can't see myself spending the time to do it since I'd have to start from ground zero and I haven't a lot of free time lately.

**Comment by NoxInmortus** [comment]
Seems resolved by commit 0cc65231159991b9423b7df5a2f105ef3e8d8a7d
