### ISSUE TITLE
Pulling incorrect issue listing for annuals

### ISSUE THREAD

**Issue by war3zlod3r** [evilhero/mylar#2354]
**Describe the bug**
Magnificent Ms. Marvel is showing 8 annuals and listing issue #1 of the annual twice

**Screenshots/Logs**
[mylar - Copy.log](https://github.com/evilhero/mylar/files/3643578/mylar.-.Copy.log)

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - Branch / commit: Development

**Additional information**
Has similar issues with "Old Man Quill" but doing a refresh on that series removed the bogus issues.

**Comment by leaderdog** [comment]
I had that problem with Magnificent Ms. Marvel as well. 

Right above where the annuals are listed it shows you what Mylar is using for an annual.  So you can go ahead and delete the one that just says Magnificent Ms. Marvel and leave the one that has the word annual in it. (black X looking icon)

It then works correctly.

Not sure why it did that, that would be Evilhero's department.  but that's how you can fix it.

**Comment by war3zlod3r** [comment]
Thanks for the tip

**Comment by leaderdog** [comment]
I just want to do a follow up on this.  It fixed the index, but for some reason, I still had 8/15 in the main listing.  Even after a refresh, and restart of Mylar it still showed it was missing a bunch of files.  I did hit refresh on the series itself and that cleared up the main index.

**Comment by m00n22** [comment]
Same issue here

**Comment by evilhero** [comment]
Try deleting the series and re-adding it again - seems like it might be something related to CV. 

I just tried adding the Ms.Marvel one and it added fine with no duplication of annuals (was fully expecting it to, but can't reproduce atm at least). Only thing that is different for me vs you folks is that this was a new series add for me, and I believe yours are all existing watchlist series that are being refreshed (I also tried refreshing the series after the add, and still no duplication).

**Comment by war3zlod3r** [comment]
leaderdogs solution worked for me, although I did delete and readd prior to trying his solution

**Comment by JacksonB** [comment]
I'm experiencing this issue as well.

The Magnificent Ms. Marvel series has an Annual series that gets discovered automatically. But usually sometime the week a new issue is added, the Annuals list for the series will include the comic itself.

As mentioned by other comments you can trim the list of titles that are included in the Annuals but this has only ever been temporary. And as of this past week (Jan 8, 2020), removing the non-Annual title from the list of annuals has only been temporary.

Removing and re-adding the series from Mylar has about a 75% chance of adding everything as expected (1/4 times my Annuals list included the primary series).

I've attached the log where I've added the series to Mylar and near the end of the trimmed section, the "manualAnnual" thread is adding the wrong series to the Annual

`12-Jan-2020 09:15:50 - DEBUG   :: mylar.manualAnnual.968 : Thread-36 : 117593 added to series list as an Annual`
[ms-marvel-annual-bug.log](https://github.com/evilhero/mylar/files/4050842/ms-marvel-annual-bug.log)

Please let me know if there is any other info I can provide.

**Comment by war3zlod3r** [comment]
I too would like to see a fix for this

**Comment by leaderdog** [comment]
yeah, my solution ended up only being temporary.  Mylar keeps adding them at some point after I delete it.  Is a weird one.

**Comment by evilhero** [comment]
In looking at this some more, I realised that the comicid was being forced thru via the pullist - which had the comicid listed as an annuallink. I've fixed it on the backend now, so the series is pointed to the correct annual series on CV (instead of itself), so you shouldn't be getting any more of these circular references which is what's been causing the series to add itself over and over as annual.

**Comment by JacksonB** [comment]
Thanks for looking at it further. Because it isn't a release week for that series I'm not able to reproduce but if it shows up again I'll check back in here, otherwise assume solved.
