### ISSUE TITLE
Mako Runtime Error when clicking on Config

### ISSUE THREAD

**Issue by gitsnow** [evilhero/mylar#2356]
HI,

I just updated mylar to the latest dev version.  Everything starts up fine, but when I click on the config page i get a Mako Runtime Error.

Error !
KeyError: 'deluge_download_directory'
</div> <div class="row"> <label>Deluge Download Path</label> <input type="text" name="deluge_download_directory" value="${config['deluge_download_directory']}" size="30"><br/> <small>Where the torrent will be downloaded to</small> </div> <div class="row"> <label>Deluge Move Path</label> <input type="text" name="deluge_done_directory" value="${config['deluge_done_directory']}" size="30"><br/>
/opt/mylar/data/interfaces/default/config.html, line 678:
<input type="text" name="deluge_download_directory" value="${config['deluge_download_directory']}" size="30"><br/>
/opt/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/opt/mylar/mylar/webserve.py, line 57:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

Is this a variable that needs to be set in the mylar config.ini?

**Comment by evilhero** [comment]
Does your config.ini have a ```deluge_download_directory``` variable under the [deluge] section ? 
Are you using deluge with Mylar?
Can you confirm the commit version you're running of Mylar ? 

Normally when you start Mylar up, it will load up your config values from the config.ini - however if the ini entry doesn't exist (or it's in the wrong section if you manually added it), it might throw that error. I've seen that error also pop when it's being used behind a reverse_proxy, but not to the point where it indicates a specfic variable.

Also, please use the issue template for any new issues - keeps things cleaner, and saves us some time when answering/asking questions.

**Comment by gitsnow** [comment]
My config.ini doesn't have a deluge_download_directory variable.  I've been using Mylar for many years so my config may be out of date.

I'm not using deluge with Mylar, I'm using Sabnzbd.  

I'm using the Dev branch build 9fb9ab4d732fad1c181df54e419975e5ec823d2a

I tried adding the deluge_download_directory variable to the config.ini but the Mako error persists.  I'm wondering if I should just start over with a brand new config.ini at this point?

**Comment by evilhero** [comment]
Weird, when you start up Mylar it looks at your config.ini - if the config_version variable (should be near the top) is not current it will update your ini to the correct version.  If you're adding the deluge_download_directory option then you need to make sure that it's in the [deluge] section of the ini. But if you don't have any sections in the ini, then something's wrong and it might be easier to just move the ini out of the mylar directory and let it recreate a new one from scratch.

Is your ini file writable by the user running Mylar ?

**Comment by gitsnow** [comment]
I have a [Deluge] section with a capital D and that's where I added the deluge_download_directory variable.

I'm running Mylar on an Ubuntu 19.04 machine.  I'm using systemd to startup mylar automatically and its running under my user account.  My user account owns all of the files and directories under the mylar directory and has read/write access to the config.ini.

I checked the config.ini and its currently on config_version = 10.  What version should my config be on?

**Comment by evilhero** [comment]
Are you specifying a config location in your systemd file?

You can check what the config.ini file location mylar is using by going to the 1st tab of the configuration in the GUI.

Also 10 is the latest version of the config. Can you paste that deluge section of your ini (minus the keys obviously if anything is in there? I'm wondering if there's a blank line in there or something)

**Comment by gitsnow** [comment]
So I found out that when I try stopping or restarting mylar with systemd, the python process is still running.  I had to kill the process manually and then start mylar to get any changes to the config.ini to be recognized.  

After generating a new config.ini the config page opens normally now.  I re-added all my info and everything seems to be working normally again.
