### ISSUE TITLE
500 Internal Server Error When trying to view the weekly list

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2363]
I am getting the following error when trying to view this weeks list

> Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/src/mylar/mylar/webserve.py", line 1649, in pullist
    repoll = self.manualpull()
  File "/usr/local/src/mylar/mylar/webserve.py", line 1932, in manualpull
    weeklypull.pullit()
  File "/usr/local/src/mylar/mylar/weeklypull.py", line 361, in pullit
    comicnm = issname[1]
IndexError: list index out of range

I've read through the forums and have seen that this has been an issue in the past but none of the fixes seem to work.

Thanks

**Comment by evilhero** [comment]
In your config.ini (with mylar not running), make sure the alt_pull variable is set to 2 and not 0.

That error occurs when mylar attempts to use the fallback/alternate pull list site, which is pretty much broken. This tends to happen when the main pullist site is offline/unreachable and mylar tries to use the alternate site to ensure that there's data present in the pull list view.

**Comment by edimusxero** [comment]
alt_pull is already set to 2

Thanks

**Comment by evilhero** [comment]
Restart mylar then and do a recreate pullist from within the weekly tab. If that doesn't work, make sure you're referencing the correct ini as the only way that error occurs is if alt_pull is not set to 2 (or its stored in memory if it's running)

**Comment by edimusxero** [comment]
It's still doing it and I have confirmed that it is referencing the correct ini file.  I am going to try and reboot my modem and server and see what happens, maybe I have an internet issue at the moment
