### ISSUE TITLE
Unable to locate a valid cbr/cbz file. Aborting post-processing for this filename.

### ISSUE THREAD

**Issue by timmyrocks26** [evilhero/mylar#2365]
**Describe the bug**
Everything I download fails to post-process. I get the error unable to locate a valid cbr/cbz file.
Scanning my comic library also does not seem to find any CBR/CBZ files

**Screenshots/Logs**
see log file attached

**Environment (please complete the following information):**
 - OS: MAcOS Catalina
Mylar Version: development
-- git build 36f544b6d9455d0f2a4b2eb91ae3a762b558c3de.
Python Version : 2.7.16
Language : en_US.UTF-8

Thank you so much for your time!

T.

[mylar.log](https://github.com/evilhero/mylar/files/3781811/mylar.log)

**Comment by timmyrocks26** [comment]
Thank you for your response.

all permissions are allowed for this directory and its contents.
I also verified that all the files I have tried to download are valid cbr/cbz files and they are.

drwxrwxrwx  16 timrogers  staff   512B 30 Oct 19:25 comics
and
-rw-rw-rw-   1 timrogers  staff    26M 29 Oct 12:08 Batman v3 081 (2019) (Webrip) (The Last Kryptonian-DCP).cbr

and I am logged in as user timrogers

very confused. My hard rive died so this is a brand new install of macOS Catalina, Sab, Mylar, et all
prior to this everything worked spectacularly!

**Comment by Onetimejoe** [comment]
I am having the same issues since upgrading to macOS 10.15

It seems to be a permissions issue, but I can’t figure out how to give Mylar the permissions it needs to the directory.

**Comment by Onetimejoe** [comment]
Just found a solution. I went into the security & privacy settings in the system preferences then to the “privacy’ tab then “full disk access” then selected python 2.7 to  have access.  

Problem solved.

**Comment by timmyrocks26** [comment]
Yes, that was the solution for me too! 
thank you so much to both of you for this!
