### ISSUE TITLE
Not finding any new issues

### ISSUE THREAD

**Issue by the-Dakta** [evilhero/mylar#2368]
**Describe the bug**
Searching for any wanted series just says that it can't find any matching issues.

**Screenshots/Logs**
https://pastebin.com/1vQRtLjv
https://pastebin.com/Sueq1YzH

**Environment (please complete the following information):**
 - OS:  Distro.......: Ubuntu 18.04.2 LTS
  Kernel.......: Linux 5.0.0-31-generic
 - Branch / commit: development
-- git build 36f544b6d9455d0f2a4b2eb91ae3a762b558c3de.

**Additional information**
 I've done manual searches on my tracker and can find many of them no problem. Logs: https://pastebin.com/1vQRtLjv

Much of my log is also filled with this: https://pastebin.com/Sueq1YzH

**Comment by barbequesauce** [comment]
Can you please post the log file from disk, rather than copy & paste the logs webpage contents? There's additional details in the file that don't show in the GUI.

**Comment by the-Dakta** [comment]
[mylar.log](https://github.com/evilhero/mylar/files/3841709/mylar.log)

**Comment by barbequesauce** [comment]
Looks like your jackett configuration is incorrect....

`[ERROR CODE: 201] iptorrents does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
`

**Comment by the-Dakta** [comment]
I ended up removing jackett config and just sticking with 32pages and have the same issue. All before I sent that log.

**Comment by barbequesauce** [comment]
In the same log?

**Comment by the-Dakta** [comment]
Yes. Before sending any logs here, I had already disabled Jackett, restarted, and initiated a search using only 32pages login.

**Comment by barbequesauce** [comment]
Hmmm...

```
11-Nov-2019 20:22:09 - INFO    :: mylar.searcher.2122 : SEARCH-QUEUE : Found Rick and Morty (2019) #55 using 32P
11-Nov-2019 20:22:09 - INFO    :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Rick and Morty
11-Nov-2019 20:22:11 - INFO    :: mylar.authenticate.123 : SEARCH-QUEUE : [32P] Successfully authenticated.
11-Nov-2019 20:22:11 - INFO    :: mylar.authenticate.128 : SEARCH-QUEUE : [32P-AUTHENTICATION] Attempting to integrate with all of your 32P Notification feeds.
11-Nov-2019 20:22:13 - INFO    :: mylar.torsend2client.1251 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
11-Nov-2019 20:22:13 - INFO    :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /opt/appdata/Mylar/cache/Rick_and_Morty_55_2019.torrent
11-Nov-2019 20:22:13 - INFO    :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
11-Nov-2019 20:22:13 - INFO    :: mylar.get_torrent.55 : SEARCH-QUEUE : Successfully located information for torrent
11-Nov-2019 20:22:13 - INFO    :: mylar.load_torrent.82 : SEARCH-QUEUE : load_torrent: Torrent already exists!
11-Nov-2019 20:22:13 - INFO    :: mylar.torsend2client.1259 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
11-Nov-2019 20:22:13 - ERROR   :: mylar.searcher.2415 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
```


```
11-Nov-2019 20:25:09 - INFO    :: mylar.NZB_SEARCH.513 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Lumberjanes issue: 67 (2019) using 32P.
11-Nov-2019 20:25:12 - INFO    :: mylar.searcher.2122 : SEARCH-QUEUE : Found Lumberjanes (2019) #67 using 32P
11-Nov-2019 20:25:12 - INFO    :: mylar.torsend2client.964 : SEARCH-QUEUE : matched on Lumberjanes
11-Nov-2019 20:25:14 - INFO    :: mylar.torsend2client.1251 : SEARCH-QUEUE : Connected to qBittorrent! Will try to add torrent now!
11-Nov-2019 20:25:14 - INFO    :: mylar.load_torrent.62 : SEARCH-QUEUE : filepath to torrent file set to : /opt/appdata/Mylar/cache/Lumberjanes_67_2019.torrent
11-Nov-2019 20:25:14 - INFO    :: mylar.load_torrent.65 : SEARCH-QUEUE : Checking if Torrent Exists!
11-Nov-2019 20:25:14 - INFO    :: mylar.get_torrent.55 : SEARCH-QUEUE : Successfully located information for torrent
11-Nov-2019 20:25:14 - INFO    :: mylar.load_torrent.82 : SEARCH-QUEUE : load_torrent: Torrent already exists!
11-Nov-2019 20:25:14 - INFO    :: mylar.torsend2client.1259 : SEARCH-QUEUE : Unable to add torrent to qBittorrent
11-Nov-2019 20:25:14 - ERROR   :: mylar.searcher.2415 : SEARCH-QUEUE : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
```

Are you sure communication to qBT is working?

**Comment by the-Dakta** [comment]
When I test the connection, it comes back successful. I checked a few of those that said they were already there, and they are. Those are from when I was having issues before and tried to use FlexGet instead. I just have those series still seeding.

**Comment by barbequesauce** [comment]
Okay - so can you provide an example of something not being found that exists on 32p?

**Comment by evilhero** [comment]
I don't understand - it found the issue on 32p, tries to send it to your torrent client, but it says it already exists in your client so it can't add it. 

It doesn't fail during the search at all, but during the attempt to add the torrent to your torrent client. If you download items outside of mylar, it only tracks/monitors what it knows.

**Comment by the-Dakta** [comment]
So I tested out a few random ones, here are some examples:

7 Miles A Second
Blacklung
All you need is Kill
Field Tripping
Deadenders

I searched each of these as they are listed in mylar and found all issues on 32pages. To test this for the purpose of this troubleshooting I then checked only these series to force check for them. Here is the result log:

[mylar.log](https://github.com/evilhero/mylar/files/3843655/mylar.log)

I am sure there are other series with the same problem, I just used these as an example.

**Comment by barbequesauce** [comment]
Field Tripping - #3 is not on 32p as of my writing this.

7 Miles a Second, Blacklung, All you need is Kill, Field Tripping, and Deadenders do not appear in this log.

**Comment by the-Dakta** [comment]
Alright well I don't know why those aren't showing up, I think I just misunderstood checking certain series before hitting Force Check. It definitely seems to at least not look for quite everything

At this point, it's whatever. I'll just live with and read what I've got and collect stuff manually.
