### ISSUE TITLE
TypeError: string indices must be integers when trying to add new comic series

### ISSUE THREAD

**Issue by hwwilliams** [evilhero/mylar#2371]
**Describe the bug**
Whenever I try to add any comic series I get this error in the logs, this specifically was when I was trying to add Batman: Last Knight on Earth to wanted list.

**Screenshots/Logs**
```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/importer.py", line 62, in addComictoDB
comlocation = os.path.dirname(imported['filelisting'][0]['comiclocation'])
TypeError: string indices must be integers
```

**Environment (please complete the following information):**
 - OS: [e.g. Docker Image: linuxserver/mylar]
 - Branch / commit: Version: 5ffe8fbd3080e11884c6d11ad3aacbc9f6a73cb3 ((HEAD detached at 5ffe8fb))
 - Python Version : 2.7.16

**Comment by evilhero** [comment]
On what screen were you trying to add the series from ? 
As per our issue template, pasting an exception isn't enough information as we need to see the context leading up to the error. 

Please post the debug log leading up to and showing the error and we can go from there.
