### ISSUE TITLE
[Config Help Request]

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#2373]
So I am using transmission in a docker and mylar also in docker but in another one.
Anyone else doing that and able to help me out with the config ?
So far I told mylar to enable torrent download and it grabs some but it puts them in mylar cache folder and they are not sent to transmission.
Both are on the same network

Mylar config :
/downloads refers to /volume1/Downloads/Comics
Transmission host : http://transmission:9091
User : xxxx
Pass : xxxx
Directory : /downloads

How is mylar supposed to communicate with transmission ? Does it connect to it and tell transmission the path to cache folder ? In which case i would need to link the cache folder to transmission with the exact same path.
What is supposed to be transmission directory ? The path as seen by transmission where it should put the download ? The path as seen by mylar where it should put the download ? Both ? In which cas the path should be seen as exactly the same by both dockers.

Maybe it would be nice to have a remote path link option or so for those running things dockerized.

**Comment by barbequesauce** [comment]
Assuming you're using the native client and not blackhole, Mylar speaks to the Transmission API. Your dockerfile on the transmission side should expose 9091...
