### ISSUE TITLE
made a Mylar config.ini change for a path issue and

### ISSUE THREAD

**Issue by jedimole** [evilhero/mylar#2377]
So for a year or so Mylar has been working with this error in the log file

07-Dec-2019 17:30:21 - INFO    :: mylar.validateAndCreateDirectory.1691 : MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Mylar
07-Dec-2019 17:30:21 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
**07-Dec-2019 17:30:22 - ERROR   :: mylar.runGit.55 : MAIN : ['C:\Program' is not recognized as an internal or external command,

operable program or batch file.

] Unable to find git with command: C:\Program Files\Git rev-parse HEAD**
07-Dec-2019 17:30:22 - INFO    :: mylar.versionload.311 : MAIN : Version information: development [7e8025c5f6ccc35573e1ed69b2dca90cc159245b]

Which lead me to the config.ini where I added the close of the path due to path statement
[Git]
git_user = evilhero
check_github = True
git_path = 'C:\Program Files\Git'
check_github_on_startup = True
git_branch = development

Now when it starts up it says unknown version
07-Dec-2019 17:37:23 - INFO    :: mylar.validateAndCreateDirectory.1691 : MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Mylar
07-Dec-2019 17:37:23 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
07-Dec-2019 17:37:24 - ERROR   :: mylar.getVersion.93 : MAIN : Output does not look like a hash, not using it
07-Dec-2019 17:37:24 - INFO    :: mylar.versionload.311 : MAIN : Version information: development [None]
07-Dec-2019 17:37:26 - INFO    :: mylar.checkGithub.203 : MAIN : You are running an unknown version of Mylar. Run the updater to identify your version

But it appears to be working?!  Should I go back to a bad path where it does identify properly?
Web UI now shows
Mylar Version: development
-- git build None.
Python Version : 2.7.9
Language : en_US.cp1252

**Comment by evilhero** [comment]
Pretty sure that you need to provide the full path to the git executable. So it needs to be ```'C:\Program Files\Git\Git.exe'``` - otherwise as what you have provided in the logs, Mylar would try to execute it as ```C:\Program Files\Git.exe``` (capitalization doesn't matter in Windows).

If you had git in your Windows environment path, you could leave that entire git_path field empty and Mylar would call the command as given within the environment path.

**Comment by jedimole** [comment]
DID the full path in the ini, as there is no git.exe in the root

[Git]
git_user = evilhero
check_github = True
git_path = 'C:\Program Files\Git\bin\git.exe'
check_github_on_startup = True
git_branch = development

and still the same thing
08-Dec-2019 16:21:23 - INFO    :: mylar.validateAndCreateDirectory.1691 : MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Mylar
08-Dec-2019 16:21:23 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
08-Dec-2019 16:21:24 - ERROR   :: mylar.getVersion.93 : MAIN : Output does not look like a hash, not using it
08-Dec-2019 16:21:24 - INFO    :: mylar.versionload.311 : MAIN : Version information: development [None]
08-Dec-2019 16:21:25 - INFO    :: mylar.checkGithub.203 : MAIN : You are running an unknown version of Mylar. Run the updater to identify your version

**Comment by evilhero** [comment]
How was it installed - by git or source?

**Comment by jedimole** [comment]
Man that's a good question and I cannot even tell you anymore as its been running for 2 plus years!  Let me try Verbose

**Comment by evilhero** [comment]
It should say the important stuff on the 1st tab of the configuration page.

**Comment by jedimole** [comment]
Took it back to the way it was and verbose is on.  It works with the ini messed up!  The path is to git\cmd

08-Dec-2019 16:45:43 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
08-Dec-2019 16:45:44 - ERROR   :: mylar.runGit.55 : MAIN : ['C:\Program' is not recognized as an internal or external command,

operable program or batch file.

] Unable to find git with command: C:\Program Files\Git\bin\git.exe rev-parse HEAD
08-Dec-2019 16:45:44 - INFO    :: mylar.versionload.311 : MAIN : Version information: development [2cd1f876ee9e756a1f98cdbc67a3fbe6021c8454]
08-Dec-2019 16:45:46 - INFO    :: mylar.checkGithub.198 : MAIN : Mylar is up to date
08-Dec-2019 16:45:46 - INFO    :: mylar.start.356 : MAIN : DB Updater sccheduled to fire every 5 minutes
08-Dec-2019 16:45:46 - INFO    :: mylar.queue_schedule.525 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
08-Dec-2019 16:45:46 - INFO    :: mylar.queue_schedule.528 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
08-Dec-2019 16:45:46 - INFO    :: mylar.queue_schedule.536 : MAIN : [POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
08-Dec-2019 16:45:46 - INFO    :: mylar.queue_schedule.539 : MAIN : [POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
08-Dec-2019 16:45:46 - INFO    :: mylar.start.405 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
08-Dec-2019 16:45:46 - INFO    :: mylar.start.436 : MAIN : [RSS-FEEDS] Initiating startup-RSS feed checks.
08-Dec-2019 16:45:46 - INFO    :: mylar.start.439 : MAIN : [RSS-FEEDS] RSS last run @ 2019-12-08 20:23:09.653000
08-Dec-2019 16:45:46 - INFO    :: mylar.start.463 : MAIN : [FOLDER MONITOR] Enabling folder monitor for : E:\Media\Books _ Comics every 600 minutes.
08-Dec-2019 16:45:47 - INFO    :: mylar.start.471 : MAIN : Firing up the Background Schedulers now....
08-Dec-2019 16:45:47 - INFO    :: mylar.start.475 : MAIN : Background Schedulers successfully started...
08-Dec-2019 16:46:08 - INFO    :: mylar.forceRescan.951 : Thread-12 : [FILE-RESCAN] Now checking files for Action Comics (2011) in e:\media\comics\Action Comics (2011)
08-Dec-2019 16:46:08 - INFO    :: mylar.traverse_directories.1474 : Thread-12 : there are 54 files.
08-Dec-2019 16:46:10 - INFO    :: mylar.forceRescan.1505 : Thread-12 : [FILE-RESCAN] Total files located: 54
08-Dec-2019 16:46:10 - INFO    :: mylar.forceRescan.1614 : Thread-12 : [FILE-RESCAN] I have physically found 54 issues, ignored 0 issues, snatched 0 issues, and accounted for 6 in an Archived state [ Total Issue Count: 60 / 60 ]
08-Dec-2019 16:47:42 - ERROR   :: mylar.runGit.55 : CP Server Thread-6 : ['C:\Program' is not recognized as an internal or external command,

operable program or batch file.

] Unable to find git with command: C:\Program Files\Git\bin\git.exe log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5
08-Dec-2019 16:47:42 - ERROR   :: mylar.runGit.55 : CP Server Thread-6 : ['C:\Program' is not recognized as an internal or external command,

operable program or batch file.

] Unable to find git with command: C:\Program Files\Git\bin\git.exe rev-parse HEAD
