### ISSUE TITLE
BUG: Clickable index only uppercase

### ISSUE THREAD

**Issue by Djangox** [evilhero/mylar#2381]
**Describe the bug**
Clicking on a letter only shows titles that begin with uppercase. For example when I hover over "I (eye)" it tells me there are 5 entries. But when I click it I get "no matching records found". It doesn't list the 5 "iZombie" titles that are there. Clicking "none" and typing "iz" in filter does bring up the expected titles. I don't know if it's just the letter "i" or any lowercase letters.

**Environment (please complete the following information):**

    OS: Synology DSM 6.2.2
    Branch / commit: master / 5ffe8fbd3080e11884c6d11ad3aacbc9f6a73cb3

**Comment by Djangox** [comment]
hi there. I updated to cbb89e1b603a10f037363b4e94bca82b3c69d9e3 in development branch, but still no change. Lowercase title still not shown when clicking letter. Anything I can give you?

**Comment by barbequesauce** [comment]
[Stay tuned](https://datatables.net/forums/discussion/59712/alphabetsearch-bug-with-mixed-case#latest)...

**Comment by barbequesauce** [comment]
Hopefully this does the trick - I missed this entirely. Works on my test rig...

**Comment by Djangox** [comment]
Confirmed working here. THANKS MUCH!
