### ISSUE TITLE
Mistaking covers for issues?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2384]
Uploaders are commonly posting Cbr files of variant covers only, and Mylar is downloading them as issues. Here’s an example:

Avengers.009.David.Marquez.2nd.Printing.Variant.2018cover.onlyDigitalPeteThePIPster-Novus

I can’t get Mylar to search for and grab the actual issue. Is this a bug or something I’m doing wrong?

**Comment by BRTPOB** [comment]
Set the minimum size to something like 5mb.
