### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by professionaltart** [evilhero/mylar#2390]
**Describe the bug**
I tried to update when away from home for a week and it wouldn't.  Just got home and tried again, same issue, nothing in logs about it.  Tried to grab the latest dev branch zip and manually extract (with service stopped via nssm).  Same issue - restart mylar and it's using an older dev build.

**Screenshots/Logs**
[code]git pull
error: Your local changes to the following files would be overwritten by merge:
        data/js/alphabetSearch.js
        mylar/filechecker.py
        mylar/helpers.py
        mylar/webserve.py
Please commit your changes or stash them before you merge.
Aborting
Updating cbb89e1..85f2959 [/code]

**Environment (please complete the following information):**
 - OS: Win10
 - Branch / commit:  Dev[cbb89e1] FIX:(#2372) Fix for file parser not picking up titles in the Series (Year) Issue format in some cases {10 days ago/evilhero}

**Additional information**
I suspect if I just delete those specific files, and then git pull or extract the zip again, it'll work?  Just weird, because the zip overwrote everything 🤷‍♀️

**Comment by professionaltart** [comment]
I tried deleting those files, and then another git pull, but it complained about .gitignore

Deleted most of the mylar subdir apart from settings and db and then it complained there was no git repository, nor .git folder.  Extracted fresh from the latest dev zip, and... it's back to the same (read: not latest) version.

**Comment by evilhero** [comment]
Looks like you did a git install initially, then did a source (zip) download - overwrote the files, and then tried to do a git pull again and it's saying it can't cause the zip overwrote everything which makes it not in sync with the git.

I think if you do a ```git fetch --all``` followed by a ```git reset --hard origin/development``` will force it to pull the latest stuff from git, and then hammer any local changes with the updated stuff. Keep in mind that if you did do any local changes (ie. you changed some of the .py files for whatever reason), those will be lost in the above commands.

Failing that, backup your config.ini, mylar.db and entire cache folder. Then wipe out the entire mylar directory, and then do a ```git clone https://github.com/evilhero/mylar.git -b development``` to bring down a fresh git install. Then move back the stuff you moved off above, and you'll be good to go.

**Comment by professionaltart** [comment]
Thanks, evilhero.  It normally just updates fine, but I don't remember if I've been grabbing the zip for problem manual updates, or using git - tho' I'm trying to get more familiar with the git CLI, so I'll try and stick with that going forward.
