### ISSUE TITLE
Some comics are not making it into the comic title folders 

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2396]
**Describe the bug**
I get these extra folders, and it’s a PITA to organize. I *think* I have the files properly downloaded into their title folders, but I can’t say for sure. How do I stop these extra folders from being created

**Screenshots/Logs**
You can see here in the comic reader app CHUNKY, I have the proper folder with all the comics inside, but then in my general downloads directory, I have all these extra separate folders also with comics inside. How do I stop this behavior? I also included a quote from what I believe is the relevant log entry.

```

2020-01-09 22:58:43 | INFO | [DUPECHECK] Duplicate check for E:\OneDrive - b\Comics\Amazing.Spider-Man.037.2020.Digital.Zone-Empire\Amazing Spider-Man 037 (2020) (Digital) (Zone-Empire).cbr
-- | -- | --
2020-01-09 22:58:35 | INFO | Now loading from post-processing queue: {'issueid': u'732873', 'apicall': True, 'nzb_name': u'Amazing Spider-Man 037 (2020) (Digital) (Zone-Empire).cbr', 'nzb_folder': u'E:\\OneDrive - b\\Comics\\Amazing.Spider-Man.037.2020.Digital.Zone-Empire', 'failed': False, 'ddl': False, 'comicid': u'112161'}
2020-01-09 22:58:34 | INFO | location found @ E:\OneDrive - b\Comics\Amazing.Spider-Man.037.2020.Digital.Zone-Empire\Amazing Spider-Man 037 (2020) (Digital) (Zone-Empire).cbr

```
Primary folder containing files (good):
![0E76B0AA-9CA3-47C6-9C41-3DA9314DDD7F](https://user-images.githubusercontent.com/97095/72163300-961d5280-3391-11ea-9ecf-ad7913e0cb5e.jpeg)
Undesired separate issue folders and files:
![21030DC2-A2F3-45CB-832A-4E6CFFC78FE0](https://user-images.githubusercontent.com/97095/72163301-961d5280-3391-11ea-82ba-e9e8ac82a87a.jpeg)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Branch / commit: Mylar Version: development
-- git build 4f8943b5b5680f47097c4048ebd342ca66c21a01.

**Additional information**
Let me know if I need to try and catch it with debug on

**Comment by evilhero** [comment]
Mylar probably doesn't have permissions to delete on the onedrive itself, so after it post-processes an item it can't clean up after itself and remove the original directory + file.

Debug logs showing a post-processing (I'm assuming that's what you're inquiring about) would help, and would probably show that it's failing to perform the tidy up call due to an error or some kind.

**Comment by AtariBaby** [comment]
Still waiting for it to happen again! I did see what looked like one of those folders, after a manual search of an issue, and then the folder disappeared, and the issue was in its correct folder. I’ll keep watch!

**Comment by AtariBaby** [comment]
Hi,

Caught one! In my finished directory is a separate folder, the contents of which appears to be a duplicate file of the comic in the “Revenge of the Cosmic Ghost Rider” folder called Revenge.of.the.Cosmic.Ghost.Rider.001.2020.Digital.Zone-Empire

I am sorry for this big chunk of log. I tried to start at the first recent mention of the folder, and to the last. Let me know if it’s not in here, or how I can narrow it down better for you. I’m using a site other than pastebin because it exceeds their size and I don’t have Pro.

https://controlc.com/e7063c5c

**Comment by AtariBaby** [comment]
I have several folders now. Is there any sense of what the solution is?

**Comment by AtariBaby** [comment]
So I went on an exhaustive quest to resolve this issue, fixing permissions in any number of ways that I found in google searches, and I have finally come to the conclusion that if I put comic files in a folder and it’s on Mylar’s to-do list to download those files, those file will wind up in individually numbered folders in the main comic directory. If you are certain this is a permissions problem and have suggestions on how to fix it, I’m all ears. I do sometimes download the files myself after adding a comic, because it’s a mysterious amount of time as to when Mylar will look for them.

**Comment by AtariBaby** [comment]
Actually I have to correct myself. Mylar just downloaded a whole slew of comics I didn’t already have and put them in separate folders, and now reports them as as snatched. If anyone has ANY suggestions on how to correct this behavior please let me know. It’s essentially impractical to use at this point, since I can download issues myself and put them in the desired folders, saving me several steps correcting Mylar putting them in individual issue folders.

**Comment by evilhero** [comment]
You literally have your sabnzbd folder set to be your ComicLocation path according to your previous log file. You cannot do this. Set your Comic Location path to be something different. If you expect Mylar to be able to clean up items that are downloaded to a remote location (ie. OneDrive) - it probably cannot as they're either going to be locked as it's syncing, or it's permission. The logs state that it cannot perform the operation as it's not permitted. That's not mylar speaking - that's from the OS level. It's something with your configuration setup -but we need to see your config.ini probably (stripped of keys), in addition to a current log.

**Comment by AtariBaby** [comment]
Okay, let me look at that and come back.

It might be of interest to you that NZBhydra removes keys from logs automatically. Just mentioning in case you want to look at that.

**Comment by AtariBaby** [comment]
Ah thank you, I see that I do have a category for “comics” in sabnzbd that is the same. Do. I need to do away with the sabnzbd category all together, or just just give a different location, for those instances where I search for comics on my own and not through Mylar?

**Comment by AtariBaby** [comment]
I just added a comic as a test, after changing the sabnzbd comics category folder destination, and it downloaded the test properly. Fingers crossed!

**Comment by AtariBaby** [comment]
I think this is solved now. I gather I’m a source of frustration. I really do think this app is a marvel, no pun intended. I think from the developer side of things, of course you can’t do that! But to the end user, who doesn’t understand the underlying code, it’s not obvious at all. I have been with Mylar since its earliest days, and I honestly don’t know how I could have avoided some of these pitfalls. Thanks for being so patient with me!

**Comment by AtariBaby** [comment]
So I moved the comics category to be it's own folder. It still happens, but into the new folder. It seems to mostly happen with experimental, not with NZB Hydra (newznab) but that could be a coincidence.

**Comment by barbequesauce** [comment]
We need logs and current commit - assuming you're using the last version of mylar and not mylar3? Remember that only security patching is being done for mylar at this stage...

**Comment by AtariBaby** [comment]
Hi I didn’t know there was a new version of Mylar!
