### ISSUE TITLE
Py3: DBupdate type error line 86

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#2400]
```
13-Jan-2020 16:26:56 - DEBUG :: mylar.dbUpdate.84 : ThreadPoolExecutor-0_0 : Refresh sequence set to fire every 5 minutes for 7 day(s)
Job "DB Updater (trigger: interval[0:05:00], next run at: 2020-01-13 21:31:56 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/mylar.py3/mylar/updater.py", line 86, in dbUpdate
    for comic in sorted(comiclist, key=operator.itemgetter('LastUpdated'), reverse=True):
TypeError: '<' not supported between instances of 'str' and 'NoneType'
13-Jan-2020 16:31:56 - DEBUG :: mylar.dbUpdate.84 : ThreadPoolExecutor-0_0 : Refresh sequence set to fire every 5 minutes for 7 day(s)
Job "DB Updater (trigger: interval[0:05:00], next run at: 2020-01-13 21:36:56 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/mylar.py3/mylar/updater.py", line 86, in dbUpdate
    for comic in sorted(comiclist, key=operator.itemgetter('LastUpdated'), reverse=True):
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by ArathoN** [comment]
These errores are because you are using python 3.x
If you read the project frontpage under requirement, you'll notice:
`**At least Python version 2.7.9 (3.x is not supported)**`

**Comment by mylar3** [comment]
@ArathoN , we know - barbequesauce is one of the devs helping with the transition to python3. He was just logging some of the errors we've encountered so we could track it, but these will all be moved to the mylar3 fork to keep things separate regardless. 
Cheers!

**Comment by evilhero** [comment]
@ArathoN , we know - barbequesauce is one of the devs helping with the transition to python3. He was just logging some of the errors we've encountered so we could track it, but these will all be moved to the mylar3 fork to keep things separate regardless.
Cheers!

**Comment by ArathoN** [comment]
@evilhero Cool, I didn't know this. I was setting up again mylar on windows and when i saw these issues I decided to "help" (because the first time I had the same "issue" because I didn't bother to read all the requirements).  
Anyway I'm glad you are working to migrate to the latest version and thank you for this awesome project.

**Comment by BRTPOB** [comment]
@ArathoN don't listen to him. He's full of it. @barbequesauce is just a putz.

**Comment by barbequesauce** [comment]
Don’t you have QA work to do?

**Comment by ArathoN** [comment]
@BRTPOB @barbequesauce @evilhero  AHAHAHAHAH!!! I love you all
