### ISSUE TITLE
Attempting to change Directory Location to invalid path results in blank page

### ISSUE THREAD

**Issue by SenorSmartyPants** [evilhero/mylar#2404]
**Describe the bug**
Attempting to change Directory Location to invalid path results in blank page.

**Comment by evilhero** [comment]
What screen are you changing the Directory Location ? 
Browser?  OS ? Branch ? Commit ? (broken record.)

**Comment by SenorSmartyPants** [comment]
Click into comic details. Click Edit Series, change Directory location to /path/does/not/exist, click update.

Chrome Version 79.0.3945.117
Mylar LSIO docker container.

master branch
git build d1ff6079a0d1994272fd441736fc27ee2c8084d1
-most recent item from "branch history"
[d1ff607] Merge branch 'development' {2 weeks ago/evilhero}

**Comment by evilhero** [comment]
FYI: You can also set ```create_folders = False``` in your config.ini, and it would not attempt to create/rename any existing folders but it would change the series location within the dB itself (and then create it when required).
