### ISSUE TITLE
Adding new comics no longer works

### ISSUE THREAD

**Issue by FrankEBailey** [evilhero/mylar#2407]
**Describe the bug**
Any title I search for and then try to add goes to the "adding" screen and then just keeps refreshing that page with "none" next to the ID. The title doesn't get added. Also my version build says "None"??

**Screenshots/Logs**
![Screenshot_2020-01-26 Mylar - Comic ID 40266](https://user-images.githubusercontent.com/273418/73139768-08708100-407a-11ea-9037-983d5d9b6805.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: Mylar Version: master -- source build None. (??!)

**Comment by evilhero** [comment]
Source installs will not put the git commit as it can't link the two as is (I believe we have it working in the python3 version however). So the None part is actually normal for source installations I believe.

In order to see what's happening, we'll need to see the debug logs showing what happens when you try to add a series. It could be a CV problem, or a network related problem, or some other issue - but without seeing the log we haven't a clue.

**Comment by FrankEBailey** [comment]
Sorry, I'm struggling to get the latest debug log. All I see in the log folder is a log from much earlier in the day.

The only error I see in the onscreen log this this:

Uncaught exception: Traceback (most recent call last):
File "q:\Mylar\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "q:\Mylar\mylar\importer.py", line 218, in addComictoDB
comlocation = dothedew.folder_create()
File "q:\Mylar\mylar\filers.py", line 130, in folder_create
comlocation = re.sub('/', '\\', comlocation)
File "C:\Python27\lib\re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "C:\Python27\lib\re.py", line 286, in _subx
template = _compile_repl(template, pattern)
File "C:\Python27\lib\re.py", line 273, in _compile_repl
raise error, v # invalid expression
error: bogus escape (end of line)

**Comment by evilhero** [comment]
You probably have an incorrect slash in either your folder format string or your comic location path. What are they set to right now ?

**Comment by FrankEBailey** [comment]
Well knock me over with a feather. The folder format was set to use forward slashes, I changed it to backslashes and it's working fine now. Thanks so much for taking time out of your Sunday to help me out, it's really appreciated!
