### ISSUE TITLE
Unable to import comics

### ISSUE THREAD

**Issue by ErenPhayte** [evilhero/mylar#2412]
Hi,

I newly setup Mylar however it doesn't save the import comics information - also it scans all the comics, but nothing is imported. If I restart Mylar, everything is reset back and I have to put in the "folder to scan" again, and again nothing gets imported although it does seem to run through all the comics and reads the metadata, it doesn't seem to do anything else with it.

**Comment by evilhero** [comment]
After the initial scan completes, you should see the numeric results of the scan on that same page. If there was at least one item that can be imported, on that same page/tab, you'll see a button appear in the lower right hand side called Import Results Management. You need to go into that option and select the series that you wish to import (or do a Bulk Import). The Auto-Add option on the main import screen does not work as intended, so once the import scan completes, you need to go into the Import Results Management screen to see what Mylar recognised and if there were any issues that didn't scan in.

If the button doesn't appear for whatever reason, you can find the ImportResults Management option under: ```Manage tab / Advanced Options / Import Management```.

**Comment by ErenPhayte** [comment]
thanks, it was having some troubles, so I deleted the primary DB file and started again. Then it worked.
I had to manually edit the INI file because the settings wouldnt save any other way.

**Comment by ErenPhayte** [comment]
Okay, also found that when its all imported and I go to Import Results Management .. it hangs. It looks like its trying to get a large number of results in an un-paged result set. Would it be possibly to build in pagination here so its quicker to access data?
