### ISSUE TITLE
Mylar does not recognize torznab search providers

### ISSUE THREAD

**Issue by tolusonaike** [evilhero/mylar#2431]
**Describe the bug**
I suspect Mylar is not recognizing my torznab configuration. To test, i turned off nzb and trying to use **only** torznab, i get the error below

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/253270/76685676-a0530b80-65e3-11ea-98d1-ecc8797db652.png)

 mylar.log14-Mar-2020 15:57:36 - ERROR   :: mylar.csv_load.1366 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar

14-Mar-2020 15:57:37 - WARNING :: mylar.searchforissue.1875 : Thread-12 : There are no search providers enabled atm - not performing an RSS check for obvious reasons

14-Mar-2020 15:59:37 - WARNING :: mylar.searchforissue.1877 : SEARCH-QUEUE : There are no search providers enabled atm - not performing an Force Check for obvious reasons

**Environment (please complete the following information):**
 - linuxserver/mylar: #https://github.com/linuxserver/docker-mylar/commit/0d7f1d0fa2c176c4871075395232063e8a216890
 - master/ Version: 94dcfd13f6c8be5836ca76324ebbe585bda642fc (master)

**Comment by evilhero** [comment]
We've pretty much migrated to the python3 fork located [here](https://github.com/mylar3/mylar3), and while I realise that you're using a docker, it bears mentioning that we've frozen the codebase on mylar save for critical bugs until such time as we deem it EOL.

That being said, without the debug logs it's hard to see what's the problem - so you'll have to pastebin/paste those in if you can (make sure to strip the apikeys, etc - as that functionality is not in this version of Mylar). If you're uncomfortable pasting the log, you can just throw it to me. Either way, I can look more into it when I'm able to see the debug log showing the workflow (ie. Start of search to warning message indicating no providers).

**Comment by tolusonaike** [comment]
@evilhero  debug logs (let me know if this isnt what you where expecting): https://pastebin.com/hhyw4Fsv 
config.ini: https://pastebin.com/qDLfnWaG
