### ISSUE TITLE
Lost Collection - Mylar not downloading old Wanted comics

### ISSUE THREAD

**Issue by Serneum** [evilhero/mylar#2432]
**Describe the bug**
I recently had a hard drive issue and lost my entire collection. Luckily, Mylar itself was on a separate drive, so I kept my configuration and DB. I was able to manually go through and set all of my previously downloaded comics to Wanted (admittedly through scripting and hitting the same endpoint that Manage Issues uses), but none of the old comics seem to actually get searched for unless I manually go in to each comic and hit the Search icon again. This is obviously pretty tedious and I'm wondering if this issue has come up before and how I might go about searching for all of my old comics again.

**Screenshots/Logs**
I left debugging on overnight and both runs of the Auto-Search logged
```
19-Mar-2020 04:56:30 - INFO    :: mylar.run.28 : Thread-30 : [SEARCH] Running Search for Wanted.
19-Mar-2020 04:56:30 - INFO    :: mylar.searchforissue.1589 : Thread-30 : A search is currently in progress....queueing this up again to try in a bit.
19-Mar-2020 04:56:30 - DEBUG   :: mylar.job_management.3599 : Thread-30 : ReScheduled job: Auto-Search to 2020-03-19 14:56:30
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: Master / 94dcfd13f6c8be5836ca76324ebbe585bda642fc

**Additional information**
New comics seem to download fine. Also, some of the issues _did_ get searched when I initially marked each series under Manage Comics as `Recheck Files`, but it was only a select few issues in a small set of my series.

I was going to try moving to Mylar3 to see if it might solve my issue, but am not quite sure how to migrate to the newer version

**Comment by barbequesauce** [comment]
So those log snippets are telling us the search queue crashed at some point.

Since development is halted on the python2 version of Mylar, you're probably best moving to mylar3. 

git clone https://github.com/mylar3/mylar3

Then copy in your config.ini, mylar.db, and all the contents of the cache folder.

Make sure to edit the config.ini and change any paths pointing to the old mylar install - especially logs...

**Comment by Serneum** [comment]
Migrated to Mylar 3 and things appear to be searching properly for now. Thanks!
