### ISSUE TITLE
change search order to NZBHydra (nwznab) then experimental

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2433]
**Describe the bug**
Is it possible to change the order? I can't seem to figure out how.

**Screenshots/Logs**

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] windows 10 pro
 - Branch / commit:Version: de60a31fd74aa2840ef7b7cb70ddf03a526e2c86 (development

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
Shut Mylar down and edit your config.ini.

Find provider_order and set it to whatever order you prefer. As an example:

`provider_order = 0, 32p, 1, dognzb, 2, DDL, 3, Miatrix`

Where Miatrix is a newznab provider name...
