### ISSUE TITLE
Anonymize logs?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2434]
**Describe the bug**
more and more apps strip out the confidential stuff like api keys. would you guys be willing to add it to your roadmap?

**Screenshots/Logs**

**Environment (please complete the following information):**
Windows10
 - Branch / commit: Version: de60a31fd74aa2840ef7b7cb70ddf03a526e2c86 (development

**Comment by BRTPOB** [comment]
Already done. Any time I see that occurring, I hound evilhero to fix it.
