### ISSUE TITLE
Unable to Rename Files for 2010 Wonderland Annual (2010)

### ISSUE THREAD

**Issue by miracle152005** [evilhero/mylar#2436]
**Describe the bug**
Hi,
I am unable to to rename the files for 2010 Wonderland Annual (2010).
The File Format is $Series $Issue ($VolumeY)
The UI shows an error popup, but in the logs there are no error logs.
Could you please take a look.
Thanks.

**Screenshots/Logs**
Include a DEBUG log using the log files and do not paste from the GUI log.
Do not just paste a traceback/error.

[mylar.log](https://github.com/evilhero/mylar/files/4658231/mylar.log)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04 docker install
 - Branch / commit: 94dcfd13f6c8be5836ca76324ebbe585bda642fc

**Comment by evilhero** [comment]
Only critical bugs are being addressed in this version as per the README.md file. 

Please upgrade to the python3 branch located [here](https://github.com/mylar3/mylar3) and see if the issue exists on that. If it does, then you'll to resubmit an issue ticket but for that repo.
