### ISSUE TITLE
ComicRN PPFAILURE on all downloads after updating

### ISSUE THREAD

**Issue by Fruitfrog** [evilhero/mylar#2440]
**Describe the bug**
I have a issue after updating my containers
Everything was working well in the past, after an update at some point, every download now has the same error message when post processing.

**Screenshots/Logs**

INFO | Wed Jul 08 2020 18:28:38 | ComicRN: SyntaxError: invalid syntax
INFO | Wed Jul 08 2020 18:28:38 | ComicRN: ^
INFO | Wed Jul 08 2020 18:28:38 | ComicRN: print 'Download of "%s" has failed.' % (os.environ['NZBPP_NZBNAME'])
INFO | Wed Jul 08 2020 18:28:38 | ComicRN: File "/downloads/scripts/ComicRN.py", line 40

**Environment (please complete the following information):**
OS is :  Ubuntu 19.10 (GNU/Linux 5.3.0-62-generic x86_64)
I am running : Docker 19.03.11 on linux, amd64
Containers in use : 
linuxserver/nzbget:latest@sha256:61427722910390edf7b43bc865911a72f61b04aa1645cc90adadada66275ddeb
linuxserver/mylar:latest@sha256:c99865937a37a7cf4cc52a57bbff30ebf4be0a4aaca8131ae6b345e02d6a693d

**Additional information**
I have downloaded the latest ComicRN.py file off github and am still getting the error.
https://raw.githubusercontent.com/evilhero/mylar/master/post-processing/nzbget/ComicRN.py
https://raw.githubusercontent.com/evilhero/mylar/master/post-processing/autoProcessComics.py

**Comment by evilhero** [comment]
Latest iterations of nzbget seems to break a bunch of nzbget scripts that were built for python2. There's an issue on their github in regards to it. This really isn't an issue with the script itself, as it works fine under Python2. 

I'm guessing that you're executing python3 as just "python", so you might need to update the shebang at the top of the ComicRN script to point to your Python2 location.

Other than that, I'd suggest trying mylar3 as that's what we're mainly supporting as of now.

**Comment by Fruitfrog** [comment]
Thank you !
Ill fix the script to call the correct version to get things running again.
Ill at the same time try get MyLar3 up and running.
Much appreciated.
