### ISSUE TITLE
Missing icon_search.png

### ISSUE THREAD

**Issue by InStim** [evilhero/mylar#2444]
**Describe the bug**
icon_search.png 404 results in broken icon image on main Search and Story Arcs search results.

**Screenshots/Logs**
http://192.168.86.200:8090/searchit?name=broken
![Screenshot 2020-10-07 09 43 46](https://user-images.githubusercontent.com/282607/95339208-d1e23b80-0881-11eb-863e-1e6248a03d31.png)

http://192.168.86.200:8090/searchit?type=story_arc&name=Milk
![Screenshot 2020-10-07 09 44 34](https://user-images.githubusercontent.com/282607/95339241-dc043a00-0881-11eb-9657-9029286a876b.png)

Open Image in a New Tab: http://192.168.86.200:8090/interfaces/default/images/icon_search.png

404 Not Found
The path '/interfaces/default/images/icon_search.png' was not found.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cperror.py", line 416, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/interfaces/default/images/icon_search.png' was not found.")
Powered by CherryPy 18.6.0

**Environment (please complete the following information):**
 - OS: MacOS 10.13.6
 - Branch / commit: Version: v0.4.6 (master)

**Additional information**

**Comment by evilhero** [comment]
Please submit against the correct repo. 

This is the python2 version which is not supported any longer save for critical bugs. 

The mylar3 repo (which is what you are using) is [here](https://github.com/mylar3/mylar3)
