### ISSUE TITLE
Error during post process of last "Amazing Spider-Man" issue 50 LR

### ISSUE THREAD

**Issue by tomtom602** [evilhero/mylar#2445]
**Describe the bug**
Mylar can't post-process the last issue of Amazing Spider-Man. 
This issue is particular. It's numbered 50 LR

**Screenshots/Logs**
Uncaught exception: Traceback (most recent call last):
File "/usr/local/share/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/local/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/share/mylar3/mylar/PostProcessor.py", line 1749, in Process
self.Process_next(comicid, issueid, issuenumOG, ml, stat)
File "/usr/local/share/mylar3/mylar/PostProcessor.py", line 2254, in Process_next
if int(iss_decval) == 0:
ValueError: invalid literal for int() with base 10: 'LR'

**Environment (please complete the following information):**
 - OS: Freenas 11.3, Python 3.7.9
 - Branch / commit: master/ build 91fad59ce33d16b75084fcdbb9065b8e46a0c965

**Additional information**
Mylar has no issue in the wanted list to display this particular issue

**Comment by evilhero** [comment]
Wrong repo. This is the python2 version of mylar - you want ```https://github.com/mylar3/mylar3```, also this has been been brought up in the mylar3 repo already.
