### ISSUE TITLE
Mylar searches, finds, downloads best after a restart

### ISSUE THREAD

**Issue by 11001010111111101011101010111110** [evilhero/mylar#2448]
My Mylar hasn’t worked 100% ever. It works ok but it never downloads as well as when I restart it, after which it downloads a bunch of comics. Normally it only does so episodically day to day.

Can anyone help diagnose?

**Comment by barbequesauce** [comment]
This version is no longer supported. The supported version can be found here: https://GitHub.com/mylar3/mylar3
