### ISSUE TITLE
Cant add any comics via search or weekly pull list

### ISSUE THREAD

**Issue by Prymal** [evilhero/mylar#342]
I just moved over to a Linux Mint 14 install because i was having tons of issues with Windows and now I can't even add Action Comics, I have some pretty limited Linux skills so this might be something simple i just dont know about.

to install Mylar i pulled the Zip file from the Dev branch and extracted to my home directory then updated to the newest commit.

I verified that python 2.7.3 is installed to /usr/lib/python2.7

14-Apr-2013 06:19:14 - INFO :: Thread-14 : Now adding/updating: Action Comics
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/chad/Mylar/mylar/importer.py", line 96, in addComictoDB
    gcdinfo=parseit.GCDScraper(comic['ComicName'], comic['ComicYear'], comic['ComicIssues'], comicid)
  File "/home/chad/Mylar/mylar/parseit.py", line 160, in GCDScraper
    return GCDdetails(comseries=None, resultURL=resultURL, vari_loop=0, ComicID=ComicID, TotalIssues=TotalIssues, issvariation=issvariation, resultPublished=resultPublished)
  File "/home/chad/Mylar/mylar/parseit.py", line 211, in GCDdetails
    pyeartxt = pyearit.find(text=re.compile(r"Series"))
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by solspire** [comment]
To do a git install it's pretty easy => for you !!

from the 'nix command line =>  What is it ? Where ? how ? all people are not informaticien !
git clone https://github.com/evilhero/mylar.git

cd into the mylar directory to run the following commands:
git pull (you probably don't need to do this, but just in case)
git checkout development

start up Mylar - you're on the development branch :)
