### ISSUE TITLE
Feature request: Transmission for torrents

### ISSUE THREAD

**Issue by thebdizzle** [evilhero/mylar#606]
I run Mylar on a synology NAS and absolutely love it! But one feature I think would be great would be the ability to send torrents directly to transmission rather than use a watch folder. I'm not sure how the code works, but it's a feature that's available in sickbeard, headphones, couch potato etc. any chance of migrating this feature to Mylar? It would be much appreciated!

**Comment by Rick7C2** [comment]
Is there any news on this? This is something I would like as well.

**Comment by doucheymcdoucherson** [comment]
+1 for this!

**Comment by kingbobski** [comment]
+1 for this!
