### ISSUE TITLE
'Have' Progress Bar Not Updating

### ISSUE THREAD

**Issue by razambon** [evilhero/mylar#671]
This may be me doing something wrong - but it seems the 'have' progress bar isn't updating correctly for certain series (for met at least).  If I set it as 'downloaded' or 'archived' - the issues still show up as not had in the progress bar on the main page.

It's a minor issue, but it's a PITA when trying to identify what's missing, confirming the wanted list, etc.

**Comment by razambon** [comment]
So...just did a huge batch download of issues outside of mylar and marked stuff as "archived" via the "Wanted" interface and this bug reared it's head again.  Everything is marked as archived in the comic itself, and I tried rescanning it, but it's not updating the little bar at all.

**Comment by barbequesauce** [comment]
Good catch - that gives us a place to look.

Did you have a debug log by chance, capturing both?

**Comment by razambon** [comment]
Unfortunately, I do not have the log.

**Comment by evilhero** [comment]
Screenshot of the "clear"  please. Not sure the description you provided would do it justice at this point.

**Comment by razambon** [comment]
Sorry, I went through and had everything rescan last night to address it.  

Where it said "clear" was within a comic screen, under the status for a specific issue.  Note that it was that case as well (with a lower case c) and no i in a circle graphic/link either.  

Apologies for all the confusion around this.  If I can get something more definitive I'll get the info - otherwise please just ignore for now.
