### ISSUE TITLE
Batwoman (2011), Issue 0

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#809]
There are two 0 issues for this comic, 2011 and 2012. Mylar will pick up one or the other but not both. Manually adding and force recheck doesn't work nor does manually marking as downloaded. Latest dev build.

Suggestions?

**Comment by Aimhere2k** [comment]
Any update on this? 

For me, Mylar keeps downloading/adding "Batwoman 000 (2012)" (titled "Interlude") as issue 0 "Beyond a Shadow", while it marks issue 0 "Interlude" as "Archived", and nothing I do can convince it otherwise!

**Comment by evilhero** [comment]
Yeah this one I forgo about until a few days ago tbh. I have it working in my local repo (with those exact issues)  as well as the duplicate checking (if more than one issue exist in the series directory for a given issue, it will only scan in the one by file size or file type). 

Expect it in the next development commit, which is gonna go either tonight or tomorrow.

**Comment by Aimhere2k** [comment]
That's good. I have only one of the "issue 0" issues, the 2012 one, and 
the filename even says 2012, but Mylar keeps adding it as the file for 
the 2011 issue 0. Is there a way to manually designate the "issue 0" I 
do have as the 2011 comic?

**Comment by evilhero** [comment]
At this point there's nothing you can do to get it to recognize properly, until the code gets committed. 

The commit should go up sometime today, once I get back to a machine for longer than two minutes ;)
