### ISSUE TITLE
Mylar loses search Providers

### ISSUE THREAD

**Issue by Tstall** [evilhero/mylar#872]
Mylar will be working fine then all of a sudden I will get the error below that says I do not have any search providers enabled. I need to restart Mylar and it will work again.

2014-10-30 13:30:05	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.
2014-10-30 13:30:05	INFO	Issue Title given as : anniversary
2014-10-30 13:30:05	INFO	[SEARCH] altering ComicName to search-safe Name : Detective Comics Futures End
2014-10-30 13:30:05	INFO	Marking issues: [u'1'] as Wanted
2014-10-30 13:29:41	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.
2014-10-30 13:29:41	INFO	Issue Title given as : remains
2014-10-30 13:29:41	INFO	[SEARCH] altering ComicName to search-safe Name : Batman Futures End
2014-10-30 13:29:41	INFO	Marking issues: [u'1'] as Wanted
2014-10-30 13:29:27	INFO	Deleting all traces of Comic: Worlds' Finest: Futures End

**Comment by CptanPanic** [comment]
I just wanted to comment that I installed mylar today.  And had this same problem.  Without making any changes, my nzbproviders got lost.

Here is a grep of the log file, and you see that they just left.  I restarted mylar and they came back.

 nzbprovider: []
13-May-2015 20:05:42 - DEBUG   :: Thread-27 : nzbprovider: []
13-May-2015 20:06:18 - DEBUG   :: Thread-28 : nzbprovider: []
13-May-2015 20:09:18 - DEBUG   :: Thread-13 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:09:18 - DEBUG   :: Thread-13 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:09:18 - DEBUG   :: Thread-13 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:09:18 - DEBUG   :: Thread-13 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:12:54 - DEBUG   :: Thread-15 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:12:54 - DEBUG   :: Thread-15 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:12:54 - DEBUG   :: Thread-15 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:12:54 - DEBUG   :: Thread-15 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:08 - DEBUG   :: Thread-16 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:16:08 - DEBUG   :: Thread-16 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:08 - DEBUG   :: Thread-16 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:08 - DEBUG   :: Thread-16 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:10 - DEBUG   :: Thread-17 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:16:10 - DEBUG   :: Thread-17 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:10 - DEBUG   :: Thread-17 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:16:10 - DEBUG   :: Thread-17 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbprovider: ['experimental', 'newznab:My NZBs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:27:19 - DEBUG   :: Thread-21 : nzbproviders ['experimental', 'newznab:my nzbs.in']
13-May-2015 20:37:03 - DEBUG   :: Thread-27 : nzbprovider: []
13-May-2015 20:38:08 - DEBUG   :: Thread-29 : nzbprovider: []
13-May-2015 20:39:46 - DEBUG   :: Thread-30 : nzbprovider: []

**Comment by evilhero** [comment]
What were the instances of the threads running when they didn't exist? (thread 27,28,29,30). Something in one of those threads is resetting the provider order for some reason. 

I'm just going to ask - are you on the development branch?

**Comment by CptanPanic** [comment]
Yes I am on development branch, as per the ubuntu install instructions on the wiki.  I will have to look at the threads next time.  Seems that after restarting it everything is good, it was probably the first time I restarted it since adding the providers.

**Comment by evilhero** [comment]
Yes restarting / shutting down will always fix things like invalid provider order as the provider order always gets regenerated on startup. 

It's just really helpful to know which process within mylar is killing the existing provider order so I can try to fix things.. 

Thanks for the info and hopefully you can track down those threads next time.

**Comment by mnbf9rca** [comment]
i have this too. i'm on development branch too. restarting does not always fix the problem, or if it does, it reoccurs.

**Comment by evilhero** [comment]
It will only reoccur if configuration changes are done without restarting mylar. It also happens occasionally when an error occurs within mylar , and mylar again isn't restarted (this I have absolutely zero control over).

Blowing away the line in the config.ini. will always fix the problem, every time.

**Comment by mnbf9rca** [comment]
some apps have a reminder/warning to users that a restart is required. in Mylar for example, it says "Web Interface changes require a restart to take effect" - i take this to mean changes affecting the web interface (specifically, those on the "web interface" tab) - but does it mean "any change made via the web interface will only take effect after restarting Mylar"? If so - can we say that? And perhaps add a "save and restart now" button next to "save"?
