### ISSUE TITLE
Unable to complete Refreshing / Adding issue data - this WILL create future problems if not addressed.

### ISSUE THREAD

**Issue by duhasst** [evilhero/mylar#912]
Trying to add X-O Manowar (1992) http://www.comicvine.com/x-o-manowar/4050-4831/

I suspect it's failing because they have a #1/2 issue.  Looks like this happened with other series.

**Comment by duhasst** [comment]
awesome! thanks… let me know when I can git pull the changes.  Thanks for spending the time on this.

du

**Comment by evilhero** [comment]
Should be good to go - give it a try and let me know if things are working now for ya.

**Comment by JacksonB** [comment]
I started seeing this same error on Daredevil 2014 (http://www.comicvine.com/daredevil/4050-72417/). Looking at my series list showed the error. I tried updating, including the fix attached to this thread but I'm still seeing the error on that series.

I'm seeing this in the log file:

`01-Jan-2015 22:49:10 - DEBUG   :: Thread-13 : issuechk: None`
`01-Jan-2015 22:49:10 - DEBUG   :: Thread-13 : latestissueinfo: [{'latestiss': u'Error', 'latestdate': u'Error-Erro-01'}]`

**Comment by evilhero** [comment]
I didn't even notice that one - that's erroring out on the refresh of the series (or even adding it) on issue "1.50."  

This is fairly new too, as I had this series in my watchlist and it had refreshed fine and the issue numbers were showing properly - it looks like someone at CV changed the issue number from "1.50" to "1.50." - the trailing decimal is screwing things up.

I'm looking at this now to see what can be done to accommodate the trailing period, without breaking anything related to issues that contain legitimately placed decimals.

**Comment by duhasst** [comment]
It added the series perfectly now.  The only problem is 0.5, 50-O and 50-X won’t import into the system.  I tried renaming .5 to 1-2 and 1/2 and fails.  Tried 50-O as 50O and same for 50X

Here is the error for X-O Manowar 00.5 (1992).cbr issue
2015-01-02 10:50:02	ERROR	Uncaught exception: Traceback (most recent call last):
File "E:\Tools\mylar\mylar\logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "E:\Tools\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 557, in Process
self.Process_next(comicid,issueid,issuenumOG,ml)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 597, in Process_next
logger.info(module + ' Starting Post-Processing for ' + issuenzb['ComicName'] + ' issue: ' + str(issuenzb['Issue_Number']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 0: ordinal not in range(128)

Here is the error for X-O Manowar 0.5 (1992).cbr naming
2015-01-02 10:51:06	ERROR	Uncaught exception: Traceback (most recent call last):
File "E:\Tools\mylar\mylar\logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "E:\Tools\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 557, in Process
self.Process_next(comicid,issueid,issuenumOG,ml)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 597, in Process_next
logger.info(module + ' Starting Post-Processing for ' + issuenzb['ComicName'] + ' issue: ' + str(issuenzb['Issue_Number']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 0: ordinal not in range(128)

Here is the error for X-O Manowar ½ (1992).cbr naming
2015-01-02 10:53:16	ERROR	Uncaught exception: Traceback (most recent call last):
File "E:\Tools\mylar\mylar\logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "E:\Tools\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 243, in Process
watchmatch = filechecker.listFiles(self.nzb_folder,cs['ComicName'],cs['ComicPublisher'],cs['AlternateSearch'], manual=cs['WatchValues'])
File "E:\Tools\mylar\mylar\filechecker.py", line 369, in listFiles
logger.fdebug('[FILECHECKER] subname no brackets: ' + str(subname))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 12: ordinal not in range(128)

Here is the error for X-O Manowar 050-O (SECOND PART) (1992).cbr
2015-01-02 10:54:50	ERROR	Uncaught exception: Traceback (most recent call last):
File "E:\Tools\mylar\mylar\logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "E:\Tools\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 557, in Process
self.Process_next(comicid,issueid,issuenumOG,ml)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 660, in Process_next
elif int(issueno) < 0:
ValueError: invalid literal for int() with base 10: '50-O’

Here is the error for X-O Manowar 050-X (FIRST PART) (1992).cbr
2015-01-02 10:56:01	ERROR	Uncaught exception: Traceback (most recent call last):
File "E:\Tools\mylar\mylar\logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "E:\Tools\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 557, in Process
self.Process_next(comicid,issueid,issuenumOG,ml)
File "E:\Tools\mylar\mylar\PostProcessor.py", line 660, in Process_next
elif int(issueno) < 0:
ValueError: invalid literal for int() with base 10: '50-X’

So, not sure if I should try a different naming or if the code doesn’t like an integer + an ascii character

Also, found another weird add series. 2000 AD (1977) http://www.comicvine.com/2000-ad/4050-19752/  I didn’t see any strange issue numbers.  It adds the series but never finishes refreshing everything. I thought maybe it takes a long time to refresh because it has like 2000 issues for it (weekly comic).  So, I’ve let it go and it gets to about 1583 and then just keeps refreshing itself.  Never finishes.  It’s been going for almost 12 hours now.  I don’t see any errors in the log file either from it.

Thanks
du

**Comment by evilhero** [comment]
Yeah the post-processing probably would die in those parts you posted, I'll look into that today and get it working so you can manually post-process and download these issues. 
The 2000a.d series would take awhile to refresh because of the issues like you said, but not longer than 30 minutes (and even then that would be on a slow machine). There was some problems before with the issues above 1900 that included the year in the filename and mylar was getting confused about which one was the issue number. 

Are your files all named the same? Can you post the name of a file or even the one you think it's dying  on -  as that might have some correlation to what's going on.

**Comment by duhasst** [comment]
I haven’t even tried adding them to the system yet because it won’t finishing adding the series to Mylar.  So, when I did a manual post-process it thinks it’s not in my watch list and ignores them.

In my ComicRack it names them like this
2000 AD Vol.1977 #1868 (February, 2014).cbr

So, I’m trying to move everything from ComicRack to Mylar and have Mylar do all the naming and meta data.  Then I’ll just use ComicRack to point at the issues it sees for reading and syncing to devices.

If you try to add the series to your test Mylar you will see it doesn’t refresh and finish adding itself.

It looks like this screenshot I attached in the web interface.


du

**Comment by evilhero** [comment]
I was able to refresh it just fine (I had it in my watchlist already), but I did a refresh and it pulled it all down just fine:
```
02-Jan-2015 16:27:33 - INFO :: Thread-13 : Starting update for 1 active comics
02-Jan-2015 16:27:33 - INFO :: Thread-13 : [DIRECTORY-CHECK] Found comic directory: /mnt/Comics-1/2000 AD-(1977)
02-Jan-2015 16:28:31 - INFO :: Thread-13 : Now adding/updating: 2000 AD
02-Jan-2015 16:28:31 - INFO :: Thread-13 : Sucessfully retrieved details for 2000 AD
02-Jan-2015 16:28:34 - INFO :: Thread-13 : Directory (/mnt/mediavg/Comics/Comics-1/2000 AD-(1977)) already exists! Continuing...
02-Jan-2015 16:28:35 - INFO :: Thread-13 : Image header check: jpeg
02-Jan-2015 16:28:35 - INFO :: Thread-13 : Successfully retrieved cover for 2000 AD
02-Jan-2015 16:28:35 - INFO :: Thread-13 : previous version detected as None - seeing if update required
02-Jan-2015 16:29:16 - INFO :: Thread-13 : Sucessfully retrieved issue details for 2000 AD
02-Jan-2015 16:29:17 - INFO :: Thread-13 : Attempting to integrate 2000AD Annual (37464) to the existing series of 2000 AD(1977)
02-Jan-2015 16:29:18 - INFO :: Thread-13 : Successfully integrated 14 issues of 2000AD Annual to the series: 2000 AD
02-Jan-2015 16:29:19 - INFO :: Thread-13 : Now adding/updating issues for 2000 AD
02-Jan-2015 16:29:40 - INFO :: Thread-13 : Updating complete for: 2000 AD
02-Jan-2015 16:29:40 - INFO :: Thread-13 : [FILE-RESCAN] Now checking files for 2000 AD (1977) in /mnt/Comics-1/2000 AD-(1977)
02-Jan-2015 16:29:54 - INFO :: Thread-13 : [FILE-RESCAN] Updated the status of 1926 issues for 2000 AD (1977) that were not found.
02-Jan-2015 16:29:54 - INFO :: Thread-13 : [FILE-RESCAN] Total files located: 1
02-Jan-2015 16:29:54 - INFO :: Thread-13 : [FILE-RESCAN] I have physically found 1 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 1 / 1941 ]
02-Jan-2015 16:29:59 - INFO :: Thread-13 : Update complete
```
Have you restarted / shutdown Mylar since you have received the error messages ? If mylar encounters an error (of any kind), you need to shutdown/restart Mylar so that the error clears out and it continue loading things properly.

**Comment by duhasst** [comment]
Hi evilhero,

Yeah, I've restarted it a bunch of times. I removed it. Tonight I'll try adding again. Shutdown and start it. 

du

**Comment by duhasst** [comment]
OK, so I shutdown Mylar.  Started Mylar.  Let it run through it’s checks.  Then searched for 2000 AD.  Clicked the +Add Series for the 1977 one and I get this error now.

2015-01-02 17:18:35	WARNING	[Warning] ComicID: 19752 is incomplete - Removing from DB. You should try to re-add the series.

Gonna try another shutdown and restart and try again.

du

**Comment by duhasst** [comment]
Shutdown / Restart and now it’s letting me add the series.  I’m waiting for it to finish refreshing.  I’ll give it 30 minutes and let you know.

du

**Comment by duhasst** [comment]
Well, it sync’d  I left it in the details after it first added it and let it run.  So, it’s loaded just fine now and importing issues.

du

**Comment by duhasst** [comment]
Thanks for the help. Working good now. 

du

**Comment by icebal** [comment]
issue has popped up again, this time its for a double issue. the issue number pulled from comicvine is 112/113 and is erroring out. the series that this is happening to is Cerebus (1977)

2016-10-19 07:08:31	WARNING	Unable to complete Refreshing / Adding issue data - this WILL create future problems if not addressed.
2016-10-19 07:08:31	ERROR	112/113 this has an alpha-numeric in the issue # which I cannot account for.

**Comment by evilhero** [comment]
Are you running dev up to date? The fix for this particular problem went into development about 5 days ago, and was working during testing at least.

**Comment by icebal** [comment]
I will git pull just to make sure but I believe so.

**Comment by icebal** [comment]
Good news everyone!  I pulled in the latest 6 commits and it works.
