### ISSUE TITLE
Mass Archived changed to Wanted?

### ISSUE THREAD

**Issue by rupaschomaker** [evilhero/mylar#913]
Suddenly mylar decided to download old issues that have been marked as Archived.  The current state of the issues are now marked as Wanted.

Something to keep in mind -- I read the issue in a given folder and then when the folder is empty I delete the folder.  This makes it easy to tell at the file system level which comics are available.  Is it possible that deleting the folder is faking out the filechecker?  Would still think the status would stay are Archived though.

I can't find a way to trigger it, though it has gone through and done it for multiple comics.  The logs have already rotated out from underneath me so I can't look at 'em prior to the current state. :(

Has anyone else experienced this?

**Comment by evilhero** [comment]
I'm pretty sure this would be happening on the rollover of new releases every Tuesday/Wednesday, and when it attempts to autorefresh the series it sees the totals as being out of whack (ie. 10/9 or something) and does a complete kill of the series, then readds it and repopulates the new issue data from CV. It then tries to put back the status as they were previously but the archived is probably getting mixed up in the process. 

If the newest issue isn't the highest number in the series, it may also be causing a similar issue which may be a part of the process above as well. 

(this is all just guesswork atm)

**Comment by rupaschomaker** [comment]
It doesn't happen on every week.  At least it didn't.  I'll wait for things
to settle down and next time I see  it happen I'll try to grab the logs
before they roll over.  Wish I could see a pattern. :(

On Thu, Jan 1, 2015 at 11:30 AM, evilhero <notifications@github.com> wrote:

> I'm pretty sure this would be happening on the rollover of new releases
> every Tuesday/Wednesday, and when it attempts to autorefresh the series it
> sees the totals as being out of whack (ie. 10/9 or something) and does a
> complete kill of the series, then readds it and repopulates the new issue
> data from CV. It then tries to put back the status as they were previously
> but the archived is probably getting mixed up in the process.
>
> If the newest issue isn't the highest number in the series, it may also be
> causing a similar issue which may be a part of the process above as well.
>
> (this is all just guesswork atm)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/913#issuecomment-68492432>.
>



-- 
-Rupa

**Comment by evilhero** [comment]
Do you have the names of the ones it downloaded again that were marked as Archived previously? I can look into it more if I had some issues to track

**Comment by rupaschomaker** [comment]
Sure,

The Walking Dead
Suicide Risk
Uber
X-Men v4

Those are the most recent from the sabnzbd logs.


On Thu, Jan 1, 2015 at 1:25 PM, evilhero <notifications@github.com> wrote:

> Do you have the names of the ones it downloaded again that were marked as
> Archived previously? I can look into it more if I had some issues to track
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/913#issuecomment-68495427>.
>



-- 
-Rupa

**Comment by evilhero** [comment]
Have you had any problems with database locks or errors when refreshing those series?  Reason I ask is if mylar tries to refresh a series and it errors out somehow, it will leave the issue data empty as it hasn't been written. That literally would reset all your status to Skipped, and then depending on files in the directory, mark them as Wanted respectively if it was new release.

**Comment by rupaschomaker** [comment]
I have had issues with database locking at times.  This is a better
explanation than I could come up with for a possible cause.  Does sqlite
have transaction support?  If there is an error, just rollback the TX?

On Fri, Jan 2, 2015 at 5:02 PM, evilhero <notifications@github.com> wrote:

> Have you had any problems with database locks or errors when refreshing
> those series? Reason I ask is if mylar tries to refresh a series and it
> errors out somehow, it will leave the issue data empty as it hasn't been
> written. That literally would reset all your status to Skipped, and then
> depending on files in the directory, mark them as Wanted respectively if it
> was new release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/913#issuecomment-68571203>.
>



-- 
-Rupa

**Comment by evilhero** [comment]
sqlite does have rollback, and it's supposed to be automatic...if a transaction locked, depending on the status of the transaction, it should attempt to perform a rollback. Obviously it doesn't, as the locks just keep on occuring - but it's definitely something to look into as far as that methodology.

I am working on a postgresql module layer for mylar - when it's done you should (what my end goal is), be able to specify on startup which database you want to use (sqlite3 or postgresql). Postgresql is much better with transaction locking than sqlite3, which should solve the prolbem of the database locking - although I'm not sure if it would fix the issue at hand, but we can hope :)

**Comment by rupaschomaker** [comment]
Took a while for me to respond.  Automatic rollback is on a per-statement
basis by default, so each statement either completes or rolls back at the
time it is sent to the backend (or the sqlite call is made in the case of
sqlite).

So, pseudocode would be something like:

delete from issues where ...
download info
for each issue:
  insert into issues () values ()

if download fails, then we still have missing issues and if the insert
fails along the way we have an incomplete load.  Using explicit
transactions, I might structure it like this:

BEGIN;
try
  delete from ...
  download info
  for each issue:
    insert..
  COMMIT;
catch excepiton e:
  ROLLBACK;

That way if there is any error, the db is put back into it's original state.

On Mon, Jan 5, 2015 at 11:30 AM, evilhero <notifications@github.com> wrote:

> sqlite does have rollback, and it's supposed to be automatic...if a
> transaction locked, depending on the status of the transaction, it should
> attempt to perform a rollback. Obviously it doesn't, as the locks just keep
> on occuring - but it's definitely something to look into as far as that
> methodology.
>
> I am working on a postgresql module layer for mylar - when it's done you
> should (what my end goal is), be able to specify on startup which database
> you want to use (sqlite3 or postgresql). Postgresql is much better with
> transaction locking than sqlite3, which should solve the prolbem of the
> database locking - although I'm not sure if it would fix the issue at hand,
> but we can hope :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/913#issuecomment-68743067>.
>



-- 
-Rupa

**Comment by evilhero** [comment]
I'm thinking I'm going to have to redo the complete db module at this point because it's pretty much taken from headphones, which I know has the same type of problems.

**Comment by rupaschomaker** [comment]
OK. When this gets to the top of your list I can definitely test, bounce
ideas, etc and if I can the time maybe contribute. This probably falls in
line with the more generic db access that would support (say) postgresql.

I did get bit by this last pull. Mylar was unresponsive, lock problems in
log, and a number of comics reset.  Restarted mylar and then got hit with
some big downloads (no biggie). Symptoms match your analysis pretty well.
