### ISSUE TITLE
Automatic change to Archived Status when file 'disappears' from Downloaded Issue

### ISSUE THREAD

**Issue by razambon** [evilhero/mylar#914]
Just an option I thought would be great - if something is marked as downloaded, and the file disappears for some reason, automatically change the status to archived when next scanned/refreshed.  This would allow archiving to be automatically detected.  

This would be something you can toggle on/off in the settings based on your comic workflow.

**Comment by evilhero** [comment]
It actually does do this already.. But the file has to be in a Downloaded status first, then if it gets moved / deleted / etc, it will automatically change the status to Archived. 

If this isn't working for you, then I'd need to know what your work flow is and see what can be done from that.

**Comment by razambon** [comment]
Hrm.  Let me run some checks.  Just tested, and it definitely didn't happen with an annual - but I'm finding all kinds of oddities with annuals and setting things as archived (i.e., it just won't set it without switching between other statuses or using the X in a circle graphic to mark something as skipped first).

**Comment by evilhero** [comment]
When you mention problems with annuals - are you meaning annuals that are attached to a series (meaning they show up on the bottom of the comicdetails page for the series), or are you adding annuals as a series and they appear as individual items in your watchlist ? 

If you have annuals enabled - you can technically do both of the above, but if you don't have annuals enabled, you cannot attach annuals to a series.

**Comment by razambon** [comment]
I'm doing annuals as 'attached' to a series only.  And I'll get more details on it and add if I can figure out the exact flow that's causing it to occur.
