### ISSUE TITLE
Error Adding Miracleman (2013)

### ISSUE THREAD

**Issue by pardus79** [evilhero/mylar#916]
03-Jan-2015 16:52:13 - DEBUG   :: CP Server Thread-6 : Default search mode - this will match on ALL search words
03-Jan-2015 16:52:13 - DEBUG   :: CP Server Thread-6 : [ComicVine API] ComicVine API Check Running...
03-Jan-2015 16:52:13 - DEBUG   :: CP Server Thread-6 : [ComicVine API] API Start Monitoring Time (~15mins): 2015-01-03 16:46:33
03-Jan-2015 16:52:13 - DEBUG   :: CP Server Thread-6 : [ComicVine API] Time now: 2015-01-03 16:52:13
03-Jan-2015 16:52:13 - INFO    :: CP Server Thread-6 : [ComicVine API] Comicvine API count now at : 0 / 400 in 5.67 minutes.
03-Jan-2015 16:52:15 - DEBUG   :: CP Server Thread-6 : there are 0 search results...
03-Jan-2015 16:52:20 - DEBUG   :: CP Server Thread-6 : Default search mode - this will match on ALL search words
03-Jan-2015 16:52:23 - DEBUG   :: CP Server Thread-6 : there are 14 search results...
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : number of issues I counted: 13
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : number of issues CV says it has: 13
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : vari is set to: no
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : comic[ComicVersion]:noversion
03-Jan-2015 16:52:34 - INFO    :: Thread-69 : Now adding/updating: Miracleman
03-Jan-2015 16:52:34 - INFO    :: Thread-69 : Sucessfully retrieved details for Miracleman
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - Annual Year:2013
03-Jan-2015 16:52:34 - DEBUG   :: Thread-69 : Default search mode - this will match on ALL search words
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : there are 1 search results...
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - 1 result
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - there are 1 results.
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : description:<p style="">An annual to Marvel's <a href="/miracleman/4050-70918/" data-ref-id="4050-70918">Miracleman</a> series.</p>
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - 70918 found. Assuming it is part of the greater collection.
03-Jan-2015 16:52:36 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - 79169 added to series list as an Annual
03-Jan-2015 16:52:37 - DEBUG   :: Thread-69 : there are 1 search results...
03-Jan-2015 16:52:37 - DEBUG   :: Thread-69 : querying 0
03-Jan-2015 16:52:37 - DEBUG   :: Thread-69 : [IMPORTER-ANNUAL] - There are 1 annuals in this series.
03-Jan-2015 16:52:37 - ERROR   :: Thread-69 : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/mylar/mylar/logger.py", line 140, in new_run
    old_run(_args, *_kwargs)
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/mylar/mylar/importer.py", line 248, in addComictoDB
    cleanname = helpers.cleanName(firstval['Issue_Name'])
  File "/usr/local/mylar/mylar/helpers.py", line 178, in cleanName
    pass1 = latinToAscii(string).lower()
  File "/usr/local/mylar/mylar/helpers.py", line 84, in latinToAscii
    for i in unicrap:
TypeError: 'NoneType' object is not iterable

**Comment by pardus79** [comment]
Apparently, the same problem with Thunderbolts (#54429)

03-Jan-2015 18:48:47 - DEBUG   :: CP Server Thread-7 : Default search mode - this will match on ALL search words
03-Jan-2015 18:48:50 - DEBUG   :: CP Server Thread-7 : there are 62 search results...
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : number of issues I counted: 32
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : number of issues CV says it has: 32
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : vari is set to: no
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : volume X format - 0: Volume 2A new M
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : Volume information found! Adding to series record : volume 2
03-Jan-2015 18:48:57 - INFO    :: Thread-50 : Now adding/updating: Thunderbolts
03-Jan-2015 18:48:57 - INFO    :: Thread-50 : Sucessfully retrieved details for Thunderbolts
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : [IMPORTER-ANNUAL] - Annual Year:2013
03-Jan-2015 18:48:57 - DEBUG   :: Thread-50 : Default search mode - this will match on ALL search words
03-Jan-2015 18:48:59 - DEBUG   :: Thread-50 : there are 3 search results...
03-Jan-2015 18:48:59 - DEBUG   :: Thread-50 : [IMPORTER-ANNUAL] - there are 3 results.
03-Jan-2015 18:48:59 - DEBUG   :: Thread-50 : description:<p style="">2013 annual for <a href="//www.comicvine.com/thunderbolts/4050-54429/" data-ref-id="4050-54429">Thunderbolts</a>.</p><p style="">Collected in <a href="/thunderbolts-punisher-vs-the-thunderbolts/4050-78974/" data-ref-id="4050-78974">Thunderbolts: Punisher vs. The Thunderbolts</a>.</p>
03-Jan-2015 18:48:59 - DEBUG   :: Thread-50 : [IMPORTER-ANNUAL] - 54429 found. Assuming it is part of the greater collection.
03-Jan-2015 18:48:59 - DEBUG   :: Thread-50 : [IMPORTER-ANNUAL] - 70061 added to series list as an Annual
03-Jan-2015 18:49:00 - DEBUG   :: Thread-50 : there are 1 search results...
03-Jan-2015 18:49:00 - DEBUG   :: Thread-50 : querying 0
03-Jan-2015 18:49:00 - DEBUG   :: Thread-50 : [IMPORTER-ANNUAL] - There are 1 annuals in this series.
03-Jan-2015 18:49:00 - ERROR   :: Thread-50 : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/mylar/mylar/logger.py", line 140, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/mylar/mylar/importer.py", line 248, in addComictoDB
    cleanname = helpers.cleanName(firstval['Issue_Name'])
  File "/usr/local/mylar/mylar/helpers.py", line 178, in cleanName
    pass1 = latinToAscii(string).lower()
  File "/usr/local/mylar/mylar/helpers.py", line 84, in latinToAscii
    for i in unicrap:
TypeError: 'NoneType' object is not iterable

03-Jan-2015 18:50:57 - INFO    :: CP Server Thread-10 : Attempting to add directly by ComicVineID: 54429. I sure hope you know what you are doing.
03-Jan-2015 18:50:57 - ERROR   :: Thread-51 : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/mylar/mylar/logger.py", line 140, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/mylar/mylar/importer.py", line 83, in addComictoDB
    filechecker.validateAndCreateDirectory(comlocation, True)
  File "/usr/local/mylar/mylar/filechecker.py", line 970, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by evilhero** [comment]
The first error about the unicrap is most likely due to the issue title not existing so it can't convert it. I'll have to code up the fix for this. 

The last error probably relates to the fact that after the first error was hit for thunderbolts, mylar wasn't restarted. While mylar will catch the exception and log it, in most cases it will fubar later on and start doing really weird things for no reason. A simple restart of mylar will fix things back to normal. I always try to reiterate that mylar should always be restarted after any sort of error, just to ensure things don't break further down the line.
