### ISSUE TITLE
Error on startup after most recent update

### ISSUE THREAD

**Issue by jacote** [evilhero/mylar#922]
Hey EvilHero,

I got a warning that I was a couple of commits behind today and clicked "update" when prompted. Since then Mylar refuses to start.

I did a little digging and found the following stack trace:

Traceback (most recent call last):
  File "/usr/local/mylar/Mylar.py", line 24, in <module>
    import mylar
  File "/usr/local/mylar/mylar/__init__.py", line 37, in <module>
    from mylar import logger, versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers #versioncheckit, searchit, weeklypullit, dbupdater, scheduler
  File "/usr/local/mylar/mylar/PostProcessor.py", line 31, in <module>
    from mylar import logger, db, helpers, updater, notifiers, filechecker, weeklypull
  File "/usr/local/mylar/mylar/weeklypull.py", line 124
    specialissues = {'au','ai','inh','now'}
                                   ^
SyntaxError: invalid syntax

It seems like when it's loading weeklypull.py, the python interpreter is choking on the comma after 'au' in the specialissues dictionary declaration for some reason.

I skimmed the source and I don't see any obvious reason why Python doesn't like the comma. Mind you, I have never coded in Python so I don't know all of it's little foibles. :)

Running the file manually produces the same error confirming that Python REALLY doesn't like it for some reason. I've tried cloning into my install directory again in the event that I just had a corrupted file but the issue persists. I'm going to continue troubleshooting this but I'd appreciate any support you may be able to give. :)

**Comment by evilhero** [comment]
That's been running that way in the development build for the last month with  no issues reported.. So it's kind of a weird one. 

Are you using the alt_pull option for the weekly list, or just the normal method? (it shouldn't really matter) 

It might have a problem because it's not being declared prior but like I said I'm not sure why it's working for me and not you at this point. 

You could try declaring it prior to that line, by : 

specialissues = {}

**Comment by jacote** [comment]
Thanks for the quick reply EH. I wonder if it's a Python version issue. Does mylar need to be run on Python 2.7 or is 2.6.6 sufficient?

**Comment by evilhero** [comment]
Definitely, you need to be on the 2.7.x branch.. I'm pretty sure the 2.6.x would have some issues with the logic and code. 

As an FYI, I develop on 2.7.2, and I believe the entire 2.7.x branch works, although I think there was an issue at one point with with 2.7.8

**Comment by jacote** [comment]
That explains it then. My box is on 2.6.6 for some reason. Probably a plugin downgraded it on me. I'll reinstall 2.7 and see what happens. :)

**Comment by jacote** [comment]
It was totally the version. I'm on 2.7.3 now and it works just fine. Sorry for the bother!
