### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by MoOx** [evilhero/mylar#923]
I just added a new serie & just got this issue for some seconds (after 5 refresh, error was gone)

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 73, in home
    comics = helpers.havetotals()
  File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 1147, in havetotals
    elif 'present' in comic['ComicPublished'].lower() or ( today()[:4] in comic['LatestDate']):
TypeError: argument of type 'NoneType' is not iterable

Powered by CherryPy 3.2.0 
```

**Comment by evilhero** [comment]
What was the series that you were adding ? 

And how did you go about adding it (via the Search/Add Series button or using the Import A Directory option)?

If you were adding it via the Search/Add button - did you browse away from the page (and go back to the main index page) before the item had finished being added ? Normally those types of errors only occur because the series hasn't fully loaded yet so Mylar can't display them properly.

This is pretty much identical to #919, which will be fixed in the next development release.

**Comment by MoOx** [comment]
Futures End.

I have used the add from the "This week" page.

Indeed it seems the same has #919

**Comment by jasontucker** [comment]
I'm having the same issue:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 200, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=None, explicit=explicit)
TypeError: 'bool' object is not iterable
Powered by CherryPy 3.2.0

**Comment by evilhero** [comment]
What build of mylar are you running? What were you doing leading up to the error (check/post the mylar.log file for more details) 

Do you have your own Comicvine API key specified?

**Comment by jasontucker** [comment]
Version: 0b9ce0befe07d3eb73830aae48a2ee29539d5edc (development) 
I'm using my own API Key I generated over on their website.
I've never have had Mylar work for me, each time I try to add a series or search it doesnt work. adding a one timer doesnt seem to work either.


the bottom of /volume1/@appstore/mylar/share/mylar/logs/mylar.log says: 
28-Jan-2015 01:23:46 - INFO    :: Thread-12 : Weekly Pull List successfully loaded.
28-Jan-2015 01:23:46 - INFO    :: Thread-12 : Checking the Weekly Releases list for comics I'm watching...
28-Jan-2015 01:23:46 - DEBUG   :: Thread-12 : You are watching for: 0 comics
28-Jan-2015 01:23:46 - DEBUG   :: Thread-12 : There are 0 comics this week to get!
28-Jan-2015 01:23:46 - INFO    :: Thread-12 : Finished checking for comics on my watchlist.
28-Jan-2015 01:23:56 - DEBUG   :: CP Server Thread-7 : Weekly pull list present - retrieving pull-list date.
28-Jan-2015 01:24:01 - DEBUG   :: CP Server Thread-7 : Default search mode - this will match on ALL search words
28-Jan-2015 01:24:01 - DEBUG   :: CP Server Thread-7 : [ComicVine API] ComicVine API Check Running...
28-Jan-2015 01:24:01 - DEBUG   :: CP Server Thread-7 : [ComicVine API] API Start Monitoring Time (~15mins): 2015-01-28 01:22:59
28-Jan-2015 01:24:01 - DEBUG   :: CP Server Thread-7 : [ComicVine API] Time now: 2015-01-28 01:24:01
28-Jan-2015 01:24:01 - INFO    :: CP Server Thread-7 : [ComicVine API] Comicvine API count now at : 0 / 400 in 1.03 minutes.
28-Jan-2015 01:24:01 - ERROR   :: CP Server Thread-7 : err : HTTP Error 404: Not Found
28-Jan-2015 01:24:01 - ERROR   :: CP Server Thread-7 : There was a major problem retrieving data from ComicVine - on their end. You'll have to try again later most likely.
28-Jan-2015 01:24:11 - INFO    :: MAIN : Received signal: shutdown
28-Jan-2015 01:24:12 - DEBUG   :: MAIN : [ComicVine API] ComicVine API Check Running...
28-Jan-2015 01:24:12 - DEBUG   :: MAIN : [ComicVine API] API Start Monitoring Time (~15mins): 2015-01-28 01:22:59
28-Jan-2015 01:24:12 - DEBUG   :: MAIN : [ComicVine API] Time now: 2015-01-28 01:24:12
28-Jan-2015 01:24:12 - INFO    :: MAIN : [ComicVine API] Comicvine API count now at : 0 / 400 in 1.22 minutes.


I checked this:

MediaServer> curl http://www.comicvine.com/api
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://www.comicvine.com/api/" />

        <title>Redirecting to http://www.comicvine.com/api/</title>
    </head>
    <body>
        Redirecting to <a href="http://www.comicvine.com/api/">http://www.comicvine.com/api/</a>.
    </body>

**Comment by evilhero** [comment]
Have you enabled the synology fix in the gui options? If not try enabling it, save the config, restart mylar and try again. 

Synology users have different linking to libraries and the XML parser is one of them.

**Comment by jasontucker** [comment]
Yeah, I did the synology fix that doesnt seem to help any.

**Comment by evilhero** [comment]
Ok, how did you install mylar? By using git or the synopackage?

**Comment by jasontucker** [comment]
I installed mylar using synopackage and then switched it to development and then used git to pull it again. I used curl to try and connect to their api endpoint (I had the correct one, right? I havent looked at your code to see what you were referencing) and thats what I go when I did. I've tried with and without most of the switches on and off including but not limited to comicvine. I also tried nuking and paving and starting fresh and tried pulling from git with a clean directory.

below is my current config:

```bash
MediaServer> cat /volume1/@appstore/mylar/var/config.ini
[General]
config_version = 5
dbchoice = ""
dbuser = ""
dbpass = ""
dbname = ""
comicvine_api = ################myapikey###############
cvapi_count = 0
cvapi_time = 2015-01-28 21:21:30
http_port = 8090
http_host = 0.0.0.0
http_username = ""
http_password = ""
http_root = /
enable_https = 0
https_cert = ""
https_key = ""
https_force_on = 0
api_enabled = 1
api_key = ###########myapikey##############
launch_browser = 0
auto_update = 0
log_dir = /usr/local/mylar/var/logs
max_logsize = 1000000
logverbose = 0
git_path = ""
cache_dir = /usr/local/mylar/var/cache
annuals_on = 0
cv_only = 1
cv_onetimer = 1
cvapifix = 1
check_github = 1
check_github_on_startup = 1
check_github_interval = 360
destination_dir = /volume1/Media/dropbox/Comics
multiple_dest_dirs = ""
create_folders = 1
chmod_dir = 0777
chmod_file = 0660
usenet_retention = 1500
alt_pull = 0
search_interval = 360
nzb_startup_search = 0
libraryscan = 0
libraryscan_interval = 300
add_comics = 1
comic_dir = Enter a Comic Directory to scan
imp_move = 0
imp_rename = 0
imp_metadata = 0
enable_check_folder = 0
download_scan_interval = 5
check_folder = ""
interface = default
dupeconstraint = filesize
autowant_all = 1
autowant_upcoming = 1
preferred_quality = 0
comic_cover_local = 1
correct_metadata = 0
move_files = 0
rename_files = 0
folder_format = $Series ($Year)
file_format = $Series $Issue ($Year)
blackhole_dir = ""
replace_spaces = 0
replace_char = .
zero_level = 0
zero_level_n = none
lowercase_filenames = 0
ignore_havetotal = 0
snatched_havetotal = 0
syno_fix = 1
search_delay = 1
grabbag_dir = /volume1/Media/dropbox/Comics
highcount = 0
read2filename = 0
storyarcdir = 0
copy2arcdir = 0
use_minsize = 0
minsize = ""
use_maxsize = 0
maxsize = ""
add_to_csv = 1
cvinfo = 0
log_level = 0
enable_extra_scripts = 0
extra_scripts = ""
enable_pre_scripts = 0
pre_scripts = ""
post_processing = 1
post_processing_script = ""
weekfolder = 0
locmove = 0
newcom_dir = ""
fftonewcom_dir = 0
enable_meta = 1
cmtagger_path = /usr/local/mylar/share/mylar
ct_tag_cr = 1
ct_tag_cbl = 1
ct_cbz_overwrite = 0
unrar_cmd = None
indie_pub = 75
biggie_pub = 55
enable_rss = 1
rss_checkinterval = 20
rss_lastrun = 2015-01-28 21:26:30
failed_download_handling = 0
failed_auto = 0
provider_order = 0, oznzb, 1, nzbgeek
nzb_downloader = 0
[Torrents]
enable_torrents = 0
minseeds = 0
torrent_local = 0
local_watchdir = ""
torrent_seedbox = 0
seedbox_host = ""
seedbox_port = ""
seedbox_user = ""
seedbox_pass = ""
seedbox_watchdir = ""
enable_torrent_search = 0
enable_kat = 0
kat_proxy = ""
enable_cbt = 0
cbt_passkey = ""
snatchedtorrent_notify = 0
[SABnzbd]
sab_host = http://localhost:8080
sab_username = ""
sab_password = ""
sab_apikey = ##########myapikey############
sab_category = comics
sab_priority = Default
sab_directory = ""
[NZBGet]
nzbget_host = ""
nzbget_port = ""
nzbget_username = ""
nzbget_password = ""
nzbget_category = ""
nzbget_priority = Default
nzbget_directory = ""
[NZBsu]
nzbsu = 0
nzbsu_uid = ""
nzbsu_apikey = ""
[DOGnzb]
dognzb = 0
dognzb_uid = ""
dognzb_apikey = ""
[Experimental]
experimental = 0
altexperimental = 1
[Newznab]
newznab = 1
extra_newznabs = oznzb, https://api.oznzb.com, ###############myapikey#########, 7030, 1, nzbgeek, https://api.nzbgeek.info, #################myapikey################, "", 1
[Prowl]
prowl_enabled = 0
prowl_keys = ""
prowl_onsnatch = 0
prowl_priority = 0
[NMA]
nma_enabled = 0
nma_apikey = ""
nma_priority = 0
nma_onsnatch = 0
[PUSHOVER]
pushover_enabled = 0
pushover_apikey = ""
pushover_userkey = ""
pushover_priority = 0
pushover_onsnatch = 0
[BOXCAR]
boxcar_enabled = 0
boxcar_onsnatch = 0
boxcar_token = ""
[PUSHBULLET]
pushbullet_enabled = 0
pushbullet_apikey = ""
pushbullet_deviceid = ""
pushbullet_onsnatch = 0
[Raw]
raw = 0
raw_provider = None
raw_username = None
raw_password = None
raw_groups = None
MediaServer>
```

**Comment by evilhero** [comment]
Yeah your config looks perfectly fine, so I can't see anything in there being an issue.

I know in the past users have experienced alot of problems with the synopackage, for whatever reason (I really don't know alot of the specifics, I just know when they have problems they come here).

Is it possible for you to try doing a fresh git clone, without using the synopackage?
