### ISSUE TITLE
Manual Post processing fails with Uncaught Exception

### ISSUE THREAD

**Issue by ProtoJazz** [evilhero/mylar#925]
Uncaught exception: Traceback (most recent call last):
File "/home/protojazz/mylar/mylar/logger.py", line 140, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/protojazz/mylar/mylar/PostProcessor.py", line 243, in Process
watchmatch = filechecker.listFiles(self.nzb_folder,cs['ComicName'],cs['ComicPublisher'],cs['AlternateSearch'], manual=cs['WatchValues'])
File "/home/protojazz/mylar/mylar/filechecker.py", line 584, in listFiles
if j <= len(subname) and subname[j+1].isdigit():
IndexError: string index out of range

**Comment by evilhero** [comment]
Can I ask what the filename is that you're trying to scan in that it's erroring out on? Based on that error I would guess that there's some kind of trailing character  that might be there because it's being used to designate a space.

**Comment by ProtoJazz** [comment]
How would I find that out? The only line before that is starting manual
post process

**Comment by evilhero** [comment]
It should say something in the mylar.log file itself, although if you're importing the log might span more than one log file. 

If you have any files in that directory that have multiple spaces designated as '__'  or '..'  or even 2 spaces together as examples.

**Comment by ProtoJazz** [comment]
Thanks. I was able to find the file causing the issue, it had lots of "---"
everywhere. I cleaned up the name and it was able to process everything.
