### ISSUE TITLE
Not Finding Files

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#927]
Updated to the latest development version and now files are not being found after refresh.

Here is a link to the logs

http://pastebin.com/mR7L0E2h

**Comment by evilhero** [comment]
Ah yeah the month, year in the filename.. This was working before wasn't it?

**Comment by kev0153** [comment]
Was working great, not sure after what update it broke

**Comment by kev0153** [comment]
nailed it with this last update, you are the man
