### ISSUE TITLE
Wondering if Mylar is doing its automatic updates

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#931]
I noticed that despite adding Ant-Man #1 it hasn't shown up yet. I have added new comics and they are getting downloaded, but I seem to have a lot of missing recent issues to previously added comics. Maybe there haven't been that many releases in the last two or three weeks, but I have like 100 or more active comics right now. How can I tell? What might be a magic fix? Or maybe I should "really just relax" lol

**Comment by evilhero** [comment]
Well, there hasn't been a decline in comics the last few weeks - my pull-list has stayed pretty consistent and haven't had any problems (outside of stupid user ones I mean).

Have you tried just restarting Mylar at all ? If you had encountered any kind of error in the past and hadn't restarted Mylar and the logs rolled over, you would have never seen the error.

Even attempting to do a Force Check (after a restart), might very well be enough to jump-start things.

That is of course, unless there's some errors happening - which should re-appear on a restart so you could see them.

**Comment by AtariBaby** [comment]
Is a terminal restart better, worse, or the same as a web UI restart?

**Comment by AtariBaby** [comment]
FYI I thought I would check for an update and I was "15 commits behind". Surprised I didn't see any notices despite accessing Mylar often in recent weeks.

**Comment by AtariBaby** [comment]
And the update bug is back. I had that thing licked for a long time! Now it won't go away after click restart again.

**Comment by evilhero** [comment]
What was the update bug again ? That it wouldn't update because git is saying it can't ?

**Comment by AtariBaby** [comment]
Oh, sorry to be so vague. You click the "Update" link in the bottom right corner, Mylar page says "updating", then it refreshes and it's not updated and the update notification is still in the bottom right corner. Also won't shut down. You or I had whooped that in the past but now it's happening again, along with not searching for comics properly again, apparently.

**Comment by AtariBaby** [comment]
one git pull later and comics are flooding in!

**Comment by evilhero** [comment]
OOh yeah, the stupid 'git stash' thing...so everything is working and up-to-date now ?

**Comment by AtariBaby** [comment]
working and up to date, but I haven't tested "shut down". Maybe I will after comics download

**Comment by evilhero** [comment]
If you were able to start it up with no errors, shutting down and restarting should be a piece of cake ;)

**Comment by AtariBaby** [comment]
All is well now. Thanks for the help!
