### ISSUE TITLE
RSS Checker Not Including First Item (CBT)

### ISSUE THREAD

**Issue by vegetate** [evilhero/mylar#932]
I believe there is a problem where the RSS checker isn't including the first item in the follow list.  I was having problems finding an issue that was in the list.  So I checked the database and noticed the first item in the list wasn't in the rssdb table.  I then added another series to my follow list, force updated RSS, and now the issue that I had been missing is in the table, but the most recent addition is not.

**Comment by evilhero** [comment]
It's very possible, there was a similar thing happening to one of the nzb providers. If you have minimum number of seeders greater than 0 within mylar, it wouldn't pick it up - plus, I've noticed before that it sometimes takes a few mins for stuff to get on the actual rss feed (albeit i don't believe it was cbt , but

**Comment by vegetate** [comment]
Ok, thanks.  Just to add details, I don't have the seeders option set and I don't think it's a timing issue as part of figuring it out I was looking at the RSS directly and noticed that the issue it couldn't find was the top one which led me to my test of adding a new series to my list.  So it was definitely in the RSS feed it just wasn't being pulled into the database.

**Comment by evilhero** [comment]
Silly mistake on my end, and a really easy fix - was starting a loop to write the information to the db table at a value of 1, instead of 0 ..nice catch!  And thanks for all the detailed information, took me all of    a minute to find the mistake just based on your information alone.

Will be in the next development commit.
