### ISSUE TITLE
Mylar errors on post-process [DUPECHECK]

### ISSUE THREAD

**Issue by ubun2Junky** [evilhero/mylar#934]
I just installed Mylar on my Ubuntu box.  Everything was working great until the post-process.  The post-process is giving the following error.  I'm not sure how to check for the latest version of autoProcessComics.py since I've already done a git pull and get a "Already up-to-date" message.  I've installed the development branch.

2015-01-26 13:46:38 	ERROR 	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/PostProcessor.py", line 568, in Process
dupthis = helpers.duplicate_filecheck(self.nzb_folder, ComicID=comicid, IssueID=issueid)
File "/opt/mylar/mylar/helpers.py", line 1577, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/ubun2/Downloads/complete/Star Wars 001 (2015) (digital) (Minutemen-Midas)'
2015-01-26 13:46:38 	INFO 	[DUPECHECK] Duplicate check for /home/ubun2/Downloads/complete/Star Wars 001 (2015) (digital) (Minutemen-Midas)
2015-01-26 13:46:38 	INFO 	[POST-PROCESSING] issuenzb found.
2015-01-26 13:46:38 	INFO 	Starting postprocessing for : Star Wars 001 (2015) (digital) (Minutemen-Midas)
2015-01-26 13:46:38 	WARNING 	ComicRN should be v1.0 and autoProcessComics.py should be v1.0, but they are not and are out of date. Post-Processing may or may not work.

**Comment by ubun2Junky** [comment]
Here is the log from mylar.log:

26-Jan-2015 14:27:24 - INFO    :: CP Server Thread-7 : Starting postprocessing for : Star Wars 001 (2015) (digital) (Minutemen-Midas)
26-Jan-2015 14:27:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: Star Wars 001 (2015) (digital) (Minutemen-Midas)
26-Jan-2015 14:27:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /home/ubun2/Downloads/complete/comics/Star Wars 001 (2015) (digital) (Minutemen-Midas)
26-Jan-2015 14:27:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] SABnzbd Download folder option enabled. Directory set to : /home/ubun2/Downloads/complete/Star Wars 001 (2015) (digital) (Minutemen-Midas)
26-Jan-2015 14:27:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : Star.Wars.001.(2015).(digital).(Minutemen-Midas)
26-Jan-2015 14:27:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: 475858
26-Jan-2015 14:27:24 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb found.
26-Jan-2015 14:27:24 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for /home/ubun2/Downloads/complete/Star Wars 001 (2015) (digital) (Minutemen-Midas)
26-Jan-2015 14:27:24 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/PostProcessor.py", line 568, in Process
    dupthis = helpers.duplicate_filecheck(self.nzb_folder, ComicID=comicid, IssueID=issueid)
  File "/opt/mylar/mylar/helpers.py", line 1577, in duplicate_filecheck
    filesz = os.path.getsize(filename)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/ubun2/Downloads/complete/Star Wars 001 (2015) (digital) (Minutemen-Midas)

**Comment by evilhero** [comment]
For the error:
Blank out the Sabnzbd Download Directory option within the mylar configuration. If sabnzbd and mylar are on the same machine, you don't specify a download directory since it gets passed with each download from sabnzbd. The option is intended to be used for users that have mylar and sabnzbd on different machines. 

For the version message:
Wherever you have your comicRN.py a day AutoProcesscomics.py, you have to make sure that you copy the newest versions from within the /post-processing/ directory is the root of mylar. Odds are you copied the scripts into your sabnzbd scripts

**Comment by ubun2Junky** [comment]
Thank you for the prompt response.  Removing the download directory solved the issue.  As far as the scripts, I'm using nzbToMylar.py.  It was the only script I knew about.  On closer inspection I did find a autoProcessComics.py script in the nzbtomedia folder.  When I copied the version that is located from the mylar root folder it errored out, so I just left the one that came with nzbtomedia for now.

**Comment by evilhero** [comment]
I can't say how uptodate NzbToMylar.py is - some things have changed in regards to how mylar handles post-processing and I'm not sure if it's been accounted for in nzbtomylar.py as of yet. All I can support is what I've worked on, so I really can't provide any help with that particular script, although I know the author is very hands on and helpful with things. 

Have you tried using the post-processing/autoProcesscomics.py and post-processing/sabnzbd/ComicRN.py scripts? They should just work - drop and go once you setup the autoProcesscomics.cfg, and configure your sabnzbd (I run mine on ubuntu 12.04LTS and haven't had an issue lately)

**Comment by ubun2Junky** [comment]
I'm just going to rename the other scripts and I'll create symlinks to the autoProcessComics.py autoProcessComics.pyc and ComicRN.py, so they are always up to date whenever Mylar is updated.  Thank you for the great suggestions.  Kick ass app! Keep up the great work!
