### ISSUE TITLE
Can't update Mylar

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#935]
It's telling me I am 14 commits behind.  I try to update and it tells me I am still 14 commits behind.  SSHed into the server and did a git pull from the bash shell, and it's still claiming 14 commits behind.

**Comment by evilhero** [comment]
You have files that were modified and because of that git will refuse to overwrite any local changes. 

Do a 'git stash' to store your local changes, then either a 'git pull' or update via the mylar gui and it will work. 

If you want to merge back your changes that you stashed, just do a 'git stash apply', although it will probably complain about conflicts with the attempted merge and you might be worse off.

**Comment by apastuszak** [comment]
git stash says "No local changes to save."

git pull says "Already up-to-date."

UI still says I am 14 commits behind.

**Comment by evilhero** [comment]
Did you install mylar using git or from source? 

Are you within the mylar directory when you're doing the commands? 

Only other option is to backup your mylar.db, config.ini and your entire cache/ directory, and then wipe the mylar directory out. Then do a clean git clone (with the '-b development') and then move back the items you backed up. Start it up and you should be OK at that point.

**Comment by apastuszak** [comment]
I installed with a git pull.  It's been working fine and updating just fine
for a very long time.  This is the first time I have been unable to do an
update.

**Comment by evilhero** [comment]
Maybe you need to do a 'git reset - hard' or similar in order to get it back to the normal and then git pull it again. 

You're on the development branch correct?

**Comment by apastuszak** [comment]
yes

**Comment by apastuszak** [comment]
So, nothing is working.  I'll start over again.  No need to waste your time
on one user.

**Comment by evilhero** [comment]
One/hundred... If they have a problem, I'll do my best to help and fix it. Doesn't matter to me the number, just about making things work as they should ;)

**Comment by apastuszak** [comment]
Ok, cloned a new version and it's still telling me I am 17 commits behind.

**Comment by apastuszak** [comment]
Ignore that.  I'll get back to you.

**Comment by apastuszak** [comment]
I'm good.  Was doing a git pull from the wrong directory.  Thanks for the help!
