### ISSUE TITLE
Error on Manual post-processing

### ISSUE THREAD

**Issue by tchirou** [evilhero/mylar#936]
Hello

Mylar Version: development
-- source build 0b9ce0befe07d3eb73830aae48a2ee29539d5edc.
Python Version : 2.7.6 / Win 8.1

I try to manual post-process a file and it gives me this error. It is injustice year three digital.

2015-01-28 11:59:29	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Program Files (x86)\SABnzbd\mylar-development\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Program Files (x86)\SABnzbd\mylar-development\mylar\PostProcessor.py", line 243, in Process
watchmatch = filechecker.listFiles(self.nzb_folder,cs['ComicName'],cs['ComicPublisher'],cs['AlternateSearch'], manual=cs['WatchValues'])
File "C:\Program Files (x86)\SABnzbd\mylar-development\mylar\filechecker.py", line 103, in listFiles
print item
IOError: [Errno 9] Bad file descriptor
2015-01-28 11:59:26	INFO	[ComicVine API] Comicvine API count now at : 0 / 400 in 5.08 minutes.
2015-01-28 11:59:03	INFO	Starting postprocessing for : Manual Run

Any thoughts ?

Many thanks

**Comment by evilhero** [comment]
Do you have the file open somewhere else or had it not finished downloading yet? 

Have you tried running it again?

**Comment by tchirou** [comment]
Well It is in a dropbox folder but it works that way every week. I had
tried dozens of time this morning.
I just disabled dropbox and tried again but same result.

I removed a file from another comics I post-processed successfully last
week, put it in archived status, and tried the post process and error
again. So it is not a problem with the first file.

**Comment by evilhero** [comment]
I'd need to see the mylar.log file from the start of the manual run up until the error.  Kind of hard to tell what's going on otherwise.

**Comment by tchirou** [comment]
Here you go my good sir : http://pastebin.com/MeqWqgdJ
Fresh from starting up this morning

**Comment by evilhero** [comment]
That error in that log (the alternate name error), was fixed in the last development commit. You also updated to the latest version after that error occurred. 

Have you tried again since updating?

**Comment by tchirou** [comment]
I was checking the log and weirdly enough, it does not go after the update and I tried the post process after the update
I have to find the log about that

**Comment by tchirou** [comment]
I am going to delete all log files and start mylar and launch the post process

**Comment by tchirou** [comment]
Where can i send you the zip with all the log files because as soon as I try the manual post-process, the thing is going bat shit crazy and creates 6 log files

**Comment by evilhero** [comment]
All I really need to see is the one that contains the error, or the lead up to it at the very least. 

Otherwise, evilhero@mylarcomics.com

**Comment by evilhero** [comment]
Ok this was just a stupid error, the print statement should be removed.

**Comment by tchirou** [comment]
Ok please let me know through here when you author a new one so I can check

Thanks

**Comment by tchirou** [comment]
Works again !
Many thanks
