### ISSUE TITLE
Things went a little fubar with the latest update notice

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#937]
Earlier I got a notice that there were updates on the web UI. I click to install them, and then Mylar's web pages became non-responsive (404 error). I tried to stop and start via command line, but it kept responding that it was already running.

I finally rebooted the system and now it's working, though I see a lot of pink in the logs. Do you want me to show you, and what should I do? Show you a whole tone of logs or just the pink parts or what?

Also, I'm having to click "check for updates" to find out there are updates. Shouldn't it notify automatically? NOTE: I subsequently repeated the above process and the updates appeared to install successfully.

**Comment by evilhero** [comment]
It should notify on startup, or every 6 hrs (I think it's 6 hrs, might be 12).

You can paste the pink stuff just so I can see what the errors are, and if I need more information I'll ask for it (backup your existing log files though, so they don't roll over and get wiped out)
