### ISSUE TITLE
Redirect Loop Error

### ISSUE THREAD

**Issue by kev0153** [evilhero/mylar#939]
I'm getting a re-direct loop error on chrome when trying to go to the pull list.  I've tried restarting the server and clearing cookies but it doesn't seem to help.  I also tried opening mylar in safari and I'm still getting the error.  Not sure if this is a local error on my end or what...

**Comment by evilhero** [comment]
Can you post the error you're getting when you try to go the pull-list page ? 

Do you have the ALT_PULL enabled or disabled in the config?

**Comment by Logan360** [comment]
I had this too, but turning off alt_pull fixed it

**Comment by kev0153** [comment]
yep, ALT_PULL is enabled.  Here is a screen shoot.  I'll try and turn it off and see what happens.

![screenshot_2015-02-02-14-15-32](https://cloud.githubusercontent.com/assets/841053/6008407/d69c79a0-aae6-11e4-9f48-98bdf9cc7833.png)

**Comment by evilhero** [comment]
I was able to get it working with the ALT_PULL enabled - turns out they changed something on the source of the page, that I had hard-coded in as being explicit. Fixed it and it ran fine on mine. Will commit up shortly for you guys to test out.

(I think the redirects error is probably in relation to the endless looping)

**Comment by gsargent70** [comment]
I am also getting a redirect loop error on the pull list screen.  Log entries are

2015-04-10 13:11:14	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 504, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/weeklypull.py", line 72, in pullit
if not row[0].startswith('#'):
IndexError: list index out of range
2015-04-10 13:11:14	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 504, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/weeklypull.py", line 72, in pullit
if not row[0].startswith('#'):
IndexError: list index out of range

ALT_PULL is not enabled.

**Comment by gsargent70** [comment]
Nevermind I figured it out.  Just for future reference you can not have a line in your substitutes.csv file that only has a carriage return on it.

**Comment by evilhero** [comment]
Ahh yeah, I can't really control the csv entry portion, but I think I can make it not error out on lines with only carriage returns on it so this doesn't happen again or to anyone else.

Cheers, for posting back the solution - it helps alot when I'm trying to catch errors and clean up some of the functions :+1:
