### ISSUE TITLE
ComicRN and autoProcessComics out of date. What do you make of it?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#943]
2015-02-07 19:28:08	WARNING	ComicRN should be v1.0 and autoProcessComics.py should be v1.0, but they are not and are out of date. Post-Processing may or may not work.

**Comment by evilhero** [comment]
Just what it says... Make sure you are running the latest version of both files (recopy them from the updated working directory).  Probably best to copy AutoProcesscomics.py as well.

**Comment by AtariBaby** [comment]
okay i replaced 'em. Hopefully no editing of the files was required! Thanks.

**Comment by evilhero** [comment]
Yep, no editing - just drop and go ;)
