### ISSUE TITLE
Skipping Comics with Volume number in Name

### ISSUE THREAD

**Issue by kidinstinct** [evilhero/mylar#945]
This may not necessarily be a bug, just wondering if there's anything (reasonable) that may be done about it. Mylar sometimes missing new releases due to a release having [Series] [v#] [issue #] [year](misc info). That [v#] seems to throw it off it's game and does not recognize the release. There are others, such as if a release has 0-day in front of the name. But want to concentrate on this one first I guess if possible.

Example below:
X-Men **v4** 024 (2015) (Digital-Empire)

Mylar skipped this issue because it has **v4** in the name.

Thanks

**Comment by evilhero** [comment]
The volume in the series within a filename should work across all providers,provided it matches what mylar has on on file (comic details, edit setting, volume label). It polls this automatically when adding /refreshing a series, but CV doesn't actually have a volume field so mylar has to try to determine it. If it's wrong, simply put in the correct volume label. 

The 0-day should also be handled fine within the experimental. I've grabbed releases that have 0-day in the header and it works fine.. If however the filename has 0 day in it, then mylar won't grab those. 

If you have another provider that's Newznab based and those are being left in, then it's not doing its job (basically, it should be stripping out the crap and leaving the actual title - cause that's what Newznab are supposed to do).
