### ISSUE TITLE
Unable to start Mylar after updating

### ISSUE THREAD

**Issue by ManOrMonster** [evilhero/mylar#949]
Saw today that I was 30 commits behind, so updated, and now it won't start ("Error code: ERR_CONNECTION_REFUSED" in Chrome). Windows 8.1.

**Comment by ManOrMonster** [comment]
So I realized that the Mylar script with console is working. The one without console (which is what I run by default) is not.

**Comment by evilhero** [comment]
Make sure to update your existing Mylar.pyw file as well (copy over the Mylar.py to Mylar.pyw). 

Normally for Windows users, they change the Mylar.py to Mylar.pyw (so it runs as a daemon) , which won't get updated because it's a local modification.

**Comment by ManOrMonster** [comment]
Ok, that worked. I don't remember needing to do this before. I'll have to keep this in mind next time an update breaks my installation. :)
