### ISSUE TITLE
Auto convert cbr/cbz?

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#951]
Would love a "'Convert to CBZ" option in Post-Processing. I know there's a search for cbr/cbz preference but often issues are only available in one format.

**Comment by evilhero** [comment]
If you're wanting to have the final cbz have metatagging as well,  then it's already built into the metatagging option within mylar. Just enable metatagging (and obviously follow the instructions for installing Comictagger), and it will autoconvert from cbr to cbz, and tag it from comicvine using Comictagger. 

It's possible for me to add an option that just converts cbr to cbz, without any metagging done - is that what you're requesting?

**Comment by ElementSixtySix** [comment]
I had it autotagging but half the time it failed and just left a zip and rar file in PP folder so I was manually tagging with CT. I didn't realise it converted permanently. But yeah a convert option would be sweet...

**Comment by evilhero** [comment]
There were some lingering post-processing issues with metatagging that should have been cleared up a little while ago (development branch). Most times mylar had problems with files that were already in cbz format and trying to metatag them. 

If you're on the latest development build I'd be really interested in seeing the pp logs from the mylar.log for a failed run to see exactly what's going on.

**Comment by ElementSixtySix** [comment]
I'll turn tagging back on and post up logs next pp run. Maybe issue is already fixed though. I stopped using tagging and haven't noticed a fix posted, though I could have missed it...

**Comment by ElementSixtySix** [comment]
Ok so tagging back on. Works fine for cbz but below is excerpt from a cbr tagging attempt.

26-Feb-2015 07:23:39 - INFO    :: Thread-14 : [DUPECHECK] Duplicate check for D:\Mylar\Deadpool 042 (2015).cbr
26-Feb-2015 07:23:39 - INFO    :: Thread-14 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
26-Feb-2015 07:23:39 - INFO    :: Thread-14 : [POST-PROCESSING] Starting Post-Processing for Deadpool issue: 42
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] issueid: 480671
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] issuenumOG: 42
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Zero Suppression set to : 00x
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Pretty Comic Issue is : 042
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Issue Year : 2015
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Publisher: Marvel
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Series: Deadpool
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Year: 2013
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Location: K:\Comics\Marvel\Deadpool (2013)
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Version: v3
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Not an annual - removing from filename parameters
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format: $Series $Issue ($Year)
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [POST-PROCESSING] Metatagging enabled - proceeding...
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] dirName:D:\Mylar
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] chkpath: D:\Mylar
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] chkfile: Deadpool 042 (2015).cbr
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Paths / Locations:
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] scriptname : Mylar.py
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] downloadpath : D:\Mylar
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] sabnzbdscriptpath : K:\Mylar New
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] comicpath : D:\Mylar\480671
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] unrar_folder : D:\Mylar\480671\unrard
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Attempting to create directory @: D:\Mylar\480671
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Created directory @ : D:\Mylar\480671
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Filename is : D:\Mylar\Deadpool 042 (2015).cbr
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : D:\Mylar\Deadpool 042 (2015).cbr
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] moving : D:\Mylar\Deadpool 042 (2015).cbr to D:\Mylar\480671\Deadpool 042 (2015).cbr
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] Mylar.py: converting Deadpool 042 (2015).cbr to be zip format
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] {0}: Comicpath is D:\Mylar\480671\Deadpool 042 (2015).rar
26-Feb-2015 07:23:39 - DEBUG   :: Thread-14 : [META-TAGGER] {0}: Unrar is D:\Mylar\480671\unrard
26-Feb-2015 07:23:42 - DEBUG   :: Thread-14 : [META-TAGGER] Converted directory: D:\Mylar\
26-Feb-2015 07:23:42 - DEBUG   :: Thread-14 : [META-TAGGER] Converted filename: Deadpool 042 (2015).cbz
26-Feb-2015 07:23:42 - DEBUG   :: Thread-14 : [META-TAGGER] Destination path: D:\Mylar\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:42 - DEBUG   :: Thread-14 : [META-TAGGER] dirName: D:\Mylar
26-Feb-2015 07:23:42 - DEBUG   :: Thread-14 : [META-TAGGER] absDirName: D:\Mylar
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] ComicTagger 1.1.15-beta being used - using personal ComicVine API key supplied via mylar.
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] CR Tagging enabled.
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] Will NOT modify existing tag blocks even if they exist already.
26-Feb-2015 07:23:43 - INFO    :: Thread-14 : [META-TAGGER] ComicRack tagging meta-tagging processing started.
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [ComicVine API] ComicVine API Check Running...
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [ComicVine API] API Start Monitoring Time (~15mins): 2015-02-26 07:23:02
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [ComicVine API] Time now: 2015-02-26 07:23:43
26-Feb-2015 07:23:43 - INFO    :: Thread-14 : [ComicVine API] Comicvine API count now at : 0 / 400 in 0.68 minutes.
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] Enabling ComicTagger script: C:\Program Files (x86)\ComicTagger\comictagger.exe with options: ['-s', '--verbose', '-m', 'volume=3', '--cv-api-key', u'72f595aab1483d8ca63b8aaaf2f43c29cd9409e8', '--nooverwrite', '-o', '--id', u'480671', '--type', 'cr', u'D:\\Mylar\\480671\\Deadpool 042 (2015).cbz']
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] Executing command: ['C:\\Program', 'Files', '(x86)\\ComicTagger\\comictagger.exe', '-s', '--verbose', '-m', 'volume=3', '--cv-api-key', u'72f595aab1483d8ca63b8aaaf2f43c29cd9409e8', '--nooverwrite', '-o', '--id', u'480671', '--type', 'cr', u'D:\\Mylar\\480671\\Deadpool 042 (2015).cbz']
26-Feb-2015 07:23:43 - DEBUG   :: Thread-14 : [META-TAGGER] Absolute path to script: C:\Program
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [META-TAGGER][COMIC-TAGGER] : None
26-Feb-2015 07:23:47 - INFO    :: Thread-14 : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging
26-Feb-2015 07:23:47 - ERROR   :: Thread-14 : [META-TAGGER] Unable to move file from temporary path. Deletion of temporary path halted.
26-Feb-2015 07:23:47 - ERROR   :: Thread-14 : [META-TAGGER] attempt to move: D:\Mylar\480671\Deadpool 042 (2015).cbz to D:\Mylar\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - INFO    :: Thread-14 : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Deadpool 042 (2015).cbz) - Continuing..
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] otofilename:D:\Mylar\480671\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir: D:\Mylar\480671
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename: Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] path: Deadpool 042 (2015)
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] ext:.cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Filename: Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Extension: .cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] New Filename: Deadpool 042 (2015)
26-Feb-2015 07:23:47 - INFO    :: Thread-14 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: K:\Comics\Marvel\Deadpool (2013)
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Source: D:\Mylar\480671\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Destination: K:\Comics\Marvel\Deadpool (2013)\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Filename is identical as original, not renaming.
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir src : D:\Mylar\480671\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Moving D:\Mylar\480671\Deadpool 042 (2015).cbz ... to ... K:\Comics\Marvel\Deadpool (2013)\Deadpool 042 (2015).cbz
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
26-Feb-2015 07:23:47 - DEBUG   :: Thread-14 : [POST-PROCESSING] Post-Processing ABORTED.
26-Feb-2015 07:23:47 - INFO    :: Thread-14 : [POST-PROCESSING] Manual post-processing completed.

**Comment by ElementSixtySix** [comment]
Interestingly it just completed tagging a bunch of cbrs without issue there. The only changed variable is that I had comictagger running a job on a bunch of files this time. I don't know if this made a difference. Will post successful logs now

**Comment by ElementSixtySix** [comment]
successful Tagging log. The log says "failed to remove temp dir", however this was removed.

26-Feb-2015 09:53:02 - INFO    :: Thread-14 : [POST-PROCESSING] Starting Post-Processing for Superior Iron Man issue: 5
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] issueid: 480683
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] issuenumOG: 5
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Zero Suppression set to : 00x
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Pretty Comic Issue is : 005
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Issue Year : 2015
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Publisher: Marvel
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Series: Superior Iron Man
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Year: 2014
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Location: K:\Comics\Marvel\Superior Iron Man (2014)
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Version: None
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] No version # found for series, removing from filename
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format is now: $Series $Issue ($Year)
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Not an annual - removing from filename parameters
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format: $Series $Issue ($Year)
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [POST-PROCESSING] Metatagging enabled - proceeding...
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] dirName:D:\Mylar
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] UNRAR path set to : C:\Program Files\WinRAR\UnRAR.exe
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] chkpath: D:\Mylar
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] chkfile: Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Paths / Locations:
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] scriptname : Mylar.py
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] downloadpath : D:\Mylar
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] sabnzbdscriptpath : K:\Mylar New
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] comicpath : D:\Mylar\480683
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] unrar_folder : D:\Mylar\480683\unrard
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Attempting to create directory @: D:\Mylar\480683
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Created directory @ : D:\Mylar\480683
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Filename is : D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] moving : D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr to D:\Mylar\480683\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] Mylar.py: converting Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbr to be zip format
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] {0}: Comicpath is D:\Mylar\480683\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).rar
26-Feb-2015 09:53:02 - DEBUG   :: Thread-14 : [META-TAGGER] {0}: Unrar is D:\Mylar\480683\unrard
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Converted directory: D:\Mylar\
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Converted filename: Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Destination path: D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] dirName: D:\Mylar
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] absDirName: D:\Mylar
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] ComicTagger 1.1.15-beta being used - using personal ComicVine API key supplied via mylar.
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] CR Tagging enabled.
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Will NOT modify existing tag blocks even if they exist already.
26-Feb-2015 09:53:06 - INFO    :: Thread-14 : [META-TAGGER] ComicRack tagging meta-tagging processing started.
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Enabling ComicTagger script: C:\Program Files (x86)\ComicTagger\comictagger.exe with options: ['-s', '--verbose', '-m', 'volume=', '--cv-api-key', XXXXXXX', '--nooverwrite', '-o', '--id', u'480683', '--type', 'cr', u'D:\\Mylar\\480683\\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz']
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Executing command: ['C:\\Program', 'Files', '(x86)\\ComicTagger\\comictagger.exe', '-s', '--verbose', '-m', 'volume=', '--cv-api-key', u'72f595aab1483d8ca63b8aaaf2f43c29cd9409e8', '--nooverwrite', '-o', '--id', u'480683', '--type', 'cr', u'D:\\Mylar\\480683\\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz']
26-Feb-2015 09:53:06 - DEBUG   :: Thread-14 : [META-TAGGER] Absolute path to script: C:\Program
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [META-TAGGER][COMIC-TAGGER] : None
26-Feb-2015 09:53:10 - INFO    :: Thread-14 : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [META-TAGGER] Sucessfully moved file from temporary path.
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [META-TAGGER] Attempting to remove: D:\Mylar\480683
26-Feb-2015 09:53:10 - INFO    :: Thread-14 : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz) - Continuing..
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] otofilename:D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir: D:\Mylar
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename: Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] path: Superior Iron Man 005 (2015) (Digital) (Zone-Empire)
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] ext:.cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Filename: Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Extension: .cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] New Filename: Superior Iron Man 005 (2015)
26-Feb-2015 09:53:10 - INFO    :: Thread-14 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: K:\Comics\Marvel\Superior Iron Man (2014)
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Source: D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Destination: K:\Comics\Marvel\Superior Iron Man (2014)\Superior Iron Man 005 (2015).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Renaming D:\Mylar\Superior Iron Man 005 (2015) (Digital) (Zone-Empire).cbz ..to.. D:\Mylar\Superior Iron Man 005 (2015).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir src : D:\Mylar\Superior Iron Man 005 (2015).cbz
26-Feb-2015 09:53:10 - DEBUG   :: Thread-14 : [POST-PROCESSING] Moving D:\Mylar\Superior Iron Man 005 (2015).cbz ... to ... K:\Comics\Marvel\Superior Iron Man (2014)\Superior Iron Man 005 (2015).cbz
26-Feb-2015 09:53:12 - DEBUG   :: Thread-14 : [POST-PROCESSING] Successfully moved to : K:\Comics\Marvel\Superior Iron Man (2014)\Superior Iron Man 005 (2015).cbz
26-Feb-2015 09:53:12 - DEBUG   :: Thread-14 : [POST-PROCESSING] Failed to remove temporary directory (D:\Mylar) - Processing will continue, but manual removal is necessary

**Comment by evilhero** [comment]
So it removed the temporary directory (last line in log), but still logged that it couldn't? 

This might be one of those windows quirks that doesn't happen on Linux based os'.  I'll have to check on my windows machine and see if I can replicate it - are your drives all local to mylar (on the same machine), or are you waiting to network drives?

**Comment by ElementSixtySix** [comment]
All local disks
