### ISSUE TITLE
Feature request : choose how home list is sorted by default

### ISSUE THREAD

**Issue by tchirou** [evilhero/mylar#952]
Hello
I know bug fixing is a priority and  but we never know, you could be bored sometime.
To me, it would be more coherent that the home list be sorted by "continuing" status first by default. It could seem lazy because it is just 2 clicks away but who would refuse perfection ?
Maybe it would be better to be able to choose each user want its list sorted by default, I don't know if it would be easy to offer.
Anyway, be sure I won't hold a grudge if it never happens as I am already grateful for the tremendous work you do.
Cheers

**Comment by evilhero** [comment]
Well that should be easy enough to implement (status as primary, series title as secondary unless a column gets manually ordered than that takes priority). 

I'll see what I can do to add this in since I don't think it would take very long to implement  ;)

**Comment by ElementSixtySix** [comment]
Would/could this also force Mylar to update active comics in this order also? Be nice to have continuing series' updated first...

**Comment by evilhero** [comment]
That's a separate item, but yes it should update continuing series first, then ended series (perhaps an option to not refresh ended series as well might be needed since series that are actually ended won't have any new updates).

**Comment by tchirou** [comment]
Hi
Any news on this matter ?
Thanks

**Comment by evilhero** [comment]
It will be in next development commit, just some personal matters are taking away a lot of my free time lately, which is why there hasn't been a recent commit

**Comment by tchirou** [comment]
No worries, take care of your closed ones and yourself, this is what matters.
