### ISSUE TITLE
Post Processing fails when moving a file to a network share 

### ISSUE THREAD

**Issue by BrokenRSA** [evilhero/mylar#954]
I'm trying to move my collection to a network drive instead of keeping on the local machine. This drive is mapped via CIFS, running on Debian. 

What seems to happen, is that the copying of the file to the network share works fine, but it fails right after that. Doing a bit of research, it seems to be an issue with the shutil.move function when copying across different file system types. Sickbeard however works fine when doing this, so perhaps that is something worth looking into. 

Log extract as follow:

26-Feb-2015 15:24:38 - INFO    :: Post-Processing : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /media/network/media/Comics/Image/Sex Criminals
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] Source: /home/osmc/Downloads/complete/comics/Sex.Criminals.010.2015.Digital.Darkness-Empire/Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] Destination: /media/network/media/Comics/Image/Sex Criminals/Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] self.nzb_folder: /home/osmc/Downloads/complete/comics/Sex.Criminals.010.2015.Digital.Darkness-Empire
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] odir: /home/osmc/Downloads/complete/comics/Sex.Criminals.010.2015.Digital.Darkness-Empire
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] ofilename:Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz
26-Feb-2015 15:24:38 - DEBUG   :: Post-Processing : [POST-PROCESSING] nfilename:Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz
26-Feb-2015 15:24:53 - WARNING :: Post-Processing : [POST-PROCESSING] Failed to move directory : /home/osmc/Downloads/complete/comics/Sex.Criminals.010.2015.Digital.Darkness-Empire/Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz to /media/network/media/Comics/Image/Sex Criminals/Sex Criminals 010 (2015) (Digital) (Darkness-Empire).cbz - check directory and manually re-run
26-Feb-2015 15:24:53 - WARNING :: Post-Processing : [POST-PROCESSING] Post-Processing ABORTED

**Comment by evilhero** [comment]
Are you on the master / development branch of mylar? 

Do mylar and sabnzbd (I'm guessing that's where the above log was generated from) reside on the same machine? If so, is the network mount on the same as either?  Are you using the Sabnzbd Download Directory option  within the mylar configuration?

**Comment by BrokenRSA** [comment]
This is on the development branch of Mylar.

Yes, this is with Mylar and SABnzbd being on the same machine. The network mount is on the same machine as well. The network share is on a drive that's formatted to NTFS.

I'm not using the SABnzbd download directory option in MYlar no.

I checked quickly and even when doing a move from the command line, I get the following errors:

mv: preserving times for '/media/network/media/Temp/Sex Criminals 010 (2015).cbz': Operation not permitted
mv: preserving permissions for '/media/network/media/Temp/Sex Criminals 010 (2015).cbz': Operation not permitted

I suspect that Mylar is also getting these errors when moving. It looks like it's trying to preserve the file datestamp and permissions when moving, and since the NTFS file system doesn't have similar attributes, it's failing at the move. The file does get copied across, but I can see the datestamp changes to the time the move happened, and doesn't match the original file's datestamp.

**Comment by evilhero** [comment]
Ok, so it's not a problem with Mylar per-se, but an underlying problem with the NTFS and mv functionality at an OS level (mylar uses the shutil.move which uses the os.rename function from my understanding).

There's not much I can do from the Mylar aspect of it, since it's occurring outside of mylar usage as well - aside from changing the operation from a mv to a cp, which 'might' help things.

But you have a couple of options: you can set the uid/gid mount options to the user mylar is running under or specify the noperms mount option.

**Comment by BrokenRSA** [comment]
I had the uid and gid set already in the mount, which wasn't working, but adding the noperm option sorted it out, thanks! I want to dig a bit into how Sickbeard does this, I suspect they have some extra error handling around this specific thing, but you can close this issue for now, much appreciated!

**Comment by evilhero** [comment]
Sickbeard might just have a simple exception that if it can't do the move to test  to see if the file made it, and assume it's a date stamp and permissions issue and to keep on trucking. Mylar catches the initial exception, since it doesn't log an actual traceback, it just needs to handle it a bit more specifically...

**Comment by BrokenRSA** [comment]
It's all good, at least with your help I found what is probably actually the right way of dealing with this, so thanks!
