### ISSUE TITLE
Odd issue when Mylar creates folders

### ISSUE THREAD

**Issue by mightyflub** [evilhero/mylar#957]
I'm running Mylar on a Ubuntu 14 box. My Comics are stored on a smb mounted share from a Synology NAS. When Mylar creates a new folder everything works fine. Except that the folders aren't visible when you browse the share on a Mac. After doing some checking it seems the Mac thinks it's a hidden folder (The files Mylar gets in these folders by sabnzb are fine on the mac. It's just the folders). I had this problem a while ago and changing some attribute seemed to fix it for folders already created but I can't figure out for the life of me what I did.

I've just browsed the share on a windows PC and the same folders are missing. If I change the folder view options on windows to show protected system files they appear. Do you have any idea what might be causing this?

**Comment by mightyflub** [comment]
I've solved my problem with a workaround but I'm not sure why Mylar is the app that does this. On my NAS there was an advanced setting called "Set default unix permissions" which presume means when it creates a file or folder. When I set this and tell Mylar to add a series the folder gets created correctly. Sab puts downloaded files in the folders correctly no matter what the settings. It's really weird. The folders that are affected can have some things done to them (Be renamed) but not others (Deleted or checked with something like lsattr for example. Even as root).

I'd be curious to know what causes it

**Comment by evilhero** [comment]
Does the user running mylar have the ability to run a chmod/chown command (meaning are you running it as a user with administrative rights)? Or how are you running mylar? 

I'm guessing the user you're running mylar as is creating the folders with whatever ownership permissions are associated with the account (ie. If you're running as mylar, then the ownership perms would be mylar:mylar). If that user then can't chmod the files, only that user and the respective group (local to ubuntu) would have access, which would lock you out using Windows / Mac sessions.

**Comment by mightyflub** [comment]
I run mylar, sickbeard and sab on startup from /etc/init.d so I'm guessing they're running as root. There's one regular user on the server. Both the user and root have full permissions to play with files on the mounted smb share. It really weird. The folders that were getting created I can chmod and mv but even root can't delete them (I have to do that from the NAS). As I say I've tweaked a setting on the NAS that seems to have corrected the problem so it's not critical. I'm just curious as to what's going on.  I did do a test by running mylar as the user rather than root and had the same folder issue.

When sab downloads files I have it put them in folders for me. No issue. When sickbeard creates season folders I don't get the issue either. When sab downloads comics and passes them to the post processing script no problem. It's just folder creation from Mylar. I'd be less concerned if I could actually figure out what was different about the folders :)

**Comment by mightyflub** [comment]
Turns out this is the same issue as 954. My NAS isn't NTFS (But that shouldn't have anything to do with a network mounted share) but turning off the setting I changed on my NAS and turning on noperm on my cifs mount fixes the issue with Mylar. I'm not sure why Mylar is the app on that server that does it but at least I know I can fix the problem at either end now :) Very, very odd though.

**Comment by evilhero** [comment]
Curious, when you mounted the cifs share - what user did the mount command? It turns out that cifs mounts inherit permissions associated with the user who mounted the share. 

Instead of noperm you could also try 'multiuser', which grants individual access to the cifs share based on the user accessing the share, not the one who mounted it. This would also allow for file/directory permissions to be assigned by mylar.
