### ISSUE TITLE
When it fails

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#958]
When Mylar grabs an nzb that fails, might it be possible for it to search and try another?

I often wind up with one or two missing issues per title. So Mylar goes and grabs the nzb, in this case not it's fault. It had "too many non-matching duplicates" when I tried to download it on its own.

But there are 3 more versions from other release groups.

![screen shot 2015-03-07 at 7 18 00 am](https://cloud.githubusercontent.com/assets/97095/6541849/e3a50cde-c49a-11e4-9929-9963a754f709.png)

Some of my apps do this: couch potato (which is now a train wreck but I digress), dognzb's movie/tv feature, and 
Sonarr(nzbdrone)

**Comment by evilhero** [comment]
Have you tried enabling failed download handling within mylar, and set it to retry on fails? 

You can also forcibly mark an issue that is in snatched status as Failed, in doing so it makes that nzb as bad and won't grab it again (at least from the same provider). I can't recall atm if it's only in snatched status, or if it's also downloaded status. 

I know when metatagging is enabled and a file gets downloaded that's corrupt (meaning it can't extract the files from the cbr), it marks it as failed and then tried to grab it from a different  source.
