### ISSUE TITLE
FR : Show "snatched but not downloaded" in wanted page

### ISSUE THREAD

**Issue by tchirou** [evilhero/mylar#963]
Hello

We are discussing a new filter over at Sickrage to indicate in the coming episodes list when a show is snatched but not downloaded to avoid having to check manually show by show in the history page

This could be a nice feature too to have this in the wanted list : if the list is empty, everything is good and no need to check further if something went wrong in the download or the post process or whatever.
What do you think ?

**Comment by evilhero** [comment]
So you want the Wanted tab to show wanted issues & snatched issues?? Or the upcoming tab to show snatched issues? 

It might be possible, but it would make it very cluttered in the current state I'd imagine - it would also require some reworking of the tabs and naming conventions therein. 

A filter showing snatched and wanted on the tab might be more doable (kinda like what the issues filter does on the series detail page).

**Comment by tchirou** [comment]
Yeah the filter like on the series detail page is good
So when the wanted page is empty, we know that everything has been snatched and downloaded (or manually post processed) properly, so no need to investigate further.

**Comment by evilhero** [comment]
Kinda like this ? 
![wanted](https://cloud.githubusercontent.com/assets/909424/6754393/a02c0f9a-cef2-11e4-8383-0abb4977f0b4.png)

**Comment by tchirou** [comment]
Yes but once it has been downloaded or manually post processed, it
should disappear.
Right ?

**Comment by evilhero** [comment]
Yes, that only shows issues that are in Wanted status (as it currently is now), and the change will allow it to show Snatched issues. The post-processing/downloading has no bearing on this as it's only looking at those 2 status' to display.

**Comment by tchirou** [comment]
Wonderful
Many thanks !



Le 20 mars 2015 à 16:25, evilhero <notifications@github.com> a écrit :

Yes, that only shows issues that are in Wanted status (as it currently is
now), and the change will allow it to show Snatched issues. The
post-processing/downloading has no bearing on this as it's only looking at
those 2 status' to display.

—
Reply to this email directly or view it on GitHub
<https://github.com/evilhero/mylar/issues/963#issuecomment-84048803>.
