### ISSUE TITLE
Doing  a Manual Post-Process sometimes deletes the directory

### ISSUE THREAD

**Issue by adrianmoisey** [evilhero/mylar#964]
When doing a Manual Post-Process sometimes mylar deletes the directory that it was scanning.

**Comment by evilhero** [comment]
Is the directory empty when it gets deleted? If so, this is probably normal behaviour as mylar checks to see if its empty before deleting (and it should also not delete it if it was the directory being passed in the manual post-processing command) 

If it wasn't empty, then we need to look more closely as to what's going on for sure.

**Comment by adrianmoisey** [comment]
I think it's empty before it deleted it

**Comment by evilhero** [comment]
And the deleted directory was the directory (not the subdirs) you passed it using the Manual post-processing command I'm guessing right?

**Comment by adrianmoisey** [comment]
Yup
