### ISSUE TITLE
This week the pull list shows none of my titles as wanted

### ISSUE THREAD

**Issue by mightyflub** [evilhero/mylar#965]
Like the subject says. All the titles in the current pull list show as if I hadn't already added some of them. (Everything is listed as skipped and the options add series and one off are present) If I click add series they do show as added to my library. Nothing gets downloaded automatically.

When I click "one off" mylar pulls down the nzb, passes it to sabnzbd which downloads but either hangs on the sab part of the post processing (Which previously worked) or fails with an error in sab. 

Loading config from /home/flub/sabscripts/autoProcessComics.cfg
Opening URL: http://localhost:8090/post_process?nzb_name=Earth+2+-+World%27s+End+024+%282015%29+%28Digital%29+%28ThatGuy-Empire%29&failed=0&apc_version=1.0&comicrn_version=1.0&nzb_folder=%2Fexport%2Fdiskstation1%2Fsabdata%2FData%2FComics%2FEarth+2+-+World%27s+End+024+%282015%29+%28Digital%29+%28ThatGuy-Empire%29
nzb name: Earth 2 - World's End 024 (2015) (Digital) (ThatGuy-Empire)

nzb folder: /export/diskstation1/sabdata/Data/Comics/Earth 2 - World's End 024 (2015) (Digital) (ThatGuy-Empire)

nzbname: Earth.2.-.Worlds.End.024.(2015).(Digital).(ThatGuy-Empire)

Failure - could not initially locate nzbfile in my database to rename.

trying again with this nzbname: Earth.2.-.Worlds.End.024.2015.Digital.ThatGuy-Empire

Unable to locate downloaded file to rename. PostProcessing aborted.

---

Additionally when I try to use the feature  "recreate pull list" it fails with this error

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/flub/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/flub/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/home/flub/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/flub/mylar/mylar/webserve.py", line 1707, in pullrecreate
    weeklypull.pullit(forcecheck)
  File "/home/flub/mylar/mylar/weeklypull.py", line 447, in pullit
    pullitcheck(forcecheck=forcecheck)
  File "/home/flub/mylar/mylar/weeklypull.py", line 526, in pullitcheck
    chklimit = helpers.checkthepub(watchd[0])
  File "/home/flub/mylar/mylar/helpers.py", line 956, in checkthepub
    if publish in str(pubchk['ComicPublisher']).lower():
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 10: ordinal not in range(128)

---

Mylar has been running really well for ages. Not sure what the problem is now.

**Comment by evilhero** [comment]
It looks like you have a publisher with a weird character in its name that it's erroring out on (something in your weekly pull). It errors out trying to update the pullist, so it can't do the next step which is marking issues as Wanted and subsequently downloading them. 

You'll have to check your mylar.log file when you do a few recreate pullist and it should indicate what series is causing the problem just prior to the error getting logged. If I know the series, I can fix the code to accommodate but I don't see anything on this week's pullist offhand that would cause the error by itself (mine pulled down fine this week). 

The one off post-processing is probably broken since a lot of changes have happened.. It's on my to do to get it working again once the  next development commit goes up.

**Comment by mightyflub** [comment]
The logs show this at the end of recreating the pulllist

0-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'GN', 'SERVAMP', 'VOL 01', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'GN', 'SEVEN DEADLY SINS', 'VOL 07', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '219', 'SIMPSONS COMICS', 'None', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '10', 'SOLAR MAN OF ATOM', 'CVR A LAMING MAIN', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'TP', 'SONIC SAGA', 'VOL 07 DARK MIRROR', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '19', 'SONS OF ANARCHY', '(MR)', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '2', 'STEAM TALES', 'None', 'Skipped']
20-Mar-2015 05:57:49 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'GN', 'STRIKE WITCHES ONE WINGED WITCHES', 'VOL 02 (MR)', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '1', 'TALES FROM THE CREEP', '(ONE-SHOT)', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '5', 'TERRIBLE LIZARD', 'None', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'HC', 'THIRD TESTAMENT', 'VOL 03 MIGHT OF THE OX', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '3', 'TUKI SAVE THE HUMANS', 'None', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', 'GN', 'UNDERSEA ADV OF CAPTAIN ELI', 'VOL 03', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '1', 'UNIT 5', 'None', 'Skipped']
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Row: ['2015-03-18', 'COMICS', '9', 'ZOMBIE TRAMP', '#9 MAIN CVR (MR)', 'Skipped']
20-Mar-2015 05:57:50 - INFO    :: CP Server Thread-4 : Weekly Pull List successfully loaded.
20-Mar-2015 05:57:50 - INFO    :: CP Server Thread-4 : Checking the Weekly Releases list for comics I'm watching...
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : ComicName: Wolverine & the X-Men
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : latestdate:  2015-01-31
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : c_date : 2015-01-31 ... n_date : 2015-03-20
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : recentchk: 48 days
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Biggie publisher detected - Marvel
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Check date limit set to : 55
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 :  -----
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : no Alternate name given. Aborting search.
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : ComicName: Amazing X-Men
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : latestdate:  2015-04-30
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : c_date : 2015-04-30 ... n_date : 2015-03-20
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : recentchk: -41 days
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Biggie publisher detected - Marvel
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : Check date limit set to : 55
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 :  -----
20-Mar-2015 05:57:50 - DEBUG   :: CP Server Thread-4 : no Alternate name given. Aborting search.

And then it looks like it goes all the way through my list deciding to abort the search on each one. I did notice this when it started the process

20-Mar-2015 05:57:37 - DEBUG   :: CP Server Thread-4 : shipdate: 20150318
20-Mar-2015 05:57:37 - DEBUG   :: CP Server Thread-4 : today: 00000000

Could all those zeros have anything to do with it?

**Comment by mightyflub** [comment]
I think I found it. The log ended at a new comic called The Metabarons. The publisher just happens to be Les Humanoïdes Associés. I remove that and it's working now. I think I added that at some point last week. Presumably after the pullist had already been done.

Thanks for the help

**Comment by mightyflub** [comment]
Oh and I don't know why but the weekly folder creation has just started working for me. I've never had it do anything at all since the day it was patched in. This week it's started making copies of my stuff in the folder (It never even created the folder previously) so that's amazing. If you made a fix for that it's very welcome indeed

**Comment by evilhero** [comment]
The error you getting with that particular publisher will be fixed in the next development commit - so you can re-add it back in then if you want and everything should still work.

I didn't patch anything as of late for the weekly folder creation, but if you had encountered errors before or there were problems with the pull-list / post-processing then the folders probably weren't getting created or it was pointing to a dead link and was just supressing the error for some reason. Regardless, glad it's working for you now ;)

**Comment by mightyflub** [comment]
In the end it only put 6 or 7 issues in the weekly folder but it's progress and given the problems I had this week it's impressive. I'll see how it goes next week :) Thanks for the help

**Comment by evilhero** [comment]
Anytime - it 'should' be putting anything that's on the current pull-list that's in a Downloaded status into that weekly directory. If you happen to use torrents, and you post-process after the weekly pull-list has changed, then it wouldn't move them because it can't locate the issue on the pull-list - a future release will allow it to match up against previous weeks and put them in the proper directories (which could cause some confusion obviously for past pull-lists), but at the very least the option will be there if someone wants to use it or not.
