### ISSUE TITLE
Issue with Pushover notifications failing

### ISSUE THREAD

**Issue by SebNYD** [evilhero/mylar#972]
Hello,

Since I went with a clean install, Pushover fails to work properly.

I'm using it with a personnal API key.

Thanks for your help,

Here is an example log : 

03-avr.-2015 18:16:59 - INFO    :: Thread-12 : Successfully sent nzb file to SABnzbd
03-avr.-2015 18:16:59 - DEBUG   :: Thread-12 : we should break out now - sucessful search previous
03-avr.-2015 18:16:59 - DEBUG   :: Thread-12 : Found matching comic...preparing to send to Updater with IssueID: 482192 and nzbname: Sheltered.015.2015.Digital.Vee-Empire[Sheltered.015.2015.Digital.Vee-Empire]
03-avr.-2015 18:16:59 - INFO    :: Thread-12 : setting the nzbid for this download grabbed by nzb.su in the nzblog to : c7660f4aea03363f4ad47089649011ee.nzb&i=84030&r=none
03-avr.-2015 18:16:59 - INFO    :: Thread-12 : setting the alternate nzbname for this download grabbed by nzb.su in the nzblog to : Sheltered.015.2015.Digital.Vee-Empire
03-avr.-2015 18:16:59 - INFO    :: Thread-12 : Sending Pushover notification
03-avr.-2015 18:17:00 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "E:\Multimedia\Logiciels\Mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\Multimedia\Logiciels\Mylar\mylar\webserve.py", line 1290, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "E:\Multimedia\Logiciels\Mylar\mylar\search.py", line 225, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "E:\Multimedia\Logiciels\Mylar\mylar\search.py", line 1301, in NZB_SEARCH
    notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
  File "E:\Multimedia\Logiciels\Mylar\mylar\search.py", line 1892, in notify_snatch
    pushover.notify(thisline,snline)
  File "E:\Multimedia\Logiciels\Mylar\mylar\notifiers.py", line 181, in notify
    headers = {'Content-type': "application/x-www-form-urlencoded"}
  File "C:\Python27\lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1216, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 350, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

03-avr.-2015 18:17:04 - DEBUG   :: FOLDERMONITOR : Starting new thread: FOLDERMONITOR
03-avr.-2015 18:17:04 - INFO    :: FOLDERMONITOR : delaying startup thread for 60 seconds to avoid locks.

**Comment by evilhero** [comment]
I don't use pushover so I'll have to see what's going on. It looks like it's having a problem with the https - not sure if it's a problem with what mylar is sending or if it's the pushover api /site. Will check and update.

**Comment by SebNYD** [comment]
Hello,

It seems that something else was at play in my issue following my fresh install.
I was using ComicTagger but WinRAR was not installed yet, which was making the tagging failed.
In this context, Pushover failed too.

Since I installed WinRAR everything is now working properly.

Best regards,
