### ISSUE TITLE
Weird mismatch in dates with the comic "Kanan - The Last Padawan"?

### ISSUE THREAD

**Issue by Rawh** [evilhero/mylar#975]
Hello,

When I compare the wiki site with the comic list : http://starwars.wikia.com/wiki/Star_Wars:_Kanan:_The_Last_Padawan

To the Mylar found comic overview (screenshot
![kadan_comic](https://cloud.githubusercontent.com/assets/10486655/7028715/f5ce7cd0-dd57-11e4-89d5-7eec0662141f.jpg)), the dates dont seem to be the same?
Searching on with the Mylar site, I keep on having empty results (dognzbd index site).

When using a manual search by hand on the episode I can actually find and download it. 

Any idea why the dates do not add up?

**Comment by evilhero** [comment]
Mylar shows the publication dates for all issues, which is different than the actual store date. Generally the publication dates are +1-2 months beyond the actual store date and is the date us d by the indicas. This is how comicvine displays dates as well (which is where mylar pulls information from). 

When searching mylar will use the store date, if that's not available then it will use the publication date. While it shows the publication dates, it also stores the store dates as well. 

If you click on the Manage option at the very top, and select manage issues - change the status to whatever the kanan issue is and then find it in the list. It will show the store date and issue date. 

If a publication date is wrong or list as 0000-00-00 you can edit it by simply clicking on the date within mylar (only on the comic details page), and entering in the correct value. Mylar will then use this value if the store date was listed as 0000-00-00 which happens on really old issues, or very very new issues occasionally.

**Comment by Rawh** [comment]
Read the edit part, cheers for explaining that. I will need to express more patience :)
