### ISSUE TITLE
OSX meta tagging not working

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#976]
Hi there,

I have enabled meta tagging and post processing in Mylar. I have copied the comictagger lib into the correct location within the Mylar folder and left the comictagger location in the GUI to the default.

Whenever a file is post processed, Mylar doesn't even attempt to tag it, the logs do not mention metatagging at all. When running a manual tag, it instantly provides a pop up saying tagging complete but does not actually write any tags to the files.

The files are all torrents through KAT downloaded by Transmission. I am running OS X 10.10 and the master version of Mylar.

I've read through everything I can here and on the forums but I'm still at a loss. Any help would be greatly appreciated!

**Comment by evilhero** [comment]
It's probably related to not being able to find the unrar binary on your system. Check the mylar.log file itself (it holds the debugging information), and see what it says for the reason why it's failing. 

If you need to set the unrar path to something other than the default location.. Shutdown mylar, edit the config.ini and find the line that says unrar_cmd and enter in the full path to the binary. Save the config.ini and start up mylar and if that was the issue it will start tagging.

**Comment by kurnalbert** [comment]
Thanks for your reply, I'm halfway there now. 

Currently when attempting to manually tag a file, it will get moved from the comics specific folder to the root comic directory but not write any metadata into the file. 

08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] dirName:/Users/tv/eBooks/Comics/Venom (2011)
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] UNRAR path set to : /Applications/rar/unrar
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Paths / Locations:
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] scriptname : Mylar.py
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] downloadpath : /Users/tv/eBooks/Comics/Venom (2011)
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] sabnzbdscriptpath : /Applications/Mylar-master
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] comicpath : /Users/tv/eBooks/Comics/Venom (2011)/temp
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] unrar_folder : /Users/tv/eBooks/Comics/Venom (2011)/temp/unrard
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Attempting to create directory @: /Users/tv/eBooks/Comics/Venom (2011)/temp
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Created directory @ : /Users/tv/eBooks/Comics/Venom (2011)/temp
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Filename is : /Users/tv/eBooks/Comics/Venom (2011)/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : /Users/tv/eBooks/Comics/Venom (2011)/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] moving : /Users/tv/eBooks/Comics/Venom (2011)/Venom 041 (2013).cbz to /Users/tv/eBooks/Comics/Venom (2011)/temp/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - INFO    :: CP Server Thread-6 : [META-TAGGER] Filename detected as a .cbz file.
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] filename : /Users/tv/eBooks/Comics/Venom (2011)/temp/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] This is a zipfile. Unable to test rar.
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Base set to : /Users/tv/eBooks/Comics/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Moving : /Users/tv/eBooks/Comics/Venom (2011)/temp/Venom 041 (2013).cbz - to - /Users/tv/eBooks/Comics/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Verified file exists in location: /Users/tv/eBooks/Comics/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Successfully removed temporary directory: /Users/tv/eBooks/Comics/Venom (2011)/temp
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] new filename : /Users/tv/eBooks/Comics/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Converted directory: /Users/tv/eBooks/Comics/Venom (2011)
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Converted filename: Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] Destination path: /Users/tv/eBooks/Comics/Venom (2011)/Venom 041 (2013).cbz
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] dirName: /Users/tv/eBooks/Comics/Venom (2011)
08-Apr-2015 21:41:31 - DEBUG   :: CP Server Thread-6 : [META-TAGGER] absDirName: /Users/tv/eBooks/Comics/Venom (2011)

When attempting to automatically  tag a newly downloaded comic, it does the same thing except that it gets stuck in a temporary folder that it creates:

08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [POST-PROCESSING] Metatagging enabled - proceeding...
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] dirName:/Users/tv/Downloads
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] UNRAR path set to : /Applications/rar/unrar
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] chkpath: /Users/tv/Downloads
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] chkfile: Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Paths / Locations:
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] scriptname : Mylar.py
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] downloadpath : /Users/tv/Downloads
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] sabnzbdscriptpath : /Applications/Mylar-master
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] comicpath : /Users/tv/Downloads/485504
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] unrar_folder : /Users/tv/Downloads/485504/unrard
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Attempting to create directory @: /Users/tv/Downloads/485504
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Created directory @ : /Users/tv/Downloads/485504
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Filename is : /Users/tv/Downloads/Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : /Users/tv/Downloads/Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] moving : /Users/tv/Downloads/Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr to /Users/tv/Downloads/485504/Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] Mylar.py: converting Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbr to be zip format
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] {0}: Comicpath is /Users/tv/Downloads/485504/Ant-Man 004 (2015) (Digital) (Zone-Empire) .rar
08-Apr-2015 21:52:10 - DEBUG   :: Thread-29 : [META-TAGGER] {0}: Unrar is /Users/tv/Downloads/485504/unrard
08-Apr-2015 21:52:19 - DEBUG   :: Thread-29 : [META-TAGGER] Converted directory: /Users/tv/Downloads/
08-Apr-2015 21:52:19 - DEBUG   :: Thread-29 : [META-TAGGER] Converted filename: Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbz
08-Apr-2015 21:52:19 - DEBUG   :: Thread-29 : [META-TAGGER] Destination path: /Users/tv/Downloads/Ant-Man 004 (2015) (Digital) (Zone-Empire) .cbz
08-Apr-2015 21:52:19 - DEBUG   :: Thread-29 : [META-TAGGER] dirName: /Users/tv/Downloads
08-Apr-2015 21:52:19 - DEBUG   :: Thread-29 : [META-TAGGER] absDirName: /Users/tv/Downloads

**Comment by evilhero** [comment]
Pretty sure the first issue was fixed in the development build, but hasnt made it to the master branch due to the enormous amount of fixes than went into the branch at that time in order to allow for bug fixing. 

The downloading problem might be related to something else, but it's hard to tell without seeing the rest of the log to know what's actually happening. It could be an issue with comicvine, Comictagger, mylar or any combination of the three. Can you post a full post-processing log from the mylar.log file so I can see the complete work flow?

**Comment by kurnalbert** [comment]
Here is the rest of the post processing log for that same file:

08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Was downloaded from KAT. Enabling torrent manual post-processing completion notification.
08-Apr-2015 22:20:33 - INFO    :: Thread-70 : [POST-PROCESSING] Starting Post-Processing for Ant-Man issue: 3
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] issueid: 482152
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] issuenumOG: 3
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Zero Suppression set to : 00x
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Pretty Comic Issue is : 003
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Issue Year : 2015
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Publisher: Marvel
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Series: Ant-Man
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Year: 2015
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Comic Location: /Users/tv/eBooks/Comics/Ant-Man (2015)
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Comic Version: None
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] No version # found for series, removing from filename
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] New format is now: $Series $Issue ($Year)
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Not an annual - removing from filename parameters
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] New format: $Series $Issue ($Year)
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [POST-PROCESSING] Metatagging enabled - proceeding...
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] dirName:/Users/tv/Downloads
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] chkpath: /Users/tv/Downloads
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] chkfile: Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Paths / Locations:
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] scriptname : Mylar.py
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] downloadpath : /Users/tv/Downloads
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] sabnzbdscriptpath : /Applications/Mylar-master
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] comicpath : /Users/tv/Downloads/482152
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] unrar_folder : /Users/tv/Downloads/482152/unrard
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Attempting to create directory @: /Users/tv/Downloads/482152
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Created directory @ : /Users/tv/Downloads/482152
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Filename is : /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] The path where the file is that I was provided is probably wrong - modifying it to : /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] moving : /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz to /Users/tv/Downloads/482152/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - INFO    :: Thread-70 : [META-TAGGER] Filename detected as a .cbz file.
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] filename : /Users/tv/Downloads/482152/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] This is a zipfile. Unable to test rar.
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Base set to : /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Moving : /Users/tv/Downloads/482152/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz - to - /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Verified file exists in location: /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Successfully removed temporary directory: /Users/tv/Downloads/482152
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] new filename : /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Converted directory: /Users/tv/Downloads/
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Converted filename: Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] Destination path: /Users/tv/Downloads/Ant-Man 003 (2015) (digital) (Minutemen-Faessla).cbz
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] dirName: /Users/tv/Downloads
08-Apr-2015 22:20:33 - DEBUG   :: Thread-70 : [META-TAGGER] absDirName: /Users/tv/Downloads

**Comment by evilhero** [comment]
If that's where it's failing, then it's having problems with your Comictagger installation - when you copied the files into the mylar/lib/comictagger/ folder, did you overwrite the comictagger.py file located in the root of mylar? 

If, from a command prompt/she'll you can issue this command :

python Comictagger.py - - version

If it's working it will display the version, if it's not then your Comictagger installation isn't working with mylar.

**Comment by kurnalbert** [comment]
When I copied in the library I made sure not to overwrite the comictagger.py in the root of Mylar. Just to make sure, I just reinstalled it from the master version on github then ran the command and all I got was the following error: 

PyQt4 is not available.  ComicTagger is limited to command-line mode.
Cannot find -
Cannot find -
Cannot find version

**Comment by kurnalbert** [comment]
I realise that the command you wanted me to run had gotten spaced wrong. When I ran it properly it returned the correct version of ComicTagger:

server:mylar-master tv$ python comictagger.py --version
ComicTagger 1.1.15-beta:  Copyright (c) 2012-2014 Anthony Beville
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

**Comment by evilhero** [comment]
Ok so it's setup right then, how do you start mylar up? Can you try running mylar from a command prompt  (python Mylar.py)  and then try a post-processing run? 

There's something happening on the command that's messing up things. You might see it in the console..

**Comment by kurnalbert** [comment]
Aha! I have been running it from a LaunchDaemon so that it would stat up with my computer. When unloading that LaunchDaemon and running it from the command line, it appears to be tagging successfully!
