### ISSUE TITLE
500 error on search

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#977]
Just started after update to latest dev release. Doesn't matter what the search string is.
Anyone else?

Traceback (most recent call last):
  File "K:\Mylar New\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "K:\Mylar New\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "K:\Mylar New\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "K:\Mylar New\mylar\webserve.py", line 199, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=None, explicit=explicit)
TypeError: 'bool' object is not iterable

**Comment by evilhero** [comment]
Nothing  got charged in that module in the last few commits (was just rss stuff). Have you tried restarting mylar? 

What is it that you're trying to search for? (I'm guessing you're typing a series name in the search box and clicking on search) The error indicates it's a problem with one of the variables being a true/false when it shouldn't be..

**Comment by ElementSixtySix** [comment]
Yeah strike that. Reverting to previous commit, and master branch return same error so I've messed something up myself.

**Comment by evilhero** [comment]
If you happen to figure it out, post back and I might be able to trap those kinds of errors (well it's a goal to). Or if you need some help in figuring things out, I'm here as well for that ;)

**Comment by ElementSixtySix** [comment]
I changed DNS servers to OpenDNS with moderate filtering (porn, nudity, etc). Comicvine is blocked (tagged nudity) with these. Thankfully they allow whitelists so all is good now.
