### ISSUE TITLE
Dark Horse Presents (1986) Alpha-Numeric

### ISSUE THREAD

**Issue by SquaTront** [evilhero/mylar#979]
I tried to add Dark Horse Present (1986) and received the following:

12-Apr-2015 20:40:40 - INFO :: Thread-14 : Sucessfully retrieved issue details for Dark Horse Presents
12-Apr-2015 20:40:41 - INFO :: Thread-14 : Now adding/updating issues for Dark Horse Presents
12-Apr-2015 20:40:41 - ERROR :: Thread-14 : 100-0 this has an alpha-numeric in the issue # which I cannot account for.
12-Apr-2015 20:40:41 - WARNING :: Thread-14 : Unable to complete Refreshing / Adding issue data - this WILL create future problems if not addressed.

Yeah, there's strange numbering scheme for issue 100. Five different issues numbered 100-0 to 100-4.

**Comment by evilhero** [comment]
Saw this when you posted but forgot to reply.. Sorry. I'll look into this, but yeah the -  in the issue number would throw things off cause mylar would either think it's a negative number or the start of the issue title.
