### ISSUE TITLE
After restarting Mylar, Type error upon init

### ISSUE THREAD

**Issue by kae24** [evilhero/mylar#983]
Not sure why when i restart mylar this occurs

Traceback (most recent call last):
  File "/opt/Mylar/Mylar.py", line 261, in <module>
    main()
  File "/opt/Mylar/Mylar.py", line 194, in main
    mylar.initialize()
  File "/opt/Mylar/mylar/__init__.py", line 865, in initialize
    flatt_providers.append(re.sub('cbt','32p',value))
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

any ideas?

**Comment by evilhero** [comment]
Check you config.ini, and see what is given for provider_order - what has happened (actually yesterday someone else mentioned this on the forums), is that a blank provider entry was placed at the very beginning (for him) and it was causing the exact same error.

I have a fix going up shortly, but if you can beat me to it, you just need to remove the blank entry from the provider_line (ie. normally it should show : 0, experimental, 1, cbt, 2, kat, etc... but in these cases it's been : 0,  1, experimental, 2, cbt, 3, kat, etc...)

**Comment by kae24** [comment]
I don't think i have a provider_line option in the config.ini file. I did however have a provider_order option

**Comment by evilhero** [comment]
oh, lol - sorry, stupid auto-correct on phone. Yes, the provider_order line is what you want to look at.

**Comment by kae24** [comment]
no problem! sorry to bother you again but i'm running to another issue:

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/search.py", line 1404, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/opt/Mylar/mylar/search.py", line 225, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/opt/Mylar/mylar/search.py", line 1283, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov)
File "/opt/Mylar/mylar/search.py", line 1777, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
File "/opt/Mylar/mylar/rsscheck.py", line 764, in torsend2client
from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named packages.urllib3.exceptions


i did a check for urllib3, and its version 1.7.1

**Comment by evilhero** [comment]
Well, Mylar forces the uses of the requests library that comes with it (in (mylarroot)/lib/requests) - I'm going to guess that you have your lib directory in a different location than the rest of the program (did you specify datadir on startup, or are you using some other package) ?

**Comment by kae24** [comment]
i'm following the exact same steps posted here http://www.htpcguides.com/install-mylar-ubuntu-usenet-comics/

so i'm not sure :s

**Comment by evilhero** [comment]
That's abit weird - can I ask what commit of Mylar you're running?

**Comment by kae24** [comment]
Mylar Version: development
-- git build 5c2a24f874455e53609903e71e9c219da12fad36.
Python Version : 2.7.6

MYLAR PROGRAM OPTIONS
Mylar Data Directory : /opt/Mylar
Mylar Program Directory : /opt/Mylar
Mylar Cache Directory : /opt/Mylar/cache
Mylar Config File :/opt/Mylar/config.ini

**Comment by evilhero** [comment]
Try updating to the latest development commit - hopefully it will fix things for you.

**Comment by kae24** [comment]
I did a complete reclone and it still gives me the same error

**Comment by evilhero** [comment]
Ok, most recent commit should work (I hope)

**Comment by kae24** [comment]
Yep does work, Thanks for your help i'll go about ironing out the other issues as best as I can!

Thanks again!
