### ISSUE TITLE
Error during KAT torrent manual search

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#984]
Hello,

Mylar is great, and I am really excited to use it.

I first got all my existing library scanned in and that worked great.  But I now want to start downloading torrents to fill some of the holes in my library.

First, I have setup transmission on my Ubuntu box, and have set the watch directory, and selected KAT as my search provider.  

My first issue was that it was not searching anything, but i fixed that.  My search provider order list in config.ini was blank, so I changed the value of the entry to 0, kat.  

This made mylar actually try searching kat, but now I get an import error:
![mylarerror](https://cloud.githubusercontent.com/assets/5505883/7220650/580b8ace-e69e-11e4-8c47-60122d84f07a.jpg)

I am on:

Mylar Version: development
-- git build fda491e2fcdfe598ca61f68f2bb0bb136cd2ec70.
Python Version : 2.7.6

**Comment by evilhero** [comment]
Yeah there's something really messed up with both urllib3 and the requests modules.. I thought I had this fixed recently, but obviously not. 

The easiest solution for you is to just install python-requests (or python-urllib3, but requests has a built in urllib3 so that's probably preferable) . In doing so, mylar will be able to load the module and avoid the error. 

I'll look into this more today, but it might be abit before I can get a working version going that works across all OS'.

**Comment by BenBeyond** [comment]
Thanks for the quick follow-up and info.  

I just tried to install either of these, but Ubuntu says I already have the newest version of both installed.

Running Ubuntu 14.04.2, in case that is related.

**Comment by evilhero** [comment]
Ok, I'm on Ubuntu 12.04 and I haven't had the problems, but that doesn't mean they're not happening obviously ;)

Can you get to a python prompt (you have to be in the root of the mylar directory for this to work), and type in the following:
```
import lib.requests as requests
from requests.packages.urllib3 import disable_warnings
disable_warnings()
```
I'm hoping that won't throw any errors - if it does, then I need to rejig that abit, if it doesn't it means that things are working and I can roll that out so Mylar will work for ya...

**Comment by BenBeyond** [comment]
Ran all the lines individually, but get an error on the first one:

Python 2.7.6 (default, Mar 22 2014, 22:59:38)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lib.requests as requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lib.requests
>>> from requests.packages.urllib3 import disable_warnings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named packages.urllib3
>>> disable_warnings()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'disable_warnings' is not defined
>>>

**Comment by evilhero** [comment]
sorry, that's my fault (I'm doing too much at once here) - can you replace the 2nd line with:
```
from lib.requests.packages.urllib3 import disable_warnings
```
I'm pretty sure that will work, but I just would like to confirm it's working for you before I roll that out.

**Comment by BenBeyond** [comment]
yep, that works in my python prompt. Thanks!

**Comment by evilhero** [comment]
k, hang tight - will commit up for ya momentarily .. thanks for the quick feedback! ;)

**Comment by BenBeyond** [comment]
Bit of a thread hijack, but any idea why my search provider order list would have been empty? It was an easy fix, but took a bit of forum fishing to find the answer.

**Comment by evilhero** [comment]
Did you happen to restart Mylar after you made the provider changes (or for that matter, any configuration change)? If you didn't restart Mylar after you saved the configuration changes, the provider_order wouldn't have been generated (it only generates it on startup).

**Comment by BenBeyond** [comment]
I did a number of restarts since making the provider changes, to make sure that the error you just fixed couldn't be cleared with a restart.

Oh well, not an issue anymore. Thanks again.

**Comment by evilhero** [comment]
Latest development commit has the ImportError fix.

The provider order portion is going to get an overhaul soon - I'm going to try to GUI it and fix things up abit, as first-run usage of it seems to not work very reliably for some, but once it's set it should be  good from that point.

**Comment by BenBeyond** [comment]
Just updated and everything is working great. Thanks again!
