### ISSUE TITLE
Another Feature Request

### ISSUE THREAD

**Issue by ElementSixtySix** [evilhero/mylar#985]
Option to NOT update/refresh/check comics with status "Ended"

**Comment by evilhero** [comment]
Well it doesn't check Ended series against the pullist already (which has caused some issues, but that's the way it is), but the 'db update all active series' option can have a sub-option to not look at Ended series for sure.

**Comment by ElementSixtySix** [comment]
Or better yet.... (If) 'issues have' = 'total issues' & 'status = ended' then pause comic?

**Comment by evilhero** [comment]
Yeah that logic wouldn't really hold up well if it's an indie-type comic where it's not in a regular publication schedule (ie. Saga). Those types of series get marked by mylar usually as ended by mistake, and adding in the pause would further the problem as they would never get updated. 

I like the idea, it's just finding the correct logic that will work across the greater mass of series which might take some experimenting.
