### ISSUE TITLE
mylar has stopped downloading again

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#986]
I think it broke after one of the updates of the last few days.

I haven't downloaded anything since the 15th. I even added a new, popular comic to test, and nothing.

I have restarted, done both the force options on the manage page, and no bueno.

**Comment by evilhero** [comment]
What providers are you checking against? (or you're trying to download from) 

Is there anything in the mylar.log file showing the searching and resulting no finds?

**Comment by lostkt87** [comment]
I'm having the same problem and agree with AtariBaby. Here's what I'm getting in my logs

Error

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 605, in addComictoDB
search.searchforissue(result['IssueID'])
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1443, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 225, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 486, in NZB_SEARCH
findurl = findurl + "&apikey=" + str(apikey)
UnboundLocalError: local variable 'findurl' referenced before assignment


Not sure what is happening. After update it just stopped working normally and won't download anything

**Comment by evilhero** [comment]
Just a couple lines up from that error in your mylar.log file, there should be a line stating what the nzbprov is...does it contain the word 'newznab' at all ?

**Comment by lostkt87** [comment]
22-Apr-2015 22:03:52 - DEBUG   :: SEARCH : nzbprov: 
22-Apr-2015 22:03:52 - DEBUG   :: SEARCH : comicid: 79836
22-Apr-2015 22:03:52 - DEBUG   :: SEARCH : Exception generated in thread SEARCH: local variable 'findurl' referenced before assignment
22-Apr-2015 22:03:52 - DEBUG   :: SEARCH : 'Traceback (most recent call last):\n  File "/volume1/@appstore/mylar/share/mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/volume1/@appstore/mylar/share/mylar/mylar/searchit.py", line 29, in run\n    mylar.search.searchforissue()\n  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1404, in searchforissue\n    foundNZB, prov = search_init(comic[\'ComicName\'], result[\'Issue_Number\'], str(ComicYear), comic[\'ComicYear\'], Publisher, IssueDate, StoreDate, result[\'IssueID\'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result[\'ComicID\'], filesafe=comic[\'ComicName_Filesafe\'])\n  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 225, in search_init\n    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)\n  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 486, in NZB_SEARCH\n    findurl = findurl + "&apikey=" + str(apikey)\nUnboundLocalError: local variable \'findurl\' referenced before assignment\n'

**Comment by lostkt87** [comment]
that help?

**Comment by evilhero** [comment]
Yups, on the right track - can you confirm/not that your provider_order line doesn't have any blank entries ?

**Comment by lostkt87** [comment]
look in the config file right

**Comment by evilhero** [comment]
yes, it's the only place you can currently look/edit that option.

**Comment by lostkt87** [comment]
provider_order = 0, dognzb, 1, NZBGeek, 2, ""

**Comment by evilhero** [comment]
bingos...Ok, wipe out that 2, "" (make sure mylar isn't running), and then start it up and it should work.

Now I know where it's messing, I just have to figure out the why - Cheers for the quick feedback ;)

**Comment by lostkt87** [comment]
no problem. I'm surprised you were up at this hour. its 1:30 in the morning where i am

**Comment by evilhero** [comment]
2:30 am here - sometimes it's the only time I can find some time to work on things. I'm a sucker for punishment lol

**Comment by lostkt87** [comment]
I've shut mylar down, deleted what you told me, turned mylar back on and it reappears

**Comment by evilhero** [comment]
ok, then it's due to there being either an empty newznab entry in your newznab configuration, or you have a newznab entry that doesn't have a name (the newznab entry would be enabled).

**Comment by AtariBaby** [comment]
I'll try to grok this in a bit. Thank you.

**Comment by AtariBaby** [comment]
I just emailed you a log. Wasn't sure what I was looking for.

**Comment by lostkt87** [comment]
Yeah, you were right. I have no idea, how that got pushed. Thanks though

**Comment by AtariBaby** [comment]
still stuck here

**Comment by evilhero** [comment]
@AtariBaby: Never got an email - can you resend?

**Comment by AtariBaby** [comment]
Test

**Comment by AtariBaby** [comment]
Well, I am getting my T shows and movies with no issues.

**Comment by AtariBaby** [comment]
Sent! I accidentiallly emailed it myself *sigh*

**Comment by evilhero** [comment]
I don't see anything wrong, although I don't see it searching dog or experimental via the api (it's not it that particular log file). 

Can you blank out the provider_order line in your config.ini and try again? (shutdown mylar first of course)

**Comment by AtariBaby** [comment]
That time, I added a comic and it worked fine! I pressed the two force buttons and nothing happened for a while. Maybe it's because I have so many comics; a few are trickling in now. Thank you! Close it if you think we're good now!
