### ISSUE TITLE
Colons and other punctuation in titles

### ISSUE THREAD

**Issue by solidus0079** [evilhero/mylar#987]
I was wondering if it's at all possible to alter the way certain punctuation marks in comic titles are handled, primarily colons - e.g.: "Bucky Barnes: The Winter Soldier".  As it stands, Mylar's post-processing will put downloads into folders with the colon removed.  (Becoming "Bucky Barnes The Winter Soldier)

I realize the primary reason for this is that file systems typically can't handle funny characters.

It would be nice to have an option (if it doesn't exist hidden somewhere) to replace this with a dash instead (Bucky Barnes- The Winter Soldier).  The pathing Mylar uses conflicts with my preferred reading program (that also syncs to my iPad), so I have to correct it every time and mess with the paths in Mylar for the comics that would be affected by this.

**Comment by evilhero** [comment]
Yep, on the series detail page for any given series, on the Edit tab, there's a field called Alternate File Naming. 

Put in how you want the series to be named (ie. Bucky Barnes- The Winter Soldier), hit Update and then try post-processing (or renaming) again. It will force mylar to use that title instead of the actual series title (except for searches). 

Hopefully that's what you were asking for?

**Comment by solidus0079** [comment]
Yeah that's what I meant about fixing it manually, I'm going into the various series's that use colons and the like and changing it manually.  It will result in extra empty folders, or folders that contain Comicvine info (which Comicrack uses).  I was looking for this step to be eliminated via an option to replace colons with dashes.

**Comment by evilhero** [comment]
I think I follow, so are you wanting the replacement for folders or for files (or for both)?

**Comment by solidus0079** [comment]
The folder bathing, mainly, just because it leaves empty folder clutter when I'm done changing it after it's been added.  I use Comicrack to name the files themselves, so that's not an issue for me personally.  Thanks!  :)
