### ISSUE TITLE
Automatic startup problems under Ubuntu 15.04 Vivid Vervet

### ISSUE THREAD

**Issue by cybrwizrd** [evilhero/mylar#988]
There might be an issue with mylar not starting automatically after an upgrade to Ubuntu 15.04 Vivid Vervet. 

The problem seems to be that mylar uses a classic SysV init script which was still supported under upstart, but the default init system has now been changed to systemd . 

So if you do:

`sudo service mylar start`

You might get:

**Failed to start mylar.service: Unit mylar.service failed to load: No such file or directory.**

I am looking into it right now but in the meantime, if you have that problem what you can do is just

`sudo /etc/init.d/mylar start`

and it should start fine. You'll need to do that every time you reboot, though.

**Comment by cybrwizrd** [comment]
I wrote a systemd service configuration that seems to work for me. Considering I had never seen one before this morning you probably shouldn't trust that. There are several issues with it (see comments) but maybe that's a start.

/etc/systemd/system/mylar.service
```
[Unit]
Description=Mylar, the automated Comic Book downloader
After=multi-user.target

[Service]
Type=forking
Environment=MYLAR_USER=mylar
Environment=PYTHON_BIN=/usr/bin/python
Environment=MYLAR_HOME=/opt/mylar
Environment=MYLAR_PIDFILE=/var/run/mylar/mylar.pid
Environment=MYLAR_DATA=/opt/mylar
Environment=MYLAR_OPTS=
EnvironmentFile=/etc/default/mylar

# Doesn't look like we can use a variable in User= line
User=mylar

PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p ${MYLAR_DATA}
ExecStartPre=/bin/chown ${MYLAR_USER} ${MYLAR_DATA}
ExecStartPre=/bin/bash -c "mkdir -p `dirname ${MYLAR_PIDFILE}`"
ExecStartPre=/bin/bash -c "chown ${MYLAR_USER} `dirname ${MYLAR_PIDFILE}`"
WorkingDirectory=/opt/mylar
ExecStartPre=/usr/bin/env
TimeoutStartSec=5

# Should be the same as MYLAR_PIDFILE, but systemd requires an absolute path
PIDFile=/var/run/mylar/mylar.pid


# Issue : Python path is hardcoded
# Issue : No Port definition
# Issue : No $MYLAR_OPTS
ExecStart=/usr/bin/python -- Mylar.py --quiet --daemon --nolaunch --pidfile=${MYLAR_PIDFILE} --datadir=${MYLAR_DATA}
ExecStopPost=/bin/echo Mylar service stopped.

[Install]
WantedBy=multi-user.target
```

And then after that you should do:

```
$ sudo chown root.root /etc/systemd/system/mylar.service
$ sudo chmod 644 /etc/systemd/system/mylar.service
$ sudo systemctl daemon-reload
$ sudo systemctl enable mylar.service
```
And that should be it.

From that point, you should be able to start the service with

`$ sudo service mylar start`

And it should also restart by itself if you reboot.

systemd is supposed to be backward compatible with upstart and sysv init scripts so there might be an easier way. If you know such a way or see problems with this script your help would be appreciated.

**Comment by bebetech** [comment]
Thanks. Didn't work for me though. Is there a way to be able to debug on my system?

**Comment by dannyhanes** [comment]
Give this a shot. I cloned the repo to /opt/mylar. Be sure to change username to your actual username. 

```
[Unit]
Description=Mylar - Comic book downloader

[Service]
Type=forking
User=username
Group=username
ExecStart=/usr/bin/python /opt/mylar/Mylar.py --daemon --datadir=/opt/mylar --config=/opt/mylar/config.ini --quiet --nolaunch
GuessMainPID=no

[Install]
WantedBy=multi-user.target
```
