### ISSUE TITLE
Recent group of comics downloading repeatedly

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#993]
Now it seems that the latest comics are downloading and processing (successfully) over and over and over again.

![screen shot 2015-04-26 at 7 29 04 am](https://cloud.githubusercontent.com/assets/97095/7337676/37faf974-ebe7-11e4-8e7b-80369f1a4924.png)

**Comment by AtariBaby** [comment]
Hasn't occurred for30 minutes

**Comment by evilhero** [comment]
If you've hit the Force Search option multiple times, it queues them up in sequence. Only one will run at a time, so the first will run and complete, and then, if you had hit the Force Search again, it would run that and so on.. If you have a huge wanted list, with indexer delays and processing it could take a while for them to redownload. This is that cacheing problem I had mentioned awhile ago, but it had occurred with rss search running at the same time that a force search is. 

I'm going to try to fix some of this type of stuff, but they're not quick fixes usually.

**Comment by AtariBaby** [comment]
no biggie!
