### ISSUE TITLE
[READLIST] Cannot locate IssueID - aborting..

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#995]
```[READLIST] Cannot locate IssueID - aborting..```
The above error is logged any time I attempt to add a comic to my reading list.  I've tried several different comics from different series and they all give this same error.  These are all comics that were added and tagged successfully by Mylar.  I also noticed hundreds of the following in Mylar.log:

```
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] issueID to write to db:485564
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] temploc: 077
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] [235524] Issue match - fcdigit: 77000 ... int_iss: 77000
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] Matched...issue: The Walking Dead#77 --- 77000
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filename: The Walking Dead #077 - (2010).cbz
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filesize: 20952741
27-Apr-2015 20:09:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] issueID to write to db:235524
```

**Comment by evilhero** [comment]
The readinglist error I've already fixed as I encountered it myself a few days ago and just haven't had a chance to push it out - will be in the next development commit up very shortly.

As far as the invalid numeric, I'd have to see what was in the log prior to those errors, as it looks like it's passing the function a non-numeric character (it looks like a space). The only thing I can see from your post is the filename might be a problem - the '#077 - (2010)' portion, well the '-' and then having nothing after it. Since Mylar removes the brackets when doing comparisons, I think it expects there to be something after the '-', normally it's an issue title and it's coming back with nothing.

I can fix it, but if you could confirm/paste the portion of the log just above that so I can see what the issnum is being passed, it should be a farily easy fix ;)

**Comment by bonebox** [comment]
That one just got pruned out.  Here's the top and bottom for a different one. Let me know if this isn't what you need.

```
27-Apr-2015 20:37:19 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] [106800] Issue match - fcdigit: 18000 ... int_iss: 18000
27-Apr-2015 20:37:19 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] Matched...issue: The Walking Dead#18 --- 18000
27-Apr-2015 20:37:19 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filename: The Walking Dead #018 - (2005).cbz
27-Apr-2015 20:37:19 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filesize: 6218457
27-Apr-2015 20:37:19 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] issueID to write to db:106800
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] temploc: micho
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [] Invalid numeric for issue - cannot be found. Ignoring.
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : this does not have an issue # that I can parse properly.
[trimmed spam...]
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] issueID to write to db:485564
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] temploc: 077
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] [235524] Issue match - fcdigit: 77000 ... int_iss: 77000
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] Matched...issue: The Walking Dead#77 --- 77000
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filename: The Walking Dead #077 - (2010).cbz
27-Apr-2015 20:37:20 - DEBUG   :: CP Server Thread-4 : [FILE-RESCAN] .......filesize: 20952741
```

**Comment by evilhero** [comment]
Oh, ok I see - you must have a filename in that directory that doesn't have an issue number in the filename or it does and it either starts with 'micho', or most likely it's something like 'The Walking Dead Micho....'?

**Comment by bonebox** [comment]
Yep, it's named "The Walking Dead - Michonne Special #001 - Michonne Special (2012).cbr".

**Comment by evilhero** [comment]
It's parsing it against the series title in the directory so it's warning it can't determine the issue because it basically doesn't belong in that directory ;) 

If you add it as  an annual type it might  suppress the errors, but I'm not 100% sure even if the add would work (enable annuals in the configuration, then refresh the series, then a green arrow appears at bottom right of series page, enter in the ComicID from comicvine to that particular special and see if it adds ok.

**Comment by bonebox** [comment]
I went ahead and just separated the specials into their own folder.  Thanks!

**Comment by bonebox** [comment]
Hmm, I updated to https://github.com/evilhero/mylar/commit/e58f17f958423af552fadd318021af897d572541 and restarted, but still get the same `[READLIST] Cannot locate IssueID - aborting..` error in the log.

**Comment by evilhero** [comment]
How are you trying to add to the readlist? Via the series detail page or having it auto add on a weekly pull list?

**Comment by bonebox** [comment]
Clicking the icon from the series detail page.  I do have it enabled to auto-add, but haven't had a chance to see if that works yet.

**Comment by evilhero** [comment]
That was working before but it's possible that a recent commit broke it again. I only tested against the pullist, and actually forgot about the icon option :(

I'll get it fixed later today when I can get to a machine.

**Comment by bonebox** [comment]
No worries, thanks!

**Comment by evilhero** [comment]
This is a real easy fix, it's just not ordering the issueid variable. I'm going to commit up a fix shortly using my phone (yay technology!)
