### ISSUE TITLE
Rate limit for API hits

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#996]
NZB.su just instituted a once-per-second rate limit on the API, which causes searches to predictably bail out. 

Can we get a feature added for per-search-provider API delay, in seconds?

**Comment by evilhero** [comment]
Unless it's been code-hacked, by default mylar should only send one api request / 60s to any given nzb provider (local newznab installations are bypassed). I'm sure they count the rss hit in there too, but that's once/20 mins by default. 

Does yours hit more frequently than 1/60?

**Comment by ForumFerret** [comment]
Hmmm. I guess what I'm seeing in the logs was a 0-second-to avoid hammering message; it LOOKED like it was searching more than once per second but if it's 1 per 60s then I think we're good. Thanks for the clarification, EH!
