### ISSUE TITLE
Invincible Series causes Uncaught Exceptions and ComicRN.py to freeze

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#998]
Hi! I love Mylar.

Anyway, I get tracebacks and uncaught exceptions every time I try to do anything with the Invincible series.  I have all 119 issues in the folder and it shows them all downloaded.  On the summary page, it shows 0/119.  If I do a refresh or a folder recheck, I get tracebacks.  When SABnzbd tries to post-process, it hangs the client on the script.  Is there anything I should know about this particular series?  I can provide any logs that are required to check.

Thanks in advance, evilhero!

**Comment by evilhero** [comment]
Can you post the traceback error you're getting? I happen to have this series in my watchlist, and haven't had any issues - just tried doing a Refresh and a manual post-process for the lastest issue and it went through without any errors.

If I were to hazard a guess on this, it's probably likely that you have a filename in that directory that is causing the traceback error. The tracebacks are happening at the end of the file recheck, or at the end of the post-processing (as It shows them all as Downloaded) - but the last step in both of those portions is to update the totals accordingly. This is just a guess, posting the traceback error would either confirm this or not ;)

**Comment by bguidotti** [comment]
Sure - probably one of my files, then.  I hadn't considered that!

30-Apr-2015 16:27:41 - INFO :: Thread-74 : [FILE-RESCAN] Now checking files for
Invincible (2003) in y:\comics\Invincible (2003)
30-Apr-2015 16:27:44 - ERROR :: Thread-74 : Uncaught exception: Traceback (most
recent call last):
  File "c:\users\bruce\documents\github\mylar\mylar\logger.py", line 159, in new
_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\bruce\documents\github\mylar\mylar\updater.py", line 754, in fo
rceRescan
    tmpval = filechecker.listFiles(dir=rescan['ComicLocation'], watchcomic=resca
n['ComicName'], Publisher=rescan['ComicPublisher'], AlternateSearch=altnames)
  File "c:\users\bruce\documents\github\mylar\mylar\filechecker.py", line 153, i
n listFiles
    subname = re.sub(subit, '', subname)
  File "c:\python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\python27\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
error: unbalanced parenthesis

Traceback (most recent call last):
  File "c:\users\bruce\documents\github\mylar\mylar\logger.py", line 159, in new
_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\bruce\documents\github\mylar\mylar\updater.py", line 754, in fo
rceRescan
    tmpval = filechecker.listFiles(dir=rescan['ComicLocation'], watchcomic=resca
n['ComicName'], Publisher=rescan['ComicPublisher'], AlternateSearch=altnames)
  File "c:\users\bruce\documents\github\mylar\mylar\filechecker.py", line 153, i
n listFiles
    subname = re.sub(subit, '', subname)
  File "c:\python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\python27\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

**Comment by evilhero** [comment]
Can you post the contents of the mylar.log file showing from the FILE-RESCAN Now checking files.., up until the error? The mylar.log file holds all the debugging information so I need to see that to figure it out a it more. 

Have you restarted mylar since the error occurred, and it's consistent after reboots?

**Comment by bguidotti** [comment]
It is consistent after reboots.
I even deleted the series a while back and re-added it with the same problems.

It seems to say every single file has an invalid filename at first.
Then it gets to 66:

30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] subname no brackets: Invincible 066 
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] AS_Alt : ['None']
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] watchcomic:Invincible ..comparing to found file: Invincible 066
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] Complete matching list of names to this file [1] : ['Invincible']
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] AS_Tuple : []
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] Invincible - watchlist match on : y:\comics\Invincible (2003)\Invincible 066 (2009) (c2c) (Victorian-DCP).cbr
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] cchk is : Invincible
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] we should remove 0 characters
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] nonocount [0] cchk [Invincible] length [10]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] final jtd_len to prune [10]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] before title removed from FILENAME [Invincible 066 (2009) (c2c) (Victorian-DCP).cbr]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] after title removed from FILENAME [ 066 (2009) (c2c) (Victorian-DCP).cbr]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] creating just the digits using SUBNAME, pruning first [10] chars from [Invincible 066]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] after title removed from SUBNAME [066]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] JUSTTHEDIGITS [066]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] final justthedigits [066]
30-Apr-2015 16:47:19 - DEBUG   :: Thread-75 : [FILECHECKER] volume indicator detected as version #:Voltage).cbr
30-Apr-2015 16:47:19 - ERROR   :: Thread-75 : Uncaught exception: Traceback (most recent call last):
  File "c:\users\bruce\documents\github\mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\bruce\documents\github\mylar\mylar\updater.py", line 754, in forceRescan
    tmpval = filechecker.listFiles(dir=rescan['ComicLocation'], watchcomic=rescan['ComicName'], Publisher=rescan['ComicPublisher'], AlternateSearch=altnames)
  File "c:\users\bruce\documents\github\mylar\mylar\filechecker.py", line 153, in listFiles
    subname = re.sub(subit, '', subname)
  File "c:\python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\python27\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
error: unbalanced parenthesis

**Comment by evilhero** [comment]
Do you have a filename in that directory that contains the word 'Voltage'?  It looks like that particular filename is causing the errors, as well as the invalid filename messages your getting (most likely). It's assuming 'Voltage' is actually 'Vol' and trying to parse it out unsuccessfully. I'll have to code on a fix for that if that's the case. 

Can you paste that filename in here so I can see what it looks like? It might be as simple as removing that issue from the directory until I can get the fix up.

**Comment by bguidotti** [comment]
Ah hah!
That is why...
A goofy combination of contributor names:
Invincible 068 (2010) (Minutemen-High Voltage).cbr

I re-named the file, and it works fine.
I can put it back to test code if you need me to.

Thanks!

**Comment by evilhero** [comment]
No need to put it back, I now know the name of the file, so that's all I need to fix the code. 

And it's most definitely related to the lockup. When mylar does a post-processing, the very last thing it does before it tells sabnzbd that it was successful or not is to do a file check on the series. If that gets a traceback error or doesn't complete then sabnzbd just sits waiting for a response and never gets it. 

I'll reference this issue when the commit goes up with the fix so you'll know it's available. 

Cheers, and thanks for working through all of this troubleshooting ;)

**Comment by bguidotti** [comment]
Thanks so much, evilhero!
Cheers to you!

**Comment by evilhero** [comment]
This should be fixed - it went in a few commits ago, but I forgot to reference this issue in the commit...

**Comment by bguidotti** [comment]
This is closed.
